### ISSUE TITLE
LND RPC crashing on startup

### ISSUE THREAD

**Issue by katatoniq** [lightningnetwork/lnd#2695] opened 2019-02-24 13:28 UTC
### Background

Lightning Network Daemon crashing on startup after running without problems for over a month.

I do have a symbol in my password, which a brief googling suggested may be an issue but hasn't been so far...?

### Your environment

* LND 0.5
* Raspbian on Rasperry Pi 3 B+
* bitcoind 0.17.1

### Behaviour

`-- Logs begin at Fri 2016-11-04 04:16:50 AEDT. --

Feb 22 16:02:47 xxx systemd[1]: Started LND Lightning Daemon.

Feb 22 16:02:48 xxx systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

Feb 22 16:02:48 xxx systemd[1]: lnd.service: Unit entered failed state.

Feb 22 16:02:48 xxx systemd[1]: lnd.service: Failed with result 'exit-code' .

Feb 22 16:03:48 xxx systemd[1]: lnd.service: Service hold-off time over, sc heduling restart.

Feb 22 16:03:48 xxx systemd[1]: Stopped LND Lightning Daemon.

Feb 22 16:03:48 xxx systemd[1]: Started LND Lightning Daemon.

Feb 22 16:03:48 xxx systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

Feb 22 16:03:48 xxx systemd[1]: lnd.service: Unit entered failed state.

Feb 22 16:03:48 xxx systemd[1]: lnd.service: Failed with result 'exit-code'`

**Comment by Roasbeef** [comment] 2019-02-24 19:42
Do you have the `stderr` or `stdout` output?

**Comment by katatoniq** [comment] 2019-02-25 01:51
This popped up:

panic: illegam"▒ase64 data at in`ut`Byte 225

goroutine 1 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/btcec.initS256()
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/btcec/btcec.go:928 +0x484
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/btcec.initAll()
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/btcec/btcec.go:892 +0x14
sync.(*Once).Do(0x1314378, 0xaedcd4)
        /usr/local/go/src/sync/once.go:44 +0xb8
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/btcec.S256(0x8c6620)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/btcec/btcec.go:956 +0x24

**Comment by Roasbeef** [comment] 2019-02-28 15:46
Does this happen each time you start up?

**Comment by Roasbeef** [comment] 2019-03-05 22:50
Unable to reproduce, closing for now.

**Closed by Roasbeef** 2019-03-05 22:50 UTC

**Comment by jrwagh333** [comment] 2019-03-18 14:38
I am also now experiencing this issue. Everything was working fine and then one day I can no longer unlock the wallet without it crashing within a few minutes.

Your environment

    LND 0.5.2
    Raspbian on Rasperry Pi 3 B+
    bitcoind 0.17.1

**Behavior**
Mar 18 14:23:56 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 14:23:56 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Mar 18 14:23:56 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Mar 18 14:24:56 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Mar 18 14:24:56 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Mar 18 14:24:56 RaspiBolt systemd[1]: Started LND Lightning Daemon.

**Logs from earlier:**
2019-03-18 11:30:40.469 [INF] UTXN: Attempting to graduate height=567626: num_kids=0, num_babies=0 unexpected fault address 0x61ca7008 fatal error: fault [signal SIGBUS: bus error code=0x2 addr=0x61ca7008 pc=0x212c88]

**lncli getinfo:**
2019-03-18 11:30:40.469 [INF] UTXN: Attempting to graduate height=567626: num_kids=0, num_babies=0 unexpected fault address 0x61ca7008 fatal error: fault [signal SIGBUS: bus error code=0x2 addr=0x61ca7008 pc=0x212c88]

**Comment by halseth** [comment] 2019-03-19 12:33
@jrwagh333 Your crash looks unrelated. Can you open a new issue, with the crash logs attached? Thanks!
