### ISSUE TITLE
CLN interoperability: cooperative close attempt resulted in unilateral close

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6599] opened 2022-05-31 12:35 UTC
Also see https://github.com/ElementsProject/lightning/issues/5295

### Background

My peer "zero fee routing" (running CLN 0.11.1) attempted to cooperatively close the channel to my node (running lnd 0.15.0-beta.rc3). This resulted in a unilateral close. At this time, the channel had several active/pending HTLCs.

CLN logs:
```
2022-05-31T12:20:22.034Z UNUSUAL 027ce055380348d7812d2ae7745701c9f93e70c1adeb2657f053f91df4f2843c71-chan#4233: Peer permanent failure in CHANNELD_SHUTTING_DOWN: channeld: received ERROR error channel a97b201f22165254e8035c22f5051f37470208e5248d80bce57871bc684565cd: link failed to shutdown
```

lnd logs:

```
2022-05-31 14:20:19.089 [DBG] HSWC: ChannelLink(cc654568bc7178e5bc808d24e5080247371f05f5225c03e8545216221f207ba9:1): queueing keystone of ADD open circuit: (Chan ID=0:0:0, HTLC ID=8175304)->(Chan ID=733084:270:1, HTLC ID=219854)
2022-05-31 14:20:19.168 [DBG] HSWC: ChannelLink(cc654568bc7178e5bc808d24e5080247371f05f5225c03e8545216221f207ba9:1): removing Add packet (Chan ID=0:0:0, HTLC ID=8175304) from mailbox
2022-05-31 14:20:22.240 [INF] HSWC: ChannelLink(cc654568bc7178e5bc808d24e5080247371f05f5225c03e8545216221f207ba9:1): stopping
2022-05-31 14:20:22.240 [INF] HSWC: ChannelLink(cc654568bc7178e5bc808d24e5080247371f05f5225c03e8545216221f207ba9:1): exited
2022-05-31 14:20:52.925 [DBG] NANN: Marking channel(cc654568bc7178e5bc808d24e5080247371f05f5225c03e8545216221f207ba9:1) pending-inactive
```

```
2022-05-31 14:20:22.039 [INF] PEER: unable to read message from 038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5@167.235.3.234:51448: EOF
2022-05-31 14:20:22.039 [INF] PEER: disconnecting 038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5@167.235.3.234:51448, reason: read handler closed
```

```
2022-05-31 14:20:22.030 [ERR] PEER: failed link shutdown: link failed to shutdown
2022-05-31 14:20:22.030 [ERR] PEER: Unable to respond to remote close msg: link failed to shutdown
```

### Your environment

* version of `lnd`: 0.15.0-beta.rc3
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

Have channel with CLN peer. Have active/pending HTLCs. Initiate cooperative close from CLN.

### Expected behaviour

Channel is disabled (peer disconnects?) and then closed once the HTLCs time out/settle/fail.

### Actual behaviour

Immediate unilateral close triggered by CLN.

**Comment by Crypt-iQ** [comment] 2022-05-31 17:03
This has to wait on the spec issue before we can make progress, but I think it's close

**Comment by C-Otto** [comment] 2022-05-31 17:23
Could you provide a link?

**Comment by Crypt-iQ** [comment] 2022-05-31 17:45
https://github.com/lightning/bolts/pull/970

**Comment by alexbosworth** [comment] 2022-06-01 00:25
could be related to https://github.com/lightningnetwork/lnd/issues/6039

**Comment by Crypt-iQ** [comment] 2022-06-01 17:01
Dupe of #6039

**Closed as completed by Crypt-iQ** 2022-06-01 17:01 UTC
