### ISSUE TITLE
force closed htlcs not swept past stage 2 by nursery 

### ISSUE THREAD

**Issue by engenegr** [lightningnetwork/lnd#1305] opened 2018-05-31 08:06 UTC
### Background

I would be grateful if somebody experienced could explain what happened with channel. I had one hung payment and then Bitrefill closed my channel. I fugured out that some of my funds are locked in the same time Bitrefill returned partially my channel funds. 

It is pendingchannels [output pastebinit](http://paste.debian.net/1027379/)

`
{
    "total_limbo_balance": "96688",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed",
                "channel_point": "30c95867e533ea7d5bf44dde8758411bfca4a2c726296ac3b3259919898eb754:1",
                "capacity": "200000",
                "local_balance": "100973",
                "remote_balance": "0"
            },
            "closing_txid": "147a20624d0a79266cd120f6e6cd4e11c542634d45bd83958a4d738e33ef60f4",
            "limbo_balance": "96688",
            "maturity_height": 525215,
            "blocks_til_maturity": -26,
            "recovered_balance": "100973",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "96688",
                    "outpoint": "2c4cc30b45d5f8a3673c99fb3e314406770d65d2b9d6aaf2b4097ff59ca60bb3:0",
                    "maturity_height": 525225,
                    "blocks_til_maturity": -16,
                    "stage": 2
                }
            ]
        }
    ],
    "waiting_close_channels": [
    ]
}
`
### Your environment

* version of `lnd` 0.4.2-beta
* Linux armv71 (raspbian)
* bitcoind Core 0.16.0.0

### Steps to reproduce
Probably, irreproducible 

1. Create channel with Bitrefill (minimum funds).
2. Try to pay Blockstream store. It couldn't find a route.
3. Wait one day. Then it probably would find a route to BS store.
4. Try to send money via payment request.
5. Figure out that there's no route really. Payment hangs. 
6. Request expires.  "pending_htlcs" does not change.
7. On the day two node close channel for an unknown reason.
8. Day three. Funds partially restored, but  "pending_htlcs" stays and channel is not fully closed.

### Expected behaviour

I do not know. It should close anyway and funds should return (exclude all fees)

### Actual behaviour

Tell us what happens instead

see Steps to reproduce

**Comment by Roasbeef** [comment] 2018-05-31 22:52
The channel was force closed by your node it looks like. If a large HTLC times out, then we'll go to chain in order to sweep the funds. It looks like all the funds in the channel have been swept, other than that HTLC. 

The HTLC has been spent to the second layer: https://www.smartbit.com.au/tx/2c4cc30b45d5f8a3673c99fb3e314406770d65d2b9d6aaf2b4097ff59ca60bb3. So at this point, we should sweep after the CSV has expired. 

Can you give us a set of logs searching for `UTXN` and `CNCT` within the set of logs? Also which debug level were you at?

**Comment by engenegr** [comment] 2018-06-01 07:42
Yes, they have.

If HTLC has been spent, what should I do? Can I ensure whether or not it was received by destination?

I have launched node with --debuglevel=debug, but haven't seen any files associated with lnd in /var/log. Where it saves logs? I can post them if it will help us.

**Comment by Roasbeef** [comment] 2018-06-01 20:07
The logs are in `lnd`'s data directory. On linux, it's found at `~/.lnd` .

**Comment by Roasbeef** [comment] 2018-06-04 23:20
What about `UTXN`? If you restart, they should print out their normal on start up diagnostic information, which should help us figure out why the transaction hasn't been broadcast. You can also search for `LNWL` which'll give us even more information, thanks!

**Comment by engenegr** [comment] 2018-06-05 09:21
`cat lnd.log | grep UTXN` output

> 2018-06-04 15:31:16.033 [INF] UTXN: Attempting to graduate height=525964: num_kids=0, num_babies=0
2018-06-04 15:31:20.905 [INF] UTXN: NurseryReport: building nursery report for channel 30c95867e533ea7d5bf44dde8758411bfca4a2c726296ac3b3259919898eb754:1
2018-06-04 15:31:24.528 [INF] UTXN: Attempting to graduate height=525965: num_kids=0, num_babies=0
2018-06-04 15:31:31.770 [INF] UTXN: Attempting to graduate height=525966: num_kids=0, num_babies=0
2018-06-04 15:31:41.582 [INF] UTXN: Attempting to graduate height=525967: num_kids=0, num_babies=0
2018-06-04 15:45:27.194 [ERR] UTXN: Notification chan closed, can't advance 1 graduating outputs
2018-06-04 15:46:00.956 [INF] UTXN: UTXO nursery shutting down

**Comment by juscamarena** [comment] 2018-06-06 18:40
Seeing the same thing here:

        {
            "channel": {
                "remote_node_pub": "03deedbfee762a68a44d2587560507e513ac185908728aaf053ad4a3c096d8acb0",
                "channel_point": "69c5d6bc5de0723a7e8e13a35719d03406b0f9f0bcc4722869a8685511b8f588:0",
                "capacity": "1000000",
                "local_balance": "273782",
                "remote_balance": "0"
            },
            "closing_txid": "7fb2ac8a6991f2b6511a8f92ea38bd3c0a54fcf07756a27da2505d33d25d5398",
            "limbo_balance": "23196",
            "maturity_height": 526138,
            "blocks_til_maturity": -186,
            "recovered_balance": "273782",
            "pending_htlcs": [
                {
                    "incoming": false,
                    "amount": "23196",
                    "outpoint": "461687e6fe59b5408de8531e8cc7398134ee03bee67cacc4105fd2e8f79bc6b7:0",
                    "maturity_height": 526148,
                    "blocks_til_maturity": -176,
                    "stage": 2
                }
            ]
        }

**Comment by Roasbeef** [comment] 2018-06-06 22:20
@engenegr so looks like the HTLC was properly passed off to the nursery. Do you have logs for the nursery on start up?

**Comment by Roasbeef** [comment] 2018-06-06 22:21
@juscamarena same q's as above.

**Comment by Roasbeef** [comment] 2018-06-06 22:29
@engenegr you should see something like `Incubating Channel(30c95867e533ea7d5bf44dde8758411bfca4a2c726296ac3b3259919898eb754:1)` when the  channel was originally handed off. 

Also is your `bitcoind` node remote or local? Also can you also check the logs which weren't rotated?

**Comment by engenegr** [comment] 2018-06-07 14:16
@Roasbeef 
grepping for "Incubating Channel" does not provide any output.

My bitcoind node is local and operating on the same RPi. 

I've checked all logs in ~/.lnd/logs/bitcoin/mainnet. No results.

**Comment by juscamarena** [comment] 2018-06-07 14:59
No incubating here: https://paste.ubuntu.com/p/4SJPp8rnrY/

I've grepped all the outpoint output 

	cat .lnd/logs/bitcoin/mainnet/lnd.log | grep '69c5d6bc5de0723a7e8e13a35719d03406b0f9f0bcc4722869a8685511b8f588' -A 20 -B 20

**Comment by Roasbeef** [comment] 2018-06-08 00:52
Check your rotated logs.

**Comment by Roasbeef** [comment] 2018-06-08 00:55
```
2018-06-07 04:05:12.507 [INF] CNCT: *contractcourt.htlcTimeoutResolver(461687e6fe59b5408de8531e8cc7398134ee03bee67cacc4105fd2e8f79bc6b7:0): waiting second-level tx (txid=461687e6fe59b5408de8531e8cc7398134ee03bee67cacc4105fd2e8f79bc6b7) to be fully confirmed
2018-06-07 04:05:12.507 [INF] NTFN: New confirmation subscription: txid=461687e6fe59b5408de8531e8cc7398134ee03bee67cacc4105fd2e8f79bc6b7, numconfs=1
```

You sure the node is getting confirmation notifications? This has already confirmed, but it looks like it isn't yet handing it off to the nursery. @juscamarena

**Comment by Roasbeef** [comment] 2018-06-08 00:56
@engenegr a similar q there as you're in the same position. If you can restart and filter out in the logs everything but `CNCT, NTFN, LNWL, UTXN`, then we should be able to see what's waiting for what.

**Comment by engenegr** [comment] 2018-06-08 07:33
@Roasbeef 

I did the filtering for all logs I have in .lnd

Here, http://paste.debian.net/1028426/

**Comment by Roasbeef** [comment] 2018-06-08 20:13
@engenegr are these logs _right_ after a start up? That's what we need to narrow down the issue.

**Comment by juscamarena** [comment] 2018-06-11 15:13
https://paste.ubuntu.com/p/75y4XrKFvC/

**Comment by halseth** [comment] 2018-06-12 10:31
From the log provided by @juscamarena it looks like maybe the sweep tx (`515412e2f548c4a79cd6f4f153c6caad7ecf7e97dfbed544593c9fb1afc7fac5`) failed to get published by the UTXO nursery, as on startup it looks like it is re-registering for confirmation notifications. And the tx doesn't seem to exists on any block explorer.

We should probably attemtp to re-publish any final tx on startup?

**Comment by juscamarena** [comment] 2018-06-13 19:22
I tried running PR #1380 

It seems to actually try to sweep the funds again after a reboot!

Although I think it still doesn't propagate due to a really low fee being used of 120 sats for the sweep.

TXID 515412e2f548c4a79cd6f4f153c6caad7ecf7e97dfbed544593c9fb1afc7fac5
input of 23196 sats
txout of 23076 sats

Here are the logs running PR #1380.

https://paste.ubuntu.com/p/Kw9PpxMDsP/

**Comment by engenegr** [comment] 2018-06-14 07:30
Hi @Roasbeef,

First 140 lines of log just after the start https://pastebin.com/0Aa8Qtte

Sorry for late reply. The node works fine now and I'm trying to balance time for updating repo, compilation and gathering the data. Sometimes it's not so simple to catch logs in the right place before it starts to output channel announcements.

**Closed** 2018-06-15 23:49 UTC
Labels: HTLC, channel management
