### ISSUE TITLE
[bug]: Unable to complete chain rescan: readScript: script witness item is larger than the max allowed

### ISSUE THREAD

**Issue by zagota** [lightningnetwork/lnd#7009] opened 2022-10-10 08:38 UTC
### Background

Describe your issue here.

The node was no longer in sync
`synced_to_chain: false`

After a restart I get the following message
`Started rescan from block 00000000000000000007477b90ff0ea53cdd1db88e03799af18ff58df0cebaa7 (height 757921) for 17 addresses

[ERR] LNWL: Unable to complete chain rescan: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]`
Both nodes have the same problem. 
A new bitcoin node, same errors

### Your environment

* version of `lnd 0.15.1-beta`
* which operating system (`uname -a Linux ubnt-ln 5.15.0-48-generic` )
* version of  `bitcoind Version: 230000`
* any other relevant environment details

### Steps to reproduce

Restart Node

**Comment by guggero** [comment] 2022-10-10 08:44
Duplicate of https://github.com/lightningnetwork/lnd/issues/7002.
A hotfix is out: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.2-beta

**Closed by guggero** 2022-10-10 08:44 UTC
Labels: bug, needs triage
