### ISSUE TITLE
[bug]: Channel Transaction has over 800 confirmations but still pending and LND node failure

### ISSUE THREAD

**Issue by Megasley** [lightningnetwork/lnd#7803] opened 2023-07-03 09:23 UTC
### Background

I opened a channel a few days ago, it got confirmed the same day, but the channel hasn't showed up. It's still pending. 

Upon reviewing my logs in an effort to diagnose this problem, I've noticed that my lnd node is consistently failing and restarting on its own via systemd. Each failure incident is invariably preceded by the same log entry, implying a potential connection between this recurring log pattern and the node's instability.

This continuous failure and auto-restart sequence is quite troubling and seems to be indicative of a deeper issue within the `lnd`.

I've attached the relevant log excerpt below for reference. I would appreciate any assistance in resolving these persistent issues.

### Your environment

*version of `lnd` : v0.16.3
*operating system: ubuntu-20.04-x86_64 on a server
*backend: Bitcoin Core version v24.0.1 (pruned)

### Steps to reproduce

Initiate a channel opening transaction as usual through Thunderhub.

### Expected behaviour

The transaction is confirmed, the channel appears, and the LND continues to run as expected

### Actual behaviour
The transaction gets confirmed, but the channel remains in a "pending" state.
The LND node intermittently stops and restarts.

### Relevant Log
```
Jul 03 10:38:39 lnd[589808]: 2023-07-03 10:38:39.748 [INF] DISC: Creating new GossipSyncer for peer=027e05064da4abbe0b6655819867aeca327e2865a22594383ab3a204a3475a843f
Jul 03 10:38:39 lnd[589808]: 2023-07-03 10:38:39.749 [INF] HSWC: ChannelLink(8966cf22ad3abc4a7eb362f6d32040200ef0ed9a25198b5817cf3554c2094257:1): received re-establishment message from remote side
Jul 03 10:38:48 lnd[589808]: 2023-07-03 10:38:48.626 [INF] WTCL: (anchor) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
Jul 03 10:38:48 lnd[589808]: 2023-07-03 10:38:48.627 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
Jul 03 10:38:56 lnd[589808]: 2023-07-03 10:38:56.633 [INF] NTFN: Historical spend dispatch finished for request outpoint=6310df9b5ea48533c67965db43f957357e9eba230beb917cce1bcb5761b24eb2:0, script=0 0ffc7719879896d3d20a81f3fe25b21b7669b275442dd209fe379f74665d7707 (start=796029 end=796988) with details: 43d7f9ec080970d9ae3d4470b80866c523550c95ebb75bf81c24f5c4dba6d5f1[0] spending 6310df9b5ea48533c67965db43f957357e9eba230beb917cce1bcb5761b24eb2:0 at height=796029
Jul 03 10:38:56 lnd[589808]: 2023-07-03 10:38:56.652 [INF] NTFN: Dispatching confirmed spend notification for outpoint=6310df9b5ea48533c67965db43f957357e9eba230beb917cce1bcb5761b24eb2:0, script=0 0ffc7719879896d3d20a81f3fe25b21b7669b275442dd209fe379f74665d7707 at current height=796991: 43d7f9ec080970d9ae3d4470b80866c523550c95ebb75bf81c24f5c4dba6d5f1[0] spending 6310df9b5ea48533c67965db43f957357e9eba230beb917cce1bcb5761b24eb2:0 at height=796029
Jul 03 10:38:56 lnd[589808]: panic: runtime error: index out of range [1] with length 0
Jul 03 10:38:56 lnd[589808]: goroutine 1599 [running]:
Jul 03 10:38:56 lnd[589808]: github.com/lightningnetwork/lnd/contractcourt.isPreimageSpend(...)
Jul 03 10:38:56 lnd[589808]:         github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:255
Jul 03 10:38:56 lnd[589808]: github.com/lightningnetwork/lnd/contractcourt.(*htlcTimeoutResolver).Resolve(0xc001b4b400)
Jul 03 10:38:56 lnd[589808]:         github.com/lightningnetwork/lnd/contractcourt/htlc_timeout_resolver.go:281 +0x2a9
Jul 03 10:38:56 lnd[589808]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).resolveContract(0xc001c28840, {0x2258ac0?, 0xc001b4b400})
Jul 03 10:38:56 lnd[589808]:         github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:2371 +0x2a9
Jul 03 10:38:56 lnd[589808]: created by github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).launchResolvers
Jul 03 10:38:56 lnd[589808]:         github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:1376 +0xd2
Jul 03 10:38:56 systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 03 10:38:56 systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 03 10:39:56 systemd[1]: lnd.service: Scheduled restart job, restart counter is at 7.
Jul 03 10:39:56 systemd[1]: Stopped Lightning Network Daemon.
```

**Comment by ffranr** [comment] 2023-07-03 20:02
I've brought this to the attention of the team.

**Comment by Megasley** [comment] 2023-07-04 07:10
Thank you @ffranr 

I'm not sure, but I will reach out to him.

**Comment by blckbx** [comment] 2023-07-04 07:20
If `027e05064da4abbe0b6655819867aeca327e2865a22594383ab3a204a3475a843f` is the peer, feature bits are telling they're likely running LND.

**Comment by Megasley** [comment] 2023-07-04 12:51
@ffranr I have confirmed. He's running `lnd`

**Comment by ffranr** [comment] 2023-07-04 13:54
@Megasley , I've been told by @yyforyongyu that the first commit in PR https://github.com/lightningnetwork/lnd/pull/7615 should stop the daemon from panicking when encountering this problem. But we do not yet know the root cause.

**Comment by Megasley** [comment] 2023-07-04 14:22
Thank you @ffranr.

However, that's not the channel in question. This is the txid of the channel opening transaction: ddecc4cf5b5f311581e137c0c2fb1743f58bd83cd46df9b388c784460caf0575

Also, the channel status is still pending on my side, despite being confirmed.

**Comment by ffranr** [comment] 2023-07-04 14:35
Thanks for the response. Opening transaction: https://mempool.space/tx/ddecc4cf5b5f311581e137c0c2fb1743f58bd83cd46df9b388c784460caf0575

**Comment by Megasley** [comment] 2023-07-05 04:20
What do you suggest I do at this point?

@ffranr

**Comment by ziggie1984** [comment] 2023-07-05 16:34
Could you switch back to a full-node ? I have the feeling that your prunded not caused this issue. Your node seems to be running again, you are NigeriaRouting or?

**Comment by Megasley** [comment] 2023-07-06 07:57
Thanks @ziggie1984 .
Yes, it's NigeriaFreeRouting. The problem is, it's stoping and restarting on it's own. And the log before it stops is the one I provided above.

@ffranr any update for me?

**Comment by ffranr** [comment] 2023-07-06 16:12
@Megasley do you have access to the lnd source code? If so, one possible solution is to apply these changes: https://github.com/lightningnetwork/lnd/pull/7811 and build a new lnd binary.

```shell
git clone https://github.com/lightningnetwork/lnd
cd lnd
git remote add upstream https://github.com/lightningnetwork/lnd
pr=7811
git fetch upstream pull/$pr/head:code-review-$pr
git checkout v0.16.3-beta
git cherry-pick 0229b082692dc40a12eebf387dff66af5acce5e7
make install
```

There may be another option using this tool: https://github.com/lightninglabs/chantools

**Comment by Megasley** [comment] 2023-07-06 16:48
Thanks @ffranr 

Before I try. Would this in any way affect my current LND files, especially since I didn't initially install LND from source?

**Comment by ffranr** [comment] 2023-07-06 18:13
> Would this in any way affect my current LND files

I don't think it should. But I recommend that you make a backup copy of `~/.lnd`.

You need to also ensure that `Thunderhub` ends up using the new binary. But the logs should make it obvious when that is the case.

**Comment by yyforyongyu** [comment] 2023-07-10 12:25
@Megasley What's the current status? There's a similar issue #5977, which could be resolved after re-index `bitcoind`.

**Comment by Crypt-iQ** [comment] 2023-07-10 15:42
If you want to help us debug this @Megasley, I'd suggest not running `-reindex` and then we can fix this for users in the future

**Comment by Megasley** [comment] 2023-07-10 16:37
> @Megasley What's the current status? There's a similar issue #5977, which could be resolved after re-index `bitcoind`.

Hi @yyforyongyu 

I haven't been able to apply the changes recommended by @ffranr, I keep getting errors. Not sure if it has anything to do with the fact that I installed lnd binary initially.

**Comment by Megasley** [comment] 2023-07-10 16:39
> If you want to help us debug this @Megasley, I'd suggest not running `-reindex` and then we can fix this for users in the future

I'm not sure I understand what you mean. @Crypt-iQ

**Comment by Crypt-iQ** [comment] 2023-07-10 16:45
A few questions:
- how long has the bitcoind node been running? have you upgraded from an older version recently?
- what does your bitcoind config look like?
- what is your bitcoind's `-prune` value?
- if you run `bitcoin-cli getrawtransaction` on recent transactions, do they have witness data when passed into `bitcoin-cli decoderawtransaction`?

**Comment by Megasley** [comment] 2023-07-10 19:42
> A few questions:
> 
> * how long has the bitcoind node been running? have you upgraded from an older version recently?
> * what does your bitcoind config look like?
> * what is your bitcoind's `-prune` value?
> * if you run `bitcoin-cli getrawtransaction` on recent transactions, do they have witness data when passed into `bitcoin-cli decoderawtransaction`?
> * you may have the block pruned by now, but what is the output of `bitcoin-cli getblock 00000000000000000002373fe032ae5c85228259f3b41daf0edb3da8f84a61dc`?

1. The bitcoin node has been running for 6 months now

2. This is what my bitcoin.conf file looks like 
`prune=3000
server=1
daemon=1
mainnet=1
testnet=0
blocksonly=1
fallbackfee=0.0002
rpcuser=
rpcpassword=
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333`

**Comment by Megasley** [comment] 2023-07-11 09:51
Hello @Crypt-iQ, I am still waiting for your response 🙏🏾

**Comment by ziggie1984** [comment] 2023-10-26 11:30
your problem was caused, because when running in pruned mode, we did ask our peer for the block data, but we queried for the witness-stripped data, which caused exactly your behaviour (see https://github.com/bitcoin/bitcoin/issues/28730#issuecomment-1780931226). Because this is fixed in the new btcd release I think we can close this issue.

**Closed** 2023-10-26 12:06 UTC
Labels: bug, P2, pruning
