### ISSUE TITLE
Private channel can't receive despite being notified as active.

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#3660] opened 2019-11-01 08:48 UTC
### Background

Private channel that is opened by a remote node is not ready for payment and not listed in ListChannels RPC output despite a "CHANNEL_ACTIVE" notification dispatched.

### Your environment

* lnd 0.8.0-beta with neutrino backend running on mobile.

### Steps to reproduce

* Open a private channel from a remote node (B) to a local node (A)
* Track channel activeness on node A via `SubscribeChannelEvents`
* When active:
** Generate invoice - no routing hints exist in the invoice.
** Call GetChanInfo RPC for this specific channel - error returned `[ERR] RPCS: [/lnrpc.Lightning/GetChanInfo]: edge not found`
** The call:
 ```
client.ListChannels(context.Background(), &lnrpc.ListChannelsRequest{		
		ActiveOnly:  true,
	})
```
returns empty list.

### Expected behaviour

Should have routing hints on the invoice so the channel can receive payment, should be listed in `ListChannels` and get no error from `GetChanInfo`

I think the reason is that the `CHANNEL_ACTIVE` event is dispatched immediately after channel reestablishment https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L992
And the `channel_update` message which is required for the channel to be usable only received later.

**Comment by roeierez** [comment] 2019-11-01 16:05
**Update**: When generating invoices right after channel active event is dispatched the routing hints are not added since the remote node announcement haven't been received yet.
I deduce that from the logs running in trace:
`2019-11-01 15:21:14.901 [INF] IRPC: Skipping channel 6064b72e280933a652e85efae0e16e5e0d0fa3404a85cf69017a16ba11463f3d due to counterparty 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0 being unadvertised`

**Comment by wpaulino** [comment] 2019-11-01 18:58
> 2019-11-01 15:21:14.901 [INF] IRPC: Skipping channel 6064b72e280933a652e85efae0e16e5e0d0fa3404a85cf69017a16ba11463f3d due to counterparty 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0 being unadvertised

Is the node that the channel is being opened to aware of the other channels of the node opening the channel? Hints are only added for public nodes.

**Comment by roeierez** [comment] 2019-11-01 19:33
I see that there is a gap between the channel reestablishment that triggers the CHANNEL_ACTIVE to the time the node announcement (of B) is received at the local node (A). During this gap, routing hints are not generated.
Now thinking again this behavior makes sense.
The ListChannels with ActiveOnly filter still returns empty list despite the event dispatched. Do you think it is related to the missing node in the graph as well?

**Comment by roeierez** [comment] 2019-11-01 19:36
> > 2019-11-01 15:21:14.901 [INF] IRPC: Skipping channel 6064b72e280933a652e85efae0e16e5e0d0fa3404a85cf69017a16ba11463f3d due to counterparty 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0 being unadvertised
> 
> Is the node that the channel is being opened to aware of the other channels of the node opening the channel? Hints are only added for public nodes.

yes

**Comment by roeierez** [comment] 2019-11-03 10:20
**Update**: Did some more tests and I see that `ListChannels` does not depend on the node announcement but only on the channel_update that lands shortly after the channel is reestablished.
So in fact I think it is reasonable for now, thanks for the clarifications.
Closing the issue.

**Comment by roeierez** [comment] 2019-11-03 10:44
On second thought the current behavior is still problematic for being able to receive immediately after a private channel is opened as right now the hints are only added if the remote node is seen as public which takes minutes...
What is the reason for this restriction? In my case I know the node is public and it is only a matter of time until the graph will be updated to reflect that...
As this use case is crucial for good on-boarding experience I believe it is necessary to either let the user pass routing hints manually to `AddInvoice` or ability to skip the restriction for publicity of certain nodes.
Curious to hear others opinions here and if there are better approaches to handle this case.

**Comment by wpaulino** [comment] 2019-11-04 19:54
There's actually already an issue and PR tracking this, see https://github.com/lightningnetwork/lnd/issues/2963 and https://github.com/lightningnetwork/lnd/pull/3022. Will close this as a duplicate of https://github.com/lightningnetwork/lnd/issues/2963.

**Closed by wpaulino** 2019-11-04 19:54 UTC
