### ISSUE TITLE
lncli listinvoices - auto-remove expired, list settled only

### ISSUE THREAD

**Issue by aggroLINUS** [lightningnetwork/lnd#2015] opened 2018-10-08 03:09 UTC
### Background

it would be more than nice, if LND would remove unsettled expired invoices. this blows up the database for no reason.

also a lncli listinvoices call to show recently settled would be very useful.

thanks for your hard work guys.

**Comment by Roasbeef** [comment] 2018-10-08 05:01
Closing as duplicate of #1404.

**Closed** 2018-10-09 02:06 UTC
