### ISSUE TITLE
[feature]: backup latest force-close tx into backup

### ISSUE THREAD

**Issue by starius** [lightningnetwork/lnd#7791] opened 2023-06-25 14:50 UTC
**Is your feature request related to a problem? Please describe.**

Imagine that a node is permanently broken and I have to recover funds from backup. I regularly backup channel.backup to many places, since it is a small file.

But some nodes can go down or be unresponsive to attempts to close the channels using the backup file.

I think it is not great, that recovery of my funds depends solely on willingness to cooperate of other nodes.

**Describe the solution you'd like**

Let's make a backup for the backup :)

Let's include the latest versions of force closing transactions to the backup file in addition to existing info that is there already.

Then during the recovery I would have an option (under a flag) to broadcast latest force-close transactions for the channels whose counterpart nodes would not cooperate. 

Possible optimization (under a flag): do it only for inactive channels or channels with suboptimal uptime. Stable channels are likely to be recoverable through the existing solution. This will reduce the frequency of updates of the backup file significantly.

**Describe alternatives you've considered**

I can use etcd to store channel db storing it on many servers. On the one hand it is more reliable, because all the servers will have the latest version. On the other hand, if all the instances are lost, we have the original problem. Another downside is that running 3-5 etcd instances is costly.

**Additional context**

I'm aware that it is risky and that if I broadcast not the latest channel force close tx, I may lose funds (if the counterpart node or watchtower turns out to be alive). But it is better than nothing! It is a choice to take the risk. Now we don't have choice. If both nodes of the channel are down, the funds are also lost. My proposal allows to recover funds in this case.

**Comment by guggero** [comment] 2023-06-26 11:13
Duplicate of https://github.com/lightningnetwork/lnd/issues/7658.

**Closed by guggero** 2023-06-26 11:13 UTC
Labels: enhancement
