### ISSUE TITLE
Need an API to delete expired unsettled invoices

### ISSUE THREAD

**Issue by saubyk** [lightningnetwork/lnd#4002] opened 2020-02-14 00:32 UTC
Need an Api to delete expired unsettled invoices.
Such invoices clutter the data and create a lot of noise in the lists.

**Comment by wpaulino** [comment] 2020-02-14 00:41
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/1404.

**Closed by wpaulino** 2020-02-14 00:41 UTC
