### ISSUE TITLE
lnd refuses to start while sweeping

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1580] opened 2018-07-18 07:33 UTC
issues sweeping when starting up:

2018-07-17 06:37:55.349 [ERR] UTXN: Failed to re-register for kindergarten sweep transaction at height=531727: -22: TX rejected: transaction 725e7b9ebf2a123586e7849e0fee604be0b89810280b57603f99e1dc8eb3c7f8 has insufficient priority (3839.404011461318 <= 5.76e+07)

2018-07-17 06:37:55.363 [ERR] FNDG: failed to handle fundingconfirmation: failed sending fundingLocked: shutting down unable to send

full log when trying to start
http://paste.ubuntu.com/p/wS6xd5sy2T/

patched it like this for the time being to make the node start up. if i remove it it refuses to start.

```
index ff190fa..14cdd39 100644
--- a/utxonursery.go
+++ b/utxonursery.go
@@ -741,7 +741,8 @@ func (u *utxoNursery) regraduateClass(classHeight uint32) error {
                        utxnLog.Errorf("Failed to re-register for kindergarten "+
                                "sweep transaction at height=%d: %v",
                                classHeight, err)
-                       return err
+//                       return err
+                       return nil;
                }
        }```

**Comment by Roasbeef** [comment] 2018-07-18 23:00
Duplicate of #1429.

**Closed by Roasbeef** 2018-07-18 23:00 UTC
