### ISSUE TITLE
[Tor] Need a way for "tor.active=1" to not route clearnet traffic through Tor

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#3100] opened 2019-05-21 08:07 UTC
I want to expose LND as a Tor service and to connect to remote Tor nodes. (inbound and outgoing connection)

I do not care about Tor privacy features, and I do not care about leaks. ([See the rational](https://medium.com/@BtcpayServer/about-tor-and-btcpay-server-2ec1e4bd5e51))

The problem is: `tor.active=1` will route all lightning traffic through Tor, and this will make clearnet traffic more unreliable.

There should have an option to route through Tor only Tor connections, leaving clearnet connection as is.

**Comment by Roasbeef** [comment] 2019-05-21 22:00
Duplicate of #2387.

**Comment by NicolasDorier** [comment] 2019-05-23 23:34
@Roasbeef consider for reopening, this is not a duplicate.
The problem is that if `tor.active=1` all outgoing traffic pass through the proxy. (even clearnet)

**Comment by inaltoasinistra** [comment] 2020-12-03 16:52
who nees this feature could achieve a part of that with the current version of lnd.
it is possible to receive incoming connections over Tor without enabling Tor in the lnd settings.
this is useful to get Tor inbound connections witout expose the IP address.

in order to achieve this you must configure a Tor hidden service in the torrc file
for example
```
HiddenServiceDir /var/lib/tor/lnd/
HiddenServicePort 9735 127.0.0.1:9735
```

in order to advertise the hidden service address put it in the `externalip` value of lnd settings.
in my example you can find the onion address in the file `/var/lib/tor/lnd/hostname`

**Comment by NicolasDorier** [comment] 2020-12-08 13:34
Our current config is:
```
tor.active=1
tor.socks=tor:9050

    listen=0.0.0.0:9735
externalip=mainnet.demo.btcpayserver.org:9735
alias=mainnet.demo.btcpayserver.org

            bitcoin.active=1
            bitcoin.mainnet=1

externalip=dppqg535s5shy5sjnsmzzrk3cdyshwau5vierujpybybboxxxglfx7id.onion:9735
noseedbackup=1
```

I don't know if all traffic is routed via Tor or not, but that's what we use.

We want to use

```
tor.active=1
tor.socks=tor:9050
```
Because we want to give our users the ability to make channel with other tor hidden services.
We don't want that all LND traffic to use Tor though.

**Comment by Kixunil** [comment] 2021-05-19 12:59
What's the status of this? This question came up lately several times in various channels (LN groups, private messages...) Would be really useful to have this resolved.

I suggest adding another option `tor.mixed=bool`, default false. Setting it to true would use tor for onion addresses only. I recommend strongly against surprising changes to the current behavior as it could silently destroy privacy of people.

**Comment by Roasbeef** [comment] 2021-05-19 23:31
Closing this as it's tracked in this issue now with an implementation path going forward: https://github.com/lightningnetwork/lnd/issues/5042

As mentioned above, it's possible to use a custom `torrc` today to achieve the same functionality.

**Closed by Roasbeef** 2021-05-19 23:31 UTC
Labels: feature request, networking, tor

**Comment by Kixunil** [comment] 2021-05-20 07:00
That `torrc` doesn't achieve the same since outgoing connections will still go through Tor. It only achieves the reverse - incoming connections being able to come from clearnet or using onion address.
