### ISSUE TITLE
SRVR: unable to create server: can't create router: ReadVarBytes: sig is larger than the max allowed size

### ISSUE THREAD

**Issue by bobwang3** [lightningnetwork/lnd#2016] opened 2018-10-08 09:08 UTC
I upgraded LND from v0.4.2-beta to v0.5-beta and found that after 'lncli unlock' for a while, LND will report an error and stop running. The error log is as follows:

_Oct  8 16:45:16 debian lnd[2954]: 2018-10-08 16:45:16.586 [INF] LNWL: Opened wallet
Oct  8 16:45:16 debian lnd[2954]: 2018-10-08 16:45:16.718 [INF] LTND: Primary chain is set to: bitcoin
Oct  8 16:45:16 debian lnd[2954]: 2018-10-08 16:45:16.757 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:29000
Oct  8 16:45:16 debian lnd[2954]: 2018-10-08 16:45:16.757 [INF] LTND: Initializing bitcoind backed fee estimator
Oct  8 16:45:16 debian lnd[2954]: 2018-10-08 16:45:16.757 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:29001
Oct  8 16:45:16 debian lnd[2954]: 2018-10-08 16:45:16.759 [DBG] LNWL: Using minimum fee rate of 253 sat/kw
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.274 [INF] LNWL: The wallet has been unlocked without a time limit
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.275 [INF] LTND: LightningWallet opened
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.320 [INF] LNWL: Started rescan from block 000000000000000000238a91fe610d2bc8d318e522490e5f76cc4e02302770eb (height 544870) for 0 addresses
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.320 [INF] LNWL: Starting rescan from block 000000000000000000238a91fe610d2bc8d318e522490e5f76cc4e02302770eb
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.459 [INF] HSWC: Restoring in-memory circuit state from disk
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.473 [DBG] LNWL: Filtering block 544871 (00000000000000000023c85124780fd82d4b45e0aff2f47c8b4d496965ceeb13) with 1914 transactions
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.481 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.522 [ERR] **SRVR: unable to create server: can't create router: ReadVarBytes: sig is larger than the max allowed size [count 171, max 80]**
Oct  8 16:45:18 debian lnd[2954]: 2018-10-08 16:45:18.523 [INF] LTND: Shutdown complete
Oct  8 16:45:18 debian lnd[2954]: can't create router: ReadVarBytes: sig is larger than the max allowed size [count 171, max 80]
Oct  8 16:45:18 debian systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Oct  8 16:45:18 debian systemd[1]: lnd.service: Unit entered failed state.
Oct  8 16:45:18 debian systemd[1]: lnd.service: Failed with result 'exit-code'._

---------------------
BTW, LND works fine at v0.4.2-beta.
Here is my lnd.conf:

_# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=debug
#debughtlc=true		//This configuration is not compatible with v0.5-beta.
maxpendingchannels=5

#alias=bno2		//The following configuration is based on the description of v0.5-beta.
alias=bno2=lncli --network=mainnet
color=#68F442

[Bitcoin]
bitcoin.active=1
#bitcoin.testnet=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6_

**Comment by Roasbeef** [comment] 2018-10-08 09:40
Which precise commit were you on before updating to 0.5?

**Comment by bobwang3** [comment] 2018-10-08 10:05
> Which precise commit were you on before updating to 0.5?

First, I deleted the /mnt/hdd/lnd after I backup.
then,
wget lnd-linux-amd64-v0.5-beta.tar.gz
wget manifest-v0.5-beta.txt
wget manifest-v0.5-beta.txt.sig
wget https://keybase.io/roasbeef/pgp_keys.asc
gpg pgp_keys.asc
gpg --import pgp_keys.asc
gpg --verify manifest-v0.5-beta.txt.sig
tar -xzf lnd-linux-amd64-v0.5-beta.tar.gz
install -m 0755 -o root -g root -t /usr/local/bin lnd-linux-amd64-v0.5-beta/*
lnd --version

su bitcoin
mkdir /mnt/hdd/lnd
ln -s /mnt/hdd/lnd /home/bitcoin/.lnd
Copy the old lnd.conf to /mnt/hdd/lnd.
exit
systemctl start lnd
After I noticed that the lnd.conf file is not compatible, I modified lnd.conf.
#debughtlc=true
#bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
#bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

That's all.
There are other minor problems, such as the problem of macaroon under root. I switch to the bitcoin user and it will be OK.

**Comment by Roasbeef** [comment] 2018-10-08 10:09
Which git commit?

**Comment by bobwang3** [comment] 2018-10-09 03:18
I don't know

**Comment by halseth** [comment] 2018-10-10 13:08
@bobwang3 Thanks for reporting this! Very interesting indeed.

Are you able to reproduce this, does it happen every time?

Can you try running it with the changes from this PR: https://github.com/lightningnetwork/lnd/pull/2030

**Comment by halseth** [comment] 2018-10-10 13:30
Also, do you have any `externalIP` set?

**Comment by Roasbeef** [comment] 2018-10-26 00:19
Closing for now due to lack of updates. Will reopen if we get additional details from the OP.

**Comment by kangoala** [comment] 2018-11-28 09:08
As mentioned by rootzoll, I have a simillar issue with my raspi blitz.
I am not an experienced user, but attached you find the log-report as already postet in https://github.com/rootzoll/raspiblitz/issues/175 

*** LND SYSTEMD STATUS ***
● lnd.service - LND Lightning Daemon
Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enab led)
Active: active (running) since Sun 2018-11-18 17:17:06 UTC; 52s ago
Main PID: 25990 (lnd)
CGroup: /system.slice/lnd.service
└─25990 /usr/local/bin/lnd --externalip=

Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.467 [INF] RPCS: passwo…8080
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.468 [INF] LTND: Waitin… it.
Hint: Some lines were ellipsized, use -l to show in full.

*** LAST 20 LND LOGS ***
-- Logs begin at Sun 2018-11-18 16:29:29 UTC, end at Sun 2018-11-18 17:17:58 UTC . --
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.243 [INF] LNWL: Started resca n from block 00000000000000000012fa399e180c25dc15425c59e846dd1fd021ca896598a8 (h eight 550406) for 24 addresses
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.253 [INF] LNWL: Starting resc an from block 00000000000000000012fa399e180c25dc15425c59e846dd1fd021ca896598a8
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.276 [INF] HSWC: Restoring in- memory circuit state from disk
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.354 [INF] HSWC: Payment circu its loaded: num_pending=0, num_open=0
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.427 [INF] HSWC: Trimming open circuits for chan_id=549963:1076:1, start_htlc_id=0
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.795 [ERR] SRVR: unable to cre ate server: can't create router: ReadVarBytes: sig is larger than the max allowe d size [count 233, max 80]
Nov 18 17:16:05 pm01 lnd[639]: 2018-11-18 17:16:05.796 [INF] LTND: Shutdown comp lete
Nov 18 17:16:05 pm01 lnd[639]: can't create router: ReadVarBytes: sig is larger than the max allowed size [count 233, max 80]
Nov 18 17:16:05 pm01 systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 17:16:05 pm01 systemd[1]: lnd.service: Unit entered failed state.
Nov 18 17:16:05 pm01 systemd[1]: lnd.service: Failed with result 'exit-code'.
Nov 18 17:17:06 pm01 systemd[1]: lnd.service: Service hold-off time over, schedu ling restart.
Nov 18 17:17:06 pm01 systemd[1]: Stopped LND Lightning Daemon.
Nov 18 17:17:06 pm01 systemd[1]: Started LND Lightning Daemon.
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.452 [INF] LTND: Version: 0. 5.0-beta commit=v0.5-beta-101-g61e867741926bcb318432a6344b80161fabd1455, build=p roduction, logging=default
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.452 [INF] LTND: Active chai n: Bitcoin (network=mainnet)
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.453 [INF] CHDB: Checking fo r schema update: latest_version=6, db_version=6
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.467 [INF] RPCS: password RP C server listening on [::]:10009
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.467 [INF] RPCS: password gR PC proxy started at 127.0.0.1:8080
Nov 18 17:17:06 pm01 lnd[25990]: 2018-11-18 17:17:06.468 [INF] LTND: Waiting for wallet encryption

**Comment by halseth** [comment] 2018-11-28 09:12
Reopening per https://github.com/lightningnetwork/lnd/issues/2016#issuecomment-442372981

**Comment by Roasbeef** [comment] 2018-11-29 01:48
What version of `lnd` are you running @kangoala ?

**Comment by kangoala** [comment] 2018-11-29 06:09
LND v0.5-beta

**Comment by wpaulino** [comment] 2018-11-29 22:49
@kangoala we'll need the actual commit hash as well. Can you post the output of `lnd --version`?

**Comment by kangoala** [comment] 2018-11-30 07:51
lnd version 0.5.0-beta commit=v0.5-beta-101-g61e867741926bcb318432a6344b80161fabd1455

**Comment by kangoala** [comment] 2018-11-30 08:10
Could this be caused by an rpc-issue?

**Comment by wpaulino** [comment] 2018-11-30 22:02
@kangoala no, this isn't RPC related.

The `ChannelRouter` fails to be created because it's unable to fetch the source node. Here are some relevant commits which could have affected this:

* https://github.com/lightningnetwork/lnd/commit/0879a7354fa236dd2f6dfaf7f54955f2270cc787
* https://github.com/lightningnetwork/lnd/commit/f5c582d8d7b6fdaca2d6114720cff4cfb55ca4ec
* https://github.com/lightningnetwork/lnd/commit/48072f8e826d9a08305ff7b53878641f463d4478
* https://github.com/lightningnetwork/lnd/commit/785efcfaa21c49ee4bd06982b4217f30c57af2e5

**Comment by kangoala** [comment] 2018-12-02 07:34
Ok, thanks for the reply and your help. 
As already mentioned, I'm not an experienced user and to me the commits doesn't explain a lot.

As far as I understood, it would be best to wait for the next release, and then start with a fresh installation. If this could be fixed easily, I could offer to do some changes in config-files to check whats going wrong. Otherwise I will just wait for the next release.

**Comment by fluidvoice** [comment] 2019-01-16 10:49
This is still happening. Can I get some feedback?
$ `lnd --version`
lnd version 0.5.1-beta commit=
https://github.com/rootzoll/raspiblitz/issues/272#issuecomment-454440716

**Comment by halseth** [comment] 2019-01-16 14:16
are you saying it sometimes is able to start, sometimes not? Looks like a db corruption maybe?

Also #2030 is merged in master, should prevent this from happening (won't help with db corruption though..)

**Comment by fluidvoice** [comment] 2019-01-16 14:22
> are you saying it sometimes is able to start, sometimes not? Looks like a db corruption maybe?
> 
> Also #2030 is merged in master, should prevent this from happening (won't help with db corruption though..)

Yeah, I was just messing with it. Stopping and restarting both the lnd.service and bitcoind.service and after a few failed attempts if finally succeeded. I turned up the debuglogging level to trace. Let me see if it shows anything interesting.  Other thoughts?

For example, at the end of this sequence it came up OK. Note the first time it did not...

> *** LND SYSTEMD STATUS ***
> ● lnd.service - LND Lightning Daemon
>    Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Wed 2019-01-16 04:04:33 PST; 43s ago
>   Process: 14792 ExecStart=/usr/local/bin/lnd --externalip=${publicIP} (code=exited, status=1/FAILURE)
>  Main PID: 14792 (code=exited, status=1/FAILURE)
> 
> Jan 16 04:04:33 thundahub systemd[1]: lnd.service: Failed with result 'exit-code'.
> 
> *** LAST 20 LND LOGS ***
> -- Logs begin at Tue 2019-01-15 17:14:20 PST, end at Wed 2019-01-16 04:05:16 PST. --
> Jan 16 04:03:50 thundahub lnd[14792]: 2019-01-16 04:03:50.890 [INF] RPCS: password RPC server listening on [::]:10009
> Jan 16 04:03:50 thundahub lnd[14792]: 2019-01-16 04:03:50.891 [INF] RPCS: password gRPC proxy started at [::]:8080
> Jan 16 04:03:50 thundahub lnd[14792]: 2019-01-16 04:03:50.891 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
> Jan 16 04:04:25 thundahub lnd[14792]: 2019-01-16 04:04:25.947 [INF] LNWL: Opened wallet
> Jan 16 04:04:26 thundahub lnd[14792]: 2019-01-16 04:04:26.410 [INF] LTND: Primary chain is set to: bitcoin
> Jan 16 04:04:26 thundahub lnd[14792]: 2019-01-16 04:04:26.446 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://*:28332
> Jan 16 04:04:26 thundahub lnd[14792]: 2019-01-16 04:04:26.446 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://*:28333
> Jan 16 04:04:26 thundahub lnd[14792]: 2019-01-16 04:04:26.446 [INF] LTND: Initializing bitcoind backed fee estimator
> Jan 16 04:04:26 thundahub lnd[14792]: 2019-01-16 04:04:26.452 [DBG] LNWL: Using minimum fee rate of 253 sat/kw
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.829 [INF] LNWL: The wallet has been unlocked without a time limit
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.838 [INF] LTND: LightningWallet opened
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.838 [DBG] LNWL: Birthday block has already been verified: height=553299, hash=0000000000000000002fb5012be16342623a11878216e6b9fc2b75cf4f702ece
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.924 [INF] HSWC: Restoring in-memory circuit state from disk
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.949 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.980 [INF] HSWC: Trimming open circuits for chan_id=557641:1467:0, start_htlc_id=0
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.980 [INF] HSWC: Trimming open circuits for chan_id=557944:1598:1, start_htlc_id=0
> Jan 16 04:04:32 thundahub lnd[14792]: 2019-01-16 04:04:32.981 [INF] HSWC: Trimming open circuits for chan_id=558507:2703:1, start_htlc_id=0
> Jan 16 04:04:33 thundahub systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
> Jan 16 04:04:33 thundahub systemd[1]: lnd.service: Unit entered failed state.
> Jan 16 04:04:33 thundahub systemd[1]: lnd.service: Failed with result 'exit-code'.
> 
> - RTL is OFF by config
> admin@thundahub:~ $ sudo systemctl stop lnd.service
> admin@thundahub:~ $ sudo systemctl stop bitcoind.service
> admin@thundahub:~ $ sudo systemctl start bitcoind.service
> admin@thundahub:~ $ sudo systemctl start lnd.service
> admin@thundahub:~ $ lncli unlock
> Input wallet password: 
> 
> lnd successfully unlocked!
> admin@thundahub:~ $ lncli unlock
> Input wallet password: 
> [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
> admin@thundahub:~ $ sudo systemctl stop lnd.service
> admin@thundahub:~ $ sudo systemctl start lnd.service
> admin@thundahub:~ $ lncli unlock
> Input wallet password: 
> 
> lnd successfully unlocked!

**Comment by fluidvoice** [comment] 2019-01-16 15:05
> are you saying it sometimes is able to start, sometimes not? Looks like a db corruption maybe?
> 
> Also #2030 is merged in master, should prevent this from happening (won't help with db corruption though..)

by merged in master do you mean that it's in my version?... **"version": "0.5.1-beta commit="**

**Comment by fluidvoice** [comment] 2019-01-16 15:37
I'm not able to consistently reproduce the problem yet. Rebooting and stopping/starting lnd.service is so far not showing the problem.

**Comment by halseth** [comment] 2019-01-17 10:19
Do you have any `externalIP` set in your config?

**Comment by halseth** [comment] 2019-01-17 12:04
@fluidvoice Would help a lot if you pasted your config file here :)

Also, if you know how to compile `lnd` yourself, you could try to repro with this patch: https://github.com/lightningnetwork/lnd/pull/2493

**Comment by fluidvoice** [comment] 2019-01-17 15:06
> @fluidvoice Would help a lot if you pasted your config file here :)
> 
> Also, if you know how to compile `lnd` yourself, you could try to repro with this patch: #2493

Compile of master progressed quite a bit but then failed towards the end of `make`

**Comment by fluidvoice** [comment] 2019-01-17 15:38
> Do you have any `externalIP` set in your config?

looks like it yes (note prob not harmful script bug creating multiple blank entries):

`cat /mnt/hdd/raspiblitz.conf`
# RASPIBLITZ CONFIG FILE
raspiBlitzVersion='0.99'
hostname=
network=bitcoin
chain=main
publicIP=
runBehindTor=off
autoUnlock=on
publicIP=
publicIP=
publicIP=
publicIP=
publicIP=179.125.20.216

**Comment by Roasbeef** [comment] 2019-04-09 23:46
Fixed by #2493.

**Closed by Roasbeef** 2019-04-09 23:46 UTC
