### ISSUE TITLE
Unable to pay invoice created by current node

### ISSUE THREAD

**Issue by modenl** [lightningnetwork/lnd#3088] opened 2019-05-16 21:35 UTC
### Background

sendpayment should work with invoice created by the current node. Blue wallet seems to have a work around by doing database level changes. But sender can double pay the old invoice and lose funds.

### Steps to reproduce

1. create an invoice. 
2. Pay the invoice with the node which created the invoice.

### Expected behaviour

Invoice is paid.

### Actual behaviour

Unable to find a path

It seems a bug in path finding algorithm. We should allow the dest equals to source.

**Comment by molxyz** [comment] 2019-05-16 21:38
@modenl  Your post is not clear. Are you having trouble with Blue wallet?  It's not created by LND devs. You have to talk to bluewallet people.

**Comment by wpaulino** [comment] 2019-05-16 22:09
This is currently not supported. Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/1645.

**Closed by wpaulino** 2019-05-16 22:09 UTC

**Comment by modenl** [comment] 2019-05-16 22:41
The goal of #1645 is to rebalance channel. But this issue is not.
There is no other way to "close" an active invoice. 
Think about any custodial lightning wallet: user A creates an invoice, user B using the same wallet software cannot pay user A. The db level workaround cannot prevent the invoice to be "double" paid.
