### ISSUE TITLE
pendingchannels "confirmation_height" seemingly unset

### ISSUE THREAD

**Issue by instagibbs** [lightningnetwork/lnd#4426] opened 2020-06-29 20:18 UTC
Funding tx has >1 confirmation and yet it's always been 0.

```pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
...
            },
            "confirmation_height": 0,
...
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

**Comment by wpaulino** [comment] 2020-06-29 20:19
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/1217.

**Comment by instagibbs** [comment] 2020-06-29 20:20
apologies :+1:

**Closed by wpaulino** 2020-06-29 20:19 UTC
