### ISSUE TITLE
Unexpected Unspent UTXO balance in the on-chain section

### ISSUE THREAD

**Issue by gked** [lightningnetwork/lnd#5057] opened 2021-02-26 06:35 UTC
### Background
Hi,
I am not 100% sure if this issue is LND specific but since I am observing it LND, I am going to open an issue here first.
I am at a loss here as I can't understand what happend to an on-chain balance of my node for a few days now.
It is currently shown as unconfirmed and I have no way of spending it. 
The screenshot below was taken from Thunderhub shows three unspent UTXOs where the bottom two are spendable, i.e. I can send these balances but the top balance is not for some reason.

![image](https://user-images.githubusercontent.com/12704474/109264132-572aa600-77b9-11eb-9201-ad15f9e2a70e.png)

About a month ago, I moved 8million sats from my samourai wallet to LND on-chain wallet. Right after the transfer, I verified that the funds arrived to LND wallet. About a week or so ago, I connected to a new node and created a channel but it got stuck in pending state. After further investigation I realized that available balance (confirmed) is smaller than a new channel amount and probably caused the channel opening not being resolved. 

So, as I was going through the history of chain transactions, I saw that the initial balance of 8 million that I received from my samourai wallet was being spent into another addresses through a number of transactions. Moreover, there were few received transaction that have no balance shown at all:

![image](https://user-images.githubusercontent.com/12704474/109264210-76293800-77b9-11eb-8d99-2c78ece51d2a.png)

What next steps can I take to debug this issue further? Why is the balance stuck in unconfirmed state? How can I make it to be unstuck or at least, make it spendable?

### Your environment

* lnd version 0.11.1-beta commit=v0.11.1-beta

* Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

* Bitcoin Core version v0.20.0

**Comment by wpaulino** [comment] 2021-03-01 23:32
There have been some bugs within the wallet in previous versions that caused UTXOs to not be tracked properly. It'll be somewhat involved to identify the issue unless you have logs going back to the initial wallet deposit. You could also [force a wallet rescan](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan), which will make sure you're wallet is in sync with the chain.

**Comment by gked** [comment] 2021-03-02 06:03
> There have been some bugs within the wallet in previous versions that caused UTXOs to not be tracked properly. It'll be somewhat involved to identify the issue unless you have logs going back to the initial wallet deposit. You could also [force a wallet rescan](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan), which will make sure your wallet is in sync with the chain.

Thank for the pointers!
Just wanted to clarify something. When you say I could force wallet rescan, what do you mean exactly? 
When I run the flag , I get an error message saying: "unknown flag `reset-wallet-transactions'. 
I searched in lnd --help  for this flag but there is no reference of it or how to use it.
Thanks

**Comment by guggero** [comment] 2021-03-02 08:32
The flag was added only recently. Try upgrading to `v0.12.1-beta`, it should work there.

**Comment by jensstraten** [comment] 2021-03-06 05:35
Awesome advice, thank you! I updated to v0.12.1-beta from the previous release and ended up having 0 sats in my lnd walletbance, after I did an lncli close with a delivery_addr, which was ignored (for a reason I still don't know). Instead, the sats were withdrawn to a new address of the lnd wallet. I was super confused, because in the transaction it showed a totally different delivery_addr than I submitted and the lnd walletbalance remained 0.

--reset-wallet-transactions really did the trick and I got my money back - all sats where shown as confirmed in my walletbalance. ;)

But: I then sent out a small test transaction, which worked fine, so afterwards I did an lncli sendcoins sweepall, which failed (utxos already spent).

I went through a --reset-wallet-transactions again, did another lncli sendcoins sweepall - which worked fine now.

I saved all .lnd data and set up a new wallet, idk, maybe something is still not 100% correct after the --reset-wallet-transactions process.

If you need my lnd data for analysis, pls let me know. :)

**Comment by guggero** [comment] 2021-03-08 09:06
It sounds to me like your node somehow falls out of sync with `bitcoind`. Not sure how else the test transaction wouldn't be picked up by lnd. Or when you say "I sent out a small test transaction", you mean through `lncli` right? Or are you using the same seed in another wallet somehow?

**Comment by jensstraten** [comment] 2021-03-09 16:10
Yes, I was copying my stuff from one computer to another, I must have been running two lnd instances of the same seed for a short time. 

Thanks a lot for your help!

**Comment by guggero** [comment] 2021-03-09 17:50
Yeah, that's never a good idea and will certainly confuse lnd's wallet.
Closing as all funds are back and the strange behavior can be explained by two wallets running with the same seed.

**Closed by guggero** 2021-03-09 17:50 UTC
