### ISSUE TITLE
LND is forcing me to use a password

### ISSUE THREAD

**Issue by svewa** [lightningnetwork/lnd#5184] opened 2021-04-07 04:50 UTC
While there are certainly use-cases where it makes sense to use a password, it takes the decision from me and forces cumbersome workarounds to thousands of users (systemd units, cronjobs, whatever). 
Thinking about the pros/cons of the mandatory password:
# pro
* if my hardware gets stolen my funds are reasonably safe
   * unless this results in my node being down and channel partners can steal my funds
   * or, like in most cases, the password is in another file on the same hardware for automatic unlocking
   * or my harddrive is encrypted anyway and stolen hardware does not grant direct access to my funds
# con
* startup takes longer, especially on slow hardware
* extra steps are necessary to get LND running
   * log in, manually enter password - risk of extended downtime, funds stolen via broadcast of old channel states
   * configure 3rd party solutions to automatically supply password
* even when just running LND as WT, the password not protecting any funds, all this fuss is necessary

So pretty please make the password optional, allow the user to take measures as user sees fit.

**Comment by guggero** [comment] 2021-04-07 06:36
Duplicate of https://github.com/lightningnetwork/lnd/issues/899.

**Closed by guggero** 2021-04-07 06:36 UTC
