### ISSUE TITLE
Confusing grpc status code on startup

### ISSUE THREAD

**Issue by nepet** [lightningnetwork/lnd#6765] opened 2022-07-24 18:11 UTC
### Background

When we try to connect to a lnd node that is not ready to accept or handle rpc calls yet, lnd returns the following rpc error
```
rpc error: code = Unknown desc = the RPC server is in the process of starting up, but not yet ready to accept calls
```
This is a bit confusing as rpc has a distinct status code for the case that the resource is not ready yet or is just `UNAVAILABLE`.

From https://grpc.github.io/grpc/core/md_doc_statuscodes.html:

- `UNAVAILABLE (14)`: __The service is currently unavailable__. This is most likely a transient condition, which can be corrected by retrying with a backoff. Note that it is not always safe to retry non-idempotent operations.

It would be very handy if plugins could understand from the status code that the service is not, or not yet available, instead of taking this information from the description.
The grpc middleware retry: https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry is therefore incompatible and cannot be used to automatically retry a request or reconnect to a stream.

### Your environment

* lnd v0.15.0-beta

### Expected behaviour

Return the rpc code 14 `UNAVAILABLE` if the service is not ready to accept connections.

### Actual behaviour

Returns the rpc code 2 `UNKNOWN` if the service is not ready to accept connections.

**Comment by guggero** [comment] 2022-07-25 16:03
Yeah, we don't make use of gRPC status codes in 99% of the code. We should start doing so, at least in the important places.

But going to close this as a duplicate of https://github.com/lightningnetwork/lnd/issues/5586.

**Closed by guggero** 2022-07-25 16:03 UTC
