### ISSUE TITLE
PendingChannel does not update confirmation_height

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#6499] opened 2022-05-04 22:25 UTC
### Background

When opening a channel and channel is still in pending, the confirmation_height is not updated even if new blocks are found and stays at 0.

### Your environment

* version of `lnd`:  v0.14.3-beta.rc1
* version of `btcd`, `bitcoind`, or other backend: btcd and bitcoin (both did not work)
* any other relevant environment details

### Steps to reproduce

Open a channel and wait until first blocks are confirmed then check with `lncli pendingchannels` and verify that the `confirmation_height` is not updated and stays 0

### Expected behaviour

show blockheight when channel will be mature and locked in

### Actual behaviour

confirmation_height remains 0 the whole time

**Comment by ziggie1984** [comment] 2022-05-04 22:27
```
 "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "03ceddba52e1dbbc2927defa9c695166a9890937915453aec00c8d89d33ddeea66",
                "channel_point": "5b00704af112f5a8506cec2eae335f6813cb1880a02dc4b89461ee93336c6303:0",
                "capacity": "888877",
                "local_balance": "885407",
                "remote_balance": "0",
                "local_chan_reserve_sat": "8888",
                "remote_chan_reserve_sat": "8888",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "confirmation_height": 0,
            "commit_fee": "2810",
            "commit_weight": "772",
            "fee_per_kw": "2500"
        }
    ],
```
even if I mined 2 blocks after opening the channel and being synced to chain

**Comment by Roasbeef** [comment] 2022-05-04 22:29
Duplicate of https://github.com/lightningnetwork/lnd/issues/1217

**Comment by Roasbeef** [comment] 2022-05-04 22:29
Also see: https://github.com/lightningnetwork/lnd/pull/6472 

Likely also want to mark it as deprecated for now potentially

**Closed by Roasbeef** 2022-05-04 22:29 UTC
