### ISSUE TITLE
Domain name and refresh external IP

### ISSUE THREAD

**Issue by jochemin** [lightningnetwork/lnd#1057] opened 2018-04-09 12:01 UTC
### Background

I have a LND node running 24*7. It has a no-ip hostname associated with his external ip, in the configuration file (lnd.conf) I have this:

externalip=jocheminlnd1.ddns.net 
![image](https://user-images.githubusercontent.com/6348955/38496360-8f0050f2-3bfd-11e8-9a23-0a309cbeda55.png)

If I launch a getinfo it returns the node public IP.
![image](https://user-images.githubusercontent.com/6348955/38496464-ee5728be-3bfd-11e8-8506-4479f922c6fb.png)

This public IP changes from time to time, lnd node continues working but active channels and peers drop and I have to stop client and launch again. 

Is there a way to refer to the domain name and not the IP? or refresh the ip automatically on change?

### Your environment

* LND 0.4.1
* Linux srv1 4.4.0-119-generic #143-Ubuntu
* Bitcoin Core 0.16

### Steps to reproduce

Start your node with domain name in config file (lnd.conf) and change external IP.

### Expected behaviour

Refer to the node by his domain name to avoid fails on public ip changing.

### Actual behaviour

This public IP changes from time to time, lnd node continues working but active channels and peers drop and I have to stop client and launch again.

**Comment by vegardengen** [comment] 2018-04-09 12:46
In the weekend, I experimented with creating an "lncli addexternalip" command, so that you could wrap this in script. I have it almost working, the only problem is that I don't get a new node announcement sent out - hopefully it's just a small misunderstanding from my side. Once that is done, I will continue with making an "lncli deleteexternalip" command. This would help some, right?

Other than that - would it be possible to add a lncli gracefulrestart - where wallet is kept open, and *everything* else is reinitialized? If there is no fundamental things stopping this, I could put it on my working list for future contributions.

**Comment by Roasbeef** [comment] 2018-04-09 19:41
> This public IP changes from time to time, lnd node continues working but active channels and peers drop and I have to stop client and launch again.

We'll automatically establish outbound connections to any peers that we have channels open with. 

> In the weekend, I experimented with creating an "lncli addexternalip" command, so that you could wrap this in script.

I don't think this is the best solution, as you'll need to have a secondary script just to monitor IP address changes and then tell `lnd` to use the latest one. Instead, if you're attempting to run a _routing_ node it's desired that you have a _stable_ IP address, otherwise peers will have trouble connecting out to you in the case that they don't even store any new `NodeAnnouncements`.

**Comment by vegardengen** [comment] 2018-04-09 21:08
Well. There are different versions of stable. I am running on a dynamic IP that only rarely changes. But in the offshoot that it should change, I'm for example running a script to update DNS.

I think it's a valid use case. But I can code it myself and test it :)

**Comment by vegardengen** [comment] 2018-04-11 10:09
Well - since you can have a  domain name in the config file (resolved at startup time) - couldn't this also be solved if we created an "lncli reload" command?

lncli reload would do everything an lncli stop does, but stopping short of closing the wallet - and then opening/initializing everything again, except not having to reopen the wallet?

**Comment by jochemin** [comment] 2018-04-11 10:11
I think it would be better to refer to domain name if it's in the config file, but reload option is interesting.

**Comment by Stadicus** [comment] 2018-04-12 12:16
I can confirm that changing external ip addresses are the **single most asked questdion** in combination with my RaspiBolt guide. @Roasbeef, I don't think the requirement to have a fixed ip address to be able to route payments should just be assumed. At least in Europe fixed ip addresses are only available with business ISP contracts that are quite expensive. I think this goes directly against the goal to have a decentralized mesh network by raising the barriers to entry for non-business participants. And at least in my case, I do not have a fixed ip, but the address changes every few weeks, if not months.

I think the `lncli reload` command would be a good solution as opposed to manually updating ip external addresses. Monitoring ip address changes with a script is trivial and if a routing node is connected with a dyndns fqdn, a graceful restart would solve these issues.

On the other hand, the *need* to use a dyndns fqdn may not suit everybody, and as the whole Lightning specification works on bare ip addresses, this abstraction layer may not be welcomed.

Thanks @vegardengen for working on this after our Slack discussion. I would appreciate a broader discourse how to best enable this valid requirement.

**Comment by vegardengen** [comment] 2018-04-12 13:11
@Stadicus I have most of the addexternalip stuff coded, only thing is that it's not currently gossiped before something else triggers the gossiping. I think I might code it as addexternalip and deleteexternalip, and not updateexternalip, though. Only thing, I guess, is that you don't want to trigger gossiping twice if you are doing an add/delete combination.

**Comment by vegardengen** [comment] 2018-04-12 13:13
I also belief there is proof in working code. I am fully aware that @Roasbeef doesn't think it makes sense. My generating working code is an argument, not a protest. And being an LND newbie, it's useful training anyhow, whether or not it is merged in the end.

**Comment by Stadicus** [comment] 2018-04-12 13:30
@vegardengen Is it the intent to allow multiple externalip addresses? This is what it seems to imply by `add...` and `delete....` ip addresses and this is why I phrased it as `update...`. But any functionality to make LND usable with dynamic ips is fine with me.

Let me know if I can help in any way, eg. testing or documenting. I'm not much of a programmer, unfortunately... :-)

**Comment by vegardengen** [comment] 2018-04-12 13:51
Multiple externalip is already supported - so I think add/delete is a more general solution than update. deleteexternalip is also a way of stopping your node from getting new connections, should you want that for a period.

**Comment by Stadicus** [comment] 2018-04-12 13:55
Ah, did't consider that. It makes more sense now. 👍

**Comment by Roasbeef** [comment] 2018-04-13 03:02
> At least in Europe fixed ip addresses are only available with business ISP contracts that are quite expensive.
> And at least in my case, I do not have a fixed ip, but the address changes every few weeks, if not months.

Time to IPv6? Heh, only partially kidding...

I certainly see the use case, so seems the option is: restarting every few weeks, or adding a command to allow scripts to update the current set of advertised IPs for a node.

**Comment by Stadicus** [comment] 2018-04-13 07:03
An external script to do that would definitely help, as a restart of `lnd` always forces unlocking the wallet again. 

Any pointers how that could work? I coud work on the details given the knowledge where to start and how a good design could work on an abstract level.

**Comment by jochemin** [comment] 2018-04-13 07:10
I think a good aproach would be 'announce' option.  I assume a domain name in the config file. 

Launching lncli announce will refresh only the ip in the "uris". The user could make a script to track his public ip and if changes send the announce option automatically.

![image](https://user-images.githubusercontent.com/6348955/38721440-89656ce0-3efa-11e8-835e-749e90ce0748.png)

**Comment by vegardengen** [comment] 2018-04-13 07:25
What about creating a command:

updatenodeinfo

Here you can:

--addexternalip (to add)
--deleteexternalip (delete)
--setexternalip (to set the (list of) ip-adresses, disregarding the ones there before
--setalias

Would it also make sense to create an --announce true/false options, where you specify whether or not you want to gossip it now or wait till next change of node announcement?

@jochemin approach could also work, not sure what I prefer.

**Comment by vegardengen** [comment] 2018-04-15 16:59
@Roasbeef I value your opinion here. My choice is between:

1) Adding separate addexternalip, deleteexternalip (and possibly later setalias)
2) Adding an updatenodeannouncement that will change all of these, with parameters :)

It's also a question whether or not we should gossip immediately or just wait until next time nodeannouncement is going to change anyhow. The first will actually make it easier to spam the network with unwanted info.

**Comment by halseth** [comment] 2018-04-17 08:46
Related PR: https://github.com/lightningnetwork/lnd/pull/518

**Comment by Roasbeef** [comment] 2018-04-18 00:29
So we're reviving #518 now. The new version of the PR will have a background goroutine that'll detect IP address changes and send out new announcements to update the network for reachability. 

I think this addresses all the desired features detailed in this issue? The process would be automatic, and just all the setup guides would direct users to set the appropriate flag. This should work for the general case, but not for anything beyond a double NAT.

**Comment by Roasbeef** [comment] 2018-06-13 02:14
Fixed by #1109.

**Closed by Roasbeef** 2018-06-13 02:14 UTC

**Comment by Chrozayis** [comment] 2019-05-12 11:46
I am continuing to have issues with a dynamic IP over UPnP. The broadcast URI does not update unless I do a full restart of my node.

**Comment by egzumer** [comment] 2019-06-11 07:04
One problem is that when router is restarted, then the UPnP ports are lost and not reestablished by lnd.
Second problem is that it looks like changed IP isn't reannounced after it changes. All block explorers show the old IP address unless lnd is restarted.
