### ISSUE TITLE
LND insufficient priority

### ISSUE THREAD

**Issue by joaojoyce** [lightningnetwork/lnd#480] opened 2017-12-13 12:41 UTC
Hi.

I'm trying to open a channel on testnet using lnd and Lnd Web Client (lncli-web).

I went to the lnd testnet explorer to get a peer (77.249.29.104:9735 025eeb02baf7555a3601b9eb894319bb7db594c9be11e5b5c289938274e1752894 ) and tried to open a channel but I'm getting the following error:

````
2017-12-13 12:10:20 +0000 - INFO - -22: TX rejected: transaction 41de84f1763f925b0949b5b6699696837cf31e8f5b44c967cd8ced5e54011575 has insufficient priority (336787.5647668394 <= 5.76e+07)
````

For the questions:
1. Am I doing something wrong or is this a bug?
2. Is this because the funding transaction has insufficient fees?
3. How can I set a higher fee?
4. How can I remove these pending transactions? They appear when I do a "pendingchannels" but testnet block explorers don't seem to know them. I guess they never left my machine

Thank you.

**Comment by halseth** [comment] 2017-12-13 12:43
Thanks, this is definitely a bug! 

Duplicate of #456

**Closed by halseth** 2017-12-13 12:43 UTC

**Comment by joaojoyce** [comment] 2017-12-13 12:45
Thank you. Is there a way to bypass it for now, just to go through with some testing and poking around?

**Comment by halseth** [comment] 2017-12-13 12:48
Are you using the `btcd` (fullnode) backend? If you are, I think it should usually be enough to let the output you are trying to spend mature a bit, let more blocks be mined :)

**Comment by joaojoyce** [comment] 2017-12-13 12:50
Yes. But did the transaction left my machine? I can't see it at.

https://testnet.smartbit.com.au/tx/41de84f1763f925b0949b5b6699696837cf31e8f5b44c967cd8ced5e54011575

**Comment by halseth** [comment] 2017-12-13 12:52
It probably did not, since your fullnode rejected it. That it is still listed in `pendingchannels` is a bug.

**Comment by joaojoyce** [comment] 2017-12-13 12:53
OK. Thank you.

**Comment by halseth** [comment] 2017-12-13 13:01
You can tru updating to `1121b0c`, I think that might resolve this issue.

**Comment by joaojoyce** [comment] 2017-12-13 17:55
I'll try and report back. 

In case it is of any use I've also noticed that I only was able to create a channel in lncli by passing the --conf_target=1 flag.

**Comment by joaojoyce** [comment] 2017-12-13 18:45
OK. Was able to create the transaction with the update.
Thanks!
