### ISSUE TITLE
unexpected fault address fatal error

### ISSUE THREAD

**Issue by mutatrum** [lightningnetwork/lnd#5270] opened 2021-05-05 15:33 UTC
### Background

Sudden crash of LND with unexpected faul address.

### Your environment

* LND 0.12.1-beta (release)
* Linux thundroid 4.14.111-139 #1 SMP PREEMPT Tue Apr 16 17:31:00 UTC 2019 armv7l armv7l armv7l GNU/Linux
* Bitcoin Core version v0.21.1
* Odroid HC2 (2GB ram)
* ~80 open channels, both clearnet and tor

### Steps to reproduce

[lndcrash2.log](https://github.com/lightningnetwork/lnd/files/6428286/lndcrash2.log)

### Expected behaviour

Obviously not crash. LND seems to have recovered after a restart, so the DB looks uncorrupted.

A similar stack is seen in https://github.com/lightningnetwork/lnd/issues/4811

**Comment by guggero** [comment] 2021-05-05 15:35
Duplicate of #4811, #5234, #5126.
Upgrade OS to 64bit or run compaction.

**Closed by guggero** 2021-05-05 15:35 UTC

**Comment by mutatrum** [comment] 2021-05-05 15:40
Apologies, I only looked at open tickets. Compaction had run a few days ago at startup, channel.db is 515MB.

Hardware is running out so regardless of this issue I'm in the process of moving a new host.

**Comment by guggero** [comment] 2021-05-05 15:44
Interesting, we usually only saw this crash if the DB approached the 1GB limit on 32bit systems. But could also be related to the amount of RAM your system has available and crash earlier if there isn't enough.
You can also try removing old data such as invoices (see `--gc-canceled-invoices-on-startup`).

Unfortunately there isn't much else to do but to upgrade the hardware or OS as this is a hard limitation of the underlying `bbolt` database library.

**Comment by mutatrum** [comment] 2021-05-05 15:56
I understand, I'll try to clean up some stuff. It's been fairly busy last month, with a few 1000 forwards a day, and I can see it's stretching the limits of this hardware.

I do have a feeling I jumped a tiny hoop here and survived this without db corruption.
