### ISSUE TITLE
authentication handshake failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by evancrose** [lightningnetwork/lnd#4231] opened 2020-04-29 00:18 UTC
EDIT: I fixed this by doing the following:

* Append /etc/ssl/openssl.cnf with:
[SAN]
subjectAltName=DNS:localhost,DNS:{LND_OWNER},IP:127.0.0.1

* Generate cert:
    openssl ecparam -genkey -name prime256v1 -out {LND_OWNER}.key
    openssl req -new -sha256 -key {LND_OWNER}.key -subj "/CN=localhost/O=lnd" -reqexts SAN - config /etc/ssl/openssl.cnf -out csr.csr
    openssl req -x509 -sha256 -days 36500 -key {LND_OWNER}.key -in csr.csr -out {LND_OWNER}.cert -extensions SAN -config /etc/ssl/openssl.cnf

* Replace tls.cert / tls.key files with above, copy tls.cert to ~/lncli-web/lnd.cert

### Background

I've got lncli-web running using their p-256 certs in lieu of the automatically generated certs for lnd as I'd like to keep the web interface in addition to setting up programmatic access. When I try to run cURL commands to the REST API, I get this error:

{"error":"all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs\"","message":"all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs\"","code":14,"details":[]}

lncli commands still work as expected.

### Your environment

* version of `lnd` 
0.10.0-beta.rc5
* which operating system (`uname -a` on *Nix)
4.15.0-96-generic #97~16.04.1-Ubuntu 
* version of `btcd`, `bitcoind`, or other backend
bitcoind 0.19
* any other relevant environment details
if I remove the lncli-web certs and let LND autogenerate them, the cURL commands to the REST API work:

{"total_balance":"XXXXXXX","confirmed_balance":"XXXXXXX","unconfirmed_balance":"0"}

I've also set/unset --tlsextraip=127.0.0.1 to no avail

Running curl -k https://localhost:8080/v1/getinfo produces the same response.

### Steps to reproduce

Install lnd, lncli-web and copy the p-256 certs needed by lncli-web to the .lnd directory

### Expected behaviour

REST API should function using the admin macaroon + provided cert

### Actual behaviour

auth handshake fails

**Comment by guggero** [comment] 2020-04-29 07:11
Not sure what the state of this issue is. It looks like you were able to fix it by adding the IP to the SAN?
This behavior in general is expected. The REST interface is just a small proxy component that forwards the requests internally against the gRPC interface. It does this through 127.0.0.1.
Therefore the IP address must be included in any certificate.

Also the `--tlxextraip / --tlsextradomain` are only used when `lnd` creates its own certificate, not when an external one is provided.

Closing the issue as it looks like the problem is solved.

**Closed by guggero** 2020-04-29 07:11 UTC
