### ISSUE TITLE
channel is pending, mempool is empty and I can not see funding tx in bloxkexplorer

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#3122] opened 2019-05-26 08:52 UTC
### Background
This is the tx
```
admin@raspberrypi:~ $ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e",
                "channel_point": "8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1",
                "capacity": "800000",
                "local_balance": "782727",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "17273",
            "commit_weight": "600",
            "fee_per_kw": "23858"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}


```
I can not find this tx - 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694 in the blockexplorer, and the mempool is empty.
My funds are still locked in this channel.

### Your environment

lnd version 0.6.0-beta commit=v0.6-beta
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
Bitcoin Core Daemon version v0.17.1

What should I do to get the coins back?

**Comment by Roasbeef** [comment] 2019-05-27 20:01
First, I recommend you update to v0.6.1. Beyond that, check your logs to see if it's being broadcast, check `listunspent` to see if that UTXO has actually been consumed, and also your `bitcoind` state to see if it's in the mempool.

**Comment by MrManPew** [comment] 2019-05-27 22:54
> First, I recommend you update to v0.6.1.

Updated, problem persist.

> check listunspent to see if that UTXO has actually been consumed

Indeed it was consumed

>  and also your bitcoind state to see if it's in the mempool.

It is not in the mempool

> . Beyond that, check your logs to see if it's being broadcast,

How do I do it exactly?

Thanks

**Comment by wpaulino** [comment] 2019-05-28 22:51
I'd suggest reading over the Raspiblitz documentation on how to obtain the logs. It's likely that the transaction is attempting to double spend an output that's already confirmed. Once you locate the logs of the funding transaction broadcast, it should show you the outputs it's attempting to spend. Could you also look for any references in the logs of those outputs?

**Comment by MrManPew** [comment] 2019-05-28 23:28
Is these logs enough?
```
2019-05-23 07:16:37.985 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 07:16:38.017 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-23 07:16:38.017 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-23 07:16:38.018 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-23 07:16:38.018 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 07:17:08.023 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-23 07:17:08.029 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-23 07:17:39.003 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 07:17:39.007 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-23 07:17:39.008 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-23 07:17:39.008 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-23 07:17:39.008 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 07:18:09.013 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-23 07:18:09.014 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-23 18:12:59.182 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 18:12:59.234 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-23 18:12:59.257 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-23 18:12:59.257 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-23 18:12:59.257 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 18:13:29.268 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-23 18:13:29.271 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-23 18:18:01.587 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 18:18:01.597 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-23 18:18:01.598 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-23 18:18:01.598 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-23 18:18:01.598 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 18:18:31.603 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-23 18:18:31.603 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-23 18:19:26.510 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 18:19:26.518 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-23 18:19:26.520 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-23 18:19:26.521 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-23 18:19:26.522 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-23 18:19:56.524 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-23 18:19:56.524 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-26 10:57:33.394 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-26 10:58:05.850 [INF] NTFN: New spend subscription: spend_id=29, outpoint=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, height_hint=577830
2019-05-26 10:58:11.095 [INF] CNCT: Close observer for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) active
2019-05-26 10:58:13.002 [INF] CNCT: ChannelArbitrator(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): starting state=StateDefault
2019-05-26 10:58:34.336 [INF] LNWL: Inserting unconfirmed transaction 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694
2019-05-26 10:58:34.479 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): Transaction rejected: output already spent
2019-05-26 10:58:34.481 [INF] NTFN: New confirmation subscription: txid=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694, num_confs=3
2019-05-26 10:58:34.515 [INF] NTFN: New confirmation subscription: conf_id=1, txid=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694, height_hint=577830
2019-05-26 10:58:34.516 [INF] FNDG: Waiting for funding tx (8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694) to reach 3 confirmations
2019-05-26 11:24:38.484 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-26 11:24:38.492 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-26 11:24:38.493 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-26 11:24:38.493 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-26 11:24:38.493 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-26 11:25:08.498 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-26 11:25:08.498 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-26 11:25:48.200 [INF] PEER: NodeKey(032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e) loading ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-26 11:25:48.210 [WRN] PEER: Unable to find our forwarding policy for channel 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, using default values
2019-05-26 11:25:48.212 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is starting
2019-05-26 11:25:48.213 [INF] HSWC: HTLC manager for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) started, bandwidth=774727000 mSAT
2019-05-26 11:25:48.213 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-26 11:26:18.217 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) has exited
2019-05-26 11:26:18.217 [INF] HSWC: ChannelLink(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) is stopping
2019-05-28 01:41:01.807 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-28 01:44:29.721 [INF] NTFN: New spend subscription: spend_id=26, outpoint=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, height_hint=578094
2019-05-28 01:44:34.378 [INF] CNCT: Close observer for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) active
2019-05-28 01:44:35.803 [INF] CNCT: ChannelArbitrator(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): starting state=StateDefault
2019-05-28 01:45:04.477 [INF] LNWL: Inserting unconfirmed transaction 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694
2019-05-28 01:45:04.700 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): Transaction rejected: output already spent
2019-05-28 01:45:04.702 [INF] NTFN: New confirmation subscription: txid=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694, num_confs=3
2019-05-28 01:45:04.702 [INF] NTFN: New confirmation subscription: conf_id=1, txid=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694, height_hint=578094
2019-05-28 01:45:04.702 [INF] FNDG: Waiting for funding tx (8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694) to reach 3 confirmations
2019-05-28 02:03:02.663 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1)
2019-05-28 04:25:57.508 [INF] NTFN: New spend subscription: spend_id=50, outpoint=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1, height_hint=578094
2019-05-28 04:25:58.364 [INF] CNCT: Close observer for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1) active
2019-05-28 04:26:02.423 [INF] CNCT: ChannelArbitrator(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): starting state=StateDefault
2019-05-28 04:29:01.765 [INF] LNWL: Inserting unconfirmed transaction 8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694
2019-05-28 04:29:01.868 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): Transaction rejected: output already spent
2019-05-28 04:29:01.870 [INF] NTFN: New confirmation subscription: txid=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694, num_confs=3
2019-05-28 04:29:01.888 [INF] NTFN: New confirmation subscription: conf_id=1, txid=8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694, height_hint=578094
2019-05-28 04:29:01.889 [INF] FNDG: Waiting for funding tx (8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694) to reach 3 confirmations

```

**Comment by Roasbeef** [comment] 2019-05-28 23:35
As far as we can tell, no UTXO actually consumed here, and there's also no active channel. 
When you made this channel, did you instruct `lnd` to spend zero conf outputs?

**Comment by MrManPew** [comment] 2019-05-29 06:31
> As far as we can tell, no UTXO actually consumed here, and there's also no active channel.

But I had 1,400,000 sat and now I have  600,000 ... 

> When you made this channel, did you instruct lnd to spend zero conf outputs?

I opened the channel like I open any channel:
```
lncli openchannel node_name 800000 --sat_per_byte 2
```
Thanks @Roasbeef  for the support

**Comment by wpaulino** [comment] 2019-05-29 19:18
> 2019-05-09 21:47:08.018 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(8ae6f32902bd32c2320b0b1eacb988d8a417000d1f82c5fe0c6f7bcb31d48694:1): -26: mempool min fee not met, 851 < 2763 (code 66)

This is the issue, which can happen when you restrict the size of your mempool.

The logs show that the transaction was removed so the funds shouldn't be locked up. If you look up the inputs used within the transaction, they all seem to have been spent by other transactions.

Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/1623.

**Closed by wpaulino** 2019-05-29 19:18 UTC
