### ISSUE TITLE
[bug]: RBF Confirmed, Channel not open then closed tx not broadcast

### ISSUE THREAD

**Issue by jiraiyax** [lightningnetwork/lnd#7801] opened 2023-07-02 01:18 UTC
### Background

I have been open channel with PSBT. I signed transaction using electrum then broadcast by lnd. After that I do bump fee by using electrum and transaction has confirmed but channel do not open. After all I do force close with "lncli closechannel -force" but closing tx not broadcast. What can I do next. Thanks

This is open channel tx "c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9" (Sign by electrum broadcast by node)
But I do RBF it replace by tx "3c1e505390269371ac152df474867a15b260a9973c02025c1695bbf2165ad614" (RBF by electrum)

### Your environment

* version of `lnd` 0.16.3
* which operating system (`ubuntu`)
* version of  `bitcoin-core`, v25.0
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Here is log when I use "lncli pendingchannels"

{
"total_limbo_balance": "3996530",
"pending_open_channels": [
],
"pending_closing_channels": [
],
"pending_force_closing_channels": [
],
"waiting_close_channels": [
{
"channel": {
"remote_node_pub": "0294ac3e099def03c12a37e30fe5364b1223fd60069869142ef96580c8439c2e0a",
"channel_point": "c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9:0",
"capacity": "4000000",
"local_balance": "3996530",
"remote_balance": "0",
"local_chan_reserve_sat": "40000",
"remote_chan_reserve_sat": "40000",
"initiator": "INITIATOR_LOCAL",
"commitment_type": "ANCHORS",
"num_forwarding_packages": "0",
"chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
"private": false
},
"limbo_balance": "3996530",
"commitments": {
"local_txid": "e4832caedc0120f2e7c857f5475672101219ae529bfc75e670794aafe811c62d",
"remote_txid": "61634480014ee03a7ddd8f3f255b9807df7c44000384b84722ac3131742266dd",
"remote_pending_txid": "",
"local_commit_fee_sat": "2810",
"remote_commit_fee_sat": "2810",
"remote_pending_commit_fee_sat": "0"
},
"closing_txid": "e4832caedc0120f2e7c857f5475672101219ae529bfc75e670794aafe811c62d"
}.
]
}

**Comment by guggero** [comment] 2023-07-02 13:11
If you RBF a channel funding transaction, you change its TXID, making any pre-signed commitment transaction invalid. So basically you sent your funds to a 2-of-2 multisig address for which you only have one key. So you should NEVER (!!) RBF a channel funding transaction, you MUST use CPFP. The only option you now have to rescue the funds is to use [`chantools rescuefunding`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_rescuefunding.md), for which you need your peer's cooperation.

**Comment by jiraiyax** [comment] 2023-07-02 14:38
> If you RBF a channel funding transaction, you change its TXID, making any pre-signed commitment transaction invalid. So basically you sent your funds to a 2-of-2 multisig address for which you only have one key. So you should NEVER (!!) RBF a channel funding transaction, you MUST use CPFP. The only option you now have to rescue the funds is to use [`chantools rescuefunding`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_rescuefunding.md), for which you need your peer's cooperation.

Thank you for your kind. And anyone who know to contact okx lightning team?

**Comment by jiraiyax** [comment] 2023-07-02 15:09
> > If you RBF a channel funding transaction, you change its TXID, making any pre-signed commitment transaction invalid. So basically you sent your funds to a 2-of-2 multisig address for which you only have one key. So you should NEVER (!!) RBF a channel funding transaction, you MUST use CPFP. The only option you now have to rescue the funds is to use [`chantools rescuefunding`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_rescuefunding.md), for which you need your peer's cooperation.
> 
> Thank you for your kind. And anyone who know to contact okx lightning team?

chantools rescuefunding \
	--channeldb ~/.lnd/data/graph/mainnet/channel.db \
	--dbchannelpoint xxxxxxx:xx \
	--sweepaddr bc1qxxxxxxxxx \
	--feerate 10

chantools rescuefunding \
	--confirmedchannelpoint xxxxxxx:xx \
	--localkeyindex x \
	--remotepubkey 0xxxxxxxxxxxxxxxx \
	--sweepaddr bc1qxxxxxxxxx \
	--feerate 10

is --dbchannelpoint xxxxxxx:xx  same with --confirmedchannelpoint xxxxxxx:xx?

**Comment by jiraiyax** [comment] 2023-07-02 15:56
I have no luck. after run command the node reply "error fetching UTXO info for outpoint c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9:0: transaction not found"

**Comment by ffranr** [comment] 2023-07-04 15:16
Hello @jiraiyax ,

As far as I understand this is the current state of this issue (please correct me if I'm wrong):
* This channel open transaction was broadcast by your node: c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9
* Then you replaced that tx (via RBF) with [3c1e505390269371ac152df474867a15b260a9973c02025c1695bbf2165ad614](https://mempool.space/tx/3c1e505390269371ac152df474867a15b260a9973c02025c1695bbf2165ad614)
* You're attempting to use `chantools rescuefunding`.

I think `--dbchannelpoint` should have a different value to `--confirmedchannelpoint`.

`--dbchannelpoint` should point to the `tx:c2be` transaction. And `--confirmedchannelpoint` should point to the `tx:3c1e` transaction.

```
--confirmedchannelpoint string   channel outpoint that got confirmed on chain (<txid>:<txindex>);
```

> error fetching UTXO info for outpoint c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9:0: transaction not found

The error you've reported in your latest message is not unexpected because that tx never made it into the chain.

Please give it a go using `--dbchannelpoint` and `--confirmedchannelpoint`, and then let me know how it goes.

**Comment by jiraiyax** [comment] 2023-07-08 03:04
> Hello @jiraiyax ,
> 
> 
> 
> As far as I understand this is the current state of this issue (please correct me if I'm wrong):
> 
> * This channel open transaction was broadcast by your node: c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9
> 
> * Then you replaced that tx (via RBF) with [3c1e505390269371ac152df474867a15b260a9973c02025c1695bbf2165ad614](https://mempool.space/tx/3c1e505390269371ac152df474867a15b260a9973c02025c1695bbf2165ad614)
> 
> * You're attempting to use `chantools rescuefunding`.
> 
> 
> 
> I think `--dbchannelpoint` should have a different value to `--confirmedchannelpoint`.
> 
> 
> 
> `--dbchannelpoint` should point to the `tx:c2be` transaction. And `--confirmedchannelpoint` should point to the `tx:3c1e` transaction.
> 
> 
> 
> ```
> 
> --confirmedchannelpoint string   channel outpoint that got confirmed on chain (<txid>:<txindex>);
> 
> ```
> 
> 
> 
> > error fetching UTXO info for outpoint c2beb0f19ce58a7e56a3a359dee4aa1dfb4eb2424bef22502bb61ee5b882b1e9:0: transaction not found
> 
> 
> 
> The error you've reported in your latest message is not unexpected because that tx never made it into the chain.
> 
> 
> 
> Please give it a go using `--dbchannelpoint` and `--confirmedchannelpoint`, and then let me know how it goes. 

Yes, You got it right. How to resolve this solution? Which way I need to do to recovery my money. Thank you.

**Comment by jiraiyax** [comment] 2023-07-09 12:04
> * 3c1e505390269371ac152df474867a15b260a9973c02025c1695bbf2165ad614

Yes I got it!
This is base64 encode `cHNidP8BAFICAAAAARTWWhbyu5UWXAICPJepYLIVeoZ09C0VrHGTJpBTUB48AAAAAAAAAAAAAdT4PAAAAAAAFgAU76MUxY35k8UoyNVIiHP84C1vi4gAAAAAAAEBKwAJPQAAAAAAIgAg1OXb8O+W/G2QoGvxzCZIrVnnstfV10luzJGHuXWk2BUiAgPDQZRxKpzkc7H6Ga0rXtj6SgFKfS89TNGMyWAeC94CgEgwRQIhAL8sDju7FKPbPRUyXdzsO/u1BOSrwkOYY4YBJiEp7tuaAiBBuMaJd4ETZJMnZnRxUFXGkF+CPy9TvRcGYSfDKwg+CgEBBUdSIQKfb2E0fsHYkhZZv25rkSsi6nLaMdoj42YQD4gd2q+4cyEDw0GUcSqc5HOx+hmtK17Y+koBSn0vPUzRjMlgHgveAoBSrgHMIQKfb2E0fsHYkhZZv25rkSsi6nLaMdoj42YQD4gd2q+4cwAA`

Please anyone tell me where I can contact OKX team to do sign transaction for me?

**Comment by hieblmi** [comment] 2023-07-10 10:51
One way is to contact the okx helpdesk, they offer it on multiple channels https://www.okx.com/community.

**Comment by megaptera21** [comment] 2023-08-21 07:23
I have exactly the same problem and also with the OKX node.
Could you ever resolve this @jiraiyax? Do you have a contact with OKX which could help you resolve this?

Thanks!

**Comment by ffranr** [comment] 2023-08-21 10:10
@jiraiyax I'll try to figure out if we have a contact in OKX that I can refer you to.

**Comment by jiraiyax** [comment] 2023-08-21 10:34
> @jiraiyax I'll try to figure out if we have a contact in OKX that I can refer you to. Thanks for keeping this issue updated with your progress.

Thank you so much for your help.

**Comment by megaptera21** [comment] 2023-08-21 14:26
> @jiraiyax I'll try to figure out if we have a contact in OKX that I can refer you to. Thanks for keeping this issue updated with your progress.

That would be very useful. I created a ticket with the support e-mail but I don't think this will succeed...

**Comment by megaptera21** [comment] 2023-09-20 08:09
> @jiraiyax I'll try to figure out if we have a contact in OKX that I can refer you to. Thanks for keeping this issue updated with your progress.

Hi @jiraiyax ! Could you finaly find someone to contact? Would be very helpful, thanks!

**Comment by jiraiyax** [comment] 2023-09-20 08:19
No, Sir. Still the same as before.

**Comment by jiraiyax** [comment] 2023-09-20 08:21
> > @jiraiyax I'll try to figure out if we have a contact in OKX that I can refer you to. Thanks for keeping this issue updated with your progress.
> 
> 
> 
> Hi @jiraiyax ! Could you finaly find someone to contact? Would be very helpful, thanks!

No, Sir. Still the same as before.

**Comment by megaptera21** [comment] 2023-10-17 07:48
I got a repsone from the OKX Support. Maybe there is some hope... 

_Thank you for your patience.
 
After reviewing your concern, we have escalated the issue for further attention. We kindly request your understanding as we allow sufficient time for the necessary processes to take place. Rest assured, we will ensure that your matter is addressed appropriately and we will provide you with an update once we have received feedback.
 
Due to the technical complexity of this issue, we regret to inform you that we are unable to provide a specific timeframe for its resolution. However, we assure you that our team is actively working on finding a solution. We sincerely appreciate your patience and understanding in this matter.
 
Thank you for your understanding and cooperation._

Keep you updated.

**Comment by jiraiyax** [comment] 2023-10-17 11:49
> I got a repsone from the OKX Support. Maybe there is some hope... 
> 
> 
> 
> _Thank you for your patience.
> 
>  
> 
> After reviewing your concern, we have escalated the issue for further attention. We kindly request your understanding as we allow sufficient time for the necessary processes to take place. Rest assured, we will ensure that your matter is addressed appropriately and we will provide you with an update once we have received feedback.
> 
>  
> 
> Due to the technical complexity of this issue, we regret to inform you that we are unable to provide a specific timeframe for its resolution. However, we assure you that our team is actively working on finding a solution. We sincerely appreciate your patience and understanding in this matter.
> 
>  
> 
> Thank you for your understanding and cooperation._
> 
> 
> 
> Keep you updated.

Thank you so much sir.

**Comment by jiraiyax** [comment] 2024-05-17 15:02
Still wait for someone who can help.

**Comment by guggero** [comment] 2024-05-17 15:12
Only OKX can help you by counter signing. There is nothing anyone else can do, sorry. Keep trying their helpdesk/support. Closing the issue.

**Closed by guggero** 2024-05-17 15:12 UTC
Labels: bug, P3, psbt, rbf

**Comment by megaptera21** [comment] 2024-09-18 05:40
@jiraiyax just for your information:

After one year of back and forth with the OKX customer support I got this message. 

> Thank you for your patience while we're checking on the issue. Please be informed that after a careful decision and consideration, kindly noted that we will not able to assist further on this due to the associated risks. 
> Hope this clarifies. If you have any further questions or concerns, please do not hesitate to contact us. We are always here to help you.

They probably just don't care.

Those sats are now a gift to the entire bitcoin community, enjoy!

**Comment by jiraiyax** [comment] 2024-09-18 06:09
> @jiraiyax just for your information:
> 
> 
> 
> After one year of back and forth with the OKX customer support I got this message. 
> 
> 
> 
> > Thank you for your patience while we're checking on the issue. Please be informed that after a careful decision and consideration, kindly noted that we will not able to assist further on this due to the associated risks. 
> 
> > Hope this clarifies. If you have any further questions or concerns, please do not hesitate to contact us. We are always here to help you.
> 
> 
> 
> They probably just don't care.
> 
> 
> 
> Those sats are now a gift to the entire bitcoin community, enjoy!
> 
> 

Thank you so much sir.
