### ISSUE TITLE
Add support of forward fail payments tracking

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#1318] opened 2018-06-04 08:55 UTC
As a Gateway providers it is needed to track users fail attempts to make a multi-hop payment, in order to have a trigger/alert for further investigation of the problem. This would allow gateway providers lock more funds if that is the reason of fail.

@cfromknecht @Roasbeef
Do you think that it should be implemented, and if yes, do you have anything in mind about how you would prefer this to be implemented?

**Comment by Roasbeef** [comment] 2018-06-04 23:18
Someone can just spam you with failures and fill up your disk. We have some stuff like this planned w.r.t node management software we're making, but it isn't too high of a priority at present, and when we're closer to shipping this software, it'll likely be prioritized.

**Comment by AndrewSamokhvalov** [comment] 2018-06-05 09:21
So, I could start working at this right now. Would be great if you guys could lay out your initial thought on it, or we could sync up after PR, but implementation might deviate from what you would expect in this case.

**Comment by Roasbeef** [comment] 2018-06-08 01:19
What's the PR? You never described the approach.

**Comment by Roasbeef** [comment] 2018-06-08 01:20
The better thing to do, would be to instead work on the monitoring integration with the `telemetry` package, `lndmon`, and Prometheus.

**Comment by AndrewSamokhvalov** [comment] 2018-06-08 10:42
When you are saying that it would be better to work on monitoring integration I kinda don't understand how exactly I could squeeze in, for two reasons:

1. From what I have seen so far there is no yet agreement on how exactly metrics subsystem should be integrated. There are two ways (1) `lndmon+telemetry`, (2) `prometheus` endpoint in `lnd`. Both ways good from my POV, but there have been knowledgeable comments left in favor and against both approaches in this [thread](https://github.com/lightningnetwork/lnd/issues/1243).

2. There is some effort putted in both of this directions, (1) @baryluk claims to have some working code which just needed to be polished, (2) @maurycy already sent a [PR](https://github.com/lightningnetwork/lnd/pull/1302) with some initial code of `telemetry`.

If I start working in this direction it will mean that at least one of us would lose its work 😕

**Comment by AndrewSamokhvalov** [comment] 2018-06-08 12:08
@Roasbeef Am I right that you would like fail forwards info being pushed directly in `telemetry` subsystem instead of being stored somewhere in-memory? If not, than I don't see how this feature request is dependant in monitoring subsystem.

**Comment by Roasbeef** [comment] 2018-06-08 20:02
`lndmon+telemtry` has already been decided. Including `prometheus` would result in an unnecessary increase in the surface area for `lnd`. We would need to be concerned with CVE's that target the `prometheus` client.

**Comment by baryluk** [comment] 2018-06-09 18:50
> Including prometheus would result in an unnecessary increase in the surface area for lnd. We would need to be concerned with CVE's that target the prometheus client.
I think you are misinformed on this topic.

**Comment by baryluk** [comment] 2018-06-11 12:10
The failure of these kind should either be logged to file, or sent to a some kind of notification system, i.e. zmq or other pub/sub system, that can persist notification and details about it, even if consumer is missing.

Monitoring like prometheues or telemetry, would probably only track total count of failures instead, and could be used as trigger to do an alert, but it would not store any details about failed transaction.

**Comment by AndrewSamokhvalov** [comment] 2018-06-11 15:08
@baryluk I believe that is what @Roasbeef would like to do with telemetry?

**Comment by baryluk** [comment] 2018-06-16 20:27
I have seen no mention that telemetry will be persisted (i.e. ACID semantic for guaranteed message delivery).

**Comment by MrManPew** [comment] 2019-06-02 22:51
This one is very important if we would like to know how to make the network stronger

**Comment by MrManPew** [comment] 2019-07-11 23:03
Hi, is this ticket still valid?

**Comment by MrManPew** [comment] 2019-08-22 06:16
This is solved by : https://github.com/lightningnetwork/lnd/issues/3420

**Comment by halseth** [comment] 2019-09-25 13:27
Marking duplicate of https://github.com/lightningnetwork/lnd/issues/3420

**Closed by halseth** 2019-09-25 13:27 UTC
Labels: P3, enhancement, feature request
