### ISSUE TITLE
No `channel_update` is sent to non-public channels

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#1347] opened 2018-06-08 12:26 UTC
LND currently supports routing hints in payment requests but does not send a `channel_update` to pop-public channels as specified at https://github.com/lightningnetwork/lightning-rfc/pull/193. Thus many mobile wallets which use non-public channels by default have no way of receiving funds when connected to LND nodes.

**Comment by Roasbeef** [comment] 2018-06-08 20:00
Are you sure? We have test exercising this on a multi-hop basis even. This is the code that sends the channel update: https://github.com/lightningnetwork/lnd/blob/master/discovery/gossiper.go#L1983

**Comment by Roasbeef** [comment] 2018-06-08 20:01
The one thing we don't do currently is ensure that it's sent reliably, so if the peer isn't connected at the time we go to send the update, then we'll never send it to them. This is documented in a TODO a few lines below where I linked.

**Comment by btcontract** [comment] 2018-06-08 20:08
I have a non public channel with LND node where funding tx has 63 confirmations and no update received, looks like it's an "offline" case.

**Comment by Perlover** [comment] 2018-07-02 10:30
@Roasbeef , can you open this issue?
This issue is closed but i think it's annoying problem. I use Bitcoin Lightning Wallet and i cannot to get payments because the my own `lnd` (fresh commits) has this fault (if i right understand).
I think if this issue will be closed it will not resolved near time :(

**Comment by btcontract** [comment] 2018-07-20 04:27
Indeed it's annoying, keep getting user complaints all the time. Plus, it looks like ACINQ works on receiving in their Android wallet which also uses private channels, so will face the same issues.

**Comment by SomberNight** [comment] 2018-10-08 16:02
This affects Electrum as well.
I have tried sending a `query_short_channel_ids` message for specifically the private channel but lnd won't send the channel update even then.
I think the easiest fix/workaround would be to at least make `query_short_channel_ids` work here.

**Comment by Roasbeef** [comment] 2018-10-09 03:16
> sending a query_short_channel_ids message for specifically the private channel but lnd won't send the channel update even then

By design, you can't query private channels.

**Comment by ecdsa** [comment] 2018-10-09 10:09
@roasbeef why is that so? allowing this would fix the 'offline' issue.

**Closed** 2019-02-20 05:09 UTC
