### ISSUE TITLE
LND v.0.14.0 is incompatible with eclair and c-lightning! Please stop distributing it!!!

### ISSUE THREAD

**Issue by viaj3ro** [lightningnetwork/lnd#6023] opened 2021-11-24 06:23 UTC
Why is this broken release still being distributed even after @Roasbeef has acknowledged the issue? It's partitioning the network!

https://github.com/lightningnetwork/lnd/issues/5890#issuecomment-972125361
https://github.com/lightningnetwork/lnd/issues/5890#issuecomment-974277916

**Comment by nolim1t** [comment] 2021-11-24 07:13
I've had no issues (apart from some deprecated API issues using an older version of LNBits)?

**Comment by levmi** [comment] 2021-11-24 12:33
We're actively investigating this issue to determine its scope and the proper fix. Retracting a release isn't practical, but we'll prioritize a 0.14.1 release with a patch/fix if necessary.

**Comment by viaj3ro** [comment] 2021-11-24 13:31
> I've had no issues (apart from some deprecated API issues using an older version of LNBits)?

what do you mean? As is, LND v0.14.0 can't open channels to eclair or c-lightning nodes or the other way around. I tried multiple nodes and can't connect to anyone on this latest release and neither can they open channels with me. And as per the the linked comments, others have the same issue.

**Comment by Roasbeef** [comment] 2021-11-24 15:53
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/5890, we have a fix which will be released eminently.

**Closed by Roasbeef** 2021-11-24 15:53 UTC
