### ISSUE TITLE
Crash using listchaintxns with an unconfirmed balance

### ISSUE THREAD

**Issue by Derek701** [lightningnetwork/lnd#1964] opened 2018-09-22 03:42 UTC
### Background
`lnd` crashes when I try to use `lncli listchaintxns` with an unconfirmed balance.

### Environment
* `lnd v0.5-beta`
* `bitcoind 0.16.3`
* `Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-34-generic x86_64)`

### Error Log
```
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044c500, 0x1209e80, 0xc010e82600, 0xc000012300, 0xc000194f30, 0x19e2130, 0xc010886c90, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x8ec
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00044c500, 0x1209e80, 0xc010e82600, 0xc000012300, 0xc010886c90)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1308
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc010eccc70, 0xc00044c500, 0x1209e80, 0xc010e82600, 0xc000012300)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0xa1
```

### Resolution
The command works after restarting `lnd` and waiting for a confirmation.

**Comment by Roasbeef** [comment] 2018-09-22 03:43
Duplicate of #1950, fixed in master, and will be rolled out in the next minor release.

**Closed by Roasbeef** 2018-09-22 03:43 UTC

**Comment by Derek701** [comment] 2018-09-22 03:47
Oops! Sorry I missed that.
