### ISSUE TITLE
High CPU usage, constant at ~100% in top

### ISSUE THREAD

**Issue by hoplaaa** [lightningnetwork/lnd#6065] opened 2021-12-06 18:41 UTC
### Background

Running a very small node on a recent laptop, the CPU is always high, the fan is always active.

CPU usage oscillate ~10% around  100%, from `top` :
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 451713 lnd       20   0   39.2g   1.1g 108972 S 106.7  14.6  55:55.33 lnd

I ran go tool pprof http://localhost:9736/debug/pprof/profile?seconds=90
You will find the profile002.svg file in that zip : (let me know how to upload more properly)
[profile002.zip](https://github.com/lightningnetwork/lnd/files/7662757/profile002.zip)

This extract was done few minutes after a fresh node startup, I can provide another one tomorrow.
I can provide more inputs on demand.

### Your environment

* small node, 2 public channels, no routing, no payments, ~2 month old
* version of `lnd` 0.14.0-beta
* Linux hop 5.10.0-9-amd64 # 1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
* Bitcoin Core version v22.0.0
* Recent laptop always online
* Previously I was running latest 0.13 version from binaries, I'm not sure if I got the same issue.

### Steps to reproduce

Start lnd, run `top`, wait 1 week, run `top` again, still stable CPU usage at ~100%

### Expected behaviour

CPU usage shouldn't be so high in 'idle'. 

### Actual behaviour

CPU should be very low when there is no activity for weeks.

**Comment by Roasbeef** [comment] 2021-12-06 20:13
Looks like it's spending a lot of time storing the freelist (when writing mission control data to disk). If you run with the default configuration (free list sync is off), then this should be addressed.

**Comment by hoplaaa** [comment] 2021-12-06 22:58
Yeah you are right, in my config file : 
`sync-freelist=1`

I removed that line, restarted and after few seconds lnd is at 1% of CPU. Thanks !

I took that parameter from here: 
https://docs.lightning.engineering/lightning-network-tools/lnd/optimal-configuration-of-a-routing-node
_sync-freelist=1
stagger-initial-reconnect=1
This will help our node start up faster by applying randomized staggering when reconnecting to persistent peers. This minimizes the chance of connecting to all non-responsive peers at once._

You might want either dig on the CPU usage, add a warning in the documentation or consider small nodes shouldn't run lnd with such option. I'm fine with all. Feel free to close the issue if you consider there is nothing to do.

**Comment by guggero** [comment] 2021-12-07 08:45
Did you ever compact your DB? Over time the "free list" of the DB gets fragmented. If it needs to be synced after every write operation, that can take longer and longer. So using `db.bolt.auto-compact=1` and restarting every now and then would probably have solved the issue for you as well.

@Liongrass can you please update the example config in https://docs.lightning.engineering/lightning-network-tools/lnd/optimal-configuration-of-a-routing-node to also turn on compaction?

**Comment by hoplaaa** [comment] 2021-12-07 09:24
Tried adding `db.bolt.auto-compact=1` along with `sync-freelist=1`, restarted lnd.
No more CPU issue. Nice !
In the logs : 
`2021-12-07 10:11:15.891 [INF] CHDB: DB compaction of /home/lnd/.lnd/data/graph/mainnet/channel.db successful, 39882661888 -> 126050304 bytes (gain=**316.40x**)
`

I didn't save channel.db before doing so, sorry.
It's weird that I got such issue on a very small node (2 channels, no routing activity, 2 month old).

**Comment by guggero** [comment] 2021-12-07 09:37
It's a known problem of the `bbolt` database library we use. Even if data is deleted from it, it's not really freed up unless you compact. So just from downloading the whole channel graph when you first started your node there probably was a lot of left-over data in there. I think we should probably start turning on auto-compaction by default.
But the long-term goal is clear: move away from the `bbolt` database entirely. That will just take a lot of time.

**Comment by Liongrass** [comment] 2021-12-08 04:31
I've added `db.bolt.auto-compact=1` to the guide, thank you for the suggestion!

**Comment by guggero** [comment] 2021-12-08 10:45
Closing as the issue was caused by lack of periodic auto-compaction. The docs were updated, thanks @Liongrass.

**Closed by guggero** 2021-12-08 10:45 UTC
