### ISSUE TITLE
Support Tor v3 addresses for neutrino connections

### ISSUE THREAD

**Issue by dmp1ce** [lightningnetwork/lnd#5308] opened 2021-05-17 20:21 UTC
### Background

I am trying to connect to a node using Neutrino over Tor but LND seems to only support v2 addresses and not v3 addresses.

### Your environment

* 0.12
* Docker: dmp1ce/lnd:0.12-beta-alpine
* neutrino

Relevant configuration:

```
bitcoin.node=neutrino
# Tor v3 address here
neutrino.connect=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.onion
```

### Steps to reproduce

Try to connect Neutrino backend to a v3 Tor bitcoin node.

### Expected behaviour

Connection and downloads blocks as normal using neutrino

### Actual behaviour

Several of these warning:
```
lnd_1  | 2021-05-17 20:11:30.810 [WRN] BTCN: unable to lookup IP for xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.onion: invalid onion v2 host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.onion
```

**Comment by Roasbeef** [comment] 2021-05-17 20:43
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/4973

**Closed by Roasbeef** 2021-05-17 20:43 UTC
