### ISSUE TITLE
Add gRPC/lncli function to `getOverflowBandwidth` (and/or `availableBandwidth`).

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2271] opened 2018-12-04 13:13 UTC
### Background

lnd nodes cannot route the entire Balance they have in a channel in an instance. The current maximum value that they can route is described in the [Bandwidth function](https://github.com/lightningnetwork/lnd/blob/640fe2558b9b812f812fe1591dfc564037abb470/htlcswitch/link.go#L1808). The actual value is called Bandwidth, and it is basically calculated as follows:

`availableBandwidth = availableBalance - reserve - overflowBandwidth`

The reserve is generally 1% of the capacity of the channel, the `availableBalance` can be check from lncli/gRPC calling `listchannels`, but there is no way of getting neither `overflowBandwidth` nor `availableBandwidth`.  The `overflowBandwidth` is the amount of balance that is currently being used for other payments (which may succeed or not). This is an important feature and nodes should be able to easily retrieve how much of their balance is available at a particular time (i.e. how much of their balance is being used to try other payments). Instead of a new function, this can be listed in `listchannels`.

### Expected behaviour

Nodes should be able to access their available/overflow bandwidth.

### Actual behaviour

Nodes cannot access their available/overflow bandwidth from lncli/gRPC.

**Comment by wpaulino** [comment] 2018-12-04 20:15
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/1639.

**Closed by wpaulino** 2018-12-04 20:15 UTC
