### ISSUE TITLE
[bug]: SubscribeInvoices not generating ACCEPTED notifications

### ISSUE THREAD

**Issue by dolcalmi** [lightningnetwork/lnd#7735] opened 2023-05-31 03:18 UTC
### Background

SubscribeInvoices is not generating an event when a hold invoice is accepted

### Your environment

* version of `lnd`: 0.16.2-beta
* operating system: Linux
* version of `bitcoind`: v24.0.1

### Steps to reproduce

Create a hold invoice and use SubscribeInvoices, you only will get an event when invoice is created or settled. You can compare using SubscribeSingleInvoice

### Expected behaviour

Events generated by SubscribeSingleInvoice must be the same for SubscribeInvoices. Not sure about the technical reasons but does not make sense, from client perspective, to have a different behavior 

### Actual behaviour

We cant use SubscribeInvoices and had to create a "hack" using SubscribeSingleInvoice to handle hold invoices. In environments with thousands of invoices (like in our case) causes performance issues https://github.com/GaloyMoney/galoy/blob/main/src/servers/trigger.ts#L438

### Related Issues/Requests

https://github.com/lightningnetwork/lnd/issues/7539
https://github.com/lightningnetwork/lnd/issues/3120
https://github.com/lightningnetwork/lnd/issues/6299

**Comment by Roasbeef** [comment] 2023-05-31 04:08
Closing as a duplicate of: https://github.com/lightningnetwork/lnd/issues/3120

Currently you need to use the `SubscribeSingleInvoice` call. The current DB formt doesn't easily allow us to also _reliably_ send out backlog notifications for invoice accept/hold events. [We're re-working things](#7354) to be much more flexible and allow behavior like this and much more.

**Closed by Roasbeef** 2023-05-31 04:08 UTC
Labels: bug, needs triage
