### ISSUE TITLE
lnd 0.15.0-beta.rc3: no second close attempt after failed cooperative close possible

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#6604] opened 2022-05-31 18:50 UTC
Copied from #6419 (which was supposed to fix this issue).

### Background

My peer asked my node to close the channel. Our nodes didn't agree on a fee rate, which is why the first attempt failed. Afterwards, I wasn't able to restart a cooperative close attempt and had to "force" close the channel.

Coop close attempt:

```
2022-05-27 23:30:53.325 [INF] CHCL: Ideal fee for closure of ChannelPoint(CHANPOINT) is: 284 sat
2022-05-27 23:30:53.325 [INF] NANN: Announcing channel(CHANPOINT) disabled [requested]
2022-05-27 23:30:53.359 [INF] CHCL: ChannelPoint(CHANPOINT): sending shutdown message
2022-05-27 23:30:53.360 [INF] CHCL: ChannelPoint(CHANPOINT): responding to shutdown
2022-05-27 23:30:53.360 [INF] CHCL: ChannelPoint(CHANPOINT): proposing fee of 284 sat to close chan
[...]
2022-05-27 23:30:58.942 [INF] CHCL: ChannelPoint(CHANPOINT): proposing fee of 804 sat to close chan
2022-05-27 23:30:59.564 [INF] CHCL: ChannelPoint(CHANPOINT): computing fee compromise, ideal=284, last_sent=804, remote_offer=1327
2022-05-27 23:30:59.564 [ERR] PEER: unable to process close msg: couldn't find compromise fee
```

Reconnecting to peer:
```
2022-05-28 10:13:04.563 [INF] SRVR: Finalizing connection to PUBKEY@IP, inbound=true
2022-05-28 10:13:04.568 [INF] PEER: NodeKey(PUBKEY) loading ChannelPoint(CHANPOINT)
2022-05-28 10:13:04.593 [INF] PEER: Negotiated chan series queries with PUBKEY
2022-05-28 10:13:05.067 [ERR] PEER: resend failed: unable to fetch channel sync messages for peer PUBKEY@IP: unable to find closed channel summary
```

### Your environment

* version of `lnd`: lnd 0.15.0-beta.rc3
* which operating system (`uname -a` on *Nix): Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23

### Steps to reproduce

Trigger coop close with lnd node, but disagree on fee.

### Expected behaviour

Channel can be (coop) closed if a second attempt at finding the fee rate succeeds.

### Actual behaviour

See above. Channel had to be "force" closed.

**Comment by Crypt-iQ** [comment] 2022-06-01 18:18
Do you have any other logs here? I was able to reproduce the log line above after a coop close restart on master, and it did complete cooperative close successfully after restart.

**Comment by C-Otto** [comment] 2022-06-01 18:37
I wasn't able to find either of those.

**Comment by Crypt-iQ** [comment] 2022-06-01 18:41
Did you send/receive any Shutdown or ClosingSigned for that channel id? Did you disconnect again with that peer or send/receive an Error?

**Comment by C-Otto** [comment] 2022-06-01 18:53
I only found the following logs, which didn't end up in the report above (sorry!):

```
2022-05-28 10:13:04.568 [WRN] PEER: ChannelPoint(C) has status ChanStatusCoopBroadcasted|ChanStatusRemoteCloseInitiator, won't start.
2022-05-28 10:13:04.583 [INF] CHCL: Ideal fee for closure of ChannelPoint(C) is: 284 sat
2022-05-28 10:13:04.583 [INF] CHCL: ChannelPoint(C): initiating shutdown
2022-05-28 10:13:04.593 [INF] CHCL: ChannelPoint(C): sending shutdown message
2022-05-28 10:13:04.593 [INF] PEER: Negotiated chan series queries with P
```

The only messages after that are related to my force-close.

**Comment by Crypt-iQ** [comment] 2022-06-01 18:58
do you know the implementation of the peer? It seems like you're not getting a shutdown in response on startup. If this is an old lnd node w/o the patch, I would expect this to happen

**Comment by C-Otto** [comment] 2022-06-01 18:59
Looks like my peer had some major issues. No idea which implementation it is/was, though: https://amboss.space/node/02530bf9cd43ebf3d32867708735b9d5c8f96af143f5f08be5bc2b7fe47a3d81c3

**Comment by Crypt-iQ** [comment] 2022-06-01 19:07
I'm going to close this since I was able to successfully test this on restart. I think your peer is an older lnd node that sent reestablish, but not shutdown

**Closed by Crypt-iQ** 2022-06-01 19:07 UTC
Labels: bug, channel closing

**Comment by C-Otto** [comment] 2022-06-03 13:02
@Crypt-iQ Just had the same issue with another peer. Finding a compromise fee failed. Afterwards `rpc error: code = Unknown desc = unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found`, although `lncli connect` states that I'm already connected to my peer. The logs don't state anything useful. I'm trying to get details from my peer.

**Comment by C-Otto** [comment] 2022-06-03 13:30
Another one. This is after the first failure:

```
2022-06-03 15:21:24.229 [INF] PEER: NodeKey(P) loading ChannelPoint(C:0)
2022-06-03 15:21:24.229 [WRN] PEER: ChannelPoint(C:0) has status ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator, won't start.
2022-06-03 15:21:24.250 [INF] CHCL: Ideal fee for closure of ChannelPoint(C:0) is: 183 sat
2022-06-03 15:21:24.250 [INF] CHCL: ChannelPoint(C:0): initiating shutdown
2022-06-03 15:21:24.261 [INF] CHCL: ChannelPoint(C:0): sending shutdown message
2022-06-03 15:21:24.261 [INF] PEER: Negotiated chan series queries with P
2022-06-03 15:21:24.312 [ERR] PEER: resend failed: unable to fetch channel sync messages for peer P@IP:PORT: unable to find closed channel summary
```

**Comment by C-Otto** [comment] 2022-06-03 21:25
Just had another example, which I think is the 4th. Is that the expected behavior? What are the requirements for this to work? Is this only supported between two nodes running lnd 0.15?

**Comment by Crypt-iQ** [comment] 2022-06-03 21:42
> Just had another example, which I think is the 4th. Is that the expected behavior? What are the requirements for this to work? Is this only supported between two nodes running lnd 0.15?

- lnd and any other implementation
- lnd 0.15 and lnd 0.15

restarting on earlier lnd versions doesn't work between any node.
