### ISSUE TITLE
Unable to query bootstrapper BOLT-0010

### ISSUE THREAD

**Issue by plasm0r** [lightningnetwork/lnd#854] opened 2018-03-16 00:40 UTC
I upgraded to v0.4 beta and now LND is reporting these errors:

2018-03-15 21:32:52.469 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2018-03-15 21:32:52.470 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]
2018-03-15 21:33:03.348 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]: dns: domain must be fully qualified
2018-03-15 21:33:03.348 [INF] DISC: Obtained 0 addrs to bootstrap network with

These messages repeat themselves over and over again in the same pattern.

I deleted my previous data folder in ~/.lnd/data before running the new version of LND for the first time. 

I'm running on Ubuntu 16.04 LTS behind a NAT firewall that is forwarding traffic on port 9735 and 18333.

I didn't get this problem with the alpha version I had been running since Jan 2018.

Any ideas?

Thanks

**Comment by Roasbeef** [comment] 2018-03-16 00:45
Duplicate of https://github.com/lightningnetwork/lnd/issues/848

The seed is purposefully not active right now to give all the preemptive old nodes on mainnet to update. This is to ensure we seed updated, healthy nodes.

**Comment by plasm0r** [comment] 2018-03-16 18:02
Ok, cool. I'm running on testnet, but I will wait. Thanks.

**Comment by Roasbeef** [comment] 2018-03-16 18:05
The testnet seed is active, but you'll need to be running the latest
version as the DNS scheme has been modified

**Comment by Roasbeef** [comment] 2018-03-17 22:59
DNS seeding for both networks should be active now.

**Comment by cpacia** [comment] 2018-03-18 07:21
fwiw I still see this same error with the 0.4 binary on linux 64 despite the dns seed returning results. Node will not bootstrap. Doesn't seem to be an addnode function is there?

**Comment by Roasbeef** [comment] 2018-03-18 22:32
Realized what the issue was from a different network, about to push a patch shortly to remedy. Those that are able to compile manually can build from master for now, we'll be making a patch release mid next week so it's resolved for all. Thanks!

**Comment by Roasbeef** [comment] 2018-03-18 23:05
Alright just pushed out the fix, this only arose if `lnd` had to fallback to direct TCP resolution. This can happen if your resolvers filter out our SRV records due to their size (they include pubkeys in addition to hosts). When I tested initially I was using a resolver that didn't filter out the records so this issue wasn't apparent.

**Closed by Roasbeef** 2018-03-18 23:05 UTC
Labels: discovery

**Comment by cpacia** [comment] 2018-03-19 12:29
I was able to patch it by adding a `.` to the end of the domain names since there I was getting was the name was not a fully qualified domain name. Not sure if that's how you fixed it or not, but that did work.

**Comment by Roasbeef** [comment] 2018-03-19 20:30
Yep if you look at the commit above, that's what the fix was! Note that this was only the case if your resolver filtered out the regular UDP query, and we had to fallback to TCP.

**Comment by plasm0r** [comment] 2018-03-19 22:07
Thanks! I rebuilt from latest source and its working perfectly now.
