### ISSUE TITLE
[wallet|sweep] Force-Closes still remain in waiting_to_close although confirmed onchain

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#6433] opened 2022-04-20 08:11 UTC
### Background

Helping a node operator, he had several channels in the category `waiting_close_channels`, which as far as I understood are there until the closure is seen onchain. However, his Transaction are already confirmed for more than 4000 Blocks and channels still remain marked as waiting_close_channels. After several restarts and also a wallet rescan nothing tends to help. My question is how I can somehow trigger lnd in a state where it checks relevant blocks again and sees the transaction onchain. Because right now there are a lot of funds locked in limbo (including htlcs which went onchain)

### Your environment

* version of `lnd`: 0.14.2-beta 
* version of  `bitcoind` : v 22.0

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

lnd recognizes the spend channelfunding and sweeps the relavant outputs that belong to oneself.

### Actual behaviour

Funds are not swept bc lnd keeps them in waiting_close_channels

**Comment by ziggie1984** [comment] 2022-04-20 08:12
I know how to sweep funds out of the channeldb, but maybe there is another option we put lnd into, where it reconsiders scanning the chain for some outputs.

**Comment by guggero** [comment] 2022-04-20 08:19
The channels that confirmed on chain, were those force-closures? I think this might happen on an attempted coop-close which fails (known issue). My suspicion is that in such a case lnd only expects the coop-close transaction to go on chain and perhaps doesn't watch force closures anymore.

**Comment by sanjay-shah** [comment] 2022-04-20 08:34
Yes, I manually force closed the channel after 7-10 days of waiting. One of the force close example: `lncli closechannel --force --funding_txid 628ec461b48e1ca56f0400a10a2d3ae22abf39da6faf62eaa9f46b5e85fc623e --output_index 1
[lncli] rpc error: code = Unknown desc = channel is already in the process of being force closed`

**Comment by ziggie1984** [comment] 2022-04-20 08:35
Onchain Footprint are all Force-Closes

**Comment by guggero** [comment] 2022-04-20 12:05
Okay, so that matches my suspicion.
@Crypt-iQ do you think that https://github.com/lightningnetwork/lnd/pull/6419 could fix this case as well? Since it seems like currently if we expect the coop-close TX to publish we don't watch for any other spend of the funding TX on-chain.

**Comment by Crypt-iQ** [comment] 2022-04-20 12:53
We watch for force closes even if we've coop closed as otherwise some nasty things could happen. I'm guessing this is mostly cosmetic. #6419 should eliminate some cases of needing to force close when a coop close was initially attempted, but the peer could always be unresponsive and the local node may need to then force close.

**Comment by Crypt-iQ** [comment] 2022-04-20 13:11
I think we'd need debug logs before and after a restart. For some reason the channel_arbitrator (which handles channel closure) appears to be stuck

**Comment by ziggie1984** [comment] 2022-04-20 14:01
yes I opened the issue in regards of his case! So we need to analyze his logs thanks for the help so far!

**Comment by sanjay-shah** [comment] 2022-05-03 07:40
@Crypt-iQ @ziggie1984 Sorry I have been away for a while. My channels are still in the closing state. Would you like me to upload the logs here? Any specific debug info you need?

**Comment by ziggie1984** [comment] 2022-05-05 22:43
Analyzing the logs I found the following details can you take a look @Crypt-iQ:

There are several channels, I concentrate on the following one: 22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787: (https://mempool.space/address/bc1q2vgqp058js58xdm8krtlc60r0csptxp0hwscspw9zhazeze4n6ds0s8ylc) it is clearly force-closed and the local node does not sweep his portion of the funds.


```
 2303 2022-05-03 01:01:44.306 [DBG] LNWL: ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): Restoring 0 dangling remote updates
 2304 2022-05-03 01:01:44.306 [DBG] LNWL: ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): Restoring 0 local updates that the peer should sign
 2305 2022-05-03 01:01:44.306 [DBG] FNDG: ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1) with chan_id=875733ec1d6f71a4835ffcd5afcc5cf151d7cc5632c00b3cfa696a07b66b3623 not found in opening database, assuming already announced to the network

...

 2022-05-03 01:01:44.381 [DBG] CNCT: New ChainEventSubscription(id=0) for ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1)
 2395 2022-05-03 01:01:44.381 [INF] CNCT: Re-publishing force close tx(8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0) for channel 22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1
```
Does LND not check whether the broadcasting tx failed bc, it already got broadcasted and the backend will reject this transaction?

```
 2022-05-03 01:01:44.400 [DBG] CNCT: Starting chain watcher for ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1)
  2022-05-03 01:01:44.400 [DBG] NTFN: Using height hint 734689 retrieved from cache for outpoint=22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1, script=0       531000be879428733767b0d7fc69e37e2015982fbba18805c515fa2c8b359e9b instead of 727215 for spend subscription
  2022-05-03 01:01:44.400 [INF] NTFN: New spend subscription: spend_id=28, outpoint=22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1, script=0 531000be87942      8733767b0d7fc69e37e2015982fbba18805c515fa2c8b359e9b, height_hint=734689
 2670 2022-05-03 01:01:44.400 [INF] NTFN: Dispatching historical spend rescan for outpoint=22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1, script=0 531000be879428733767b0d7fc69e37e2015982fbba18805c515fa2c8b359e9b, start=734689, end=734690


....

2022-05-03 01:01:44.537 [INF] CNCT: Close observer for ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1) active

...

2022-05-03 01:01:44.626 [INF] NTFN: Historical spend dispatch finished for request outpoint=22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1, script=0 531      000be879428733767b0d7fc69e37e2015982fbba18805c515fa2c8b359e9b (start=734689 end=734690) with details: <nil>
```
```
2022-05-03 01:01:44.726 [DBG] CNCT: Starting ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) (len=2) {
 (contractcourt.HtlcSetKey) LocalHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
....

```

```
2022-05-03 01:01:44.728 [INF] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): starting state=StateCommitmentBroadcasted, trigger=chainTrigger, triggerHeight=734690
2022-05-03 01:01:44.728 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): attempting state step with trigger=chainTrigger from state=StateCommitmentBroadcasted
2022-05-03 01:01:44.730 [DBG] LNWL: ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): Restoring 0 dangling remote updates
2022-05-03 01:01:44.730 [DBG] LNWL: ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): Restoring 0 local updates that the peer should sign
2022-05-03 01:01:44.730 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): skipped deadline for dust htlc=31fda8d8f1b3e04c1cc2f0fcd36a3e10f09f84aafde73f0ab2b42d24053a2f26
2022-05-03 01:01:44.730 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): calculated deadline: 144, using deadlineMinHeight=4294967295, heightHint=734690
2022-05-03 01:01:44.730 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): pre-confirmation sweep of anchor of local commit tx 8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0
2022-05-03 01:01:44.734 [DBG] NTFN: Updated spend hint to height=734690 for unconfirmed spend request outpoint=7f5120d28e4ac79082229536e28a66729e905b6a9aec831536a8878641742ffd:1, script=0 9c60865d35911558c6e81d2c7e7500eb26aa91fe371936b8125e338d9a46ac4a
2022-05-03 01:01:44.734 [DBG] LNWL: Estimated fee rate of 250 sat/kw sat/kw is too low, using fee floor of 253 sat/kw sat/kw instead
2022-05-03 01:01:44.734 [DBG] LNWL: Returning 253 sat/kw for conf target of 144                                                                                                   2022-05-03 01:01:44.734 [INF] SWPR: Sweep request received: out_point=8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0xc0013e0570)
2022-05-03 01:01:44.734 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): skipped deadline for dust htlc=31fda8d8f1b3e04c1cc2f0fcd36a3e10f09f84aafde73f0ab2b42d24053a2f26
2022-05-03 01:01:44.734 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): calculated deadline: 144, using deadlineMinHeight=4294967295, heightHint=734690
2022-05-03 01:01:44.734 [DBG] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): pre-confirmation sweep of anchor of remote commit tx 93cd478b1bd34bbb4702310c2c959b15618f8a50d62c6b4bde4389b11badf3aa:0
2022-05-03 01:01:44.734 [DBG] SWPR: Wait for spend of 8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0
2022-05-03 01:01:44.736 [DBG] LNWL: Estimated fee rate of 250 sat/kw sat/kw is too low, using fee floor of 253 sat/kw sat/kw instead
2022-05-03 01:01:44.736 [DBG] LNWL: Returning 253 sat/kw for conf target of 144
2022-05-03 01:01:44.736 [INF] SWPR: Sweep request received: out_point=93cd478b1bd34bbb4702310c2c959b15618f8a50d62c6b4bde4389b11badf3aa:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0xc0013e0570)
2022-05-03 01:01:44.746 [DBG] NTFN: Updated spend hint to height=734690 for unconfirmed spend request outpoint=75436e6a4fb9d07c93eb971c7e3c640f4422d7d7a9ebb10b8c1059c6122cef24:1, script=0 0100c6c185a5b3c0b5e8b23884c4235cd76a7e674b8269bc65d0d396f039a490
2022-05-03 01:01:44.757 [DBG] NTFN: Updated spend hint to height=734690 for unconfirmed spend request outpoint=628ec461b48e1ca56f0400a10a2d3ae22abf39da6faf62eaa9f46b5e85fc623e:1, script=0 2a05e26a564b3097c231614a8260c3425b482d03a121ddec9576f5da7d588aca
2022-05-03 01:01:44.768 [DBG] NTFN: Updated spend hint to height=734690 for unconfirmed spend request outpoint=7a53a47fa2ee146530ac2b86945e0c8bf99f4da1b8efd28798fd2124eb29f42c:1, script=0 d251c97f5f11a60b865f38fc9ccb1f139e62c1199ee9a1a76f38607b5a6da5c9
2022-05-03 01:01:44.783 [DBG] NTFN: Updated spend hint to height=734690 for unconfirmed spend request outpoint=22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1, script=0 531000be879428733767b0d7fc69e37e2015982fbba18805c515fa2c8b359e9b
2022-05-03 01:01:44.783 [INF] NTFN: New spend subscription: spend_id=31, outpoint=8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0, script=0 9e7326fc9625615d21d605dc5c080a3ecff3954f7ba23f32d34a6f3f1917be85, height_hint=734690
2022-05-03 01:01:44.783 [INF] NTFN: Dispatching historical spend rescan for outpoint=8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0, script=0 9e7326fc9625615d21d605dc5c080a3ecff3954f7ba23f32d34a6f3f1917be85, start=734690, end=734690
2022-05-03 01:01:44.800 [INF] NTFN: Historical spend dispatch finished for request outpoint=8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0, script=0 9e7326fc9625615d21d605dc5c080a3ecff3954f7ba23f32d34a6f3f1917be85 (start=734690 end=734690) with details: <nil>
2022-05-03 01:01:44.800 [DBG] LNWL: Estimated fee rate of 250 sat/kw sat/kw is too low, using fee floor of 253 sat/kw sat/kw instead
2022-05-03 01:01:44.800 [DBG] LNWL: Returning 253 sat/kw for conf target of 144
2022-05-03 01:01:44.800 [DBG] SWPR: Skipping cpfp input 8fc2f76ed8ce00ecb42b029f09af24e4770ca0c60f8fb2cafef843b17828d2f0:0: fee_rate=253 sat/kw, parent_fee_rate=508 sat/kw
2022-05-03 01:01:44.800 [DBG] SWPR: Wait for spend of 93cd478b1bd34bbb4702310c2c959b15618f8a50d62c6b4bde4389b11badf3aa:0
2022-05-03 01:01:44.800 [INF] CNCT: ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1): trigger chainTrigger moving from state StateCommitmentBroadcasted to StateCommitmentBroadcasted

...

2022-05-03 01:02:13.948 [WRN] CHBU: Replacing disk backup for ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1) w/ newer version

...

2022-05-03 01:20:43.844 [DBG] CNCT: Stopping ChannelArbitrator(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1)

...

2022-05-03 01:24:44.267 [DBG] CHBU: Crafting backup for ChannelPoint(22366bb6076a69fa3c0bc03256ccd751f15cccafd5fc5f83a4716f1dec335787:1)
 ```

after this its repeating again.

**Comment by zanderisrael** [comment] 2023-03-24 09:46
Any solutions to this issue?

**Closed** 2024-04-22 18:20 UTC
Labels: bug, bitcoind, chain handling, needs investigation
