### ISSUE TITLE
Mobile android - "server is still in the process of starting" is taking too long

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#4930] opened 2021-01-19 18:41 UTC
### Background

cc @halseth 

I compiled LND for android. I start LND, unlock wallet, and for ~20 sec lnd does something under the hood and can't do anything useful.
It has empty wallet and zero channels, so I cant figure out how to make it startup faster.
I use connectpeer to probe f lnd is ready.
I grepped some logs:

```
2021-01-19 18:02:42.069 6904-7106/com.example.rnlnd V/ReactNativeLND: lnd unlocked ===========================================================================
...
2021-01-19 18:02:56.632 6904-7122/com.example.rnlnd I/GoLog: 2021-01-19 18:02:56.632 [ERR] RPCS: [/lnrpc.Lightning/ConnectPeer]: server is still in the process of starting
...
2021-01-19 18:03:03.206 6904-7106/com.example.rnlnd I/GoLog: 2021-01-19 18:03:03.205 [DBG] DISC: Initial historical sync completed
2021-01-19 18:03:03.206 6904-7106/com.example.rnlnd I/GoLog: 2021-01-19 18:03:03.205 [DBG] DISC: Attempting to transition 1 passive GossipSyncers to active
2021-01-19 18:03:03.207 6904-7106/com.example.rnlnd I/GoLog: 2021-01-19 18:03:03.205 [DBG] PEER: Sending GossipTimestampRange(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, first_stamp=2021-01-19 18:03:03 +000
2021-01-19 18:03:05.341 6904-7105/com.example.rnlnd I/GoLog: 2021-01-19 18:03:05.341 [DBG] SRVR: Waiting 2s before trying to locate bootstrap peers (attempt #1)
2021-01-19 18:03:06.068 6904-6946/com.example.rnlnd V/ReactNativeLND: connectPeer
2021-01-19 18:03:06.096 6904-7122/com.example.rnlnd I/GoLog: 2021-01-19 18:03:06.096 [DBG] RPCS: [connectpeer] requested connection to 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.230.56:9735
2021-01-19 18:03:06.097 6904-7106/com.example.rnlnd I/GoLog: 2021-01-19 18:03:06.096 [ERR] RPCS: [connectpeer]: error connecting to peer: already connected to peer: 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.
```

as you can see, between 'lnd unlocked' and successful peer connection there's ~20 sec, which is unacceptable for mobile usage.
As far as I can tell, all compact filters are synced long ago.

Launch args:

```
    const defaultArguments =
      '--sync-freelist --tlsdisableautofill  --maxpendingchannels=10 --debuglevel=debug ' +
      '--minchansize=1000000 --ignore-historical-gossip-filters --rejecthtlc ' +
      '--bitcoin.active --bitcoin.mainnet --bitcoin.defaultchanconfs=1 --routing.assumechanvalid ' +
      '--protocol.wumbo-channels --rpclisten=127.0.0.1 --norest --nolisten ' +
      '--maxbackoff=5s --enable-upfront-shutdown --connectiontimeout=20s' + //
      '--bitcoin.node=neutrino --neutrino.addpeer=btcd-mainnet.lightning.computer --neutrino.maxpeers=3 ' +
      '--neutrino.assertfilterheader=660000:08312375fabc082b17fa8ee88443feb350c19a34bb7483f94f7478fa4ad33032 ' +
      '--neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json  --numgraphsyncpeers=1 ' +
      '--bitcoin.basefee=100000 --bitcoin.feerate=10000 ';
```

Question 1: how can we speed it up and save 20 sec on each run?

Question 2: Given lnd is started and unlocked, how can we tell that lnd finished starting and can accept calls? I tried to use GetInfo, but it works okay even if "server is still in the process of starting" and shows that its synced to chain: true

PS. I'm aware of https://github.com/lightningnetwork/lnd/issues/3982 and its a bit different

PPS. Attached full log with debug level enabled.

[lnd_mobile_android.log](https://github.com/lightningnetwork/lnd/files/5837860/lnd_mobile_android.log)

**Comment by halseth** [comment] 2021-01-20 08:35
What is taking a lot of time here is the `server` starting up, since it in turn will start all the various subsystems within lnd. 

We could try to drill down more to figure out which subsystems are slow to start, but looking at your logs, it seems like the `ChannelRouter` adds significant to the start up time:
```shell
2021-01-19 18:02:46.203 [INF] CRTR: Examining channel graph for zombie channels
...
2021-01-19 18:03:02.228 [DBG] CRTR: Cleaning network result store.
```

The zombie pruning is iterating through the DB, and checking whether channels have "expired". There is no real reason AFAIK that we have to do this synchronously at startup, so this we can probably optimize.

For question 2 there is no easy way currently other than attempting to do the calls, I think we need #3982 to solve this properly.

Also cc @hsjoberg as he has experimented a lot with tuning lnd for fast startup on Android :)

**Comment by halseth** [comment] 2021-01-20 08:58
@Overtorment I created https://github.com/lightningnetwork/lnd/pull/4933 that you can try to see if if helps

**Comment by Overtorment** [comment] 2021-01-22 19:47
at first it looked like https://github.com/lightningnetwork/lnd/pull/4933 helped but I still occasionally get long startup times.

```
2021-01-22 19:42:21.331 16123-16172/com.example.rnlnd W/ReactNativeJS: starting...
2021-01-22 19:42:23.333 16123-16172/com.example.rnlnd W/ReactNativeJS: started
2021-01-22 19:42:26.937 16123-16172/com.example.rnlnd W/ReactNativeJS: unlocked
2021-01-22 19:43:01.839 16123-16172/com.example.rnlnd W/ReactNativeJS: ready
```

here's a log with debug level :
[lnd_mobile_android2.log](https://github.com/lightningnetwork/lnd/files/5858222/lnd_mobile_android2.log)

**Comment by halseth** [comment] 2021-01-25 08:35
This is caused by neutrino syncing to tip, which sometimes can take a few seconds: https://github.com/lightningnetwork/lnd/blob/39f51b5568646ed9cf1a0a6e1dd5d8ea4cfeb068/lnd.go#L753-L801

We could look into optimizing that such that the rest of the deamon can continue starting up in parallel.

**Comment by saubyk** [comment] 2024-10-23 17:44
closing this issue for no further traction and the express need to address

**Closed by saubyk** 2024-10-23 17:44 UTC
Labels: neutrino, P2, optimization, mobile
