### ISSUE TITLE
[ERR] LTND: Unable to start server: unable to refresh backup file

### ISSUE THREAD

**Issue by sendbitcoin** [lightningnetwork/lnd#4466] opened 2020-07-14 15:29 UTC
after upgrade to 10.0.3 lnd shuts itself down after a minute or so

checking the log i can see this:

```
2020-07-14 17:21:40.695 [INF] CHBU: Updating backup file at C:\Users\monster\AppData\Local\Lnd\data\chain\bitcoin\mainnet\channel.backup
2020-07-14 17:21:40.698 [INF] CHBU: Swapping old multi backup file from C:\Users\monster\AppData\Local\Lnd\data\chain\bitcoin\mainnet\temp-dont-use.backup to C:\Users\monster\AppData\Local\Lnd\data\chain\bitcoin\mainnet\channel.backup
2020-07-14 17:21:40.705 [ERR] LTND: Unable to start server: unable to refresh backup file: unable to update multi backup: rename C:\Users\monster\AppData\Local\Lnd\data\chain\bitcoin\mainnet\temp-dont-use.backup C:\Users\monster\AppData\Local\Lnd\data\chain\bitcoin\mainnet\channel.backup: Zugriff verweigert
2020-07-14 17:21:40.706 [INF] RPCS: Stopping RPC Server
2020-07-14 17:21:40.706 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2020-07-14 17:21:40.707 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2020-07-14 17:21:40.707 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2020-07-14 17:21:40.708 [INF] RPCS: Stopping VersionRPC Sub-RPC Server
2020-07-14 17:21:40.708 [INF] RPCS: Stopping WatchtowerRPC Sub-RPC Server
2020-07-14 17:21:40.708 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
2020-07-14 17:21:40.708 [INF] RPCS: Stopping AutopilotRPC Sub-RPC Server
2020-07-14 17:21:40.709 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2020-07-14 17:21:40.709 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2020-07-14 17:21:40.720 [INF] LTND: Shutdown complete
```

renaming channel.backup into channel.backup_old and starting lnd again seems to fix the problem... but ive had to it at least twice now already (i fixed it, then went on to upgrade RTL and rebooted and stuff and then it happened again)

I checked file permission and I have full access

**Comment by wpaulino** [comment] 2020-07-14 17:44
Duplicate of https://github.com/lightningnetwork/lnd/issues/4450. The issue has already been fixed in the master branch. If you're comfortable with using that, then feel free to do so, otherwise you'll have to wait for the `0.11.0` release.

**Closed by wpaulino** 2020-07-14 17:44 UTC
