### ISSUE TITLE
Add `spend_unconfirmed` param to `estimateFee`

### ISSUE THREAD

**Issue by lukechilds** [lightningnetwork/lnd#4764] opened 2020-11-12 09:51 UTC
In @getumbrel we want to allow users to open channels with unconfirmed outputs.

Previous discussion: https://github.com/getumbrel/umbrel/issues/303

We can do this with the `spend_unconfirmed` param in `openChannel`.

However we use `estimateFee` to provide fee estimates to the user in both sat/b and $. We do this by getting an estimation from `estimateFee` for a normal payment to a random address with the total balance we're expecting to open the channel with so LND should select the same inputs. We then add some weight to the absolute sat value to account for the extra size of a channel open TX to derive a fiat estimate.

If we enable `spend_unconfirmed` in `openChannel`, our fee estimation logic errors due to no available inputs, even though there are available unconfirmed inputs which `openChannel` will use.

Would it be possible to add a `spend_unconfirmed` param to `estimateFee` so we can still make these estimations?

I don't think it needs to take into account the feerate of the previous unconfirmed TX for CPFP style calculations or anything like that, but if it does, even better.

If this isn't something you want to implement in LND, is there a way we can do some sort of dry run with `openChannel` so we can get the size of our channel open TX with some random fee rate without broadcasting it? Then we can use that to do our fee estimation in the UI.

**Comment by jalavosus** [comment] 2020-12-06 07:20
@lukechilds I'm working on implementing this, I'll open a PR within the next couple days.

**Comment by lukechilds** [comment] 2020-12-06 09:03
@jalavosus awesome!

Might be worth waiting to hear back from the maintainers to see if they're interested in accepting this change before you spend time on it.

**Comment by jalavosus** [comment] 2020-12-07 00:07
@lukechilds I'd be an old man by the time we hear back from them 😅

**Comment by guggero** [comment] 2020-12-07 09:11
I don't see any reason why we shouldn't add this, so feel free to go ahead with the PR, @jalavosus.
Would be cool if we could add the same parameters as https://github.com/lightningnetwork/lnd/pull/4653 did, so `min_confs` and `spend_unconfirmed` to keep the RPCs as similar as possible.

One thing I do want to mention however, is that we'd like to see RPC users to transition to the new PSBT RPCs in the `walletrpc` subserver, as those allow for more control. The `EstimateFee` call is a good example: Even if you query that RPC before opening a channel, it could be (however unlikely) that the UTXOs used for the estimation are no longer unspent and the wallet will select different ones, causing the fee to be different from the estimation.

Using the PSBT calls, you would instead call the `FundPsbt` call with the desired channel output. The result is a partial transaction with the selected UTXOs, and, most importantly, those UTXOs are now locked for 10 minutes and can't be spent otherwise by the wallet. From the partial transaction you can also estimate the exact fee (because you know all input types and output types, you just need to account for the witness that's not yet in the TX, hence partial).
If the user agrees with the fee, you can just ask the `FinalizePsbt` to sign the TX and publish it.

My counter proposal therefore is: Do you want to add the `min_confs` and `spend_unconfirmed` parameters to the `FundPsbt` call in `lnrpc/walletrpc/walletkit.proto`?
I'm also fine with a PR that adds the parameters to both `EstimateFee` and `FundPsbt`.

**Comment by jalavosus** [comment] 2020-12-07 23:03
@guggero, I can take a look at adding the same params to FundPsbt. I would like to say that I appreciate you taking the time to explain how it works! I'm still a bit green with the codebase, and slowly figuring out how it all links together, so the pointers on it are appreciated :)

**Comment by jalavosus** [comment] 2020-12-08 04:53
@guggero #4845

**Comment by mrfelton** [comment] 2021-05-14 07:36
Support for this was added in https://github.com/lightningnetwork/lnd/pull/4905

**Comment by guggero** [comment] 2021-05-14 08:15
Thanks for the reminder @mrfelton!

Fixed in #4905.

**Closed by guggero** 2021-05-14 08:15 UTC
Labels: feature request, fees, rpc
