### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#2689] opened 2019-02-23 00:06 UTC
### Background

LND crashed after running for a month.  Updated to latest code. Restarted, ran for an hour and crashed.

### Your environment

* version of `lnd`: 5.2 e1382bd4fc118ba2e93b1e987f94bc1a1b1fec3d
* which operating system (`uname -a` on *Nix) Raspbian
* version of `btcd`, `bitcoind`, or other backend: BitcoinD 0.16.0
* any other relevant environment details

### Steps to reproduce

Just letting it run
Console output:
https://pastebin.com/rSjHGCsc

Log output:
https://pastebin.com/PDcvTMZZ  
(Last couple lines are from restarting to show version)

**Comment by ZapUser77** [comment] 2019-02-23 00:37
Upon restarting, not only did it crash within a few minutes, but it crash BitcoinD backend as well.  
This is the 2nd time this scenario has played out.
Upgrading BitcoinD now, to see if that fixes.

**Comment by halseth** [comment] 2019-02-25 15:38
@ZapUser77 the console output doesn't show the actual crash, just the last part of the goroutine dump. Do you have all the output from the crash?

**Comment by ZapUser77** [comment] 2019-02-26 02:34
I submitted the log output.  If there is anything else, please tell me the file name/location, and I'll submit it, if it hasn't been overwritten.
I've upgraded to BitcoinD 17.1, and LND has been successfully running for 12 hours.

**Comment by ZapUser77** [comment] 2019-03-03 15:41
Crashed again.  Before 5.2 it crashed maybe once in 6 months.  Since 5.2, it's crashed at least a dozen times.
I know I haven't presented enough information to track the bug... but if you tell me *exactly* how to get the info you need, I'll provide it promptly.

**Comment by wpaulino** [comment] 2019-03-05 18:19
It should've been shown as part of the console output. Is your console output buffered (limits output to N lines) by any chance? The panic stack trace shows before the goroutine dump you posted, so it could be that the goroutine dump is so large that your console is discarding the panic stack trace.

**Comment by ZapUser77** [comment] 2019-03-06 01:50
I copied the entire contents of the console output.  I was looking for the specific error message, but it went outside the total buffer window.

**Comment by wpaulino** [comment] 2019-03-06 01:52
In that case, look into modifying the settings of your console to temporarily have an unlimited buffer (or are a larger one) in order to get the info we need.

**Comment by ZapUser77** [comment] 2019-03-06 02:07
Ok, I've doubled the size from 1,000 lines to 2,000... will see if that catches it.

**Comment by ZapUser77** [comment] 2019-03-06 02:09
Considering all the other complaints of LND crashing Raspberry Pi on 5.2 due to 'out of memory', let's assume that's the same issue, until I have proof otherwise.

**Comment by ZapUser77** [comment] 2019-03-12 02:51
So, 2000 line buffer wasn't enough... That's one heck of a dump it's taking.
So, trying 20k buffer, hopefully that won't kill the window.

**Comment by ZapUser77** [comment] 2019-03-12 02:52
Something to note: I ran it with gossiper disabled, and it ran fine for 5 days... ran it with gossiper on, crashed in less than 48 hours.

**Comment by halseth** [comment] 2019-03-12 18:45
This is likely to the massive increase in mainnet graph size as of lately. We are aware of the issue. Closing as duplicate of #2658

**Closed by halseth** 2019-03-12 18:45 UTC

**Comment by ZapUser77** [comment] 2019-03-13 00:52
While I agree it's mostly likely an "out of memory", I whole heatedly disagree it's the "graph size recently".

The crashes *only* started after migrating to the lastest version, and the effect was quite immediate.  It's seems to be every 3 days, like clockwork, starting from the day I upgraded LND.

**Comment by wpaulino** [comment] 2019-03-13 01:01
> While I agree it's mostly likely an "out of memory", I whole heatedly disagree it's the "graph size recently". The crashes only started after migrating to the lastest version, and the effect was quite immediate.

The time when you decided to update and the graph size increasing just happened to correlate.

> Something to note: I ran it with gossiper disabled, and it ran fine for 5 days... ran it with gossiper on, crashed in less than 48 hours.

This is enough of a clue that it has to do with the graph. With the current graph size, whenever peers attempt to sync with each other's graphs, about 16,000 updates are being queued up, which is something that we didn't think would happen this soon.

> It's seems to be every 3 days, like clockwork, starting from the day I upgraded LND.

This is most likely because some peers reconnect to you within a very short time period, causing the gossip sync to be started upon every reconnection queueing all the updates I mentioned above in memory. If this happens enough, you'll run out of memory.

If you still think v0.5.2 is the issue, feel free to downgrade back to v0.5.1 and see if the crash still happens.

**Comment by ZapUser77** [comment] 2019-03-13 01:05
"If you still think v0.5.2 is the issue, feel free to downgrade back to v0.5.1 and see if the crash still happens."
I first want to gather enough info to at least make sure it's the same issue.

I'm not hear to 'complain' about the crashing.  I'm here to provide what info I can.  (Which doesn't seem to be any, since Linux is outside my area of expertise.)

Thanks for the assistance.

**Comment by hpbock** [comment] 2019-03-13 14:55
The memory usage on my node seems to correlate with the network traffic. So it seems reasonable that is caused by a lot of messages being queued up.
![image](https://user-images.githubusercontent.com/15837933/54288422-b7fa4d00-45a7-11e9-956d-9c8ed214ac28.png)
![image](https://user-images.githubusercontent.com/15837933/54288433-bc266a80-45a7-11e9-87e3-4d2fd2cbd623.png)
The question is why this happens suddenly for three or four hours and then recovers running fine again.

**Comment by ZapUser77** [comment] 2019-03-15 15:42
Yep, out of memory.

2019-03-15 18:37:12.065 [INF] HSWC: Removing channel link with ChannelID(eb21683bcb29798857d274b0485dde5215ce3e1d98a70ae60c195660d4eb98d0)
2019-03-15 18:37:12.065 [INF] HSWC: ChannelLink(d098ebd46056190ce60aa7981d3ece1552de5d48b074d257887929cb3b6821eb:0) is stopping
runtime: out of memory: cannot allocate 409600-byte block (963903488 in use)
fatal error: out of memory

Gig of ram... plus 2 gig of cache... sounds like a mem-leak...  Pesky things to hunt down.
