### ISSUE TITLE
`UnknownNextPeer` instead of `ChannelDisabled`

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#3546] opened 2019-09-27 12:21 UTC
Currently when next peer in a route is offline LND replies with `UnknownNextPeer` while it would be reasonable to expect a more appropriate `ChannelDisabled`. 

This happens with https://1ml.com/testnet/node/03236a685d30096b26692dce0cf0fa7c8528bdf61dbf5363a3ef6d5c92733a3016.

**Comment by cfromknecht** [comment] 2019-09-27 23:15
A peer can be offline without having its channel actually disabled via a `channel_update`. Sending `ChannelDisabled` also leaks more info about private channels since on can test if the channel belongs to the forwarder.

**Comment by btcontract** [comment] 2019-09-28 04:24
OK, fired it mean `ChannelDisabled` is sort of deprecated?

**Comment by cfromknecht** [comment] 2019-09-28 07:41
Idk about that, but LND currently doesn’t send `ChannelDisabled` anywhere or restrict channel usage if it is disabled in the latest channel update. Currently it is only used as a hint to the sender to avoid using the channel.

**Comment by btcontract** [comment] 2019-09-30 14:22
Reopening because there was a discussion about this at https://gitter.im/ACINQ/developers?at=5d91c71d086a72719e8b7860 and seems like this might be not that a good solution.

**Comment by cfromknecht** [comment] 2019-10-01 03:18
> I'd agree that fooling sender like this is not justified, my understanding is UnknownNextPeer can be interpreted as "never try that channel again, it does not exist anymore" so there could be some harm in doing this

> Exactly, so we'll need to take into account on our side that they're doing this and that UnknownNextPeer must not be mapped to an unrecoverable failure otherwise some payments might not succeed because we banned a channel that was just temporarily offline...

Interesting, it could very well be the case that eclair/blw has a non-negligible portion of the graph banned because of this. This has been in lnd for as long as I can remember 😬

Looking at it now, i see that `UnknownNextPeer` is a PERM failure in the spec, so there is probably a better alternative.

> That's why I believe sending ChannelDisabled makes more sense because it's more useful to the network as it improves routing (UnknownNextPeer makes it look like the sender made a mistake and included an invalid channel in the path).

I still don't see why we would send `ChannelDisabled` if the channel isn't actually disabled. Otherwise the `ChannelDisabled` error will contain an update that is enabled, which doesn't make any sense.

To be honest, the spec just doesn't have an error for a peer being offline + enabled. For instance, lnd never disables unadvertised channels, so we'd still need an error to send in that case.

If we are all going to be treating `UnknownNextPeer` as transient for backwards compatibility, one option is to have the spec also send this for offline + enabled. However, I think in this case it makes more sense to add a proper transient error and fill this gap in the spec. Hadn't considered this before, but I can see how a permanent `UnknownNextPeer` error is useful in the context of pruning channels on mobile nodes. I assume this is why eclair blacklists in response?

**Comment by cfromknecht** [comment] 2019-10-01 03:18
Do you know if CL treats this as a permanent or transient failure?

**Comment by Roasbeef** [comment] 2019-10-01 04:13
> Do you know if CL treats this as a permanent or transient failure?

CL has the same behavior as us, if the peer isn't online, or they are, but the channel isn't fully confirmed yet, then they'll send `UnknownNextPeer`.

**Comment by btcontract** [comment] 2019-10-01 11:39
> Interesting, it could very well be the case that eclair/blw has a non-negligible portion of the graph banned because of this

This is indeed the case with BLW, although there are countermeasures so it's not as bad as it could be (for example, if previously banned channel is present in invoice route hints then that channel gets unbanned for that particular payment).

**Comment by cfromknecht** [comment] 2019-10-02 00:01
@btcontract so a destination's channels may be unbanned, but a routing node's would likely stay banned?

What are your thoughts on filling in the spec gap with a new error type?

**Comment by btcontract** [comment] 2019-10-02 19:55
> so a destination's channels may be unbanned, but a routing node's would likely stay banned?

In BLW yes, for routing purposes it will get banned. It seems to have minimal effect since routing full nodes tend to stay online and for mobile receiver hints the ban is lifted, but of course this is not the best possible state of affairs.

I don't quite understand why can't a `ChannelUpdate` be marked as disabled after channel becomes offline? The way Eclair does this is each `Channel` stores the latest `ChannelUpdate`, once someone tries to route through that channel after connection is lost a new `ChannelUpdate` is generated with `disabled=true`, and it gets included in `ChannelDisabled` response, so it's always disabled there.

**Comment by cfromknecht** [comment] 2019-10-03 02:23
> I don't quite understand why can't a ChannelUpdate be marked as disabled after channel becomes offline? 

We used to do this, and found at scale it leads to a lot of wasted bandwidth and chose to dampen how often we transition between enabled and disabled. Currently lnd waits about 20 minutes before fully disabling a channel to prevent small aberrations in connectivity, e.g. nodes restarting, from flooding the network.

A considerable amount of time for 0.6 was spent migrating away from aggressive disabling, and I'd be hesitant to reopen pandora's box by going back in that direction. It's not that it can't be done, but I think are a number of reasons why implementations would choose a different heuristic for disabling that would steer them away from this approach. Using a different error that means "try again later" is a much simpler change that won't unnecessarily pollute the gossip network with traffic from unstable peers.

**Comment by Roasbeef** [comment] 2019-10-16 09:59
Closing as we don't plan to change behavior in this area. A channel disable will only be sent after the peer is persistently offline.

**Closed by Roasbeef** 2019-10-16 09:59 UTC
