### ISSUE TITLE
Channels sometimes get disabled and re-enabled even when active

### ISSUE THREAD

**Issue by rkfg** [lightningnetwork/lnd#6000] opened 2021-11-18 13:24 UTC
### Background

Continuation of #5980. I found out that sometimes channels get disabled 22 minutes after the peer has disconnected even though that peer reconnected shortly after that and before 22 minutes passed. The channel is re-enabled in a few minutes after (0-4 minutes in my case) but the "channel disabled" announcement is already broadcasted at that point which causes long period of channel being unavailable from me for the rest of the network.

### Your environment

* version of `lnd`: `v0.14.0-beta.rc4`
* which operating system (`uname -a` on *Nix): `5.10.63-v8+ aarch64`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind 22.0`
* maybe relevant settings:
```
minbackoff=1s              
maxbackoff=1m
caches.reject-cache-size=10000000
caches.channel-cache-size=1000000
```

### Steps to reproduce

```
Nov 16 02:08:42 fullnode lnd[384677]: 2021-11-16 02:08:42.852 [INF] PEER: disconnecting 032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b@185.107.47.215:43864, reason: peer 032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b@185.107.47.215:43864 no answer for 5m0s -- disconnecting
Nov 16 02:08:42 fullnode lnd[384677]: 2021-11-16 02:08:42.852 [INF] PEER: unable to read message from 032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b@185.107.47.215:43864: read tcp 10.40.0.2:9735->185.107.47.215:43864: use of closed network connection
Nov 16 02:08:43 fullnode lnd[384677]: 2021-11-16 02:08:43.053 [INF] DISC: Removing GossipSyncer for peer=032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b
Nov 16 02:08:43 fullnode lnd[384677]: 2021-11-16 02:08:43.054 [INF] HSWC: Removing channel link with ChannelID(3a0fba1fc7537792c1a9105030bc63c9d0931513b37a9d1ea6b7b2d6c878c928)
Nov 16 02:08:43 fullnode lnd[384677]: 2021-11-16 02:08:43.054 [INF] HSWC: ChannelLink(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5): stopping
Nov 16 02:08:43 fullnode lnd[384677]: 2021-11-16 02:08:43.054 [INF] HSWC: ChannelLink(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5): exited
```
Okay, a peer timed out. Happens sometimes. Now lnd should wait for 22 minutes until it declares the channel disabled. Let's see what happens next:
```
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.463 [INF] SRVR: New inbound connection from 185.220.100.243:28548
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.463 [INF] SRVR: Finalizing connection to 032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b@185.220.100.243:28548, inbound=true
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.660 [INF] PEER: NodeKey(032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b) loading ChannelPoint(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5)
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.672 [INF] HSWC: Removing channel link with ChannelID(3a0fba1fc7537792c1a9105030bc63c9d0931513b37a9d1ea6b7b2d6c878c928)
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.673 [INF] HSWC: ChannelLink(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5): starting
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.673 [INF] HSWC: Trimming open circuits for chan_id=695110:1597:5, start_htlc_id=568
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.673 [INF] HSWC: Adding live link chan_id=3a0fba1fc7537792c1a9105030bc63c9d0931513b37a9d1ea6b7b2d6c878c928, short_chan_id=695110:1597:5
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.673 [INF] HSWC: ChannelLink(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5): HTLC manager started, bandwidth=1478031069 mSAT
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.673 [INF] HSWC: ChannelLink(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5): attempting to re-synchronize
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.673 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5)
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.674 [INF] NTFN: New block epoch subscription
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.674 [INF] PEER: Negotiated chan series queries with 032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b
Nov 16 02:12:27 fullnode lnd[384677]: 2021-11-16 02:12:27.674 [INF] DISC: Creating new GossipSyncer for peer=032261d6ec5fb578919e2455f2061d27bd93df57b26d78cdf7bad38f1368d0531b
Nov 16 02:12:28 fullnode lnd[384677]: 2021-11-16 02:12:28.049 [INF] HSWC: ChannelLink(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5): received re-establishment message from remote side
```
The channel seems to be working now. However:
```
Nov 16 02:30:21 fullnode lnd[384677]: 2021-11-16 02:30:21.431 [INF] NANN: Announcing channel(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5) disabled [detected]
```
18 minutes later it's announced as disabled (???) even though it was working at that moment. This timestamp `02:30:21` is 22 minutes later the moment the channel died due to peer disconnecting after timeout (`02:08:43`). Could it be a timer not being cancelled if the channel reconnects? This channel is reenabled a minute later:
```
Nov 16 02:31:27 fullnode lnd[384677]: 2021-11-16 02:31:27.675 [INF] NANN: Announcing channel(2dc978c8d6b2b7a61e9d7ab3131593d0c963bc305010a9c1927753c71fba0f3a:5) enabled
```
I have many such occurrences in the log, they all share the same properties:
1. Peer disconnects for whatever reason, channel link stops
2. Peer reconnects, channel link becomes active again
3. 22 minutes after `1.` happened channel gets disabled
4. Channel gets re-enabled in a few minutes (0-4) after `3.`

It can't be explained by channels flapping for a while. They clearly behave normally for hours, then disconnect/reconnect once and then get disabled and enabled after that even though they should be perfectly working.

### Expected behaviour

Channel should only be disabled if the peer disconnected (or the channel link exit for any other reason) and was down for `chan-disable-timeout` time (22 minutes by default).

### Actual behaviour

Sometimes (but not always!) a channel is marked as disabled 22 minutes after the peer disconnected even though that peer connected shortly after disconnect (before 22 minutes passed).

**Comment by yyforyongyu** [comment] 2021-12-09 09:31
@rkfg Does this still happen? Do you happen to have any logs with `debug` turned on?

**Comment by rkfg** [comment] 2021-12-09 10:26
Yes, it happens regularly several times a day. What subsystem should I increase the verbosity for? DISC and/or NANN?

**Comment by C-Otto** [comment] 2021-12-09 11:27
I also experience that some of my channels are known as "disabled" in the network although they are enabled, even hours after the last state change / reconnect to the peer at the other side of the channel.

**Comment by viaj3ro** [comment] 2021-12-09 11:29
One of those disabled channels from @C-Otto was to my node. In case my logs are of any use, please ping me and let me know

**Comment by yyforyongyu** [comment] 2021-12-09 12:01
@rkfg Would you mind patching [this PR](https://github.com/lightningnetwork/lnd/pull/6074) to your `lnd`? This PR adds more debugging logs, and commits in it are cherry-picked from other PRs which are attempting to fix issues as such.

After which, I'd say just turn on `debug` for the whole node for a while and send me the logs.

Thanks!

**Comment by yyforyongyu** [comment] 2021-12-09 20:39
Thanks for the logs!

Looks like there's issue with the peer `03271338633d2d37b285dae4df40b413d8c6c791fbee7797bc5dc70812196d7d5c`. Do you happen to know whether it's online during that time?

And could you search the logs for `Created ChanStatusManager with: ChanEnableTimeout` and post it here?

I think there's something wrong with the peer connection, will post a detailed report here tomorrow. In short, we require the node the send a `ChanSync` message to ensure the liveness of the channel, but it appeared there's connection issue with the peer which caused a delay, and the channel is marked disabled first and then enabled again.

**Comment by rkfg** [comment] 2021-12-10 06:26
>  Do you happen to know whether it's online during that time?

I suppose it was online all the time, it's LNMarkets and they were online before I restarted my lnd. Doubt we both went down at the same time.

> And could you search the logs for `Created ChanStatusManager with: ChanEnableTimeout` and post it here?

I couldn't find that message in the yesterday's logs but I disabled debugging shortly after I sent these logs above, there's a lot of data generated from that. I re-enabled debug now and will look for it.

**Comment by rkfg** [comment] 2021-12-10 15:52
The amount of logs generated is enormous and grepping them takes a lot of time. In just 6 hours it logged about 6 Gb I think. I couldn't find the message you mentioned but no channels were disabled since either.

I'm afraid I have to turn logging back to `INFO` unless there's an important reason to catch it. These events usually happen daily but not very often, like 2-3 times a day so waiting for them takes time and systemd's logs are extremely slow to parse and even open. Maybe you can reduce this verbosity to the bare minimum so they're still useful but not as I/O hungry? Or maybe someone else can do that like @C-Otto and @viaj3ro.

**Comment by C-Otto** [comment] 2021-12-10 16:30
Maybe it helps to look at a very concrete example: 782139795591397377 (c-otto.de to SilentBob (@viaj3ro)) is enabled on both sides according to my lnd, but the network doesn't see this. Instead, the network believes that I disabled the channel.

**Comment by rkfg** [comment] 2021-12-10 16:43
This channel looks like this on my side:
```
{
    "channel_id": "782139795591397377",
    "chan_point": "9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1",
    "last_update": 1639136582,
    "node1_pub": "027ce055380348d7812d2ae7745701c9f93e70c1adeb2657f053f91df4f2843c71",
    "node2_pub": "02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844",
    "capacity": "20000000",
    "node1_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "233",
        "disabled": true,
        "max_htlc_msat": "5000000000",
        "last_update": 1639136582
    },
    "node2_policy": {
        "time_lock_delta": 50,
        "min_htlc": "1",
        "fee_base_msat": "100",
        "fee_rate_milli_msat": "349",
        "disabled": false,
        "max_htlc_msat": "20000000000",
        "last_update": 1639123426
    }
}
```
As you can see my last_update is 7 seconds older and yours never made it to my node (I don't have channels to you but it doesn't really matter in this case) so I see this channel as disabled from one side. It will stay like this for hours I suppose and there's no way to use it in one direction until the more recent policy version is propagated.

Look in your log for the word `disabled`, then see if it was enabled shortly after that, then look if there was a disconnection ~20-22 minutes before it got disabled, then look if it was reconnected between that disconnection and announcing that it was disabled. The network rate limits these messages, so this `channel disabled` update can stall for a while (up to 24 hours?) if it went out. I described this problem in #5980 but later found this weird behavior which causes this whole issue. When it's fixed the channels will get disabled much less often and the overall network stability and liquidity should increase. 22 minutes are plenty of time to reconnect even when Tor slows down or drops connections.

**Comment by C-Otto** [comment] 2021-12-10 16:52
These are the recent log entries. According to @joostjager the channel was disabled two days ago, see screenshot below.

```
2021-12-05 11:06:38.688 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) disabled [detected]
2021-12-05 11:06:41.011 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) enabled
2021-12-05 14:08:23.193 [DBG] NANN: Channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) already enabled, canceling scheduled disable
2021-12-05 17:37:40.492 [DBG] NANN: Channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) already enabled, canceling scheduled disable
2021-12-08 11:14:52.123 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) disabled [detected]
2021-12-08 11:15:24.316 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) enabled
2021-12-08 15:27:31.031 [DBG] NANN: Channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) already enabled, canceling scheduled disable
2021-12-10 12:43:02.254 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) disabled [detected]
2021-12-10 12:43:09.022 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) enabled
```

![msg-1609571733-778](https://user-images.githubusercontent.com/344948/145611248-2c2fb152-d4af-46d5-abb2-7370cb83a904.jpg)

**Comment by C-Otto** [comment] 2021-12-10 16:59
Reconnections:

```
2021-12-05 10:47:40.972 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-05 13:49:23.171 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:65308, inbound=true
2021-12-05 16:55:09.526 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:49699, inbound=true
2021-12-05 17:18:40.446 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-05 22:05:11.901 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-07 07:23:43.347 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-07 22:07:44.803 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-08 10:56:24.279 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-08 15:08:30.986 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:9735, inbound=false
2021-12-08 21:13:23.413 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:55009, inbound=true
2021-12-10 12:22:37.474 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:64461, inbound=true
2021-12-10 12:24:09.010 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:64475, inbound=true
2021-12-10 16:39:32.899 [INF] SRVR: Finalizing connection to 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:50131, inbound=true
```

**Comment by rkfg** [comment] 2021-12-10 17:21
Yeah, it matches the logs. This is what my timestamp corresponds to:
```
2021-12-10 12:43:02.254 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) disabled [detected]
```
And this is yours, exactly 7 seconds later (I never received this update):
```
2021-12-10 12:43:09.022 [INF] NANN: Announcing channel(9586812797de75d4e81c87ec8de045adc2c833b4cf81bc5d5e8dc814e562b71f:1) enabled
```
The disconnection timestamp roughly matches, 24 minutes before disabling:
```
2021-12-10 12:18:55.548 [INF] SRVR: Disconnecting from 02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844@31.16.52.37:55009
```
And reconnect happened between `12:18:55` and `12:43:02` so the channel should be active at the moment it was wrongfully disabled.

**Comment by C-Otto** [comment] 2021-12-10 17:51
I see, but I don't really understand. The "enabled" message didn't get propagated for some more-or-less valid reason (anti-spam?). However, the channel should not have been disabled in the first place?

**Comment by rkfg** [comment] 2021-12-10 20:23
Correct and correct!

**Comment by viaj3ro** [comment] 2021-12-10 20:47
It keeps happening and is impacting routing quite a bit. Fixing this should be high priority imho.

**Comment by viaj3ro** [comment] 2022-02-15 09:11
I keep having this issue with LND peers. Why is this not being fixed?

**Comment by agd-media** [comment] 2022-02-22 12:00
> I keep having this issue with LND peers. Why is this not being fixed?

As a workaround you can change the fee to enable a channel if your node is the one which disabled it.

**Comment by rkfg** [comment] 2022-11-24 21:04
This issue is still happens. It's relatively easy to reproduce if you simply restart `lnd` and look in `lntop`. You will see multiple node disabling their channels to you even if you were offline for 5 minutes. Screenshot (arrows pointing down mean the channel disabled by the peer, those channels were enabled before the restart):
![2022-11-24_23-41-12](https://user-images.githubusercontent.com/184066/203860931-ab8336ca-ee93-4eea-9a88-181637503117.png)

Also! Looks like I found the true reason of this happening from the comments in the config. This default behavior is very wrong imo (if I understand it correctly).

```
; The duration that a peer connection must be stable before attempting to send a
; channel update to re-enable or cancel a pending disables of the peer's channels
; on the network. (default: 19m0s)
; chan-enable-timeout=22m

; The duration that must elapse after first detecting that an already active
; channel is actually inactive and sending channel update disabling it to the
; network. The pending disable can be canceled if the peer reconnects and becomes
; stable for chan-enable-timeout before the disable update is sent.
; (default: 20m0s)
; chan-disable-timeout=22m
```
So what gives? The key is `The pending disable can be canceled if the peer reconnects and becomes stable for chan-enable-timeout before the disable update is sent`! However, they differ only by 1 minute. Which means if you were offline for more than 1 minute _you will never make it_. The disable timer is 20 minutes by default and it's only cancelled if you were online for 19 minutes, otherwise the `channel disabled` message is broadcasted. The `channel enabled` message _might_ broadcast next (19 minutes after you went online) but as we discussed above it might get rate limited and those limits are pretty severe so the channel gets disabled for 24 hours actually.

This looks like a very bad design to me that results in these absolutely unnecessary channel blocks for a long time. A naive and suboptimal solution would be changing the defaults (I doubt anyone tweaks these settings) so that `chan-enable-timeout` is _much_ lower than `chan-disable-timeout`, allowing quick restarts (on RPi they might take minutes). But a proper solution (as I see it) is to check if the peer is online _before_ sending the channel disabled message, then delaying this message if the peer stays online and cancelling it altogether if it's online for `chan-enable-timeout` duration. However, if the peer goes offline again during this grace period we should disable the channel and broadcast the message. This logic is less trivial than the existing one but I believe it's worth implementing. To illustrate how it works now (again, if I understand it right):

1. peer goes offline, `chan-disable-timeout` (20 minutes) starts
2. 5 minutes pass
3. peer comes online, `chan-enable-timeout` (19 minutes) starts
4. 15 more minutes pass
5. here we send the disable channel message because the enable timer didn't fire
6. 4 minutes pass
7. we send the enable channel message as the peer was stable for 19 minutes but this message gets rate limited by our peers and the network is stuck with this channel disabled for 24 hours

What it should be imo:
1. peer goes offline, 20 minute disable timer starts
2. 5 minutes pass
3. peer comes online, 19 minute enable timer starts
4. 15 more minutes pass
5. we see that the peer is online and _somehow_ delay the channel disabled message instead of sending it immediately, we give the peer a chance to prove it's not flapping

Now two things can happen:

7. 4 minutes pass, peer is still online
8. `chan-enable-timeout` fires
9. the delayed message is cancelled, the network is never notified about this incident, some forwardings might have failed but the channel is still seen as enabled by everyone

OR:

7. 2 minutes pass, peer goes offline again => peer is unstable!
8. we send the channel disabled message immediately and cancel all those timers

Please tell me if it makes sense and if I understand it right.

**Comment by rkfg** [comment] 2022-11-24 21:48
Another thing is why this update gets stuck. There are two options that control gossip rate limiting:
```
; The maximum number of updates for a specific channel and direction that lnd
; will accept over the channel update interval.
; gossip.max-channel-update-burst=10
; gossip.channel-update-interval=1m
```
Which means that we receive 1 non-keepalive (=with different fee/htlc size policy or channel being enabled/disabled) update per minute but can burst it up to 10 (i.e. 10 updates in 1 minute, then we drop all updates until the rate limiting bucket refills). Could it be that this rate limiter is drained quickly because I receive updates for the disabled channel through my other peers (I have about 50)? And because of that when it gets enabled again this message is ignored due to rate limiting?

I will test again in a few days after my currently disabled channels re-enable so I can set the `DISC` log level to `debug`, restart lnd and see if it rate limits some updates. `DISC` generates a lot of spam though, all updates for all channels in the network, hard to find what I need.

**Comment by yyforyongyu** [comment] 2022-11-25 03:28
@rkfg very detailed analysis! I think your understanding is correct, and I happened to look into these areas lately while fixing itest, particularly [this `testUpdateChanStatus`](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_channel_graph_test.go#L24). 

> Could it be that this rate limiter is drained quickly because I receive updates for the disabled channel through my other peers (I have about 50)? And because of that when it gets enabled again this message is ignored due to rate limiting?

No you won't. The rate limiter limits the channel updates `per channel per direction`, which I want to change into `per channel per relaying node per direction`, which requires a spec change. Meanwhile, you can view every channel update as uniquely identified by the combination of `channel ID + direction + timestamp`. So even if multiple peers send you the same channel update, only one will be taken into account by the rate limiter and the rest will be ignored.

> we send the enable channel message as the peer was stable for 19 minutes but this message gets rate limited by our peers and the network is stuck with this channel disabled for 24 hours

This would only happen if it's been rate limited. By default it's 10 updates per minute, which means technically we allow our channel peer to go online and offline 5 times per minute. I think that is a lot. I also think this may not be a good peer.

> we see that the peer is online and somehow delay the channel disabled message instead of sending it immediately, we give the peer a chance to prove it's not flapping

I believe there are multiple ways to achieve this. We can increase our burst limit, increase disable timeout, or decrease enable timeout. But my question is, to what degree? Suppose we have this preposterous setup where`chan-disable-timeout=60m, chan-enable-timeout=10m, --chan-status-sample-interval=1s`, if the peer is offline for 59 minutes and comes back, do we pause disabling the channel and wait for 10 minutes to see it enabled?

> the delayed message is cancelled, the network is never notified about this incident, some forwardings might have failed but the channel is still seen as enabled by everyone

I think it's better to notify the network, otherwise, this channel will be attempted and failed, causing it to be less likely to be used again. This is probably an implementation-specific algorithm, but I think in general when a channel edge fails, it will be assigned a lower success probability score during the next attempt. If it's disabled, then it won't be attempted and the probability stays unchanged during the next attempt. 

That being said, although I don't know the original ideas behind the default values, I think it's intentional,
```
chan-status-sample-interval=1m
chan-disable-timeout=20m
chan-enable-timeout=19m
```
- suppose the peer goes offline at 00:00.
- `00:01`: 1 minute sample interval later, the chan disable timer starts.
- `00:00+x`: `x` minutes later, the peer goes online.
- `00:21`: 20 minutes later when disable timer started, chan disabled.
- `00:19+x`: and 19 minutes later when the peer went online, chan enabled.

Thus we always notify the network about the peer's offline behavior. Basically, when a peer goes offline and online again, we will wait y minutes to enable it again, where y is,

- `y = x - chan-status-sample-interval - chan-disable-timeout + chan-enable-timeout`

**Comment by yyforyongyu** [comment] 2022-11-25 03:45
> I will test again in a few days after my currently disabled channels re-enable so I can set the DISC log level to debug, restart lnd and see if it rate limits some updates. DISC generates a lot of spam though, all updates for all channels in the network, hard to find what I need.

Would suggest patching #7186 as it refactored the logging in `DISC` to make it more useful. And #7157 may be a related fix.

**Comment by rkfg** [comment] 2022-11-25 06:29
Thank you for this explanation. I don't really care if the channel is disabled/enabled quickly as long as the enabled message actually goes out and propagate. So far it's not always the case.

> if the peer is offline for 59 minutes and comes back, do we pause disabling the channel and wait for 10 minutes to see it enabled?

I suppose, yes. The idea is to only disable if the peer was consistently offline longer than the disable timeout. If it went online even shortly before that we should give it a chance and not spam the network with these updates only to send another update again soon. But if it fails our expectations and goes offline before that 10 minutes interval ends (from your example) **and** the disable timer has already run out (but it kinda follows from my proposition) then we disable immediately.

I don't remember who gave me that idea of rate limiting that might prevent updates from propagating for a long time but probably it was https://github.com/lightningnetwork/lnd/issues/5980#issuecomment-969607147. Hopefully that issue, which was quickly closed without proper investigation, will also be solved with these PRs as it sounds like exactly what we need.

**Comment by joostjager** [comment] 2022-11-25 07:22
Haven't read this thread in full detail, but on the surface it reminds me of https://github.com/lightningnetwork/lnd/issues/7073. I had propagation issues too, and applied a patch that fixed it for me.

**Comment by rkfg** [comment] 2022-11-25 07:32
Yes, looks familiar. I find the rate limiting excuse kinda silly (unless I missed something), it only skips updates if they happen more often than 1 per minute and it allows 10 consequent updates faster than that if they average to 1/min eventually (to put it simply). I find it hard to believe people would update their policies faster than once a minute, it's rather once an hour or so or even less frequent. Closing the issue because it's somehow explained by that isn't good imo, I'm glad you kept digging.

**Comment by saubyk** [comment] 2023-11-28 04:06
Assuming there is no specific action here and the issue is addressed. Haven't read through the complete thread, but the prs linked in the comments as patch suggestions etc. are all merged.

Pleas reopen if the issue persists. thanks.

**Closed by saubyk** 2023-11-28 04:06 UTC
Labels: discovery, missing reproduction
