### ISSUE TITLE
/v1/invoices/ REST apis ordering issue?

### ISSUE THREAD

**Issue by mandelmonkey** [lightningnetwork/lnd#515] opened 2017-12-24 13:41 UTC
Seems that all variations of the /v1/invoices/ are always being interpreted as  /v1/invoices/{pending_only}

so if I called /v1/invoices/{r_hash_str} or v1/invoices/subscribe
response is
```
"error": "type mismatch, parameter: pending_only, error: strconv.ParseBool: parsing \"4192149879b714f452e5b5270de0606a1c02a597e6beb0b01db35cd140c05d39\": invalid syntax",
    "code": 3
```

**Comment by Richard87** [comment] 2017-12-29 17:26
Just had the same error on my setup:

```
GET https://lightningsale:***@lnd:8080/v1/invoices/b5d6a5de54a4e5519dccd7d0ececc772f3e67781882933617f7d31c05a962de5` resulted in a `400 Bad Request` response:
{"error":"type mismatch, parameter: pending_only, error: strconv.ParseBool: parsing \"b5d6a5de54a4e5519dccd7d0ececc772f3e67781882933617f7d31c05a962de5\": invalid syntax","code":3}
```

**Comment by ndeet** [comment] 2018-01-01 21:59
Hi there, sorry, saw your issue after opening a new issue #544 myself. I think the problem is that the endpoints are overlapping and not unique and causing this errors. See #544

**Comment by halseth** [comment] 2018-01-02 08:28
Dupe of #544

**Closed by halseth** 2018-01-02 08:28 UTC
