### ISSUE TITLE
BOLT 11 invoices for regtest should use `lnbcrt` prefix

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lnd#1055] opened 2018-04-09 08:09 UTC
### Background

Ran into this while trying to automate the integration testing framework. `lnd` generates (and accepts only) invoices with the prefix `lntb` in regtest mode, while eclair and c-lightning use the `lnbcrt` prefix. This causes `lnd` to abort when attempting to pay such an invoice with `(StatusCode.UNKNOWN, unknown network)`.

### Your environment

* version of `lnd`: 13945de8060ad42e077988c1cf69e205dc11e528

### Steps to reproduce

See implementation of [test_direct_payment](https://github.com/cdecker/lightning-integration/blob/09c167a566a63ce1f93abc6707fc69a768378e41/test.py#L271-L296) for an example.

### Resolutions

Admittedly the clarification to use `lnbcrt` as prefix is still under review (lightningnetwork/lightning-rfc#397), but this should be easy to resolve by either allowing `lnbcrt` as a prefix for regtest invoices, or by switching regtest to use `lnbcrt` exclusively.

**Comment by halseth** [comment] 2018-04-09 10:08
Duplicate of #882

**Closed by halseth** 2018-04-09 10:08 UTC

**Comment by cdecker** [comment] 2018-04-09 15:47
Sorry about the duplicate :wink:

**Comment by Roasbeef** [comment] 2018-04-09 19:42
As a work around for now, you can use `sendpayment` to just manually specify all the payment details encoded in the invoice.

**Comment by cdecker** [comment] 2018-04-10 11:47
Thanks @Roasbeef I have some patches that I apply when testing, one of them just hard-codes the `bcrt` prefix. I hope it doesn't result in a large change, the prefix being sourced from the `btcd` dependency. Otherwise I can make the permanent change to call `sendpayment` and we can just keep this tiny incompatibility.

**Comment by cdecker** [comment] 2018-04-10 12:35
Having a bit of trouble with the direct lnd-lnd payment, sendpayment seems to drop the `final_cltv_delta` value for some reason.

Printing the SendPaymentRequest before sending it to `lnd`:
```
dest: "\002iH\334\255\ri\0217\303\260R\304;\307\221\340\205\2058F\260\264\017M\324~8\240&K\033\313"
dest_string: "026948dcad0d691137c3b052c43bc791e085853846b0b40f4dd47e38a0264b1bcb"
amt: 1000
payment_hash_string: "90d4ac8543ca3dc20fb4b8d16a9e63168f3fb8202ce4d08f7532fd8824636ab2"
final_cltv_delta: 9
```
What `lnd` reports in its logs:
```
DEBUG:lnd(16331):2018-04-10 14:31:36.812 [TRC] CRTR: Dispatching route for lightning payment: (*routing.LightningPayment)(0xc420708e00)({
DEBUG:lnd(16331): Target: (*btcec.PublicKey)(0xc4207d07e0)({
DEBUG:lnd(16331):  Curve: (elliptic.Curve) <nil>,
DEBUG:lnd(16331):  X: (*big.Int)(0xc4207d0800)(47621585139586363746329501803577150157978144822358803047427883371479362640843),
DEBUG:lnd(16331):  Y: (*big.Int)(0xc4207d0820)(39344097727107259284151233359662692735519268809767065875924330499057248052478)
DEBUG:lnd(16331): }),
DEBUG:lnd(16331): Amount: (lnwire.MilliSatoshi) 1000000 mSAT,
DEBUG:lnd(16331): PaymentHash: ([32]uint8) (len=32 cap=32) {
DEBUG:lnd(16331):  00000000  90 d4 ac 85 43 ca 3d c2  0f b4 b8 d1 6a 9e 63 16  |....C.=.....j.c.|
DEBUG:lnd(16331):  00000010  8f 3f b8 20 2c e4 d0 8f  75 32 fd 88 24 63 6a b2  |.?. ,...u2..$cj.|
DEBUG:lnd(16331): },
DEBUG:lnd(16331): FinalCLTVDelta: (*uint16)(<nil>),
DEBUG:lnd(16331): PayAttemptTimeout: (time.Duration) 0s
DEBUG:lnd(16331):})
```

No biggy, just thought I should mention it here :-)

**Comment by Roasbeef** [comment] 2018-04-10 22:03
If you create the invoices at `lnd`, then we use a default time out of `144`, so you'll need to specify that for the `final_cltv_delta` value.

**Comment by Roasbeef** [comment] 2018-04-10 22:06
Are you using `SendPaymentSync`? It appears that hasn't been kept up to date with the actual `SendPayment` call, as the `SendPaymentSync` call was only added to support the REST interface.

**Comment by cdecker** [comment] 2018-04-11 17:13
Yeah, I was using `SendPaymentSync` which seems to drop the final CLTV timeout. I have it working by checking whether the prefix is `lnbt` (recipient is `lnd`) and directly passing that one in in that case. I couldn't get the async payment working since it'd trigger the payment, but then fail to return the result (the python client would stop iterating over the stream of results immediately, instead of waiting for it to finish).

No worries though, it's working for all combinations of payments right now.
