### ISSUE TITLE
LND does not consider ChannelUpdate when paying to a private channel

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3769] opened 2019-11-27 10:01 UTC
### Background

When the LND pays an invoice created by the Eclair Mobile where are incorrect base fee & rate in `hop_hints` for last hop he doesn't consider `ChannelUpdate` attached message from last hop (where is LND 0.8.1-beta to be run too) and cannot pay this invoice again - LND user gets the "unable to find a path to destination" error

### Your environment

* version of `lnd` - 0.8.1-beta

### Steps to reproduce

1. You need to have channel to be able to receive to Eclair mobile
2. Create invoice from Eclair Mobile
3. If Eclair will create incorrect `hop_hints` fee rate (lower than real one; bug in Eclair described here: https://github.com/ACINQ/eclair-mobile/issues/228) we will try to pay by LND
4. First paying i got error:

        l payinvoice lnbc10m1pwauwjppp5ak3vrvj8n95lh5kfy7vyqzzsa278xt35ayvsxu5ag3dq98jdx0vqdqqxqr4rqrzjqvp62xyytkuen9rc8asxue3fuuzultc89ewwnfxch70zf80yl0gpjzf9tqqq9kgqqqqqqqlgqqqqqeqqjqrzjqvww9ygka2m7m4npfr63d8clkev0443tm3gfzgs6hz2luhfkmvqtyzf9qvqq32sqqqqqqqlgqqqqqeqqjqhexr4f8d02974h3mnzrep325nngfl52shg7nzk4w0assuf4qfztjph3nz7xwnlu32v7g4xem5ge3h3mxxyyuvkc7nznyawv42c7lkdqp00393s
        Description: 
        Amount (in satoshis): 1000000
        Destination: 021780c171da4b791bf98a7e52a62f6317dcf4e557dfa955fb93ed79cc8cfbbb5d
        Confirm payment (yes/no): yes
        {
                "payment_error": "unable to route payment to destination: FeeInsufficient(htlc_amt==1000000000 mSAT, update=(lnwire.ChannelUpdate) {\n Signature: (lnwire.Sig) (len=64 cap=64) {\n  00000000  c6 ed 20 59 c5 94 47 29  08 8a 60 93 aa d8 d0 57  |.. Y..G)..`....W|\n  00000010  f6 b9 62 94 30 74 00 3b  44 16 dd c7 5f 59 2f eb  |..b.0t.;D..._Y/.|\n  00000020  71 3d 0c ff ef 31 a1 08  52 97 77 8d a4 71 1c 21  |q=...1..R.w..q.!|\n  00000030  08 00 5b a5 83 1e 88 0b  01 29 34 25 45 54 06 bf  |..[......)4%ET..|\n },\n ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,\n ShortChannelID: (lnwire.ShortChannelID) 599384:729:0,\n Timestamp: (uint32) 1574084839,\n MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,\n ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000001,\n TimeLockDelta: (uint16) 30,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 1 mSAT,\n BaseFee: (uint32) 1000,\n FeeRate: (uint32) 1500,\n HtlcMaximumMsat: (lnwire.MilliSatoshi) 3300381000 mSAT,\n ExtraOpaqueData: ([]uint8) \u003cnil\u003e\n}\n",
                "payment_preimage": "",
                "payment_route": null
        }
        [lncli] unable to route payment to destination: FeeInsufficient(htlc_amt==1000000000 mSAT, update=(lnwire.ChannelUpdate) {
         Signature: (lnwire.Sig) (len=64 cap=64) {
          00000000  c6 ed 20 59 c5 94 47 29  08 8a 60 93 aa d8 d0 57  |.. Y..G)..`....W|
          00000010  f6 b9 62 94 30 74 00 3b  44 16 dd c7 5f 59 2f eb  |..b.0t.;D..._Y/.|
          00000020  71 3d 0c ff ef 31 a1 08  52 97 77 8d a4 71 1c 21  |q=...1..R.w..q.!|
          00000030  08 00 5b a5 83 1e 88 0b  01 29 34 25 45 54 06 bf  |..[......)4%ET..|
         },
         ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
         ShortChannelID: (lnwire.ShortChannelID) 599384:729:0,
         Timestamp: (uint32) 1574084839,
         MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,
         ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000001,
         TimeLockDelta: (uint16) 30,
         HtlcMinimumMsat: (lnwire.MilliSatoshi) 1 mSAT,
         BaseFee: (uint32) 1000,
         FeeRate: (uint32) 1500,
         HtlcMaximumMsat: (lnwire.MilliSatoshi) 3300381000 mSAT,
         ExtraOpaqueData: ([]uint8) <nil>
        }
	
    The channel `599384:729:0` is channel between the Eclair Mobile and `0303a518845db99994783f606e6629e705cfaf072e5ce9a4d8bf9e249de4fbd019` node
        
    If i pay second time and again next ones i will get:
    
        l payinvoice lnbc10m1pwauwjppp5ak3vrvj8n95lh5kfy7vyqzzsa278xt35ayvsxu5ag3dq98jdx0vqdqqxqr4rqrzjqvp62xyytkuen9rc8asxue3fuuzultc89ewwnfxch70zf80yl0gpjzf9tqqq9kgqqqqqqqlgqqqqqeqqjqrzjqvww9ygka2m7m4npfr63d8clkev0443tm3gfzgs6hz2luhfkmvqtyzf9qvqq32sqqqqqqqlgqqqqqeqqjqhexr4f8d02974h3mnzrep325nngfl52shg7nzk4w0assuf4qfztjph3nz7xwnlu32v7g4xem5ge3h3mxxyyuvkc7nznyawv42c7lkdqp00393s
        Description: 
        Amount (in satoshis): 1000000
        Destination: 021780c171da4b791bf98a7e52a62f6317dcf4e557dfa955fb93ed79cc8cfbbb5d
        Confirm payment (yes/no): yes
        {
                "payment_error": "unable to find a path to destination",
                "payment_preimage": "",
                "payment_route": null
        }
        [lncli] unable to find a path to destination
        

    The decoded invoice was as:
    
        l decodepayreq lnbc10m1pwauwjppp5ak3vrvj8n95lh5kfy7vyqzzsa278xt35ayvsxu5ag3dq98jdx0vqdqqxqr4rqrzjqvp62xyytkuen9rc8asxue3fuuzultc89ewwnfxch70zf80yl0gpjzf9tqqq9kgqqqqqqqlgqqqqqeqqjqrzjqvww9ygka2m7m4npfr63d8clkev0443tm3gfzgs6hz2luhfkmvqtyzf9qvqq32sqqqqqqqlgqqqqqeqqjqhexr4f8d02974h3mnzrep325nngfl52shg7nzk4w0assuf4qfztjph3nz7xwnlu32v7g4xem5ge3h3mxxyyuvkc7nznyawv42c7lkdqp00393s
        {
            "destination": "021780c171da4b791bf98a7e52a62f6317dcf4e557dfa955fb93ed79cc8cfbbb5d",
            "payment_hash": "eda2c1b2479969fbd2c92798400850eabc732e34e91903729d445a029e4d33d8",
            "num_satoshis": "1000000",
            "timestamp": "1574844993",
            "expiry": "21600",
            "description": "",
            "description_hash": "",
            "fallback_addr": "",
            "cltv_expiry": "9",
            "route_hints": [
                {
                    "hop_hints": [
                        {
                            "node_id": "0303a518845db99994783f606e6629e705cfaf072e5ce9a4d8bf9e249de4fbd019",
                            "chan_id": "659029677550665728",
                            "fee_base_msat": 1000,
                            "fee_proportional_millionths": 100,
                            "cltv_expiry_delta": 144
                        }
                    ]
                },
                {
                    "hop_hints": [
                        {
                            "node_id": "031ce29116eab7edd66148f5169f1fb658fad62bdc5091221ab895fe5d36db00b2",
                            "chan_id": "658936219159887872",
                            "fee_base_msat": 1000,
                            "fee_proportional_millionths": 100,
                            "cltv_expiry_delta": 144
                        }
                    ]
                }
            ]
        }
    
### Expected behaviour

The LND should update last hop channel fees from `ChannelUpdate` message from first paying and to use hops from hints with new fee base & rates. And even more so do not stop paying completely on the second attempt.

I tried to pay these invoices from BLW later - they were paid successfully.

**Comment by wpaulino** [comment] 2019-11-27 17:20
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/2066.

**Closed by wpaulino** 2019-11-27 17:20 UTC
