### ISSUE TITLE
log emits gibberih when bitcoind is restarted

### ISSUE THREAD

**Issue by Talkless** [lightningnetwork/lnd#1729] opened 2018-08-15 15:46 UTC
### Background

I've performed `systemctl restart bitcoind` while `lnd` (lnd version 0.4.2-beta commit=fab1aa2d49380a3e8aef545c6b6a82e650e3b20f, master at some point, not tag) was also running, and some gibberish bytes appeard in`.lnd/logs/bitcoin/mainnet/lnd.log` file:

```
2018-08-15 18:36:22.838 [ERR] LNWL: <nil>
2018-08-15 18:36:22.839 [ERR] LNWL: <nil>
2018-08-15 18:36:22.839 [ERR] LNWL: <nil>
2018-08-15 18:36:22.839 [WRN] LNWL: Received unexpected event type from rawtx subscription: <AD>T<9D><C5>^Y<C7>^Xd<86><AE>~<8C><FC><DF>uw<B8>x<EA><EA>^L<B6>
<95>v<AC>=z<EB>뽏^B ~tVb|<9F>I       <FD>q<CE><E8><C2>^E<93>g^XG<C8>ESC<96>5<A^V<AF><DB>@}N<A5>!^A!^B<A6>]x<A6>7<BB><F0><ED><D9>q<D8><C0>^Qף<B4>0<C3>[<F2>mO^D
<C9>^L$<C8>W<83>ESC<91>X<FE><FF><FF><FF><BE><8F><93><D5><D6><C7>^F[<E8><A9>0<E4><C0><E0><D9>o<E8>~<D4>K<CA><L1<90>$<81><F2>U<9B>U\^@^@^@^@jG0D^B ^P0<AC>RH<80><C1>X
}<F8>^HE
2018-08-15 18:36:22.839 [ERR] LNWL: <nil>
2018-08-15 18:36:22.840 [ERR] LNWL: <nil>
2018-08-15 18:36:22.840 [ERR] LNWL: <nil>
2018-08-15 18:36:22.840 [ERR] LNWL: <nil>
2018-08-15 18:36:22.841 [ERR] LNWL: <nil>
```

It actually broke `tail -f .lnd/logs/bitcoin/mainnet/lnd.log` and I had to restart it, as it probably didn't expect some non-printable bytes.

I guess it would be better to print hex-encoded data, or ascii-with-questionmarks as `tcpdump` does.

### Your environment

* `fab1aa2d49380a3e8aef545c6b6a82e650e3b20f`
* `Linux odroid-hc1 4.9.0-7-armmp-lpae #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) armv7l GNU/Linux`
* `bitcoind v0.16.2`

### Steps to reproduce

Restart `bitcoind` while `lnd` is running.

### Expected behaviour

Log file should not contain non-printable bytes. 

### Actual behaviour

Log file contains non-printable bytes.

**Comment by Roasbeef** [comment] 2018-08-15 22:44
Can you reproduce this on master? Since that version (0.4.2) we've improved the reconnection logic for `bitcoind`.

**Comment by Talkless** [comment] 2018-08-15 22:54
My used commit fab1aa2d49380a3e8aef545c6b6a82e650e3b20f is just two days ago. I could try though.

**Comment by wpaulino** [comment] 2018-08-15 22:55
No need to try it, looking into it.

**Comment by wpaulino** [comment] 2018-08-16 00:25
https://github.com/btcsuite/btcwallet/pull/526 addresses the `nil`s being printed out. Haven't identified the source of the weird message yet however.

**Comment by Talkless** [comment] 2018-08-16 16:47
Maybe that's related:
`bitcoind`:
```
2018-08-16 16:44:10 WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
```
`lnd`:
```
2018-08-16 19:44:28.254 [WRN] LNWL: Received unexpected event type from rawtx subscription: vfX:DQg
2018-08-16 19:44:28.255 [WRN] LNWL: Received unexpected event type from rawtx subscription:
2018-08-16 19:44:28.255 [WRN] LNWL: Received unexpected event type from rawtx subscription:
2018-08-16 19:44:28.255 [WRN] LNWL: Received unexpected event type from rawtx subscription: U
```

**Comment by wpaulino** [comment] 2018-08-16 19:40
Don't think that's relevant as it seems to be RPC related. Was `bitcoind` restarted some time around when the logs show on `lnd`'s side like in the first instance above?

**Comment by Talkless** [comment] 2018-08-16 19:48
No, this second instanced is due to high load, bitcoind was not being restarted.

**Comment by Roasbeef** [comment] 2018-08-17 21:05
Are you running multiple `lnd` nodes backed by the same instance of `bitcoind`?

**Comment by Talkless** [comment] 2018-08-17 23:01
> Are you running multiple lnd nodes backed by the same instance of bitcoind?

No, it's only one LND. 

What I have meant in "second instance" is the *second log snippet* I have pasted here. It was not during reboot, but when bitcoind is being busy ("work queue depth exceeded"), probably because I also run electrumx what uses RPC...

**Comment by Roasbeef** [comment] 2018-08-18 00:12
Is `lnd` the only thing that you have connected to the node? We've merged that PR in `btcwallet to avoid logging garbage, so that should be updated in `lnd` soon once we upgrade the `dep` files.

**Closed** 2018-08-24 21:50 UTC
