### ISSUE TITLE
pending open channel, opening transaction never confirmed

### ISSUE THREAD

**Issue by RobinTick** [lightningnetwork/lnd#3272] opened 2019-07-04 20:49 UTC
I'm running LND 0.7.0-beta on top of Bitcoind 0.18.0, running in Debian 4.9.110-3.
A channel has been pending on opening for over a month, it tried to open when I was still running LND 0.6.1-beta.

The txid in the channel point can't be found through blockexplorers so I must conclude the transaction never got included in a block.

I tried using closechannel but that did not work, because the channel is not open. Here are the relevant log entries and output from pendingchannels and closechannel. The channel I'm concerned with is the first one in pending channels, the second one has been stuck for a long time too though.

```
2019-07-04 21:44:07.716 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1)
2019-07-04 21:44:56.217 [INF] NTFN: New spend subscription: spend_id=25, outpoint=4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1, height_hint=583848           
2019-07-04 21:44:56.272 [INF] CNCT: Close observer for ChannelPoint(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1) active                                     
2019-07-04 21:44:56.715 [INF] CNCT: ChannelArbitrator(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1): starting state=StateDefault                             
2019-07-04 21:44:57.280 [INF] LNWL: Inserting unconfirmed transaction 4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b                                             
2019-07-04 21:44:57.290 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1): Transaction rejected: output already spent
2019-07-04 21:44:57.291 [INF] NTFN: New confirmation subscription: txid=4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b, num_confs=3                              
2019-07-04 21:44:57.291 [INF] NTFN: New confirmation subscription: conf_id=2, txid=4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b, height_hint=583848            
2019-07-04 21:44:57.291 [INF] FNDG: Waiting for funding tx (4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b) to reach 3 confirmations                             
2019-07-04 21:44:58.101 [WRN] PEER: Unable to find our forwarding policy for channel 4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1, using default values      
2019-07-04 21:44:58.102 [INF] HSWC: ChannelLink(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1) is starting                                                    
2019-07-04 21:44:58.103 [INF] HSWC: HTLC manager for ChannelPoint(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1) started, bandwidth=879768000 mSAT            
2019-07-04 21:44:58.103 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1)                                
2019-07-04 21:45:28.104 [INF] HSWC: ChannelLink(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1) has exited                                                     
2019-07-04 21:45:28.104 [INF] HSWC: ChannelLink(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1) is stopping                                                    

The channel is still in pending channels
$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "020f49831fd13556e5b03239df888ca031edaebe5b4efccd52d2f5c6742a743ad6",
                "channel_point": "4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1",
                "capacity": "900000",
                "local_balance": "888768",
                "remote_balance": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "11232",
            "commit_weight": "600",
            "fee_per_kw": "15515"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "025a625a9aa3d7c2f9a7eaa6bdb2278200b2871d35d51ab1e5bc8979078e9e1036",
                "channel_point": "5e5c88386aaa1f57b293530f175fa76b28d17fc39cc8ee2eb075ec370a2160b2:1",
                "capacity": "285083",
                "local_balance": "2000",
                "remote_balance": "0"
            },
            "closing_txid": "1f90bf8f7065c3e90fbf72b3268ed57554c5f407e3a13397743e45048e3be546",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ],
    "waiting_close_channels": [
    ]
}

$ lncli closechannel 4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b
[lncli] rpc error: code = Unknown desc = channel not found
```

**Comment by a123b** [comment] 2019-07-05 22:23
I can confirm this issue. This happened to me, too, a few months ago, with v0.5.2. I opened a few channels consecutively with only a single UTXO in the wallet. Two channels ended up using the same input somehow, so one channel got into the same "pending forever" state. Back then, I could force close the channel, however, but that just got it stuck pending force closing forever.

Does lnd keep the funding transaction stored? If it does, it would be cool if lnd could check on startup whether they're still valid and abandon the channel if they are not.

**Comment by molxyz** [comment] 2019-07-06 16:37
@RobinTick  For the pending open channel, try to resend/rebroadcast it. Here's try this:  look in your `listchaintxns` and find the hexstring of the TXID of this pending channel, and resend the tx using this hexstring. 
So do this: `lncli listchaintxns`,  then look for the tx with TXID `4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b`
It should look similar to something like this: 
```
        {
            "tx_hash": "3e2e02991080f2d41f8189f66fae4ba4e4c618cbcc6e66f116353dcac40d9287",
            "amount": "-257637",
            "num_confirmations": 0,
            "block_hash": "",
            "block_height": 0,
            "time_stamp": "1562430320",
            "total_fees": "7637",
            "dest_addresses": [
            ],
            "raw_tx_hex": "01000000000101d5a23f9cd91640da7f4b7604546b511abfe647d6ccc25ce099ec7ec30746fbd20000000000ffffffff0290d0030000000000220020421d182b814a7c0d722e6200e65f8d813bc1b67b6ab6eae56aa3ea7d8884c4748ce5470000000000160014095cf07f7b349a20fddf0d1f8ff7ea3b4eda3a1b02483045022100dd951c50ad13ecc6b5bb4b4ce0d8013900a0d49bb81df718e7f1dda014f6cff20220178e2775ddd91b8284ea59e2a382010bcef77e13cf287606d2e2aaf2f3cdbbd70121020ddbf3fe8c9b43b4ca6e91446c46b418df9616982f48cf394b247bd66dd111f300000000"
        },
```
Copy the `raw_tx_hex`, on your terminal screen, do this: 
`bitcoin-cli sendrawtransaction <paste the whole raw_tx_hex here>` 

Could you try this and let me know how it goes?

**Comment by RobinTick** [comment] 2019-07-06 23:12
@molxyz The output of listchaintxs gives shows me transactions from 300 days ago till 60 days ago, the TXID of the stuck channel is not in there.

**Comment by molxyz** [comment] 2019-07-07 12:18
@RobinTick  Actually it seems the output of that transaction has been spent as stated in the log:
```
2019-07-04 21:44:57.290 [ERR] FNDG: Unable to rebroadcast funding tx for ChannelPoint(4cd80ac2bb753ae11f4de9c5eb273732480fb9d09b7599009b62d26f5199753b:1): Transaction rejected: output already spent
```
So I think maybe a rescan of the wallet might help, if not, it doesn't hurt. Because lnd uses btcwallet the rescan is done by using `dropwtxmgr`. Try this:   
`$ dropwtxmgr --db ~/.lnd/data/chain/bitcoin/mainnet/wallet.db`

**Comment by RobinTick** [comment] 2019-07-07 19:27
@molxyz I'm having trouble installing dropwtxmgr.
I have go version go1.7.4 installed.
I read this page https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
and tried:
```
$ go get -v -u github.com/btcsuite/btcwallet/cmd/dropwtxmgr
github.com/btcsuite/btcwallet (download)
github.com/btcsuite/btcutil (download)
github.com/btcsuite/btcd (download)
Fetching https://golang.org/x/crypto/ripemd160?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ripemd160?go-get=1 (status code 200)
get "golang.org/x/crypto/ripemd160": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ripemd160?go-get=1
get "golang.org/x/crypto/ripemd160": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
github.com/btcsuite/btclog (download)
github.com/btcsuite/golangcrypto (download)
github.com/coreos/bbolt (download)
github.com/jessevdk/go-flags (download)
```
That does not give me a usable dropwtxmgr, $GOPATH/bin/ is still empty.
I read this https://github.com/lightningnetwork/lnd/issues/2980
And tried:
```
$ git clone https://github.com/btcsuite/btcwallet
$ cd btcwallet
$ GO111MODULE=on go install ./cmd/dropwtxmgr
../gocode/src/golang.org/x/crypto/ripemd160/ripemd160block.go:12:2: cannot find package "math/bits" in any of:
        /usr/lib/go-1.7/src/math/bits (from $GOROOT)
        /home/robin/gocode/src/math/bits (from $GOPATH)
```
The "math/bits" thing seems to be missing.
I read https://www.sosthene.net/story-btcpay-lightning-wreckdom/ which was very amusing, but did not help.

**Comment by RobinTick** [comment] 2019-07-07 20:33
Continued.
I found references to the GO version being too old.
Removed GO as per the instructions here: https://golang.org/doc/install#uninstall
Also did: 
$ apt autoremove golang
$ apt autoremove

Next installed GO 1.12.6, after which I was finally able to install dropwtxmgr.
Stopped LND, made sure.
```
$ sudo systemctl stop lnd
$ sudo systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
```
Ran the program from ~/gocode/bin/dropwtxmgr
```
$ ~/gocode/bin$ sudo ./dropwtxmgr --db /bitcoin/.lnd/data/chain/bitcoin/mainnet/wallet.db
Database path: /bitcoin/.lnd/data/chain/bitcoin/mainnet/wallet.db
Drop all btcwallet transaction history? [y/N] y
Dropping btcwallet transaction history
Failed to drop and re-create namespace: failed to store sync information 0000000000000000002240a2bab518a25c81b14f1850d9c855be55aa16fb9597: failed to fetch block hash for height 537983: block not found
```
I have the right location for the wallet.db file.

**Comment by molxyz** [comment] 2019-07-07 23:44
@RobinTick Oh cool.. so you got it going now?  Sorry I was busy with stuff, almost forgot this thread. Let me know how it turns out!  :)

**Comment by RobinTick** [comment] 2019-07-08 06:04
@molxyz that's alright I appreciate the help.
I posted the outcome of using dropwtxmgr in the above comment, it has failed to make LND rescan from wallet birth.

**Comment by wpaulino** [comment] 2019-07-08 19:36
Will close as we're unable to determine why the duplicate output exists and there have been some fixes in this area.

> Does lnd keep the funding transaction stored? If it does, it would be cool if lnd could check on startup whether they're still valid and abandon the channel if they are not.

@a123b this is something we plan to do soon.

@RobinTick you are right in that `dropwtxmgr` is not working properly at the moment, we can follow along with that issue in https://github.com/btcsuite/btcwallet/issues/630. As for the pending channel, you can remove it with the `lncli abandonchannel` command available in a debug build of `lnd`.

**Closed by wpaulino** 2019-07-08 19:36 UTC
