### ISSUE TITLE
UnknownNextPeer error on payinvoice

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#568] opened 2018-01-07 03:44 UTC
I'm consistently getting this error when trying to send payment from one of my nodes to another, I've restarted both nodes and created lots of invoices to try but the error persists.

Whenever I try to pay a simple invoice I get `unable to route payment to destination: UnknownNextPeer`. There is an active channel between the two nodes with plenty of balance belonging to the sender. Here's some of the relevant output from the sending node:

```bash
$ lncli decodepayreq lntb1u1pd9qaztpp5pat93v4kg7z393ggrvd5r0u9tflxum3f7t9zq56scma3e480smqsdq4f35kw6r5de5kueeqgajk6cqzysx9zgpskkh0y0jxnmwzljtuw54h6g3z7jve0l8s5rhff244epjg8r5eqj7nez8f70psjqkyff5fl7n7z9ksrgjrgsv9k4sm5h2s26cqcqularhs
{
    "destination": "023c1fc1ef2d9a555693cf0fdc39b66d934dfc07bc0b1ee050fd3f4aeb773b9438",
    "payment_hash": "0f5658b2b6478512c5081b1b41bf855a7e6e6e29f2ca205350c6fb1cd4ef86c1",
    "num_satoshis": "100",
    "timestamp": "1515222091",
    "expiry": "3600",
    "description": "Lightning Gem",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144"
}
```

Here's the active channel (I trimmed the other channels from the `listchannels` output):
```bash
$ lncli listchannels
        {
            "active": true,
            "remote_pubkey": "023c1fc1ef2d9a555693cf0fdc39b66d934dfc07bc0b1ee050fd3f4aeb773b9438",
            "channel_point": "6aa0bada9d2fce57f61d7d93bb4b8fc5189c03e722c963d5aadd52968852f934:0",
            "chan_id": "1381799143597932544",
            "capacity": "1000000",
            "local_balance": "995436",
            "remote_balance": "220",
            "commit_fee": "4564",
            "commit_weight": "600",
            "fee_per_kw": "6000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "220",
            "total_satoshis_received": "0",
            "num_updates": "4",
            "pending_htlcs": [
            ],
            "csv_delay": 4
        }
```

And here's the error:
```bash
$ lncli payinvoice lntb1u1pd9qaztpp5pat93v4kg7z393ggrvd5r0u9tflxum3f7t9zq56scma3e480smqsdq4f35kw6r5de5kueeqgajk6cqzysx9zgpskkh0y0jxnmwzljtuw54h6g3z7jve0l8s5rhff244epjg8r5eqj7nez8f70psjqkyff5fl7n7z9ksrgjrgsv9k4sm5h2s26cqcqularhs
{
        "payment_error": "unable to route payment to destination: UnknownNextPeer",
        "payment_preimage": "",
        "payment_route": null
}
```

**Comment by Roasbeef** [comment] 2018-01-07 23:18
The isn't a bug per-say, `UnknownNextPeer` is a protocol level onion routing error. That's returned when the next peer in a path simple isn't available.

**Comment by Roasbeef** [comment] 2018-01-07 23:24
If the channel is pending, then it isn't available for usage (you pasted a `pendingchannels` dump, but the return value looks like it was from `listchannels).

**Comment by sangaman** [comment] 2018-01-07 23:50
Ahhh my mistake, I just mixed that up when pruning and formatting the output. It is in fact output from a  `listchannels` call, I'll edit the main post to fix it.

Given that I have an active channel with the intended recipient, why would I get a routing error? Shouldn't the route just take a single hop to the recipient?

**Comment by Roasbeef** [comment] 2018-01-08 18:06
You'd get the routing error if the channel wasn't active at the payment attempt. What do the logs show?

**Comment by sangaman** [comment] 2018-01-08 18:18
I'm pretty sure the channel was active at the time of that error, but just now when I went to try and recreate the error and grab the log output the payment went through successfully. I'll try to go through the log archive to see if I can find the logging from when I got the error last.

**Comment by sangaman** [comment] 2018-01-08 18:23
Dang looks like my logs don't go far back enough.

**Comment by tomichec** [comment] 2018-01-08 21:16
I have a similar experience. It looks I have an open channel but am unable to route the payment through it. The direct channel to the peer from `lncli listchannels` looks like

`
        {
            "active": true,
            "remote_pubkey": "03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2",
            "channel_point": "3308378e39cbb95e263eddf20e2bb36cfa29ba6509116a83d427c8870cdf2205:0",
            "chan_id": "0",
            "capacity": "50000",
            "local_balance": "36244",
            "remote_balance": "0",
            "commit_fee": "13756",
            "commit_weight": "600",
            "fee_per_kw": "19000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 4
        }
`

The strange thing is that the ` "chan_id": "0",`.

**Comment by Roasbeef** [comment] 2018-01-08 21:18
@tomichec what commit are you on? If you're running with btcd, do you have the `txindex` active? 

Do you have a log fragment when you attempt the payment?

**Comment by tomichec** [comment] 2018-01-08 21:27
I'm on commit ac89bab in lnd and commit 9978b939 in btcd.

I have `; txindex=1` (commented out), but it should be active by default, isn't it?

if you mean btcd log fragment, then it is

```
2018-01-08 20:53:51.628 [INF] SYNC: Processed 1 block in the last 8m11.08s (62 transactions, height 1257872, 2018-01-08 20:53:29 +0100 CET)
2018-01-08 20:54:28.499 [INF] SYNC: Processed 1 block in the last 36.87s (9 transactions, height 1257873, 2018-01-08 20:54:09 +0100 CET)
2018-01-08 21:14:36.123 [INF] SYNC: Processed 1 block in the last 20m7.62s (110 transactions, height 1257874, 2018-01-08 21:14:22 +0100 CET)
2018-01-08 21:24:37.518 [INF] CHAN: Adding orphan block 000000000000040b10fc40a47e57fb541bb2d6b5b6a202b5779c97b13ff8c536 with parent 0000000000078cdc7852f9b7d8968bb50e318fb5711a471b603f8c3ae0179296
2018-01-08 21:24:37.797 [INF] CHAN: FORK: Block 0000000000078cdc7852f9b7d8968bb50e318fb5711a471b603f8c3ae0179296 forks the chain at height 1257873/block 00000000000004be35b7bb87fc7defa8645a0258c20f6cd646d5426e891509d0, but does not cause a reorganize
2018-01-08 21:24:37.800 [INF] CHAN: REORGANIZE: Block 000000000000040b10fc40a47e57fb541bb2d6b5b6a202b5779c97b13ff8c536 is causing a reorganize.
2018-01-08 21:24:37.933 [INF] CHAN: REORGANIZE: Chain forks at 00000000000004be35b7bb87fc7defa8645a0258c20f6cd646d5426e891509d0
2018-01-08 21:24:37.933 [INF] CHAN: REORGANIZE: Old best chain head was 000000008a721074384f37c71d4e926d4b95f35c8b10f1e615dbd17f7fa9fa2e
2018-01-08 21:24:37.933 [INF] CHAN: REORGANIZE: New best chain head is 000000000000040b10fc40a47e57fb541bb2d6b5b6a202b5779c97b13ff8c536
2018-01-08 21:24:37.933 [INF] SYNC: Processed 1 block in the last 10m1.81s (110 transactions, height 1257874, 2018-01-08 21:14:34 +0100 CET)
2018-01-08 21:44:13.567 [INF] SYNC: Processed 1 block in the last 19m35.63s (104 transactions, height 1257876, 2018-01-08 21:44:10 +0100 CET)
2018-01-08 21:53:56.004 [ERR] PEER: Can't read message from [2001:da8:1017:2:f56f:bcfe:25cf:51f2]:18333 (outbound): read tcp [2a02:8308:50c0:4000:ed90:31f1:aad1:3de9]:47564->[2001:da8:1017:2:f56f:bcfe:25cf:51f2]:18333: read: connection reset by peer
2018-01-08 21:53:56.005 [INF] SYNC: Lost peer [2001:da8:1017:2:f56f:bcfe:25cf:51f2]:18333 (outbound)
2018-01-08 21:54:26.110 [INF] SYNC: New valid peer 52.16.207.62:18333 (outbound) (/Satoshi:0.15.1/)
2018-01-08 22:04:17.919 [INF] SYNC: Processed 1 block in the last 20m4.35s (68 transactions, height 1257877, 2018-01-08 22:04:15 +0100 CET)
```

I attempted the opening of the channel at about 21:10.

**Comment by Roasbeef** [comment] 2018-01-08 22:06
Nope the `txindex` isn't active by default. It _must_ be active for this to function properly.

**Comment by tomichec** [comment] 2018-01-08 22:08
I have now also filtered the lnd output with

`grep -C 4 -E '3308378e39cbb95e263eddf20e2bb36cfa29ba6509116a83d427c8870cdf2205|1383047089280188416' bob/test_log/testnet3/bitcoin/lnd.log`

it can be found https://gist.github.com/tomichec/6df3c48395eb6718eb38dbfd96315789

There were some forks going on, so I wander if they could have caused it.

**Comment by tomichec** [comment] 2018-01-08 22:13
ok, now I have noticed that I passed the `--txindex` in the command line. So it _was_ turned on.

**Comment by Roasbeef** [comment] 2018-01-24 23:52
Are y'all able to reproduce this on the latest commit?

**Comment by sangaman** [comment] 2018-01-24 23:54
I haven't encountered it in a while. I'll be updating my nodes to latest lnd in the coming days and then I'll try similar steps and set-ups to what I was doing when I first got this error.

**Comment by asocjal** [comment] 2018-02-10 13:41
This issue on y environment even with txindex=1 in btcd.conf file.

Problems occurs when I have more than single channel opened. Tried to pay for coffee on starblocks. With single channel opened, it succeeded, but when I opened more channels, I have errors like "unable to route payment to destination: UnknownNextPeer" and "unable to find a path to destination" later on.

**Comment by Roasbeef** [comment] 2018-02-10 22:12
To re-iterate: unknown next peer _is not a critical error. It is simply a routing error that can be returned by any peer in the route. It happens in the case that the next peer in the route isn't online. The conditions on testnet are highly dynamic, it possible that a payment works on time, but doesn't the next time around. People restart nodes constantly, as high uptime isn't of value as we're slinging around fake money.

**Comment by halseth** [comment] 2018-02-15 07:00
@asocjal Just make a debug dump (maybe use pastebin) of all logs from right before you attempt the payment to after the error is returned :)

**Comment by Roasbeef** [comment] 2018-03-12 23:47
Closing for now due to lack of updates. Also a nasty bug was fixed a few months ago where if you had a pending channel, then reconnected, the first payment was guaranteed to either hang, or return unknown peer (as the switch's forwarding index hadn't yet been properly updated).

**Closed by Roasbeef** 2018-03-12 23:47 UTC
Labels: onion routing, payments

**Comment by yopie77** [comment] 2018-05-10 14:13
Sorry to open an older thread, but I have the exact same thing. I am trying to pay an invoice on the Mainnet, with Autopilot switched off.  txindex=1 is in my conf file.
I get:

admin ~ ฿ lncli payinvoice lnbc1500n1pd0gnrhpp5fvwna92w4rrhcnd2yct4wj5s5wstp8st4ha65lscvcd03vzu2dgsdz22fjkzep6yppx2emfdehx2uhzszvhxgz8w45kgefqw3hjpmac3l3f4g2vd9nksarwd9hx0mac3ucqzyswe7y9c0d2mpkpuc6zyyr7724e3xjcygz3j3wyvzx3a3gps8853j9z9v2ultqzajf7ffej6usyzsq8v2uexln3skzy3nmy7yd5t0wgzqpmpc23w
{
        "payment_error": "unable to route payment to destination: UnknownNextPeer",
        "payment_preimage": "",
        "payment_route": null
}

I have 4 funded and active channels:

admin ~ ฿ lncli listchannels
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "02040d058e0504c7d4b1fe2fef510396f33bdabfe36450bbb6c7ea0d567d53a15f",
            "channel_point": "ceb83b67957635e7909552ec02d10278335e4a12e40d375ce2016cefcb03ab28:1",
            "chan_id": "574003343897001985",
            "capacity": "25000",
            "local_balance": "24095",
            "remote_balance": "0",
            "commit_fee": "905",
            "commit_weight": "600",
            "fee_per_kw": "1250",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "20",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": true,
            "remote_pubkey": "02a456b816697c6b8407ee2176475d74b790a96143bc30e896e8bf7a8852a8b637",
            "channel_point": "81caa1086ed05e3c97c0fe6556dcb609416670f43ea69a935f1d79f6b697fbf6:0",
            "chan_id": "574029732201889792",
            "capacity": "100000",
            "local_balance": "0",
            "remote_balance": "99459",
            "commit_fee": "541",
            "commit_weight": "552",
            "fee_per_kw": "748",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": true,
            "remote_pubkey": "02b90365acebc10a9ff6a4deec63c638e553ea50e6138c638795e1699c09bc283f",
            "channel_point": "62a4eb98982fc5d76d2a5ab6239563fa65ef589c647b471d68428b79eeffe396:0",
            "chan_id": "574013239477272576",
            "capacity": "25000",
            "local_balance": "24095",
            "remote_balance": "0",
            "commit_fee": "905",
            "commit_weight": "600",
            "fee_per_kw": "1250",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "1",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
        {
            "active": true,
            "remote_pubkey": "02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed",
            "channel_point": "6f1bf11c6e9816c5e3513d35647ed26266fff309e35ac7100c16be774f5c2fbd:1",
            "chan_id": "574020936042545153",
            "capacity": "20000",
            "local_balance": "19095",
            "remote_balance": "0",
            "commit_fee": "905",
            "commit_weight": "600",
            "fee_per_kw": "1250",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        }
    ]
}

This is the invoice I am trying to pay:

admin ~ ฿ lncli decodepayreq lnbc1500n1pd0gnrhpp5fvwna92w4rrhcnd2yct4wj5s5wstp8st4ha65lscvcd03vzu2dgsdz22fjkzep6yppx2emfdehx2uhzszvhxgz8w45kgefqw3hjpmac3l3f4g2vd9nksarwd9hx0mac3ucqzyswe7y9c0d2mpkpuc6zyyr7724e3xjcygz3j3wyvzx3a3gps8853j9z9v2ultqzajf7ffej6usyzsq8v2uexln3skzy3nmy7yd5t0wgzqpmpc23w
{
    "destination": "03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56",
    "payment_hash": "4b1d3e954ea8c77c4daa2617574a90a3a0b09e0badfbaa7e18661af8b05c5351",
    "num_satoshis": "150",
    "timestamp": "1525959799",
    "expiry": "3600",
    "description": "Read: Beginner’s Guide to ️⚡Lightning️",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144"
}

What can be wrong here?

**Comment by Roasbeef** [comment] 2018-05-10 23:10
This isn't an implementation issue, rather it's a network level error. This is only the last error returned. For example, if the node you're trying to pay isn't online, then you'll get this error. It just means that in one of the routes (usually the last one) that we attempted, one of the peers wasn't online so we weren't able to proceed. I'd also recommend you run master as there've been several bugs fixed, and they'll be packaged in a new point release soon.

**Comment by yopie77** [comment] 2018-05-13 05:59
Well, the node I'm trying to pay is Yalls. It is online, and it is a direct peer of me (but I do not have a direct channel with it). Surely with 4 channels I should be able to send to it, right? Is there any log file I can examine/share?

**Comment by Roasbeef** [comment] 2018-05-14 22:43
Are you on IRC or the slack? Would likely be easier to give debug info there, as so far there doesn't seem to be an underlying issue.
