### ISSUE TITLE
Feature Request: Fallback bitcoin nodes

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#1416] opened 2018-06-18 15:25 UTC
I'm running lnd on a separate server from bitcoind. This means there's a possibility for the bitcoin node to go down while the lnd node stays up. Currently it appears that lnd stays running when this occurs, and restores connectivity to the bitcoin node once it comes back online. That's nice, but what I would really like is the ability to specify a "fallback" bitcoin node in the configuration, such that if the primary bitcoin node goes down then lnd will automatically switch to using the fallback bitcoin node. It would be nice as well if lnd detects when the primary bitcoin node comes back online and switches back to it.

Another bonus would be being able to specify any number of fallback nodes.

**Comment by Roasbeef** [comment] 2018-06-18 16:37
Duplicate of #520.

**Closed by Roasbeef** 2018-06-18 16:37 UTC
