### ISSUE TITLE
Bad route hint sends sender node into infinite payment loop

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#6169] opened 2022-01-17 13:11 UTC
### Your environment

* lnd master 2682ca3e22ded37aa75ba40b5dd826bcd5cdd20a
* linux
* bitcoind

### Steps to reproduce

* Nodes A and B with a channel between them
* Patch node B to generate invoices that include a hop hint from A via a non-existent channel id
* Create invoice on B
* Pay invoice from A

### Expected behaviour

Payment fails immediately.

### Actual behaviour

Node A goes into an infinite payment loop where each iteration the outcome is the same `UNKNOWN_NEXT_PEER @ 0`.

**Comment by alexbosworth** [comment] 2022-01-18 18:20
Is this a new behavior?

**Comment by joostjager** [comment] 2022-01-18 18:44
I don't know. Also, maybe B can do this to any node, not just the ones that they have a channel with.

**Comment by alexbosworth** [comment] 2022-01-18 18:52
The infinite loop is still bounded by the pathfinding timeout though right?

**Comment by joostjager** [comment] 2022-01-18 18:59
Didn't actually wait for that, but very likely that it is still bounded.

**Comment by lsunsi** [comment] 2022-07-18 23:42
@joostjager Me and a friend (@andreihod) were able to reproduce this bug reliably and we think we know how to fix it. Is it okay for us to work on it? I'm asking in case someone is already looking into this.

**Comment by yyforyongyu** [comment] 2022-07-19 00:58
I did find [something](https://github.com/lightningnetwork/lnd/pull/6683/commits/782e0bc91d8a4b8efddf6028fb40eb8e01f67484#diff-040acca58de99153a29ab6ac4871acd49fc5e1af78cc7dc6e75c3e78bd065254R366), not sure if it's related.

> Is it okay for us to work on it? I'm asking in case someone is already looking into this.

@lsunsi if it's a small fix then I'd say go for it! What's the cause you guys found?

**Comment by lsunsi** [comment] 2022-07-20 22:32
@yyforyongyu Nice! We think it's unrelated to your findings: it seems that the [`processPaymentOutcomeIntermediate` was treating the resulting error from this bug](https://github.com/lightningnetwork/lnd/blob/d9f4b36cb9009d9e52b952095b612b0edcc3e1e9/routing/result_interpretation.go#L335) while the [`processPaymentOutcomeSelf` was not](https://github.com/lightningnetwork/lnd/blob/d9f4b36cb9009d9e52b952095b612b0edcc3e1e9/routing/result_interpretation.go#L133), leading to the infinite loop because the failure is not marked as final by the handler.

We could verify this because we were able to reproduce the bug easily with a payment where the broken hint is the first hop, but could not reproduce with a payment where the broken hint is the second hop. This different behaviour is what lead us to look into the aforementioned functions.

Does that make sense?

**Comment by yyforyongyu** [comment] 2022-07-22 12:21
@lsunsi Thanks for the detailed explanation! Yeah in this case I'd say please go ahead and make a PR!

**Comment by joostjager** [comment] 2022-10-21 12:12
@saubyk This is a P2 bug with a 3-line (ex tests) fix in https://github.com/lightningnetwork/lnd/pull/6766. Move to 0.16 milestone?

**Comment by saubyk** [comment] 2022-10-21 14:22
Thanks @joostjager for bubbling this up. Tagged for 0.16.0

**Closed** 2022-11-11 11:13 UTC
Labels: bug, P2, path finding
