### ISSUE TITLE
Bumping fee of long lasted pending channels doesn't work and returns a void json

### ISSUE THREAD

**Issue by JavierRSobrino** [lightningnetwork/lnd#4991] opened 2021-02-07 12:59 UTC
### Background

I try to bump the fee of a very long lasting pending channel, that is already out of the mempool in the bitcoind node. The command returns a void json and apparently doesn't do anything.

```
$ lncli wallet bumpfee 9339a4fa80f7e9e03f38130c502acfe454e3a334b643ffc9324c021a413dbb69:1 --conf_target 5
{

}

```
Now go to https://mempool.space/es/tx/9339a4fa80f7e9e03f38130c502acfe454e3a334b643ffc9324c021a413dbb69
and see that nothing happens.
No new tx appears, and the old tx doesn't appear in my bitcoind node yet.

### Your environment

* version of 0.12.0-beta.rc2
* which operating system: Debian docker
* bitcoin-0.20.1-x86_64-linux-gnu

### Steps to reproduce

1. Configure LND in ECONOMIC mode, it uses 1sat/byte.
2. Enable autopilot or open a channel.
3. Wait more than 3 weeks or until the txs dissapear from the mempool of the bitcoind node. The txs must not be confirmed during this period.
4. Try to bump the txs.

### Expected behaviour

Actually bump the fee or rebroadcast a new tx.

### Actual behaviour

Explained above.

**Comment by guggero** [comment] 2021-02-08 09:02
I'm not sure why the CPFP of the change output didn't work here.
Since the channel wasn't confirmed for more than 3 weeks now, you're better off with trying to replace this whole transaction and send it back to your wallet. Because your peer will have removed the channel from their DB after 2 weeks. So you'd only be able to force-close it again once it's open.

I'd wait for the TX to disappear from the mempool and your bitcoind again, then run `lnd` with the `--reset-wallet-transactions` flag to make it appear unspent.

**Comment by JavierRSobrino** [comment] 2021-02-08 11:29
But how do I replace the whole transaction?
Also, this is still a bug, those tx should not be there, LND should have been taken care of them, specially knowing that I have autopilot enabled.

**Comment by guggero** [comment] 2021-02-08 12:02
By following what I wrote above, your wallet will forget the now pending transaction. If you use `lncli sendcoins --sweepall` and send everything to a new address of yours (with a sufficient fee), you make sure the funding transaction will never confirm.

The autopilot currently isn't designed to overwrite your fee preference.

**Comment by Roasbeef** [comment] 2021-02-09 01:02
> Also, this is still a bug, those tx should not be there, LND should have been taken care of them, specially knowing that I have autopilot enabled.

Not sure what you mean here. If it's a channel that you've opened, you either need to wait for it to confirm, or attempt to double spend the inputs. 

Also the `BumpFee` call returns _nothing_ upon success. To see if the bump was on going, then you'll need to check the logs. However, depending on the final confirmateion target reached, then the transaction may still fal out of the mempool. 

Looking at the chain, I see what looks to be a CPFP transaction to anchor down the original funding transaction. Note that `BumpFee` isn't acually aware of what the _package_ looks like. As a result, you'll need to ensure that you're inputting hte proper _effective fee rate_ (the feerate of the entire package). 

As reported, I don't see any bug here.

**Closed** 2021-02-11 03:08 UTC
Labels: autopilot, fees, to be closed
