### ISSUE TITLE
"UnknowneNextPeer" GRPC SendToRoute seams to work incorrectly

### ISSUE THREAD

**Issue by asocjal** [lightningnetwork/lnd#3053] opened 2019-05-07 08:21 UTC
### Background

When I call SendToRoue I fill in "route" field, I got error No route provided.

When I fill in deprecated "routes" field and add my route as zero-indexed element, I get UnknowneNextPeer.

Exact SendToRouteRequest body in attachment.

### Your environment

* version of `lnd: 0.6.0-beta commit=v0.6-beta-rc4
* which operating system: Linux lnd-tst-01 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Call gRPC SendToRoue command.

### Expected behaviour

Successfull payment

### Actual behaviour

When I call SendToRoue I fill in "route" field, I got error No route provided.

When I fill in deprecated "routes" field and add my route as zero-indexed element, I get UnknowneNextPeer.
![payment](https://user-images.githubusercontent.com/13422408/57284644-e0875a80-70b1-11e9-9b24-24ef671a7f83.png)

**Comment by wpaulino** [comment] 2019-05-07 20:58
`UnknownNextPeer` means a node in the route is offline.

**Comment by asocjal** [comment] 2019-05-08 06:51
I know, but this node actually is online. When I call "SendPaymentSync" providing "payment_request", all is fine. In addition route, chosen is the same (sorry for slightly different formatting):

![payment](https://user-images.githubusercontent.com/13422408/57355466-6537ae80-716e-11e9-931a-57f5753bdb3d.png)

**Comment by Roasbeef** [comment] 2019-05-08 19:31
I'm not sure what issue you're reporting here. If the link connecting two nodes isn't active, then you'll get an error back. If the route you've constructed with `SendToRoute` is incorrect, then it may not work.

**Comment by asocjal** [comment] 2019-05-14 09:42
Route, I specified for SendToRoue command is the same as route returned by SendPaymentSync after successful payment. That is why I believe route is constructed properly, channel is active and nodes are online.

Maybe I made some mistake in route? I paste route so I hope someone can look on it and see if it looks good. If yes, then maybe some of you, could just try to repeat this issue? I would try to debug, but I don't know LN code, I don't even know golang.

**Comment by wpaulino** [comment] 2019-05-16 09:34
Made a payment and passed in the route returned into a `SendToRoute` call and I'm not able to reproduce the issue. I'd double check the protobuf definitions for your language were generated correctly.

**Comment by asocjal** [comment] 2019-05-20 06:55
Thanks for help. The issue was as you suggested - I generated my classes from newer proto, than 0.6.0 version. After update to 0.6.1 version it works fine. The only question or suggestion I have is: When I download built version from githubs "releases" tab, how can I get proto matches this version? Maybe it should be also available in releases? And BTW: Maybe there is some easy way to check proto version on execution? Then I would get error like: "your proto is not compatible with version 0.6.0 of lnd".

**Comment by halseth** [comment] 2019-05-20 12:21
@asocjal The github release also contains a source file, the correct protos are inside.

Closing per https://github.com/lightningnetwork/lnd/issues/3053#issuecomment-493860893

**Closed by halseth** 2019-05-20 12:21 UTC
