### ISSUE TITLE
compact Filters are downloaded on every restart since wallet birthday if node has no coins

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#2215] opened 2018-11-25 08:16 UTC
### Background
On restart LND node that has a channel that was initiated by another node, compact filters are downloaded from the birthday of the wallet.

### Your environment
lnd master configured with neutrino on mac os.
running on simnet

### Steps to reproduce
1. start a new LND node and wait for it to sync
2. open channel with remote balance only - I used another node to open a channel with my node.
3. restart.

### Expected behaviour
I expect that compact filters will be downloaded from the point they stopped on previous run.

### Actual behaviour
Compact filters are downloaded from the birthday of the wallet which is a block that was mined 48 hours before the wallet creation date.
This behavior is kept event though blocks are kept being mined making the download time longer with every new mined block.

### More Info
My investigation focused on the "syncWithchain" function in btcwallet/wallet/wallet.go
The variable isInitialSync is set to true only if len(unspent) == 0 (see here: https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L350) 
This condition holds for my case as well (open channel initiated by another node) causes later a rescan from birthday instead of from tip of the chain (see here: https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L693)

**Comment by roeierez** [comment] 2018-11-25 12:07
Maybe instead of running initial sync until tip of chain we could change its semantic to be more like  "syncToBirthday", run it only until finding the birthday stamp if not given? 
This will make the `Manager.SyncedTo()`  return the birthday stamp after initial sync which will allow us to run one version of rescan at the end. 
`w.rescanWithTarget(addrs, unspent, nil)`

**Comment by Roasbeef** [comment] 2018-11-26 02:56
What version are you running? It'll rescan from birthday if you don't have any UTXOs in the wallet, that's by design.

**Comment by roeierez** [comment] 2018-11-26 08:43
> What version are you running?

version I was testing is commit 8924d8fb20eb2abfd9cc93c6cc7eb6951184cb88

> It'll rescan from birthday if you don't have any UTXOs in the wallet, that's by design.

On first start makes sense. On subsequent restarts, don't you think it is better to start a rescan from the last sync point regardless of the number of utxo?

**Comment by wpaulino** [comment] 2018-11-26 16:06
This seems like an unlikely case, but I agree that we shouldn't be rescanning from the birthday block every time, even if there are no UTXOs in the wallet. I've proposed https://github.com/btcsuite/btcwallet/pull/577 as a solution.

**Comment by roeierez** [comment] 2018-11-26 16:54
Thanks @wpaulino.
We are running on mobile and for a user that wants to receive money the case of remote node that open a channel with him is pretty common. For this user the current experience is bad as lots of time and bandwidth are wasted.
Regarding the fix I think there might be a problem in the following scenario:
1. Start LND.
2. During initial sync the birthday block is set.
3. Stop LND before the initial sync ended but after the birthday block is set.
All blocks that have been covered by the initial sync after the birthday will be missed by the initial rescan since it starts from tip now.
LMK if you prefer to move the discussion to btcwallet.

**Comment by wpaulino** [comment] 2018-11-26 18:08
> All blocks that have been covered by the initial sync after the birthday will be missed by the initial rescan since it starts from tip now.

If this happens, a rescan will start from the latest height known, and it will also attempt to catch up any missed blocks while it was down (see https://github.com/btcsuite/btcwallet/blob/master/wallet/chainntfns.go#L165).

**Comment by roeierez** [comment] 2018-11-26 18:35
> If this happens, a rescan will start from the latest height known, and it will also attempt to catch up any missed blocks while it was down

If you referring to the catchUpHashes I saw this function starts from "Manager.SyncedTo" point (see here: https://github.com/btcsuite/btcwallet/blob/master/wallet/chainntfns.go#L66)
and since the initialSync first downloads all headers to the tip this value would be the tip by the time the first rescan would start.

As an example to explain what I see, let's assume the birthday block height is "N" and the tip is "N + 300", then if the initial sync has progressed until "N + 100" for example and then restarted then the Manager.SyncedTo would be "N + 100" and the next run will skip the initialSync (since the birthday is set) and will start the rescan from the current known block "N + 100" (https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L697)
Resulting in missing 100 blocks.
Thanks and I hope I am not missing anything.

**Comment by wpaulino** [comment] 2018-11-26 19:15
> As an example to explain what I see, let's assume the birthday block height is "N" and the tip is "N + 300", then if the initial sync has progressed until "N + 100" for example and then restarted then the Manager.SyncedTo would be "N + 100" and the next run will skip the initialSync (since the birthday is set) and will start the rescan from the current known block "N + 100" (https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L697)
Resulting in missing 100 blocks.

This can already happen as is without this patch. Let's say you sync up to `N+100`, discover a UTXO, and restart. Once you restart, the initial sync logic won't get triggered, so we'd start from `N+100` anyway.

IMO "initial sync" is a term defined very loosely. How can you determine when it's really done? The point of this method _should_ be to just sync up the header chain until we discover the birthday block. Once that's done, we can follow with the rescan logic from our last synced to height to ensure we didn't miss any events.

**Comment by roeierez** [comment] 2018-11-26 20:05
> This can already happen as is without this patch

Right, agree!



> The point of this method _should_ be to just sync up the header chain until we discover the birthday block

Agree as well although I believe if the "initial sync" would be changed to stop on birthday and not on tip as it is now (We can call it syncToBirthday which makes a stronger definition) the following rescan would be bullet proof without missing any blocks but also agree such fix can be discussed in the scope of another patch.

Anyway I confirm your patch fixes the reported problem and thanks a lot for that!

**Comment by Roasbeef** [comment] 2018-11-26 20:46
Closing this issue for now, as it's actually a `btcwallet` issue. We can continue the conversation over there, thanks!

Also the start height there isn't chain tip, but the viewed synced to tip of the wallet.

**Closed by Roasbeef** 2018-11-26 20:46 UTC
Labels: wallet
