### ISSUE TITLE
Create autopilot settings rpc call

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#2127] opened 2018-10-30 18:15 UTC
### Feature Request

Create autopilot settings rpc call. 

It would be great if we could,
1. Turn on/off autopilot with an rpc call.
2. Update settings like maxchannels and maxchannelsize via rpc. 

Having to restart the node every time you want to change autopilot is a pain.

**Comment by wpaulino** [comment] 2018-10-30 19:44
> Turn on/off autopilot with an rpc call.

This will be addressed by #2039.

**Comment by wpaulino** [comment] 2019-04-18 07:56
> Turn on/off autopilot with an rpc call.

Done in #2039.

> Update settings like maxchannels and maxchannelsize via rpc.

Duplicate of #1918.

**Closed by wpaulino** 2019-04-18 07:56 UTC
Labels: P3, autopilot, enhancement, feature request, lncli, rpc
