### ISSUE TITLE
Feature Request: channel.db auto-sync with cloud services

### ISSUE THREAD

**Issue by junderw** [lightningnetwork/lnd#1626] opened 2018-07-26 01:55 UTC
### Use Case

- A large amount of server based computing is through cloud services such as AWS and Azure.
- channel.db backup is essential to maintaining a healthy LND node.
- Having a method to sync the channel.db with outside services would be a good fallback measure.

### Questions

- Would channel.db be more suited for an SQL platform or noSQL key value base platform?
- Is channel.db latency looking to be a large bottleneck? Could we allow a parameter to move the channel.db completely to cloud?

**Comment by Roasbeef** [comment] 2018-07-26 01:57
Duplicate of #175.

**Comment by Roasbeef** [comment] 2018-07-26 01:57
Do you mean backups, or like full on replication?

**Comment by junderw** [comment] 2018-07-26 02:00
Full on replication. Live.

In fact, even wondering if possible to replace channel.db and have it access the RDS/Dynamo for each read/write.

**Comment by Roasbeef** [comment] 2018-07-26 02:02
Yes that would be possible but requires a bit of re-working to introduce an interface in front of boltdb so we can add additional backends. It would require re-implementing the KV-store interface for each new storage backend.

**Comment by junderw** [comment] 2018-07-26 02:16
Yeah... it looks like channeldb is calling OS level file system directly... so it would need to create a mock filesystem that could translate into other interfaces without increasing latency too much...

In our discussions we think this is probably a must-have for production level deployments for exchanges. So it might not be super high priority right now. But eventually.

**Comment by Roasbeef** [comment] 2018-07-26 02:31
> so it would need to create a mock filesystem that could translate into other interfaces without increasing latency too much

Yeah so the goal here would be that `channeldb` gets some generic KV-store, and uses that directly. For the major SQL based databases, we'd need to create an abstraction layer to intelligently map the buckets/keys etc to tables. For other KV stores, then it's simpler as we can map to the same calls more or less 1:1. 

>  So it might not be super high priority right now. But eventually.

Agreed that it's definitely something on our radar. Doing so would also make unit testing certain areas of `lnd` easier as we wouldn't need to create a tear down a test DB each time, instead it would just be reading/writing from like an in-memory map.

**Comment by tiero** [comment] 2018-10-01 12:20
@junderw Are you working on this? I would like to experiment on it and see if it is feasible. The only issue I can see is making sure that all writes are atomic and maintain the _consecutio_ of backups.
AWS speaking, maybe we can use SQS on top of DynamoDB (or even S3 🤔 ) 

Are there other any considerations to take into account?

**Comment by xsb** [comment] 2018-10-01 20:20
I think supporting S3 would be a great idea as it's API it's widely used (minio, etc).

**Comment by Roasbeef** [comment] 2018-10-02 23:55
The first step here is actually to abstract out the database usage for boltdb into a _distinct_ interface. One good target would be to emulate the [`walletdb` interface](https://godoc.org/github.com/btcsuite/btcwallet/walletdb). With that alone we can then easily map to any existing database (that meets our consistency requirements), and emulate the bucket structure and transactional semantics. 

Alternatively, since the only _precious_ data is the channel information, and also the up to date instances of the switch itself (so we can continue forwarding in a fail over case), we can instead create _new_ implementations of the existing `htlcswitch` related interface, and erect a new set of interfaces for the channel storage. With this, the graph information is stored locally, while the crucial information required to perform a handoff are stored in the distributed database. 

The latter option is nice, as it then lets the new database possibly implement optimizations that wouldn't be possible with the KV model due to the restrictions it adds. For example, it doesn't need to worry about buckets, and could instead implement certain operations as a columnar store or the like.

**Comment by junderw** [comment] 2018-10-03 02:34
@tiero 

> Are you working on this?

No I am not. I am currently working on internal issues for my company.

I would appreciate any help on this issue. Thanks.

**Comment by Roasbeef** [comment] 2021-08-31 02:03
lnd 0.14 will have two optional remote DB options: `etcd` and postgres.

**Closed by Roasbeef** 2021-08-31 02:03 UTC
Labels: enhancement, database, P4
