### ISSUE TITLE
Allow CPFP or RBF on stuck force closing transaxtion

### ISSUE THREAD

**Issue by davidcaseria** [lightningnetwork/lnd#2899] opened 2019-04-05 23:34 UTC
### Background

When fee rates in the mempool spiked my channel opening transactions got "stuck" in the mempool with a low fee rate. While trying to troubleshoot I force closed the channel, however the fee rate for the closing transaction was also insufficient and got stuck. As a workaround I tried to open a new channel with a high fee rate which would use the output of the closing transaction as an input.

### Your environment

* version of `lnd`: `lnd version 0.6.0-beta commit=v0.6-beta-rc1`
* which operating system (`uname -a` on *Nix): `Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core Daemon version v0.17.1`

### Steps to reproduce

1. Open channel with a manually set low fee rate which will get stuck in the mempool
2. Force close the channel before the funding transaction is confirmed
3. Attempt to open another channel with a higher fee rate which requires the funds from the closing transaction by setting `min_confs=0` and `spend_unconfirmed=True`

### Expected behaviour

The closing transaction output should be selected when opening new channels if it's stuck in the mempool.

*OR*

A new API is exposed to replace the fee of the closing transaction.

### Actual behaviour

The open channel request errored out with the message `not enough witness outputs to create funding transaction` because the output of the closing transaction was not selected.

**Comment by Roasbeef** [comment] 2019-04-06 01:45
Duplicate of #609.

**Closed by Roasbeef** 2019-04-06 01:45 UTC
