### ISSUE TITLE
SendPaymentSync that encounters TemporaryChannelFailure never responds (504 Gateway Time-out)

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#2286] opened 2018-12-06 15:53 UTC
### Background

If I make an API request to `POST /v1/channels/transactions` that results in a TemporaryChannelFailure failure like so:
```
2018-12-06 10:48:18.790 [ERR] CRTR: Attempt to send payment 6290f2b54e7398de32dac081478bd51184eee0f5aec2dea69784e4010e2b705d failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc0106081e0)({
 Signature: (lnwire.Sig) (len=64 cap=64) {
  00000000  23 3c 29 81 0d 0d 76 22  ea dd c7 8d b0 c0 5d da  |#<)...v"......].|
  00000010  94 90 f4 50 e4 88 54 2c  45 dc 22 1b 5a 21 4e f7  |...P..T,E.".Z!N.|
  00000020  07 09 b2 39 41 98 12 96  41 51 a6 1c 1b d4 51 dd  |...9A...AQ....Q.|
  00000030  00 cd 35 d5 bd a1 ce fd  65 70 ae 4d c0 03 dd dd  |..5.....ep.M....|
 },
 ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
 ShortChannelID: (lnwire.ShortChannelID) 541230:2016:0,
 Timestamp: (uint32) 1543863863,
 Flags: (lnwire.ChanUpdateFlag) 256,
 TimeLockDelta: (uint16) 14,
 HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,
 BaseFee: (uint32) 1,
 FeeRate: (uint32) 10,
 ExtraOpaqueData: ([]uint8) (len=8 cap=1536) {
  00000000  00 00 00 00 76 04 67 00                           |....v.g.|
 }
})
```
the request never responds, until it gets a 504 gateway timeout.

It looks like it's retrying it a bunch, but I think it would make sense to limit the number of retries, and then to return an error properly, at least if you're doing it as an API request.

### Your environment

* version of `lnd` – 0.5.1
* which operating system (`uname -a` on *Nix) – Ubuntu 16.04
* version of `btcd`, `bitcoind`, or other backend – btcd

### Steps to reproduce

Make an API request to `POST /v1/channels/transactions` that will result in a TemporaryChannelFailure

### Expected behaviour

Request returns with a 500 error with some text explaining the channel failure

### Actual behaviour

Request times out with a 504

**Comment by Roasbeef** [comment] 2018-12-07 00:10
Possibly increase your read time out for the call? Generally, the original `SendPayment` API itself is a better target as its more actively maintained and gives the opportunity for incremental feedback. 

Closing this as a duplicate of #1867.

**Closed by Roasbeef** 2018-12-07 00:10 UTC
