### ISSUE TITLE
postgres db drastic size increase on new node

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#6662] opened 2022-06-23 08:26 UTC
### Background

Setting up lnd with postgres. 

### Your environment

* version of `lnd`: 0.15 RC 6
* which operating system (`uname -a` on *Nix). kubernetes-AAS
* version of `btcd`, `bitcoind`, or other backend. 0.22
* any other relevant environment details. 

### Steps to reproduce

node set up with postgres backend. 

SQL-as-a-service has been set up on gcloud. PostgreSQL 14 is being used. 

### Expected behaviour

db size on postgres should grow similarly to bbolt

### Actual behaviour

db increase by 3.2 GB/day

the node is new and have only 3 channels.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/11156370/175252135-102de937-960c-44fb-befe-3af55e64eba9.png">

**Comment by guggero** [comment] 2022-06-23 08:29
Hmm, this does look like abnormal growth indeed. Just to get some additional info on this: Do you run `VACUUM` regularly? If so, do you see a decrease in the storage usage?

**Comment by nicolasburtey** [comment] 2022-06-23 08:43
setting up VACUUM and see what will be the effect. 

it was not activated by default it seems.

**Comment by nicolasburtey** [comment] 2022-06-23 09:04
btw @guggero why would `VACCUM` has to be activated for lnd? using postgres for other stuffs and this is running just fine without. I don't know the intricacies of postgres.

**Comment by guggero** [comment] 2022-06-23 10:31
Okay, that's useful to know. Can you pinpoint which table has experienced the biggest growth?

**Comment by openoms** [comment] 2022-06-23 11:29
@bhandras the node had only 2 channels with 8 updates on one and ~20 on the other with a runtime of only few days.
@nicolasburtey is resetting the node going back to bbolt, but still might be able to see the existing tables.

**Comment by nicolasburtey** [comment] 2022-06-23 13:25
seems the issue is present on other node we tried to boostrap with postgres, so feels like a systematic issue (on our infrastructure at least)

**Comment by blckbx** [comment] 2022-06-23 16:21
Interesting. Had to deactivate archiving bc of disk space running low. After reading this, I can confirm that `pg_wal` takes up most of the space in postgres' datadir:

```sh
$ sudo du -h -d 1 postgresql/ | sort -hr
204G	postgresql/pg_wal
204G	postgresql/
716M	postgresql/base
1,8M	postgresql/pg_xact
568K	postgresql/global
136K	postgresql/pg_subtrans
28K	postgresql/pg_multixact
20K	postgresql/pg_replslot
16K	postgresql/pg_logical
4,0K	postgresql/pg_twophase
4,0K	postgresql/pg_tblspc
4,0K	postgresql/pg_stat_tmp
4,0K	postgresql/pg_stat
4,0K	postgresql/pg_snapshots
4,0K	postgresql/pg_serial
4,0K	postgresql/pg_notify
4,0K	postgresql/pg_dynshmem
4,0K	postgresql/pg_commit_ts

```

**Comment by bhandras** [comment] 2022-06-23 16:37
So far I tried running the bottlePay benchmark (adopted to use postgres) on `v0.15.0-beta.rc6` and for me after 8k payments the DB size is:

```
postgres@87d02469428e:~$ du -h -d 2 pgdata/ | sort -h
4.0K	pgdata/backup
4.0K	pgdata/data/pg_commit_ts
4.0K	pgdata/data/pg_dynshmem
4.0K	pgdata/data/pg_replslot
4.0K	pgdata/data/pg_serial
4.0K	pgdata/data/pg_snapshots
4.0K	pgdata/data/pg_stat
4.0K	pgdata/data/pg_tblspc
4.0K	pgdata/data/pg_twophase
12K	pgdata/data/pg_notify
16K	pgdata/data/pg_logical
20K	pgdata/data/pg_subtrans
20K	pgdata/data/pg_xact
28K	pgdata/data/pg_multixact
40K	pgdata/data/pg_stat_tmp
632K	pgdata/data/global
83M	pgdata/data/base
129M	pgdata/data/pg_wal
212M	pgdata/
212M	pgdata/data
```

I'm using the default settings `timescaledev/timescaledb-ha:pg12-latest` comes with.

**Comment by blckbx** [comment] 2022-06-23 17:43
Ok, after some research. I figured out my problem. I tried to setup replication between two local postgres instances. Gave up on it bc it didn't work out but forgot to remove replication slots. These stay active within the database and hog data 'til no space left. 
Removed those and set some checkpoints manually which drops unnecessary wals.

```sh
sudo du -h -d 1 postgresql/ | sort -hr
901M	postgresql/
721M	postgresql/base
178M	postgresql/pg_wal
1,8M	postgresql/pg_xact
568K	postgresql/global
160K	postgresql/pg_subtrans
28K	postgresql/pg_multixact
16K	postgresql/pg_logical
4,0K	postgresql/pg_twophase
4,0K	postgresql/pg_tblspc
4,0K	postgresql/pg_stat_tmp
4,0K	postgresql/pg_stat
4,0K	postgresql/pg_snapshots
4,0K	postgresql/pg_serial
4,0K	postgresql/pg_replslot
4,0K	postgresql/pg_notify
4,0K	postgresql/pg_dynshmem
4,0K	postgresql/pg_commit_ts
```
But this was just my case. There're other reasons for bloated `pg_wal` directories.

**Comment by bhandras** [comment] 2022-06-23 17:47
> so far `VACUUM` has had no effect

Since the node as you mentioned is mostly idle, most of the updates in the DB will be gossiped channel updates updating channel policies. These updates do delete/insert/update which adds quite a bit of dead tuples. I'm curious why vacuum might not have worked?

Other thing could be that's causing large wals if checkpointing fails for some reason.

**Comment by bhandras** [comment] 2022-06-23 17:48
> Ok, after some research. I figured out my problem. I tried to setup replication between two local postgres instances. Gave up on it bc it didn't work out but forgot to remove replication slots. These stay active within the database and hog data 'til no space left. Removed those and set some checkpoints manually which drops unnecessary wals.
> 
> ```shell
> sudo du -h -d 1 postgresql/ | sort -hr
> 901M	postgresql/
> 721M	postgresql/base
> 178M	postgresql/pg_wal
> 1,8M	postgresql/pg_xact
> 568K	postgresql/global
> 160K	postgresql/pg_subtrans
> 28K	postgresql/pg_multixact
> 16K	postgresql/pg_logical
> 4,0K	postgresql/pg_twophase
> 4,0K	postgresql/pg_tblspc
> 4,0K	postgresql/pg_stat_tmp
> 4,0K	postgresql/pg_stat
> 4,0K	postgresql/pg_snapshots
> 4,0K	postgresql/pg_serial
> 4,0K	postgresql/pg_replslot
> 4,0K	postgresql/pg_notify
> 4,0K	postgresql/pg_dynshmem
> 4,0K	postgresql/pg_commit_ts
> ```
> 
> But this was just my case. There're other reasons for bloated `pg_wal` directories.

Yes replication failures will also result in huge wals piling up.

**Comment by Roasbeef** [comment] 2022-06-28 00:52
Closing this now as the root cause has been identified.

**Closed by Roasbeef** 2022-06-28 00:52 UTC
Labels: database, troubleshooting
