### ISSUE TITLE
`too-long-mempool-chain` error when multiple confirmed UTXOs available

### ISSUE THREAD

**Issue by vindard** [lightningnetwork/lnd#6959] opened 2022-10-01 01:34 UTC
### Background

I'm opening this issue to start tracking an issue we've been having on our instances. Our instance throws the following error every so often when calling the `SendCoins` grpc command via the `alexbosworth/lightning` library:
```
 UNKNOWN: unmatched backend error: -26: too-long-mempool-chain, too many unconfirmed ancestors [limit: 25]
```
This is strange because it occurs when we have multiple UTXOs available to fulfill the payment amounts in question. It happened a few moments ago again and our instance has 8 unconfirmed utxos and 1260 confirmed ones ranging from 1-conf to 2411-confs.

Are there any ideas on how we can start debugging this?

### Your environment

* `lnd 0.15.1-beta commit=v0.15.1-beta`
* `bitcoind`

**Comment by Roasbeef** [comment] 2022-10-01 02:15
That's a `bitcoind` backend error. In this case, are y'all spending unconfirmed change? Or spending an unconfirmed user deposit? In either of these cases, you can inadvertently create a long chain of transactions that is (somewhat arbitrarily) rejected by bitcoind.

**Comment by nicolasburtey** [comment] 2022-10-01 07:10
> In either of these cases, you can inadvertently create a long chain of transactions that is (somewhat arbitrarily) rejected by bitcoind.

yes that is correct. you can assume one utxo is in this unconfirmed stage and has been respent and have created a long chain.

but lnd has also acceess to 100 of other utxos that have been confirmed

so the question is why the UTXO selection algorithm of lnd doesn't favor confirmed UXTOs automatically?

**Comment by guggero** [comment] 2022-10-03 08:12
There's the `--min_confs` parameter in `SendCoins` that can be used to avoid spending unconfirmed UTXOs. And that flag is set to `1` by default. So I assume `alexbosworth/lightning` sets that to 0 by default? Can you overwrite that in the command/API you use? I assume something like `utxo_confirmations`.

**Comment by nicolasburtey** [comment] 2022-10-03 09:14
yes we are indeed having `--min_confs 0` because we need it for our use case, but we would assume lnd to pick up preferably confirmed utxos or retry with another utxo sets, if the utxo(s) lnd has selected reached `too-long-mempool-chain` stage

**Comment by guggero** [comment] 2022-10-03 09:16
The coin selection algorithm is pretty limited currently. There are only two modes, largest first or random. Both of which don't take into account the number of confirmations. So I assume the unconfirmed UTXO is pretty large compared to others in the wallet?

**Comment by nicolasburtey** [comment] 2022-10-03 09:33
>  So I assume the unconfirmed UTXO is pretty large compared to others in the wallet?

it's a good assumption. ie: a loop out UTXO. 

you can also assume a fairly high frequency payment use case

**Comment by Roasbeef** [comment] 2022-10-03 18:33
One way to get around this (inadvertently making long strings) is to do manual coin selection (lock utxos + fund psbt). You can also attempt to monitor the ancestor depth externally as well and use that as a trigger for when to swtich to conf, or do manual coin selection. 

This issue #6949 will make manual coin selection much easier in the future (just specify the utxos and skip a lot of the other steps). 

Given this is a bitcoind error caused by creating long chains of transactions, which can be prevented with a particular use of the APis, I think we can close this now?

**Comment by alexbosworth** [comment] 2022-10-03 21:30
The default in the library is to use the LND default confirmed UTXOs only, a potential mitigation is to implement logic to look to see if you have confirmed UTXOs before opting in to use unconfirmed UTXOs

**Comment by Roasbeef** [comment] 2022-10-10 20:49
Closing this since it's a bitcoind mempool issue and it's the caller's responsibility to ensure they're not making chains that are too long, as depending on the backend, lnd doesn't have visibility into all the unconfirmed ancestors.

**Closed by Roasbeef** 2022-10-10 20:49 UTC
Labels: wallet, backend

**Comment by iacopo112** [comment] 2023-05-21 10:32
hi guys i have the same problem how to resolve?
