### ISSUE TITLE
[bug]: Closed trusted zero-conf unbroadcasted channels stay pending 

### ISSUE THREAD

**Issue by bota87** [lightningnetwork/lnd#7818] opened 2023-07-10 22:16 UTC
### Background

I've opened some trusted channels using balance of satoshis from my node to my blixt wallet, when I close them (1 cooperative and 1 forced) both are stuck on waiting_close_channels on pendingchannels

### Your environment

* version of `lnd` 0.16.4
* version of `bitcoind` 25

### Steps to reproduce

On blixt wallet: set zero-conf enabled peer and connect to that
On node: `bos open <wallet-public-key> --type private-trusted --avoid-broadcast --amount 1000000`
Coop or force close the channel from node or from wallet, dosen't matter
On both: lncli pendingchannels return the channel on waiting_close_channels, if force closed only the initiator see the channel close, for the other peer listchannels return the channel as active

**Comment by ViktorTigerstrom** [comment] 2023-07-11 19:08
Thanks for the issue report @bota87!
Would you be able to share some logs, potentially covering the channel open, but especially covering a cooperative closure & a force closure in order for us to be able to identify the issue clearer? If possible, please share logs from both perspectives when the node is the peer initiating the closure as well as when the wallet is.

Thanks again for the report!

**Comment by ziggie1984** [comment] 2023-07-12 10:01
I have two questions here:

You mention in the beginning the setting: `--avoid-broadcast` did you broadcast this transaction anytime ? If not it's understandable that your closing channels are in the waiting_close state because their inputs has never seen the blockchain.

I think you did that deliberately, so you never planned to broadcast the funding_tx?

**Comment by Crypt-iQ** [comment] 2023-07-12 13:55
basically dupe of https://github.com/lightningnetwork/lnd/issues/7028

**Closed by Crypt-iQ** 2023-07-12 13:55 UTC
Labels: bug, channel closing, needs triage
