### ISSUE TITLE
Send Coins with a target confirmations value set calculates insanely high fee values

### ISSUE THREAD

**Issue by michaelWuensch** [lightningnetwork/lnd#4741] opened 2020-11-02 08:22 UTC
### Background

Send Coins with a target confirmations value set calculates insanely high fee values.
The same for Estimate Fee.

I did a transaction with target confirmation set to 36 at (8:24). The transaction fee was 125.9 sat/vByte. It confirmed one Block later.

30 Minutes before (7:53) I did a transaction with target confirmation set to 1. The transaction fee was 355.8 sat/vByte.

Now here is a screenshot of the mempool at that time.

![mempool](https://user-images.githubusercontent.com/15313630/97844996-432fd580-1cec-11eb-8262-b4caa1d2c7b4.png)

### Your environment
lnd v0.11.1

### Expected behaviour
Much lower fees for a confirmation target of 36 blocks
Lower fees for a confirmation target of 1 block

**Comment by guggero** [comment] 2020-11-02 08:48
We use bitcoind's fee estimation in `lnd`. By default, the estimation mode is set to `CONSERVATIVE` which gives relatively high estimates. You can set `--bitcoind.estimatemode=ECONOMICAL` to get lower estimates.
Fee estimation also is really hard, is never really a real-time thing and depends on your node's version of the mempool. For example if you used the default 300 MB mempool max size setting in bitcoind, some transactions might have been dropped during the spike. I think that can also have an impact on fee estimation.

**Comment by guggero** [comment] 2020-11-02 10:22
Yes, what you describe is true.  For force-closes, the "anchor output commitment format" for channels will help. This is already implemented in `lnd` (and being worked on in other implementations) but not yet turned on by default (IIRC).
For coop-closes you can always specify the `--sat_per_byte` value. If the remote peer doesn't agree, you can force close and CPFP with your desired fee rate (assuming anchor outputs are used).

**Comment by ZsZolee** [comment] 2020-11-02 10:46
For force-closes is there any plan when will be the already opened channels converted to "anchor output commitment format"? My worries are not when I close the channel, but when my partner closes it. I know if I close it, I can specify the "sat/byte", but if the other side closes it I already lost in the past one week around 2% in fees (way more than earned routing fees). Which is crazy high, because the mempool was only 50-60MB big, what will be if it will be 10-100x more? I hope it is understandable my worries. I don't want to close my channels, but I can't control my channel partners decision. (Not to mention that my node is always online and some of my partners are using force-closing techniques, so I'm loosing crazy amount of money)

**Comment by guggero** [comment] 2020-11-02 12:27
Yes, there are plans to upgrade existing channels: https://www.mail-archive.com/lightning-dev@lists.linuxfoundation.org/msg02017.html

Though there is quite a bit of work needed for this and it also requires a change to the spec.

Your worries are definitely understandable. The recent wave of involuntary force-closes (potentially caused by unusual gossip traffic, among other things) also didn't help the current situation. But we are doing everything we can to mitigate those situations where possible.

**Comment by ZsZolee** [comment] 2020-11-02 15:00
Thanks to all of you for your hard work! I know you all are doing your best.

**Comment by Roasbeef** [comment] 2020-11-04 01:20
Closing as there's no issue with lnd here. Since you can use the `BumpFee` call to increase your fee using CPFP, you can target a very low confirmation range (say 50 or so blocks), then bump it up if you want it to be confirmed sooner.

**Closed by Roasbeef** 2020-11-04 01:20 UTC
