### ISSUE TITLE
Unexpected funding_locked during channel operation

### ISSUE THREAD

**Issue by araspitzu** [lightningnetwork/lnd#3189] opened 2019-06-11 11:39 UTC
### Background
Alice and Bob have a channel, Alice is running eclair and Bob LND v0.6.1-beta. The channel is operating normally and there are a few payments being routed, it eventually reaches commitment number 6. However at some point Bob and Alice perform a reconnection and right after the `channel_reestablish` Bob sent an unexpected `funding_locked`, note that Bob sent a `channel_reestablish` with `next_local_commitment_number=7` and `next_remote_revocation_number=6` and the `funding_locked` that follows makes it a spec violation.

### Your environment

* version of `lnd` = 0.6.1-beta
* which operating system = archlinux x86_64
* version of `bitcoind` = 0.18

### Steps to reproduce
Unfortunately i'm not able to reproduce and i'm waiting on the logs from the remote (Bob).

### Expected behaviour
Channel should have kept operating normally.

### Actual behaviour
A `funding_locked` has been received from LND .

Logs from Alice:
```
2019-05-29 09:53:00,377 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1 - IN msg=OpenChannel(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1,1000000,0,573,990000000,10000,1000,40955,144,483,029d987882350139a0557c71ce8e8de0ddb3bd3a6d0f727d60e9f4dc371b11768f,03fabe02a2c2b38715e32c8c8246b99f968ef7183d22f393378962cc7647cd08c0,03674d5f81dacbed8c4b70f8b55b2538567bc280c28c007ffe988aa029f3fd35f2,02bb36a03190f2d14ddfee6ea66b5ad411f07e4270ac653df8f54a03cd5f9f1c41,02e857361bd89585b7cb7d195594ec6ce49ef081eec391b47d4d80a65b42eeb5cd,03fa2f1084e00c8ce00f43757113fea972cad2bdbb59cbb7e814d6b99a64ec190f,1)
2019-05-29 09:53:00,404 INFO  f.a.e.channel.Channel  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1 - received OpenChannel=OpenChannel(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1,1000000,0,573,990000000,10000,1000,40955,144,483,029d987882350139a0557c71ce8e8de0ddb3bd3a6d0f727d60e9f4dc371b11768f,03fabe02a2c2b38715e32c8c8246b99f968ef7183d22f393378962cc7647cd08c0,03674d5f81dacbed8c4b70f8b55b2538567bc280c28c007ffe988aa029f3fd35f2,02bb36a03190f2d14ddfee6ea66b5ad411f07e4270ac653df8f54a03cd5f9f1c41,02e857361bd89585b7cb7d195594ec6ce49ef081eec391b47d4d80a65b42eeb5cd,03fa2f1084e00c8ce00f43757113fea972cad2bdbb59cbb7e814d6b99a64ec190f,1)
2019-05-29 09:53:00,414 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1 - OUT msg=AcceptChannel(bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1,546,1000000000,10000,1,3,720,30,03e88f73987b1a3cf91a0193ea6f4bd5ca57d2f3d94be87355a6f8a2ce6d381be2,0205944ec46964d65269c25551feb80bbca952a1b346b2d408c2b564a06b3188e9,02920d08443a025a7463ab1c1bc4f7ae0afa118e64c550e4d3378523b8e796ae41,027dd3bf8ff26daa2d8920817090b4ff19033057764893b55fb9d1221577b72bd0,028c11382b9a0516f13e9d5072785cfd16fbccc745b77c8fbe90a1781930606668,03634df3116ccb7d4da30f62c1a95fc896d6315c5357e25ed8efb3c0aa79ec5f3c)
2019-05-29 09:53:00,466 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1 - IN msg=FundingCreated(bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1,dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47544,1,ByteVector(72 bytes, 0x3045022100dc3e1fa6058abb39d5bb78aed4c875aefe56813340b603a4b77ef35ddac086ba02202c7a7e7a9b836ebe5f3d1370855ad30d5050e676ee94b1b855ef75c67b4ed94b01))
2019-05-29 09:53:00,471 INFO  fr.acinq.eclair.io.Peer  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 - channel id switch: previousId=bec3df72ed5151cb364ef798776c47ef0ea94ad16d195215edbff62201bde2e1 nextId=dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545
2019-05-29 09:53:00,476 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - OUT msg=FundingSigned(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,ByteVector(71 bytes, 0x304402207ad5d77b062a57ecea4153fb590e33c87e06f94c242d4e204f6b87e6d473bc12022016914bd7ed492d435003c3198ecf2647714241e91b690fff6a4c5991bf9c361301))
2019-05-29 14:34:09,261 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - IN msg=FundingLocked(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,038aee4b4231a89777db476a53478cfe3ce9a24a1a6cc26332c623809412127d0b)
2019-05-29 14:34:09,261 INFO  f.a.e.channel.Channel  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - received their FundingLocked, deferring message
2019-05-29 14:34:11,632 INFO  f.a.e.channel.Channel  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - channelId=dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 was confirmed at blockHeight=578358 txIndex=376
2019-05-29 14:34:11,636 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - OUT msg=FundingLocked(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,035f867fb45ba49cabc58fff13e5371c5fd5f48acded8fae4b37eb26bc627c194d)
2019-05-29 14:34:11,669 INFO  f.a.e.channel.Channel  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - emitting channel_update=ChannelUpdate(ByteVector(72 bytes, 0x3045022100837a21a478f1f2d1adf89922a21732c2d914a7415db378ab0ea684254aee51e902207824e86b2246534f1aef830ea8119dcec6d9eb6782e5e11c7dc34df858f0708a01),6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,578358x376x1,1559133251,1,3,144,1000,0,1,Some(1000000000)) enabled=false 
2019-05-29 14:58:13,433 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - IN msg=AnnouncementSignatures(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,578358x376x1,ByteVector(71 bytes, 0x30440220116c9467f638d9ef91828a93a72158b787fb674849a524041786a854f3d34bf50220692cd943c71f36329436ac448d545772cea959f53bde572735008f10dded1a7501),ByteVector(72 bytes, 0x3045022100f61aeb1e3108068b48604102ae09a4667a77c13c759ffa1f29bbc5122765615102206346f76e5f22b9d35111ca35061c863daa993aceb422319726a5cf69ce387fc901))
2019-05-29 15:23:29,518 INFO  f.a.e.channel.Channel  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - funding tx is deeply buried at blockHeight=578358 txIndex=376 shortChannelId=578358x376x1
2019-05-29 15:23:29,525 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - OUT msg=AnnouncementSignatures(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,578358x376x1,ByteVector(71 bytes, 0x30440220558cd76915e173c4a8b7c816b7a4efa628e3db0103974dc1df08e948210403ec02201efa96ea9f473e366fbccfbd155e2c17b9a448f7c75f4498fd8491d7a97dca9101),ByteVector(72 bytes, 0x3045022100ff517f6d47faac0053f2965dc924b49a1c414e9b152bb1eb8759ae7944027a7102200428e0bfaa44e15cfd44c35b50c2f79df6782afd6e4676948d9316f5ff2bc79601))
...
<HTLCs> in/out
...
2019-05-30 09:14:51,081 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - OUT msg=ChannelReestablish(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,7,6,Some(17a48ee0cd02b068f0c4dd42992cc99a37e75257f38738866cd31bd732b647d0),Some(02f50610f281b144d61a21d821e71c1bacbdff8c8f419ccc1e4a43bf106919174b))
2019-05-30 09:14:51,967 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - IN msg=ChannelReestablish(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,7,6,Some(54ceab23677d1f71e4bf9b28a9f2dff6164e71af77c7d64eb83c41b32e3af688),Some(022cad8861cdc0c68a0c4cf40f68c83545978b976c22bcddf81d3dd51dc4304741))
2019-05-30 09:14:52,047 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - IN msg=AnnouncementSignatures(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,578358x376x1,ByteVector(71 bytes, 0x30440220116c9467f638d9ef91828a93a72158b787fb674849a524041786a854f3d34bf50220692cd943c71f36329436ac448d545772cea959f53bde572735008f10dded1a7501),ByteVector(72 bytes, 0x3045022100f61aeb1e3108068b48604102ae09a4667a77c13c759ffa1f29bbc5122765615102206346f76e5f22b9d35111ca35061c863daa993aceb422319726a5cf69ce387fc901))
2019-05-30 09:14:52,048 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - OUT msg=AnnouncementSignatures(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,578358x376x1,ByteVector(71 bytes, 0x30440220558cd76915e173c4a8b7c816b7a4efa628e3db0103974dc1df08e948210403ec02201efa96ea9f473e366fbccfbd155e2c17b9a448f7c75f4498fd8491d7a97dca9101),ByteVector(72 bytes, 0x3045022100ff517f6d47faac0053f2965dc924b49a1c414e9b152bb1eb8759ae7944027a7102200428e0bfaa44e15cfd44c35b50c2f79df6782afd6e4676948d9316f5ff2bc79601))
2019-05-30 09:14:52,534 INFO  f.a.eclair.Diagnostics  n:02e46cf7becfc79646e0580646c3915dfcebb34acefaaac1534b770ff6f45fc694 c:dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545 - IN msg=FundingLocked(dd95ed4a380db64d0451616c82ff9450dd207fbacd46947370342ed6b0e47545,032eb0e1f3aa98393b0042ac89667a603693d9b303511de69d545160db11fb3dd1)

```

**Comment by Roasbeef** [comment] 2019-06-12 04:10
Is the pubkey in that `FundingLocked` message the _first_ next revocation point, or the current one at state 6/7?

**Comment by araspitzu** [comment] 2019-06-12 07:57
It seems to be a completely new point. The current one for state 6/7 was sent by Bob in his `channel_reestablish` (Bob supports option_data_loss_protec) and is different from the one received in the `funding_locked`. Note that since then the channel was stuck with Alice waiting for Bob to revoke commitment number=6 but Bob never sends a `revoke_and_ack`, perhaps the `next_per_commitment_point` that was supposed to be sent there has been sent in a `funding_locked`?

**Comment by saubyk** [comment] 2023-11-01 03:18
Closing this dated issue as it was reported in version 0.6. Can reopen if the issue is encountered again in the latest releases.

**Closed by saubyk** 2023-11-01 03:18 UTC
Labels: bug, p2p, P3, interop
