### ISSUE TITLE
extract preimages from mempool htlc spends

### ISSUE THREAD

**Issue by antonilol** [lightningnetwork/lnd#6566] opened 2022-05-23 16:05 UTC
### Background

extracting preimages from mempool transactions that spend htlc outputs on a broadcast commitment transaction will result in faster HTLC settlement along the path

from bolt 05:
```
A node:
    ...
  - MAY monitor (valid) broadcast transactions (a.k.a the mempool).
    - Note: watching for mempool transactions should result in lower latency HTLC redemptions.
```

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment] 2022-05-23 17:50
Duplicate of https://github.com/lightningnetwork/lnd/issues/4254

**Closed by Roasbeef** 2022-05-23 17:50 UTC
