### ISSUE TITLE
Mission Control excessively penalizes nodes that frequently update feerates

### ISSUE THREAD

**Issue by ajpwahqgbi** [lightningnetwork/lnd#5060] opened 2021-02-28 06:31 UTC
### Background

I [and other node operators](https://old.reddit.com/r/Satoshocracy/comments/ls4ajl/i_made_200k_in_routing_fees_this_month_alone/got93zo/) have noticed that when we change advertised feerates, our routing traffic on the affected channel falls dramatically for some time. In my case I notice reduced traffic for at least a week, with high rates of WIRE_FEE_INSUFFICIENT (the c-lightning equivalent to lnwire.FailFeeInsufficient) for attempted forwards.  I suspect this is due to the behavior of LND's Mission Control.

Looking through the code, I think what is going on is that many LND nodes do not get timely channel updates, then try to route an HTLC through the affected node, [the payment fails with lnwire.FailFeeInsufficient](https://github.com/lightningnetwork/lnd/blob/master/routing/result_interpretation.go#L350) and the node [is "penalize[d] as much as we can"](https://github.com/lightningnetwork/lnd/blob/master/routing/result_interpretation.go#L409).

Admittedly I do not have anywhere near a complete understanding of Mission Control or the whole context and intent behind this behavior. I know from the comments there is a "second chance" functionality but I do not know anything about it.  More guidance would be appreciated.

### Your environment

(unknown, suspected to be LND)

### Steps to reproduce

1. Run a routing node for a while and get some forwarding traffic
2. Update your feerate to a higher fee.
3. Observe reduced forwarding traffic and increased WIRE_FEE_INSUFFICIENT/lnwire.FailFeeInsufficient failure rate for attempted forwards

### Expected behaviour

`lnwire.FailFeeInsufficient` should not penalize the offending node; there is nothing wrong with updating a feerate.

### Actual behaviour

It looks like (and my experience supports the hypothesis) LND's Mission Control is penalizing nodes that have updated feerates LND hasn't yet learned about.

**Comment by whitslack** [comment] 2021-03-01 20:49
@ajpwahqgbi: Do you know whether C-Lightning actually *sends* a channel update attached to `WIRE_FEE_INSUFFICIENT` errors? That seems like something that, unless mandated by the specs, the C-Lightning developers may have elided, expecting that the sending node would eventually receive the new channel announcement via gossip. (To be clear, they *shouldn't* rely on that, but I can expect that they may have.)

**Comment by Roasbeef** [comment] 2021-03-01 23:06
> Do you know whether C-Lightning actually sends a channel update attached to WIRE_FEE_INSUFFICIENT errors?

This is a very good question @whitslack! IIRC, CL actually uses lazy logic here: they'll only send out the update once someone comes across and attempts route with an outdated policy. This may have changed, but iirc in the past this is how they handled the enable/disable bit of a channel.

**Comment by ajpwahqgbi** [comment] 2021-03-03 20:14
It appears that C-Lightning does attach an update: https://github.com/ElementsProject/lightning/blob/master/lightningd/peer_htlcs.c#L782

I am not sure when it sends out channel update gossip, but I imagine it's not that lazy. Maybe @rustyrussell can give insight?

@Roasbeef 
>  If we get a failure, and that failure has a channel update attached to it, we'll attempt using that fresh one again w/o any penalty. This is to handle the case of a node changing its fees, but us not having the new fee update at the time of payment attempt.

OK, sounds reasonable.

> This is to be expected, given that updates don't instantaneously propagate through the entire network. I'd also be curious w.r.t your sample size, and how you're drawing this conclusion.

Sure, of course. But by 'some time' I mean upwards of a week. I admit this is too subjective. I will write some analysis scripts to demonstrate the routing volume changes and WIRE_FEE_INSUFFICIENT rates.

>  They may be correlated, but necessarily the root cause.

 This is true, but I struggle to think of how that could be. Of course there is not even a guarantee that this behavior comes from lnd. I suspect that it does, though, given lnd's prevalence on the LN.

**Comment by Roasbeef** [comment] 2021-03-05 00:19
> Sure, of course. But by 'some time' I mean upwards of a week. I admit this is too subjective. I will write some analysis scripts to demonstrate the routing volume changes and WIRE_FEE_INSUFFICIENT rates.

Yeah it's hard to gauge, as it's just anecdotal information. It may be the case that you simply just are getting less traffic due to the fee update itself, and unless you have a lot of data over a long period of time, we can't come to any strong conclusions here. You may just be seeing some cyclic activity w.r.t your forwarding patterns, who knows. 

But as I mentioned above, `lnd` will try again (with no penalty) if we get a channel update due to a fee discrepancy. If you can create a reproducible scenario for us where this isn't the case, then we actually have something to investigate. In the absence of that, I'll close the issue for now until we get additional information.

**Closed by Roasbeef** 2021-03-05 00:19 UTC
