### ISSUE TITLE
lnd refuses inbound connections

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1337] opened 2018-06-06 22:13 UTC
lnd thinks that a node is connected even though the tcp socket is down. gossip-ping timeout doesn't help either.
also a mutex is hung somewhere because `updatechanpolicy` doesn't work, but most other commands work.
it doesn't seem to forward/send/receive any payments though.

```
2018-06-06 15:31:09.794 [WRN] SRVR: Received inbound connection from peer 03685a27a2d29f3f14d02dde544537317b624e39e540b6389fc6404dc3d452cb1d, but already connected, dropping conn
2018-06-06 15:36:10.048 [WRN] SRVR: Received inbound connection from peer 03685a27a2d29f3f14d02dde544537317b624e39e540b6389fc6404dc3d452cb1d, but already connected, dropping conn
2018-06-06 15:41:10.379 [WRN] SRVR: Received inbound connection from peer 03685a27a2d29f3f14d02dde544537317b624e39e540b6389fc6404dc3d452cb1d, but already connected, dropping conn
2018-06-06 15:46:10.664 [WRN] SRVR: Received inbound connection from peer 03685a27a2d29f3f14d02dde544537317b624e39e540b6389fc6404dc3d452cb1d, but already connected, dropping conn
```
```
$ sudo netstat -nap | grep 5.39.82.105
$ lncli connect 03685a27a2d29f3f14d02dde544537317b624e39e540b6389fc6404dc3d452cb1d@5.39.82.105:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 5.39.82.105:58642
$ sudo netstat -nap | grep 5.39.82.105
```

**Comment by cfromknecht** [comment] 2018-06-06 22:35
@robtex @wpaulino I think this might be related to #1008

**Comment by cfromknecht** [comment] 2018-06-07 01:46
@robtex do you see this log entry:
https://github.com/lightningnetwork/lnd/blob/master/server.go#L1369
anywhere before the occurrence? Would have printed `Peer 5.39.82.105:58642 has been disconnected`.

Your comments on not being able to send/receive make me think the switch is deadlocked somehow. Best guess atm is that the switch is blocked while tearing down the peer, even though the connection itself has been closed. 

Since we don't fully remove the peer from the server's map until this process happens, we continue to deny the incoming connection requests.

This may have been partially addressed by #1339, which fixes a potential deadlock w/in the switch. If you have more logs from this we might be able to glean if this was indeed the culprit

**Comment by sstone** [comment] 2018-06-08 16:41
We often experience connection issues with Bitrefill and Rompert, usually when we update and restart Our eclair nodes: it sometimes becomes impossible to reopen existing channels, and we enter a connect/disconnect loop.
We could confirm (by looking at the logs) that in at least one case it was the issue that @robtex described above: lnd thought it still had an existing connection and refused the new one. 

We could reproduce this problem without eclair: connect lnd A to lnd B, `kill -9` lnd A, it won't connect to lnd B anymore (I guess it would again after a very long timeout).

The problem is that LN nodes multiplex traffic over a single connection per peer (see https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#connection-handling-and-multiplexing): multiple connections per peer are not allowed, yet it is very hard to detect that connections are gone.

Since making sure that there is only one connection per peer is handled at the application level, wouldn't it be better, when a new tcp connection is created or accepted, and LN handshake has been processed properly, to keep it and replace the existing one ?
This is what we do on eclair, and we believe that it makes handling "unreliable" peers such as mobile phones easier. WDYT ?

**Comment by Roasbeef** [comment] 2018-06-08 20:38
> We could reproduce this problem without eclair: connect lnd A to lnd B, kill -9 lnd A, it won't connect to lnd B anymore (I guess it would again after a very long timeout).

Do A and B have a channel with each other? We don't reconnect unless we have an active channel with  the node. By connect, do you mean it can't connect at all, or just not auto reconnect? 

> yet it is very hard to detect that connections are gone.

It should be the case that we get an EOF error from the OS (in the golang runtime) when the connection is severed. If it's the case that for w/e reason, killing the other process doesn't actually hang up the file descriptor, then would expect the connection to die after a time out. 

Are you able to repro the above on the latest master? 

> wouldn't it be better, when a new tcp connection is created or accepted, and LN handshake has been processed properly, to keep it and replace the existing one ?

That's what we do: there's a tie breaker w.r.t which connection we keep, and which one we kill.

**Comment by Roasbeef** [comment] 2018-06-09 20:59
> We just keep the new connection (handshake was successful so it should be good)


They key is that _both_ node make the same decision though. How do you handle concurrent connection attempts? (there is no old conn)

**Comment by Roasbeef** [comment] 2018-06-09 21:08
The issue w/ just keeping the new connection is that then you may never converge to a stable state. Either side can always replace the connection, rather than the state machine always terminating, and then ignoring any "uncompliant" connections after a decision has been made.

**Comment by cfromknecht** [comment] 2018-06-10 02:51
@sstone I wrote up a description of the problem/solution here: https://github.com/lightningnetwork/lnd/pull/1351

In the long term, I think we should move to pubkey comparison as a tie-breaker, since it's the only stable procedure. I've implemented a patch for lnd that should play nicely with currently deployed strategies in lnd and eclair :)

**Closed** 2018-06-12 19:32 UTC
