### ISSUE TITLE
[feature]: recovery mode should also scan for funds on change addresses

### ISSUE THREAD

**Issue by tuvok137** [lightningnetwork/lnd#7260] opened 2022-12-16 23:00 UTC
If the remote node force closes a channel and i only got a seed backup the recovery mode should also scan change addresses.
right now i have to use a workaround like blue wallet.
other node software implementations dont even show you the seed to begin with.
would be nice if i can recover funds also sitting on change addresses.
thx

**Comment by Roasbeef** [comment] 2022-12-16 23:24
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/4778

It does scan "change" addresses, but not "change" addresses created as a result of a force close.

**Comment by Roasbeef** [comment] 2022-12-16 23:24
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/4778

It does scan "change" addresses, but not "change" addresses created as a result of a force close.

**Closed by Roasbeef** 2022-12-16 23:24 UTC
Labels: enhancement

**Comment by guggero** [comment] 2023-01-03 09:53
BTW, you can use [`chantools sweepremoteclosed`](https://github.com/guggero/chantools/blob/master/doc/chantools_sweepremoteclosed.md) to scan for those force-close outputs if you don't have the `channel.backup` file anymore.
