### ISSUE TITLE
Can't gracefully close a channel

### ISSUE THREAD

**Issue by patrikmojzis** [lightningnetwork/lnd#4802] opened 2020-11-24 16:19 UTC
### Background

Today I wanted to close 2 channels:
1) 9271f79c4384ee3121b815cbfb57ac1890063597cdd8ebbdee4f78630b0f3976 
2) 9e76d800fdbb0b3b16290e931a00b599ddd719ab6ce3ab304c2b194c9d898070

- Nodes were online but graceful close did not work
- Ended up force closing

**Log:** [https://patrikmojzis.com/lnd.log](https://patrikmojzis.com/lnd.log)

### Your environment

* version of `lnd`: 0.11.99-beta commit=v0.11.0-beta-442-g887ff442db593bb63965cea2c6938bbd5f84309c
* version of `btcd`, `bitcoind`, or other backend: Neutrino
* Tor

### Steps to reproduce

```
lncli closechannel 9271f79c4384ee3121b815cbfb57ac1890063597cdd8ebbdee4f78630b0f3976 0
lncli closechannel 9e76d800fdbb0b3b16290e931a00b599ddd719ab6ce3ab304c2b194c9d898070 0
```

### Actual behaviour

- Close channel command is pending indefinitely in terminal
- Closing transaction won't get broadcasted
- Channel goes to "Closing" state on my side only
- Luckily channel can be then force closed (that is what I did)

**Comment by JPyke3** [comment] 2020-12-31 09:50
Did you end up getting this sorted? I am having a similar issue. I am more interested in the reasoning why more than I am interested in actually closing the channel itself.

**Comment by guggero** [comment] 2021-01-02 12:43
This can happen if the remote peer does not answer reliably. Unfortunately if the coop close negotiation fails, the database state locally is already updated and a second coop close negotiation cannot be attempted. See https://github.com/lightningnetwork/lnd/issues/4819

There are many poorly connected (network/p2p wise) nodes out there. If they don't respond in time, there's not much `lnd` can do. Therefore trying again is probably the only thing that can be done. This should be possible once #4819 is fixed.

I'm closing this as a duplicate of #4819.

**Closed by guggero** 2021-01-02 12:43 UTC
