### ISSUE TITLE
Pending open channel since 2 weeks

### ISSUE THREAD

**Issue by sohomang** [lightningnetwork/lnd#3768] opened 2019-11-26 21:14 UTC
### Background

I have a channel opening pending since 2 weeks. Stangely, it’s funding tx can’t be found in an explorer. Tried to close it, but got the following error: `rpc error: code = Unknown desc = no peer for channel with chan_id=xxx`

### Your environment

* lnd 0.8.0-beta
* Raspbian Stretch
* bitcoind 0.18.1

### Expected behaviour

Channel should be open since then, or the opening attemp should have dropped.

### Actual behaviour

Channel is still listed in `pending_open_channels` when I run `lncli pendingchannels`.
Strangely, its opening transaction (5f9136aa03e82203c99d761fe9e39787301e7b9f087c2d4ef7709b3402790424) can't be found in any block explorer.

On Slack, @alexbosworth asked me to run `bitcoin-cli getrawtransaction <your_tx>`, which led to `No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions`.

**Comment by wpaulino** [comment] 2019-11-26 22:17
Did you open this channel? Is it shown in your wallet (transaction hash shows up in `lncli listchaintxns`)?

**Comment by sohomang** [comment] 2019-11-26 23:58
@wpaulino I did open it manually with a 1 sat/byte fee. But no, it doesn't show up in `lncli listchaintxns`.

**Comment by wpaulino** [comment] 2019-11-27 17:22
Do you still have the logs available during the channel open? Specifically, you should look for `Unable to broadcast funding tx`.

**Comment by sohomang** [comment] 2019-11-30 00:37
@wpaulino Couldn't find the exact line in the logs. I tried to open a few more channels to reproduce the bug, which happened again on the 4th attempt! 

```
2019-11-30 01:19:32.215 [INF] LNWL: Inserting unconfirmed transaction e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b
2019-11-30 01:19:32.242 [ERR] RPCS: [/lnrpc.Lightning/SubscribeTransactions]: rpc error: code = Internal desc = transport: connection error: desc = "transport is closing"
2019-11-30 01:19:32.242 [ERR] RPCS: [/lnrpc.Lightning/SubscribeTransactions]: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called
2019-11-30 01:19:32.242 [ERR] RPCS: [/lnrpc.Lightning/SubscribeTransactions]: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called
2019-11-30 01:19:32.242 [ERR] RPCS: [/lnrpc.Lightning/SubscribeTransactions]: rpc error: code = Internal desc = transport: connection error: desc = "transport is closing"
2019-11-30 01:19:32.242 [ERR] RPCS: [/lnrpc.Lightning/SubscribeTransactions]: rpc error: code = Internal desc = transport: connection error: desc = "transport is closing"
<same line multiple times>
2019-11-30 01:19:32.539 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0): unmatched backend error: -26: mempool min fee not met, 154 < 514 ($
2019-11-30 01:19:32.539 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0)
2019-11-30 01:19:32.543 [INF] CNCT: ChannelArbitrator(e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0): starting state=StateDefault
2019-11-30 01:19:32.544 [INF] NTFN: New block epoch subscription
2019-11-30 01:19:32.636 [INF] NTFN: New spend subscription: spend_id=20, outpoint=e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0, height_hint=605963
2019-11-30 01:19:32.697 [INF] FNDG: Finalizing pendingID(955f0bb881d5f92bab9df372451835032bdf680d0b251738ae8c326560eb963a) over ChannelPoint(e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0), , waiting for channel open on-chain
2019-11-30 01:19:32.703 [INF] NTFN: New confirmation subscription: conf_id=6, txid=e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b, num_confs=3 height_hint=605963
2019-11-30 01:19:32.706 [INF] CNCT: Close observer for ChannelPoint(e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0) active
2019-11-30 01:19:32.707 [INF] FNDG: Waiting for funding tx (e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b) to reach 3 confirmations
``` 

So, if I understand correctly, broadcasting failed but the node still tries to track it? Which makes lnd believe that the transaction is still pending. Is there a way to re-broadcast those 2 transactions?

**Comment by wpaulino** [comment] 2019-12-02 17:29
> 2019-11-30 01:19:32.539 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(e012882ede6fa388211e263b8a0a2e15c0dc5acb4dfd20734affb0879b2f580b:0): unmatched backend error: -26: mempool min fee not met, 154 < 514 ($

Looks related to https://github.com/lightningnetwork/lnd/issues/1623.

Are you running your bitcoind node with any mempool constraints?

> Is there a way to re-broadcast those 2 transactions?

If you see the funding transaction in `lncli listchaintxns`, you might be able to broadcast it through a third-party transaction push service.

**Comment by sohomang** [comment] 2019-12-02 22:55
@wpaulino Only the ones suggested by Stadicus' RaspiBolt config:
```
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000
```

Those funding transactions don't appear in `lncli listchaintxns`. My `lncli walletbalance` is back to normal though I think.

**Comment by wpaulino** [comment] 2019-12-02 23:43
> maxmempool=50

This setting restricts your mempool to only 50MB, which would be occupied by higher fee transactions. This is something we've yet to address. To prevent this going forward, you might want to either remove the option or try funding channels during low-fee periods. If you're sure the balance hasn't been deducted, you can run the `lncli abandonchannel` command, available in a debug build of `lnd` which you can obtain by running `make` and running `lnd-debug`.

Closing as duplicate of #1623.

**Closed by wpaulino** 2019-12-02 23:43 UTC
