### ISSUE TITLE
Unable to start peer: missing feature dependency: 47

### ISSUE THREAD

**Issue by begetan** [lightningnetwork/lnd#6880] opened 2022-09-02 12:03 UTC
### Background

After the upgrade from v0.15.0 to v0.15.1 several peers do not work anymore 

### Your environment

* version of `lnd` is 0.15.1-beta
* Ubuntu 20.04
* version of `bitcoind` is bitcoin-core 23.0

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

Upgrade from 0.15.0-beta to 0.15.1 with existing channels
### Expected behaviour
Peers should connect, channels should be up 

### Actual behaviour

Some peers unable to connect
```
Sep 02 13:45:31 lnd lnd[24289]: 2022-09-02 13:45:31.731 [INF] DISC: Received new remote channel announcement for 609882:1223:0
Sep 02 13:45:39 lnd lnd[24289]: 2022-09-02 13:45:39.583 [INF] SRVR: New inbound connection from 188.244.4.78:39662
Sep 02 13:45:39 lnd lnd[24289]: 2022-09-02 13:45:39.587 [INF] SRVR: Finalizing connection to 034a7b1ac1239ff2ac8438ce0a7ade1048514b77d4322f514e96918e6c13944861@188.244.4.78:39662, inbound=true
Sep 02 13:45:39 lnd lnd[24289]: 2022-09-02 13:45:39.592 [INF] PEER: Peer(034a7b1ac1239ff2ac8438ce0a7ade1048514b77d4322f514e96918e6c13944861): disconnecting 034a7b1ac1239ff2ac8438ce0a7ade1048514b77d4322f514e96918e6c13944861@188.244.4.78:39662, reason: unable to start peer: invalid remote features: missing feature dependency: 47
```

`lncli connect` to the peer gets `connection refused` error while port 9735 is open and the host responds to ping.

**Comment by sputn1ck** [comment] 2022-09-02 12:36
AFAIU it seems your peer is requiring the `scid-alias` feature bit.

Could you try running lnd with the `protocol.option-scid-alias=true` option in your `lnd.conf`, or if you run lnd manually with `--protocol.option-scid-alias`

**Comment by Crypt-iQ** [comment] 2022-09-02 17:40
https://github.com/ACINQ/eclair/blob/a735ba86b672e73005604b02dfe98c433dd74725/docs/release-notes/eclair-vnext.md#enabling-through-features

i think the peer's eclair config is wrong and didn't include option_scid_alias, you can override the init feature vector you send in eclair

**Comment by steff123** [comment] 2022-09-04 08:13
Hey, I have the same issue with the same peer after the upgrade to 0.15.1

I tested `protocol.option-scid-alias=true` but the peer is still off.

**Comment by NCrashed** [comment] 2022-09-04 10:27
> https://github.com/ACINQ/eclair/blob/a735ba86b672e73005604b02dfe98c433dd74725/docs/release-notes/eclair-vnext.md#enabling-through-features
> 
> i think the peer's eclair config is wrong and didn't include option_scid_alias, you can override the init feature vector you send in eclair

Hi, I am Eclair operator and see dozens of channels offline and 1 confirmation from other side that the issue affects me. I tried the config, but no luck. The connection with the peer is dropped on the other side immediately.

**Comment by C-Otto** [comment] 2022-09-04 17:35
Related to https://github.com/lightningnetwork/lnd/issues/6802

**Comment by begetan** [comment] 2022-09-06 13:00
@sputn1ck this option `protocol.option-scid-alias=true` doesn't help in this case

**Comment by Crypt-iQ** [comment] 2022-09-06 16:18
> > https://github.com/ACINQ/eclair/blob/a735ba86b672e73005604b02dfe98c433dd74725/docs/release-notes/eclair-vnext.md#enabling-through-features
> > i think the peer's eclair config is wrong and didn't include option_scid_alias, you can override the init feature vector you send in eclair
> 
> Hi, I am Eclair operator and I see dozens of channels offline. There is 1 confirmation from other side that the issue affects me. I tried the config, but no luck. The connection with the peer is dropped on the other side immediately.

do you mind getting a debug log containing the init message that you sent over to the peer? i think eclair can do that

**Comment by NCrashed** [comment] 2022-09-06 17:06
> > > https://github.com/ACINQ/eclair/blob/a735ba86b672e73005604b02dfe98c433dd74725/docs/release-notes/eclair-vnext.md#enabling-through-features
> > > i think the peer's eclair config is wrong and didn't include option_scid_alias, you can override the init feature vector you send in eclair
> > 
> > 
> > Hi, I am Eclair operator and I see dozens of channels offline. There is 1 confirmation from other side that the issue affects me. I tried the config, but no luck. The connection with the peer is dropped on the other side immediately.
> 
> do you mind getting a debug log containing the init message that you sent over to the peer? i think eclair can do that

Nope, Eclair doesn't do this by default. I had to patch it to print the message:
```
2022-09-06 17:02:07,924 INFO  f.a.e.io.ClientSpawner - initiating new connection to nodeId=020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 origin=Actor[akka://eclair-node/deadLetters]
2022-09-06 17:02:07,924 INFO  f.acinq.eclair.io.Client CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - connecting to 46.101.122.181:38121
2022-09-06 17:02:07,983 INFO  f.acinq.eclair.io.Client CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - connected to 46.101.122.181:38121
2022-09-06 17:02:08,048 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - connection authenticated with 020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2@46.101.122.181:38121 direction=outgoing
2022-09-06 17:02:08,048 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - using features=option_onion_messages:optional,trampoline_payment:optional,gossip_queries_ex:optional,option_data_loss_protect:optional,var_onion_optin:mandatory,option_static_remotekey:optional,option_support_large_channel:optional,option_anchors_zero_fee_htlc_tx:optional,payment_secret:mandatory,option_shutdown_anysegwit:optional,option_channel_type:optional,basic_mpp:optional,gossip_queries:optional (unknown=32973,52973)
2022-09-06 17:02:08,048 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - init message=Init(option_onion_messages:optional,trampoline_payment:optional,gossip_queries_ex:optional,option_data_loss_protect:optional,var_onion_optin:mandatory,option_static_remotekey:optional,option_support_large_channel:optional,option_anchors_zero_fee_htlc_tx:optional,payment_secret:mandatory,option_shutdown_anysegwit:optional,option_channel_type:optional,basic_mpp:optional,gossip_queries:optional (unknown=32973,52973),TlvStream(ArraySeq(Networks(List(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000))),List()))
2022-09-06 17:02:08,107 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - peer is using features=option_upfront_shutdown_script:optional,option_data_loss_protect:mandatory,var_onion_optin:optional,option_static_remotekey:mandatory,option_support_large_channel:optional,option_anchors_zero_fee_htlc_tx:optional,payment_secret:mandatory,option_shutdown_anysegwit:optional,option_channel_type:optional,basic_mpp:optional,gossip_queries:optional (unknown=31,2023), networks=
2022-09-06 17:02:08,107 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - not syncing with this peer
2022-09-06 17:02:08,107 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - rebroadcast will be delayed by 11 seconds
2022-09-06 17:02:08,107 INFO  f.a.e.i.ReconnectionTask CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - peer is connected
2022-09-06 17:02:08,108 INFO  f.a.e.c.TransportHandler CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - connection closed: PeerClosed
2022-09-06 17:02:08,108 INFO  f.a.e.c.TransportHandler CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - stopping (unackedReceived= unackedSent=None)
2022-09-06 17:02:08,108 INFO  f.a.e.io.PeerConnection CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - transport died, stopping
2022-09-06 17:02:08,109 INFO  fr.acinq.eclair.io.Peer CON n:020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 - connection lost
```

**Comment by Crypt-iQ** [comment] 2022-09-06 17:12
Is this to the OP node?

**Comment by NCrashed** [comment] 2022-09-06 17:14
That is to https://amboss.space/node/020ca6f9aaebc3c8aab77f3532112649c28a0bfb1539d0c2a42f795fb6e4c363b2 that reported to me the issue on their side.

**Comment by NCrashed** [comment] 2022-09-06 17:18
020ca6f shared the message from LND 0.15.1:
> "reason: unable to start peer: invalid remote features: missing feature dependency: 47"

**Comment by Crypt-iQ** [comment] 2022-09-06 17:24
the logs don't show the zero-conf feature bit, were you signalling or trying to open a zero-conf channel at any point to one of these nodes?

**Comment by NCrashed** [comment] 2022-09-06 17:48
> the logs don't show the zero-conf feature bit, were you signalling or trying to open a zero-conf channel at any point to one of these nodes?

I didn't try to open `zero-conf` or `option_scid_alias` (that feature is not available for public channels anyway). The issue appears on regular public channels that was opened months or even a year ago. I tried to work around via setting these features manually, but no luck. 

I checked the Eclair code and the `zero-conf` and `option_scid_alias` appeared after last stable release. I am running `0.7` release and cannot switch to `master` as I have dozen plugins that are broken by huge changes in master.

**Comment by Crypt-iQ** [comment] 2022-09-06 19:06
Ah so the problem is that eclair used to use feature bit 50/51 for trampoline_payment, which conflicts with zero-conf. So because we didn't think about this at the spec level, your older eclair node is sending the trampoline feature bit which the modern lnd node (in line with current spec) interprets as a zero-conf channel, which requires the scid-alias feature bit. Closing this since I don't see what we can do here. I think you unfortunately need to update your eclair node @NCrashed or you won't be able to open channels to lnd nodes and perhaps other impls

**Closed by Crypt-iQ** 2022-09-06 19:06 UTC
Labels: possible-bug, feature bits

**Comment by NCrashed** [comment] 2022-09-07 02:03
I found workaround, thanks to @Crypt-iQ for pointing out the trampoline bits. Eclair operators should disable the feature via the config:
```
eclair.trampoline-payments-enable=false
```
