### ISSUE TITLE
Slow down channel.db growth (and add documentation)

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5938] opened 2021-11-06 10:10 UTC
### Background

Related: #5705 #3703

My channel.db is 9 GByte after compaction. I run 0.14.0-beta.rc2 which, I think, includes #4364. The DB grows with roughly 1 GByte/week, which is something I cannot sustain over the long term.

Please advise on how I can shrink the database, add documentation, and possibly explain why that much information has to be retained.

Compaction is enabled. "gc-canceled-invoices-on-startup" and "-on-the-fly" are enabled.

The node is c-otto.de which has around 240 active channels and around 580 closed channels. It handles over 1,000 fwds/day in addition to a few hundred rebalance transactions per day.

Sum of channel updates:
```
lncli listchannels | grep num_updates|cut -f 2 -d ":"|cut -f 2 -d "\""|datamash sum 1
3918516
```
 
### Your environment

* 0.14.0-beta.rc2
* Linux server 5.10.0-8-amd64 #​1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

**Comment by Roasbeef** [comment] 2021-11-06 22:11
Closing this as an duplicate of #3703 and https://github.com/lightningnetwork/lnd/issues/5388 which are both on the milestone for 0.15. 

You can reach our to the dev community on slack or perhaps use the Discussion feature on here if you'd like to collect information on how other developers manage their state. 

AFAICT, large DB growth is caused mainly by proactive automated/manual rebalancing. These generates a ton of failed payments and attempts, which sit around until the channel is closed. You can use `DeletePayments` (see the args here, you prob just want to delete the failed payments, since rebalancing can generate a lot of them) to reclaim some of that space.

**Closed by Roasbeef** 2021-11-06 22:11 UTC
