### ISSUE TITLE
Openchannel unpredictable

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2113] opened 2018-10-28 19:19 UTC
### Background
From the start of my iOS project one of the areas i have had consistent difficulty is opening channels. Because my iOS app and neutrino are paired with a simnet blockchain, i am able to control when and how blocks are mined and often times I mine blocks immediately upon request to open channel. Most times within 6-8 confirmations, the channel is opened (usually takes up to 3 minutes).
Sometimes (like yesterday), i had connected with a remote node over ipV4. The remote was on a slower network. My node and the remote had paired (peered) properly , no problem there.
Attempt to open a channel however had problems repeatedly. Following sequences occurred
1) Attempt to open channel first time
2) Channel opening was RPC unary/asynchronous, meaning a completion block was provided.
3) The completion block was not called for a good 10 minutes as the process to open channel worked its way thru the timeout period. Its as if the process had difficulty staying connected with remote long enough to open channel (in other words behaved like the signal was spotty - i don't think the signal was spotty). It waited for timeout. 
4) Because there was no timely feedback , i tried to open channel again, and again (about 3-4 times)
5) Slowly but surely, i started to receive feedback such as "Number of pending channels exceed maximum", "Deadline exceeded" etc. but never "peer not connected" (because peers remained connected)
6) Meanwhile one of the attempts to open a channel appears to have succeeded, and suddenly i started to receive notification regarding channel open confirmations
7) If this workflow were to be true in real production situation, it is conceivable folks (mobile users) won't know the status of the process, and will hang up the app. End result, no channel will be opened, and no Lightning related payments could be made.

How can we make this process better such that an async completion block is notified immediately, regardless of the timeout , so the app is able to take corrective action 
What causes the channel opening process to be unpredictable ? What can LND clients do to make this less painful?

I am sure i will encounter this again, and i will collect a trace when this happens. But for now i don't have much in the way of logs. 

### Your environment

* version of `lnd`  - 0.5 x commit -> 1b0d8e8f13359d361cd957d2a18bf8d2801c6c86
* which operating system (`uname -a` on *Nix)  --- iOS
* version of `btcd`, `bitcoind`, or other backend ---btcd

### Expected behaviour

Predictable workflow. Immediate feedback by channel open workflow so that completion blocks can take corrective action.

### Actual behaviour

Random delays. Takes up to 10 minutes to learn of channel open failure.

**Comment by weaklysubjective** [comment] 2018-10-28 19:40
Forgot to add - can the channel opening process be handed off to a watch tower on behalf of mobile clients ? Additionally can this process be done offline (even one or both nodes are offline )? Even if both nodes are offline thru' the confirmation process, can an android or ios client receive some notification from a watch tower when their channel id is ready ?

**Comment by halseth** [comment] 2018-10-29 09:28
Hi, thanks for the report and suggestions! 

The issue is a bit unspecific so cannot take immediate action. Also we are not yet supporting mobile builds, so will close this for now.

@weaklysubjective Regarding your last questions; no watchtowers in their current design won't assist in the opening of a channel.

**Closed by halseth** 2018-10-29 09:28 UTC

**Comment by Roasbeef** [comment] 2018-10-29 21:28
> Most times within 6-8 confirmations, the channel is opened (usually takes up to 3 minutes).
We scale the # of confirmations required based on the size of the channel. Larger channels require more confirmations.

**Comment by Roasbeef** [comment] 2018-10-29 21:29
Hard to act on this without any logs or additional context. It may be something device specific as well, as if lnd goes into the background, then it's possible that we lose our TCP connection to the remote peer and need to reestablish it.

**Comment by weaklysubjective** [comment] 2018-10-29 22:08
Hi Guys, Once again great help from you both and extremely useful comments. I did not know confirmations are scaled and always wondered why at times 6 conf wasn't enough ! 

As expected it happened again - started with an open channel request ending in "deadline exceeded" ,I went ahead and turned on trace and collected a bunch. I will get all the trace together and provide a link here. 

Will be back shortly

**Comment by weaklysubjective** [comment] 2018-10-29 22:46
As promised here is a trace of the session approx. 20 minutes in duration where it went from being unable to open channel to successfully opening channel and making payments 

https://0bin.net/paste/SB5lIi-Ccqtgsl3W#VgyT0BbqBguTZ6e2XnBFGyngwlLEp00DiIeK8kmHZ0c

**Comment by weaklysubjective** [comment] 2018-10-29 22:54
From openchannel async response  i was able to glean the reason for failure to open channel as --> 
https://0bin.net/paste/R0rInJoUUKckJZMV#Rf0ZDKo0rcS7yVkOfQaYtC4T73rLv8A-6UJyoN8poLw

====================================================
Node B info before opening channel
-------------------------------------
https://0bin.net/paste/Jerj9wJbYn8dkQ6M#1TqTXe3QT2-/+XHR0U0HXKwG77uOIFfwy3KrAfUny4Z

====================================================
Node A getinfo AFTER second channel opened
-----------------------------------------------
https://0bin.net/paste/tbiv++8FGTuA-mka#xjzpabMbsJkNWfsSsjHSfGqwSOfNppGYbFTrS8H4Hel

**Comment by Roasbeef** [comment] 2018-10-31 03:00
From these logs, I would double check how you're using gRPC and the notifications that come laong with it.

**Comment by weaklysubjective** [comment] 2018-11-02 23:45
Hi roasbeef, i am unable to confirm this because i can't remember the exact situation , but i have a feeling the IP address changed, from WIFI to LTE. It is entirely possible the peer was still trying to connect / open channel at the time. 
I tested this scenario and i can confirm that abruptly changing the IP causes some issues such as payments to go into transition, future channels not opening etc. I observed this for sure.
After many frustrating attempts to open channel, i deleted the app and reinstalled. It caught up , fully syncd and all was well thereafter. The blockchain was still the same height.

However when i did this , it led me to **another issue.**..please bear with me as i mix up these issues.
_Having deleted the app i was hoping to recover my wallet (which would naturally be deleted in iOS when the app is deleted). I supplied what i knew was the previous 24 words mnemonic, and the previous wallet password . It calls 'initWallet' and goes about doing whatever it is supposed to be doing and the call itself is successful, i am guessing the wallet was initialized with the prior state. 

However the balance (confirmed and unconfirmed ) are both zero.  
I am surely missing something here...much appreciate any feedback._
