### ISSUE TITLE
Crash in logging from bitcoind.go when historicalSpendDetails does not find a spend request

### ISSUE THREAD

**Issue by remyers** [lightningnetwork/lnd#4711] opened 2020-10-22 08:53 UTC
### Background

When LND starts up, `notificationDispatcher` calls `historicalSpendDetails`. This call returns (`err`=nil, `spendDetails`=nil) when the `msg.SpendRequest` is not found. Because the `err` return value is nil, it tries to create a log entry showing the `spendDetails`, which is also nil. This causes a segfault in a printf of logging.

### Your environment

* lnd-debug version 0.11.0-beta.rc4 commit=v0.11.0-beta.rc4-7-gfa612fa671ffb22686701f624b14adbef9ebf629-dirty
* Darwin macbook-pro-6.lan 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
* Bitcoin Core Daemon version v0.17.1
* I am testing with a bitcoind regtest configuration for debugging; perhaps I killed lnd-debug from the debugger a few times and messed up a database?

### Steps to reproduce

Stack trace to [L278](https://github.com/lightningnetwork/lnd/blob/d12f76fd6d48f5d4df8d830b5ec49e9277ffa5c0/chainntnfs/bitcoindnotify/bitcoind.go#L278) of bitcoind.go
github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).notificationDispatcher.func2 (/Users/richard/VSCode/go/lnd/chainntnfs/bitcoindnotify/bitcoind.go:278)
runtime.goexit (/usr/local/go/src/runtime/asm_amd64.s:1374)

Notice that if both `spendDetails` and `err` are nil, this line will be reached and cause a crash. Happy to provide more repo details, but it seems like the logic is flawed.

### Expected behaviour

If the `SpendRequest` is not found by `historicalSpendDetails` it should not return nil, nil. Perhaps set `err` so that `spendDetails` are not accessed during logging.

### Actual behaviour

This code crashes and `lnd` falls over.

**Comment by Crypt-iQ** [comment] 2020-10-22 11:58
@wpaulino

**Comment by remyers** [comment] 2020-10-22 12:26
If I replace [L808](https://github.com/lightningnetwork/lnd/blob/d12f76fd6d48f5d4df8d830b5ec49e9277ffa5c0/chainntnfs/bitcoindnotify/bitcoind.go#L808) with:

`return nil, errors.New("not found")`

Then no crash and the logged output looks like this instead:

```
2020-10-22 14:15:51.331 [ERR] NTFN: Rescan to determine the spend details of outpoint=1efaf4405a662340db6f5108ec762978cf7f12bd6ff10aa323be5f321459a442:1, script=0 0793ca0b513b7fb6f5130000c3cf4a95b3984dd7d96d0629fe8c7a657030d27a within range 1179-1179 failed: not found
```

**Comment by wpaulino** [comment] 2020-10-22 19:12
The issue isn't with it returning `nil, nil`, that's the expected behavior in certain cases and we don't want to return an error. Instead, we just need to either modify the log statement to not include the spend details or modify `SpendDetail.String` to return a different message when it is nil.

**Comment by remyers** [comment] 2020-10-22 21:07
Would something like this [change](https://github.com/lightningnetwork/lnd/commit/4bc154c9b65481ba526c8c2816a1c6baa389b49a) make sense? 

It looks like it should fall through and not return like an error does if no spend details are found.

**Comment by wpaulino** [comment] 2020-10-22 21:32
Yeah something like that would work @remyers. The main thing is that `UpdateSpendDetails` should be called even with a nil `spendDetails`, as that will allow the `TxNotifier` to begin tracking the spend at tip.

**Comment by wpaulino** [comment] 2021-03-05 01:43
Closing as this doesn't seem to be an issue present when running the tests that exercise this behavior with logging enabled. The logger seems to handle the nil spend details correctly and outputs them as `<nil>`.

**Closed by wpaulino** 2021-03-05 01:43 UTC
Labels: P1, beginner, bug, chain handling, notifications
