### ISSUE TITLE
Can't connect to online node, channels down

### ISSUE THREAD

**Issue by svewa** [lightningnetwork/lnd#4941] opened 2021-01-21 22:36 UTC
I'm running lnd v0.12.0-beta.rc6.
This certainly was an issue on rc5
I don't think it was an issue before, but hard to verify now.

I have 2 channels with mainnet.lightningconductor.net  03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@mainnet.lightningconductor.net:9735
Both channels are down, I can't connect the node.

loglevel warn with RPCS=debug,HSWC=debug: I use RTL to connect to the node via full id@host:port

> 2021-01-21 22:28:14.282 [DBG] RPCS: [connectpeer] requested connection to 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735
> 2021-01-21 22:28:14.282 [WRN] SRVR: Already have 1 persistent connection requests for 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735, connecting anyway.
> 2021-01-21 22:28:15.323 [DBG] RPCS: Connected to peer: 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735
> 2021-01-21 22:28:15.338 [WRN] RPCS: Gossip syncer for peer=03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601 not found
> 2021-01-21 22:28:15.339 [DBG] RPCS: [listpeers] yielded [02607c9c92b7fa405dd27d8114d5ba1e6c04bf8757bef18b3649bffa2691d7638c@127.0.0.1:50328 03fa11149d584265f1356870f2a674f4b04fff5d2c39991c35dbea3b76af614f66@127.0.0.1:36126 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735 021ec9dcb5db6b31433ad864b64d278a556d56576673db889cb05099d57c01988b@193.30.121.100:9735 0307eafebbf6583eaf3dce69181018185b193414901c029e98062455e328c76bf3@127.0.0.1:51708 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735 02b0172bb38617fa3afdb69664468b492d5a21062a4fa8b47284b0cc320e6e7420@127.0.0.1:50228 03d8689ad07363524d4013d5fd4b0c0af1b212f65495be51fb43ef1b42404b5de4@127.0.0.1:39272] peers
> 2021-01-21 22:28:15.911 [INF] HSWC: Removing channel link with ChannelID(56a6b1fd3791b5cb86501b718299c5aaef1ebc0ad6188a2f5d42e627b5b76df9)
> 2021-01-21 22:28:15.911 [INF] HSWC: ChannelLink(652702:2197:1): starting
> 2021-01-21 22:28:15.911 [INF] HSWC: Trimming open circuits for chan_id=652702:2197:1, start_htlc_id=210
> 2021-01-21 22:28:15.911 [INF] HSWC: Adding live link chan_id=56a6b1fd3791b5cb86501b718299c5aaef1ebc0ad6188a2f5d42e627b5b76df9, short_chan_id=652702:2197:1
> 2021-01-21 22:28:15.912 [INF] HSWC: ChannelLink(652702:2197:1): HTLC manager started, bandwidth=3171223317 mSAT
> 2021-01-21 22:28:15.914 [INF] HSWC: ChannelLink(652702:2197:1): attempting to re-resynchronize
> 2021-01-21 22:28:15.919 [INF] HSWC: Removing channel link with ChannelID(f439d3e8dc2d323729e6c9538d02f16c9345cd548159f009138dd69140ed2034)
> 2021-01-21 22:28:15.919 [INF] HSWC: ChannelLink(652705:947:1): starting
> 2021-01-21 22:28:15.920 [INF] HSWC: Trimming open circuits for chan_id=652705:947:1, start_htlc_id=0
> 2021-01-21 22:28:15.920 [INF] HSWC: Adding live link chan_id=f439d3e8dc2d323729e6c9538d02f16c9345cd548159f009138dd69140ed2034, short_chan_id=652705:947:1
> 2021-01-21 22:28:15.920 [INF] HSWC: ChannelLink(652705:947:1): HTLC manager started, bandwidth=94750000 mSAT
> 2021-01-21 22:28:15.921 [INF] HSWC: ChannelLink(652705:947:1): attempting to re-resynchronize
> 2021-01-21 22:28:15.921 [WRN] HSWC: ChannelLink(652702:2197:1): error when syncing channel states: unable to send chan sync message for ChannelPoint(f86db7b527e6425d2f8a18d60abc1eefaac59982711b5086cbb59137fdb1a656:1): peer exiting
> 2021-01-21 22:28:15.923 [ERR] HSWC: ChannelLink(652702:2197:1): failing link: unable to synchronize channel states: unable to send chan sync message for ChannelPoint(f86db7b527e6425d2f8a18d60abc1eefaac59982711b5086cbb59137fdb1a656:1): peer exiting with error: unable to resume channel, recovery required
> 2021-01-21 22:28:15.923 [INF] HSWC: ChannelLink(652702:2197:1): exited
> 2021-01-21 22:28:16.013 [WRN] HSWC: ChannelLink(652705:947:1): error when syncing channel states: unable to send chan sync message for ChannelPoint(3520ed4091d68d1309f0598154cd45936cf1028d53c9e62937322ddce8d339f4:1): peer exiting
> 2021-01-21 22:28:16.015 [ERR] HSWC: ChannelLink(652705:947:1): failing link: unable to synchronize channel states: unable to send chan sync message for ChannelPoint(3520ed4091d68d1309f0598154cd45936cf1028d53c9e62937322ddce8d339f4:1): peer exiting with error: unable to resume channel, recovery required
> 2021-01-21 22:28:16.015 [INF] HSWC: ChannelLink(652705:947:1): exited
> 2021-01-21 22:28:16.127 [INF] HSWC: Removing channel link with ChannelID(56a6b1fd3791b5cb86501b718299c5aaef1ebc0ad6188a2f5d42e627b5b76df9)
> 2021-01-21 22:28:16.127 [INF] HSWC: ChannelLink(652702:2197:1): stopping
> 2021-01-21 22:28:16.127 [INF] HSWC: Removing channel link with ChannelID(f439d3e8dc2d323729e6c9538d02f16c9345cd548159f009138dd69140ed2034)
> 2021-01-21 22:28:16.127 [INF] HSWC: ChannelLink(652705:947:1): stopping
> 2021-01-21 22:28:18.840 [DBG] HSWC: Sent 0 satoshis and received 0 satoshis in the last 10 seconds (0.100000 tx/sec)
> 

If I connect form an c-lightning instance, the connection gets established:

> ln@c-lightning:$ lightning-cli listpeers 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
> {
>    "peers": []
> }
> ln@c-lightning:$ lightning-cli connect 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
> {
>    "id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
>    "features": "082a8a"
> }
> ln@c-lightning:$ lightning-cli listpeers 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
> {
>    "peers": [
>       {
>          "id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
>          "connected": true,
>          "netaddr": [
>             "18.191.89.219:9735"
>          ],
>          "features": "082a8a",
>          "channels": []
>       }
>    ]
> }
> 

If i connect to the host port via telnet, it works (connect is instant, discon after ~10s). This is from the host and user running LND:

> lnd@lnd:~$ time telnet 18.191.89.219 9735
> Trying 18.191.89.219...
> Connected to 18.191.89.219.
> Escape character is '^]'.
> Connection closed by foreign host.
> 
> real	0m10.404s
> user	0m0.000s
> sys	0m0.004s

Default-gateway forces tor, but anyway:
> lnd@lnd:~$ time torify telnet 18.191.89.219 9735
> Trying 18.191.89.219...
> Connected to 18.191.89.219.
> Escape character is '^]'.
> Connection closed by foreign host.
> 
> real	0m10.805s
> user	0m0.014s
> sys	0m0.003s

I have a feeling I can't connect to any nodes, but then again I have like 5 channels UP, so some are certainly working.

**Comment by Roasbeef** [comment] 2021-01-21 22:48
Very odd, if I connect I also get an instant hang up (don't have any channels with them). For your c-lightning node, are you able to see the type of `init` message the peer sends over in the logs?

**Comment by Roasbeef** [comment] 2021-01-21 22:58
Ok I was able to check out the features offered, I don't see any incompatible set of feature bits (stuff that we require, but they don't yet understand), so not sure what's going on here still...

**Comment by svewa** [comment] 2021-01-21 23:03
Not sure if you still need the connect info from c-lightning, here is level debug the stuff that seems relevant, level io gets a bit verbose and hard for me to filte for relevant stuff.



```
 {
         "type": "DEBUG",
         "time": "710168.261570004",
         "source": "connectd",
         "log": "Now try LN connect out for host 18.191.89.219"
      },
      {
         "type": "DEBUG",
         "time": "710168.261635553",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "connectd",
         "log": "Connected out, starting crypto"
      },
      {
         "type": "DEBUG",
         "time": "710168.466641504",
         "source": "hsmd",
         "log": "Client: Received message 1 from client"
      },
      {
         "type": "DEBUG",
         "time": "710168.466936088",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "connectd",
         "log": "Connect OUT"
      },
      {
         "type": "DEBUG",
         "time": "710168.467011065",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "connectd",
         "log": "peer_out WIRE_INIT"
      },
      {
         "type": "DEBUG",
         "time": "710168.671076010",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "gossipd",
         "log": "seeker: disabling gossip"
      },
      {
         "type": "DEBUG",
         "time": "710168.671195267",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "connectd",
         "log": "peer_in WIRE_INIT"
      },
      {
         "type": "DEBUG",
         "time": "710168.677740603",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "openingd-chan#21621",
         "log": "pid 21821, msgfd 62"
      },
      {
         "type": "DEBUG",
         "time": "710168.680339460",
         "source": "hsmd",
         "log": "Client: Received message 10 from client"
      },
      {
         "type": "DEBUG",
         "time": "710168.680503326",
         "source": "hsmd",
         "log": "Client: Received message 9 from client"
      },
      {
         "type": "DEBUG",
         "time": "710168.680567256",
         "source": "hsmd",
         "log": "new_client: 21621"
      },
      {
         "type": "DEBUG",
         "time": "710168.710979688",
         "source": "hsmd",
         "log": "Client: Received message 18 from client"
      },
      {
         "type": "DEBUG",
         "time": "710168.711107480",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "openingd-chan#21621",
         "log": "Handed peer, entering loop"
      },
      {
         "type": "DEBUG",
         "time": "710168.721546113",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "openingd-chan#21621",
         "log": "peer_in WIRE_GOSSIP_TIMESTAMP_FILTER"
      },
      {
         "type": "DEBUG",
         "time": "710168.721623775",
         "node_id": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
         "source": "openingd-chan#21621",
         "log": "peer_out WIRE_GOSSIP_TIMESTAMP_FILTER"
      },

```

**Comment by Roasbeef** [comment] 2021-01-21 23:27
So as far as we can tell, this is an eclair node. I'm able to connect to the main ACINQ node from mine, but still get an instant hang up from this node 🤔

**Comment by svewa** [comment] 2021-01-22 00:00
I contacted the node operator via their ticket system, maybe they can give some insight.

**Comment by Dikay900** [comment] 2021-01-23 19:36
got the same problem for some peers with 0.12.0-rc6 as well as i got them on rc5 already.
See #4947 which is probably referring the same problem since i cannot to connect to both peers mentioned here and on the other issue.

**Comment by svewa** [comment] 2021-01-23 20:01
might be related. just tried to open a channel to fulmo:
lnd@lnd:~$ lncli  connect 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735
2021-01-23 19:59:39.916 [DBG] RPCS: [connectpeer] requested connection to 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735
2021-01-23 19:59:40.696 [DBG] RPCS: Connected to peer: 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735
{

}
lnd@lnd:~$ 2021-01-23 19:59:48.060 [DBG] RPCS: [openchannel] request to NodeKey() allocation(us=1172037, them=0)
2021-01-23 19:59:48.467 [DBG] RPCS: [openchannel]: using fee of 16255 sat/kw for funding tx
2021-01-23 19:59:48.467 [ERR] RPCS: unable to open channel to NodeKey(024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365): peer 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365 is not online
2021-01-23 19:59:48.470 [ERR] RPCS: [/lnrpc.Lightning/OpenChannelSync]: peer 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365 is not online

**Comment by Dikay900** [comment] 2021-01-23 20:15
my side when connecting to fulmo:

```
2021-01-23 20:10:50.583 [WRN] SRVR: Already have 1 persistent connection requests for 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735, connecting anyway.
2021-01-23 20:10:50.898 [INF] SRVR: Established connection to: 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735
2021-01-23 20:10:50.899 [INF] SRVR: Finalizing connection to 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735, inbound=false
2021-01-23 20:10:50.902 [INF] PEER: Legacy channel open with peer: 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365, downgrading static remote required feature bit to optional
2021-01-23 20:10:51.066 [INF] PEER: NodeKey(024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365) loading ChannelPoint(******:0)
2021-01-23 20:10:51.066 [INF] HSWC: Removing channel link with ChannelID(******)
2021-01-23 20:10:51.066 [INF] HSWC: ChannelLink(643***:948:0): starting
2021-01-23 20:10:51.067 [INF] HSWC: Trimming open circuits for chan_id=643***:948:0, start_htlc_id=960
2021-01-23 20:10:51.067 [INF] HSWC: Adding live link chan_id=*******, short_chan_id=643***:948:0
2021-01-23 20:10:51.067 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(*******:0)
2021-01-23 20:10:51.067 [INF] PEER: Negotiated chan series queries with 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365
2021-01-23 20:10:51.068 [INF] DISC: Creating new GossipSyncer for peer=024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365
2021-01-23 20:10:51.068 [INF] HSWC: ChannelLink(643786:948:0): HTLC manager started, bandwidth=******** mSAT
2021-01-23 20:10:51.068 [INF] HSWC: ChannelLink(643786:948:0): attempting to re-resynchronize
2021-01-23 20:10:51.209 [INF] PEER: unable to read message from 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735: EOF
2021-01-23 20:10:51.210 [INF] PEER: disconnecting 024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365@95.211.207.81:9735, reason: read handler closed
2021-01-23 20:10:51.311 [INF] DISC: Removing GossipSyncer for peer=024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365
2021-01-23 20:10:51.311 [INF] HSWC: Removing channel link with ChannelID(**********)
2021-01-23 20:10:51.311 [INF] HSWC: ChannelLink(643***:948:0): stopping
2021-01-23 20:10:51.311 [WRN] HSWC: ChannelLink(643***:948:0): error when syncing channel states: link shutting down
2021-01-23 20:10:51.311 [INF] HSWC: ChannelLink(643***:948:0): exited
```

**Comment by svewa** [comment] 2021-01-23 21:06
fulmo is on c-lightning but not latest version he told me. So it might be another issue than the one with eclair I opened the issue for. But then again, might be the same cause.

**Comment by Roasbeef** [comment] 2021-01-27 03:55
I tried to connect to the Fulmo node and it failed as well @svewa. Looking at the set of feature bits returned, the node is indeed very old as it doesn't even _know_ about the "static remote key" channels, which we now require for safety purposes.

**Comment by svewa** [comment] 2021-01-27 10:43
fulmo is updating, should be resolved shortly I hope. Would be nice if LND would slowly deprecate peers like that, like first display a warning that features are missing and support for this peer will be dropped in future versions, to allow cooperative closing before upgrades. or maybe existing channels can still be operated, but no new ones created, I don't know the security implications of this feature. Also a lot of work for peers who don't update :/

Anyway, it seems the fulmo issue was not connected to my problem as features of my acinq peer seem to be OK.

**Comment by bmml1** [comment] 2021-02-25 21:23
Hi! I might have the same problem with this node(ZAP Technologies). Can anyone confirm?
03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735

**Comment by Roasbeef** [comment] 2021-03-05 00:33
Closing this issue as the root cause have been diagnosed: there exist nodes with extremely outdated software that haven't kept up with lnd's commitment to advertising safe defaults for the protocol.

**Closed by Roasbeef** 2021-03-05 00:33 UTC
Labels: feature bits, interop, p2p

**Comment by downet** [comment] 2021-03-07 22:32
Hi,

we are trying to solve actually in Umbrel, where we got also errors about channel down.

Found this error in LND log:
```
2021-03-07 14:18:51.189 [INF] PEER: unable to read message from 02e12a35304184cc4c6b9d3a85f3c5d9262403c335e2b01c4b6ed18cd838709c46@rbrg5j6zslb42n4xgkwh3gb2h2thzsw2xt77alh5mvosbysdvqbcivad.onion:9735: EOF
2021-03-07 14:18:51.189 [INF] PEER: disconnecting 02e12a35304184cc4c6b9d3a85f3c5d9262403c335e2b01c4b6ed18cd838709c46@rbrg5j6zslb42n4xgkwh3gb2h2thzsw2xt77alh5mvosbysdvqbcivad.onion:9735, reason: read handler closed
2021-03-07 14:18:51.290 [INF] DISC: Removing GossipSyncer for peer=02e12a35304184cc4c6b9d3a85f3c5d9262403c335e2b01c4b6ed18cd838709c46
```

But I was asking the guy who is running that node and it´s myNode with latest LND 12.1 .. Umbrel has lnd:v0.12.1 as well. Any ideas? :-)

Peer is connected, but channel is down.

**Comment by downet** [comment] 2021-03-15 18:55
@Roasbeef sorry to ping you.. can you reopen the issue or should I create new one for this?

**Comment by Overtorment** [comment] 2021-03-15 19:04
having same issues

**Comment by wpaulino** [comment] 2021-03-15 20:56
> But I was asking the guy who is running that node and it´s myNode with latest LND 12.1 .. Umbrel has lnd:v0.12.1 as well. Any ideas? :-)

@downet maybe open a new issue as the original was between c-lightning and lnd and your case seems different. Could you also reach out to them again and ask if they see any reasons on their side for the channels not being active/peer disconnecting?
