### ISSUE TITLE
LND crashed after 3 weeks of running with "fatal error: runtime: out of memory"

### ISSUE THREAD

**Issue by darklow** [lightningnetwork/lnd#2763] opened 2019-03-12 16:58 UTC
### Background

LND crashed after 3 weeks of running with "fatal error: runtime: out of memory"
Usually uses around 10-15% of RAM (1GB RAM total)
Possibly related to #2658 

### Your environment

lnd: v0.5.2-beta (mainnet)
backend: bitcoind v0.17.1

Using docker (FROM debian:stretch-slim):
Linux 7f70ec6fb7d9 4.4.0-1075-aws #85-Ubuntu SMP Thu Jan 17 17:15:12 UTC 2019 x86_64 GNU/Linux

### Steps to reproduce

Log file with moment of crash (and some multiple lines before)
[lnd-crash.log](https://github.com/lightningnetwork/lnd/files/2957938/lnd-crash.log)

**Comment by wpaulino** [comment] 2019-03-12 19:09
This is likely due to the massive increase of the mainnet channel graph. We are aware of the issue. Closing as duplicate of #2658.

**Closed by wpaulino** 2019-03-12 19:09 UTC
