### ISSUE TITLE
Wrong macaroonpath in the developer tutorial.

### ISSUE THREAD

**Issue by daniel-vera-g** [lightningnetwork/lnd#1891] opened 2018-09-12 15:23 UTC
### Background

In the developer tutorial on <https://dev.lightning.community/tutorial/01-lncli/index.html> in the section `Working with lncli and authentication`, the command to create and get info of a wallet has the wrong macaroon path. It has the path `--macaroonpath=data/admin.macaroon` instead of the right path: `--macaroonpath=data/chain/bitcoin/simnet/admin.macaroon`:

### Your environment

* version of `lnd`: 0.5.0 beta
* which operating system (`uname -a` on *Nix): Ubuntu
* version of `btcd`, `bitcoind`, or other backend: 0.12.0 beta

### Steps to reproduce

* Follow the tutorial on <https://dev.lightning.community/tutorial/01-lncli/index.html>. In detail the commands:
* `lncli --rpcserver=localhost:10001 --macaroonpath=data/admin.macaroon create`
* `lncli --rpcserver=localhost:10001 --macaroonpath=data/admin.macaroon getinfo`

### Expected behaviour

1. Create Wallet
2. Get information about the lightning connection.

### Actual behaviour

`[lncli] unable to read macaroon path (check the network setting!): open data/admin.macaroon: no such file or directory`

**Comment by ccdle12** [comment] 2018-09-13 12:49
Thought this might be useful to post here as well, as this was a post on `dev-help` slack channel about this issue.

I had the same issue, I hadn’t touch the simnet setup for a while and recently, after pulling from master I had run into a similar issue. 

Previously I had copied ```admin.macaroon``` from ```Library/Application Support/Lnd/data``` to
```go/dev/alice/data``` and that used to work for me.

So at the moment I’m running lnd and lncli with ```--no-macaroons``` and that’s working at the moment.

**Comment by daniel-vera-g** [comment] 2018-09-13 15:15
Have found the tutorials repository here

https://github.com/lightninglabs/lightning-dev-site/blob/master/tutorial/01-lncli.md

Will make a PR to the issue & if it gets fixed there I think that this issue can be closed.

**Comment by wpaulino** [comment] 2018-09-13 20:31
Closing as the issue is now being tracked in the correct repository.

**Closed by wpaulino** 2018-09-13 20:31 UTC
