### ISSUE TITLE
Openchannel FAKE, or spend all to channel opening

### ISSUE THREAD

**Issue by sako0938** [lightningnetwork/lnd#3446] opened 2019-08-31 18:51 UTC
### Background

When trying to empty my walletbalance and put it in a channel, I have to go through a bit of a tedious procedure to make sure I don't get left with dust. I always openchannels using the --sat_per_byte flag, as that is what is important to me. If I want confirmations faster or slower I'll check mempool.space to tell me which fee-rate to use.

### Your environment

* version of `lnd`
lnd 0.7.1beta
* which operating system (`uname -a` on *Nix)
Odroid XU4, bitcoind, Linux
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

1. Get walletbalance: ```lncli walletbalance```, get confirmed balance: 100,000 sats.
2. Open channel with full balance: ```lncli openchannel {pubkey} --connect={ip} --local_amt=100000 --sat_per_byte=4 ``` Specify feerate because I am cheap, but I dont want to wait all week for it to confirm.
3. Get error message: ```[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.00101000 BTC only have 0.00100000 BTC  available```
4. Using the error message calculate the fee lnd is going to use: ```0.00101000 BTC-0.00100000 BTC = 1000 sat```
5. Calculate new local_amt to make it work: ``` 0.00100000 BTC - 1000 sat  = 99000 sat```
6. Retry channel opening with new local_amt: ```lncli openchannel {pubkey} --connect={ip} --local_amt=99000 --sat_per_byte=4```
7. Success: 
``` lncli walletbalance
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0"
}
```

### Expected behaviour

Sweep All?
```lncli openchannel {pubkey} --connect={ip} --sweep_all_local --sat_per_byte=4```

FAKE?
```lncli openchannel {pubkey} --connect={ip} --local_amt=100000 --sat_per_byte=4 --fake```
Show whether the channel opening could be valid, and if not show max local_amt for given fee rate. 

What do you think?

**Comment by wpaulino** [comment] 2019-09-02 20:57
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/619.

**Closed by wpaulino** 2019-09-02 20:57 UTC
