### ISSUE TITLE
locked_balance 

### ISSUE THREAD

**Issue by Bit2Cash** [lightningnetwork/lnd#6947] opened 2022-09-26 21:42 UTC
### Background
I am running a BTCPayServer instance installed with docker on VPS and it was doing ok until I sent some BTC to the node wallet and balance is not showing as confirmed although it's been confirmed many blocks ago. 
I wasn't sure if posting this at BTCPayServer but it doesn't look related to them. 

### Your environment
* version of lnd: 0.15.0-beta commit=basedon-v0.15.0-beta-fresh-btcpay
* which operating system: Ubuntu 20.04.3 LTS
* version of bitcoind: Bitcoin Core v22.0.0
* BTCPayServer on latest version 1.6.10

### Steps to reproduce
When I run lncli walletbalance I get the following 
```
{
    "total_balance": "4039516",
    "confirmed_balance": "4039516",
    "unconfirmed_balance": "0",
    "locked_balance": "Here is the amount of transaction already with 450 confirmations",
    "account_balance": {
        "default": {
            "confirmed_balance": "4039516",
            "unconfirmed_balance": "0"
        }
    }
}
```

### Expected behaviour
lncli walletbalance should show the total_balance with latest transaction included. 

### Actual behaviour
The amount of the last transaction sent to node wallet is shown as "locked_balance"

**Comment by ellemouton** [comment] 2022-09-27 07:00
Hi @Bit2Cash , so just to clarify - `locked_balance` does not mean that the amount is not confirmed. It is instead the total amount of utxos that are being held for other uses.

So my question to you would be: were you by any chance in the middle of a psbt funding flow?

**Comment by Bit2Cash** [comment] 2022-09-27 15:00
Hi, 
When transaction had a confirmation, I started to open a dual funded channel via bos, but the other node didn'respond, so I guess something was pending but I don't see how to unlock it. I will check with bos operators now.

**Comment by Roasbeef** [comment] 2022-09-28 02:35
So the locked coins unlock automatically after 10 minutes. I think we can close this now since the funding attempt failed, but the script didn't unlock the coins automatically.

**Closed by Roasbeef** 2022-09-28 02:35 UTC

**Comment by Bladez1753** [comment] 2022-10-01 07:06
> ### Background
> I am running a BTCPayServer instance installed with docker on VPS and it was doing ok until I sent some BTC to the node wallet and balance is not showing as confirmed although it's been confirmed many blocks ago. I wasn't sure if posting this at BTCPayServer but it doesn't look related to them.
> 
> ### Your environment
> * version of lnd: 0.15.0-beta commit=basedon-v0.15.0-beta-fresh-btcpay
> * which operating system: Ubuntu 20.04.3 LTS
> * version of bitcoind: Bitcoin Core v22.0.0
> * BTCPayServer on latest version 1.6.10
> 
> ### Steps to reproduce
> When I run lncli walletbalance I get the following
> 
> ```
> {
>     "total_balance": "4039516",
>     "confirmed_balance": "4039516",
>     "unconfirmed_balance": "0",
>     "locked_balance": "Here is the amount of transaction already with 450 confirmations",
>     "account_balance": {
>         "default": {
>             "confirmed_balance": "4039516",
>             "unconfirmed_balance": "0"
>         }
>     }
> }
> ```
> 
> ### Expected behaviour
> lncli walletbalance should show the total_balance with latest transaction included.
> 
> ### Actual behaviour
> The amount of the last transaction sent to node wallet is shown as "locked_balance"



> So the locked coins unlock automatically after 10 minutes. I think we can close this now since the funding attempt failed, but the script didn't unlock the coins automatically.

**Comment by Bladez1753** [comment] 2022-10-01 07:07
{
    "total_balance": "4039516",
    "confirmed_balance": "4039516",
    "unconfirmed_balance": "0",
    "locked_balance": "Here is the amount of transaction already with 450 confirmations",
    "account_balance": {
        "default": {
            "confirmed_balance": "4039516",
            "unconfirmed_balance": "0"
        }
    }
}
