### ISSUE TITLE
No record of push amounts in channel opening historical data

### ISSUE THREAD

**Issue by BTCBap** [lightningnetwork/lnd#6876] opened 2022-08-31 22:01 UTC
Background

The current available tools like Thunderhub, Ride the Lightning, Balance of Satoshis, etc are lacking historical reporting data for push amounts involved in channel openings. If this info is not manually recorded, it is lost, or left to be implied. I believe this is because LND is not relaying this info for accounting tools.

These programs above all have reporting history tools which can provide downloaded spreadsheet-formatted data for channel opening/closing, routing fees earned, chain fees spent, among other things. This is exceptionally helpful for those operating lightning businesses or those who wish to keep clean accounting records. However, in going through node history, I've noticed **there is not a record of push amounts in channel openings**.

For example, if someone has opened a channel for 10M satoshis, and pushes half upon opening- the channel recipient would have 5M added to their local balance. This data is not tracked as far as I can tell, as channel opening records are not tagged with any push amount data in the history.

Your environment

-LND 15.1
-linux
-bitcoind 

Steps to reproduce

Open a channel with an initial push amount. Neither the channel opener nor channel recipient will have record of the amount pushed through the channel in historical data. If this was done through an invoice immediately after or a keysend, but not during channel opening, there _would_ be a record.

Expected behaviour

One would expect the push amounts involved in channel opening to be reflected in internal data of the nodes, similar to a keysend. Of course, other nodes on the network would not be privy to this information, but this should be stored locally.

Actual behaviour

No data recorded for push amounts in channel openings.

**Comment by alexbosworth** [comment] 2022-08-31 22:07
Similar to https://github.com/lightningnetwork/lnd/issues/4490

**Comment by saubyk** [comment] 2024-09-13 19:19
Closing this, since its a duplicate of https://github.com/lightningnetwork/lnd/issues/4490

**Closed by saubyk** 2024-09-13 19:19 UTC
Labels: accounting
