### ISSUE TITLE
Incorrect "(default: 0)" in CLI help

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#4305] opened 2020-05-21 13:21 UTC
### Background

Defaults for Int64Flag are not specified for cli flags, this sets the default shown in --help to 0. Which is not the real default. 

E.g. here 
https://github.com/lightningnetwork/lnd/blob/c2516d935284f320cc2b9fe64fed0f512c517deb/cmd/lncli/commands.go#L2536-L2540

### Your environment

lnd version 0.10.0-beta commit=v0.10.0-beta-161-gc2516d935284f320cc2b9fe64fed0f512c517deb

### Steps to reproduce

```
lncli updatechanpolicy --help
```

### Expected behaviour
"--time_lock_delta value  the CLTV delta that will be applied to all forwarded HTLCs (default: 40)"

https://github.com/lightningnetwork/lnd/blob/c2516d935284f320cc2b9fe64fed0f512c517deb/chainregistry.go#L65

### Actual behaviour

"--time_lock_delta value  the CLTV delta that will be applied to all forwarded HTLCs (default: 0)"

**Comment by wpaulino** [comment] 2020-05-21 17:47
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/1523.

**Closed by wpaulino** 2020-05-21 17:47 UTC
