### ISSUE TITLE
Payment error: edge not found

### ISSUE THREAD

**Issue by Husogutr** [lightningnetwork/lnd#2596] opened 2019-02-06 20:46 UTC
### Background
First time with `lnd`, first time mainnet. Had used `c-lightning` on testnet before.
`tor.active=1` and `listen=127.0.0.1:9735` because I'm behind multiple NAT's.
Sometimes it takes several minutes to `openchannel` and get txid. In the remaining cases it reads `timeout`.
I have 2 active channels opened.

### Environment
- OS: Raspbian Stretch Lite November 2018
- lnd: v0.5.2-beta commit=v0.5.2-beta-rc6
- bitcoind: 0.17.1

### Steps to reproduce
```
lncli payinvoice [invoice]
Description: [desc]
Amount (in satoshis): [amount]
Destination: [dest]
Confirm payment (yes/no): yes
{
	"payment_error": "edge not found",
	"payment_preimage": "",
	"payment_route": null
}
```

### Expected behaviour
Some output telling payment went succesful. Have not seen it yet.

### Actual behaviour
Payment error above.

**Comment by Roasbeef** [comment] 2019-02-06 21:19
Are you trying to pay an invoice with hop hints? If so, this is a duplicate of #2066.

**Comment by Roasbeef** [comment] 2019-02-06 21:20
Also can you give any additional details?

**Comment by Husogutr** [comment] 2019-02-07 22:34
Honestly I don't know what hop hints are, so most likely I'm trying to pay an invoices without it.

Can't tell if my issue is related to #2066, because:
- Neither my node nor my channels are private
- An invoices I'm trying to pay is not generated by me. I am just getting it from online services (e. g. yalls.org). 
- My payment error differs from #2066's one

`lnd.log` reads nothing worthwhile with `debuglevel=info` at `lnd.conf` during `lncli payinvoice [invoice]` (couple fo seconds).

**Comment by wpaulino** [comment] 2019-02-08 00:16
Route hints are hints for private channels encoded in the invoice. It's possible that the destination included these in the invoice - you can tell by decoding the invoice and checking if it has anything set in the `route_hints` field.

My guess is that the issue seems to stem from the HTLC being canceled back with an error for a channel you are not aware of due to it being private.

**Comment by wpaulino** [comment] 2019-03-12 17:45
Closing as this is most likely a duplicate of #2066.

**Closed by wpaulino** 2019-03-12 17:45 UTC
