### ISSUE TITLE
[bug]: edge not found reported for newly opened channel

### ISSUE THREAD

**Issue by ardevd** [lightningnetwork/lnd#7426] opened 2023-02-19 21:57 UTC
### Background

Did a bos balanced channel open nearly two weeks ago. Opening TX was stuck in the mempool until today. The TX has been confirmed but the channel is in a very strange state. `lncli getchaninfo <chan_id>` returns:

`[lncli] rpc error: code = Unknown desc = edge not found`

[Here](https://mempool.space/tx/963ad6ca73e9afc7dd38999f13baf38b28766fd56dae9bc82b4344a436c50f94) is the opening transaction.

Thunderhub shows the channel, but with missing information.
<img width="1466" alt="Screenshot 2023-02-19 at 21 05 28" src="https://user-images.githubusercontent.com/366855/219977525-9a32a5e5-2bd3-4f11-bc0e-10a68acab1d7.png">

Any idea what's going on here? 

### Your environment

* version of `lnd`: 0.15.5-beta

**Comment by ellemouton** [comment] 2023-02-20 06:39
Hi @ardevd  - does `lncli listchannels` show the channel?

**Comment by ellemouton** [comment] 2023-02-20 06:41
also, are there any logs of interest around the time of this channel getting confirmed/opened? 

Would also be interested to know if your peer has the same issue (but understand you might not have that info)

**Comment by ellemouton** [comment] 2023-02-20 06:48
Ok from a quick investigation, it looks like the edge is only added to the db once a channel update is sent. And given the missing info in the screen shot you sent, the update was perhaps not sent...

**Comment by ellemouton** [comment] 2023-02-20 06:55
Do you see the following line in your logs anywhere? `Waited for 2016 blocks without seeing funding transaction confirmed, cancelling.`

**Comment by ardevd** [comment] 2023-02-20 07:30
I can confirm that my peer is seeing the same issue.

The channel also does show up under `listchannels`.

```json
{
            "active": false,
            "remote_pubkey": "03f918398e7dd266b5ff9ed330c4c86e502a51fc4d594861f1b5896d7cf4bacb44",
            "channel_point": "963ad6ca73e9afc7dd38999f13baf38b28766fd56dae9bc82b4344a436c50f94:0",
            "chan_id": "854713060556013568",
            "capacity": "5000000",
            "local_balance": "2496530",
            "remote_balance": "2500000",
            "commit_fee": "2810",
            "commit_weight": "1116",
            "fee_per_kw": "2500",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 600,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "50000",
            "remote_chan_reserve_sat": "50000",
            "static_remote_key": false,
            "commitment_type": "ANCHORS",
            "lifetime": "21673",
            "uptime": "10979",
            "close_address": "",
            "push_amount_sat": "2500000",
            "thaw_height": 0,
            "local_constraints": {
                "csv_delay": 600,
                "chan_reserve_sat": "50000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "4950000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "remote_constraints": {
                "csv_delay": 600,
                "chan_reserve_sat": "50000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "4950000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "alias_scids": [
            ],
            "zero_conf": false,
            "zero_conf_confirmed_scid": "0"
        },
```

**Comment by ardevd** [comment] 2023-02-20 07:33
> Do you see the following line in your logs anywhere? `Waited for 2016 blocks without seeing funding transaction confirmed, cancelling.`

I grep'ed through the lnd log and didnt see that message.

**Comment by thool2b3** [comment] 2023-02-20 10:17
Hi, I am the other peer in this opening transaction. I just searched through the lnd.log but did also not find this message 

> Waited for 2016 blocks without seeing funding transaction confirmed, cancelling

 but it could be that this part of the log is already gone. 
Yesterday early in the morning I found a Funding Cancelled message in RTL
![image](https://user-images.githubusercontent.com/109073892/220076594-9b32bb30-7ee9-4f74-9c7c-a3297a2cea9a.png)
But much later in the afternoon the opening tx slipped through:
963ad6ca73e9afc7dd38999f13baf38b28766fd56dae9bc82b4344a436c50f94
While on my side the funding already was canceled. 
I guess it is just bad luck but the question is how to resolve this.
Is there any chance to get the channel still opened? 
At least we should be able to get our funds back, right?

**Comment by ellemouton** [comment] 2023-02-20 11:31
Hi @thool2b3 , no I dont think there is a way to still open the channel (bad luck with the mempool there) but you should absolutely be able to recover the funds. There are two possible routes here. Both involve the funder (@ardevd) force closing the channel. 

## One

First, you the responder should try to see if you can export a channel backup using:

`lncli exportchanbackup --chan_point 963ad6ca73e9afc7dd38999f13baf38b28766fd56dae9bc82b4344a436c50f94:0`

Once the channel has been force closed, monitor to see if the channel shows up in your (@thool2b3 ) list of pending close channels. If it does, then your node will automatically handle sweeping your funds for you. If it doesnt, then you can try `lncli abandonchannel` and then `lncli restorechanbackup --single_backup` (using the backup previously created) to try force LND to sweep the funds. 

## Two

if the `exportchanbackup` or other steps above do not work (which they might not if your node decided just to completely forget about the channel) then: Get the funder to force close the channel, and then use [chantools sweepremoteclosed](https://github.com/guggero/chantools/blob/master/doc/chantools_sweepremoteclosed.md) to recover your funds.

**Comment by ardevd** [comment] 2023-02-20 11:34
@ellemouton thanks for the suggestion. Can you cast light on what exactly happened here and why the channel ended up in this state?

**Comment by ellemouton** [comment] 2023-02-20 11:38
My assumption is that the fundee node timed out the channel funding flow because the funding transaction took too long to confirm. Perhaps the tx didnt even propagate for a while given the mempool congestion.

**Comment by thool2b3** [comment] 2023-02-20 13:18
@ellemouton, the backup option didn't work: 
[lncli] rpc error: code = Unknown desc = unable to find target channel
The funding transaction actually vanished from my node (Umbrel) during the period. It appeared again in my node when the mempool congestion ebbed away and when it was finally accepted with 1 sat/vB but unfortunately couple of hours earlier the above mentioned _Close Channel Information : Funding Canceled_ happened.

**Comment by ellemouton** [comment] 2023-02-20 14:07
@thool2b3 , did you try the second option yet? (remember it will only work once the channel has been force closed by your peer)

**Comment by thool2b3** [comment] 2023-02-20 16:11
No I did not yet run the second option. Can I do it right after the the funder initiated the FC, or do I have to wait for any kind of confirmation? 
I am not familiar with thhis chantools command and I am also not sure how to _"Go through all the addresses that could have funds of channels that were force-closed by the remote party."_
I don't want to lose my funds.

**Comment by guggero** [comment] 2023-02-20 16:28
One confirmation of the force close transaction should be enough.
The command will do the "looking through all addresses" for you. All you need to do is to [download the tool](https://github.com/guggero/chantools/releases/tag/v0.10.6), (on any machine, doesn't have to be the same where you run the node), then run the following command (editing the parameters where I added placeholders):

```
chantools sweepremoteclosed --recoverywindow 300 --publish --feerate 5 --sweepaddr <address_from_your_wallet_to_send_funds_to>
```

The tool will then ask you for your seed and after that start scanning. If the funds are identified, it will send them automatically to the address you inserted.

**Comment by thool2b3** [comment] 2023-02-20 16:42
Hi @guggeror, thank you for your help. I am quite new to this stuff so I have to figure it out first. 
I can only run the tool on a Linux machine, right? If the answer is yes then I have to download it to my Umbrel node. 
I try to figure out how to do it. 
Could I come back to you in case I need help?

**Comment by guggero** [comment] 2023-02-20 16:45
No, there is also a Mac OS and Windows version available for download. You don't need to connect to your Umbrel node for it, you just need to have your seed handy (and an internet connection). Yes, you can DM me on [Slack](https://lightning.engineering/slack.html) if you need assistance (same username as here).

**Comment by thool2b3** [comment] 2023-02-20 16:47
Ok, I see. Is this one for Windows 10: [chantools-windows-386-v0.10.6.zip](https://github.com/guggero/chantools/releases/download/v0.10.6/chantools-windows-386-v0.10.6.zip)?

**Comment by thool2b3** [comment] 2023-02-20 16:58
Could you please show me how to verify the downloaded Archiv. 
Can I verify the downloaded Zip Archiv using Kleopatra? 
Thanks.

**Comment by guggero** [comment] 2023-02-20 17:16
The instructions for verifying are described in the body of the release text: https://github.com/guggero/chantools/releases/tag/v0.10.6
I won't be able to tell you how to run those same commands on Windows though, as I don't know and don't have a machine close by. But I'm sure this is an often asked question and Google should provide links for that.
Basically you want to verify the PGP signature `manifest-v0.10.6.sig` against the manifest file `manifest-v0.10.6.txt` and then make sure the SHA256 sum of the downloaded file matches the one in the manifest text file.

**Comment by thool2b3** [comment] 2023-02-20 17:22
The downloaded Windows Archive does not contain any manifest file just one exe-file (chantools.exe).

**Comment by guggero** [comment] 2023-02-20 17:23
You can download the manifest from the linked release page.

**Comment by thool2b3** [comment] 2023-02-20 17:44
Thank you. I downloaded the manifest files and could verify them in the mean time. 
When I run gpg `--verify manifest-v0.10.6.sig manifest-v0.10.6.txt` I get 
gpg: Signatur vom 29.10.2022 14:36:14 Mitteleuropische Sommerzeit
gpg:                mittels RSA-Schlüssel F4FC70F07310028424EFC20A8E4256593F177720
gpg: Korrekte Signatur von "Oliver Gugger <gugger@gmail.com>" [vollständig]
And for the SHA256 checksum under Windows I run: 
certutil -hashfile "<drive:\folder>\chantools-windows-386-v0.10.6.zip" SHA256 
and I get 82648145eb9153aef73cbe66e6fa9405e3790d3026ae3f25e3b459e108db2d52
Which is correct. 
I don't know how to run the git verify-tag command. 
Is it necessary or is the archive now sufficiently verified?

**Comment by thool2b3** [comment] 2023-02-20 17:47
@guggero, would be nice if I could contact you on Telegram if I need further help. 
Thanks.

**Comment by thool2b3** [comment] 2023-02-20 18:03
@guggero, never mind but could you please explain why I need to enter my seed phrase. 
How can I be sure it is safe? 
Thanks

**Comment by thool2b3** [comment] 2023-02-20 19:44
@guggero, using the command you gave me I could successfully recover my funds from the force close. 
Thank you very much indeed. 
I would like to send you some sats to express my gratitude. Can I send you some on Telegram using LNTipBot? 
I am not sure how to use the Trinkgeld function here. I am quite new to all this stuff...

**Comment by guggero** [comment] 2023-02-20 19:52
Channel is closed, all funds are recovered (or currently time locked and soon recoverable).

Timing out a channel after 2016 blocks of no confirmation is the default behavior, [according to the spec](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#the-funding_created-message). Normally this doesn't pose any risk for the _responder_ of a channel, as their initial balance is 0. With a push amount, they also have something at stake, so the responder should only agree to a push amount channel open if the funding transaction has sufficient fees attached to get confirmed within the 2016 blocks.

Closing as everything worked according to the spec.

**Closed by guggero** 2023-02-20 19:52 UTC
Labels: bug, needs triage

**Comment by ardevd** [comment] 2023-02-20 22:11
I would argue that while lnd is technically working according to spec, both lnd itself and the ecosystem around it (ThunderHub, RTL, etc) could be improved to handle channels that effectively time out in a better manner. Lnd showed the channel but returns errors when you try to interact with it. ThunderHub basically crashes. The lnd log didn't print any message related to the timeout either. As far as I can tell, the only way we can tell that the opening TX effectively expired in this case is by simply assuming as much due to lack of any other indicators?

**Comment by guggero** [comment] 2023-02-21 08:18
I agree, there is no good indicator for the expiry of the channel. If we add that, it might also make it more clear to the channel initiator that they're expected to get the channel confirmed.
I created a new issue: https://github.com/lightningnetwork/lnd/issues/7434.

**Comment by guggero** [comment] 2023-04-24 19:22
Can you check whether the funding transaction actually made it into the mempool?

**Comment by guggero** [comment] 2023-04-24 20:17
The `channel.backup` file is only a way to contact the remote peer and ask them to force close. It cannot restore a channel on its own. Do you have a full copy of your `channel.db` file from before you ran the `abandonchannel` command?

**Comment by guggero** [comment] 2023-04-24 20:22
Okay, then you can use the [`chantools forceclose`](https://github.com/guggero/chantools/blob/master/doc/chantools_forceclose.md) command using a version of the `channel.db` file from before you ran the `abandonchannel` command. That will publish the force close transaction and after the time lock has expired, you can sweep the funds using [`chantools sweeptimelockmanual`](https://github.com/guggero/chantools/blob/master/doc/chantools_sweeptimelockmanual.md).

**Comment by guggero** [comment] 2023-04-24 20:33
The description on that command isn't perfect, I know. Beside the `--channeldb` you need to specify a JSON in the same format as the `lncli listchannels` output, though you can omit most fields as only the channel point is needed. Then you specify that file with the `--listchannels` flag.

**Comment by guggero** [comment] 2023-04-25 10:42
I know the feeling and it sucks... I guess you can sign up at www.node-recovery.com so if the remote node operator ever signs up there as well (or might already have), we can get contact information to rescue the funds cooperatively.

Though IMO the instructions are quite clearly directed towards the _responder_ of the channel, not the funder:

> First, you the responder should try to see...

But we now went through all issues that somehow mention `lncli abandonchannel` and added an additional warning. I'm not sure what more we can do, since the command line flag (and its description) should be pretty clear when you should or should not use the command. And we never include the flag in example commands we give.

**Comment by guggero** [comment] 2023-05-01 08:11
When you create a channel, you send funds to a 2-of-2 multisig address, where your node has a key and the other node has a key. So neither of them can spend it without the cooperation of the other party.
The reason why as the funder of a channel you are okay with that is, because you only publish that funding transaction once you get a counter signed commitment transaction from the peer for spending those funds again. That commitment transaction is the current channel state and is only known to the two channel participants, kept in their databases. In this case the other party deleted it after two weeks (they didn't have any funds at stake) and you deleted yours with the `abandonchannel` command.

An SCB _cannot_ safely contain the latest channel state, because the moment you write a backup it could already be outdated. And using an outdated state puts you at risk of losing all funds as publishing an old state would be a channel breach. Again, all of this is described here: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#file-based-backups

I agree that "backup" is a bad term and that we probably need more warnings around commands related to those. I'm going to see what we can do there.

Also, can you DM me the public key of the other node? I can check a few more registries to see if they have some contact information somewhere.

**Comment by guggero** [comment] 2023-05-01 09:29
I think that's not a bad idea, yes. Can you create a feature request issue please?

**Comment by guggero** [comment] 2023-05-01 09:30
Also, can you add to the same issue that we should also store the latest channel state in the "close summary" that is written when the channel is closed (or abandoned)?

**Comment by guggero** [comment] 2023-09-16 08:28
@kroese do you still have the channel.db of the affected channel? I was working on something completely unrelated and noticed that for some situations we do write more than just the channel summary and actually have a snapshot of the channel with the latest commitment (not sure if that applies to abandoning the channel too, but maybe worth a try). I just pushed a new commit to `chantools` (in the `master`) branch. Could you check if `chantools dumpchannels --closed --channeldb ...` has the `HistoricalChannel` field set? Then there might be a way to publish the last state.

**Comment by guggero** [comment] 2023-09-18 06:56
Argh, okay. So I guess we only store that information once the channel becomes fully operational... Sorry, just thought there might be a slim chance, but apparently I was wrong.

**Comment by guggero** [comment] 2023-09-18 07:32
I think we also only started storing that information from a certain version onwards. So channels closed in a previous version wouldn't have the information. Didn't really dig deep into it, so can't say what version that would be.
