### ISSUE TITLE
QueryRoutes + SendToRoute interface is confusing in the presence of a multigraph

### ISSUE THREAD

**Issue by federicobond** [lightningnetwork/lnd#1573] opened 2018-07-17 15:06 UTC
The current QueryRoutes command returns an array of Routes through which a payment of a certain amount can be routed. The route hops are described as a sequence of channels. Its output can then be used as an input to SendToRoute, which promises to take one of those routes and route the payment through it.

Unfortunately, when multiple channels are open between two consecutive hops, that promise cannot be maintained, as the HTLC packet contains only layer-2 onion routing data, that is, the identities of the hops but not which specific channels to route through. If a node has multiple open channels with the next hop, LND will choose the one with largest bandwidth. This means that the Route taken might not be the one passed as an argument to SendToRoute, and the return value will be inaccurate as well, which can lead to mistakes or false assumptions.

The interface (inputs and return values) should make it clear that SendToRoute can only guarantee that the payments goes through a sequence of nodes, not channels. The return value of SendPayment likely suffers from the same problem.

**Comment by wpaulino** [comment] 2018-07-17 18:56
Duplicate of #1515.

**Closed by wpaulino** 2018-07-17 18:56 UTC

**Comment by federicobond** [comment] 2018-07-17 19:19
Thanks for the quick response, I had missed that issue.
