### ISSUE TITLE
lnd crashed with out of memory

### ISSUE THREAD

**Issue by hpbock** [lightningnetwork/lnd#2658] opened 2019-02-19 12:43 UTC
### Background

After running for three days, LND crashed with an out of memory exception.

### Your environment

* Version: 0.5.1-beta commit=v0.5.1-beta-721-g81783a60dc87f275d415be2e55c8f03688cd63ae, build=production, logging=default
* Linux odroid 4.14.66-147 #1 SMP PREEMPT Wed Aug 22 13:24:49 -03 2018 armv7l armv7l armv7l GNU/Linux
* bitcoind V0.16.3
```
$ free -h
              total
Mem:           1.9G
Swap:          8.0G
```

### Steps to reproduce

LND was just running normal. See [stderr log](https://privatebin.net/?122528b4640c9004#bhZXYdMOXzbRMwpG70//KlPghgXgEo56ofFD/dsL0UU=).

There are over 2000 stacktraces in the stderr log. What is the meaning of _minutes_ in that log? There are a lot of stack traces that have a _minutes value_ of mor than 1000.

### Expected behaviour

LND should keep its memory footprint constant at a few hundred MB.

### Actual behaviour

It crashes when allocating memory.

**Comment by Roasbeef** [comment] 2019-02-20 00:20
Was your full node active at this point? The minutes represents how long a goroutine has been blocked on a particular statement.

**Comment by Roasbeef** [comment] 2019-02-20 00:21
I run `lnd` on a box with 1GB of RAM and don't run into any issues, and we also recently merged a number of memory related optimizations, so I think something else is up.

**Comment by halseth** [comment] 2019-02-20 09:40
Memory use should improve significantly with the upcoming 0.6 release.

**Comment by hpbock** [comment] 2019-02-20 10:25
@Roasbeef my full node was active and running. With my testnet node I experienced memory issues  during the last one or two weeks - which caused me to shut it down four days ago.

I meanwhile monitor my node using munin. The graph below shows the memory consumption. I restarted my full node on 13:24 - which is unfortunately not shown in the graph. After the restart, lnd consumed about 1,4GB until about 14:30. Since then, beside one peek around 17:00, it consumes uses between 400MB and 600MB resident memory.

![image](https://user-images.githubusercontent.com/15837933/53084277-c9988980-3500-11e9-9f1d-4c13d8b7a01b.png)

**Comment by Roasbeef** [comment] 2019-02-20 23:08
Can you give us either a goroutine dump or the top 25 items on the heap using a memory profile? Thanks! [This blog post should help](https://blog.golang.org/profiling-go-programs).

**Comment by Roasbeef** [comment] 2019-02-20 23:09
Also is your testnet node active and responding to RPC requests at this time?

**Comment by hpbock** [comment] 2019-02-22 07:57
@Roasbeef the graph beneath shows the memory usage of my server which runs lnd. The memory consumption stays constant most of the time, but raises sporadically. At the times during which the memory consumption rises I also see a high CPU and network usage.

I started lnd on feb 21 07:04:
`
2019-02-21 07:04:42.358 [INF] LTND: Version: 0.5.1-beta commit=v0.5.1-beta-756-g2bf22617d4edf571b2f0b4b46f1a2d721bef74c8, build=production, logging=default
`
Beginning at around 13:00 i see a lot of warnings in the [logfile](https://privatebin.net/?0f112e02e402e670#lD+6+D4kYqOXs1boRVHgHG74coY8y6apbAG4bz0t1gc=) about inbound connections from peers that are already connected.

`
2019-02-21 13:02:31.730 [WRN] SRVR: Received inbound connection from peer 036a33e92cda2679ac91ac0467acb1ba33396c0df1119521653e0f269c275dd6bf, but already connected, dropping conn
2019-02-21 13:02:41.453 [WRN] SRVR: Received inbound connection from peer 036a33e92cda2679ac91ac0467acb1ba33396c0df1119521653e0f269c275dd6bf, but already connected, dropping conn
2019-02-21 13:02:51.110 [WRN] SRVR: Received inbound connection from peer 02e5067afb7be9470214acc10d7b3ebc39e84cd7de57d86cc3598514fa6d821229, but already connected, dropping conn
2019-02-21 13:02:56.348 [WRN] SRVR: Received inbound connection from peer 02e5067afb7be9470214acc10d7b3ebc39e84cd7de57d86cc3598514fa6d821229, but already connected, dropping conn
2019-02-21 13:02:56.488 [WRN] SRVR: Received inbound connection from peer 02fe9469e1d7da69539e365c9b2a64d277ed5589622cb314dc8b3060f3c55f79e6, but already connected, dropping conn
2019-02-21 13:03:00.283 [WRN] SRVR: Received inbound connection from peer 03aca0142349abf19e96a3c9231d556a1525182b659e8b2ae5328efbd01ff227e1, but already connected, dropping conn
2019-02-21 13:03:01.436 [WRN] SRVR: Received inbound connection from peer 036a33e92cda2679ac91ac0467acb1ba33396c0df1119521653e0f269c275dd6bf, but already connected, dropping conn
`

At 14:33 there are a lot errors about ZMQ messages in the logfile:
`
2019-02-21 14:33:25.453 [ERR] LNWL: Unable to receive ZMQ rawtx message: invalid flag
2019-02-21 14:33:25.453 [ERR] LNWL: Unable to receive ZMQ rawtx message: invalid flag
2019-02-21 14:33:25.453 [ERR] LNWL: Unable to receive ZMQ rawtx message: invalid flag
`

Please tell me if you need further informations!

![image](https://user-images.githubusercontent.com/15837933/53225218-9a585880-3677-11e9-8d9f-8653ae79e82f.png)
![image](https://user-images.githubusercontent.com/15837933/53225289-d12e6e80-3677-11e9-88d7-a5b006842f49.png)
![image](https://user-images.githubusercontent.com/15837933/53227052-62541400-367d-11e9-9eee-6926c47f6cd9.png)

**Comment by hpbock** [comment] 2019-02-22 13:16
BTW I noticed high write latencies up to two seconds of the SD card on which lnd stores its data. This might cause the system to block completely and maybe lnd can not acknowledge incoming network gossip on time. This could be the cause why @Roasbeef has not experienced this behaviour yet.

![image](https://user-images.githubusercontent.com/15837933/53244387-0607e900-36ab-11e9-918d-87f1e704ca66.png)

**Comment by hpbock** [comment] 2019-02-22 13:19
This issue sounds similar to #2682, #2685 and #2551.

**Comment by Roasbeef** [comment] 2019-02-22 17:27
I don't think so, your issue seems to be a lack of stable connection to bitcoind.

**Comment by Roasbeef** [comment] 2019-02-22 17:28
If you use [`go tool pprof`](https://blog.golang.org/profiling-go-programs) then we'll be able to obtain actionable data (heap top25 and goroutine dump).

**Comment by hpbock** [comment] 2019-02-22 20:24
@Roasbeef I am sorry, but I do not understand what I need to run to get a goroutine dump or the top 25 items on the heap using a memory profiler. 😢 I am not familiar with programming go language. Are there some simple commandline tools which i can run to help you with?

My lnd testnet node is currently not running.

**Comment by Roasbeef** [comment] 2019-02-22 21:37
Check out the blog post I linked to

**Comment by hpbock** [comment] 2019-02-25 19:51
Sorry, I do not understand the blogpost. If I run `go tool pprof`it just shows me a help page. How do I use it with a running `lnd`? Is there a simple commandline?

**Comment by Roasbeef** [comment] 2019-03-05 22:52
`go tool pprof http://localhost:6061/debug/pprof/heap`

If you have `--profile` set to 6061, and you're running this on the same machine.

**Comment by hpbock** [comment] 2019-03-07 13:51
It seems that `discovery createChanAnnouncement` ate up the memory between 13pm to 14 pm today.

profile graph from right now: [profile006.pdf](https://github.com/lightningnetwork/lnd/files/2941494/profile006.pdf)

yesterdays profile graph: [profile005.pdf](https://github.com/lightningnetwork/lnd/files/2941508/profile005.pdf)

![image](https://user-images.githubusercontent.com/15837933/53961012-ec719300-40e7-11e9-9ce0-9c4921f7114b.png)

**Comment by Roasbeef** [comment] 2019-03-07 23:42
That last profile was super helpful! If you check your logs, do you see a peer continually connecting and re-connecting? Or a series of them?

**Comment by hpbock** [comment] 2019-03-08 12:22
There are different peers, that the connection has an EOF or i/o timeout and is therefore reconnected. Below is a list of the numbers of new connections to/from the other peer.

According to 1ml the [peer with the most reconnects](https://1ml.com/node/026199bd0c2d357b3730d4c7a75589d2741ac5a606367198e48ffd27e22472f2fc) was first seen 8 days ago.

```
node public keys                                                   | reconnects
-------------------------------------------------------------------|-----------
026199bd0c2d357b3730d4c7a75589d2741ac5a606367198e48ffd27e22472f2fc | 192
020f0d93c700cf5cf556e61828fab473a5c30ee6eb927ae36a130cc1c57326d21a | 72
031e47777e35627e1018bc886ee24f81633a54527cfce24df0183a8fee7b3a24ef | 68
026c4708bb9e2cb2819643aa05ac38354afa0ac7286fb9a7edfddb282d26401a1d | 60
0233502f6370758ede277d0ee5308a900feffeea29dbe9fc9593d1d0c30b2eb30e | 53
026bce917a5854f3c5140cc69c977d19a6d656554120b6dedf045b246941b858c5 | 53
02a1d2856be336a58af08989aea0d8c41e072ccc392c46f8ce0e6e069f002035f3 | 52
032b2b3f4abda9677bb9563e226c068d3a2456fb8b036635a81c9bcaa1671d1ada | 49
032bf50d657c83e911b3f40ed26a8280f48ad75aca58cd6f8e82f04adf943bbf50 | 49
03c2d52cdcb5ddd40d62ba3c7197260b0f7b4dcc29ad64724c68426045919922f0 | 49
0335f1fcbb62b9490d0b4007fa158669e42f08599149b2cc54ed1d36888737e6d7 | 46
02262bbc21c171bc91a1d6bbf89571c95873849b9a60d3ea9671b777d852d39ecd | 45
031d2bbc75802689312220a017c6b51fa246efc59c7aa9355f6f7395038ffb4d6a | 44
03beddc8adbf7d56a7da15cdaf95d97b24d07088c3571b421c0e6f9d551a210342 | 42
030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f | 37
0338f87cb05016c9427de7872192615f9313d622db1a88f6c2594625ffd0b2d270 | 36
028dcc199be86786818c8c32bffe9db8855c5fca98951eec99d1fa335d841605c2 | 33
037172d2110c4148d6ed0c2790ec8be948458022425dced6794fede834be92af36 | 33
02e05528006a0b51bb72a13d81b06520486ccf8aa69b3116a9797aa6d81517af03 | 31
03012a23c769decc4fb40a92d5300692b576cb8dc887072580638b97911742554c | 31
0349e1165104b5606b94fa8e11499106f8e66526b497dcad6cc22d64987b0808e0 | 31
026c7d28784791a4b31a64eb34d9ab01552055b795919165e6ae886de637632efb | 30
029a8741675c4c9078b577ddc4348d602d2fb45a12e6087b617925997a84f4c02e | 30
021607cfce19a4c5e7e6e738663dfafbbbac262e4ff76c2c9b30dbeefc35c00643 | 28
03a503d8e30f2ff407096d235b5db63b4fcf3f89a653acb6f43d3fc492a7674019 | 28
03fce165537aea120bffe8505876b44d5119354f825b3eac329b761fc5636bf334 | 28
0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 | 27
02a0bb5ded1dd6c4f8d53682865fe22adb09b953b24812da0f0b7659f84e057c26 | 27
034653a43cb5857d6f75ff19866e27a8e03355827bf6036fd8d3c9478a37e33813 | 26
03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12 | 26
024d2387409269f3b79e2708bb39b895c9f4b6a8322153af54eba487d4993bf60f | 25
0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266 | 24
024b8019795ec753fcdb1eb21ecd319bfab6a8b05e017f357dc5f052a181fb8c91 | 24
0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 | 24
03c2abfa93eacec04721c019644584424aab2ba4dff3ac9bdab4e9c97007491dda | 24
03d69c8a0e020a10940aa54a5330b4b74600d32732aba38ac6a86611997f038a6a | 24
024a549e096f4355073e3a2712a10c5a773e48bd21a7d2ddef71639481008ce811 | 23
0260fab633066ed7b1d9b9b8a0fac87e1579d1709e874d28a0d171a1f5c43bb877 | 23
035c0730794cb324eaf7a5e79e066ef54fe4c495f1fb54118ef9651f7fb1318198 | 23
036a33e92cda2679ac91ac0467acb1ba33396c0df1119521653e0f269c275dd6bf | 23
0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0 | 23
039f01ad62e5208940faff11d0bbc997582eafad7642aaf53de6a5f6551ab73400 | 23
03bd45e49b079dc69f0402ec3004711276a372413bd483fa39e3ff4e3e810b197d | 23
0204a2b95b4c208383d7f02e741a8bfd5b5b7e8bea8d1543b1255da8342d9f2c6b | 22
02c0b38022846c6b6f45b30031859ac7c5fb0c67ec8ed5cce8409c4b438c267ffe | 22
02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469 | 22
02efb7d9ddb5e7c05a3b5e6fce5d919390512b4e108e9bce850b206ab39bc32268 | 22
0303a518845db99994783f606e6629e705cfaf072e5ce9a4d8bf9e249de4fbd019 | 22
031ce29116eab7edd66148f5169f1fb658fad62bdc5091221ab895fe5d36db00b2 | 22
03321fab5e3db6c378e23e9cceb522325dc4f6b0c68819944569128d34cba9cca3 | 22
0358327cb80ab2a8db36a5924c62966c7b4a753045600df594aa3863ecb618cc5d | 22
0373ca948ffd4cbbd08488c480aa7c43b57e9446c8ac6d3fe1cc92392e39e9eb95 | 22
0374ecf61ed6c1208c42339f47decde2bc0c4393ac95f07827b3471e939d7eb961 | 22
03a5886df676f3b3216a4520156157b8d653e262b520281d8d325c24fd8b456b9c | 22
03bc9337c7a28bb784d67742ebedd30a93bacdf7e4ca16436ef3798000242b2251 | 22
03da1c27ca77872ac5b3e568af30673e599a47a5e4497f85c7b5da42048807b3ed | 22
03dab87ff8635982815c4567eb58af48f9944d11c56beb12b91e1049aaea06e187 | 22
03e5ea100e6b1ef3959f79627cb575606b19071235c48b3e7f9808ebcd6d12e87d | 22
03ed88bb37c8c53c509d9a355e5a103614ebd30c98b7895ea4ccaddee262db190d | 22
02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b | 21
0232e20e7b68b9b673fb25f48322b151a93186bffe4550045040673797ceca43cf | 21
0265fae305778b7cb157365f70cf3a2047d2cad5c1ccc5f550c6d8a033084a8ea5 | 21
026726a4b043d413b45b334876d17b8a98848129604429ec65532ba286a42efeac | 21
02c91d6aa51aa940608b497b6beebcb1aec05be3c47704b682b3889424679ca490 | 21
02d7ca7aae77a43a65a50cbf806cf7b43af2f89c1cf331f98a3415263fa2031368 | 21
02f3069a342ae2883a6f29e275f06f28a56a6ea2e2d96f5888a3266444dcf542b6 | 21
032679fec1213e5b0a23e066c019d7b991b95c6e4d28806b9ebd1362f9e32775cf | 21
03d37fca0656558de4fd86bbe490a38d84a46228e7ec1361801f54f9437a18d618 | 21
036d1103b67ac8c4c376c133123abd69e242dec3be10b4f0d2f63177b526e4e8fc | 20
03a8eb40ba4c068847ba1a98bdfee2e7d0d3c2844d9cbba65e715966eda3904ed9 | 20
03c7be17b94473f0b515541f4ed4aacceea9be6a5c15eecdd4c4bcf256bafccb08 | 20
03d0087b718ce9259b36485995094a2065a378135925f9a71a5daf2500300fe662 | 20
.....
```

**Comment by ZapUser77** [comment] 2019-03-13 01:00
How did you create that list of peers with # of reconnect attempts?

**Comment by hpbock** [comment] 2019-03-13 15:10
@ZapUser77 i created this with a quick and dirty mix of bash, python and librecalc:

```bash
$ cat lnd.log | grep "Finalizing connection to" | cut -d \  -f 8-8 | sed s/,// >blubb
```
...to get the node id for every finalizing connection event.

```python
import json

nodes = {}

with open("blubb") as f:
    for line in f:
        nodeid = line.strip()
        if nodeid not in nodes:
            nodes[nodeid] = 1;
        else:
            nodes[nodeid] += 1;

print json.dumps(nodes, indent=4)
```
...to count the number of connections by each node.

**Comment by ZapUser77** [comment] 2019-03-16 02:54
I updated to version 0.5.2-99-beta commit=queue/v1.0.1-23-g36cc1da8ea0eec6be4559c673bc07bd0ae9be66a to see if the 'deprioritize gossip' commit helped any.
Now peers are flapping, and crashed in less than 24 hours from 'out of memory.'

**Comment by wpaulino** [comment] 2019-03-18 17:22
@ZapUser77 you need your peers to be running that commit in order for you to benefit.

**Comment by ZapUser77** [comment] 2019-03-22 15:31
Out of memory crashes is getting pretty severe now, can't stay up more than 7-10 hours.
Is there any additional information I can provide that would be of any help?

**Comment by wpaulino** [comment] 2019-03-22 17:39
@ZapUser77 not really. We're fairly aware of all the recent issues and are currently in the process of addressing them.

**Comment by cfromknecht** [comment] 2019-03-22 18:57
@ZapUser77 deprioritizing gossip traffic doesn’t address memory issues, it’s meant to allow important msgs like ChannelReestablish to be prioritized in the face of large amounts of gossip traffic. That helps address the issue of peers being connected but their channels being inactive because the ChannelReestablish comes after >30s. It makes sense that that commit alone didn’t solve the issue

**Comment by ZapUser77** [comment] 2019-03-28 01:01
No crash in 5 days... I made no changes since last OOM crash.  No peers flapping.
Looks like something has changed for the better.

**Comment by hpbock** [comment] 2019-03-28 19:31
Memory consumption is much lower since I updated my lnd to main on 22th of March. Peers are still flapping though.

**Comment by ZapUser77** [comment] 2019-03-29 03:49
Channels started flapping, starting with LN BIG 0303a518845db99994783f606e6629e705cfaf072e5ce9a4d8bf9e249de4fbd019, then more and more started flapping, eventually crashing with OOM.  Will update to the "we fixed flapping" commit.

**Comment by ZapUser77** [comment] 2019-03-30 01:02
Upgraded to latest commit.  Peers still flapping, then I get spammed with 1,000+ of: 
2019-03-30 01:41:48.229 [ERR] LNWL: Unable to receive ZMQ rawtx message: frame too large
2019-03-30 01:41:48.230 [ERR] LNWL: Unable to receive ZMQ rawtx message: invalid flag
<Repeat 20 times>
2019-03-30 01:41:48.245 [ERR] LNWL: Unable to receive ZMQ rawtx message: expected message frame
2019-03-30 01:41:48.245 [ERR] LNWL: Unable to receive ZMQ rawtx message: invalid flag

The OOM crash.
https://0bin.net/paste/BfB-dwOo5mWrUXXv#Srt9NcZikA2UISH-7J11f1d7I/O7y2nT6L+3y/RCvwk

**Comment by Roasbeef** [comment] 2019-03-30 01:06
That's an issue with your zmq connection. If you're on master, but your
peers aren't then they'll still flap, but less often (slower cycle). After
2 open prs are merged, the issue should be resolved altogether.

**Comment by ZapUser77** [comment] 2019-03-30 01:20
From LND.conf:
bitcoind.zmqpubrawblock=tcp://127.0.0.1:18501
bitcoind.zmqpubrawtx=tcp://127.0.0.1:18502

From Bitcoin.conf:
zmqpubrawblock=tcp://127.0.0.1:18501
zmqpubrawtx=tcp://127.0.0.1:18502

Both running on same machine.  How could there possibly be 'zmq connection problem'?  (Not being sarcastic, I genuinely don't understand how there could be a connection problem when on the same machine.) And how would I go about fixing it?
Was it the cause of the OOM, or was the thing that caused the OOM also cause the ZMQ errors?

Thanks.

**Comment by ZapUser77** [comment] 2019-03-30 01:50
I was thinking, multiple threads of the gossiper run asynchronously, which is eventually getting so backed up it causes OOM.
Would putting a check within the subroutine [If <Available Mem> < X, Then Wait Y seconds] 
where X is the amount needed, and Y is increased each time it fails, stop the crashes, but wouldn't fix the underlying cause.  I'm not sure if you can check available mem with go, but I imagine it's possible.

**Comment by hpbock** [comment] 2019-03-30 19:27
Since I updated my node to HEAD on 22nd of march the memory consumption has reduced dramaticaly.
![image](https://user-images.githubusercontent.com/15837933/55280764-09d1ff80-532a-11e9-877e-9850adb3d2d5.png)
@ZapUser77 I observed the ZMQ problem on my node to quite a while ago. To reduce stress to my node I limit the number of new peer connections to two per minute using iptables. I had neither an OOM nor that ZMQ problem since setting this limit. Peers are still flapping though during some hours of the day. Some kind of truncated binary exponential backoff waiting time for lnd reconnecting to peers might be helpful.

@Roasbeef is it possible that the ZMQ problem is caused by the many broken sockets to other peers depleting the users limit of open files?

**Comment by ZapUser77** [comment] 2019-03-31 01:18
"limit the number of new peer connections to two per minute using iptables"
Is this correct? [I removed the port from the example.]
sudo iptables -I INPUT -m state --state NEW -m recent --update --seconds 60 --hitcount 2 -j DROP
sudo iptables -I INPUT -m state --state NEW -m recent --set

**Comment by Roasbeef** [comment] 2019-04-09 23:45
Closing now as it seems the root issue has been addressed by the recent changes in master. The ZMQ issue seems to be something distinct all together, and may be addressed by increasing the high water mark setting for bitcoind.

**Closed by Roasbeef** 2019-04-09 23:45 UTC
