### ISSUE TITLE
Channel Recovery: ChanStatusLocalDataLoss, needs recovery

### ISSUE THREAD

**Issue by blckbx** [lightningnetwork/lnd#6425] opened 2022-04-17 08:20 UTC
### Background

Long story short: Data loss (lnd datadir gone for good) led to one channel left that I was not able to coop close in time until lnd process finally died after running without underlying datadir for some hours. This channel is still pending in limbo. channel.db now is not available anymore.

### Your environment

* `0.14.3-beta.rc1`
* Linux 5.13.0-39-generic
* bitcoind 22.0

### Steps to reproduce

* start lnd
* delete whole datadir on accident
* try to recover files (channel.db, wallet.db, wtclient.db, sphinxreplay.db) out of running process `sudo tail -c -f +0 /proc/<pid_of_lnd_process>/fd/<number_of_file_in_proc> > newfile` (sudo cp works also, see [link](https://superuser.com/questions/283102/how-to-recover-deleted-file-if-it-is-still-opened-by-some-process/600743#600743))
* check if recovered channel.db is ok by compacting copy if channel.db with chantools -> fails "buckets are nil"
* coop close channels while you can (zap app had credentials on its own) and recover funds meanwhile
* unresponsive channel left 
* lnd process finally dies (end of journal? memory refresh? not sure)
* channel.db is gone now at this state
* recreate datadir structure with recovered files
* restart lnd to recreate tls.cert credentials
* force close left channels with SCB file

### Expected behaviour

Channel force closes. Funds return.
A built-in option to replicate channel.db to another place (like cln) would be of help in some of these cases.

### Actual behaviour

Channel cannot be force closed. Chan status: ChanStatusLocalDataLoss|ChanStatusRestored
Peer is @xmrk-btc (if you see this, sorry for this inconvenience!)

Logs:
```
lnd[29386]: 2022-04-17 09:42:39.550 [INF] SRVR: Established connection to: <peer>
lnd[29386]: 2022-04-17 09:42:39.550 [INF] SRVR: Finalizing connection to <peer>, inbound=false
lnd[29386]: 2022-04-17 09:42:40.080 [INF] PEER: NodeKey(<peer>) loading ChannelPoint(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1)
lnd[29386]: 2022-04-17 09:42:40.080 [WRN] PEER: Unable to find our forwarding policy for channel 064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1, using default values
lnd[29386]: 2022-04-17 09:42:40.081 [INF] HSWC: Removing channel link with ChannelID(0de7bbd1ed668cd9b4271207e3a3a83cb4afa82af84867342bf27f2b74014407)
lnd[29386]: 2022-04-17 09:42:40.081 [INF] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): starting
lnd[29386]: 2022-04-17 09:42:40.082 [INF] HSWC: Trimming open circuits for chan_id=691453:754:1, start_htlc_id=0
lnd[29386]: 2022-04-17 09:42:40.082 [INF] HSWC: Adding live link chan_id=0de7bbd1ed668cd9b4271207e3a3a83cb4afa82af84867342bf27f2b74014407, short_chan_id=691453:754:1
lnd[29386]: 2022-04-17 09:42:40.082 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1)
lnd[29386]: 2022-04-17 09:42:40.082 [INF] PEER: Negotiated chan series queries with <peer>
lnd[29386]: 2022-04-17 09:42:40.082 [INF] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): HTLC manager started, bandwidth=0 mSAT
lnd[29386]: 2022-04-17 09:42:40.082 [INF] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): attempting to re-synchronize
lnd[29386]: 2022-04-17 09:42:40.082 [INF] NTFN: New block epoch subscription
lnd[29386]: 2022-04-17 09:42:40.082 [INF] DISC: Creating new GossipSyncer for peer=<peer>
lnd[29386]: 2022-04-17 09:42:40.082 [INF] DISC: GossipSyncer(<peer>): requesting new chans from height=0 and 732247 blocks after
lnd[29386]: 2022-04-17 09:42:40.082 [INF] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): received re-establishment message from remote side
lnd[29386]: 2022-04-17 09:42:40.082 [ERR] LNWL: ChannelPoint(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): sync failed with local data loss: remote believes our tail height is 43415, while we have 0!
lnd[29386]: 2022-04-17 09:42:40.082 [WRN] LNWL: ChannelPoint(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): detected restored triggering DLP
lnd[29386]: 2022-04-17 09:42:40.082 [WRN] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): error when syncing channel states: ChannelPoint(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1) with CommitPoint(03548d7d9ff6161aea99997d63d7cc83264e2623be184fc9e60db57cc5d842acab) had possible local commitment state data loss
lnd[29386]: 2022-04-17 09:42:40.087 [ERR] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): failing link: unable to synchronize channel states: ChannelPoint(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1) with CommitPoint(03548d7d9ff6161aea99997d63d7cc83264e2623be184fc9e60db57cc5d842acab) had possible local commitment state data loss with error: unable to resume channel, recovery required
lnd[29386]: 2022-04-17 09:42:40.087 [INF] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): exited
lnd[29386]: 2022-04-17 09:42:40.087 [INF] HSWC: Removing channel link with ChannelID(0de7bbd1ed668cd9b4271207e3a3a83cb4afa82af84867342bf27f2b74014407)
lnd[29386]: 2022-04-17 09:42:40.087 [INF] HSWC: ChannelLink(064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d:1): stopping
```

**Comment by blckbx** [comment] 2022-04-18 09:36
Could restore almost all funds. One channel is left open (in waiting_close_channels). 
@xmrk-btc if you read this. please force close: 064401742b7ff22b346748f82aa8afb43ca8a3e3071227b4d98c66edd1bbe70d

**Comment by Roasbeef** [comment] 2022-04-18 18:07
AFAICT, everything re SCB is working as expected: if that peer force closes, then you'll be able to recover those remaining funds. If you can reconnect to them, then we'll send the error each time for them to trigger the force close. 

> Channel cannot be force closed

The SCB doesn't contain enough information for you to force close with the latest state. At most, if the channel has had zero updates, the original commitment transaction could be published. 

> A built-in option to replicate channel.db to another place (like cln) would be of help in some of these cases.

You can use the [etcd](https://github.com/lightningnetwork/lnd/blob/master/docs/etcd.md) or [postgres](https://github.com/lightningnetwork/lnd/blob/master/docs/postgres.md) backends for this.

**Comment by guggero** [comment] 2022-04-19 09:32
As @Roasbeef already mentioned, when using an SCB you are depending on the remote node to force close the channel.
Try to connect to their node manually if that didn't already happen (`lncli connect 033878501f9a4ce97dba9a6bba4e540eca46cb129a322eb98ea1749ed18ab67735@86.127.243.176:9735`). If their node is up and responding to your node's recovery request, it should force-close automatically.
You can try to reach out to them through `myspam486 -at- gmail.com` (according to the 1ml.com information of their node) to ask for manual force close.

Closing the issue since everything works as designed. File based database replication will not be added to `lnd` since that opens up the possibility of breaching yourself when using an outdated version. That's the whole reason for _static_ channel backups to exist. See https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#file-based-backups for more information.

**Closed by guggero** 2022-04-19 09:32 UTC

**Comment by blckbx** [comment] 2022-04-19 18:44
Thanks!  @xmrk-btc 
Funds have returned.
