### ISSUE TITLE
0.5rc1 slow re-scanning performance after wallet creation (testnet)

### ISSUE THREAD

**Issue by irekzielinski** [lightningnetwork/lnd#1828] opened 2018-09-02 12:30 UTC
### Background

playing with 0.5rc1 on odroid hc1 and testnet.
i created new wallet and noticed that re-scanning of blockchain is much slower than in 0.42.
in 0.42 it took around 2 hours after wallet was created for LND to be operational.
in 0.5 it has already been around 18 hours and rescan is still in progress

### Your environment

* version of `lnd`: 0.5 commit=73af09a06ae9cd5ba92a376e8253ae5450fe09cc
* which operating system (`uname -a` on *Nix): Linux odroid 4.14.55-146 SMP PREEMPT Wed Jul 11 22:31:01 -03 2018 armv7l armv7l armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core Daemon version v0.16.2
* any other relevant environment details: odroid hc1 with 2gb HDD, bitcoind is fully synced to chain

### Steps to reproduce

Create a new wallet on testnet.
LND will be slow re-scanning the blockchain

### Actual behaviour

Tell us what happens instead:

LND is very slow re-syncing:
```
Sep 02 11:58:42 odroid lnd[1847]: 2018-09-02 11:58:42.083 [INF] LNWL: Rescanned through block 00000000000aa89e175f6619b1cfb148b5426dc883407ee59443bd078164c1da (height 840000)
Sep 02 12:06:38 odroid lnd[1847]: 2018-09-02 12:06:38.463 [INF] LNWL: Catching up block hashes to height 850000, this might take a while
Sep 02 12:06:38 odroid lnd[1847]: 2018-09-02 12:06:38.502 [INF] LNWL: Done catching up block hashes
Sep 02 12:06:38 odroid lnd[1847]: 2018-09-02 12:06:38.503 [INF] LNWL: Rescanned through block 0000000000055dc4159f7297b9afc1ac445fde16f41cc97685e0732e07dfc00f (height 850000)
Sep 02 12:14:45 odroid lnd[1847]: 2018-09-02 12:14:45.521 [INF] LNWL: Catching up block hashes to height 860000, this might take a while
Sep 02 12:14:45 odroid lnd[1847]: 2018-09-02 12:14:45.561 [INF] LNWL: Done catching up block hashes
Sep 02 12:14:45 odroid lnd[1847]: 2018-09-02 12:14:45.561 [INF] LNWL: Rescanned through block 00000000000bb1616f5f7ef79b761a4535dbb589b1e0138e928ac3fd68dd90c3 (height 860000)
Sep 02 12:22:54 odroid lnd[1847]: 2018-09-02 12:22:54.204 [INF] LNWL: Catching up block hashes to height 870000, this might take a while
Sep 02 12:22:54 odroid lnd[1847]: 2018-09-02 12:22:54.242 [INF] LNWL: Done catching up block hashes
Sep 02 12:22:54 odroid lnd[1847]: 2018-09-02 12:22:54.243 [INF] LNWL: Rescanned through block 000000000042d513ff64c074c00323a27634330a0a9bfa6ce8706c152bb11150 (height 870000)
```

CPU does not seem to be too busy:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
1847 bitcoin   20   0 2161312 492916  35784 S  18.2 24.1 613:45.01 lnd
4110 root      20   0       0      0      0 I   2.6  0.0   0:05.22 kworker/4:1
1337 bitcoin   20   0  550228 179380   3500 S   1.7  8.8 102:38.78 bitcoind
3993 root      20   0       0      0      0 I   1.7  0.0   0:29.29 kworker/5:2
```

but HDD is being hammered:
```
Total DISK READ :       0.00 B/s | Total DISK WRITE :     716.56 K/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:     716.56 K/s
 TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
1889 be/4 bitcoin     0.00 B/s  417.99 K/s  0.00 % 52.58 % lnd
1906 be/4 bitcoin     0.00 B/s  238.85 K/s  0.00 % 33.60 % lnd
1855 be/4 bitcoin     0.00 B/s   59.71 K/s  0.00 %  4.84 % lnd
   1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % init false
   2 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kthre
```

**Comment by irekzielinski** [comment] 2018-09-03 07:02
hi, no restart - it took around 20h to complete the rescanning.
Maybe it;s related to some spamming that was going on testnet?

**Comment by adiack** [comment] 2018-09-03 14:03
I m running on .5 as well on an android phone (linuxdeploy image) rescanning took about 23 min to complete.

```
2018-09-03 12:07:26.716 [INF] LNWL: Caught up to height 0
2018-09-03 12:07:28.045 [INF] LNWL: Caught up to height 10000
2018-09-03 12:07:33.289 [INF] LNWL: Caught up to height 20000
2018-09-03 12:07:39.012 [INF] LNWL: Caught up to height 30000
2018-09-03 12:07:45.868 [INF] LNWL: Caught up to height 40000
2018-09-03 12:07:53.496 [INF] LNWL: Caught up to height 50000
2018-09-03 12:08:00.055 [INF] LNWL: Caught up to height 60000
2018-09-03 12:08:06.703 [INF] LNWL: Caught up to height 70000
2018-09-03 12:08:13.786 [INF] LNWL: Caught up to height 80000
2018-09-03 12:08:21.118 [INF] LNWL: Caught up to height 90000
2018-09-03 12:08:29.523 [INF] LNWL: Caught up to height 100000
2018-09-03 12:08:36.597 [INF] LNWL: Caught up to height 110000
2018-09-03 12:08:43.733 [INF] LNWL: Caught up to height 120000
2018-09-03 12:08:50.965 [INF] LNWL: Caught up to height 130000
2018-09-03 12:08:58.746 [INF] LNWL: Caught up to height 140000
2018-09-03 12:09:07.247 [INF] LNWL: Caught up to height 150000
2018-09-03 12:09:14.588 [INF] LNWL: Caught up to height 160000
2018-09-03 12:09:23.719 [INF] LNWL: Caught up to height 170000
2018-09-03 12:09:57.797 [INF] LNWL: Caught up to height 180000
2018-09-03 12:10:08.670 [INF] LNWL: Caught up to height 190000
2018-09-03 12:10:17.010 [INF] LNWL: Caught up to height 200000
2018-09-03 12:10:25.672 [INF] LNWL: Caught up to height 210000
2018-09-03 12:10:33.586 [INF] LNWL: Caught up to height 220000
2018-09-03 12:10:42.398 [INF] LNWL: Caught up to height 230000
2018-09-03 12:10:52.761 [INF] LNWL: Caught up to height 240000
2018-09-03 12:11:02.483 [INF] LNWL: Caught up to height 250000
2018-09-03 12:11:11.784 [INF] LNWL: Caught up to height 260000
2018-09-03 12:11:21.766 [INF] LNWL: Caught up to height 270000
2018-09-03 12:11:30.270 [INF] LNWL: Caught up to height 280000
2018-09-03 12:11:41.821 [INF] LNWL: Caught up to height 290000
2018-09-03 12:11:49.641 [INF] LNWL: Caught up to height 300000
2018-09-03 12:12:02.217 [INF] LNWL: Caught up to height 310000
2018-09-03 12:12:09.943 [INF] LNWL: Caught up to height 320000
2018-09-03 12:12:17.536 [INF] LNWL: Caught up to height 330000
2018-09-03 12:12:26.292 [INF] LNWL: Caught up to height 340000
2018-09-03 12:12:34.794 [INF] LNWL: Caught up to height 350000
2018-09-03 12:12:42.675 [INF] LNWL: Caught up to height 360000
2018-09-03 12:12:53.013 [INF] LNWL: Caught up to height 370000
2018-09-03 12:13:02.467 [INF] LNWL: Caught up to height 380000
2018-09-03 12:13:10.948 [INF] LNWL: Caught up to height 390000
2018-09-03 12:13:20.079 [INF] LNWL: Caught up to height 400000
2018-09-03 12:13:29.447 [INF] LNWL: Caught up to height 410000
2018-09-03 12:13:39.838 [INF] LNWL: Caught up to height 420000
2018-09-03 12:13:55.780 [INF] LNWL: Caught up to height 430000
2018-09-03 12:14:07.132 [INF] LNWL: Caught up to height 440000
2018-09-03 12:14:18.283 [INF] LNWL: Caught up to height 450000
2018-09-03 12:14:29.358 [INF] LNWL: Caught up to height 460000
2018-09-03 12:14:40.405 [INF] LNWL: Caught up to height 470000
2018-09-03 12:14:51.083 [INF] LNWL: Caught up to height 480000
2018-09-03 12:15:03.542 [INF] LNWL: Caught up to height 490000
2018-09-03 12:15:13.648 [INF] LNWL: Caught up to height 500000
2018-09-03 12:15:24.699 [INF] LNWL: Caught up to height 510000
2018-09-03 12:15:35.976 [INF] LNWL: Caught up to height 520000
2018-09-03 12:15:48.662 [INF] LNWL: Caught up to height 530000
2018-09-03 12:15:58.985 [INF] LNWL: Caught up to height 540000
2018-09-03 12:16:11.125 [INF] LNWL: Caught up to height 550000
2018-09-03 12:16:22.104 [INF] LNWL: Caught up to height 560000
2018-09-03 12:16:35.484 [INF] LNWL: Caught up to height 570000
2018-09-03 12:16:49.482 [INF] LNWL: Caught up to height 580000
2018-09-03 12:17:02.591 [INF] LNWL: Caught up to height 590000
2018-09-03 12:17:25.454 [INF] LNWL: Caught up to height 600000
2018-09-03 12:17:40.333 [INF] LNWL: Caught up to height 610000
2018-09-03 12:17:52.981 [INF] LNWL: Caught up to height 620000
2018-09-03 12:18:05.562 [INF] LNWL: Caught up to height 630000
2018-09-03 12:18:17.663 [INF] LNWL: Caught up to height 640000
2018-09-03 12:18:28.812 [INF] LNWL: Caught up to height 650000
2018-09-03 12:18:38.479 [INF] LNWL: Caught up to height 660000
2018-09-03 12:18:49.190 [INF] LNWL: Caught up to height 670000
2018-09-03 12:18:58.963 [INF] LNWL: Caught up to height 680000
2018-09-03 12:19:10.185 [INF] LNWL: Caught up to height 690000
2018-09-03 12:19:21.629 [INF] LNWL: Caught up to height 700000
2018-09-03 12:19:31.416 [INF] LNWL: Caught up to height 710000
2018-09-03 12:19:40.551 [INF] LNWL: Caught up to height 720000
2018-09-03 12:19:51.291 [INF] LNWL: Caught up to height 730000
2018-09-03 12:20:03.420 [INF] LNWL: Caught up to height 740000
2018-09-03 12:20:14.216 [INF] LNWL: Caught up to height 750000
2018-09-03 12:20:25.706 [INF] LNWL: Caught up to height 760000
2018-09-03 12:20:38.999 [INF] LNWL: Caught up to height 770000
2018-09-03 12:20:49.988 [INF] LNWL: Caught up to height 780000
2018-09-03 12:21:00.788 [INF] LNWL: Caught up to height 790000
2018-09-03 12:21:09.194 [INF] LNWL: Caught up to height 800000
2018-09-03 12:21:19.804 [INF] LNWL: Caught up to height 810000
2018-09-03 12:21:31.702 [INF] LNWL: Caught up to height 820000
2018-09-03 12:21:42.170 [INF] LNWL: Caught up to height 830000
2018-09-03 12:21:52.846 [INF] LNWL: Caught up to height 840000
2018-09-03 12:22:03.551 [INF] LNWL: Caught up to height 850000
2018-09-03 12:22:12.477 [INF] LNWL: Caught up to height 860000
2018-09-03 12:22:22.511 [INF] LNWL: Caught up to height 870000
2018-09-03 12:22:33.565 [INF] LNWL: Caught up to height 880000
2018-09-03 12:22:44.202 [INF] LNWL: Caught up to height 890000
2018-09-03 12:22:58.267 [INF] LNWL: Caught up to height 900000
2018-09-03 12:23:08.634 [INF] LNWL: Caught up to height 910000
2018-09-03 12:23:20.023 [INF] LNWL: Caught up to height 920000
2018-09-03 12:23:30.796 [INF] LNWL: Caught up to height 930000
2018-09-03 12:23:44.895 [INF] LNWL: Caught up to height 940000
2018-09-03 12:23:58.312 [INF] LNWL: Caught up to height 950000
2018-09-03 12:24:09.677 [INF] LNWL: Caught up to height 960000
2018-09-03 12:24:22.174 [INF] LNWL: Caught up to height 970000
2018-09-03 12:24:34.250 [INF] LNWL: Caught up to height 980000
2018-09-03 12:24:47.230 [INF] LNWL: Caught up to height 990000
2018-09-03 12:24:56.229 [INF] LNWL: Caught up to height 1000000
2018-09-03 12:25:09.882 [INF] LNWL: Caught up to height 1010000
2018-09-03 12:25:21.882 [INF] LNWL: Caught up to height 1020000
2018-09-03 12:25:35.083 [INF] LNWL: Caught up to height 1030000
2018-09-03 12:25:47.504 [INF] LNWL: Caught up to height 1040000
2018-09-03 12:26:02.514 [INF] LNWL: Caught up to height 1050000
2018-09-03 12:26:13.927 [INF] LNWL: Caught up to height 1060000
2018-09-03 12:26:27.528 [INF] LNWL: Caught up to height 1070000
2018-09-03 12:26:40.739 [INF] LNWL: Caught up to height 1080000
2018-09-03 12:26:54.889 [INF] LNWL: Caught up to height 1090000
2018-09-03 12:27:09.260 [INF] LNWL: Caught up to height 1100000
2018-09-03 12:27:23.998 [INF] LNWL: Caught up to height 1110000
2018-09-03 12:27:37.016 [INF] LNWL: Caught up to height 1120000
2018-09-03 12:27:52.220 [INF] LNWL: Caught up to height 1130000
2018-09-03 12:28:05.237 [INF] LNWL: Caught up to height 1140000
2018-09-03 12:28:19.695 [INF] LNWL: Caught up to height 1150000
2018-09-03 12:28:34.467 [INF] LNWL: Caught up to height 1160000
2018-09-03 12:28:47.896 [INF] LNWL: Caught up to height 1170000
2018-09-03 12:29:00.530 [INF] LNWL: Caught up to height 1180000
2018-09-03 12:29:14.748 [INF] LNWL: Caught up to height 1190000
2018-09-03 12:29:26.863 [INF] LNWL: Caught up to height 1200000
2018-09-03 12:29:42.065 [INF] LNWL: Caught up to height 1210000
2018-09-03 12:29:57.814 [INF] LNWL: Caught up to height 1220000
2018-09-03 12:30:14.336 [INF] LNWL: Caught up to height 1230000
2018-09-03 12:32:41.748 [INF] LNWL: Opened wallet
```


```
[android@localhost ~]$ uname -a
Linux localhost 3.18.35+ #1 SMP PREEMPT Tue Aug 29 10:08:49 CST 2017 aarch64 aarch64 aarch64 GNU/Linux
[android@localhost ~]$ lnd -V
lnd version 0.5.0-beta commit=a1f549754b61c1ba84466f0226997687127f7fc0
```

**Comment by Roasbeef** [comment] 2018-09-03 22:29
Nothing in this area of the code has changed, but the testnet chain has significantly been extended over the past few months it's now over 1.5 million blocks. If you're connecting to a _remote_ bitcoind then there's an known issue of the round trip latency as we currently fetch each block 1 by 1 as we need to utilize the batch JSON-RPC requests. 

Closing as a duplicate of #1528

**Closed by Roasbeef** 2018-09-03 22:29 UTC
