### ISSUE TITLE
Password forgotten, files accessible and seed known

### ISSUE THREAD

**Issue by iSOcH** [lightningnetwork/lnd#2108] opened 2018-10-27 13:02 UTC
### Background

I installed lnd (testnet) some time ago and forgot my password. I have access to the files and backed up my wallet seed. Is there a way to restore channel-states or should i just create a new wallet with the same seed?

### environment

* version of `lnd`: 0.4.2-beta commit=bc5bfeb479d5123ad3c9cfc8bf9636bb1535802e
* which operating system (`uname -a` on *Nix): 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core Daemon version v0.16.3

**Comment by wpaulino** [comment] 2018-10-27 21:30
At the moment, your off-chain funds cannot be recovered even with the seed. This will be possible with static channel backups, which we plan to include in our upcoming 0.5.1 release.

Considering this is testnet though, it'd be fine to lose the funds.

**Comment by Roasbeef** [comment] 2018-10-29 21:22
Closing as duplicate of #175

**Closed by Roasbeef** 2018-10-29 21:22 UTC
