### ISSUE TITLE
static channel backup not working

### ISSUE THREAD

**Issue by SetasSan** [lightningnetwork/lnd#2968] opened 2019-04-17 18:40 UTC
Updated my LND node from 0.5.2 to 0.6.
I have tried to create static channel backup. But it doesn't work.

Lnd: lncli version 0.6.0-beta commit=v0.6-beta-9-ga3c980b1e8fe12873ad364337b3379bb7b457cf4
OS:Ubuntu 18.04.1

executed:
`lncli exportchanbackup --all`
Response:
`[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.`

then tired to execute:
`lncli unlock`
Response:
`Input wallet password:
[lncli] Wallet is already unlocked
`
I expected my static channel file to be created in current directory. 

What I'm doing wrong here?

**Comment by wpaulino** [comment] 2019-04-17 18:50
Have you restarted `lnd` after the update? That should trigger a backup of all your existing channels.

**Comment by SetasSan** [comment] 2019-04-17 18:55
I did: 
`lncli stop`

copy .lnd directory

updated LND node

executed: `lnd`

my node started and 

executed `lncli unlock`

Now if I type `lncli -version
`
I get:
`lncli version 0.6.0-beta commit=v0.6-beta-9-ga3c980b1e8fe12873ad364337b3379bb7b457cf4
`

Do my steps restarts LND node ?

**Comment by wpaulino** [comment] 2019-04-17 18:57
Yes, that should've done it.

Seeing `[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd.` implies that `lnd` does not recognize the `exportchanbackup` command. What's the output of `lnd --version`?

**Comment by SetasSan** [comment] 2019-04-17 18:58
executed:
`lnd --version
`
response:
`lnd version 0.6.0-beta commit=v0.6-beta-9-ga3c980b1e8fe12873ad364337b3379bb7b457cf4
`

**Comment by Roasbeef** [comment] 2019-04-18 02:21
The backup is created within your data directory automatically at `channels.backup` (where the rest of the chain data is stored). Your message implies that you haven't yet unlocked your wallet, or you possibly started with `--noseedbackup`. If that's true (you have no seed), then you should re-create your node as the backups are encrypted with a key derived from the seed. 

Closing as unable to reproduce. When the command works, it returns a JSON hex-encoded version of the backup.

**Closed by Roasbeef** 2019-04-18 02:21 UTC
