### ISSUE TITLE
output with 0 confirmation and a non existing transactionid

### ISSUE THREAD

**Issue by 2Fast2BCn** [lightningnetwork/lnd#6231] opened 2022-02-03 00:18 UTC
### Background

I have this strange situation with one of my outputs:

bos utxos: 0 confirmations with description 0:sweep for 2 days now

lncli wallet pendingsweeps: {"pending_sweeps": []}

lncli wallet listsweeps: contains the transactionid that cannot be found on the mempool.

lncli wallet publishtx <txnid>: [lncli] unexpected EOF

bos call getpendingchannels: (empty array)

bitcoin-cli getmempoolentry <txnid>: error code: -5 Transaction not in mempool

screenshots from thunderhub:

![image](https://user-images.githubusercontent.com/4680358/152259179-54e450ad-cd22-4ee1-a45c-b4d07900db5f.png)

![image](https://user-images.githubusercontent.com/4680358/152259216-558c83ad-ae5d-4fb3-8a9a-6ffd5b4d8619.png)

### Your environment

lnd version 0.14.1
Linux 5.4.0-91-generic #102-Ubuntu SMP x86_64 GNU/Linux
Satoshi:22.0.0

### Steps to reproduce

Not sure but the transaction seem to have happened when a channel was closed. The non existing transactionid can also be found in 'lncli wallet listsweeps'

### Expected behaviour

Currently I'm seeing an utxo that will never get confirmed

**Comment by guggero** [comment] 2022-02-03 08:50
Can you take a look at your logs, whether you find the invalid transaction being logged there? To find out if the input was spent elsewhere?
You can try turning on `reset-wallet-transactions=true` in your lnd config and restarting to make it re-scan the chain.

**Comment by 2Fast2BCn** [comment] 2022-02-03 09:57
So I rebooted with this new setting in lnd config but I think it didn't work
Last thing I saw in the logs was: [ERR] BTCN: Can't accept connection: accept tcp [::]:9735: accept4: too many open files

**Comment by guggero** [comment] 2022-02-03 10:04
Sounds like you're hitting some other constraints of your system. See https://github.com/lightningnetwork/lnd/issues/5330 for ways to fix that "too many open files" problem.

**Comment by 2Fast2BCn** [comment] 2022-02-03 10:56
OK reboot was done.
There is now significantly more utxos visible.
All the visible utxos have confirmations.
The overall balance is still the same as before the reboot.
The invalid transaction is gone from the list responded by `lncli wallet listsweeps`
Not sure if there is anything else you want me to do. I will run some accountings but I guess we can consider this fixed?

**Comment by guggero** [comment] 2022-02-03 13:26
It's possible this was caused by https://github.com/lightningnetwork/lnd/issues/5244. Or lnd missed a transaction because of a connection issue to bitcoind (caused by the too many open files probem)?
Anyway, since this seems to be resolved for you, I'm going to close the issue.

**Closed by guggero** 2022-02-03 13:26 UTC
Labels: P1

**Comment by 2Fast2BCn** [comment] 2022-02-07 08:08
There is still something strange.
Since this `reset-wallet-transactions=true` many utxos show with a balance running bos utxos and on thunderhub but when I actually look at a block explorer the balance in 0.
i.e.: https://www.blockchain.com/btc/address/bc1qk8m7fqwwc3m0vnn32nwmfcmcv207tls3cd9gpj

bos utxos response:
``  -
    outpoint:            ec4f03fce26aa712d3ddca5079daa91eef9236c823cf1b13740e2121900ea96f:0
    amount:              0.05084805
    confirmations:       4602
    address:             bc1qk8m7fqwwc3m0vnn32nwmfcmcv207tls3cd9gpj
    related_description: external
``

thunderhub:
![image](https://user-images.githubusercontent.com/4680358/152749009-494b4ae3-b4a9-483b-b0a4-66d32aa06630.png)

**Comment by guggero** [comment] 2022-02-07 13:22
Are those UTXOs in `lncli listunspent` as well?

**Comment by 2Fast2BCn** [comment] 2022-02-07 13:42
response from lncli listunspent:
````
                {
                        "address_type": 0,
                        "address": "bc1qk8m7fqwwc3m0vnn32nwmfcmcv207tls3cd9gpj",
                        "amount_sat": 5084805,
                        "pk_script": "0014b1f7e481cec476f64e7154ddb4e378629fe5fe11",
                        "outpoint": "<outputtext>:0",
                        "confirmations": 4627
                }
````

**Comment by guggero** [comment] 2022-02-07 13:51
Did you remove the `reset-wallet-transactions` setting after restarting? Are you sure everything is fully synced?

**Comment by 2Fast2BCn** [comment] 2022-02-07 14:41
Yes, I removed `reset-wallet-transactions` after the reboot.
I now updated my lnd to `v0.14.2-beta` and added `reset-wallet-transactions` back to lnd.conf.
After this new reboot nothing changed it's still in the list of `lncli listunspent`

**Comment by guggero** [comment] 2022-02-09 08:37
Are you sure your chain backend is fully synced to the latest block? Are you running a pruned node? Can you post your full config please?

**Comment by 2Fast2BCn** [comment] 2022-02-09 08:57
Yes chain is fully synced.
I am not running a pruned node.
lnd.conf

````
[Application Options]
accept-keysend=1
alias=allNice
allow-circular-route=1
color=#660000
coop-close-target-confs=1000
debuglevel=CNCT=debug,CRTR=debug,HSWC=debug,NTFN=debug,RPCS=debug
externalip=135.181.118.177:9735
gc-canceled-invoices-on-startup=1
gc-canceled-invoices-on-the-fly=1
ignore-historical-gossip-filters=1
listen=0.0.0.0:9735
max-channel-fee-allocation=1.0
max-cltv-expiry=5000
max-commit-fee-rate-anchors=100
maxpendingchannels=10
minchansize=1000000
rpclisten=0.0.0.0:10009
sync-freelist=1
stagger-initial-reconnect=1
tlsautorefresh=1
tlsdisableautofill=1
tlsextradomain=elsa.allnice.eu
wallet-unlock-password-file=/home/<redacted>/.lnd/wallet_password
###############################
#debug the hanging transaction#
###############################
#reset-wallet-transactions=true

[Bitcoin]
bitcoin.active=1
bitcoin.defaultchanconfs=2
bitcoin.feerate=5000
bitcoin.mainnet=1
bitcoin.minhtlc=1
bitcoin.node=bitcoind

[bitcoind]
bitcoind.rpcpass=<redacted>
bitcoind.rpcuser=<redacted>
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[bolt]
db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=48h

[protocol]
protocol.wumbo-channels=1

[routerrpc]
routerrpc.apriorihopprob=0.5
routerrpc.aprioriweight=0.75
routerrpc.attemptcost=10
routerrpc.attemptcostppm=10
routerrpc.maxmchistory=10000
routerrpc.minrtprob=0.005
routerrpc.penaltyhalflife=6h0m0s

[routing]
routing.strictgraphpruning=1

[tor]
tor.active=1
tor.v3=1
tor.streamisolation=false
tor.skip-proxy-for-clearnet-targets=true

[watchtower]
watchtower.active=true
watchtower.listen=0.0.0.0:9911
watchtower.externalip=135.181.118.177

[wtclient]
wtclient.active=true
````

**Comment by guggero** [comment] 2022-02-11 09:09
Thank you for the logs.
I noticed the following things:
 - The startup takes very long. From unlocking the node to getting to `Server listening on [::]:9735` it takes 20 minutes
 - Your node cannot accept incoming p2p connections because of `too many open files`. Take a look at https://github.com/lightningnetwork/lnd/issues/5330#issuecomment-848060558 on how to fix that
 - Your node does _a lot_ of chain rescans in the beginning. This can take a very long time, especially if your hard disk is slow (judging from the time the compaction takes, that might be the case).

So in general it looks like the node doesn't get enough resources (file handles and IOPS) to do its task properly. 
I'd suggest fixing the `too many open files` issue, then restarting without the `reset-wallet-transactions` and then just giving the node a few days to perform all rescans. Then check back at how it's doing.

**Comment by 2Fast2BCn** [comment] 2022-02-11 09:25
How many is enough I already increased it to `Max open files: 1048576`
So this in normal that 1M is not enough?

**Comment by guggero** [comment] 2022-02-11 11:20
I'm not sure what a good value is. I guess the default also depends on the distribution. For example Ubuntu seems to set this to `fs.file-max = 9223372036854775807` on my system (see `sysctl -a | grep file-max`).

Are you sure the limits are _applied_ correctly? Do you need to restart a service or the system perhaps? One million sounds like a lot, that should be enough I think. So maybe you need to set other system parameters as well?

**Comment by 2Fast2BCn** [comment] 2022-02-11 16:48
````
systemctl status lnd
● lnd.service
     Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-02-10 14:59:40 CET; 1 day 2h ago
   Main PID: 3069 (lnd)
      Tasks: 20 (limit: 76954)
     Memory: 1.0G
     CGroup: /system.slice/lnd.service
             └─3069 /home/kobe/go/bin/lnd
````

````
cat /proc/3069/limits | grep files
Max open files            1024                 1048576              files
````

The following command output logged in as the user running lnd
````
ulimit -Hn
1048576
````

````
sudo sysctl -a | grep file-max
fs.file-max = 5120000
````

````
cat /etc/systemd/system.conf | grep NOFILE
DefaultLimitNOFILE=1024:5120000
````

So as far as I can see the 1 million is accurate? I honestly don't know where else to look.

**Comment by guggero** [comment] 2022-02-14 09:10
Everything looks good, yes. I honestly don't know why those settings wouldn't take effect. I assume you restarted everything that is needed for the settings to be activated? Probably doesn't require a full system restart but maybe a systemd service or something like that?
Or do you also need to restart the `lnd.service` from systemd?

The only thing I can say for certain is that as long as you see any "too many open files" errors in your log, something isn't right.

**Comment by 2Fast2BCn** [comment] 2022-02-14 09:21
I even did a complete system reboot. I'm starting to wonder if lnd does something strange causing it to actually open 1M files. But I seem to be the only one affected so that makes it very unlikely.

**Comment by guggero** [comment] 2022-02-14 09:42
It could also be a weird combination of a lot of open channels, a watchtower running, software like Thunderhub connecting which makes your node use up a lot of file descriptors. It could also be a bug somewhere. Maybe there is a way to find out what descriptors are being used? Perhaps there's a "leak" somewhere?

**Comment by 2Fast2BCn** [comment] 2022-03-18 09:05
An update on this for whoever might be facing similar problem with `too many open files` 
The problem was fixed by increasing the soft limit.
So new configuration would be `DefaultLimitNOFILE=1024000:5120000`
Thanks to ln2me for pointing that out to me!!!

I still have to do another test rebooting with `reset-wallet-transactions`.
