### ISSUE TITLE
Accounting: Listpayments fee_msat missing

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#2105] opened 2018-10-26 18:52 UTC
### Background
We show msat for values sent but do not for fees paid.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by wpaulino** [comment] 2018-10-26 20:07
Closing as duplicate of #1359.

**Closed by wpaulino** 2018-10-26 20:07 UTC
Labels: enhancement, feature request, payments, rpc
