### ISSUE TITLE
[bug]: total_fees field is always 0 for channel close transactions

### ISSUE THREAD

**Issue by michaelWuensch** [lightningnetwork/lnd#7630] opened 2023-04-23 16:39 UTC
### Background

I want to display the fee you payed for closing a channel (if you were the channel initiator) to the user.
But I am unable to access this information using the gRPC interface.
"GetTransactions" returns the relevant transactions, but for closing transactions the "total_fees" field is always 0 no matter who opened the channel.
The same applies for force closing tx, I would have to dive deeper into it though to make exact statements on force close cases.

### Your environment

* version of `lnd` 0.15.5-beta
* which operating system (`uname -a` on *Nix) Umbrel
* version of `btcd`, `bitcoind`, or other backend Bitcoin Core 24.0
* any other relevant environment details

### Steps to reproduce

1. Open a channel
2. Cooperatively close it
3. Get the transaction and check for total_fees

### Expected behaviour

It should return the fee of the on-chain transaction, regardless of who the channel initiator is.

### Actual behaviour

It returns 0 for the on-chain fee.

**Comment by alexbosworth** [comment] 2023-04-23 17:12
related issue: https://github.com/lightningnetwork/lnd/issues/2936 ?

**Comment by guggero** [comment] 2023-05-08 07:35
Duplicate of https://github.com/lightningnetwork/lnd/issues/2936.

**Closed by guggero** 2023-05-08 07:35 UTC
Labels: enhancement, channel closing, needs triage
