### ISSUE TITLE
OpenChannel should accept both NodePubKey and NodePubKeyString

### ISSUE THREAD

**Issue by torkelrogstad** [lightningnetwork/lnd#4072] opened 2020-03-11 13:45 UTC
### Background

`lnrpc.LightningServer.OpenChannel` returns an error if `NodePubKeyString` is set instead of `NodePubKey`. I'd expect this to not happen. 

### Your environment

* version of `lnd`: 0.8.2
* which operating system (`uname -a` on *Nix): 
  ```
  Linux 45477969dea4 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 Linux
  ```

### Steps to reproduce

Call `lnrpc.LightningServer.OpenChannel` with `NodePubKeyString` set instead of `NodePubKey`

### Expected behaviour

Setting `NodePubkey` and `NodePubKeyString` should behave the same. 

### Actual behaviour

I get an error `NodePubKey is not set`.

**Comment by wpaulino** [comment] 2020-03-11 16:38
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/4041.

**Closed by wpaulino** 2020-03-11 16:38 UTC
