### ISSUE TITLE
Remote force closing should deactivate channel immediately

### ISSUE THREAD

**Issue by bjarnemagnussen** [lightningnetwork/lnd#5915] opened 2021-11-01 13:08 UTC
### Background

When the remote peer force closes a channel on us, I believe LND could register the unconfirmed force closure transaction and deactivate the channel immediately.

### Your environment

* version of `lnd`: 0.13 + master

### Steps to reproduce

Have an active channel and let the remote force close it. While the force closing transaction is still unconfirmed the following behaviour is experienced.

### Expected behaviour

LND should immediately after receiving the force closing transaction via its backend deactivate the channel. This is also the behaviour of coop-closures; granted since both nodes will actually create the coop close transaction and add it to its transaction store independently before broadcasting.

### Actual behaviour

The channel stays active, even though the remote has broadcast the force closing transaction making the channel unusable.

**Comment by Crypt-iQ** [comment] 2021-11-01 14:29
It's unconfirmed and may not actually confirm, this is intentional

**Comment by bjarnemagnussen** [comment] 2021-11-01 14:37
But since the remote that initiated the force close has disabled the channel on its side, my node will still try to send payments via that channel and have its HTLCs stuck with state IN_FLIGHT until the forced close transaction confirms. 

I also don't see how in general this should be handled differently from an unconfirmed coop channel closure, which disables the channel immediately while the transaction is till unconfirmed.

**Comment by Crypt-iQ** [comment] 2021-11-01 17:49
The HTLCs won't be on a commitment transaction so there aren't limbo funds. We'd have to change the way our `chainntnfs` subsystem works to notify on unconfirmed transactions. IMO, it doesn't seem worth the effort and changing chain-handling is inherently risky

**Comment by Crypt-iQ** [comment] 2021-11-01 17:52
> I also don't see how in general this should be handled differently from an unconfirmed coop channel closure, which disables the channel immediately while the transaction is till unconfirmed.

We should disable the channel if *we* locally broadcast any closing (coop/force) tx since accepting more state updates can be dangerous.

**Comment by Roasbeef** [comment] 2021-11-01 22:38
> I also don't see how in general this should be handled differently from an unconfirmed coop channel closure, which disables the channel immediately while the transaction is till unconfirmed.

The difference is that both sides are involved in a co-op close, while only one side is involved in a force close. If you hang up, then broadcast, I have no idea what happend until it finally hits the chain. 

> We should disable the channel if we locally broadcast any closing (coop/force) tx since accepting more state updates can be dangerous.

Correct that we _do_ do this as is. 

> But since the remote that initiated the force close has disabled the channel on its side, my node will still try to send payments via that channel and have its HTLCs stuck with state IN_FLIGHT until the forced close transaction confirms.

The HTLCs will never actually be locked in, and will eventually be cancelled back by the mailbox. 

Protocol level enhancements such as soft warnings/error help out here.

**Closed by Roasbeef** 2021-11-01 22:38 UTC

**Comment by bjarnemagnussen** [comment] 2021-11-02 09:36
> [...] in a force close. If you hang up, then broadcast, I have no idea what happend until it finally hits the chain.

But we do know that it could only have been the remote peer that tries to force close this channel when we see the force close tx in the mempool. Although our funds are not at risk we could similar to when the remote peer is offline for 20(?) minutes disable the channel as it is fruitless to try to use it. 

> The HTLCs will never actually be locked in, and will eventually be cancelled back by the mailbox.

It seems to first cancel when the force close transaction confirms, or of course the HTLC expiration_height is reached in which case the local node itself force-closes the channel (but also all the channels that may have been used if the node forwarded a payment will be force closed of course). 

Maybe if the local node cannot disable the channel when it sees a force-close of the channel in the mempool, instead a "nice" remote LND node could return an error if the node still tries to send a HTLC on the force-closing channel?
