### ISSUE TITLE
[bug]: Instant force close event upon 0 conf acceptance and routing JIT payment

### ISSUE THREAD

**Issue by tony-voltage** [lightningnetwork/lnd#7410] opened 2023-02-15 21:22 UTC
### Background

When I open a 0 conf channel between CLN->LND, I wait on the CLN side until the CHANNELD_READY event before forwarding a just in time payment. 

When I forward it quick enough, LND thinks there is an issue and force closes the channel. If I wait 5 seconds after CHANNELD_READY, LND is okay. I do not have this problem going from CLN->CLN.

### Your environment

* version of `lnd`: v0.15.5
* which operating system (`uname -a` on *Nix): Mac OS m1
* version of `btcd`, `bitcoind`, or other backend: bitcoind
* any other relevant environment details: LND node is on Polar.

### Steps to reproduce

Open a zero conf channel from CLN to LND and use the LND acceptor to accept it as 0 conf. Route a payment as soon as the 0 conf is accepted.

### Expected behaviour

It should forward the payment and not force close the channel.

### Actual behaviour

It does not forward the payment and it force closes the channel.

### Logs

Without waiting 5 seconds
```
2023-02-15 20:30:05.446 [INF] FNDG: Recv'd fundingRequest(amt=0.0002 BTC, push=0 mSAT, delay=6, pendingId=1b6f1057aedea22aa1d851768d0f5edfcbafcce091b7c467a09dc414abe943a9) from peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be)
2023-02-15 20:30:05.446 [INF] CHFD: Performing funding tx coin selection using 0 sat/kw as fee rate
2023-02-15 20:30:05.562 [INF] FNDG: Requiring 0 confirmations for pendingChan(1b6f1057aedea22aa1d851768d0f5edfcbafcce091b7c467a09dc414abe943a9): amt=0.0002 BTC, push_amt=0 mSAT, committype=tweakless, upfrontShutdown=
2023-02-15 20:30:05.563 [INF] FNDG: Sending fundingResp for pending_id(1b6f1057aedea22aa1d851768d0f5edfcbafcce091b7c467a09dc414abe943a9)
2023-02-15 20:30:05.572 [INF] FNDG: completing pending_id(1b6f1057aedea22aa1d851768d0f5edfcbafcce091b7c467a09dc414abe943a9) with ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0)
2023-02-15 20:30:05.593 [INF] FNDG: sending FundingSigned for pending_id(1b6f1057aedea22aa1d851768d0f5edfcbafcce091b7c467a09dc414abe943a9) over ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0)
2023-02-15 20:30:05.593 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0)
2023-02-15 20:30:05.602 [INF] CNCT: ChannelArbitrator(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=426
2023-02-15 20:30:05.602 [INF] NTFN: New spend subscription: spend_id=3, outpoint=73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0, script=0 1b85573277a93bcba00259f3a2442698d6682b8f2d04e4151d5503a23a496a28, height_hint=426
2023-02-15 20:30:05.607 [INF] NTFN: Dispatching historical spend rescan for outpoint=73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0, script=0 1b85573277a93bcba00259f3a2442698d6682b8f2d04e4151d5503a23a496a28, start=426, end=426
2023-02-15 20:30:05.639 [INF] CNCT: Close observer for ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0) active
2023-02-15 20:30:05.639 [INF] CHBU: Updating on-disk multi SCB backup: num_old_chans=0, num_new_chans=1
2023-02-15 20:30:05.658 [INF] CHBU: Updating backup file at /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:30:05.670 [INF] CHBU: Swapping old multi backup file from /home/lnd/.lnd/data/chain/bitcoin/regtest/temp-dont-use.backup to /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:30:05.675 [INF] FNDG: Peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be) is online, sending FundingLocked for ChannelID(57972abdb46418cb0c63c1dc0efc05118a0e705ff62382e5716b815bf59daa73)
2023-02-15 20:30:05.691 [INF] CHBU: Updating on-disk multi SCB backup: num_old_chans=1, num_new_chans=1
2023-02-15 20:30:05.703 [INF] PEER: Peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be): New channel active ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0) with peer
2023-02-15 20:30:05.703 [INF] HSWC: ChannelLink(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): starting
2023-02-15 20:30:05.704 [WRN] CHBU: Replacing disk backup for ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0) w/ newer version
2023-02-15 20:30:05.707 [INF] HSWC: Trimming open circuits for chan_id=16000000:0:2, start_htlc_id=0
2023-02-15 20:30:05.714 [INF] HSWC: Adding live link chan_id=57972abdb46418cb0c63c1dc0efc05118a0e705ff62382e5716b815bf59daa73, short_chan_id=16000000:0:2
2023-02-15 20:30:05.714 [INF] HSWC: ChannelLink(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): HTLC manager started, bandwidth=0 mSAT
2023-02-15 20:30:05.733 [WRN] LNWL: ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): empty commit sig message received
2023-02-15 20:30:05.714 [INF] CHBU: Updating backup file at /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:30:05.714 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0)
2023-02-15 20:30:05.738 [ERR] HSWC: ChannelLink(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): failing link: ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): unable to accept new commitment: number of htlc sig mismatch. Expected 0 sigs, got 1 with error: invalid commitment
2023-02-15 20:30:05.756 [ERR] HSWC: ChannelLink(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): link failed, exiting htlcManager
2023-02-15 20:30:05.758 [INF] HSWC: ChannelLink(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): exited
2023-02-15 20:30:05.756 [INF] HSWC: ChannelLink(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): stopping
2023-02-15 20:30:05.758 [INF] CHBU: Swapping old multi backup file from /home/lnd/.lnd/data/chain/bitcoin/regtest/temp-dont-use.backup to /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:30:05.760 [INF] NTFN: New confirmation subscription: conf_id=4, txid=73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757, num_confs=6 height_hint=426
2023-02-15 20:30:05.766 [INF] HSWC: Removing channel link with ChannelID(57972abdb46418cb0c63c1dc0efc05118a0e705ff62382e5716b815bf59daa73)
2023-02-15 20:30:05.778 [WRN] PEER: Peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be): Force closing link(16000000:0:2)
2023-02-15 20:30:05.771 [INF] FNDG: Waiting for funding tx (73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757) to reach 6 confirmations
2023-02-15 20:30:05.781 [INF] CNCT: Attempting to force close ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0)
2023-02-15 20:30:05.785 [INF] NANN: Announcing channel(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0) disabled [requested]
2023-02-15 20:30:05.821 [INF] CNCT: ChannelArbitrator(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): force closing chan
2023-02-15 20:30:05.857 [INF] CNCT: Broadcasting force close transaction 1ff5b849e6b5c839b7ee71635f9596e81ab8d0d693a628f9819102b9a09ce635, ChannelPoint(73aa9df55b816b71e58223f65f700e8a1105fc0edcc1630ccb1864b4bd2a9757:0): (*wire.MsgTx)(0x400216cc00)({
```

Waiting 5 seconds:

```
2023-02-15 20:46:40.458 [INF] FNDG: Recv'd fundingRequest(amt=0.0002 BTC, push=0 mSAT, delay=6, pendingId=921e282503b415c9f3c833ae9629407c7bb4c848c3b9bfa95fd39c3bf4527cdd) from peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be)
2023-02-15 20:46:40.458 [INF] CHFD: Performing funding tx coin selection using 0 sat/kw as fee rate
2023-02-15 20:46:40.581 [INF] FNDG: Requiring 0 confirmations for pendingChan(921e282503b415c9f3c833ae9629407c7bb4c848c3b9bfa95fd39c3bf4527cdd): amt=0.0002 BTC, push_amt=0 mSAT, committype=tweakless, upfrontShutdown=
2023-02-15 20:46:40.582 [INF] FNDG: Sending fundingResp for pending_id(921e282503b415c9f3c833ae9629407c7bb4c848c3b9bfa95fd39c3bf4527cdd)
2023-02-15 20:46:40.591 [INF] FNDG: completing pending_id(921e282503b415c9f3c833ae9629407c7bb4c848c3b9bfa95fd39c3bf4527cdd) with ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0)
2023-02-15 20:46:40.613 [INF] FNDG: sending FundingSigned for pending_id(921e282503b415c9f3c833ae9629407c7bb4c848c3b9bfa95fd39c3bf4527cdd) over ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0)
2023-02-15 20:46:40.614 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0)
2023-02-15 20:46:40.621 [INF] CNCT: ChannelArbitrator(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=632
2023-02-15 20:46:40.621 [INF] NTFN: New spend subscription: spend_id=4, outpoint=f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0, script=0 fe087332f4db2728c0b8f3e6df68d37394d43e6d7c0d8da1db39a919c4e5d969, height_hint=632
2023-02-15 20:46:40.628 [INF] NTFN: Dispatching historical spend rescan for outpoint=f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0, script=0 fe087332f4db2728c0b8f3e6df68d37394d43e6d7c0d8da1db39a919c4e5d969, start=632, end=632
2023-02-15 20:46:40.639 [INF] CNCT: Close observer for ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0) active
2023-02-15 20:46:40.639 [INF] CHBU: Updating on-disk multi SCB backup: num_old_chans=0, num_new_chans=1
2023-02-15 20:46:40.643 [INF] NTFN: Historical spend dispatch finished for request outpoint=f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0, script=0 fe087332f4db2728c0b8f3e6df68d37394d43e6d7c0d8da1db39a919c4e5d969 (start=632 end=632) with details: <nil>
2023-02-15 20:46:40.653 [INF] CHBU: Updating backup file at /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:46:40.661 [INF] CHBU: Swapping old multi backup file from /home/lnd/.lnd/data/chain/bitcoin/regtest/temp-dont-use.backup to /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:46:40.686 [INF] CHBU: Updating on-disk multi SCB backup: num_old_chans=1, num_new_chans=1
2023-02-15 20:46:40.692 [INF] FNDG: Peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be) is online, sending FundingLocked for ChannelID(faf93408ed3ceae113a7b92abf55b9c8142e858407db49a899e9c3cd24c119f9)
2023-02-15 20:46:40.697 [WRN] CHBU: Replacing disk backup for ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0) w/ newer version
2023-02-15 20:46:40.700 [INF] CHBU: Updating backup file at /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:46:40.710 [INF] PEER: Peer(03e24f68ea4795bbebc27c8956058df42c416195977a8627aabc52d69cf93d38be): New channel active ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0) with peer
2023-02-15 20:46:40.710 [INF] HSWC: ChannelLink(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0): starting
2023-02-15 20:46:40.712 [INF] CHBU: Swapping old multi backup file from /home/lnd/.lnd/data/chain/bitcoin/regtest/temp-dont-use.backup to /home/lnd/.lnd/data/chain/bitcoin/regtest/channel.backup
2023-02-15 20:46:40.714 [INF] HSWC: Trimming open circuits for chan_id=16000000:0:3, start_htlc_id=0
2023-02-15 20:46:40.724 [INF] HSWC: Adding live link chan_id=faf93408ed3ceae113a7b92abf55b9c8142e858407db49a899e9c3cd24c119f9, short_chan_id=16000000:0:3
2023-02-15 20:46:40.724 [INF] HSWC: ChannelLink(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0): HTLC manager started, bandwidth=0 mSAT
2023-02-15 20:46:40.724 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0)
2023-02-15 20:46:40.741 [INF] NTFN: New confirmation subscription: conf_id=5, txid=f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa, num_confs=6 height_hint=632
2023-02-15 20:46:40.742 [INF] FNDG: Waiting for funding tx (f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa) to reach 6 confirmations
2023-02-15 20:46:41.024 [INF] DISC: Broadcasting 2 new announcements in 1 sub batches
2023-02-15 20:46:45.707 [WRN] DISC: Update announcement for short_chan_id(209711627592148668), is premature: advertises height 190731, only height 632 is known
2023-02-15 20:46:45.825 [INF] HSWC: ChannelLink(f919c124cdc3e999a849db0784852e14c8b955bf2ab9a713e1ea3ced0834f9fa:0): settling htlc 5f583e22f7ace4f5931445c65fd393a9cf559d831557f2b58acd6f1a8ebf7b85 as exit hop
2023-02-15 20:47:21.748 [INF] CRTR: Processed channels=2 updates=3 nodes=2 in last 16m9.972912196s
```

**Comment by Crypt-iQ** [comment] 2023-02-15 21:23
dupe of #7401

**Closed by Crypt-iQ** 2023-02-15 21:23 UTC
Labels: bug, needs triage
