### ISSUE TITLE
lnd sends announcement_signatures before reestablish_channel

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lnd#2940] opened 2019-04-12 01:12 UTC
### Background

You're supposed to send reestablish first, and also wait for the reply.

https://github.com/ElementsProject/lightning/issues/2559

### Your environment

The source was Pierre Rochard's node, which he tells me is 0.5.2-99-beta commit=queue/v1.0.1-109-g9f6a1403e9773ba97ec0e9fdee3b654789970d3a

### Steps to reproduce

Take your c-lightning node (minus above fix) up and down several times while lnd connects with a relatively fresh channel.

### Expected behaviour

Delay other channel msgs until REESTABLISH sent and received.

### Actual behaviour

Rusty writes nasty code in c-lightning to defer unexpected packets.  We had an earlier issue with funding_locked, but I had special cased that.  Now I just defer all weird stuff.

**Comment by cfromknecht** [comment] 2019-04-12 02:22
Hmm, BOLT 2 says that BOLT 7 messages are not required to wait for ChannelReestablish:

> [Note that messages described in BOLT #7 are independent of particular channels; their transmission requirements are covered there, and besides being transmitted after init (as all messages are), they are independent of requirements here.](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#message-retransmission)

and BOLT 7 does not include anything about ChannelReestablish in the retransmission requirements for AnnouncementSignatures.

I assume then, that this the issue in regards to delaying BOLT 7 messages only if:
 1. They pertain to a channel with the current peer, and
 2. We have not sent ChannelReestablish for that channel?

If I understand correctly, what is the benefit of being able to send info about everyone else's channels immediately, but withhold relevant gossip info from your channel partner until after ChannelReestablish?

**Comment by Roasbeef** [comment] 2019-04-12 02:26
Closing as a duplicate of #2555.

**Closed by Roasbeef** 2019-04-12 02:26 UTC
