### ISSUE TITLE
no trace of a "forced closed" channel in lnd via lncli

### ISSUE THREAD

**Issue by emplexity** [lightningnetwork/lnd#5167] opened 2021-04-03 13:48 UTC
### Background
I "forced closed" a lightning channel 12 days ago from my lnd 0.11 node, which was opened by a third party 6 weeks ago. 

The command "lncli closechannel --funding_txid xxx --output_index 0 --force" replied with a "closing_txid". The closing txid was confirmed within an hour according a bitcoin blockchain explorer. 

The commands "lncli closedchannels, list channels, pendingchannels" have no trace of the channel I forced closed. 

The balance of the channel on my side is still missing from the wallet. 

The log file of lnd shows traces of the history of the forced closed channel. See attached the log file "grep'ed" with the channel point of the forced closed channel. It suggests that lnd continues to attempt to settle the force closed channel and  is aware of the status of this forced closed channel.
[nohupae914.txt](https://github.com/lightningnetwork/lnd/files/6252633/nohupae914.txt)

### Your environment

* version of `lnd` "version": "0.11.99-beta commit=v0.11.0-beta-305-gd26001a69a27aa025c7db497315c2aaf89444f21"
* which operating system ubuntu 16.04
* version of bitcoind "version": 200000,

### Steps to reproduce

force close a channel

### Expected behaviour

The lifecycle of the forced channels should be fully traceable at all times via lncli in the channel history of lnd, with clear indication of the time delay (time lock?) within which the user may expect the settlement of the forced closed channel.

### Actual behaviour

There is no info available via lncli on the status of forced closed channel from when it is forced closed until it is settled and on the delay that the user may expect to recover her/his balance of the forced closed channel.

**Comment by guggero** [comment] 2021-04-05 08:25
This is definitely not the expected behavior. The channel should stay in the `lncli pendingchannels` until it's fully resolved and should then move to `lncli closedchannels`. From the logs it looks like it's still being worked on. Can you please try to upgrade `lnd` to `v0.12.1-beta` and check `lncli pendingchannels` again?

**Comment by wpaulino** [comment] 2021-04-05 22:07
If you look at the channel on-chain, it seems to have been resolved already. Since you force closed, then your funds took the delayed path: https://blockstream.info/tx/89ac71b4af3ef8e6b3113d9f9a980e092ced8513249c2ebc49fc535d20de2c47?input:0&expand.

**Comment by emplexity** [comment] 2021-04-06 16:02
@guggero & @wpaulino: Thanks for your feedback, indeed the force closure of the channel was resolved in @ block 677850 (2021-04-05 11:23:24 GMT +2).
No material anymore in the node to further check if the issue reported is resolved by an upgrade.
Will do at the next opportunity and will report.

**Comment by guggero** [comment] 2021-04-06 17:42
Okay, good to know it looks to be resolved.

Closing for now, feel free to reopen if it happens again.

**Closed by guggero** 2021-04-06 17:42 UTC
