### ISSUE TITLE
commitment transaction dips peer below chan reserve

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#3300] opened 2019-07-11 14:43 UTC
### Background

A BLW user tried to send a `~1 096 000 SAT` payment, it took a few attempts and eventually got one of channels closed remotely with `Invalid commitment` message, remote LND peer has this in logs:

> ChannelLink(578797:1724:0) Failing link: ChannelPoint(0f1ff9b7236acdc017246f448c6b2a133e5cea30879852a439288e7c5d15289f:0): unable to accept new commitment: commitment transaction dips peer below chan reserve

Here's how a channel looks now: 

```
{
            "channel": {
                "remote_node_pub": "02fe09a0d41dcb810877947519ada9dbcd0aefb36621f45cf23e61eaa0e35a4a03",
                "channel_point": "0f1ff9b7236acdc017246f448c6b2a133e5cea30879852a439288e7c5d15289f:0",
                "capacity": "4000000",
                "local_balance": "42089",
                "remote_balance": "0"
            },
            "closing_txid": "aed37b840f5e80fecbeae5396c38ac0f245ecf34aafa8c2bf50f0bededc2e2e4",
            "limbo_balance": "42089",
            "maturity_height": 586935,
            "blocks_til_maturity": 2007,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
```

`commitment transaction dips peer below chan reserve` sounds strange here since a single ~1M SAT payment could not in principle cause that. BLW channel data is lost by now and I guess it's not possible to extract a failed remote commit from LND side (?). I'm not yet sure on which side the problem is but submitting an issue in case this sounds familiar.

### Your environment

* 0.7.0-beta commit=v0.7.0-beta-rc3

**Comment by Roasbeef** [comment] 2019-07-11 23:10
If a large portion of the channel was allocated to fees (I think BLW was the initiator in this case?), then it's possible that the 1 mil sat payment started to eat into the reserve, or if there were several pending HTLCs at the time the payment was attempted.

**Comment by wpaulino** [comment] 2019-07-11 23:13
Doesn't seem like that was the case here looking at the commitment transaction broadcast.

**Comment by btcontract** [comment] 2019-07-12 04:31
LND was the channel funder, there was a single in-flight payment attempt. I was also thinking about fee but BLW would have taken that into account before attempting to send and 3+m fee send unrealistic.

**Comment by btcontract** [comment] 2019-07-12 04:40
Plus, published commitment tx should have had that huge fee if it was the case?

**Comment by LNBIG-COM** [comment] 2019-07-12 11:40
Hello!

This error was catched by me. I am not programmer of Golang but i understand sources. I think i know where this error occur.

Now i am here at commit: f0692769704dc74f98b2a83c79c03c442d8fed57

I think error was here: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3747

Because:

1. Channel was created by LND
2. After i filled it up to maximum from other BLW wallet some days ago before next transaction
3. When the error occured i tried to send a next payment

So initiator was LND. The condition was be here:

    if ourBalance < ourInitialBalance &&
            ourBalance < lnwire.NewMSatFromSatoshis(
                    lc.localChanCfg.ChanReserve) {
            return ErrBelowChanReserve
    }

Please to see code here: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3727
And please see the balance of limbo: `"limbo_balance": "42089"`

This limbo balance is close to 1/100 of reserve of channel.

I think:

1. The commitFeeMsat was higher then 2089 sats (https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3727) (a fees are higher)
2. It decreased `ourBalance` below 40000 sats here: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3729
3. Error was throwed here: https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3750 because the condition `ourBalance < ourInitialBalance && ourBalance < lnwire.NewMSatFromSatoshis(lc.localChanCfg.ChanReserve)` was true

**Comment by LNBIG-COM** [comment] 2019-07-12 11:56
And the `validateCommitmentSanity` called before new commitment checks

https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L4065

But new commitment would bring new balance to LND side so a closing channel from LND looks weird

**Comment by Roasbeef** [comment] 2019-07-12 20:27
> But new commitment would bring new balance to LND side so a closing channel from LND looks weird


Would it? From my reading above, is it correct that at a balance of `42089 SAT`, you tried to send an _outbound_ payment?

**Comment by btcontract** [comment] 2019-07-13 05:11
I think what @LNBIG-COM means is:

- earlier channel was filled to the max on BLW side so LND only had `42089 SAT` (probably reserve + commit fee so receivable amount is 0).
- then fees got higher, at this moment LND was not able to send `update_fee` so supposedy it was doing nothing.
- on reciving a commit LND somehow used an new fee which was higher (not sure how viable this assumption is, an old fee should have been used or else signature check would have failed).

**Comment by LNBIG-COM** [comment] 2019-07-16 17:54
> Would it? From my reading above, is it correct that at a balance of 42089 SAT, you tried to send an outbound payment?

No, there was a following channel:

````
BLW <***************--> (i) LND
````

Here `(i)` - initiator
`****` - balance at BLW side

The BLW wanted to send payment further through LND thus the BLW sent funds to the LND side. But LND in this moment to be closing a channel. I tried to describe everything above in detail, even pointing out the places in the source code where it happened. But you apparently are very busy to get into the process.

**Comment by Roasbeef** [comment] 2019-07-16 23:39
> on reciving a commit LND somehow used a new fee which was higher (not sure how viable this assumption is, an old fee should have been used or else signature check would have failed).

So BLW didn't send a fee update? Also to confirm BLW was the one that sent the payment as well? If BLW was the initiator, then a fee update wouldn't case the `lnd` balance to go down.

**Comment by Roasbeef** [comment] 2019-07-16 23:41
> I tried to describe everything above in detail, even pointing out the places in the source code where it happened. But you apparently are very busy to carefully examine the situation :(

The above information atm is insufficient, as it's still unclear exactly what happened. We also haven't been able to reproduce this on our end. 

But if `lnd` had `42089 SAT`, and attempted to send a new payment, then it follows that we would then be forced to dip into our reserve. If a fee update happend _after_ the HTLC was sent, then it also follows that we would allow the HTLC to be added, but then reject it once we dipped below the commitment.

**Comment by btcontract** [comment] 2019-07-17 03:45
LND was an initiator in this channel and payment was sent by BLW.

**Comment by btcontract** [comment] 2019-07-18 05:08
I have suspicions this could be the cause: https://github.com/ACINQ/eclair/issues/1081
It seems like LND was complaining about it's own balance dipping below reserve, not remove BLW balance.

**Comment by btcontract** [comment] 2019-07-18 13:14
Just wondering: if I'm correct in my above assumption then this bug is on BLW side, is this something else?

**Comment by halseth** [comment] 2019-07-19 10:17
@btcontract That sounds correct. When offering an HTLC, the sender must check that the receiver's balance won't become too low.

In this case it looks like BLW sends an HTLC which dips LND below the reserve, which is a protocol violation (hence why lnd closes the channel). The latest acked fee_update will be used to determine the fee. Does that sound about right?

**Comment by btcontract** [comment] 2019-07-19 10:34
@halseth yes, I was confused since `BUG` was added possibly implying something else was discovered on LND side.

**Comment by halseth** [comment] 2019-07-19 10:36
Cool, just labeled it to keep track of it in case it was on the LND side. Will close this for now then.

**Closed by halseth** 2019-07-19 10:36 UTC
Labels: HTLC, bug, commitments
