### ISSUE TITLE
memory usage depends on debuglevel

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#1092] opened 2018-04-13 15:12 UTC
### Background

My lnd is working with debuglevel set to "trace". i have tried with "info" and --debuglevel=CMGR=debug

Both cases ends with lnd using crazy amount of memory. My rasb just freezes for like 10-20+ min 
because its out of RAM and start swap proccess.

So im suspecting that there are some kinds of memory leaks when using any other debuglevel than trace.

### Your environment

* version of `lnd`: lncli version 0.4.1 commit=bc029b9cd4c15ff974c4e232fb4a606e9fea4f8c
* which operating system (`uname -a` on *Nix): Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitoin core 15.1

### Steps to reproduce

Run with --debuglevel=info or --debuglevel=CMGR=debug - mesure memory usage
and then run with ----debuglevel=trace and compare memory usage.

Maybe on sth with more that 1GB  RAM you wont have problem. But on rasbp 3 it is strongly felt.

### Expected behaviour

Same memory usage as when it runs with debuglevel=trace

### Actual behaviour

Taking all available memory and using swap.

**Comment by Roasbeef** [comment] 2018-04-13 20:53
> My lnd is working with debuglevel set to "trace"

Trace simply logs nearly _everything_. If you're running on `trace`, I would set `PEER=debug`. Otherwise, you'll get a massive firehouse of every message we send out on the wire. I run a node (along with several other daemons) with 1GB of RAM and have no issues.

**Comment by Roasbeef** [comment] 2018-04-13 20:55
> Both cases ends with lnd using crazy amount of memory.

How much memory are talking here? I'm not sure if there're some issues with the rasp pi builds people are trying to use. I run routinely with < 1GB and no issues. If you're running _both_ bitcoind and `lnd` on the same machine, would note that `bitcoind` itself can be very resource draining itself.

**Comment by halfik** [comment] 2018-04-14 09:31
Thats what is funny here. With trace that is login much more than any other debuglevel it workin. With any other mode after lnd connects with peers and start receiving data its done. Can mesure how much ram and swap it takes becouse swap proccess it taking all cpu and can do anyting on pi except disconecting is from power source.

With trace its take up to 450Mb of ram when initiali syncing and up to 3cpu.
With any other mode it must take little more + swap.  And swap proccess is whats killing my rasp.

**Comment by halfik** [comment] 2018-04-14 14:25
Ok im debuging this with Offer Markovich.
Here is thing i notice:

If i delete log files i can run lnd with any debuglevel with out swap proccess kicking in.
But for some reason any other debuglevel than trace ends with lnd killed, dunno by what?

http://wklej.org/id/3410123/

**Comment by halfik** [comment] 2018-04-15 10:53
Ok in my case problem was tiny swap file.
Markovich figure that out. When using trace debulevel GC kicks in more often so lnd is using a lot less memory.

To compare this: 
1. debuglevel(trace) =>  my system uses like 450-650Mb of memory when syncing
2. debuglevel(CMGR=debug) => 1.1-1.2Gb of memory when syncing

After sync is done memory usage in both cases is pretty much the same.

**Comment by halfik** [comment] 2018-04-15 21:35
@Roasbeef http://wklej.org/id/3411010/
Can look up for data when was running with trace debuglevel it you need?

**Comment by Roasbeef** [comment] 2018-04-15 21:38
There's no need. I'm not sure there's a real issue here, you're running both `bitcoind` and `lnd` on a single pi. It's expected that memory would be a bit tight. In my experimentation, I have a few hundred megs free with a similar set up.

**Comment by halfik** [comment] 2018-04-15 21:43
@Roasbeef but its kinda odd that there is like 600Mb of data in ram that GC is collecting when debuglevel is set to trace. It GC clean this up, why so many data is in ram when not needed?

**Comment by Roasbeef** [comment] 2018-04-25 20:26
Closing as unable to reproduce on similar hardware.

**Closed by Roasbeef** 2018-04-25 20:26 UTC
