### ISSUE TITLE
BOLT7: LND send channel_update before receiving funding_locked from peer

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lnd#3651] opened 2019-10-30 11:27 UTC
### Background

LND send `channel_update` before receiving `funding_locked` from peer.

https://github.com/lightningnetwork/lightning-rfc/blob/3d60581a7a39265186f318636f36920dbc5012e7/07-routing-gossip.md#requirements-3

```
The origin node:
* MUST NOT send a created channel_update before funding_locked has been received.
```

### Your environment

* version of `lnd`
commit a8f077a8417011e2b816002ba4c4f777fb511999
lnd version 0.8.0-beta commit=v0.8.0-beta-78-ga8f077a8417011e2b816002ba4c4f777fb511999

* which operating system (`uname -a` on *Nix)
Linux nayuta-server 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65

* regtest

### Steps to reproduce

1. `connect` and `openchannel` (minimum_depth=1)
2. `bitcoin-cli generatetoaddress 1 SOMETHING_ADDR`

### Expected behaviour

LND send `channel_update` after receiving `funding_locked` from peer.

```
LND                      peer
|                         |
| funding_locked          |
|------------------------>|
|                         |
|          funding_locked |
|<------------------------|
|                         |
| channel_update          |
|------------------------>|
|                         |
```

### Actual behaviour

LND send `funding_locked` and `channel_update` before receiving `funding_locked` from peer.

```
LND                      peer
|                         |
| funding_locked          |
|------------------------>|
|                         |
| channel_update          |
|------------------------>|
|                         |
|          funding_locked |
|<------------------------|
|                         |
```

**Comment by Roasbeef** [comment] 2019-10-30 19:17
More or less a duplicate of https://github.com/lightningnetwork/lnd/issues/2555.

**Comment by Crypt-iQ** [comment] 2022-06-15 14:44
This came up in https://github.com/lightningnetwork/lnd/pull/5955#discussion_r897635899 and I think is a requirement for private (including `scid-alias`) channels between eclair.

**Closed** 2022-08-12 23:01 UTC
Labels: spec
