### ISSUE TITLE
Can't pay my own invoice

### ISSUE THREAD

**Issue by RHavar** [lightningnetwork/lnd#1155] opened 2018-04-29 19:42 UTC
```
$ lncli addinvoice
{
	"r_hash": "4debe6f5a58e86d4fff91894c887c63d0c5ab2d3c8e7a000bf57dc6a063c1e2d",
	"pay_req": "lntb1pdwv80tpp5fh47dad936rdfllerz2v3p7x85x94vknern6qq9l2lwx5p3urcksdqqcqzyswcgrpep95lsa34vzdr4l4z8u368hv9f90hyg4jg6gapazurpcecjj7l5296ylk50wxt0frlxk433vdu8s9y9u6k8xqpl6rhdvqqdavqpvn9xuk"
}

$ lncli payinvoice lntb1pdwv80tpp5fh47dad936rdfllerz2v3p7x85x94vknern6qq9l2lwx5p3urcksdqqcqzyswcgrpep95lsa34vzdr4l4z8u368hv9f90hyg4jg6gapazurpcecjj7l5296ylk50wxt0frlxk433vdu8s9y9u6k8xqpl6rhdvqqdavqpvn9xuk
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
```

While superficially it seems silly to pay your own invoice, in practice it's pretty useful. Like I used to run a website that had a bitcoin deposit/withdraw, and a good 10% of all the transactions were simply send-to-self  (user A owes user B money, so user B gives user A their deposit address, user A withdraws) and they often didn't even realize it was in the same wallet.

**Comment by Roasbeef** [comment] 2018-04-29 21:45
Closing as a duplicate of #482.

**Closed by Roasbeef** 2018-04-29 21:45 UTC
