### ISSUE TITLE
SIGSEGV after sending updatefee @ MacOS

### ISSUE THREAD

**Issue by bitcoinsplit** [lightningnetwork/lnd#474] opened 2017-12-11 13:19 UTC
While doing nothing Lnd crashes after sending updatefee. I'm running it at MacOS with high sierra. 

```
2017-12-11 14:00:12.346 [DBG] PEER: Sending UpdateFee(chan_id=66bbda26b59406fdb5a225793a08e83e25a5d045497cb5ed2f42a9cea3ae8055, fee_update_sat=3000) to 45.77.115.33:9735
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1212f39]

goroutine 356 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec.(*PublicKey).SerializeCompressed(0x0, 0xc420524000, 0xc42021e069, 0xc4203175a8)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec/pubkey.go:146 +0x69
github.com/lightningnetwork/lnd/lnwallet.SingleTweakBytes(0x0, 0xc4206a93e0, 0x0, 0xc420317608, 0x0)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/lnwallet/script_utils.go:1045 +0x47
github.com/lightningnetwork/lnd/lnwallet.deriveCommitmentKeys(0x0, 0x0, 0xc420092f80, 0xc420092fd8, 0x0)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:825 +0x51
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc4208a4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2958 +0x1c9
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc420108780, 0x20e2f00, 0xc4201c2150)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:985 +0x44
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateChannelFee(0xc420108780, 0xbb8, 0x0, 0x0)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1149 +0x238
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc420108780)
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:491 +0xf7f
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
	/Users/abc/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:267 +0x126
```

**Comment by halseth** [comment] 2017-12-12 18:42
Duplicate of #470.

**Closed by halseth** 2017-12-12 18:42 UTC
