### ISSUE TITLE
[bug]: CLN interoperability "Channel open canceled by us"

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7151] opened 2022-11-14 10:48 UTC
### Background

My peer, running CLN 0.12.1, opened a channel to my node, running lnd v0.15.4-beta. The open transaction was never broadcasted, and according to my peer the initial "handshaking" didn't complete. I can provide logs, if necessary.

When our nodes reconnect, this error appears in my logs:

```
[ERR] FNDG: received funding error from 02994ad13ea85d7b95fb37c1b72a43e63742ca3f97bcffa3a752432cde6b8d428e: chan_id=459537661a046111dea08036eb8cc7487873fcb2d538c9fb238b3fc1b88dc149, err=Channel open canceled by us
```

This message seems to originate here: https://github.com/ElementsProject/lightning/blob/master/openingd/openingd.c#L1420

### Your environment

* v0.15.4-beta
* Linux server 5.10.0-13-amd64 #<i>1</i> SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* bitcoind v23

### Steps to reproduce

Accept channel from CLN 0.12.1. Cause open "handshaking" to fail (I don't know the specifics, though).

### Expected behaviour

I don't know what exactly should happen.

### Actual behaviour

Error message, channel stuck in "pending_open_channels".

**Comment by cdecker** [comment] 2022-11-14 13:07
This is intended behavior and results from the node operator or a plugin calling `fundchannel_cancel` on the RPC. We'd need more information as to whether that call was intentional or due to something like a `multifundchannel` failing.

**Comment by C-Otto** [comment] 2022-11-14 13:11
Thanks. I think lnd should handle this error gracefully, possibly by forgetting the previous open attempt. Currently, having an error hidden in the logs and some broken channel lingering in "pending_open_channels" doesn't seem right for an intentional scenario.

**Comment by Roasbeef** [comment] 2022-11-14 22:21
If we never got all the way to exchanging signatures, then the pending channel _should_ just expire after 10 minutes. 

If we _did_ get all the way to exchanging signatures, but then the remote party decided to never publish the channel (something happened, or they did `fundchannel_cancel` to bail out), then we'll end up forgetting it after 2 weeks.

**Comment by C-Otto** [comment] 2022-11-15 06:43
It sounds like this is just a nuisance, assuming CLN's `fundchannel_cancel` is something worth supporting. Is there any way to fail more gracefully, i.e. without having to wait 14 days? Should lnd act on a specific (error) message?

I also wonder if pre-existing channels would be affected by this. I'm not sure if this is a channel-specific error, or if it affects the whole connection to the peer.

**Comment by morehouse** [comment] 2022-11-15 14:49
Seems to be working as intended.

We remember the pending channel after signature exchange in case the peer does actually broadcast the funding transaction.  In that case, we would know how to close the channel and potentially recover any `push_msat` funds they gave to us.  This also allows us to help the peer recover their channel funds if they screwed up and forgot the commitment transaction after the cancel.

I we forgot the channel after the peer cancelled, we wouldn't be able to do this.

**Comment by Roasbeef** [comment] 2022-11-30 04:27
Closing based on the above comment. There's a different issue open which tracks that we _do_ forget the channel, but don't clean up the state in the channel arbitrator once it's done (goroutine watching the chain is still active, but shouldn't be).

**Closed** 2022-11-30 04:29 UTC
Labels: bug, needs triage

**Comment by C-Otto** [comment] 2022-11-30 08:06
What about this?

> Is there any way to fail more gracefully, i.e. without having to wait 14 days? Should lnd act on a specific (error) message?
