### ISSUE TITLE
CloseChannel not properly working via gRPC

### ISSUE THREAD

**Issue by dieeasy** [lightningnetwork/lnd#3378] opened 2019-08-06 15:45 UTC
### Your environment

* `lnd` 0.7.1-beta
* `debian` "stretch" 9
* `bitcoind` 0.18.0
* `python` 3.5

### Steps to reproduce

Place a `CloseChannel` API call [as documented](https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/python.md#response-streaming-rpc):
```
    try:
            for lnd_res in stub.CloseChannel(lnd_req, timeout=30):
                if lnd_res.chan_close.closing_txid:
                    print(lnd_res.chan_close)
    except RpcError as err:
        error = err.details() if hasattr(err, 'details') else err
        print(error)
```

### Expected behaviour

1. `PendingUpdate` message
2. `ChannelCloseUpdate` message

### Actual behaviour

1. `PendingUpdate` message
2. `Deadline Exceeded` error

**Comment by wpaulino** [comment] 2019-08-06 18:14
I believe the issue here is the use of the timeout, which can cause the `deadline exceeded` error to happen if the RPC doesn't exit by then. `CloseChannel` returns a stream that sends two updates: one once the closing transaction is broadcast and another once it confirms. It's likely that you're not receiving the second update within 30s.

**Closed** 2019-08-12 19:43 UTC

**Comment by dieeasy** [comment] 2019-08-21 13:56
Actually, if the same operation is attempted via CLI, it does complete successfully, typically well before 30s.
Moreover, after receiving the timeout error the channel is actually closed if queried via `pendingchannels`.

So, it feels like the streaming is just failing to deliver the second message and just "waits" until the timeout expires to report an error.

PS: don't have a test case to offer at the moment but it used to work some time ago, with 99% accuracy

**Comment by wpaulino** [comment] 2019-08-21 18:42
> Actually, if the same operation is attempted via CLI, it does complete successfully, typically well before 30s.

That's because the CLI doesn't wait for the second event being delivered, only the first (closing transaction broadcast).

> Moreover, after receiving the timeout error the channel is actually closed if queried via pendingchannels.

This depends on how the channel is being closed. If you force close it, you'll incur a CSV delay and have to wait longer. In any case, the channel moves from `listchannels` to `pendingchannels` once the closing transaction is broadcast, and then moves from `pendingchannels` to `closedchannels` once fully confirmed.

> So, it feels like the streaming is just failing to deliver the second message and just "waits" until the timeout expires to report an error.

Our streaming APIs are definitely weird through REST, which is why we've opted to have sync counterparts to them, e.g. OpenChannelSync.
