### ISSUE TITLE
Wallet is missing funds after recovery

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [lightningnetwork/lnd#4216] opened 2020-04-22 15:17 UTC
### Background + Steps to reproduce

I've faced issue with recovering funds from wallet backup

After my vm with 6 nodes was destroyed, I tried to restore nodes with lnd_data folders saved previously(last updated 10 days ago), so I just started them with the same configs and tried to sync.

What I received as result is - synced lnd's missing transactions made during this 10 days period.

Then I tried using dropwtxmgr + recovery_window=2500 option - this synced some transactions but some were still left ( this caused much lower walletbalance).

Using explorer I've found last state of missing funds(for one of nodes) and addresses that store this funds right now.
I've made few changes to derive my wallet's adresses and printed them with derivation pathes - no needed addresses where found (only those known to wallet).

Then I've made a script to scan my hdchain and was able to find that addresses - they are stored in another KeyScope scope=m/1017'/0' , while lnd is scanning for KeyScopeBIP0084.

This raises two questions:
1. What could be done in such situation to restore my funds?
2. How could this situation happen? 

### Your environment

* lnd 0.8.2
* ubuntu

### Expected behaviour

Lnd synced and all funds are back

### Actual behaviour

Lnd synced and is missing some transactions ( they're located in other KeyScope)

**Comment by wpaulino** [comment] 2020-04-22 16:31
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/4127, this has been resolved in `v0.10.0-beta`.

**Closed by wpaulino** 2020-04-22 16:31 UTC
