### ISSUE TITLE
Different balance after masstesting and after restarting lnd

### ISSUE THREAD

**Issue by RvMp** [lightningnetwork/lnd#699] opened 2018-01-30 22:50 UTC
I've been doing some mass-testing on testnet with LND. First connecting to nodes and opening a channel with some funds seems fine. They go into pending and don't go into a normal state. 

During the mass test somehow I suddenly get errors regarding the amount of funds I have. Even the walletballance command gives me 0 as confirmed balance. 
```
lnd@dawson:~$    lncli connect 0381302d9733ac244d0480fb6e5f5f9a6042cd79b9c7ac27d019231185a5344272@188.166.103.252:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 188.166.103.252:9735
lnd@dawson:~$    lncli openchannel 0381302d9733ac244d0480fb6e5f5f9a6042cd79b9c7ac27d019231185a5344272 --local_amt=10000
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.0001 BTC only have 0 BTC  available
lnd@dawson:~$ lncli walletbalance
{
    "total_balance": "251457746",
    "confirmed_balance": "235312346",
    "unconfirmed_balance": "16145400"
}
lnd@dawson:~$ lncli walletbalance --witness_only
{
    "total_balance": "16145399",
    "confirmed_balance": "0",
    "unconfirmed_balance": "16145399"
}
```

When restarting LND things suddenly change.
All the pending channels are gone. Some moved to the normal channel state but the balance itself is also different. It is not 0 anymore.

```
lnd@dawson:~$ lncli unlock
Input wallet password: 
lnd@dawson:~$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ]
}
lnd@dawson:~$ lncli walletbalance --witness_only
{
    "total_balance": "494479875",
    "confirmed_balance": "494479875",
    "unconfirmed_balance": "0"
}
lnd@dawson:~$ lncli connect 0381302d9733ac244d0480fb6e5f5f9a6042cd79b9c7ac27d019231185a5344272@188.166.103.252:9735
{
    "peer_id": 0
}
lnd@dawson:~$ lncli openchannel 0381302d9733ac244d0480fb6e5f5f9a6042cd79b9c7ac27d019231185a5344272 --local_amt=10000
{
	"funding_txid": "b74c572af325affca5bbcab33e434c357128322daafb780a9a3d43da14ff1dac"
}

```

Before the restart it was not possible to fund a channel but after it is.

**Comment by aakselrod** [comment] 2018-01-31 19:37
Hey @RvMp, can you put the following in a pastebin or similar, please?

* The `lnd` logs from before and after the restart, especially when you were attempting to open channels
* Your `lnd.conf` (please blank out any credentials, etc.)

Thanks!

**Comment by RvMp** [comment] 2018-01-31 22:27
I'll try. maybe this is related as well
https://github.com/lightningnetwork/lnd/issues/713

**Comment by aakselrod** [comment] 2018-02-02 13:57
As mentioned in #713, pending channels make some balance look like it's disappeared due to the difference between the output you're using and the channel you're trying to fund. The pending issue you've opened in #720 seems to show an issue getting blockchain notifications. Again, at least your `lnd.conf` would be useful here, as well as the commit you're running.

**Comment by RvMp** [comment] 2018-02-02 14:04
lnd.conf added to https://github.com/lightningnetwork/lnd/issues/720

**Comment by Roasbeef** [comment] 2018-02-03 22:57
Duplicate of #720.

**Closed by Roasbeef** 2018-02-03 22:57 UTC
Labels: funding, safety, wallet
