### ISSUE TITLE
invalid memory after LND upgrade

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#5217] opened 2021-04-16 13:13 UTC
### Background

LND running well for months, after upgrade and unlock got Invalid memory crash.

### Your environment

* `lnd version 0.12.99-beta commit=v0.12.0-beta-373-ga36c95f7`
* which operating system (`uname -a` on *Nix) `Linux  5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux`
* version of `bitcoind` `Bitcoin Core version v0.19.1`

### Steps to reproduce

Stop Land, Upgrade, Start, Unlock.

### Expected behaviour

unlock and start

### Actual behaviour

```
2021-04-16 06:08:49.627 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: wallet locked, unlock it to enable full RPC access
2021-04-16 06:08:52.678 [INF] LNWL: Opened wallet
2021-04-16 06:08:52.850 [INF] CHRE: Primary chain is set to: bitcoin
2021-04-16 06:08:52.989 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:29000
2021-04-16 06:08:52.989 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:29001
2021-04-16 06:08:53.021 [INF] LTND: Shutdown complete

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1326c]

goroutine 1 [running]:
github.com/btcsuite/btcwallet/chain.(*BitcoindConn).NewBitcoindClient(0x2ae8380, 0x2c836e0)
        /home/lightning/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20210405201449-683061f79797/chain/bitcoind_conn.go:501 +0x50
github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.New(0x2ae8380, 0x19aaaa0, 0x10e0cd0, 0x2c872b8, 0x10e0cb0, 0x2c872b8, 0xe)
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:92 +0x108
github.com/lightningnetwork/lnd/chainreg.NewChainControl(0x2951ed0, 0x2c872a8, 0x280d201, 0x2c88640)
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/chainreg/chainregistry.go:411 +0x1834
github.com/lightningnetwork/lnd.Main(0x2c9ca00, 0x0, 0x0, 0x0, 0x0, 0x29a7ac0, 0x28902c0, 0x2890300, 0x2890340, 0x0, ...)
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/lnd.go:551 +0xcac
main.main()
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:36 +0x1ac
```

**Comment by halseth** [comment] 2021-04-16 14:22
Do you see this every time you start, or just this one time?

**Comment by alevchuk** [comment] 2021-04-16 14:29
Tried twice. Every time

**Comment by Crypt-iQ** [comment] 2021-04-16 14:51
Dupe of https://github.com/lightningnetwork/lnd/issues/5196

**Closed by Crypt-iQ** 2021-04-16 14:51 UTC
