### ISSUE TITLE
Payment FAILURE with an INSUFFICIENT_FEE error, whereas C should retry with the new fee.

### ISSUE THREAD

**Issue by jk14** [lightningnetwork/lnd#4957] opened 2021-01-26 14:00 UTC
### Background

Here is the failing scenario:

1. Launch 3 LND nodes, connected this way: A <---> B <---> C with private channels (it's important that the channels are private, like wallets do)
2. Create an invoice from A
3. On B, update the relay fees for the channel B <---> A (set values higher than the previous ones)
4. Pay A's invoice from C
5. The payment will fail with an INSUFFICIENT_FEE error, whereas C should retry with the new fee and the payment should work

Result:
| FEE_INSUFFICIENT @ 2 | 4.601 | 7.874 | 10200 | 3.03 | 666804 | 723388491148165120 | Brisk Lightning->ACINQ->02a81f |
Amount + fee: 0 + 0 sat
Payment hash: 251cc8a9a44c4a993fbf930ccd64b8480d1d252332af21231cd02bae06ddfed6
Payment status: FAILED, reason: FAILURE_REASON_NO_ROUTE
[lncli] FAILED

### Your environment

* LND version 0.11.1
* Linux vmi.contaboserver.net 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)
* Bitcoin Core version v0.20.1
* standard configuration

### Steps to reproduce

Already above.

### Expected behaviour

Payment status: SUCCEEDED, preimage: ...

### Actual behaviour

Payment status: FAILED, reason: FAILURE_REASON_NO_ROUTE

**Comment by Roasbeef** [comment] 2021-01-27 04:21
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/2066

**Closed by Roasbeef** 2021-01-27 04:21 UTC
