### ISSUE TITLE
Channel cannot be closed cooperatively after previous failed attempt

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [lightningnetwork/lnd#4513] opened 2020-08-06 15:10 UTC
### Background

Having some channels stuck on waiting_close status, which are not resolved for days or weeks now.

### Your environment

* version of `lnd` - 0.10.0 rc5
* which operating system - Linux
* bitcoind backend

### Steps to reproduce

Due to logs, this happens when you try to close channel and peer goes offline at that moment.

From logs:

```
ChannelPoint(996698094ebc25c2effeefc5e719bfa3a31c02793b001bbfa854266146fb43db:1): sending shutdown message
ChannelPoint(996698094ebc25c2effeefc5e719bfa3a31c02793b001bbfa854266146fb43db:1): shutdown response receieved, entering fee negotiation
...
...
unable to read message from 03757b80302c8dfe38a127c252700ec3052e5168a7ec6ba183cdab2ac7adad3910@178.128.97.48:11000: EOF
disconnecting 03757b80302c8dfe38a127c252700ec3052e5168a7ec6ba183cdab2ac7adad3910@178.128.97.48:11000, reason: read handler closed
```

This leads channel to be stuck in waiting_close_channels forever until you force close it.

```
{
            "channel": {
                "remote_node_pub": "0398a257b2abd70322a4072b4bca65c3dbe22e5079f67bd72e295774d4193068de",
                "channel_point": "996698094ebc25c2effeefc5e719bfa3a31c02793b001bbfa854266146fb43db:1",
                "capacity": "56337",
                "local_balance": "47287",
                "remote_balance": "0",
                "local_chan_reserve_sat": "573",
                "remote_chan_reserve_sat": "573",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "47287",
            "commitments": {
                "local_txid": "bacb696f3d4f80572ed841de5aea2d6339880526774ea202eaf3e1b444658033",
                "remote_txid": "1581776e1dde4bea87b2a97c73931b876ea91455881cdf2bdfe8d1ecb2e788af",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "9050",
                "remote_commit_fee_sat": "9050",
                "remote_pending_commit_fee_sat": "0"
            }
```

On restart when chain_arbitrator tries to rebroadcast this channel, it sends an error:
```
[WRN] CNCT: Channel 996698094ebc25c2effeefc5e719bfa3a31c02793b001bbfa854266146fb43db:1 is in state ChanStatusCoopBroadcasted, but no coop closing tx to re-publish... 
```

### Expected behaviour

I would expect lnd, to handle this case and try to submit this tx again.

### Actual behaviour

Channel is stuck until you force close it manually.

**Comment by wpaulino** [comment] 2020-08-10 17:15
Has this been resolved yet? Looking at the chain, the channel has been fully closed.

**Comment by RostyslavAntonyshyn** [comment] 2020-08-10 18:37
> Has this been resolved yet? Looking at the chain, the channel has been fully closed.

I force-closed it manually, it was stuck for a long time before that.

**Comment by pretyflaco** [comment] 2021-04-10 22:25
I have the same issue. Channel is stuck in pending after my node had a disc failure and had to be restored from backup. When node came back up 2 weeks ago, one channel was waiting close and balance is in limbo. OP wrote that force-closing solved issue for him. Is this the recommended way to resolve? 

` "version": "0.11.1-beta commit=v0.11.1-beta",
"synced_to_chain": true,
    "synced_to_graph": true,`

`    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "02e01367e1d7818a7e9a0e8a52badd5c32615e07568dbe0497b6a47f9bef89d6af",
                "channel_point": "fc65405f10a6cbf08e7f2a2e14cc137477d214eb38d4059c5318499e2407cd8d:1",
                "capacity": "1500000",
                "local_balance": "1307044",
                "remote_balance": "176360",
                "local_chan_reserve_sat": "15000",
                "remote_chan_reserve_sat": "15000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "1307044",
            "commitments": {
                "local_txid": "487b8fd3ee6d62772cd61932aa8c4a52fa30df32e4b924db15194ffe8f34b7b3",
                "remote_txid": "9c56bd2d9833903da6ffb29d522de25c57d7de40b369d42e747bb4e4a3e759a1",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "16595",
                "remote_commit_fee_sat": "16595",
                "remote_pending_commit_fee_sat": "0"
            }
`

**Comment by wpaulino** [comment] 2021-04-12 19:30
@pretyflaco your case is different since you had to restore from a backup. You'll need to wait until lnd connects to your channel counterparty, which will then signal them to force close the channel, allowing you to sweep your funds. It's possible that the backup contained outdated addresses for your channel counterparty, which is maybe why it's in `waiting_close_channels`, so it might be worth looking up an updated address for the node at https://1ml.com to connect to and get the process started.

**Comment by pretyflaco** [comment] 2021-04-12 23:20
Indeed! lnd used to run over tor before, switched it on and now tx settled. Thank you for the hint.

**Comment by Roasbeef** [comment] 2021-08-31 01:41
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/4819

**Closed by Roasbeef** 2021-08-31 01:41 UTC
Labels: channel closing, channel management, spec
