### ISSUE TITLE
describe graph channel last_updated

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1649] opened 2018-07-29 14:35 UTC
it looks like describegraph for channels shows the last_updated for node1 only, and the last_updated for node2 is not taken into account. either way it is only one timestamp.

it would be more useful if the last_updated times were specidied individually per side

**Comment by Roasbeef** [comment] 2018-07-30 02:12
Yep, [there's a TODO in the code for this](https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L3055).

**Comment by robtex** [comment] 2018-08-02 08:49
cool. it is only presentation cosmetics right? the node actually handles the timestamps individually?

**Comment by ConnorL33t** [comment] 2018-08-04 18:58
I'd like to implement this if it's up for grabs!

**Comment by Roasbeef** [comment] 2018-08-05 18:36
> cool. it is only presentation cosmetics right? the node actually handles the timestamps individually?

Yeah internally it's there, so it's just a matter of modifying the protos to be able to track the last update time individually.

**Comment by Roasbeef** [comment] 2018-08-05 18:36
@ConnorL33t yep still up for grabs!

**Comment by robtex** [comment] 2018-08-06 07:28
sorry for a rhetorical question, but wouldn't it be like common sense to keep the old deprecated name for compatibility, and to use the max() value of the two update times instead of still having only one of them so it also makes some kind of sense?
also my personal opinion would be to have the timestamp in the policy section, since after all the timestamp corresponds to the latest update of the policies/flags.

**Comment by ConnorL33t** [comment] 2018-08-06 14:26
I was coming to those same questions about the desired behavior around last_update versus individual time stamps on policies. Those commits above aren’t ready for a PR, my apologies if they notified you

**Comment by robtex** [comment] 2018-08-06 15:03
@ConnorL33t ah sorry about that. i get lots of notifications, i seldom read them. guess you were unlucky :) keep up the good work! also mind the opinions above are my personal and i'm not on dev team.

**Comment by wpaulino** [comment] 2019-04-18 08:08
Closing as duplicate of #2310.

**Closed by wpaulino** 2019-04-18 08:08 UTC
Labels: P3, beginner, enhancement, feature request, rpc
