### ISSUE TITLE
NANN Error: Unable to sign update disabling channel ... edge not found

### ISSUE THREAD

**Issue by cryptagoras** [lightningnetwork/lnd#2798] opened 2019-03-18 17:26 UTC
### Background

After updating to a recent master ( 36cc1da8ea0eec6be4559c673bc07bd0ae9be66a ), I started getting an error message related to some already remote force-closed channels.

### Your environment

* version of `lnd`: after upgrading (probably from 351865ac6772e7885a64c7e0c1e154abade40c91) to 36cc1da8ea0eec6be4559c673bc07bd0ae9be66a
* Ubuntu 16.04 LTS
* `bitcoind` 0.17.1

### Steps to reproduce

Not sure, I think there were some problematic channels that were forced-closed from the remote side. Below are the logs with the error messages which I get every minute for some days now.

```
2019-03-18 16:33:42.954 [INF] NANN: Announcing channel(481e1d8c2f14e87bc73d32038358b4145c259de7cd500342a1306980e6833646:1) disabled [detected]
2019-03-18 16:33:42.954 [ERR] NANN: Unable to sign update disabling channel(481e1d8c2f14e87bc73d32038358b4145c259de7cd500342a1306980e6833646:1): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(180301999e2ba94819a6fe8458ca6428bcc53b5dbf94ccc0c5f729251a2718d7:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(180301999e2ba94819a6fe8458ca6428bcc53b5dbf94ccc0c5f729251a2718d7:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(975233a616a5d8600cd437806bd0686f14ff548e10a42ec3bc3e2cee120e3749:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(975233a616a5d8600cd437806bd0686f14ff548e10a42ec3bc3e2cee120e3749:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(59e601b132c046eaecbe8394c45f0135250c4f0be3400722d9538351d624d3de:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(59e601b132c046eaecbe8394c45f0135250c4f0be3400722d9538351d624d3de:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(2d55a0eeb6606cc50da153b89e361d2dbc693dbfc396966bf8027304a8a26a13:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(2d55a0eeb6606cc50da153b89e361d2dbc693dbfc396966bf8027304a8a26a13:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(5b87693722a742bdead2a0d0e021f46b1c42fcb48524ac3c8880542118591f44:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(5b87693722a742bdead2a0d0e021f46b1c42fcb48524ac3c8880542118591f44:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(d5a03bffc45d26d8bc3de4ff647b4ad5b26914033b7a5c7b5c3701619c5b0cf4:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(d5a03bffc45d26d8bc3de4ff647b4ad5b26914033b7a5c7b5c3701619c5b0cf4:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(32832c08486dc65d233ede3647d5c521f57e013119cb86f7defce4f5ed76ed8c:1) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(32832c08486dc65d233ede3647d5c521f57e013119cb86f7defce4f5ed76ed8c:1): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(ac797227836d1528d9352d5adcfb90d881af0d33ac37473dace9d3e58bc821bb:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(ac797227836d1528d9352d5adcfb90d881af0d33ac37473dace9d3e58bc821bb:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(68d8d77c133e526ee5579661942d29f76739360e632429c58b4f6d75cffb1618:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(68d8d77c133e526ee5579661942d29f76739360e632429c58b4f6d75cffb1618:0): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(6923e068557cb2e87d50c53446162c9219ffc7fb2223eeae18e202d5cbea69e7:1) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(6923e068557cb2e87d50c53446162c9219ffc7fb2223eeae18e202d5cbea69e7:1): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(3af86b8802aaf22d5aac3ba131761d62366b71a86212b3baf96a38b27b55153a:1) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(3af86b8802aaf22d5aac3ba131761d62366b71a86212b3baf96a38b27b55153a:1): edge not found
2019-03-18 16:33:42.955 [INF] NANN: Announcing channel(62d7c78473b81530b024051a621d480ebff6904ad419cdafa09a7d626dd6da3e:0) disabled [detected]
2019-03-18 16:33:42.955 [ERR] NANN: Unable to sign update disabling channel(62d7c78473b81530b024051a621d480ebff6904ad419cdafa09a7d626dd6da3e:0): edge not found
```

### Expected behaviour

Not sure, maybe not trying to announce the disabling of  (remote force-closed) / already closed channels.

### Actual behaviour

It seems it tries to announce the disabling of an already (force-)closed channel.

**Comment by wpaulino** [comment] 2019-03-18 17:36
Duplicate of #2696. Will be fixed by https://github.com/lightningnetwork/lnd/pull/2744.

**Closed by wpaulino** 2019-03-18 17:36 UTC

**Comment by cryptagoras** [comment] 2019-03-18 19:22
Oh sorry, weird, I did search but I missed it :S
