### ISSUE TITLE
sendcoins makes lnd enter unconfirmed state

### ISSUE THREAD

**Issue by PWKad** [lightningnetwork/lnd#2011] opened 2018-10-04 23:13 UTC
### Background

When using sendcoins and sending from and to the same wallet that generated the address the full balance seems to stay unconfirmed forever.

```
mymachine:Lnd $ lncli --network regtest walletbalance
{
    "total_balance": "1999913856",
    "confirmed_balance": "0",
    "unconfirmed_balance": "1999913856"
}
# // killed and re-ran lnd in the other window
mymachine:Lnd $ lncli unlock
Input wallet password:

lnd successfully unlocked!
mymachine:Lnd $ lncli --network regtest walletbalance
{
    "total_balance": "1999956698",
    "confirmed_balance": "1999956698",
    "unconfirmed_balance": "0"
}
```

### Your environment

* version of `lnd` lat = lnd version 0.5.0-beta commit=a3edcf9cd537ea37a502efc91d262e7017a99e6b
* which operating system (`uname -a` on *Nix) = osx 
* version of `btcd`, `bitcoind`, or other backend = bitcoind
* any other relevant environment details
`regtest` mode

### Steps to reproduce

Pseudo-code, from no chain data at all - 
```
$ bitcoind --regtest
$ lnd
$ lnd unlock
$ bitcoin-cli generate 450
$ lncli newaddress
$ bitcoin-cli sendtoaddress <address from previous line> 10
$ bitcoin-cli generate 1
$ lncli walletbalance // balance looks good
$ lncli new address
$ lncli sendcoins <address from previous line> 25000
$ bitcoin-cli generate 1
$ lncli walletbalance // balance is 100% unconfirmed
```

### Expected behaviour

Balance should be all confirmed on what is left in the wallet.

### Actual behaviour

Balance is 100% unconfirmed no matter how many new blocks are generated

**Comment by joostjager** [comment] 2018-10-17 14:14
Tried to reproduce this, but no luck. Used same commit and bitcoind/regtest. Ubuntu instead of osx, but seems unlikely that that is the cause.

I started with a completely empty wallet. Don't know if your wallet has history, but maybe you can try to reproduce this after wiping all lnd data and creating a new wallet?

**Comment by Roasbeef** [comment] 2018-10-26 00:20
Closing for now as we're unable to reproduce.

**Comment by joostjager** [comment] 2018-10-29 14:54
I get this problem too on latest master 68d96488cc9f78e6aeb7d5c27822f384f756f335.

Repro steps:
- Backend bitcoind
- Clear all lnd data
- Start lnd
- `lncli newaddress np2wkh` -> addr1
- `bitcoin-cli sendtoaddress <addr1> 1`
- `bitcoin-cli generate 6`
- `bitcoin-cli getnewaddress` -> addr2
- `lncli-alice sendcoins <addr2> 100000`
- `bitcoin-cli generate 1`
- `lncli-alice sendcoins <addr2> 100000`
- `bitcoin-cli generate 10`

And balance is still unconfirmed.

**Comment by PWKad** [comment] 2018-10-29 14:58
Post your logs? I think that was what the maintainers were asking for I hadn't had a chance to repro and get them again yet

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 29, 2018 at 10:55 AM, Joost Jager<notifications@github.com> wrote:   
Reopened #2011.

**Comment by joostjager** [comment] 2018-10-29 15:04
Full log (includes restart)
[alice.log](https://github.com/lightningnetwork/lnd/files/2525798/alice.log)

**Comment by PWKad** [comment] 2018-10-29 15:19
Just realized you were the one who asked for the logs >.<

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 29, 2018 at 10:58 AM, Patrick Walters<patrickwaltersc21@yahoo.com> wrote:   Post your logs? I think that was what the maintainers were asking for I hadn't had a chance to repro and get them again yet

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 29, 2018 at 10:55 AM, Joost Jager<notifications@github.com> wrote:   
Reopened #2011.

**Comment by joostjager** [comment] 2018-10-29 19:54
Haha, yes indeed. But I did like the suggestion :smile:

**Closed** 2018-11-15 05:39 UTC
Labels: P2, bug
