### ISSUE TITLE
ListInvoices since certain timestamp

### ISSUE THREAD

**Issue by AbelLykens** [lightningnetwork/lnd#6796] opened 2022-08-04 06:59 UTC
### Background

Feature request: currently we can start reading invoices from a certain `add_index`. Would be useful if we could list invoices based on creation or settle date

### Your environment

* version of `lnd` *0.14*
* which operating system (`uname -a` on *Nix) *4.19.0-20-amd64*
* version of `btcd`, `bitcoind`, or other backend: *neutrino*
* any other relevant environment details *none*

**Comment by yyforyongyu** [comment] 2022-08-04 11:30
Duplicate of #6533?

**Comment by AbelLykens** [comment] 2022-08-04 11:33
Yeah sounds related. Let's ask in that ticket.

**Comment by positiveblue** [comment] 2022-08-04 14:53
Closing as duplicated. Changes are already been tracked in #6533 and implemented in [6542](https://github.com/lightningnetwork/lnd/pull/6542)

**Closed by positiveblue** 2022-08-04 14:53 UTC
Labels: beginner, feature request, good first issue
