### ISSUE TITLE
[bug]: Cannot send coins with 1 sat/vB

### ISSUE THREAD

**Issue by Impa10r** [lightningnetwork/lnd#8704] opened 2024-04-27 21:04 UTC
### Background

Describe your issue here.

### Your environment

* version of `lnd` 0.18.0-beta.rc1 
* which operating system (`uname -a` on *Nix) ubuntu
* version of `btcd`, `bitcoind`, or other backend Bitcoin Core version v26.0.0
* any other relevant environment details testnet3

### Steps to reproduce

```
lncli sendcoins --addr tb1p6phwhqxsykfu0rhsnye0mvscamrfjderawlwq4mxls6k8y0dut0q39ck4s --amt 1000 --sat_per_vbyte 1
Amount: 1000
Destination address: tb1p6phwhqxsykfu0rhsnye0mvscamrfjderawlwq4mxls6k8y0dut0q39ck4s
Confirm payment (yes/no): yes
[lncli] rpc error: code = Unknown desc = fee preference too low: got 253 sat/kw, minimum is 287 sat/kw
```

### Expected behaviour

should send

### Actual behaviour

does not let me use such a fee

**Comment by Impa10r** [comment] 2024-04-28 16:38
today even 2 sats/vB does not work. same build, same address:
```
vlad@vlad-VirtualBox:~$ lncli sendcoins --addr tb1p6phwhqxsykfu0rhsnye0mvscamrfjderawlwq4mxls6k8y0dut0q39ck4s --amt 1000 --sat_per_vbyte 2
Amount: 1000
Destination address: tb1p6phwhqxsykfu0rhsnye0mvscamrfjderawlwq4mxls6k8y0dut0q39ck4s
Confirm payment (yes/no): yes
[lncli] rpc error: code = Unknown desc = fee preference too low: got 500 sat/kw, minimum is 697 sat/kw

```

**Comment by alexbosworth** [comment] 2024-04-28 19:32
If your peers won't relay too-low chain fee transactions then publishing the transaction wouldn't work right?

**Comment by Impa10r** [comment] 2024-04-28 20:01
This is not a problem on testnet. Fee estimation is wrong. How do I calculate the new floor? If we censor low fee transactions the fees won't go down.

**Comment by guggero** [comment] 2024-04-29 07:58
What value do you get for `mempoolminfee` when you run `bitcoin-cli getmempoolinfo`? That should match up with the minimum fee rate you get in the error message.

**Comment by guggero** [comment] 2024-04-29 08:43
Starting with `v0.18.0`, `lnd` will not let you create a transaction that will not make it into your local `bitcoind`'s mempool. So `lnd` uses the `mempoolminfee` as the absolute minimum fee rate it will allow you to use. Otherwise you won't be able to broadcast it.
Since you are using the default mempool size of 300 MB, I assume that value was lower when you tried yesterday.

Closing the issue, as this is expected behavior.

**Closed by guggero** 2024-04-29 08:43 UTC
Labels: bug, needs triage
