### ISSUE TITLE
How to reload the lnd.conf configuration without restarting the daemon?

### ISSUE THREAD

**Issue by vwas2** [lightningnetwork/lnd#6491] opened 2022-05-02 15:06 UTC
latest version, how to send eg a sighup to make lnd process reload its config. 
restart is horrible considering open channels etc

**Comment by alexbosworth** [comment] 2022-05-02 15:07
is there a specific setting that you want to alter?

**Comment by vwas2** [comment] 2022-05-02 15:18
yes: minchansize, tor.active, rpclisten, etc etc. basically everything. please help

**Comment by alexbosworth** [comment] 2022-05-02 15:21
for min chan size you can use the `ChannelAcceptor` API to alter requirements without a restart

For Tor enabling and disabling and RPC a restart is currently required yes

**Comment by Roasbeef** [comment] 2022-05-02 17:57
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/800

**Closed by Roasbeef** 2022-05-02 17:57 UTC
