### ISSUE TITLE
Feature Request: support passing confidence parameter to fee estimation

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#2983] opened 2019-04-20 01:10 UTC
When getting fee estimates from the API, it would be useful for the caller to be able to express the level of fee estimation confidence they desire.

Bitcoin Core currently supports two fee levels: economical and conservative.

**Comment by wpaulino** [comment] 2019-04-23 18:51
Duplicate of #2990.

**Closed by wpaulino** 2019-04-23 18:51 UTC
Labels: enhancement, feature request, fees, wallet
