### ISSUE TITLE
contractcourt: htlcSuccessResolver should be aware of peer claiming w/ timeout

### ISSUE THREAD

**Issue by antonilol** [lightningnetwork/lnd#6444] opened 2022-04-22 14:14 UTC
### Background

Describe your issue here.

i had a channel with a lot of pending htlcs under the dust limit of p2wsh, when i force closed a few days ago those htlcs were not in the commitment tx on chain (expected), but they have been sitting in pendingchannels stuck in stage one with non existent outpoints

there were also larger htlcs in this channel which have been resolved on chain

https://github.com/lightning/bolts/blob/master/03-transactions.md#trimmed-outputs

```json
{
    ...
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "026e4ac4ce38c559a918fbc3f94abccc64992626cb3335364b7c0a381d1d1ef9fd",
                "channel_point": "d1ad120b1805af53782c14b00584f14fd197cdc68b502bf15bb27e8b07daa490:0",
                "capacity": "100000",
                "local_balance": "1478",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY",
                "num_forwarding_packages": "0",
                "chan_status_flags": ""
            },
            "closing_txid": "de46048881b41dcd48a8f51845ee9e918961ccc82b4a3fafe7a0441cb77bfe0d",
            "limbo_balance": "12012",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
                {
                    "incoming": true,
                    "amount": "364",
                    "outpoint": "f080341ee47e4b1f22811a09a0ac0f949dbe123b94edad5722a193cfc0cc527f:0",
                    "maturity_height": 2196562,
                    "blocks_til_maturity": -292,
                    "stage": 1
                },
                {
                    "incoming": true,
                    "amount": "364",
                    "outpoint": "d33d36cbe7b56dd4b087e90fd6b13ae18ddc3cd4d9d3bd3c123611667bb3ba39:0",
                    "maturity_height": 2196562,
                    "blocks_til_maturity": -292,
                    "stage": 1
                },
                ...
                {
                    "incoming": true,
                    "amount": "364",
                    "outpoint": "4cc72ae3a6984b3e6b12721cef7c9af92a4f4ce79ec9c004bf83661e0af169a8:0",
                    "maturity_height": 2196562,
                    "blocks_til_maturity": -292,
                    "stage": 1
                },
                {
                    "incoming": true,
                    "amount": "364",
                    "outpoint": "e9cb4b1fb366951c81318400ba92df2e507de3d6d1c8a59f532acae92d3bcc35:0",
                    "maturity_height": 2196562,
                    "blocks_til_maturity": -292,
                    "stage": 1
                }
            ],
            "anchor": "LIMBO"
        }
    ],
    "waiting_close_channels": [
    ]
}
```

### Your environment

* version of `lnd`
  `lnd version 0.14.2-beta commit=v0.14.2-beta`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details
  testnet

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

i dont know, i tried but they dont show up on chain (expected) and not in pendingchannels (expected)

### Expected behaviour

Tell us what should happen

lnd should not try to resolve contracts that dont exist on chain (look up the outpoints in the htlcs)

### Actual behaviour

Tell us what happens instead

they got stuck in stage 1

**Comment by Crypt-iQ** [comment] 2022-04-22 15:19
the dust limit for a p2wsh script is 330sats and our code does account for this before creating a resolver.  it seems like the 2nd level tx never hit the chain so that's why you wouldn't find the outpoints. not sure why the resolver didn't expire itself though, do you have any logs? do you own this tx (257588070d593c9dfcc6e75ebc8f29b6c29d22ba5cabf78830f2fdeaf903ec88)?

**Comment by Crypt-iQ** [comment] 2022-04-22 15:27
My hunch is that the incoming_contest_resolver decided to morph into a success resolver, broadcasted the 2nd-level, but doesn't handle the case where the the blockheight is close to the htlc expiry and the peer claims the outputs via timeout, leading to stuck resolvers. cc @Roasbeef

**Comment by antonilol** [comment] 2022-04-22 15:51
> do you have any logs?

lnd.log got rotated, here is [lnd.log.2.gz](https://github.com/lightningnetwork/lnd/files/8542302/lnd.log.2.gz)

> do you own this tx (257588070d593c9dfcc6e75ebc8f29b6c29d22ba5cabf78830f2fdeaf903ec88)?

yes

**Comment by antonilol** [comment] 2022-04-22 21:01
https://github.com/lightning/bolts/blob/master/03-transactions.md#trimmed-outputs

i accidentally got the same issue again

i think the issue might be that HTLC timeout transactions create outputs under the dust limit

does LND use this logic from bolt 3? i think those HTLCs must not be created in the first place in the commitment tx

  - for every offered HTLC:
    - if the HTLC amount minus the HTLC-timeout fee would be less than
    `dust_limit_satoshis` set by the transaction owner:
      - MUST NOT contain that output.
    - otherwise:
      - MUST be generated as specified in
      [Offered HTLC Outputs](https://github.com/lightning/bolts/blob/master/03-transactions.md#offered-htlc-outputs).
  - for every received HTLC:
    - if the HTLC amount minus the HTLC-success fee would be less than
    `dust_limit_satoshis` set by the transaction owner:
      - MUST NOT contain that output.
    - otherwise:
      - MUST be generated as specified in
      [Received HTLC Outputs](https://github.com/lightning/bolts/blob/master/03-transactions.md#received-htlc-outputs).

**Comment by Crypt-iQ** [comment] 2022-04-22 21:19
I don't think this is correct, lnd does not create outputs under the dust limit. There seems to be something else going on with the resolver that is unrelated to the spec

**Comment by Crypt-iQ** [comment] 2022-08-24 15:42
Dupe of https://github.com/lightningnetwork/lnd/issues/4896

**Closed by Crypt-iQ** 2022-08-24 15:42 UTC
Labels: bug, help wanted, intermediate, contracts, chain handling
