### ISSUE TITLE
Channels "active=false" while both nodes are online

### ISSUE THREAD

**Issue by glo-www** [lightningnetwork/lnd#2632] opened 2019-02-12 09:09 UTC
### Background

Today I found three channels marked as inactive (active="false"). They where active previously. When I try to connect to peer, it says I am already connected.

Two other channels are still active though.

### Your environment

* lnd version 0.5.2-beta commit=v0.5.2-beta-rc7
* Raspbian Stretch Lite 
* Bitcoin Core Daemon version v0.17.1
* Tor

### Steps to reproduce

Channels active turned inactive, don't know how to reproduce. 

If you need additional log info, don't hesitate to specify how I find it :p

**Comment by glo-www** [comment] 2019-02-12 13:39
All channels back to "active" after restart. Still no clue of what happened.

**Comment by ccdle12** [comment] 2019-02-12 13:51
It could have been that the other parties on that channel were offline.

**Comment by glo-www** [comment] 2019-02-12 14:11
They were online.
Perhaps, they went offline but could not reconnect to me because I am behind tor. 
But then, why did they appear when I ran "listpeers" ?

**Comment by ccdle12** [comment] 2019-02-12 14:43
That's strange then, I'm not sure, you are correct if they go offline then they shouldn't appear in "listpeers" to my knowledge.

**Comment by ccdle12** [comment] 2019-02-12 14:45
btw: to answer on the above questions the logs can be found
* On Linux
```
/root/.lnd/log/bitcoin/<mainnet/testnet/simnet>/lnd.log
```

It might be worth having a look to see if there's any info there that can help.

**Comment by wpaulino** [comment] 2019-02-12 23:33
It's possible for this to happen if the channel can't be reestablished with your peer upon reconnection. You can check the logs for the message `didn't receive ChannelReestablish before deadline` to see if this happened.

**Comment by glo-www** [comment] 2019-02-13 07:54
Thanks for help guys.

Indeed I had three times this lines, which would correspond to the three inactive channels:
2019-02-11 18:47:57.025 [ERR] HSWC: ChannelLink(xxxx:2735:1) Failing link: unable to synchronize channel states: didn't receive ChannelReestablish before deadline
2019-02-11 18:47:57.025 [INF] HSWC: ChannelLink(yyyyy) has exited
2019-02-11 18:47:57.025 [INF] HSWC: Removing channel link with ChannelID(zzzzz)
2019-02-11 18:47:57.026 [INF] HSWC: ChannelLink(yyyyy:1) is stopping

Is it still a LND bug? Why can't the channel be reestablished when both nodes are online?

**Comment by Roasbeef** [comment] 2019-02-13 22:42
If for w/e reason they other peer doesn't respond (it's suck, stale TCP connection, the connection is dead, etc), then they won't send the message we need. If this happens persistently with the remote peer, then you may want to consider selecting a different channel peer.

**Comment by roeierez** [comment] 2019-03-03 10:08
Hi,
This happens to me every couple of days and currently the work around is to restart the node.
The problem is that the channel is left in a non-recoverable state. 
Since reconnecting again solves this, do you think there is a room for adding a retry mechanism to `syncChanStates` with the remote peer on a configurable/backoff interval? After all the code does retry to reconnect peers that it has a channel with.

**Comment by glo-www** [comment] 2019-03-04 09:10
Today, I had to restart my node as well because two channels were inactive. They go back to active after restart...

**Comment by cfromknecht** [comment] 2019-03-04 21:54
@glo-www I believe this will be mostly addressed by #2690, would be interested to see if the issue persists after that is in

**Comment by Roasbeef** [comment] 2019-03-06 05:11
#2690 in now, do y'all still see this pop up? 

@roeierez before if we failed to sync, we'd just disconnect all together. It was discovered that this behavior made connections unstable (flappy peers) we removed it in order to have the TCP connections themselves be more stable. Retrying as you suggest would likely fix the issue, but I'd rather get to the bottom of why it's happening in the first place, rather than applying a band-aide and forgetting about the root cause.

**Comment by Roasbeef** [comment] 2019-03-06 05:31
Dug into this a bit more, and I think we have a pretty good hunch on why we still this happen consistently, and also why it's become more frequent in the past few months.

**Comment by begetan** [comment] 2019-03-17 00:32
I have a peer which goes to discconect state while being online.

First time we recoverd channel by restart of my side. It was lnd 0.5.1. 
Second time it was not recovered when I did restart after upgrade to 0.5.2
I found that telnet to peer port failed with "connection refuse" message.

Is it possible to have tcp connection refuse for normally running peer? May some kind of anti-spoof, or ddos protection do that?

**Comment by wpaulino** [comment] 2019-03-18 17:33
> I found that telnet to peer port failed with "connection refuse" message.

@begetan would either mean that the peer is offline or they've banned your IP.

**Comment by danbadjar** [comment] 2019-03-27 12:59
Same problem here, often with Bitrefill!

I have to restart lnd to see the channel active.
Same thing happens randomly with other nodes. Sometimes i just do a reconnect and the channel turns to active. Sometimes instead I obtain "you're already connected" and the channel is always inactive.

lnd 0.5.2 last commit

**Comment by wpaulino** [comment] 2019-03-27 17:59
@danbadjar if you update to master things should be a bit better. We'll have these issues addressed by the next major release.

**Comment by engenegr** [comment] 2019-04-05 09:14
Always have inactive channels.
I decided to write here since I've opened second channel (bigger) with the peer which already have an open _active_ channel with me. I can't make second channel active by simple restarting my node. It is not on RPi but on Google. It is almost 100% uptime except updates but I always have about 8-10 inactive channels from 40-50.

**Comment by wpaulino** [comment] 2019-04-05 19:08
@engenegr this _shouldn't_ be an issue anymore with v0.6, but it will require your peers to upgrade.

**Comment by Roasbeef** [comment] 2019-04-09 23:35
Closing this now as it's addressed in 0.6 by the new distinct gossip queue and also partially relies on your peers updating.

**Closed by Roasbeef** 2019-04-09 23:35 UTC
