### ISSUE TITLE
Feature request: Ban list

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#2840] opened 2019-03-26 15:04 UTC
### Background

I would like to perma-ban certain IPs and/or node IDs.

My node is 'getting harassed' by a node that has no channel to mine (actually, it has zero channels), but tries to connect to my node as a peer every 2-3 seconds, causing gossiper to go nuts.
Pub Key: 030b719f743b0e2fadae65ebf4a70bc198f97deea129f7780c3b2bf6e17a4507be
Address: 188.246.224.96

This could be quite useful to auto-reject any connects coming from a IP range and/or Node ID.

**Comment by wpaulino** [comment] 2019-03-26 19:34
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/1183.

**Closed by wpaulino** 2019-03-26 19:34 UTC

**Comment by ZapUser77** [comment] 2019-03-27 00:45
This is not a duplicate of 1183.
1183 is automatic banning.
My request is manually banning.  Very similar, but not the same.

**Comment by wpaulino** [comment] 2019-03-27 01:02
We'll likely include an interface for that as well. Ideally though, users do not need to worry about banning peers themselves.

**Comment by ZapUser77** [comment] 2019-03-27 01:05
There will *definitely* be users that need to ban peer connections from entire regions, for legal reasons, while not banning their IP from the server, just from LND.
As well as "known spies", or known bad actors, etc, that ppl will want to manually ban.

Unfortunately, we don't live in an ideal world.  ;)
But as long as there's a command to do it, all will be peachy.  ^_^  Keep up the great work.
