### ISSUE TITLE
Switching from `neutrino` to `bitcoind`: is it stuck?

### ISSUE THREAD

**Issue by callebtc** [lightningnetwork/lnd#6900] opened 2022-09-08 08:08 UTC
### Background

I want to switch a node from neutrino back to bitcoind (started with bitcoind, had to use neutrino in the mean time because of problems with the bitcoind instance). Neutrino worked well but now I want to switch back. When I enable `bitcoind` in the config, I see the following log entry upon lnd startup:

`Syncing channel graph from height=748582 (hash=...) to height=753130 (hash=...)`

Then almost nothing happens. No progress indicator, no CPU use by lnd nor bitcoind. Is it stuck? Is it working? How long do I need to wait?

I switched back to `neutrino` in the mean time (worked). 

### Your environment

* version of `lnd` 0.15.1
* which operating system (`uname -a` on *Nix): ubuntu
* version of `btcd`, `bitcoind`, or other backend: 23.0

### Steps to reproduce

Use bitcoind, then switch to neutrino for a long time, attempt to switch back to bitcoind.

### Expected behaviour

Should synch graph and continue working.

### Actual behaviour

Nothing happens with no progress indication.

**Comment by Roasbeef** [comment] 2022-09-08 18:07
Gonna close as a duplicate of https://github.com/lightningnetwork/lnd/issues/6901. 

You can switch one way pretty easily, but going the other way you might run into some issues. This also isn't exactly an "officially" supported switch over. 

You might have some luck doing a wallet rescan when switching over from neutrino to `bitcoind`.

**Closed by Roasbeef** 2022-09-08 18:07 UTC
Labels: neutrino
