### ISSUE TITLE
How to get funds from the channel to the initiator having the SCB backup, if the other party has closed the channel long ago?

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#5507] opened 2021-07-12 09:53 UTC
One of the operators of the site faced the problem of recovering funds through the SCB. Can I ask someone from the developers to help me figure out the following situation. I don't quite understand how the funds are returned in the following scenario:

1. The remote peer opened (at 2021-05-04) the channel `e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1`. So he was initiator
2. He didn't use the channel so my `local_balance` was zero
3. At some point, my node decided to close the channel (force) with that node, but since there were no funds on my side, the LND apparently did not form a closing transaction (he is not the initiator, he does not pay on-chain fees, there are no funds to be refunded - it is quite logical just close the channel without a transaction)
```

        {
            "channel_point": "e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1",
            "chan_id": "0",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "0000000000000000000000000000000000000000000000000000000000000000",
            "remote_pubkey": "0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a",
            "capacity": "2000000",
            "close_height": 0,
            "settled_balance": "0",
            "time_locked_balance": "0",
            "close_type": "FUNDING_CANCELED",
            "open_initiator": "INITIATOR_REMOTE",
            "close_initiator": "INITIATOR_LOCAL",
            "resolutions": [
            ]
        },
```
4. Most likely, after such a closure, the remote peer breaks down and the owner of the node decided to restore funds from the channel through the SCB.
5. He asks me to close the channel - after all, this is how the SCB works, but I cannot close the channel, since it was closed long ago. As far as I understand, how the SCB should work - its node should ask my node for the last channel status, my node should respond and, based on the data from my node, its node should then form a closing transaction. Or I have to close. And in the current situation, neither one nor the other can be done. How can he get the funds back from the channel with a SCB?

**Comment by guggero** [comment] 2021-07-12 10:04
When looking at the chain I see that the channel was never closed (at least not on-chain).
Did you try force-closing the channel from your end again? That should be possible, your node should still have a version of the commitment transactions. The other node should then be able to get the funds back with the SCB.

**Comment by LNBIG-COM** [comment] 2021-07-12 10:26
> Did you try force-closing the channel from your end again? That should be possible, your node should still have a version of the commitment transactions. The other node should then be able to get the funds back with the SCB

I will try but this channel in list of 'closedchannels' (not in `pendingchannels` or in `listchannels`). Are you sure that I can force it again? I'll try now and write down the result

**Comment by LNBIG-COM** [comment] 2021-07-12 10:30
`l closechannel --force e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07 1
[lncli] rpc error: code = Unknown desc = channel not found
`

**Comment by LNBIG-COM** [comment] 2021-07-12 10:39
As I already described the situation, the channel was closed from my side some time ago. And there was no closing transaction, because the initiator was the other party and did not use the channel. And judging by the status (`FUNDING_CANCELED`, the server thought then that the channel opening transaction did not get into the mempool (maybe there were low commissions - 3 sat/vbyte). Perhaps, as I suppose now, then two weeks passed after the opening and the transaction did not get into the mempool (if the pool was often overloaded). Therefore, the server could close this channel, but after the transaction was confirmed.The important thing is that the backup (SCB) does not help to return the funds, although the remote site is online and owner too.

**Comment by guggero** [comment] 2021-07-12 11:06
Okay, worth a try. I don't know how a channel gets into the `FUNDING_CANCELED` state... Normally `lnd` doesn't give up on a channel if the possibility of the funding TX reaching the mempool exists.

If the user still has their seed and you are willing to help them, I guess you can use the [`chantools rescuefunding`](https://github.com/guggero/chantools/blob/master/doc/chantools_rescuefunding.md) command (the sweep addr should be an address that belongs to the user, that's where the funds will go) and the user then has to run `chantools signrescuefunding`. If you get an error when running `rescuefunding` because it cannot find the channel, then I need to add some more functionality to `chantools` to get it working.

**Comment by Roasbeef** [comment] 2021-07-12 19:05
> Okay, worth a try. I don't know how a channel gets into the FUNDING_CANCELED state... Normally lnd doesn't give up on a channel if the possibility of the funding TX reaching the mempool exists.

Assuming they were the responder, it sounds like the channel was opened during a high fee period, and failed to be confirmed after a few days. In this case, the lnbig node only has a close summary for that channel (should show up in `lncli closedchannels`). However, since this channel was completely forgotten and never actually opened/used in the first place, [I think we don't have a `LastChanSyncMsg` for it](https://github.com/lightningnetwork/lnd/blob/master/peer/brontide.go#L2851), so we won't retransmit anything on peer connection, as the channel never really existed from our PoV.

**Comment by Roasbeef** [comment] 2021-07-12 19:07
In other words, you can't close the channel as from your PoV, the channel never actually existed, since the _responder_ never obtains the funding transaction. In this case, SCB is working as expected, as a channel can't be forced closed unless the funding transaction is broadcast/confirmed, and in this case, it was never confirmed. 

Since the channel was never confirmed, the initiator can double spend the original funding output and reclaim their funds.

**Comment by Roasbeef** [comment] 2021-07-14 00:08
Closing this since things are working as expected: the channel was never confirmed (no funding transaction in the mempool), so even if we had a channel re-establishment message for it, it would be an orphan until the funding transaction confirmed.

**Closed by Roasbeef** 2021-07-14 00:08 UTC

**Comment by LNBIG-COM** [comment] 2021-07-23 09:17
> Closing this since things are working as expected: the channel was never confirmed (no funding transaction in the mempool), so even if we had a channel re-establishment message for it, it would be an orphan until the funding transaction confirmed.

You don't understood
The initiator - the remote side, not LNBiG
And funding transaction was confirmed may be through a long time but before I think the LNBiG was closed channel as not funded. Now the remote side has SCBH and ask me to help.

**Comment by LNBIG-COM** [comment] 2021-07-23 09:29
It turns out that other nodes may face a similar situation. It's rare, of course. In principle, this is similar to another situation - as if the other side also lost all of the channel data.

@Roasbeef, I do not understand the protocol at a deep level, but it seems to me that there is a lack of a certain deterministic key for the first funding transaction, until the initiator has time to use the channel. That is, so that this key can be calculated based on the SCB, and then, based on it, the closing transaction could be built without the participation of the remote side. Until the channel has been used even once, the side with zero balance (not initiator) does not lose anything and there can be no penalties in principle (BREACH case). Based on this, the first channel opening transactions from the initiator's side could be deterministically calculated from the key (from SCB). And maybe this is how it works now?

**Comment by LNBIG-COM** [comment] 2021-07-23 09:51
Here are full logs about this case.
It turns out that 19 days have passed between the time the peer broadcasted the transaction and how it was confirmed.

```
2021-04-16 01:49:12.408 [INF] FNDG: Recv'd fundingRequest(amt=0.02 BTC, push=0 mSAT, delay=240, pendingId=7d2d3e61d62d345e74ebde0275ea9a6a27015f2961feec20025e52153133add8) from peer(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a)
2021-04-16 01:49:12.424 [INF] FNDG: Requiring 3 confirmations for pendingChan(7d2d3e61d62d345e74ebde0275ea9a6a27015f2961feec20025e52153133add8): amt=0.02 BTC, push_amt=0 mSAT, committype=tweakless, upfrontShutdown=
2021-04-16 01:49:12.428 [INF] FNDG: Sending fundingResp for pending_id(7d2d3e61d62d345e74ebde0275ea9a6a27015f2961feec20025e52153133add8)
2021-04-16 01:49:12.849 [INF] FNDG: completing pending_id(7d2d3e61d62d345e74ebde0275ea9a6a27015f2961feec20025e52153133add8) with ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-16 01:49:12.857 [INF] FNDG: sending FundingSigned for pending_id(7d2d3e61d62d345e74ebde0275ea9a6a27015f2961feec20025e52153133add8) over ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-16 01:49:12.857 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-16 01:49:12.860 [INF] CNCT: ChannelArbitrator(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): starting state=StateDefault, trigger=chainTrigger, triggerHeight=679421
2021-04-16 01:49:12.860 [INF] NTFN: New spend subscription: spend_id=360, outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c, height_hint=679421
2021-04-16 01:49:12.861 [INF] NTFN: Dispatching historical spend rescan for outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c, start=679421, end=679421
2021-04-16 01:49:12.873 [INF] CNCT: Close observer for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) active
2021-04-16 01:49:12.873 [INF] NTFN: New confirmation subscription: conf_id=57, txid=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07, num_confs=3 height_hint=679421
2021-04-16 01:49:12.873 [INF] FNDG: Waiting for funding tx (e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07) to reach 3 confirmations
2021-04-16 01:49:13.112 [INF] NTFN: Historical spend dispatch finished for request outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c (start=679421 end=679421) with details: <nil>
2021-04-16 11:11:07.603 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-16 11:11:07.603 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-17 17:32:34.133 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-17 17:32:34.133 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-18 03:53:24.275 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-18 18:35:30.045 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-18 18:35:30.045 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-21 01:31:47.949 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-21 01:31:47.950 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-21 03:00:56.180 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-22 11:16:02.584 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-22 21:48:10.435 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-23 20:14:26.112 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-23 20:25:37.521 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-25 18:18:41.537 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-25 19:08:51.431 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-25 22:33:33.650 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-25 23:03:00.935 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-26 21:14:56.346 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-27 02:06:02.690 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-27 04:41:26.778 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-27 20:16:08.824 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-27 21:39:57.272 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-27 21:44:55.236 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-27 21:44:55.236 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-27 22:26:11.421 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-27 22:26:11.421 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-28 04:03:09.103 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-28 05:58:29.180 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-28 10:46:23.394 [WRN] FNDG: canceled waiting for funding confirmation, stopping funding flow for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-28 10:46:23.394 [ERR] FNDG: Unable to advance pending state of ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): error waiting for funding confirmation for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): epoch client shutting down
2021-04-28 10:51:09.823 [INF] NTFN: New spend subscription: spend_id=222, outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c, height_hint=680945
2021-04-28 10:51:09.823 [INF] NTFN: Dispatching historical spend rescan for outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c, start=680945, end=680945
2021-04-28 10:51:10.263 [INF] CNCT: Close observer for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) active
2021-04-28 10:51:10.997 [INF] NTFN: Historical spend dispatch finished for request outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c (start=680945 end=680945) with details: <nil>
2021-04-28 10:51:13.675 [INF] CNCT: ChannelArbitrator(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): starting state=StateDefault, trigger=chainTrigger, triggerHeight=680945
2021-04-28 10:51:25.590 [INF] NTFN: New confirmation subscription: conf_id=3, txid=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07, num_confs=3 height_hint=680945
2021-04-28 10:51:25.611 [INF] FNDG: Waiting for funding tx (e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07) to reach 3 confirmations
2021-04-28 10:51:26.749 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-28 10:51:26.849 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-28 10:51:26.849 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-28 13:28:55.345 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-28 13:28:55.345 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-28 15:18:03.027 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-28 15:35:13.739 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-28 16:06:59.765 [ERR] FNDG: Unable to advance pending state of ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): error waiting for funding confirmation for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): epoch client shutting down
2021-04-28 16:06:59.765 [WRN] FNDG: canceled waiting for funding confirmation, stopping funding flow for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-28 16:08:53.359 [INF] NTFN: New spend subscription: spend_id=36, outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c, height_hint=680981
2021-04-28 16:08:53.359 [INF] NTFN: Dispatching historical spend rescan for outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c, start=680981, end=680981
2021-04-28 16:08:53.545 [INF] CNCT: Close observer for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) active
2021-04-28 16:08:54.021 [INF] NTFN: Historical spend dispatch finished for request outpoint=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, script=0 b46aed556fc9b75ae259332b7a57b0c90ae39dcbeddcd39a4f933a75a3f29a3c (start=680981 end=680981) with details: <nil>
2021-04-28 16:08:57.120 [INF] CNCT: ChannelArbitrator(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): starting state=StateDefault, trigger=chainTrigger, triggerHeight=680981
2021-04-28 16:09:07.206 [INF] NTFN: New confirmation subscription: conf_id=3, txid=e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07, num_confs=3 height_hint=680981
2021-04-28 16:09:07.219 [INF] FNDG: Waiting for funding tx (e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07) to reach 3 confirmations
2021-04-28 16:09:08.136 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-28 16:09:09.989 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-28 16:09:09.989 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-29 11:51:22.570 [INF] PEER: NodeKey(0290ba7b9d7d16d86c6ab71b43258f38e6eea12c71da110a2d895c6ae20fcdc01a) loading ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-04-29 11:51:22.570 [WRN] PEER: Unable to find our forwarding policy for channel e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1, using default values
2021-04-29 12:53:12.530 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-04-30 15:32:47.904 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-05-01 12:05:57.360 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
2021-05-02 02:55:33.424 [WRN] FNDG: canceled waiting for funding confirmation, stopping funding flow for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1)
2021-05-02 02:55:33.426 [ERR] FNDG: Unable to advance pending state of ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1): timeout waiting for funding tx (e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) to confirm
2021-05-02 23:08:23.948 [WRN] CHBU: Replacing disk backup for ChannelPoint(e4500f1e34bd2d6924265efcf95e92c4fbbe0d0e80955fa4eb396eb23e09ce07:1) w/ newer version
```
