### ISSUE TITLE
[bug]:  LND still produces unbroadcastable transactions

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#7622] opened 2023-04-20 23:19 UTC
### Background

While trying to open a channel, LND decided to use a bunch of near-dust outputs and produced huge unbroadcastable transaction

BitcoinCore usually throws `error code: -6 error message: Transaction too large` on similar txs, but LND takes them seriously and pretends that its ok and waits for the channel to confirm while locking out those utxos.
I double checked the produced txhex, it _is_ huge and any web broadcasting service throws error on it.

### Your environment

* version of `lnd`  `   "commit": "v0.16.0-beta",        "commit_hash": "51df3e5b1ea2f1f749652cecf26e7471d35aa629", `
* which operating system (`uname -a` on *Nix)  `Linux lnd3 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend:   `neutrino`

### Steps to reproduce

* Have a lot of dust utxos
* try to open a channel

### Expected behaviour

Throw an error and NOT lock out utxos so user can retry (maybe use sendcoins to consolidate)

### Actual behaviour

Channel negotiated and awaits being confirmed. But in reality such tx doesnt make it to the mempool

I noticed https://github.com/lightningnetwork/lnd/pull/7513 but this mentions only logging around the issue..?

**Comment by alexbosworth** [comment] 2023-04-20 23:20
is this different from https://github.com/lightningnetwork/lnd/issues/6556 ?

**Comment by Roasbeef** [comment] 2023-04-20 23:20
Tracked here along with some implementation considerations: https://github.com/lightningnetwork/lnd/issues/4760

**Comment by Roasbeef** [comment] 2023-04-20 23:23
in #6556 we were unable to repro the base scenario (lnd _will_ remove the tx from the wallet). However the core issue is that the funding manager will broadcast and not realize that the tx is bad and wait (leaving the allocated UTXOs locked still).

**Comment by Overtorment** [comment] 2023-04-20 23:23
oops indeed probably a duplicate of https://github.com/lightningnetwork/lnd/issues/6556

the only difference is in this ticket i tried opening a channel, and in old ticket looks like i tried to use `sendcoins`

might be good to close, up to you.

**Comment by Overtorment** [comment] 2023-04-20 23:32
thinking about it, probably more and more node operators will encounter it (dust produced as result of stuck htlcs settling onchain..?), and it might be worth making a dirty late stage pre-broadcast assertion so it throws with visible error to node operator

**Comment by ellemouton** [comment] 2023-04-21 12:24
closing this as a duplicate of #4760. Feel free to continue discussions or to post more details there 👍

**Closed by ellemouton** 2023-04-21 12:24 UTC
Labels: bug, needs triage
