### ISSUE TITLE
lnd doesn't start. unable to read channel data

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1633] opened 2018-07-26 07:39 UTC
happened after #1629  issue and upgrading to latest master.

```lnd version 0.4.2-beta commit=098cd940e312c111dda3efe5fa2c7d375743f770```

```
2018-07-26 06:59:17.348 [ERR] HSWC: ChannelLink(515064:2114:0) unable to synchronize channel states: link shutting down
2018-07-26 06:59:17.348 [INF] HSWC: ChannelLink(85bd7a4094502a0a47a77d3012d5f31247a6819612c8bb842a283a36969ce4cc:0) has exited
2018-07-26 06:59:17.350 [ERR] DISC: channel  announcement proof for short_chan_id=565949421248315392 isn't valid: can't verify second bitcoin signature
2018-07-26 06:59:17.350 [ERR] FNDG: Unable to send channel proof: channel  announcement proof for short_chan_id=565949421248315392 isn't valid: can't verify second bitcoin signature
2018-07-26 06:59:17.350 [ERR] FNDG: error sending channel announcement: channel announcement failed: channel  announcement proof for short_chan_id=565949421248315392 isn't valid: can't verify second bitcoin signature
2018-07-26 06:59:17.360 [INF] LTND: Shutdown complete
unable to fetch open channels for peer 035c0fe76eea9faf84d630cf749f3187e5b54b22c0e5a50079d4ccdd4a2b00c11b: unable to read channel for chain_hash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000, node_key=035c0fe76eea9faf84d630cf749f3187e5b54b22c0e5a50079d4ccdd4a2b00c11b: unable to read channel data for chan_point=d0ce726c9c344ec61f34c6c51794cbd7c0e6cbfd82725fd3720f746ef28ddeeb:0: unable to fetch chan info: no chan info found
```

**Comment by halseth** [comment] 2018-07-26 10:31
This is caused by the server calling `PruneLinkNodes()` at startup, and failing to find a channel's channel info in the database.

For some reason the channel is found in the `chainBucket` but not in the `chanBucket` 🤔

**Comment by robtex** [comment] 2018-07-26 11:35
ok. thanks. sound like you found it.
so, shall i add a strategic continue there somewhere?

**Comment by robtex** [comment] 2018-07-26 12:57
seems to have helped! thank you very much!

**Comment by Roasbeef** [comment] 2018-07-26 21:50
This could happen in the past as the buckets were auto created, so the top level bucket would exist, but the channel not actually present. It's been fixed in master since then.

**Closed by Roasbeef** 2018-07-26 21:50 UTC
