### ISSUE TITLE
Reconnection to LND after network switch is dropped

### ISSUE THREAD

**Issue by frennkie** [lightningnetwork/lnd#1930] opened 2018-09-17 19:26 UTC
### Background

I'm using the Eclair app (Testnet) on my android and had an active (online) open channel. Then I switched off the Wifi and my phone moved to the LTE/4G network.
In my LND I see 20-30+ messages of this kind (and the Channel stays `OFFLINE` in Eclair.

```
2018-09-17 19:14:52.056 [WRN] SRVR: Received inbound connection from peer 03b9...fac0, but already connected, dropping conn
2018-09-17 19:14:53.207 [INF] SRVR: New inbound connection from 111.222.111.333:46744
``` 

Is this an issue with
* my LND settings
* Eclair
* LND
* the protocol?

### Your environment

* version of `lnd`
  * `v0.5-beta ()`
* which operating system (`uname -a` on *Nix)
  * `Linux host 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
  * `bitcoind`
* any other relevant environment details

### Steps to reproduce

Use Ecliar Testnet app and connect to (testnet) LND node. Switch to another connection (e.g. from LTE to Wifi or vice-versa).

### Expected behaviour

The channel in Ecliar should go `OFFLINE` and then re-connect and become `ONLNE` again.

### Actual behaviour

The channel stays `OFFLINE` and the lnd.log is flooded with `Received inbound connection from peer 03b9...fac0, but already connected, dropping conn` messages.

**Comment by frennkie** [comment] 2018-09-17 19:28
Ah.. ok.. not enough patience:

```
Disconnecting 111.222.111.333:47124, reason: Peer 111.222.111.333:47124 no answer for 5m0s -- disconnecting
```

So there is a 5 minute timeout. Is this reasonable? Can this be configured?

**Comment by cfromknecht** [comment] 2018-09-17 23:01
It seems like connection initially established over wifi was never closed by the eclair side, so we think still think we have a stable conn. Seems strange to me that the app would continue making outbound connection before closing the old one? I would have expected the OS to close them when switching networks, but that's just speculation haha. @sstone @pm47 any thoughts?

another thing that looks like it could be improved is adding some sort of exponential backoff when reconnecting unsuccessfully to avoid flooding nodes.

**Comment by cfromknecht** [comment] 2018-09-21 21:22
@sstone If the connection were closed, then we should have gotten an error when trying to write ping messages out. If five minutes had elapsed, this would seem at the very least that we were able to write 4 or 5 pings that went unreplied. @frennkie do you have any more logs on the LND side to see whether or not messages were still being sent?

LND also imposes a write timeout of 50s https://github.com/lightningnetwork/lnd/blob/master/peer.go#L46:2, so I'm skeptical that the connection was actually closed. If the write timeout is hit, we will disconnect the peer well before 5 mins.

> When we discussed this we came to the conclusion that switching to the new connection (which we know works) is the only safe way, as sometimes it may be very difficult to detect that a connection is dead.

I don't recall that being the conclusion. My recollection is that for some cases that policy is stable, and other times it isn't. In this case, that would be the appropriate response, though there are others where unilaterally using this policy will result in connection loops. The solution I worked on with that gracefully handles a number of widely used connection selection policies was documented in https://github.com/lightningnetwork/lnd/pull/1351

**Comment by sstone** [comment] 2018-09-21 22:09
User turned wifi off and switched to 4G, I don't see how the connection could have been kept alive (on the mobile device).

I'm pretty sure that we concluded that switching to the new connection is the safest policy, because detecting dead connections is very hard. I even managed to reproduce the issue between 2 lnd nodes: A disconnects but B does not see that its incoming connection is dead and refuses to let A connect again (see #1337). We can discuss this again during the next dev meeting.

**Comment by sstone** [comment] 2018-09-21 22:13
I think I understand why we disagree: when we discussed the issue on github we did not reach a definite conclusion, but we also discussed it during one of our LN dev meetings, that's what I was referring to.

**Closed** 2018-12-18 04:57 UTC
Labels: interop, networking, p2p, server
