### ISSUE TITLE
REST API prioritize IPv4 over .onion when .onion peer connection is requested 

### ISSUE THREAD

**Issue by elkimek** [lightningnetwork/lnd#3160] opened 2019-06-04 21:52 UTC
### Background

When connecting to new onion peer where the node has both IPv4 and onion addresses available, LND choose to connect to IPv4 over onion.

### Your environment

* 0.6.1beta
* Linux nodl.it
* 0.18.1
* see https://github.com/ShahanaFarooqui/RTL/issues/154

### Steps to reproduce

Asked to reproduce it a member on LND slack and RTL dev confirmed.

### Expected behaviour

Should been connected to onion address

### Actual behaviour

Was connected to IPv4

**Comment by wpaulino** [comment] 2019-06-04 21:53
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/2387.

**Closed by wpaulino** 2019-06-04 21:53 UTC
