### ISSUE TITLE
Initial sync slows to a crawl during the `Fetching filter for height X` sync stage

### ISSUE THREAD

**Issue by mrfelton** [lightningnetwork/lnd#1744] opened 2018-08-17 10:27 UTC
### Background

There seems to be something a little wonky with the initial lnd sync process. The basic sequence of log messages I see is:

1. `Sending getheaders` all the way until `Caught up to height` (right up to the current block height). This takes about 4 minutes.

2. `Fetching filter for height=1383641`
  ... this message prints over and overt again until eventually I get the following warning in the logs
  `Unable to synchronize wallet to chain: Couldn't get cfheader for block 000000000017ecc6bc0b552574a5c83318d7fca6757884eda64fff59f8d5af24 from database`

3. Whilst (2) is happening, it also starts `Sending getcfheaders` As with (1) it does this all the way from 0 up until the current block height. This also takes about 4 minutes.

4. Eventually, I see the message `Fully caught up with cfheaders, waiting at tip for new blocks`

5. Now we start another set of log messages `Writing filter headers up to height=2000`... again, this runs all the way from 0 up until the current block height. This also takes another 4 minutes or so

6. At some point whilst it is writing the filter headers (5), I then see the message `Rescan became current at 12000 (000000004ad8f1f39fa3e3eb43791b9283337b09b06b4e75164dc5a9cb0262ff), subscribing to block notifications`. Which kicks off another set of  messages `Fetching filter for height=12001`. However, unlike the other 3 stages which each took about 4 minutes each and with numbers incrementing at 1000 or so per log message output, this part of the synbc stage increments at a much much slower rate - perhaps as slow as 10 blocks a second.

Between 09:28:16 and 09:34:05 it got from `12001` to `13643`. Clearly at this rate it was going to take longer than actually syncing the full blockchain! At this point stopped and restarted lnd...

This time, it started doing `Fetching filter for height=X` again... however, it started at `1383641` (it was only up to `13643` when I terminated lnd a minute before) and after about 90 seconds it got to the current block height and then completed the sync process with:

```
[DBG] BTCN: Rescan became current at 1384089 (000000000000000ef7a8b278519331b67deece3c8031dc40f6584d10d4925f99), subscribing to block notifications +2ms
[INF] LNWL: Catching up block hashes to height 1384089, this might take a while +1ms
[INF] LNWL: Done catching up block hashes (edited)
```

This is with the latest BTCD on the backend, and a recent checkout from lnd master

I've tried this several time over and the result is the same each time. On first startup after creating a new wallet the sync process effectively never ends as the part where it does `Fetching filter for height=X` is just too slow. Stopping and restarting lnd gets it to jump forward in the `Fetching filter for height=X` process almost to the end and this time it completes within a minute or so.

I don't fully understand this process and what all the different messages mean. But it does appear that on a fresh sync there is a problem in the `Fetching filter for height X` stage. Firstly it is very slow (10 blocks a second). Secondly, it initially starts doing it from about block 12001 and increments at a rate so slowly that it would probably take several days to get up to the current block height. But if you stop and start lnd then it suddenly jumps forward  to block 1383641 and completes within a minute or so.

### Your environment

* version of `lnd`: lnd version 0.4.2-beta commit=643618b4f64ed0ebc62e3e82b8ea9f79ff72db77
* which operating system (`uname -a` on *Nix): Mac
* version of `btcd`, `bitcoind`, or other backend: `latest`

### Steps to reproduce

1. Set the log level to debug.
2. Create and unlock a new wallet
3. Monitor the log messages during the inital sync.

### Expected behaviour

It should sync from start to finish in a predictable and reliable way.

### Actual behaviour

The sync effectively stalls and slows down to a crawl after about 10 minutes. Stopping and restarting lnd makes it complete in a reasonable time.

**Comment by mrfelton** [comment] 2018-08-17 13:58
I believe this may be related to https://github.com/lightningnetwork/lnd/issues/511 in which they also got this `Unable to synchronise wallet to chain: Couldn't get cfheader for block ...` error.

**Comment by mrfelton** [comment] 2018-08-17 16:44
Regarding the sync speed. To be clear I observe 3 distinct phases:

1. Syncing data from `getheaders` (about 4 minutes to get all 1384118)
2. Syncing data from `getcfheaders` (about 4 minutes to get up to 1380000)
3. Syncing data from `getcfilters`
 a) **about 5 days or more** - IF you start lnd and let it run until synced
 b) about 120 seconds - IF you stop and restart lnd mid-way through the initial sync.

In case (a) it makes calls to `getcfilters` starting from about block 20000 and increments at a rate of about 5-10 blocks per second.

In case (b) it  makes calls to `getcfilters` starting from about block 1380000 and increments at a rate of about 5-10 blocks per second.

`getcfheaders` & `getcfilters` run at the same time, although `getcfilters` is about 1/100 of the speed of `getcfheaders`

So, as it stands right now the only way to sync lnd within a reasonable amount of time is to restart lnd at least once, towards the end of the sync process.

Here, you can see the point at which it appears to fail at fetching the more recent filters, and then reverts to fetching them from block 20000

<img width="1419" alt="screenshot 2018-08-17 15 40 33" src="https://user-images.githubusercontent.com/200251/44278169-7857c680-a24d-11e8-839b-b3ff63fcb3c9.png">

**Comment by Roasbeef** [comment] 2018-08-17 20:35
Are you able to reproduce this with a _fresh_ sync? So not restarting at all throughout the process. Also can you try running without Zap? They haven't been very active within this repo, or various chats in months, so I'm unsure if they're actively keeping up with the latest version of `lnd`, nor neutrino. 

I'm able to sync no problem via multiple `btcd` nodes on my end, I'd check that you're properly installing those nodes as well as making sure `dep` is fetching all the latest dependencies locally.

**Comment by Roasbeef** [comment] 2018-08-17 20:36
It looks like you have an older wallet or perhaps aren't setting the birthday of the wallet properly (rather are overwriting it somewhere?). It shouldn't be fetching filters until chain tip, however if your birthday is in the _past_ then it may do so.

**Comment by mrfelton** [comment] 2018-08-17 21:30
Hey @Roasbeef - yes. I can reproduce this with a fresh sync and have done a number of times. For context, I'm one of the main developers for Zap and I have been activly working on the lnd integration for Zap Desktop, particularly the synchronisation process in which we monitor the log output from lnd in order to determine the current sync progress and report this to users of the app as part of the wallet onboarding process, with a progress bar and a realtime summary of the sync progress etc.

We are running the latest version of BTCD (most recent commit on the master branch) within a docker environment, from https://hub.docker.com/r/lnzap/btcd/. This was built from this docker file: https://github.com/LN-Zap/docker-btcd/tree/btcd which we maintain (just just builds and runs the btcd master branch).

We are running the latest version of lnd from https://github.com/LN-Zap/lnd/releases which is a build from the tip of the master branch from earlier today. We build and publish our own pre-compiled versions of lnd that we bundle with our app, which you can see here https://github.com/LN-Zap/lnd/releases. It would be nice if there was access to a nightly build of lnd, but short of this we have been building and publishing these binaries quite regularly, and keeping our app in sync with the work you guys are doing.

> Are you able to reproduce this with a fresh sync? So not restarting at all throughout the process.

If I don't restart the process then it would literally take a week (based on a couple of hours of monitoring the logs very closely - the rate at which it syncs is very slow). So I haven't actually let it run all the way through as I don't really have the time to tie up my machine for this long, espectially when I know that if I stop and restart lnd the sync will complete in a very reasonable amount of time. I'll leave it overnight tonight though, just for the sake of interest in knowing how far it will get!

> Also can you try running without Zap?

We have had users report the same issue who are running their own version of lnd outside of the context of zap - although we are doing nothing in zap other than spawning the process, initiating the sync, and monitoring the logs. I will certainly try though.

> They haven't been very active within this repo, or various chats in months, so I'm unsure if they're actively keeping up with the latest version of lnd, nor neutrino.

I know there was a bit of a lul for a while. I joined the Zap team a couple of months ago, we're doing pretty active development, and have been keeping up with lnd as best we can.

> I'm able to sync no problem via multiple btcd nodes on my end (syncs testnet in about 5 mins), I'd check that you're properly installing those nodes as well as making sure dep is fetching all the latest dependencies locally.

I have tried this from two separate, fully synced btcd nodes using the above mentioned docker image which we maintain - which just runs a build of the latest code from btcsuite/btcd master. There were no build related issues when building this docker image.

Is there any chance that you could provide access to one of your btcd nodes so that we could give a go against that? Uou could PM me the details on slack if you like.

Cheers,
- Tom

**Comment by mrfelton** [comment] 2018-08-17 21:46
> It looks like you have an older wallet or perhaps aren't setting the birthday of the wallet properly (rather are overwriting it somewhere?). It shouldn't be fetching filters until chain tip, however if your birthday is in the past then it may do so.

@Roasbeef We don't do anything with regards to the wallet birthday. I created this brand new wallet today (which is just a call to `initWallet` (see https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/lnd/methods/walletController.js#L136-L162) followed by a call to `unlockWallet` to start the sync (see https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/lnd/methods/walletController.js#L120-L134).

How or where would the birthday of the wallet be set to anything other that what it should be (which is what?)?

The only thing I seen about the wallet birthday is in the logs:

>   zap:lnd  [INF]  2018-08-17 13:25:11.785 [INF] LNWL: Seed birthday surpassed, starting recovery of wallet from height=1383641 hash=000000000017ecc6bc0b552574a5c83318d7fca6757884eda64fff59f8d5af24 with recovery-window=250 +22ms

<img width="1439" alt="screenshot 2018-08-17 23 42 47" src="https://user-images.githubusercontent.com/200251/44290070-49eee100-a277-11e8-812d-cb9ee3779c06.png">

**Comment by Roasbeef** [comment] 2018-08-17 23:13
Closing for now as it was discovered on Slack that by removing the recovery window option, `lnd` will do a full regular sync rather than trying to scan the entire chain for non-existent funds.

**Closed by Roasbeef** 2018-08-17 23:13 UTC

**Comment by mrfelton** [comment] 2018-08-18 07:02
@Roasbeef if the recovery window was set to `250` should that really cause lnd to resync every single filter from the beginning of time? It is not clear from the documentation that this should be the case:

https://github.com/lightningnetwork/lnd/blob/4c51f9b5ae4ab541b17824b4e0eea0be6929d7ac/lnrpc/rpc.proto#L142-L149

**Comment by Roasbeef** [comment] 2018-08-20 23:31
> when restoring a wallet seed
It's only meant to be used if you're restoring the wallet from a seed. Otherwise it should be set to zero.
