### ISSUE TITLE
Payment was received, but settle is false

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#2909] opened 2019-04-08 08:51 UTC
### Background

On zigzag.io we have received payment from Bluewallet user who was trying to make lightning BTC to BTC exchange. He has made lightning payment to zigzag node, but invoice hasn't been settled, later he contacted us and presented proper payment proof.

By asking Igor from Bluewallet, it was found that payment was made over several hops. Also from `listpayments` output it seems as if payment was made before expiration time.

-----
Zigzag `listinvoice` output:
```
{
            "memo": "Zigzag.io exchange BTC to BTC (1e397bab-9328-4188-975e-39cdfffbbc54)",
            "receipt": "emlnemFn",
            "r_preimage": "QOpbMdnfqjdJq3A+LurcyKKe62rYj4esxB0XsMBp39I=",
            "r_hash": "WYHTqravUi8ELekKOl2+qiE92ysRlu1OxKc3DHRXdEE=",
            "value": "590000",
            "settled": false,
            "creation_date": "1554230098",
            "settle_date": "0",
            "payment_request": "lnbc5900u1pw2826jpp5txqa824k4afz7ppday9r5hd74gsnmketzxtw6nky5umscazhw3qsdrdtf5kw7npvuhxjmeqv4uxx6rpdenk2gzz23pjqar0ypp9gseq9qck2veexa3xzc3d8yenywpdxscnswpd8ymn2efdxvukxerxvenxycnrx56zjcqpsxqzuy9kze6wvnta0r9rcm0ele48vsut7rly8farzx7564ysu4zsudurdqrzl0jtp8h5zwzum0h0rrmxd0ws39wlakulf3fsk44yhru2zryzcpn6fpas",
            "description_hash": null,
            "expiry": "900",
            "fallback_addr": "",
            "cltv_expiry": "16",
            "route_hints": [
            ],
            "private": false,
            "add_index": "17691",
            "settle_index": "0",
            "amt_paid": "0",
            "amt_paid_sat": "0",
            "amt_paid_msat": "0",
            "state": "OPEN"
        },
```

-----
Igor `listpayment` output:
```


{
            "payment_hash": "5981d3aab6af522f042de90a3a5dbeaa213ddb2b1196ed4ec4a7370c74577441",
            "value": "590000",
            "creation_date": "1554230615",
            "path": [
                "022c699df736064b51a33017abfc4d577d133f7124ac117d3d9f9633b6297a3b6a",
                "02bb24da3d0fb0793f4918c7599f973cc402f0912ec3fb530470f1fc08bdd6ecb5",
                "0232e20e7b68b9b673fb25f48322b151a93186bffe4550045040673797ceca43cf"
            ],
            "fee": "2",
            "payment_preimage": "40ea5b31d9dfaa3749ab703e2eeadcc8a29eeb6ad88f87acc41d17b0c069dfd2",
            "value_sat": "590000",
            "value_msat": "590000000"
        },
```
----
Also, I have made manual conversations to simplify the check:
```
Payment preimage:
hex: 40ea5b31d9dfaa3749ab703e2eeadcc8a29eeb6ad88f87acc41d17b0c069dfd2
base64: QOpbMdnfqjdJq3A+LurcyKKe62rYj4esxB0XsMBp39I=

Payment hash:
hex: 5981d3aab6af522f042de90a3a5dbeaa213ddb2b1196ed4ec4a7370c74577441
base64: WYHTqravUi8ELekKOl2+qiE92ysRlu1OxKc3DHRXdEE=
```

### Your environment
* version of `lnd`
```
"0.5.2-99-beta commit=queue/v1.0.1-132-gc7ca387a9d92a1a2cd0f6e56b61ff04b9adc062d"
```
* which operating system (`uname -a` on *Nix)
```
Linux 028ad061abdc 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 Linux
```

* version of `btcd`, `bitcoind`, or other backend
```
bitcoind - 0.17.0
```

### Expected behaviour
Invoice being settled.

### Actual behaviour
Invoice is not settled.

**Comment by halseth** [comment] 2019-04-08 12:10
Related https://github.com/lightningnetwork/lnd/issues/2032

**Comment by joostjager** [comment] 2019-04-09 07:52
@AndrewSamokhvalov do you have (debug) logs from around the time the payment happened?

**Comment by AndrewSamokhvalov** [comment] 2019-04-09 09:11
@joostjager Started checking logs, and found that seems like it is related with channel close, checked invoice again, and see that invoice is settled now.

**Comment by joostjager** [comment] 2019-04-09 09:20
This was a regular invoice right, no hodl invoice?

Normally a regular invoice should be marked settled almost directly after the htlc is locked in. We have seen a similar thing happening in a different context.

Would you mind sharing the log with me? I am pretty eager to find out the cause of this.

**Comment by joostjager** [comment] 2019-04-26 13:06
Linking https://github.com/lightningnetwork/lnd/pull/2913
Maybe this issue is caused by a corner case in on-chain resolution.

**Comment by Roasbeef** [comment] 2019-07-16 02:01
Fixed by the recent work in the router/switch.

**Closed by Roasbeef** 2019-07-16 02:01 UTC
Labels: P2, payments
