### ISSUE TITLE
LND unable to determine prune state of Litecoin-core (litecoind) node version 0.21.2rc1

### ISSUE THREAD

**Issue by qprimed** [lightningnetwork/lnd#6230] opened 2022-02-02 18:19 UTC
### Background
LND unable to determine prune state of Litecoin-core (litecoind) node version 0.21.2rc1

### Your environment
* LND Version: 0.14.1-beta commit=v0.14.1-beta, build=production, logging=default, debuglevel=info
* Linux 4.19.0-18-amd64 # 1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
* Litecoin Core version v0.21.2rc1
* Running in an LXC container

### Steps to reproduce
Update working litecoind v0.18.1 to 0.21.2rc1. Start previously working LND systemd service and unlock LND wallet.

### Expected behaviour
good things

### Actual behaviour
2022-02-02 12:59:07.843 [ERR] LTND: unable to create partial chain control: unable to determine if bitcoind is pruned: json: cannot unmarshal object into Go struct field SoftForks.softforks of type []*btcjson.SoftForkDescription
2022-02-02 12:59:07.843 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: json: cannot unmarshal object into Go struct field SoftForks.softforks of type []*btcjson.SoftForkDescription
2022-02-02 12:59:07.846 [INF] LTND: Shutdown complete

also opening this issue against litecoin-project/litecoin

**Comment by losh11** [comment] 2022-02-03 02:26
This failure is likely caused by a new bip8/9 version bit that's unknown to lnd. At first glance: patch the new version bit into ltcd, or btcd, this means that lnd will also fail to start on future pruned nodes with new feature activation bits.

**Comment by qprimed** [comment] 2022-02-03 06:56
@HannahMR 
If @losh11 is correct and unknown version bits indeed breaks dialog with the chain node then it ends up being a wider scoped issue -- perhaps a review of the "nice to have" triage tag may be warranted, no?

**Comment by realizecondition** [comment] 2023-01-25 02:42
I have this as well. Unfortunately I am brand new to both lightning and reasonably new to litecoin and so far it's not a great experience. I've just been following online tutorials trying to get a basic lightning node to work so I can try out what's supposed to be the future of money that grandma's going to use to pay Joe the plumber. Did you manage to find a workaround to get it to work? What is a version bit and do I have any control over that?

**Comment by saubyk** [comment] 2023-11-11 02:28
Closing this issue as LND will not be supporting Litecoin from 0.18 onwards

**Closed by saubyk** 2023-11-11 02:28 UTC
Labels: litecoin, P3
