### ISSUE TITLE
IP Change -> bad? 

### ISSUE THREAD

**Issue by waffi121** [lightningnetwork/lnd#1150] opened 2018-04-29 06:32 UTC
hey guys i have since yesterday a raspberry with btc core vers. 0.16 and lightning 0.4.1 online. my provider chance every day in the night my ip adresse. at the homepage: 1ml.com show me my old IP at. is this bad? is this automatically adjusted by lightning?

thank for yours horny project!

regards waffi

**Comment by guggero** [comment] 2018-04-29 08:32
Hi @waffi121 

I'm not 100% sure of what the consequences are if you have a new IP address and have channels open with peers that only know your old address. Probably most things would still work, assuming you still have outgoing connections with other peers.

But, the good news is, the code to automatically update your node's info is already on its way: see Pull Request #1109

For now, `lnd` does announce its IP address at startup, then every node in the network should update their entries for your node. But because this *currently* doesn't happen automatically, you could restart your lightning node every day to broadcast the new IP address.

Cheers,
guggero

**Comment by irekzielinski** [comment] 2018-04-29 09:41
Looks like a duplicate of #1057

**Comment by waffi121** [comment] 2018-04-29 14:56
Thank your for the infos. I will whait for the automatically update and start my raspberry from time to time new.

Have a nice day! 

Cherrs
waffi

**Closed** 2018-04-29 14:56 UTC

**Comment by Roasbeef** [comment] 2018-04-29 21:41
>  1ml.com show me my old IP at

Please don't treat these "explorers" as any source of ground truth. They shouldn't be used for anything other than looking a pretty visualizations. Their usefulness stops there.
