### ISSUE TITLE
rpc error feerate_per_kw below minimum

### ISSUE THREAD

**Issue by halfik** [lightningnetwork/lnd#1003] opened 2018-04-02 12:33 UTC
### Background

Get rpc error when trying to open channel. No matter if i use  --sat_per_byte or not.

### Your environment

* lnd 0.4
* Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
*  bitcoin core 15.1

### Steps to reproduce

Hard to say. Had no issues with opening channels before. Here is comand than results in this error:

> lncli openchannel 02dd65974654061fd0008fdd6c7436af613aa116d29769ed5bbf4e7e41eb0604e0 250000

> [lncli]  rpc error: code = Code(202) desc = feerate_per_kw 250 below minimum 253

>  lncli walletbalance
> {
>     "total_balance": "493296",
>     "confirmed_balance": "493296",
>     "unconfirmed_balance": "0"
> }

And some debug from lnd:

> 2018-04-02 14:29:07.179 [DBG] LNWL: Returning 1 sat/vbyte for conf target of 3
> 2018-04-02 14:29:07.179 [INF] LNWL: Performing funding tx coin selection using 1 sat/vbyte as fee rate
> 2018-04-02 14:29:07.181 [INF] SRVR: Disconnecting from 107.191.109.5:9735
> 2018-04-02 14:29:07.181 [DBG] SRVR: removing peer 107.191.109.5:9735
> 2018-04-02 14:29:07.181 [TRC] PEER: Disconnecting 107.191.109.5:9735, reason: server: disconnecting peer 107.191.109.5:9735
> 2018-04-02 14:29:07.182 [INF] PEER: unable to read message from 107.191.109.5:9735: read tcp 192.168.0.19:39506->107.191.109.5:9735: use of closed network connection
> 2018-04-02 14:29:07.182 [TRC] PEER: readHandler for peer 107.191.109.5:9735 done
> 2018-04-02 14:29:07.182 [TRC] PEER: Update stream for gossiper exited
> 2018-04-02 14:29:07.182 [TRC] PEER: writeHandler for peer 107.191.109.5:9735 done
> 2018-04-02 14:29:07.182 [DBG] SRVR: Peer 107.191.109.5:9735 has been disconnected
> 2018-04-02 14:29:07.182 [DBG] FNDG: Cancelling all reservations for peer 02f0addfe58ec34cef057c91aeca27f77d22b5c812b22c54759b85b8934c3179a0
> 2018-04-02 14:29:07.183 [DBG] FNDG: No active reservations for node: 02f0addfe58ec34cef057c91aeca27f77d22b5c812b22c54759b85b8934c3179a0
> 2018-04-02 14:29:07.183 [ERR] SRVR: unable to get channel links: unable to locate channel link bydestination hop id 02f0addfe58ec34cef057c91aeca27f77d22b5c812b22c54759b85b8934c3179a0
> 2018-04-02 14:29:07.183 [WRN] ATPL: Unable to open channel to 02f0addfe58ec34cef057c91aeca27f77d22b5c812b22c54759b85b8934c3179a0 of 0.00493296 BTC: not enough witness outputs to create funding transaction, **need 0.00493586 BTC only have 0.00493296 BTC  available**
> 2018-04-02 14:29:07.183 [INF] ATPL: Processing new external signal
> 2018-04-02 14:29:07.183 [DBG] ATPL: Retrying after previous channel open failure.
> 2018-04-02 14:29:07.185 [DBG] ATPL: Pending channels: (map[autopilot.NodeID]autopilot.Channel) (len=2) {
>  (autopilot.NodeID) (len=33 cap=33) {

### Expected behaviour

> [lncli]  rpc error: code = Code(202) desc = feerate_per_kw 250 below minimum 253

### Actual behaviour

Opened channel :)

**Comment by Roasbeef** [comment] 2018-04-02 19:30
This isn't really an issue with `lnd`. The error you're getting there is that some other impl doesn't like how low the fees are. As it's only _3 satoshis_ below their target value, IMO it should be accepted. 

Aside from that, this is a duplicate of #687.

**Closed by Roasbeef** 2018-04-02 19:30 UTC
