### ISSUE TITLE
Still pending channels and locked funds, after failed channel opening

### ISSUE THREAD

**Issue by derHase85** [lightningnetwork/lnd#710] opened 2018-01-31 18:56 UTC
When I'm trying to open a channel and opening fails, it happens that I've got still pending open channels with funds locked. And as there is no valid channel_point, I can not force to close the channel. I have to close all open channels, delete my channel.db and restart lnd to get my funds unlocked.

In the bitcoin mempool, there is also no transaction id with the channel point.

Log:

2018-01-31 18:33:21.296 [INF] FNDG: Recv'd fundingResponse for pendingID(7daa4958c24e7bd02f873d622ca77b866783c387c6a272cb50caacd396c1426f)
2018-01-31 18:33:21.406 [INF] FNDG: pendingChan(7daa4958c24e7bd02f873d622ca77b866783c387c6a272cb50caacd396c1426f): remote party proposes num_confs=3, csv_delay=144
2018-01-31 18:33:21.435 [INF] FNDG: Generated ChannelPoint(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1) for pendingID(7daa4958c24e7bd02f873d62273d622ca77b866783c387c6a272cb50caacd396c1426f)
2018-01-31 18:33:23.275 [ERR] FNDG: Unable to complete reservation sign complete: -25: Missing inputs
2018-01-31 18:33:23.276 [ERR] FNDG: Failing funding flow: (*lnwire.Error)(0x11a73f50)({
 ChanID: (lnwire.ChannelID) (len=32 cap=32) 7daa4958c24e7bd02f873d622ca77b866783c387c6a272cb50caacd396c1426f,
 Data: (lnwire.ErrorData) (len=19 cap=32) {
  00000000  2d 32 35 3a 20 4d 69 73  73 69 6e 67 20 69 6e 70  |-25: Missing inp|
  00000010  75 74 73                                          |uts|
 }
})

2018-01-31 18:33:23.276 [INF] SRVR: Attempting to send msgs 1 to: 024d2a7636c331eb2b9216ee40405e105f0b887479517f10b6f3cd0cf87ab280fa
2018-01-31 18:33:23.277 [INF] FNDG: Cancelling funding reservation for node_key=024d2a7636c331eb2b9216ee40405e105f0b887479517f10b6f3cd0cf87ab280fa, chan_id=7daa4958c24958c24e7bd02f873d622ca77b866783c387c6a272cb50caacd396c1426f
2018-01-31 18:33:23.277 [ERR] RPCS: unable to open channel to identityPub(024d2a7636c331eb2b9216ee40405e105f0b887479517f10b6f3cd0cf87ab280fa) nor peerID(0): -25: Missing inputs

**Comment by Roasbeef** [comment] 2018-01-31 19:04
From that error, it looks like your coin selection attempted to create a funding transaction without any inputs. In this case, so funds were committed and a restart should have sufficed. Can you provide any additional information concerning your setup, how you funded the wallet, etc? 

Also are those all the logs? If so, then the transaction itself was never even broadcast to the network.

**Comment by Roasbeef** [comment] 2018-01-31 19:06
This might have happened if you were connected to a node that wasn't actually aware of segwit. In this case, certain transaction serializations would look as if no inputs were actually present on the transaction. I think this is the most likely explanation with the information provided thus far.

**Comment by derHase85** [comment] 2018-01-31 19:38
That was all the relevant logs, yes. A Transaction was not broadcasted.

Im using LND with the latest commits from 28.01 with bitcoind on mainnet. I'm using bech32 addresses

I've connected to quantumgear.io

024d2a7636c331eb2b9216ee40405e105f0b887479517f10b6f3cd0cf87ab280fa@159.89.104.197:9735

I've checked if I'm connected to the node and then tried to open the channel.

lncli --tlscertpath tls.cert --macaroonpath admin.macaroon openchannel --sat_per_byte 10 024d2a7636c331eb2b9216ee40405e105f0b887479517f10b6f3cd0cf87ab280fa 500000

I've had the behaviour several times. Maybe 1 / 2 or 1 / 3  of every channel opening. It's not proven, but it seems to me, that I've had it also at following situations:

- trying to open a channel, while another channel is pending and has no confirmation yet. Confirmed balance was sufficient
- remote host disconnects before I open channel

I've also hat it with nodes, where in the past a channel was possible.

I've restarted lnd now and confirmed balance is now back, where it was before trying to open the channel. Put there is still a pending open channel in the list. And I haven't tried, if I can open a channel now.

For me it is not a problem at the moment, that the channel opening didn't work. That can happen. But it should not lock my funds until I restart lnd and it should clean pending channels.

**Comment by derHase85** [comment] 2018-01-31 19:54
Tried another open channel, and it failed with the same error. Maybe there's something fucked up in my bitcoin wallet part of lnd. But that is fine at the moment. But he now tries to start the channel links over and over again:

2018-01-31 20:44:29.579 [INF] HSWC: ChannelLink(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1) is starting
2018-01-31 20:44:29.583 [INF] HSWC: Added channel link with chan_id=e35dbd7f74d35b07aedc734a8f076260ab7326ab3706ca97aa1b355c665f9235, short_chan_id=((lnwire.ShortChanID) 0:0:0
)
2018-01-31 20:44:29.583 [INF] SRVR: Attempting to send msgs 4882 to: 024d2a7636c331eb2b9216ee40405e105f0b887479517f10b6f3cd0cf87ab280fa
2018-01-31 20:44:29.583 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1)
2018-01-31 20:44:29.584 [INF] HSWC: HTLC manager for ChannelPoint(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1) started, bandwidth=471040000 mSAT
2018-01-31 20:44:29.584 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1)
2018-01-31 20:44:29.588 [INF] PEER: unable to read message from 159.89.104.197:9735: EOF
2018-01-31 20:44:29.588 [INF] HSWC: Removing channel link with ChannelID(e35dbd7f74d35b07aedc734a8f076260ab7326ab3706ca97aa1b355c665f9235)
2018-01-31 20:44:29.589 [INF] HSWC: ChannelLink(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1) is stopping
2018-01-31 20:44:29.665 [WRN] FNDG: Received error for non-existent funding flow: (*lnwire.Error)(0x134caa20)({
 ChanID: (lnwire.ChannelID) (len=32 cap=32) 0000000000000000000000000000000000000000000000000000000000000000,
 Data: (lnwire.ErrorData) (len=57 cap=57) {
  00000000  6c 69 67 68 74 6e 69 6e  67 5f 63 68 61 6e 6e 65  |lightning_channe|
  00000010  6c 64 3a 20 57 49 52 45  5f 45 52 52 4f 52 20 28  |ld: WIRE_ERROR (|
  00000020  31 37 29 20 62 65 66 6f  72 65 20 66 75 6e 64 69  |17) before fundi|
  00000030  6e 67 20 6c 6f 63 6b 65  64                       |ng locked|
 }
})

2018-01-31 20:44:29.666 [ERR] HSWC: shutting down
2018-01-31 20:44:29.674 [INF] NTFN: Cancelling epoch notification, epoch_id=323
2018-01-31 20:44:29.675 [INF] HSWC: ChannelLink(34925f665c351baa97ca0637ab2673ab6062078f4a73dcae075bd3747fbd5de3:1) has exited

**Comment by Roasbeef** [comment] 2018-01-31 20:02
That second log dump is with a `clightning` node. They can get in a weird state where if they encounter an error, they'll just send the error, then reconnect almost immediately, and repeat the same cyle.

**Comment by Roasbeef** [comment] 2018-01-31 20:04
Also since the funding flow failed locally, the reservation should have been cancelled an inputs made available immediately. I'd check that your `bitcoind` node is actually running the latest version that is aware of segwit. The error is indicative of a parsing error as by consensus transaction w/o any inputs is invalid.

**Comment by Roasbeef** [comment] 2018-01-31 20:17
The `Missing inputs` error is not found in `lnd`, `btcd`, or `btcwallet`. Which points towards an incorrect setup with your `bitcoind` node.

**Comment by derHase85** [comment] 2018-01-31 20:30
I use bitcoind 0.16 rc1 without wallet support. I have 2 channels open at the moment, so the overall process should work.

It's connected over zmq to lnd. Blocks and TX propagation is working.

I've done some shit in the past with this wallet, so maybe some coins are locked in a weird manner and I have only clean access to 2/3 of my coins. That does not bother me right now. That will get interesting not till I have to get the coins to layer 1.

I think, it should close and remove the pending channel and unlock the funds immediately and not after a restart, if it fails to open a channel. (Which in my case, does not really unlock the funds, but that should not be the topic of this issue. Thats maybe another issue and first needs more observation)

**Comment by Roasbeef** [comment] 2018-01-31 20:37
It will unlock the funds immediately, but atm it won't yet remove the pending channel from the database.

**Comment by Roasbeef** [comment] 2018-01-31 22:04
See #711 for a fix for the: "if they disconnect mid msg send we won't cancel the reservation" issue.

**Comment by Roasbeef** [comment] 2018-03-20 21:17
We've also implemented logic to ensure that the funding transaction is rebroadcast on start up if it hasn't yet confirmed: https://github.com/lightningnetwork/lnd/pull/814

We'll also now properly prune out our UTXO's in response to attempted transaction broadcasts that fail.

**Closed by Roasbeef** 2018-03-20 21:17 UTC
Labels: channel closing, funding, recovery
