### ISSUE TITLE
Pending channel with status and balance issues

### ISSUE THREAD

**Issue by robclark56** [lightningnetwork/lnd#3450] opened 2019-09-03 07:58 UTC
### Background
Noticed my node has a channel that:

1. Has been pendingfor months
2. Has a both local and remote balance zero, yet channel capacity is not zero

(see below for pendingchannels report)

### Your environment
* version of `lnd` 
Today =  v0.7.1-beta
When the channel was closed (July-2019) = ?? Possibly v0.7.0-beta

* which operating system: Linux RaspiBolt 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.17.1

* any other relevant environment details
No

### Steps to reproduce
No idea how it happened or how to reproduce. Other channel closings before and after have been fine.

### Expected behaviour
1. When closing TX is confirmed (it is) then the channel should disappear from the pendingchannels report
2. Not possible to have a channel with non-zero capacity but zero Local & Remote balances

### Actual behaviour
```
admin ~  ฿  lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [],
    "pending_closing_channels": [],
    "pending_force_closing_channels": [],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7",
                "channel_point": "e4e8fa952c78bd592a41581fe133b2db9d00b2175003ccd8b5b6719222c96b34:0",
                "capacity": "848047",       <---------------   
                "local_balance": "0",       <---------------  
                "remote_balance": "0",      <---------------  
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0"
            },
            "limbo_balance": "0"
        }
    ]
}
```

And here is the closing TX
https://www.blockchain.com/btc/tx/e4e8fa952c78bd592a41581fe133b2db9d00b2175003ccd8b5b6719222c96b34

**Comment by robclark56** [comment] 2019-09-03 08:11
And ... 1ml.com shows the channel as follows as I write this:
```
Active Channel
Capacity 0.00848047 BTC 848,047 sat (0.001005%) $88.04 
Last Update 3 days ago 
First Seen Saturday, July 13, 2019 
Age a month
```
https://1ml.com/channel/643396821318172672

**Comment by lobsterpub** [comment] 2019-09-03 10:07
So, I'm gonna ask the obvious questions: Have you tried restarting LND?

**Comment by robclark56** [comment] 2019-09-03 11:15
Thanks for asking .

Yes

**Comment by wpaulino** [comment] 2019-09-03 21:29
Looks like the fields were just not being set, which should be fixed with https://github.com/lightningnetwork/lnd/pull/3456. What are the logs for the channel? If it's in waiting close, then you prompted the close.

**Comment by robclark56** [comment] 2019-09-04 03:37
Sorry - My log files do not go back to July.

**Comment by molxyz** [comment] 2019-09-04 12:19
> And here is the closing TX
> https://www.blockchain.com/btc/tx/e4e8fa952c78bd592a41581fe133b2db9d00b2175003ccd8b5b6719222c96b34

That's not the closing TXID. That's the `channel_point` which is the funding TXID. From your post:
```
"channel_point": "e4e8fa952c78bd592a41581fe133b2db9d00b2175003ccd8b5b6719222c96b34:0",
```

@wpaulino  In this case can he just try to close it again and it should be closed?

**Comment by wpaulino** [comment] 2019-09-04 19:21
It's already been closed according to their database state, the closing transaction just hasn't confirmed yet. There's not much we can do without logs.

**Comment by robclark56** [comment] 2019-09-04 23:01
@molxyz: My apologies ... you are 100% correct. I cited the opening transaction.

So that means - I may indeed have the logs for the closing. Will look deeper.

**Comment by robclark56** [comment] 2019-09-05 02:46
grep'ing the log files for the remote_node_pub (03a...7d7) has zillions of hits.

As I don't know the approx timestamp for the close event, hard to pin down.

Here is a small example of the errors I see with the remote node in the log files.

```
2019-08-19 07:44:50.696 [INF] SRVR: Finalizing connection to 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7@118.163
.74.161:43826, inbound=true
2019-08-19 07:44:51.113 [INF] PEER: NodeKey(03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7) loading ChannelPoint(e4
e8fa952c78bd592a41581fe133b2db9d00b2175003ccd8b5b6719222c96b34:0)
2019-08-19 07:44:51.207 [INF] SRVR: Negotiated chan series queries with 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d16367910
7d7
2019-08-19 07:44:51.208 [INF] DISC: Creating new GossipSyncer for peer=03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107
d7
2019-08-19 07:44:51.705 [INF] DISC: GossipSyncer(03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7): applying new upda
te horizon: start=2019-08-19 07:44:50 +0800 AWST, end=2155-09-25 14:13:05 +0800 AWST, backlog_size=0
2019-08-19 07:45:59.013 [INF] PEER: unable to read message from 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7@118.
163.74.161:43826: EOF
2019-08-19 07:45:59.013 [INF] PEER: Disconnecting 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7@118.163.74.161:438
26, reason: read handler closed
2019-08-19 07:45:59.214 [INF] DISC: Removing GossipSyncer for peer=03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7

```

Any suggestions on what I should be grep'ing for?

Or should I just upload the log files here?

**Comment by wpaulino** [comment] 2019-09-05 21:14
Make sure to also check the gzipped log files. If the channel was force closed, you should see something like `Attempting to force close ChannelPoint(txid)`. If it was closed cooperatively, you should see `Ideal fee for closure of ChannelPoint(txid)`.

**Comment by robclark56** [comment] 2019-09-05 23:32
I have gunzip'ed my three *,gz files
```
root@RaspiBolt:/home/bitcoin/.lnd/logs/bitcoin/mainnet# ls -l
total 31852
-rw-r--r-- 1 bitcoin bitcoin  1878917 Sep  6 07:25 lnd.log
-rw-r--r-- 1 bitcoin bitcoin 10240082 Aug 27 10:32 lnd.log.3345
-rw-r--r-- 1 bitcoin bitcoin 10240139 Aug 31 00:19 lnd.log.3346
-rw-r--r-- 1 bitcoin bitcoin 10240164 Sep  4 21:31 lnd.log.3347
```
greping all 4 files for 'force close' & 'closure of Channel' show no hits for the channel I am looking for.

Maybe the log files do not go back far enough?

**Comment by wpaulino** [comment] 2019-09-06 19:30
> Maybe the log files do not go back far enough?

That's likely the case.

It looks like the balance isn't on your side of the channel anyway, so no need to worry about having funds locked.

**Comment by Roasbeef** [comment] 2019-09-06 20:09
Closing at it appears you have no funds in the channel, and the closing transaction was never actually broadcast (for some reason).

**Closed by Roasbeef** 2019-09-06 20:09 UTC
