### ISSUE TITLE
Tor general error when connecting clearnet hosts in hybrid mode

### ISSUE THREAD

**Issue by akovalenko** [lightningnetwork/lnd#6378] opened 2022-03-29 15:09 UTC
### Your environment

* version of `lnd`:6e2214fd0fc04adff705141b17482550bee58cde + tor workaround
* `Linux murphy 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`
* bitcoind 22.0

### Steps to reproduce

lncli connect ...@1.2.3.4:9735

### Expected behaviour

connecting to node

### Actual behaviour

Tor general error

**Comment by akovalenko** [comment] 2022-03-29 15:12
I can be the one to blame here:
I modify lncfg/address.go to make it possible to start LND with my config.
Lnd is instructed to connect via clearnet to clearnet targets (that's why tor general error very much surprise me here).

```diff
diff --git a/lncfg/address.go b/lncfg/address.go
index afb4188dd..b9c52b4bc 100644
--- a/lncfg/address.go
+++ b/lncfg/address.go
@@ -232,7 +232,7 @@ func ParseAddressString(strAddress string, defaultPort string,
 		// Otherwise, we'll attempt the resolve the host. The Tor
 		// resolver is unable to resolve local or IPv6 addresses, so
 		// we'll use the system resolver instead.
-		if rawHost == "" || IsLoopback(rawHost) ||
+		if rawHost == "" || IsLoopback(rawHost) || true ||
 			isIPv6Host(rawHost) {
 
 			return net.ResolveTCPAddr("tcp", addrWithPort)
-- 
```

**Comment by akovalenko** [comment] 2022-03-29 16:18
Even if the issue is due to my nasty workaround, I'd appreciate an advice for an alternative. Maybe downgrading lnd or rolling back something will fix either "tor general error" or config validation issues? (Preferably both)

**Comment by Roasbeef** [comment] 2022-03-29 16:22
If you don't already know: that patch you applied will end up leaking all your DNS queries over clearnet. If you've upgraded to master (not considered to be stable, not a tagged release) then you'll be unable to downgrade. 

I recommend reviewing your `lnd.conf` and also ensuring that your tor daemon is reachable over the specified control port.

**Comment by akovalenko** [comment] 2022-03-29 17:05
I don't really care for dns leaks.

The problem is, I have no idea how to satisfy lncfg in my config file with current tip of the master branch. That is, I can review but the only way to fix it for me will be trial and error. I don't grok the nature of the problem.

Sorry for bothering y'all, but I'm running lnurl-pay.me on master branch (sometimes patched), and I assume there aren't too many people as reckless as me, and my battle-testing is beneficial for lnd. So we both lose if I'm unable to run the master's tip, and I want to continue to do that.

**Comment by Roasbeef** [comment] 2022-03-29 18:41
I think you might be affected by an issue which is fixed in this PR: https://github.com/lightningnetwork/lnd/pull/6376. Are you able to give it a spin to confirm the fix?

**Comment by guggero** [comment] 2022-03-29 20:10
Or can you at least post your config so we can take a look to spot potential problems?

**Comment by akovalenko** [comment] 2022-03-30 04:57
externalip=185.29.8.198 triggers "tor general error" on config validation (with bare master, also with PR #6376, but not with my workaround).
I SUSPECT that tor general error on connect'ing a clearnet target while in skip-proxy-for-clearnet mode is of the same nature, but triggered in some other code. I haven't tested it yet, though.

**Comment by akovalenko** [comment] 2022-03-30 04:59
```
tlsextradomain=vds.sw4me.com
enable-upfront-shutdown=1
tor.v3=1
tor.privatekeypath=<redacted>
tor.active=1
tor.skip-proxy-for-clearnet-targets=1

bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

autopilot.active=0

nat=false
rpclisten=localhost:10009

alias=lnurl-pay.me
color=#0020FF

externalip=185.29.8.198
externalip=104.244.76.120
bitcoin.minhtlc=1000
bitcoin.basefee=0
bitcoin.feerate=25

protocol.wumbo-channels=1
db.bolt.auto-compact=true
db.bolt.auto-compact-min-age=480h
db.batch-commit-interval=1s
caches.reject-cache-size=200000
caches.channel-cache-size=80000
blockcachesize=83886080


gc-canceled-invoices-on-startup=1
wallet-unlock-password-file=/srv/lnd/data/.lnd/pw

max-cltv-expiry=8064
accept-keysend=true
accept-amp=true
bitcoind.estimatemode=ECONOMICAL

workers.read=200
caches.reject-cache-size=200000
caches.channel-cache-size=80000
healthcheck.chainbackend.interval=10m
ignore-historical-gossip-filters=0


healthcheck.chainbackend.attempts=20
; The number of times we should attempt to check our tor connection before
; gracefully shutting down. Set this value to 0 to disable this health check.
healthcheck.torconnection.attempts=3

; The amount of time we allow a call to our tor connection to take before we 
; fail the attempt. This value must be >= 1s.
healthcheck.torconnection.timeout=10s

; The amount of time we should backoff between failed attempts to check tor 
; connection. This value must be >= 1s.
healthcheck.torconnection.backoff=30s

; The amount of time we should wait between tor connection health checks. This
; value must be >= 1m.
healthcheck.torconnection.interval=1m
```

**Comment by guggero** [comment] 2022-03-30 12:50
Okay, I think for some reason the IP address 185.29.8.198 cannot be resolved properly by Tor.
But since you're using the `tor.skip-proxy-for-clearnet-targets=1` config, it shouldn't be.

Can you try if this patch fixes things for you?
[tor.diff.txt](https://github.com/lightningnetwork/lnd/files/8380567/tor.diff.txt)

**Comment by akovalenko** [comment] 2022-03-30 16:55
@guggero it fixes config validation, but the issue with connecting to clearnet manually remains:

```
lnd@murphy:~$ lncli connect 03ee58475055820fbfa52e356a8920f62f8316129c39369dbdde3e5d0198a9e315@107.189.30.195:9734
[lncli] rpc error: code = Unknown desc = tor general error
```

**Comment by Roasbeef** [comment] 2022-03-30 20:34
Ok, we tracked down the issue. There was a regression merged into the `master` branch of `btcd` which has been resolved.  Once #6376 is updated, this issue should be resolved. 

Alternatively, if you want to try out the fix sooner, then you can run this command: 
```
go get -v github.com/btcsuite/btcd@074266215c26f8c4731330abb515f92b905f8dfa
go mod tidy 
```

Then build as normal, and things _should_ be resolved.

**Comment by akovalenko** [comment] 2022-03-31 04:26
@Roasbeef thanks, it helped (I haven't really checked whether it skips tor for clearnet targets, though)

**Closed** 2022-03-31 12:46 UTC

**Comment by chill117** [comment] 2022-08-30 13:18
I encountered the same error in this issue: "tor general error". But not with the the `lncli openchannel` command using the `--connect` argument. I was able to work-around the error by using the `lncli connect` command first then using the openchannel command again but without the `--connect` flag.
