### ISSUE TITLE
[bug]: listunspent shows old and confirmed TX

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7063] opened 2022-10-20 06:38 UTC
### Background

`lncli listunspent` shows the expected data, but also one outpoint that has been spent 11 months ago:

```
{
    "address_type": 0,
    "address": "bc1q552qpdmmq7z7422yztshh3mud6757vypnv5q9t",
    "amount_sat": 4000095,
    "pk_script": "0014a51400b77b0785eaa94412e17bc77c6ebd4f3081",
    "outpoint": "5dd0694e2d8a6c70196918bb2695c1d59618ad1540abb2ad5951670d0ba076a4:1",
    "confirmations": 50309
}
```

The logs show:
```
2021-11-10 17:20:05.980 [INF] LNWL: Inserting unconfirmed transaction 5dd0694e2d8a6c70196918bb2695c1d59618ad1540abb2ad5951670d0ba076a4
2021-11-11 05:59:57.875 [INF] LNWL: Marking unconfirmed transaction 5dd0694e2d8a6c70196918bb2695c1d59618ad1540abb2ad5951670d0ba076a4 mined in block 709170
```

According to my notes this was a preparation for a dual-funded channel using `bos`. `7424524d3aa55302d7abea10db9dc18fedd702429bdaf62c195701167d42f890` was the actual open transaction, where my node provided half of the inputs.

### Your environment

* lnd v0.15.3-beta
* Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* bitcoind v23

**Comment by guggero** [comment] 2022-10-20 07:31
I think this is a duplicate of https://github.com/lightningnetwork/lnd/issues/6434. Inputs that are used up fully with a single channel funding output aren't recognized properly by the wallet as belonging to it and aren't tracked for spentness.

**Comment by positiveblue** [comment] 2022-10-25 11:20
Duplicated, discussion will follow up in #6434

**Closed by positiveblue** 2022-10-25 11:20 UTC
Labels: bug, needs triage
