### ISSUE TITLE
UTXO Transaction not found

### ISSUE THREAD

**Issue by raymondclowe** [lightningnetwork/lnd#6367] opened 2022-03-25 02:16 UTC
### Background

After the Telegram lightning watch bot went down a few days ago the channel to it was force closed but the funds in the channel have not reappeared for me.  There is a transaction listed but it is not found in mempool.space.  There is another transaction with approx the right amount, but the money isn't found anywhere, it has gone to another address I can't see I think; not very clear on this last point.

This node hasn't been touched in several months, apart from upgrading lnd and restarting, as it is my test setup for "I'll get around to learning more about this when I have time" which of course never happens.

When I first started to troubleshoot this there were 3 utxos in this strange 0-confirmations state so I took the advice to use `--reset-wallet-transactions` and after an hour the situation improved and now has only one like this.  I ran it again to see if it would clear up any more but has not changed again.

### Your environment

* lnd version 0.14.2-beta commit=v0.14.2-beta
* Windows 10
* Neutrino
* tor and a dynamic ip that is also advertised

### The problem

Two-fold issue from my perspective

* A) have sats marked as "unconfirmed" which will presumably never get confirmed as the transaction is not in the pool
* B) I don't appear to have got the sats back from the force closed channel, unless they are the ones in A) which is roughly the right amount

#### Transaction with no confirmations
Is this normal?  lnd can see this utxo but the transaction doesn't exist and hence no balance in the address.
```
{
        "utxos": [
                {
                        "address_type": 0,
                        "address": "bc1qv6wy20d7ceh4c4yus5hsmz0zjj5kld8sry03wp",
                        "amount_sat": 15455,
                        "pk_script": "0014669c453dbec66f5c549c852f0d89e294a96fb4f0",
                        "outpoint": "2dc37123f8c662d3e36754915d0ad430b6f75b288271112b104f0eee9164356b:0",
                        "confirmations": 0
                },
```

#### Transaction with funds gone somewhere I can't see

Separately, in RTL there is a listing for the force closed transaction.  I don't know how to see this via the lncli.  

In that listing it shows the closing transaction as being `10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409` 

It shows the sats moving to an address, and then some time later moving to another one.  I can't see this as an available balance unless it is the unconfirmed amount described above, though the amount doesn't quite match.

### Expected behaviour

I would expect the funds from the force closed to become available to me.

### Actual behaviour

It didn't

### Log grep for the transaction id s

```
2022-03-22 09:14:52.975 [INF] SWPR: Creating sweep transaction 2dc37123f8c662d3e36754915d0ad430b6f75b288271112b104f0eee9164356b for 2 inputs (10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0 (CommitmentAnchor), 4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f:0 (WitnessKeyHash)) using 253 sat/kw, tx_weight=719, tx_fee=0.00000181 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2022-03-22 09:14:52.977 [INF] LNWL: Inserting unconfirmed transaction 2dc37123f8c662d3e36754915d0ad430b6f75b288271112b104f0eee9164356b
2022-03-24 17:06:03.465 [INF] LNWL: Inserting unconfirmed transaction 2dc37123f8c662d3e36754915d0ad430b6f75b288271112b104f0eee9164356b
2022-03-25 09:22:44.142 [INF] LNWL: Inserting unconfirmed transaction 2dc37123f8c662d3e36754915d0ad430b6f75b288271112b104f0eee9164356b
```

```
2022-03-20 23:27:44.217 [INF] CNCT: Broadcasting force close transaction 10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409, ChannelPoint(d372ac0e2dedeaba29eaf98e5c85070b1d91c7dda8cbc6a8afe31c41d941b8e4:0): (*wire.MsgTx)(0xc003066f80)({
2022-03-20 23:27:44.246 [INF] LNWL: Inserting unconfirmed transaction 10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409
2022-03-20 23:27:49.288 [INF] SWPR: Sweep request received: out_point=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0xc0095bb2d8)
2022-03-20 23:27:49.297 [INF] NTFN: New spend subscription: spend_id=4, outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, height_hint=728217
2022-03-20 23:27:49.298 [INF] NTFN: Dispatching historical spend rescan for outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, start=728217, end=728217
2022-03-20 23:27:49.301 [INF] PEER: channel(695837:1425:0) force closed with txid 10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409
2022-03-21 09:08:13.153 [INF] CNCT: Re-publishing force close tx(10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409) for channel d372ac0e2dedeaba29eaf98e5c85070b1d91c7dda8cbc6a8afe31c41d941b8e4:0
2022-03-21 09:08:22.786 [INF] SWPR: Sweep request received: out_point=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0xc005e04a28)
2022-03-21 09:08:22.787 [INF] NTFN: New spend subscription: spend_id=4, outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, height_hint=728287
2022-03-21 09:08:22.787 [INF] NTFN: Dispatching historical spend rescan for outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, start=728287, end=728287
2022-03-21 09:08:42.793 [INF] NTFN: Dispatching confirmed spend notification for outpoint=d372ac0e2dedeaba29eaf98e5c85070b1d91c7dda8cbc6a8afe31c41d941b8e4:0, script=0 06eaa3013d18c073be0b757601e3ef5fe76ac96eecb3115406898e81c58c9133 at current height=728287: 10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409[0] spending d372ac0e2dedeaba29eaf98e5c85070b1d91c7dda8cbc6a8afe31c41d941b8e4:0 at height=728218
2022-03-21 09:08:42.865 [INF] SWPR: Sweep request received: out_point=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=253 sat/kw, force=false, exclusive_group=<nil>)
2022-03-21 09:08:42.865 [INF] NTFN: New confirmation subscription: conf_id=1, txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409, num_confs=1 height_hint=728218
2022-03-21 09:08:42.925 [INF] NTFN: Dispatching 1 confirmation notification for txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409
2022-03-21 09:08:42.925 [INF] NTFN: Canceling confirmation notification: conf_id=1, txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409
2022-03-21 09:25:00.947 [INF] SWPR: Creating sweep transaction 67e54fa4edb155a8bf6ff2466d269b4cac774b1ebcd4151e44d03b1a1a8c96ef for 2 inputs (10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0 (CommitmentAnchor), 9a9c84d17a76d3384986305b1398c9576aef79649f4440456d60b3cd9700487b:0 (WitnessKeyHash)) using 253 sat/kw, tx_weight=719, tx_fee=0.00000181 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2022-03-21 09:54:57.143 [INF] SWPR: Creating sweep transaction c3f8f5d20025be7d821b0411344de818c9ace57d45953c8979bcc183bc73afbb for 2 inputs (10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0 (CommitmentAnchor), 0d30b482795bbe5d249c3b6517f1f8ccdbd604ebcff176aae5f4353bafed6f01:0 (WitnessKeyHash)) using 253 sat/kw, tx_weight=719, tx_fee=0.00000181 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2022-03-21 17:44:46.441 [INF] SWPR: Sweep request received: out_point=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=253 sat/kw, force=false, exclusive_group=<nil>)
2022-03-21 17:44:46.441 [INF] NTFN: New confirmation subscription: conf_id=1, txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409, num_confs=1 height_hint=728218
2022-03-21 17:44:46.441 [INF] NTFN: New spend subscription: spend_id=3, outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, height_hint=728336
2022-03-21 17:44:46.442 [INF] NTFN: Dispatching historical spend rescan for outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, start=728336, end=728336
2022-03-22 07:28:37.967 [WRN] BTCN: All peers rejected transaction 10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409 checking errors
2022-03-22 09:08:30.595 [INF] SWPR: Sweep request received: out_point=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=253 sat/kw, force=false, exclusive_group=<nil>)
2022-03-22 09:08:30.594 [INF] NTFN: New confirmation subscription: conf_id=1, txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409, num_confs=1 height_hint=728218
2022-03-22 09:08:30.595 [INF] NTFN: New spend subscription: spend_id=3, outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, height_hint=728433
2022-03-22 09:08:30.596 [INF] NTFN: Dispatching historical spend rescan for outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0, script=0 9bb1f7dc80edd81e1c3163f35e03366829d18e4dcc2ad5398006209bc5739bbb, start=728433, end=728436
2022-03-22 09:08:49.819 [INF] NTFN: Dispatching 1 confirmation notification for txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409
2022-03-22 09:08:49.819 [INF] NTFN: Canceling confirmation notification: conf_id=1, txid=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409
2022-03-22 09:08:49.821 [INF] SWPR: Sweep request received: out_point=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3, witness_type=CommitmentTimeLock, relative_time_lock=144, absolute_time_lock=0, amount=0.00015792 BTC, params=(fee=6 blocks, force=false, exclusive_group=<nil>)
2022-03-22 09:08:49.821 [INF] NTFN: New spend subscription: spend_id=4, outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3, script=0 670589f9338a09fe0a0d560e97bce5aeb9b174a326a517a2f54211e27a95d20b, height_hint=728218
2022-03-22 09:08:49.821 [INF] NTFN: Dispatching historical spend rescan for outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3, script=0 670589f9338a09fe0a0d560e97bce5aeb9b174a326a517a2f54211e27a95d20b, start=728218, end=728436
2022-03-22 09:09:19.844 [INF] SWPR: Creating sweep transaction 4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f for 1 inputs (10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3 (CommitmentTimeLock)) using 1002 sat/kw, tx_weight=486, tx_fee=0.00000486 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2022-03-22 09:14:22.966 [INF] NTFN: Dispatching confirmed spend notification for outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3, script=0 670589f9338a09fe0a0d560e97bce5aeb9b174a326a517a2f54211e27a95d20b at current height=728437: 4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f[0] spending 10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3 at height=728437
2022-03-22 09:14:22.967 [INF] NTFN: Canceling spend notification: spend_id=4, outpoint=10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:3, script=0 670589f9338a09fe0a0d560e97bce5aeb9b174a326a517a2f54211e27a95d20b
2022-03-22 09:14:52.975 [INF] SWPR: Creating sweep transaction 2dc37123f8c662d3e36754915d0ad430b6f75b288271112b104f0eee9164356b for 2 inputs (10034c258395cb0211ec0edd066d11cb1b5a0cec0aaa0890f947959b88f0b409:0 (CommitmentAnchor), 4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f:0 (WitnessKeyHash)) using 253 sat/kw, tx_weight=719, tx_fee=0.00000181 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0

```

**Comment by guggero** [comment] 2022-03-25 09:38
I think this is a duplicate of https://github.com/lightningnetwork/lnd/issues/6241, which should be fixed in the upcoming `v0.14.3-beta` (for which the RC is being prepared here https://github.com/lightningnetwork/lnd/pull/6366).

**Comment by raymondclowe** [comment] 2022-03-25 09:49
> I think this is a duplicate of #6241, which should be fixed in the upcoming `v0.14.3-beta` (for which the RC is being prepared here #6366).

Thanks, certainly sounds similar.  

Two points: 

1. In that issue it is suggested that reset-wallet-transactions is the right thing to do, but it didn't fix it for me.
2. Seems to say that someone else can/has sweep the funds. Does that mean the SATs are "stolen"/ unrecoverable by me ?

**Comment by guggero** [comment] 2022-03-25 09:56
No, `--reset-wallet-transactions` can't fix this, only the mentioned version can.

The 15455 sats of your channel aren't lost. You just can't currently sweep them because of the bug. You should be able to with `v0.14.3-beta`.
Someone else collected the 330 sats that were used as the anchor output. See https://bitcoinops.org/en/topics/anchor-outputs/ for more explanation and why that's "by design" that someone else can sweep them.

**Comment by guggero** [comment] 2022-03-25 09:58
Ah, I just looked at the outputs again, and I was wrong. The 15792 sats were already swept to your wallet (`4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f`). So the only thing that will change with `v0.14.3-beta` is that the "ghost UTXO" will likely disappear.

**Comment by raymondclowe** [comment] 2022-03-25 10:14
So transaction `4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f` sent it to address `bc1qupvlpas722umft6rr8zn3a20tm68nwe43xrxqx`, but how is that mine?  I don't see it when I do `lncli listunspent`.

**Comment by guggero** [comment] 2022-03-25 10:19
It was just a guess, since I don't know what your balance of the channel was. Do you see `ab20d89bde30580d5faf21de3f2012ef3732525cbf86ac2821dbac398d520406` in your list of unspent?

**Comment by guggero** [comment] 2022-03-25 10:23
No, scratch that. I see from your log that your sweeper tries to sweep `4641f2a7a9d18af733f58ce3ffa0f65dc5f5f91510fc27fe4c4468083aca1a1f:0` into the wallet but fails because of the already swept anchor. Not sure why that extra transaction is necessary. So you do need to wait for `lnd v0.14.3-beta` it seems.

**Comment by raymondclowe** [comment] 2022-03-25 10:31
Ok thanks, I'll wait.

Appreciate you taking the time to check it out.  :-)

**Comment by guggero** [comment] 2022-03-28 11:35
Closing as this has been addressed by https://github.com/lightningnetwork/lnd/pull/6274. Feel free to re-open if `lnd v0.14.3-beta` doesn't fix this.

**Closed by guggero** 2022-03-28 11:35 UTC

**Comment by guggero** [comment] 2022-07-22 13:49
Hmm, this seems to be happening to [other users as well](https://github.com/lightningnetwork/lnd/issues/6434).

Since you upgraded to 0.15 already and that didn't fix it, we need more information to dig deeper.
Could you please set `--debuglevel=debug` and `--reset-wallet-transactions` on your node (again) and send us the full log since that restart? You can DM me the logs on [Slack](https://lightning.engineering/slack.html) or send me an email (in my profile).
Also the full output of `lncli listunspent` and `lncli listchaintxns` would be very useful. Thanks!

**Comment by raymondclowe** [comment] 2022-07-25 07:27
Ok I'm running --debuglevel=debug and --reset-wallet-transactions now.

How long do I run it before sending you the logs?

**Comment by guggero** [comment] 2022-07-25 15:55
I'd say until the wallet is fully synced (watch the log for progress) and then maybe two hours more to make sure any rescans finish as well?

**Comment by raymondclowe** [comment] 2022-07-26 01:45
What do I look for in the log to tell the wallet is fully synced?

I grepped for "wallet" and got:


```
2022-07-25 15:11:19.410 [DBG] WLKT: WalletKit RPC server successfully registered with root gRPC server
2022-07-25 15:11:19.413 [DBG] WLKT: WalletKit REST server successfully registered with root REST server
2022-07-25 15:11:43.110 [INF] LTND: Attempting automatic wallet unlock with password provided in file
2022-07-25 15:11:44.955 [INF] LNWL: Opened wallet
2022-07-25 15:11:44.955 [INF] LNWL: Dropping btcwallet transaction history
2022-07-25 15:11:46.745 [INF] LNWL: Opened wallet
2022-07-25 15:11:48.791 [INF] LNWL: The wallet has been unlocked without a time limit
2022-07-25 15:11:48.798 [INF] CHRE: LightningWallet opened
2022-07-25 15:11:49.003 [DBG] LTND: Populating dependencies for sub RPC server: WalletKitRPC
2022-07-25 15:11:49.014 [DBG] RPCS: Starting sub RPC server: WalletKitRPC
```


Grepped for sync and got:


```
2022-07-25 15:11:19.422 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
2022-07-25 15:11:44.187 [INF] BTCN: Waiting for more block headers, then will start cfheaders sync from height 746434...
2022-07-25 15:11:44.188 [INF] BTCN: Starting cfheaders sync from (block_height=746434, block_hash=00000000000000000006cfb7ec409bd6f810840da242253884b6f6612ba2a9e3) to (block_height=746434, block_hash=00000000000000000006cfb7ec409bd6f810840da242253884b6f6612ba2a9e3)
2022-07-25 15:11:44.188 [INF] BTCN: Starting cfheaders sync for filter_type=0
2022-07-25 15:11:48.799 [DBG] LNWL: Waiting for chain backend to sync to tip
2022-07-25 15:11:49.019 [INF] LTND: Waiting for chain backend to finish sync, start_height=746434
2022-07-25 15:11:49.815 [DBG] LNWL: Chain backend synced to tip!
2022-07-26 05:45:23.003 [WRN] BTCN: No sync peer candidates available
2022-07-26 05:48:28.345 [WRN] BTCN: No sync peer candidates available

```

I saw the "Starting rescan" so grepped for "rescan" and got:


```
2022-07-25 15:11:49.820 [DBG] BTCN: Starting rescan from known block 746434 (00000000000000000006cfb7ec409bd6f810840da242253884b6f6612ba2a9e3)
2022-07-25 15:11:49.870 [INF] LNWL: Started rescan from block 0000000000000000000066f2e0a0937b73c26a10d33fbf6d9d0811ebb4866dd9 (height 695311) for 30 addresses
2022-07-25 15:11:49.870 [DBG] BTCN: Starting rescan from known block 695311 (0000000000000000000066f2e0a0937b73c26a10d33fbf6d9d0811ebb4866dd9)


```

At the moment it is just doing ping and pong with an occasional addrv2.

**Comment by guggero** [comment] 2022-07-27 12:44
Can you check if `lncli getinfo` returns `synced_to_chain: true` and `lncli getrecoveryinfo` returns `recovery_finished: true`?
If both is the case, then you can send me the logs.

**Comment by raymondclowe** [comment] 2022-07-28 06:02
No, they both return false, synced_to_graph also false.  And both channels (I only had 2) are inactive.  Feel this isn't working so I'm restarting everything, cold boot.

Now that I know to look for "getrecoveryinfo" I'll try again and see if it turns true at some point.

**Comment by raymondclowe** [comment] 2022-07-28 06:20
One other point; this node is using Neutrino backend which I gather is unusual.  At the time I set it up I didn't have a working bitcoin node, but I do now.  I have on another machine on the LAN a bitcoind archival with txindex. If it would be helpful for troubleshooting I could try to switch the lnd backend to point to the bitcoind. In theory at least! :-)

**Comment by guggero** [comment] 2022-07-28 07:27
Switching from neutrino to bitcoind should work. But the other way won't be possible.

**Comment by raymondclowe** [comment] 2022-07-29 02:16
In that case I'll try that later and try  `--reset-wallet-transactions` again first.

Is `getrecoveryinfo `supposed to say something is in progress?

All I get is:

```
{
    "recovery_mode": false,
    "recovery_finished": false,
    "progress": 0
}
```

**Comment by guggero** [comment] 2022-07-29 09:27
Ah, I think I remembered incorrectly and recovery mode is only active when restoring from seed, sorry. I think all you have to go by is the log. This is how it looks on my dev machine for example:

```
2022-07-29 11:25:31.138 [INF] LTND: Waiting for chain backend to finish sync, start_height=4856
2022-07-29 11:25:31.146 [INF] LNWL: Started rescan from block 72791a8901191a2140743bac67091a8a9dfb90029ff6fdda4f1009e45240787e (height 319) for 1 address
2022-07-29 11:25:31.150 [INF] LNWL: Catching up block hashes to height 320, this might take a while
2022-07-29 11:25:31.151 [DBG] LNWL: Filtering block 320 (3fdb7f2aa72a5f87127be622530ee010511aed4933f45a9d5879f34ed77aebb4) with 1 transactions
2022-07-29 11:25:31.153 [DBG] LNWL: Filtering block 321 (350ef9fe548089b0a5dcbd8cb826884076642836169d7e1ae9b3680212009ade) with 1 transactions
2022-07-29 11:25:31.153 [INF] LNWL: Done catching up block hashes
2022-07-29 11:25:31.153 [INF] LNWL: Rescanned through block 72791a8901191a2140743bac67091a8a9dfb90029ff6fdda4f1009e45240787e (height 320)
2022-07-29 11:25:31.154 [DBG] LNWL: Filtering block 322 (35c5a731e3dbbb4e9cb915d26932127f58c3e74a7d37a619a973dd773c9d7165) with 1 transactions
2022-07-29 11:25:31.155 [DBG] LNWL: Filtering block 323 (1dd38ba9b3717e926132d89a026acaf50ed992f84020c9208151cd5c46baf358) with 1 transactions
2022-07-29 11:25:31.156 [DBG] LNWL: Filtering block 324 (24749a64c11262c61633df13ea159fe07f3ee8008c71736fed8a327334381d77) with 1 transactions
2022-07-29 11:25:31.157 [DBG] LNWL: Filtering block 325 (4e81e0ddd148e00680f9b9e963016a8e4597bf4a59b0a1c52de815be1e6f6ea9) with 1 transactions
...
2022-07-29 11:25:35.017 [DBG] LNWL: Filtering block 4856 (010398a6f381297c5d5a0b775c4b745ef184dea81e96f7a3dca4e04ea271ff2c) with 1 transactions
2022-07-29 11:25:35.018 [INF] LNWL: Catching up block hashes to height 4856, this might take a while
2022-07-29 11:25:35.019 [INF] LNWL: Done catching up block hashes
2022-07-29 11:25:35.019 [INF] LNWL: Finished rescan for 1 address (synced to block 010398a6f381297c5d5a0b775c4b745ef184dea81e96f7a3dca4e04ea271ff2c, height 4856)
2022-07-29 11:25:35.148 [INF] LTND: Chain backend is fully synced (end_height=4856)!
```
Once you see `Chain backend is fully synced` you're good to go.

**Comment by raymondclowe** [comment] 2022-08-01 00:32
It ran over the weekend with `--debuglevel=debug --reset-wallet-transactions` and it still isn't synced.
```

    "synced_to_chain": false,
    "synced_to_graph": false,

```
The only references to sync in the log are

```
2022-07-29 20:20:32.248 [WRN] BTCN: No sync peer candidates available
2022-07-30 03:06:53.785 [WRN] BTCN: No sync peer candidates available
2022-07-30 04:34:06.042 [WRN] BTCN: No sync peer candidates available
2022-07-30 05:45:26.235 [WRN] BTCN: No sync peer candidates available
2022-07-30 05:48:05.820 [WRN] BTCN: No sync peer candidates available
2022-07-31 05:45:29.722 [WRN] BTCN: No sync peer candidates available
2022-08-01 01:00:31.550 [WRN] BTCN: No sync peer candidates available
2022-08-01 05:45:23.544 [WRN] BTCN: No sync peer candidates available
```

I also saw

`2022-07-29 11:30:12.068 [ERR] LNWL: Neutrino rescan ended with error: couldn't retrieve block 0000000000000000000774078e38fb6978e113b68b97ba9bf80fa0f7bf95ae77 from network`

I guess I have to switch to the bitcoind backend, but I'm afraid I may not be able to make anything work again so I'll try to get what funds I have in it out first, which may be difficult so will have to wait.

I'll update when I've done that.

**Comment by guggero** [comment] 2022-08-02 08:08
It looks like the Neutrino peer you were using isn't reliably serving you blocks anymore. You can also try with another peer first.

**Comment by ZoharKol** [comment] 2023-05-26 12:51
@raymondclowe what about that update ?
I get the same "Neutrino rescan ended with error..." did switching to bitcoind backend helped?
