### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when new announcement broadcast happens

### ISSUE THREAD

**Issue by reynico** [lightningnetwork/lnd#3579] opened 2019-10-04 15:32 UTC
### Background
Upgraded LND from 0.7.0-beta to v0.8.0-beta-rc1 crashes when a new announcement broadcast occurs:

```
Oct 04 15:18:06 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:18:06.919 [INF] DISC: GossipSyncer(0270685ca81a8e4d4d01beec5781f4cc924684072ae52c507f8ebe9daf0caaab7b): applying gossipFilter(start=2019-10-04 15:18:06.919878074 +0000 UTC m=+11.083495482, end=2155-11-10 21:46:21.919878074 +0000 UTC m=+4294967306.083495482)
Oct 04 15:18:20 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:18:20.013 [ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: unable to find a path to destination
Oct 04 15:19:21 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:19:21.246 [ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: unable to find a path to destination
Oct 04 15:20:22 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:20:22.359 [ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: unable to find a path to destination
Oct 04 15:21:02 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:21:02.534 [INF] DISC: Broadcasting 1 new announcements in 1 sub batches
Oct 04 15:21:23 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:21:23.371 [ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: unable to find a path to destination
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: 2019-10-04 15:21:30.609 [INF] CRTR: Processed channels=0 updates=1 nodes=0 in last 2m28.007008676s
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x58d9fe]
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: goroutine 1030 [running]:
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: crypto/ecdsa.Verify(0xc002806260, 0xc0027c0c80, 0x20, 0x20, 0xc000cdb000, 0xc000cdb020, 0xc0021dc510)
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /usr/local/go/src/crypto/ecdsa/ecdsa.go:237 +0x4e
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: github.com/btcsuite/btcd/btcec.(*Signature).Verify(...)
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /home/ubuntu/go/pkg/mod/github.com/btcsuite/btcd@v0.0.0-20190824003749-130ea5bddde3/btcec/signature.go:77
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: github.com/lightningnetwork/lnd/routing.VerifyChannelUpdateSignature(0xc000012840, 0xc002806260, 0x0, 0x0)
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /home/ubuntu/lnd/routing/ann_validation.go:155 +0x1dd
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: github.com/lightningnetwork/lnd/routing.ValidateChannelUpdateAnn(0xc002806260, 0xe4e1c0, 0xc000012840, 0x0, 0xc00325aa20)
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /home/ubuntu/lnd/routing/ann_validation.go:136 +0x70
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc00042ed80, 0xc00100ab40, 0x0, 0x0, 0x0)
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /home/ubuntu/lnd/discovery/gossiper.go:1952 +0x11a4
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc00042ed80, 0xc0008d3950, 0xc00100ab40, 0x1, 0xc000735fc0)
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /home/ubuntu/lnd/discovery/gossiper.go:1004 +0x224
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]: created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler
Oct 04 15:21:30 ip-10-0-1-215 lnd[6927]:         /home/ubuntu/lnd/discovery/gossiper.go:979 +0x5bc
Oct 04 15:21:30 ip-10-0-1-215 systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
### Your environment

* version of `lnd`: `v0.8.0-beta-rc1`
* which operating system (`uname -a` on *Nix): `Linux ip-10-0-1-215 4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 18.04.3 LTS)
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core Daemon version v0.18.1`
* goversion: `go version go1.12.7 linux/amd64`

### Steps to reproduce

Upgraded from `v0.7.0-beta` using following tags: "signrpc walletrpc chainrpc invoicesrpc routerrpc monitoring"

**Comment by Roasbeef** [comment] 2019-10-04 22:08
If you update first to 0.7.1, then 0.8 does this issue persist? Does the issue occur on start up only, or once `lnd` has been running for a period of time?

**Comment by reynico** [comment] 2019-10-05 22:46
Seems like going on from 0.7.1 works as expected. I'll left it running for a while

issue happens only after a new announcement broadcast occurs, so LND starts, runs the migrations and then crashes after an announcement broadcast

**Comment by reynico** [comment] 2019-10-07 13:13
Upgrading from 0.7.1 -> 0.8 works ok, I got 600+ announcements over the weekend and the node didn't crashed.

**Comment by reynico** [comment] 2019-10-15 13:37
Just a heads up, the 0.7.1 -> 0.8.0 upgrade is still running. @Roasbeef could you please update the 0.7->0.8 upgrade doc?

**Comment by Roasbeef** [comment] 2019-10-16 09:59
@reynico which update doc? It seems the issue is no longer reproducible?

**Comment by Roasbeef** [comment] 2020-01-14 06:29
Closing as unable to reproduce.

**Closed by Roasbeef** 2020-01-14 06:29 UTC
Labels: P2, bug, crash, discovery, gossip
