### ISSUE TITLE
[feature]: Have Accepted Hodl Invoices appear in SubscrbeInvoices

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#7539] opened 2023-03-26 17:28 UTC
**Is your feature request related to a problem? Please describe.**

Building an application using hodl invoices is extremely tedious because you need to do a SubscribeSingleInvoice for every invoice you create. This overly complicates code and makes it harder for restarts. If my application restarts I now need to find every invoice I had created and resubscribe.

**Describe the solution you'd like**

If SubscrbeInvoices gave all events then this wouldn't be a problem. If this is a problem for people it could be put behind a flag so you have to opt into it.

**Describe alternatives you've considered**

I don't think there is another solution besides switching to CLN and writing a plugin.

**Additional context**

**Comment by alexbosworth** [comment] 2023-03-26 18:09
maybe related to https://github.com/lightningnetwork/lnd/issues/3120

**Comment by Roasbeef** [comment] 2023-05-31 04:10
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/3120

Once we finish the [invoice overhaul](#7354), we'll be able to support a richer set of notification events. Right now the structure on disk is too inflexible (the existing events are implemented with a custom counter index for the two supported even types: settle and add).

**Closed by Roasbeef** 2023-05-31 04:10 UTC
Labels: enhancement
