### ISSUE TITLE
Unable to close channels for days

### ISSUE THREAD

**Issue by emretezel** [lightningnetwork/lnd#5317] opened 2021-05-20 13:49 UTC
Hi Everyone,

I have executed 3 closechannel requests two days ago with --sat_per_byte=10, they are still pending, is this normal?
Anything I can do to speed up /force the process?

Best regards

**Comment by wpaulino** [comment] 2021-05-20 19:34
Fees have risen to 50+ sat/vbyte in the past few days so 10 sat/vbyte isn't enough. Were the channels closed cooperatively? If so, you can use the `lncli wallet bumpfee` command with the output (txid:index) that belongs to you in the closing transaction.

**Comment by emretezel** [comment] 2021-05-21 07:59
Thank you the close instruction was for cooperative close. What do I use as the outpoint parameter here?

```
lncli pendingchannels
{
    "total_limbo_balance": "10460606",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "022755c3ff4e5a1d71f573cda4b315887fc00a9e5c9ea9a847d939f3e517e69a70",
                "channel_point": "4d70e744927a53b688f965e31a948adeadd54299a611b730d19dfab6d202e8e9:1",
                "capacity": "2000000",
                "local_balance": "1987083",
                "remote_balance": "0",
                "local_chan_reserve_sat": "20000",
                "remote_chan_reserve_sat": "20000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "1987083",
            "commitments": {
                "local_txid": "9e6d12722aa33037698d18865307477e17c6e809c26711368a2d71fd224d2217",
                "remote_txid": "4e00edef7b63d5ef66e2783f1d0097cc91893280a5e9d082b95b6503385fa3a3",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "12917",
                "remote_commit_fee_sat": "12917",
                "remote_pending_commit_fee_sat": "0"
            }
        },
        {
            "channel": {
                "remote_node_pub": "02816caed43171d3c9854e3b0ab2cf0c42be086ff1bd4005acc2a5f7db70d83774",
                "channel_point": "7c95a7600880a736b9b745cc84b9be5c8704e5ed8cddf161f8a8a3f14b3eac4c:1",
                "capacity": "5000000",
                "local_balance": "4987087",
                "remote_balance": "0",
                "local_chan_reserve_sat": "50000",
                "remote_chan_reserve_sat": "50000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "4987087",
            "commitments": {
                "local_txid": "1ce7360897e331a8d5e0ed53076f62754feb05c61bbaf9e00fda508db1bb60ef",
                "remote_txid": "f32303993c2d6ec2469847010a3d04eb861b5b7d539f2acb2485ce8c7491ed8a",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "12913",
                "remote_commit_fee_sat": "12913",
                "remote_pending_commit_fee_sat": "0"
            }
        },
        {
            "channel": {
                "remote_node_pub": "030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f",
                "channel_point": "639a60c61309cd3864ec2fd165feffd9307ffbbf01b000f50a759117a67e6a51:1",
                "capacity": "3500000",
                "local_balance": "3486436",
                "remote_balance": "0",
                "local_chan_reserve_sat": "35000",
                "remote_chan_reserve_sat": "35000",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "3486436",
            "commitments": {
                "local_txid": "be81abad93986ff16a860609cacdbeb31a92bd59878e0b57d2ce61e546444ba8",
                "remote_txid": "433de9ea9b2b051c35e57da5d2f59cde6050f288d6fd11fc1529fc0b058c4222",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "13564",
                "remote_commit_fee_sat": "13564",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}
```

**Comment by emretezel** [comment] 2021-05-21 08:07
I am getting the following error if using the channel point

```
lncli wallet bumpfee --sat_per_byte=30 4d70e744927a53b688f965e31a948adeadd54299a611b730d19dfab6d202e8e9:1
[lncli] rpc error: code = Unknown desc = the passed output does not belong to the wallet
```

**Comment by guggero** [comment] 2021-05-21 08:10
You need to take the transaction ID from `channel_point` (e.g. `4d70e744927a53b688f965e31a948adeadd54299a611b730d19dfab6d202e8e9`, without the `:1`) and look it up on a block explorer. Then follow the channel transaction and you'll see that there's an unconfirmed TX `a183c861da452e81361c7b1c9ac164c967362ca8133b1d8732d24ea1621f5d79`.
You then use that in bumpfee, for example: `lncli wallet bumpfee --sat_per_byte=50 a183c861da452e81361c7b1c9ac164c967362ca8133b1d8732d24ea1621f5d79:0`.
The index should always be `0` as it's a single output.

You can't use the channel point directly because that's a 2-of-2 multisig and the wallet doesn't have what it needs to bump it, that's why you get that error.

**Comment by guggero** [comment] 2021-05-21 08:10
Closing the issue as everything looks like expected behavior.

**Closed by guggero** 2021-05-21 08:10 UTC

**Comment by emretezel** [comment] 2021-05-21 08:20
Where do you see the unconfirmed TX?

[https://www.blockchain.com/btc/tx/4d70e744927a53b688f965e31a948adeadd54299a611b730d19dfab6d202e8e9](url)

**Comment by guggero** [comment] 2021-05-21 08:27
When you click on the second address: https://www.blockchain.com/btc/address/bc1q4fyqm3xqdc3xjfadwsn7zmdhrydq050497d8tf8hum72h4dd74as06qplh

**Comment by emretezel** [comment] 2021-05-22 08:28
I have bumped the fee to 50 on unconfirmed transactions, after 24 hours channels still not closed, anything else I can do ?

**Comment by guggero** [comment] 2021-05-24 08:02
It's now closed: `a183c861da452e81361c7b1c9ac164c967362ca8133b1d8732d24ea1621f5d79`.
