### ISSUE TITLE
lnd filling /var/log/syslog and /var/log/daemon.log while already logging in lnd directory

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#5993] opened 2021-11-17 14:09 UTC
### Background

I mounter /var/log to tmpfs on my raspberry, and gave it a generous 200MB size.
I also enabled `debuglevel=CNCT=debug,CRTR=debug,HSWC=debug,NTFN=debug,RPCS=debug` in lnd.conf, since I have plenty of space on the ssd where lnd folder resides.
Every operation by other applications, for instance `apt`, that needs logging, will fail with an error as there is constantly no free space in /var/log to add anything, because syslog and daemon.log contain a replica of everything that is written also in `/home/bitcoin/.lnd/logs`, and this will not only fill the space in the log partition (in my case filling the ram as well), but also, albeit marginally, determine an increased resource hogging because there will be not just one, but three logging operations going on at the same time.
I can add a line in crontab to wipe logs periodically, but this would defeat completely the purpose of keeping logs altogether, as I would at least like to check them before I reboot the system, if I need to.

### Your environment

* version of `lnd` 0.14rc3
* which operating system (`uname -a` on *Nix) Linux **** 5.10.63-v8+ # 1459 SMP PREEMPT ************** aarch64 GNU/Linux
* version of `bitcoind`,
* any other relevant environment details: testing on plebnet playground signet network

### Steps to reproduce

Have lnd running.

### Expected behaviour

lnd will prevent logging to syslog and daemon.log since a log is already kept in lnd's own folder

### Actual behaviour

Three total copies of the same logs are created

**Comment by guggero** [comment] 2021-11-17 15:22
Not sure this is actually an issue with `lnd` itself, but rather the way you _start_ lnd. What kind of start script are you using? systemd or something custom?
It is true that `lnd` logs to `stdout` and its own log file by default. But where `stdout` ends up in is completely up to the script/mechanism that starts `lnd`. There is no automatic logging to `/var/log/syslog` or `/var/log/daemon.log` by `lnd` itself.

**Comment by asvdf** [comment] 2021-11-17 18:13
Thank you for the very fast reply.
I am following raspibolt guide to define a systemd service, the command launched by ExecStart is `/usr/local/bin/lnd`, maybe there are switches to start lnd in silent mode?
`lnd -h | grep stout` and `lnd -h | grep silent` return nothing

Nvm, found something here: https://stackoverflow.com/questions/30757602/processes-started-with-systemd-are-logging-to-var-log-syslog-and-var-log-daemo
Need to add  `StandardOutput=null` in service definition file right under the `ExecStart` line, and those logs won't be spammed anymore.
A minor inconvenience is that I cannot use `journalctl -f -u lnd` anymore, but I need to run `tail -f -/home/bitcoin/lnd/logs/blahblah`

**Comment by guggero** [comment] 2021-11-18 07:39
If you want to use `journalctl` then you could instead let `lnd` log to `stdout` and limit the number (and size) of its own log files to reduce the amount of duplicate logs:
```
# Only keep one rotated log file around, limit size to 1MB
maxlogfiles=1
maxlogfilesize=1
```

Closing as this is a configuration issue, not a bug in `lnd`.

**Closed by guggero** 2021-11-18 07:39 UTC
