### ISSUE TITLE
Feature Request - spend all remaining outputs when opening a channel

### ISSUE THREAD

**Issue by windsok** [lightningnetwork/lnd#1401] opened 2018-06-16 02:49 UTC
### Background

When opening a channel, sometimes the user will want to spend all of their on-chain wallet balance, to ensure that there are no dust UTXO's leftover that are uneconomical to spend.

Currently, a user can try to manually specify the number of satoshi's and hope that all the funds will be spent, but this is prone to user error (I managed to leave some dust UTXO's when trying to do this).

A suggested solution would be to allow the user to specify "all" funds when opening a channel. The cli command could look something like:

```
lncli openchannel --node_key 027c2986cd45217cd8c996555f4f0925fc01b3030cebfa6d59e90e230bb00b3a8b --local_amt all
```

c-lightning has a similar feature to specify "all" satoshis:
```
fundchannel
    Fund channel with {id} using {satoshi} (or 'all') satoshis
```

**Comment by Roasbeef** [comment] 2018-06-16 02:51
Duplicate of #619.

**Closed by Roasbeef** 2018-06-16 02:51 UTC
