### ISSUE TITLE
[bug]: listunspent shows old and confirmed TX

### ISSUE THREAD

**Issue by walmer-bolfet** [lightningnetwork/lnd#6434] opened 2022-04-20 13:22 UTC
I am running a raspiblitz version 1.7.2

lnd version:  0.14.2-beta commit=lightning-terminal-v0.6.3-alpha

I have a discrepancy in my wallet balance, which is x sats - to which I can reconcile and believe is correct,  and the sum of my listchaintxns and the sum of my listunspent (i.e., utxos), which are both x + y sats.  

I was told then there was one utxo that equaled y sats, this was a sort of ghost utxo which might be remedied with a rescan of lnd, but alas, the rescan has increased the discrepancy and there are now three apparent ghost utxos that now sum to the y sats that are missing from the chain transactions.  I looking for information on whether this is something to ignore or whether you have a fix to suggest.  Thank you.

**Comment by rbpaul** [comment] 2022-04-20 14:37
Upon further investigation, I see these three ‘ghost uxtos’ are associated with balanced channels I opened with bos, as are the missing chain transactions which remedied, would reconcile the sums of uxtos and the sum of chain transactions to the balance of my wallet.

**Comment by Roasbeef** [comment] 2022-04-20 18:23
So safe to close this issue?

**Comment by rbpaul** [comment] 2022-04-20 19:40
No,  the issue remains even though I have provided some additional information about it.

**Comment by ziggie1984** [comment] 2022-04-21 04:57
Could it be that those balanced channels never opened correctly. Bos open-balance works in a way that it first sends funds to another derivation path, which lnd does not take into account when showing wallet balance. Normally when you open the balanced channel you will see a refund transaction which you have to broadcast in case something goes wrong with the balanced channel opening. If you don't have it anymore, you can create a psbt which sends it back to your lnd default wallet account. Hit me up if you need help with it.

**Comment by rbpaul** [comment] 2022-04-21 11:34
All the channels have opened, and are routing and rebalancing as expected. Is there any other way to notice whether they opened incorrectly?  

My reported wallet balance is correct. It is the sum of my utxos and the sum of my wallet transactions that reveal the issue.

**Comment by guggero** [comment] 2022-04-21 11:41
Do you have any more information about those ghost UTXOs? Do the outpoints exist on chain (block explorer)? Do they exist in your `lncli listchaintxns` output? If they do, are they trying to sweep anchor outputs (small, 330 bytes outputs)? If yes, it might have been fixed by https://github.com/lightningnetwork/lnd/pull/6274 (which is in `lnd v0.14.3-beta` and will also be in the upcoming `litd v0.6.6-alpha` release).

**Comment by rbpaul** [comment] 2022-04-21 12:05
I have all the information about these uxtos that appears with the lncli listunspent command (i.e. address_type,	address, amount_sat, pk_script, outpoint, confirmations).  I don’t know how to use block explorer well enough to answer your question. 

The transactions that I would have expected to see on my lncli listchaintxns output for opening these channels are not there, hence the discrepancy between my wallet balance and the sum of the chain transactions. However, there was a small chain transaction that concurrently appeared with the opening of these balanced channels, which I understood as part of the process.   I don’t understand the meaning of ‘something is trying to sweep anchor outputs’.

**Comment by rbpaul** [comment] 2022-04-21 12:30
This is an example of what bos telegram reported with the channel opening:  (I don’t understand how much can be shared securely, so I removed some information.  The 141 sats fee paid does appear in my wallet transactions.  There was another expected transaction for 1,050,095 sats that never appeared in the wallet transactions, but does appear as a ‘ghost utxo’.  I believe I saw this transaction as pending for a short while while awaiting its confirmation.  
 This is similar to the other two balanced channel openings. 
—

⚖️ Received a 0.02100000 balanced channel open proposal from “New Channel”
<Public Key>
Proposed chain fee rate: 1/vbyte
----
⛓ (pending) Sent 0.00000141. Paid 0.00000141 fee. Sent to bc1qy63. . . . . , bc1q9ce. . . . .
----
⏳ Accepting new 0.02100000 channel from ’New Channel’ <Public Key> 
‘My Node’ <public key>

**Comment by ziggie1984** [comment] 2022-04-21 18:20
Just checked my balance of all three and they add up:

`lncli walletbalance | jq '.total_balance' = x`
` lncli listchaintxns | jq '(.transactions[].amount|tonumber)' | awk '{total += $1} END {print total}' = x`
`lncli listunspent | jq '.utxos[].amount_sat' | awk '{total += $1} END {print total}' = x`

And I also checked my transactions I did with the bos open-balanced channel and everything is fine. 
So seems to me some transaction are either never been confirmed but have been created by lnd and therefore reside in the listchantxns command (see the bug guggero posted), to check this, just paste the `tx_hash` in mempool.space and see whether it finds a transaction for those ghost transactions. If it finds something then one should investigate further, bc then it could be that lnds wallet does not scan all derivation paths related to the rootkey.

**Comment by rbpaul** [comment] 2022-04-21 20:32
For me,

lncli walletbalance | jq '.total_balance' = x
lncli listchaintxns | jq '(.transactions[].amount|tonumber)' | awk '{total += $1} END {print total}' = x + y
lncli listunspent | jq '.utxos[].amount_sat' | awk '{total += $1} END {print total}' = x + y

Three 'ghost utxos' sum to y
Three 'missing' wallet payment transaction sum to y

I have some information about the 'ghost utxos', as I said above.  I have no information about missing wallet transactions so cannot proceed with your suggestion.  

I cannot explain it,  I can only see it, and it concerns me.

**Comment by guggero** [comment] 2022-04-21 20:36
Can you send us some more information please? For example DM me on [our public Slack](https://lightning.engineering/slack.html), same username. It's really hard to say anything without any transaction IDs or on-chain information.

**Comment by rbpaul** [comment] 2022-04-21 22:55
Yes, guggero  You should have it on Slack

**Comment by alexbosworth** [comment] 2022-04-26 17:53
Did you try dropping utxos and then rescanning?

**Comment by rbpaul** [comment] 2022-04-26 19:01
I have not tried that.  Clearly there is more information about why one would think these ghost utxos might be remedied by the dropping utxos than I understand.  Insofar as I am able to add funds to my wallet and open new channels with my wallet without being effected by or effecting these utxos, I am awaiting better understanding before I try to fix something that appears to be working - but somehow displays this anomaly.  Nevertheless, I thought those with better understand of lnd than I have would like to be alerted of this anomaly.

**Comment by xjmzx** [comment] 2022-07-14 04:46
Seem to have a similar ghost, locked utxo, or wallet balance issue. 
The tx is confirmed (24000+ confs.) from a coop close 6 months ago. 
Shows up in listunspent and is visible in the mempool. 
Have tried two methods to create a transaction without success. 
Also walletbalance shows the discrepancy.
--------------------------------------------
lncli walletbalance | jq '.total_balance'   "(shows balance - the utxo)"
lncli listchaintxns | jq '(.transactions[].amount|tonumber)' | awk '{total += $1} END {print total}'  (shows balance including utxo)
lncli listunspent | jq '.utxos[].amount_sat' | awk '{total += $1} END {print total}'  (shows balance including utxo)

Seems similar, didn't want to duplicate. 
Any thoughts how to diagnose what is the utxo state / get balance back to normal?
lnd v0.15-beta

**Comment by guggero** [comment] 2022-07-14 07:48
@xjmzx Take a look at [`--reset-wallet-transactions`](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan).

Closing the issue as I believe the original problem was resolved. @rbpaul feel free to re-open if that isn't the case.

**Comment by rbpaul** [comment] 2022-07-14 11:17
I have no idea why you ‘believe’ this issue is resolved.

**Comment by xjmzx** [comment] 2022-07-21 07:22
@guggero thanks for the suggestion. 

Ran `--reset-wallet-transactions` which completed in a few hours. Oddly, it increased the number of utxos. All confirmed and spent in mempool. Otherwise, no issue. Just wanted to mention the result as I heard a few others mention the same issue.

**Comment by guggero** [comment] 2022-07-21 16:01
I think the wallet will issue rescans for each found transaction output to find out if it was spent (which AFAIK is a background task independent of the initial wallet scan itself). So it might just take a while for them to be detected as spent.
If they're still there in let's say a week, can you please open a new issue?

**Comment by rbpaul** [comment] 2022-07-21 18:07
Mine ‘ghost’ uxtos have remained since I opened the issue in April.

**Comment by xjmzx** [comment] 2022-07-29 11:48
@guggero my update on changes to balance / utxos.

The only change after a week or more is that another utxo was added in the list. 

Originally there was just one. 
Then after `reset-wallet-transactions` seven more were found. 
After the last week (and db compaction) went up to nine in total. 

So, just increasing number of utxo found as opposed to detecting any have been spent. They are all listed in mempool as spent. Presents no other problem. I'll keep an eye open and update in case any significant change.

**Comment by guggero** [comment] 2022-07-29 11:55
Okay, thanks for the update. We'll need to take a look at the full logs to dig deeper.

Could you please set `--debuglevel=debug` and `--reset-wallet-transactions` on your node (again) and send us the full log since that last restart? You can DM me the logs on [Slack](https://lightning.engineering/slack.html) or send me an email (in my profile).
Also the full output of `lncli listunspent` and `lncli listchaintxns` would be very useful. Thanks!

**Comment by guggero** [comment] 2022-08-09 14:50
Thank you very much @xjmzx for providing the full logs with the correct debuglevel.
I think I was able to figure out what's going on: If one or more UTXOs are used for a channel open and no change output is created, the on-chain `btcwallet` library doesn't recognize the spend for some reason, because it doesn't get a change output to track (and the channel output is only tracked by the higher level lightning wallet).

So this is obviously a bug in the wallet that needs to be fixed.

@rbpaul can you confirm that your "ghost" UTXOs are also from channel opens where there was no change output? I know you sent them to me on Slack, but unfortunately the chat history there isn't kept. Could you please send me the output of `lncli listunspent` again so I can confirm this hypothesis?

**Comment by rbpaul** [comment] 2022-08-09 17:35
Greetings,
The listupspent output of the 3 ghost utxos is below.  As I previously mentioned, each one of them is associated with a balanced channel I opened with bos.   Another point is none of the transactions show up when I look at my chain transactions, but my wallet balance show the correct amount.  I will provide information as I am able with my limited understanding of what you are asking for.  I don’t know how to determine whether ‘no change output’ was created.  I will look forward to seeing a remedy.

> 		{
			"address_type": 0,
			"address": "bc1q9ce0s09n560ckzhw0gdge9znm0aage3tthvcju",
			"amount_sat": 1050095,
			"pk_script": "00142e32f83cb3a69f8b0aee7a1a8c9453dbfbd4662b",
			"outpoint": "085b475d7b12a0bcc11fd3321343e8fa10ea94aee65b26859bf2a58f5b311ead:1",
			"confirmations": 19840
		},
		{
			"address_type": 0,
			"address": "bc1q6qee35sxr3ghm74pp2psulgz6nux48jxwyc0cn",
			"amount_sat": 1500190,
			"pk_script": "0014d03398d2061c517dfaa10a830e7d02d4f86a9e46",
			"outpoint": "0d908b7ffed4d314216ffa0aa4efd2c1c451866b146defae6c2d1d0684b14b0e:0",
			"confirmations": 25235
		},
		{
			"address_type": 0,
			"address": "bc1qcz5ajdcqxf6t8c23hs28lmjkq0ew34ks7mxx0l",
			"amount_sat": 1500095,
			"pk_script": "0014c0a9d937003274b3e151bc147fee5603f2e8d6d0",
			"outpoint": "98f229fcae34ac234eb1f378a74682eabcfba7964dda04f873b63effd6570419:0",
			"confirmations": 25573
		},

**Comment by guggero** [comment] 2022-08-09 17:45
Thanks for the info. I can confirm they look the same as those from @xjmzx (two inputs, fully spent into a channel output with no change output).
Now that we know what the actual problem is, we can start on a fix. So thanks again for the help in tracking this down.

**Comment by positiveblue** [comment] 2022-10-25 11:23
@walmer-bolfet I will rename the issue to `[bug]: listunspent shows old and confirmed TX` now that we know what the actual problem is.

**Comment by yyforyongyu** [comment] 2022-11-03 15:42
#6939 related?

**Comment by guggero** [comment] 2022-11-29 20:01
I've been spending quite a bit of time trying to reproduce the problem. There seems to be a timing component to this so it only happens sometimes. It would really help a lot if I could take a look at the wallet file to find out how the data looks like in such a case. That way we could at least create a fix for the affected UTXOs (and that would maybe also give us a hint at how this happens in the first place).
@walmer-bolfet or @xjmzx would either of you be willing to share the encrypted `wallet.db` file with me? Without the password I wouldn't be able to access funds, only see past transaction history. If yes, could you please DM me on Slack? That would be very helpful!

**Comment by walmer-bolfet** [comment] 2022-11-30 15:29
@guggero 

As I consider your request ( I am still learning), is this the file you request? 
  ‘   /mnt/hdd/lnd/data/chain/bitcoin/mainnet/wallet.db’
     -rw------- 1 bitcoin bitcoin 4194304 Nov 30 09:13 wallet.db

Please help me understand the difference between the wallet.db file and ‘the encrypted’ wallet.db file.  Is a manual encryption of this file necessary?  Why, if the password is not shared?

**Closed** 2022-12-08 21:09 UTC
Labels: bug, wallet, missing reproduction

**Comment by walmer-bolfet** [comment] 2022-12-08 22:31
The issue is closed, but what must the user do to implement the fix?

**Comment by guggero** [comment] 2022-12-08 22:34
After the next version that includes the fix (likely `v0.16.0-beta`) is out, you need to restart with `--reset-wallet-transactions` one more time to fix the UTXOs.
