### ISSUE TITLE
lnd crash (SIGSEGV) with sendtoroute

### ISSUE THREAD

**Issue by jogc** [lightningnetwork/lnd#2102] opened 2018-10-26 13:00 UTC
Been experimenting with sendtoroute and got a few crashes.

lnd: lnd-linux-amd64-v0.5-beta
bitcoind: bitcoin-0.16.3-x86_64-linux-gnu

Log snippets:

Oct 20 04:53:09 X lnd[12930]: 2018-10-20 04:53:09.218 [INF] DISC: Broadcasting batch of 6 new announcements
Oct 20 04:53:18 X lnd[12930]: 2018-10-20 04:53:18.198 [ERR] RPCS: Unable to get link for channel f5c22b0a2f318899097af3a163625b230f7f7844616b754fb282d126e3cfc19e: channel link not found
Oct 20 04:53:18 X lnd[12930]: 2018-10-20 04:53:18.320 [ERR] CRTR: Attempt to send payment 0000000000000000000000000000000000000000000000000000000000000000 failed: payment is in transition
Oct 20 04:53:32 X lnd[12930]: 2018-10-20 04:53:32.226 [ERR] RPCS: Unable to get link for channel f5c22b0a2f318899097af3a163625b230f7f7844616b754fb282d126e3cfc19e: channel link not found
Oct 20 04:53:32 X lnd[12930]: 2018-10-20 04:53:32.378 [ERR] CRTR: Attempt to send payment 0000000000000000000000000000000000000000000000000000000000000000 failed: payment is in transition
Oct 20 04:53:39 X lnd[12930]: 2018-10-20 04:53:39.218 [INF] DISC: Broadcasting batch of 2 new announcements
Oct 20 04:53:54 X lnd[12930]: 2018-10-20 04:53:54.196 [ERR] RPCS: Unable to get link for channel f5c22b0a2f318899097af3a163625b230f7f7844616b754fb282d126e3cfc19e: channel link not found
Oct 20 04:53:54 X lnd[12930]: 2018-10-20 04:53:54.327 [ERR] CRTR: Attempt to send payment 0000000000000000000000000000000000000000000000000000000000000000 failed: payment is in transition
Oct 20 04:54:09 X lnd[12930]: 2018-10-20 04:54:09.218 [INF] DISC: Broadcasting batch of 3 new announcements
Oct 20 04:54:34 X lnd[12930]: 2018-10-20 04:54:34.499 [INF] RPCS: [listchannels] fetched 115 channels from DB
Oct 20 04:54:37 X lnd[12930]: 2018-10-20 04:54:37.590 [INF] RPCS: [listchannels] fetched 115 channels from DB
Oct 20 04:54:39 X lnd[12930]: 2018-10-20 04:54:39.218 [INF] DISC: Broadcasting batch of 4 new announcements
Oct 20 04:54:39 X lnd[12930]: 2018-10-20 04:54:39.352 [ERR] RPCS: Unable to get link for channel f5c22b0a2f318899097af3a163625b230f7f7844616b754fb282d126e3cfc19e: channel link not found
Oct 20 04:54:39 X lnd[12930]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 20 04:54:39 X lnd[12930]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xcecf21]
Oct 20 04:54:39 X lnd[12930]: goroutine 47539422 [running]:
Oct 20 04:54:39 X lnd[12930]: main.unmarshallRoute(0xc00680db40, 0xc021efda00, 0x4, 0xc008bbe5e0, 0x4)

Oct 20 05:14:22 X lnd[25594]: 2018-10-20 05:14:22.539 [ERR] RPCS: Unable to get link for channel f5c22b0a2f318899097af3a163625b230f7f7844616b754fb282d126e3cfc19e: channel link not found
Oct 20 05:14:22 X lnd[25594]: 2018-10-20 05:14:22.549 [INF] CRTR: New channel discovered! Link connects 022b662aa03cf4db4820bcf4f47f1006d2bfae9bee416a926fb8bdba16e088d7f6 and 037b7cd33aada9dd91ccb95857d8f71c34fd31c426057016f28f48b0633ae844cd with ChannelPoint(31e41b09b91a55a6c4233de98008e773df920995dc09d110404a8e970f59322d:0): chan_id=564768545677639680, capacity=0.00002 BTC
Oct 20 05:14:22 X lnd[25594]: 2018-10-20 05:14:22.665 [INF] CRTR: New channel discovered! Link connects 03c7cad7e4ecfc741909b910d59b31b631e36afffc58e87389172c80702fddcbfa and 03f7e084886b0e23f1d9c6a0e0f3aad8b7dba787cd2a52aa315b9c3d816f59dc36 with ChannelPoint(144af4107aa5bfa54f496dd58ae793b978c0747bdc341309e47bdfcee89c263a:0): chan_id=561718500494147584, capacity=0.00025 BTC
Oct 20 05:14:22 X lnd[25594]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 20 05:14:22 X lnd[25594]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xcecf21]
Oct 20 05:14:22 X lnd[25594]: goroutine 324941 [running]:
Oct 20 05:14:22 X lnd[25594]: main.unmarshallRoute(0xc01489e740, 0xc00f69da00, 0x2, 0xc00cf3a560, 0x2)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3359 +0x3c1
Oct 20 05:14:22 X lnd[25594]: main.(*rpcServer).SendToRouteSync(0xc0006fa690, 0x1204760, 0xc003342090, 0xc01489e300, 0xc0006fa690, 0xc01d633c80, 0xc0002c1ce0)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:2388 +0x104
Oct 20 05:14:22 X lnd[25594]: github.com/lightningnetwork/lnd/lnrpc._Lightning_SendToRouteSync_Handler.func1(0x1204760, 0xc003342090, 0xef3d60, 0xc01489e300, 0x1, 0x1, 0x0, 0x0)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6674 +0x89
Oct 20 05:14:22 X lnd[25594]: github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0x1204760, 0xc003342090, 0xef3d60, 0xc01489e300, 0xc01d633c60, 0xc01d633c80, 0xc0076b4b50, 0x40c478, 0x50, 0xf32b80)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x153
Oct 20 05:14:22 X lnd[25594]: github.com/lightningnetwork/lnd/lnrpc._Lightning_SendToRouteSync_Handler(0xf8aa60, 0xc0006fa690, 0x1204760, 0xc003342090, 0xc00a832a00, 0xc0006375a0, 0x0, 0x0, 0x44634d, 0x0)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6676 +0x158
Oct 20 05:14:22 X lnd[25594]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a6b40, 0x1209e40, 0xc032b51080, 0xc004b42200, 0xc0006fa7b0, 0x19e22b0, 0xc003a002a0, 0x0, 0x0)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x8ec
Oct 20 05:14:22 X lnd[25594]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0002a6b40, 0x1209e40, 0xc032b51080, 0xc004b42200, 0xc003a002a0)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1308
Oct 20 05:14:22 X lnd[25594]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000530440, 0xc0002a6b40, 0x1209e40, 0xc032b51080, 0xc004b42200)
Oct 20 05:14:22 X lnd[25594]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f

Oct 23 21:52:04 X lnd[26803]: 2018-10-23 13:52:04.448 [INF] HSWC: Sent 0 satoshis and received 0 satoshis in the last 10 seconds (0.700000 tx/sec)
Oct 23 21:52:04 X lnd[26803]: 2018-10-23 13:52:04.875 [ERR] CRTR: Attempt to send payment 963193db44b93545a01eb44f485e283b1be3bd5db1efe1fca4c3fe8616c68db7 failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc0043cb220)({
Oct 23 21:52:04 X lnd[26803]:  Signature: (lnwire.Sig) (len=64 cap=64) {
Oct 23 21:52:04 X lnd[26803]:   00000000  8e 9c 34 35 d9 dc e0 ba  6e af a9 1c b1 90 f6 17  |..45....n.......|
Oct 23 21:52:04 X lnd[26803]:   00000010  41 9c 73 50 01 fd e8 a1  eb e2 5d 2d 2e 62 e8 f1  |A.sP......]-.b..|
Oct 23 21:52:04 X lnd[26803]:   00000020  16 ba 30 d3 aa 0d 1a 44  38 e0 9c 58 c5 97 63 7e  |..0....D8..X..c~|
Oct 23 21:52:04 X lnd[26803]:   00000030  fa 66 9f b5 89 90 2e 13  3c 28 ac 96 71 3e b3 da  |.f......<(..q>..|
Oct 23 21:52:04 X lnd[26803]:  },
Oct 23 21:52:04 X lnd[26803]:  ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
Oct 23 21:52:04 X lnd[26803]:  ShortChannelID: (lnwire.ShortChannelID) 546905:2189:1,
Oct 23 21:52:04 X lnd[26803]:  Timestamp: (uint32) 1540245094,
Oct 23 21:52:04 X lnd[26803]:  Flags: (lnwire.ChanUpdateFlag) 1,
Oct 23 21:52:04 X lnd[26803]:  TimeLockDelta: (uint16) 14,
Oct 23 21:52:04 X lnd[26803]:  HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,
Oct 23 21:52:04 X lnd[26803]:  BaseFee: (uint32) 1000,
Oct 23 21:52:04 X lnd[26803]:  FeeRate: (uint32) 10,
Oct 23 21:52:04 X lnd[26803]:  ExtraOpaqueData: ([]uint8) <nil>
Oct 23 21:52:04 X lnd[26803]: })
Oct 23 21:52:04 X lnd[26803]: )
Oct 23 21:52:07 X lnd[26803]: 2018-10-23 13:52:07.750 [ERR] CRTR: Attempt to send payment 963193db44b93545a01eb44f485e283b1be3bd5db1efe1fca4c3fe8616c68db7 failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc00f42fea0)({
Oct 23 21:52:07 X lnd[26803]:  Signature: (lnwire.Sig) (len=64 cap=64) {
Oct 23 21:52:07 X lnd[26803]:   00000000  8e 9c 34 35 d9 dc e0 ba  6e af a9 1c b1 90 f6 17  |..45....n.......|
Oct 23 21:52:07 X lnd[26803]:   00000010  41 9c 73 50 01 fd e8 a1  eb e2 5d 2d 2e 62 e8 f1  |A.sP......]-.b..|
Oct 23 21:52:07 X lnd[26803]:   00000020  16 ba 30 d3 aa 0d 1a 44  38 e0 9c 58 c5 97 63 7e  |..0....D8..X..c~|
Oct 23 21:52:07 X lnd[26803]:   00000030  fa 66 9f b5 89 90 2e 13  3c 28 ac 96 71 3e b3 da  |.f......<(..q>..|
Oct 23 21:52:07 X lnd[26803]:  },
Oct 23 21:52:07 X lnd[26803]:  ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
Oct 23 21:52:07 X lnd[26803]:  ShortChannelID: (lnwire.ShortChannelID) 546905:2189:1,
Oct 23 21:52:07 X lnd[26803]:  Timestamp: (uint32) 1540245094,
Oct 23 21:52:07 X lnd[26803]:  Flags: (lnwire.ChanUpdateFlag) 1,
Oct 23 21:52:07 X lnd[26803]:  TimeLockDelta: (uint16) 14,
Oct 23 21:52:07 X lnd[26803]:  HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,
Oct 23 21:52:07 X lnd[26803]:  BaseFee: (uint32) 1000,
Oct 23 21:52:07 X lnd[26803]:  FeeRate: (uint32) 10,
Oct 23 21:52:07 X lnd[26803]:  ExtraOpaqueData: ([]uint8) <nil>
Oct 23 21:52:07 X lnd[26803]: })
Oct 23 21:52:07 X lnd[26803]: )
Oct 23 21:52:07 X lnd[26803]: 2018-10-23 13:52:07.996 [INF] CRTR: Updated vertex data for node=02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469
Oct 23 21:52:14 X lnd[26803]: 2018-10-23 13:52:14.448 [INF] HSWC: Sent 0 satoshis and received 0 satoshis in the last 10 seconds (0.200000 tx/sec)
Oct 23 21:52:27 X lnd[26803]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 23 21:52:27 X lnd[26803]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xcecdf6]

Let me know if you need anything else

**Comment by wpaulino** [comment] 2018-10-26 16:05
Closing as duplicate of #2101.

**Closed by wpaulino** 2018-10-26 16:05 UTC
