### ISSUE TITLE
Force close transaction in mempool not seen by LND

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#5682] opened 2021-08-31 19:26 UTC
### Background

An LND node got a channel with Eclair node which was force-closed by Eclair due to fee difference. The close transaction is in the mempool (yes, also in mempool of the node LND is connected to) and Eclair reports the channel as closing while LND doesn't see it and only reports being not active. 

### Your environment

* version of `lnd` 0.13.1
* which operating system (`uname -a` on *Nix) Debian 10, x86_64
* version of `btcd`, `bitcoind`, or other backend 0.21.1
* any other relevant environment details

### Steps to reproduce

0. Open a channel from LND with Eclair (non-anchors)
1. Transfer some sats to the other side
2. Cause force-close from Eclair
3. Check Eclair status - see it as Closing
4. Get TXID of closing transaction and check mempool of node which LND uses
5. Check status in LND (`listchannels`, `pendingchannels` or use ThunderHub UI)

### Expected behaviour

LND reports the status as closing

### Actual behaviour

LND reports status as `"active": false`

### Note

I do realize that maybe this it is intentional to not report it as closing because it's not guaranteed the transaction confirms but just `"active": false` sounds like missing important information ("will most likely be closed"). So if this indeed is intentional I propose adding the information somehow.

**Comment by Roasbeef** [comment] 2021-09-01 02:57
`lnd` doesn't detect things at closed until it hits the chain. We don't look at the mempool as that's no guarantee w.r.t what will eventually confirm. If we record TXID `X` as the closing TXID, start to write state to act upon that, but then TXID `Y` confirms, we need to roll that back which complicates the logic. Also clients like neutrino aren't aware of the mempool at all, so we're able to have a consistent interface across everything by never actually looking at the mempool.

**Comment by Roasbeef** [comment] 2021-09-01 03:10
If _lnd_ was the one that force closed, then we would show it as "closing" since we were the one that broadcasted it. 

I'm curious to learn why a free disagreement cased the force close in the first place though, perhaps lets open another issue to investigate that?

**Comment by Kixunil** [comment] 2021-09-01 07:58
Sure, that's what I thought. Would it be reasonable to add something like "maybe closing" indicator so that users know there's something going on and LND functions properly even though nothing is guaranteed?

Fee disagreement is classical pre-anchors problem when fees spike. Eclair doesn't support anchors yet (should in next release) that's the issue.

**Comment by Roasbeef** [comment] 2021-09-02 00:57
> Would it be reasonable to add something like "maybe closing" indicator so that users know there's something going on and LND functions properly even though nothing is guaranteed?

The issue is that we don't know that things are actually closing, since it's possible the other peer just isn't available anymore. I think the new `warning` message w/ structured errors (https://github.com/lightningnetwork/lnd/pull/5560) will help here, as then the remote party can send a message saying "just letting you know, I broadcasted a transaction".

**Closed by Roasbeef** 2021-09-02 00:57 UTC
Labels: question, channel management, chain handling
