### ISSUE TITLE
Consistent backup of channel.db of running LND

### ISSUE THREAD

**Issue by ratpoison4** [lightningnetwork/lnd#5679] opened 2021-08-30 19:33 UTC
## Background

Imagine my SSD crashes and I need to recover funds from channels. I use Static Channel Backup, but it is good only if another node is not broken, online and cooperative. What if another node is also broken or offline or does not want to cooperate? I would like to have a method to restore funds from remaining channels after I recover using Static Channel Backup. 

I can not just `cp` or `rsync` channel.db while LND is running, because it can change in the middle and I may end up with inconsistent backup. So I need to stop LND to make a backup, then start it back again, enter password to unlock the wallet. I would like to have backup of channel db generated by `lnd` / `lncli` on the fly:

```
$ lncli backup-channel-db | ssh backup-server 'cat - > /backups/channel.db'
```
or at least
```
$ lncli backup-channel-db  --destination /tmp/channel.db
```

## Research

I see in https://pkg.go.dev/github.com/btcsuite/btcwallet/walletdb#DB the following interesting method:

```
  // Copy writes a copy of the database to the provided writer.  This
  // call will start a read-only transaction to perform all operations.
  Copy(w io.Writer) error
```

I guess it could be used to produce consistent backup of channel.db without stopping LND (which I want to avoid).

Is this method safe? (Not corrupting source database and producing consistent output.)

Is this method expensive? (Blocking entire LND while working.)

**Comment by Roasbeef** [comment] 2021-08-30 19:36
Closing as a duplicate of: https://github.com/lightningnetwork/lnd/issues/1626 

With the latest versions of lnd (0.14 incoming release), you can opt to use one of the _replicated_ database backends to have it store and maintain copies of the `channeldb` state in a consistent manner.

**Closed by Roasbeef** 2021-08-30 19:36 UTC
