### ISSUE TITLE
Local Neutrino Unreacheable when Tor Enabled

### ISSUE THREAD

**Issue by contrebande-labs** [lightningnetwork/lnd#6622] opened 2022-06-07 03:35 UTC
### Background

When Tor is enabled, the local Neutrino node is unaccessible because LND tries to reach it via Tor and of course, Tor then rejects the connection. Tried "127.0.0.1" and "localhost". I also think Tor should be bypassed for any private subnet (docker, k8s).

### Your environment

* version of `lnd` : v0.15.0-beta.rc3
* which operating system (`uname -a` on *Nix): Linux 5.13.0-44-generic 49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.23, neutrino mode, local
* any other relevant environment details

### Steps to reproduce

Just start LND with neutrino enabled and pointing to a local or private IP address and with tor enabled also.

### Expected behaviour

LND should know not to try to connect to loopback and private subnet IP addresses via Tor.

### Actual behaviour

LND says "tor host unreachable" (and retries forever), Tor says "Rejecting SOCKS request for anonymous connection to private address [scrubbed]."

**Comment by guggero** [comment] 2022-06-07 07:58
Duplicate of https://github.com/lightningnetwork/lnd/issues/5647 (same problem), proposed fix: https://github.com/lightningnetwork/lnd/pull/5651

**Closed by guggero** 2022-06-07 07:58 UTC
