### ISSUE TITLE
FeeInsufficient with sendtoroute

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#3301] opened 2019-07-11 14:47 UTC
queryroutes calcualtes wrong fee:

Running a private LTCD chain (simnet) with lnd 0.6.1-beta.

channels:
A<>B<>C

Trying to send from A to B:
There is a route with 12 sat fee.
```
lndltc-lncli queryroutes 0348921ac72c978e5e634410501bf843b1d103daea9025fecccfb0ddb33d1cc948 12000000 --fee_limit 100
{
    "routes": [
        {
            "total_time_lock": 2682,
            "total_fees": "12",
            "total_amt": "12000012",
            "hops": [
                {
                    "chan_id": "456297325592577",
                    "chan_capacity": "225000000000",
                    "amt_to_forward": "12000000",
                    "fee": "12",
                    "expiry": 2106,
                    "amt_to_forward_msat": "12000000000",
                    "fee_msat": "12000",
                    "pub_key": "03e26345aa5d7024668e1f16adc2ecd85907a930820ad5a32736946cb824067eeb"
                },
                {
                    "chan_id": "2106664278884353",
                    "chan_capacity": "225000000000",
                    "amt_to_forward": "12000000",
                    "fee": "0",
                    "expiry": 2106,
                    "amt_to_forward_msat": "12000000000",
                    "fee_msat": "0",
                    "pub_key": "0348921ac72c978e5e634410501bf843b1d103daea9025fecccfb0ddb33d1cc948"
                }
            ],
            "total_fees_msat": "12000",
            "total_amt_msat": "12000012000"
        }
    ]
}
```

Trying to use it:
```
lndltc-lncli queryroutes 0348921ac72c978e5e634410501bf843b1d103daea9025fecccfb0ddb33d1cc948 12300000 --fee_limit 100|lndltc-lncli sendtoroute d46111b832b26008e45aae1698402350b3140d874d0c11382374726957fa9393 -
{
	"payment_error": "unable to route payment to destination: FeeInsufficient(htlc_amt==12300000000 mSAT, update=(lnwire.ChannelUpdate) {\n Signature: (lnwire.Sig) (len=64 cap=64) {\n  00000000  c7 9f 09 f8 8b 8c 6e c6  dc 95 72 5b 31 8f 2b 49  |......n...r[1.+I|\n  00000010  ef e5 56 f7 c0 30 8e ef  c9 d2 8d 76 f4 dc cb ff  |..V..0.....v....|\n  00000020  42 40 49 f9 c9 97 c0 a8  a8 5b 35 0e e7 fa 00 8a  |B@I......[5.....|\n  00000030  81 d4 e3 61 47 2c 6d ae  f0 06 91 06 d8 2f 8b 48  |...aG,m....../.H|\n },\n ChainHash: (chainhash.Hash) (len=32 cap=32) 1235c919b81ddcb578b67dce20669fd0c9c5a3450dbcfa2b869dbcb43a3ba4be,\n ShortChannelID: (lnwire.ShortChannelID) 1916:1:1,\n Timestamp: (uint32) 1562849998,\n MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,\n ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000001,\n TimeLockDelta: (uint16) 576,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,\n BaseFee: (uint32) 0,\n FeeRate: (uint32) 1,\n HtlcMaximumMsat: (lnwire.MilliSatoshi) 222750000000000 mSAT,\n ExtraOpaqueData: ([]uint8) \u003cnil\u003e\n}\n",
	"payment_preimage": "",
	"payment_route": null
}
```

On B logs I see this:

```
lndltc-lncli queryroutes 0348921ac72c978e5e634410501bf843b1d103daea9025fecccfb0ddb33d1cc948 12300000 --fee_limit 100|lndltc-lncli sendtoroute d46111b832b26008e45aae1698402350b3140d874d0c11382374726957fa9393 -
{
	"payment_error": "unable to route payment to destination: FeeInsufficient(htlc_amt==12300000000 mSAT, update=(lnwire.ChannelUpdate) {\n Signature: (lnwire.Sig) (len=64 cap=64) {\n  00000000  c7 9f 09 f8 8b 8c 6e c6  dc 95 72 5b 31 8f 2b 49  |......n...r[1.+I|\n  00000010  ef e5 56 f7 c0 30 8e ef  c9 d2 8d 76 f4 dc cb ff  |..V..0.....v....|\n  00000020  42 40 49 f9 c9 97 c0 a8  a8 5b 35 0e e7 fa 00 8a  |B@I......[5.....|\n  00000030  81 d4 e3 61 47 2c 6d ae  f0 06 91 06 d8 2f 8b 48  |...aG,m....../.H|\n },\n ChainHash: (chainhash.Hash) (len=32 cap=32) 1235c919b81ddcb578b67dce20669fd0c9c5a3450dbcfa2b869dbcb43a3ba4be,\n ShortChannelID: (lnwire.ShortChannelID) 1916:1:1,\n Timestamp: (uint32) 1562849998,\n MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,\n ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000001,\n TimeLockDelta: (uint16) 576,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,\n BaseFee: (uint32) 0,\n FeeRate: (uint32) 1,\n HtlcMaximumMsat: (lnwire.MilliSatoshi) 222750000000000 mSAT,\n ExtraOpaqueData: ([]uint8) \u003cnil\u003e\n}\n",
	"payment_preimage": "",
	"payment_route": null
}
```
channel between A and B (on A)
```
lndltc-lncli getchaninfo 456297325592577
{
    "channel_id": "456297325592577",
    "chan_point": "7b5c360c298ab4c90d406702990484c1b0bb9af8c192a651b3b4d236237fd693:1",
    "last_update": 1562794801,
    "node1_pub": "0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f",
    "node2_pub": "03e26345aa5d7024668e1f16adc2ecd85907a930820ad5a32736946cb824067eeb",
    "capacity": "225000000000",
    "node1_policy": {
        "time_lock_delta": 576,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "222750000000000"
    },
    "node2_policy": {
        "time_lock_delta": 576,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "222750000000000"
    }
}
```

on B:
```
{
    "channel_id": "456297325592577",
    "chan_point": "7b5c360c298ab4c90d406702990484c1b0bb9af8c192a651b3b4d236237fd693:1",
    "last_update": 1562794801,
    "node1_pub": "0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f",
    "node2_pub": "03e26345aa5d7024668e1f16adc2ecd85907a930820ad5a32736946cb824067eeb",
    "capacity": "225000000000",
    "node1_policy": {
        "time_lock_delta": 576,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "222750000000000"
    },
    "node2_policy": {
        "time_lock_delta": 576,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "222750000000000"
    }
}
```

**Comment by offerm** [comment] 2019-07-11 15:29
Note - problem disappear when I set a value fo "fee_base_msat" for node2_policy.

**Comment by Roasbeef** [comment] 2019-07-11 23:11
Can you reproduce this on 0.7?

**Comment by wpaulino** [comment] 2019-07-29 19:58
Closing due to no updates.

**Closed by wpaulino** 2019-07-29 19:58 UTC

**Comment by halseth** [comment] 2019-08-05 12:33
Would be very interested to hear if this is still a problem.

@offerm Please re-open if you still see this on 0.7.1.

**Comment by offerm** [comment] 2019-08-05 15:09
Yes, I think the problem is there. A possible reason might be that I'm
using large amounts (beyond the limits).
I will see how to reproduce.

**Comment by oparex** [comment] 2019-08-20 11:12
Trying to reproduce this one on simnet with lnd 0.7.1 (I am interested in this problem because I am getting FeeInsufficient on mainnet while trying to send a payment to myself over 2 other nodes) similar as @offerm (I used smaller channel capacaties because of default max for channels and also used smaller transaction because of default max for transactions).

```lncli-alice queryroutes 03df4ad62d9717d5d1a1ce0cbebb2481ba97882a7a7a5ffabc2ecfe958ca60bfcf 1200000
{
    "routes": [
        {
            "total_time_lock": 489,
            "total_fees": "2",
            "total_amt": "1200002",
            "hops": [
                {
                    "chan_id": "473889511636992",
                    "chan_capacity": "10000000",
                    "amt_to_forward": "1200000",
                    "fee": "2",
                    "expiry": 449,
                    "amt_to_forward_msat": "1200000000",
                    "fee_msat": "2200",
                    "pub_key": "0207b64fa72c3d7d21b1ba33474711b671d8698b61c35851b6a8e557a5911a219b"
                },
                {
                    "chan_id": "473889511702528",
                    "chan_capacity": "10000000",
                    "amt_to_forward": "1200000",
                    "fee": "0",
                    "expiry": 449,
                    "amt_to_forward_msat": "1200000000",
                    "fee_msat": "0",
                    "pub_key": "03df4ad62d9717d5d1a1ce0cbebb2481ba97882a7a7a5ffabc2ecfe958ca60bfcf"
                }
            ],
            "total_fees_msat": "2200",
            "total_amt_msat": "1200002200"
        }
    ]
}
```
With result
```
lncli-alice queryroutes 03df4ad62d9717d5d1a1ce0cbebb2481ba97882a7a7a5ffabc2ecfe958ca60bfcf 1200000 | lncli-alice sendtoroute --pay_hash=8f6ce036cbf5da43c0ca484f24cafb0bc150d0839a5b2194fe64ec5284658137 -
{
	"payment_error": "IncorrectOrUnknownPaymentDetails(amt=1200000000 mSAT)",
	"payment_preimage": "",
	"payment_route": null
}
```
Channel A>B
```
{
    "channel_id": "473889511636992",
    "chan_point": "aacc2f2c53057cf38cb4caa24316f3c7a6dfafc5dda37a64f1b321e15ee53aae:0",
    "last_update": 1566297934,
    "node1_pub": "0207b64fa72c3d7d21b1ba33474711b671d8698b61c35851b6a8e557a5911a219b",
    "node2_pub": "037a2227d9535056d7b9c441865efe261be4bc6376cf3896785e9f0fc183653089",
    "capacity": "10000000",
    "node1_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "9900000000",
        "last_update": 1566297934
    },
    "node2_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "9900000000",
        "last_update": 1566297934
    }
}
```
Channel B>C
```
{
    "channel_id": "473889511702528",
    "chan_point": "cefec5a9f57187b2dae3336b042493813c799df4510352f7c760956aefd8e88a:0",
    "last_update": 1566297934,
    "node1_pub": "0207b64fa72c3d7d21b1ba33474711b671d8698b61c35851b6a8e557a5911a219b",
    "node2_pub": "03df4ad62d9717d5d1a1ce0cbebb2481ba97882a7a7a5ffabc2ecfe958ca60bfcf",
    "capacity": "10000000",
    "node1_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "9900000000",
        "last_update": 1566297934
    },
    "node2_policy": {
        "time_lock_delta": 40,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "9900000000",
        "last_update": 1566297934
    }
}
```

I have generated pay_hash with
```
lncli-charlie addinvoice 1200000
{
	"r_hash": "8f6ce036cbf5da43c0ca484f24cafb0bc150d0839a5b2194fe64ec5284658137",
	"pay_req": "lnsb12m1pw4h5s8pp53akwqdkt7hdy8sx2fp8jfjhmp0q4p5yrnfdjr987vnk99pr9symsdqqcqzpgrxgt3qlsqqaev6wjf3pmaraxg3thv9wtnmpldxre70jdn7y5uws990lzdtmcxs463fe33ufuw2vm93g4hjanrs7e5dqjxskam59w4kspfw5pta",
	"add_index": 2
}

```

I am willing to test this further, please give instructions.

**Comment by alexbosworth** [comment] 2019-08-20 19:58
@oparex your error looks pretty expected

Try to get a route that results in an invalid fee or incorrect cltv error

**Comment by offerm** [comment] 2019-08-20 21:08
I managed to reproduce it, 

```
admins-MacBook-Pro-2:~ admin$ lndltc-lncli queryroutes 0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f  12300000 --fee_limit 100|lndltc-lncli sendtoroute  9b884dcfb2595de3f3fdfe1e51bb425feda0214ef73c05e9354f8662fad66b4a -
{
	"payment_error": "FeeInsufficient(htlc_amt==12300000000 mSAT, update=(lnwire.ChannelUpdate) {\n Signature: (lnwire.Sig) (len=64 cap=64) {\n  00000000  ef 76 c1 e7 33 91 d2 98  bc 5e ef 63 3f b1 ba f7  |.v..3....^.c?...|\n  00000010  aa 25 a1 b9 d7 88 2f 5b  9c 11 1a cf d7 a6 e1 3c  |.%..../[.......\u003c|\n  00000020  54 4d 5e 0b ce 76 35 8b  68 7c 52 aa ff e0 30 5f  |TM^..v5.h|R...0_|\n  00000030  1b f9 96 19 a5 22 b9 1e  89 5d 3f c4 4c 7e 54 70  |.....\"...]?.L~Tp|\n },\n ChainHash: (chainhash.Hash) (len=32 cap=32) 1235c919b81ddcb578b67dce20669fd0c9c5a3450dbcfa2b869dbcb43a3ba4be,\n ShortChannelID: (lnwire.ShortChannelID) 415:2:1,\n Timestamp: (uint32) 1566334772,\n MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,\n ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000001,\n TimeLockDelta: (uint16) 576,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,\n BaseFee: (uint32) 0,\n FeeRate: (uint32) 1,\n HtlcMaximumMsat: (lnwire.MilliSatoshi) 222750000000000 mSAT,\n ExtraOpaqueData: ([]uint8) \u003cnil\u003e\n}\n",
	"payment_preimage": "",
	"payment_route": null
}
```

Will collect and send data tomorrow.

**Comment by alexbosworth** [comment] 2019-08-20 21:13
make sure to set the final ctlv delta too

**Comment by offerm** [comment] 2019-08-21 09:08
@alexbosworth as you can see I got the error without using final cltv delta.
The routing node (B) failed it on FeeInsufficient.

Strangely, this morning I can't reproduce. Will keep trying

**Comment by offerm** [comment] 2019-08-21 11:43
OK, I can't reproduce with 0.7.1.

I can reproduce by changing the policy on route B (increase fee) during the update window. I guess that is OK.

Thanks!

**Comment by Kixunil** [comment] 2019-08-29 12:59
Not sure if this is the same issue, but I found something:

* BLW connected to Eclair connected to LND
* BLW-eclair channel has feeProportionalMillionth set to 100 as reported by Eclair (using channells command) and feeBaseMsat set to 1000
* BLW created an invoice, the invoice is passed to `lncli decodepayreq` - it reports fee_base_msat: 100 and fee_proportional_millionths: 10

So either BLW encodes hop hints incorrectly or LND decodes them incorrectly, or I misunderstood something.

CC @btconract

I might be able to look at the code in a while.

**Comment by Kixunil** [comment] 2019-08-29 13:25
Since https://lndecode.com reports the same as LND (no, it doesn't request LND in the background), I guess the bug is in BLW.
