### ISSUE TITLE
Memory issues on 0.5.2?

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#2685] opened 2019-02-22 07:14 UTC
Several users are reporting issues with LND 0.5.2. 

CPU and memory overuse caused by errors in LND and NBXplorer since 0.5.2. (see https://github.com/btcpayserver/btcpayserver/issues/605)

I personally did not encountered this problem though. Is there a commit around which would fix this?

**Comment by NicolasDorier** [comment] 2019-02-22 07:17
Might be related to https://github.com/lightningnetwork/lnd/issues/2551

**Comment by Roasbeef** [comment] 2019-02-23 19:44
Nothing really changed much in 0.5.2...however are these people also running bitcoind 0.17? Perhaps something changed with the RPC or ZMQ connections to cause the ZMQ connection to drop more often?

**Comment by NicolasDorier** [comment] 2019-02-24 07:09
I am not sure I will follow #2658 and #2686. It might be related.

**Comment by ccdle12** [comment] 2019-02-28 16:37
@NicolasDorier I posted a screenshot on BTCPay Server chat. I was experience 6GB RAM usage with `nbxplorer`.

I ran btcpay update as suggested, and seems to have fixed the issue. So thought I would share this here if others find themselves on this issue.

**Comment by NicolasDorier** [comment] 2019-03-01 08:24
@ccdle12 this is unrelated. The problem I am reporting is high RAM consumption from LND.

**Comment by wpaulino** [comment] 2019-03-12 19:10
This is likely due to the massive increase of the mainnet channel graph. We are aware of the issue. Closing as duplicate of #2658.

**Closed by wpaulino** 2019-03-12 19:10 UTC
