### ISSUE TITLE
Allow non-default routing policy on channel open

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#6534] opened 2022-05-12 17:35 UTC
Lnd's `OpenChannel` apis currently don't allow a routing policy to be specified. Channels are always first announced and updated with the default routing policy. A subsequent call to `UpdateChanPolicy` is required to change the policy.

Nodes on the network may have rate limits in place that prevent a second channel update right after the first one from being propagated. 

If the final fee is higher, senders will run into a failure accompanied by the latest policy. Probably not an issue?

If the final fee is lower, the channel may be avoided unnecessarily for some time by senders because cheaper routes (that wouldn't be cheaper if they had the final fee update) are available.

### Your environment

* lnd v0.14.3-beta

**Comment by Roasbeef** [comment] 2022-05-12 20:41
Duplicate of https://github.com/lightningnetwork/lnd/issues/800

**Closed by Roasbeef** 2022-05-12 20:41 UTC
