### ISSUE TITLE
Remove unconfirmed but force-closed channels after two weeks as well

### ISSUE THREAD

**Issue by bcwhite0** [lightningnetwork/lnd#4566] opened 2020-08-25 01:41 UTC
### Background

I have two channels, attempted by Autopilot during first run, that were never able to open -- it looks like the coins they wanted to use have already been spent.  I used `closechannel` (with and without "force") on them but they remain pending.

Here's one of them:
```
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "02fffb0baa1f8a64d92c8b4222278c33a9c16d0f37bba24104c678fd9e4e7f57d6",
                "channel_point": "bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0",
                "capacity": "3566965",
                "local_balance": "3565155",
                "remote_balance": "0",
                "local_chan_reserve_sat": "35669",
                "remote_chan_reserve_sat": "35669",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "3565155",
            "commitments": {
                "local_txid": "2ae855b113ef1ba388006e5145dfe48f6237d2afdc23337c22ccf65f94910df0",
                "remote_txid": "1ceb0114ddd39a9cd028235f2b1596b0c8729be70ecda31b382c9d29fbc4645e",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "1810",
                "remote_commit_fee_sat": "1810",
                "remote_pending_commit_fee_sat": "0"
            }
        },
        ...
    ]
```

And here is a cluster of log messages related to that channel:
```
2020-08-23 16:46:13.634 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0)
2020-08-23 16:46:13.635 [ERR] FNDG: Unable to advance pending state of ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0): error waiting for funding confirmation for ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0): waiting for fundingconfirmation failed
2020-08-23 16:46:58.760 [INF] CNCT: Re-publishing force close tx(2ae855b113ef1ba388006e5145dfe48f6237d2afdc23337c22ccf65f94910df0) for channel bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0
2020-08-23 16:46:58.760 [INF] LNWL: Inserting unconfirmed transaction 2ae855b113ef1ba388006e5145dfe48f6237d2afdc23337c22ccf65f94910df0
2020-08-23 16:46:58.784 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0x315fdc0)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0x3d2f640)({
   PreviousOutPoint: (wire.OutPoint) bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) (len=4 cap=4) {
    ([]uint8) {
    },
    ([]uint8) (len=72 cap=72) {
     00000000  30 45 02 21 00 86 a4 b5  ae c4 05 d8 03 a6 c1 69  |0E.!...........i|
     00000010  ea 5d ba 65 8d 68 f0 62  3e d3 29 8a 06 f7 bb 53  |.].e.h.b>.)....S|
     00000020  56 7a 83 57 ae 02 20 1f  9c ab 87 3b e9 ae ae 86  |Vz.W.. ....;....|
     00000030  2d 78 bd 01 68 fd e4 52  d4 96 b9 f5 49 03 dc f7  |-x..h..R....I...|
     00000040  43 2e 21 71 a7 a1 f9 01                           |C.!q....|
    },
    ([]uint8) (len=71 cap=71) {
     00000000  30 44 02 20 63 dc 0c 46  a3 26 83 3a 9e 54 43 3f  |0D. c..F.&.:.TC?|
     00000010  c3 bf 52 16 93 b2 d0 b9  ac 7a 61 54 d0 e3 3d 5c  |..R......zaT..=\|
     00000020  fa 7b 27 0f 02 20 25 5c  05 28 7b 4b d5 d5 76 79  |.{'.. %\.({K..vy|
     00000030  ed 5a 8a cc 66 64 3a 4d  cf 21 c4 7f 8b 8b 06 c8  |.Z..fd:M.!......|
     00000040  0c 4c 3a 3b ae 7b 01                              |.L:;.{.|
    },
    ([]uint8) (len=71 cap=71) {
     00000000  52 21 02 c0 41 7f f9 38  eb f4 45 69 4c d4 cf 0e  |R!..A..8..EiL...|
     00000010  c1 be da 7b 18 b9 f4 ac  4c a1 1f 70 9e 34 cc 8b  |...{....L..p.4..|
     00000020  cc 5f ac 21 03 7d fd 4d  fd 18 08 de b9 2b 2b 4e  |._.!.}.M.....++N|
     00000030  c4 f3 ca 47 e7 01 ef 72  20 22 c2 11 3d 62 30 d0  |...G...r "..=b0.|
     00000040  98 a2 10 1f 30 52 ae                              |....0R.|
    }
   },
   Sequence: (uint32) 2157794445
  })
 },
 TxOut: ([]*wire.TxOut) (len=1 cap=1) {
  (*wire.TxOut)(0x315fde0)({
   Value: (int64) 3565155,
   PkScript: ([]uint8) (len=34 cap=34) {
    00000000  00 20 10 74 00 11 8e 0e  49 be 7a e5 af 8a 85 63  |. .t....I.z....c|
    00000010  33 c2 00 82 3b d3 80 ec  8b de cc 94 f1 32 9d 7b  |3...;........2.{|
    00000020  5c 9d                                             |\.|
   }
  })
 },
 LockTime: (uint32) 552836133
})
2020-08-23 16:46:58.817 [INF] NTFN: New spend subscription: spend_id=8, outpoint=bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0, script=0 c0631a6a6196cb42f36342931e5f4799843bf4549c4b292d433fdf99930cd457, height_hint=645048
2020-08-23 16:46:58.817 [INF] NTFN: Dispatching historical spend rescan for outpoint=bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0, script=0 c0631a6a6196cb42f36342931e5f4799843bf4549c4b292d433fdf99930cd457, start=645048, end=645048
2020-08-23 16:46:58.890 [INF] CNCT: Close observer for ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0) active
2020-08-23 16:46:59.030 [INF] NTFN: Historical spend dispatch finished for request outpoint=bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0, script=0 c0631a6a6196cb42f36342931e5f4799843bf4549c4b292d433fdf99930cd457 (start=645048 end=645048) with details: <nil>
2020-08-23 16:46:59.058 [INF] CNCT: ChannelArbitrator(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0): starting state=StateCommitmentBroadcasted, trigger=chainTrigger, triggerHeight=645048
2020-08-23 16:46:59.073 [INF] CNCT: ChannelArbitrator(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0): trigger chainTrigger moving from state StateCommitmentBroadcasted to StateCommitmentBroadcasted
2020-08-23 16:47:00.202 [INF] LNWL: Inserting unconfirmed transaction bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076
2020-08-23 16:47:00.220 [ERR] FNDG: Unable to rebroadcast funding tx 0200000000010117805b2f3552cb0a24ca0fb2f70c4d9146578c59bbd6025d1c484faff4fe6e8e01000000000000000002756d360000000000220020c0631a6a6196cb42f36342931e5f4799843bf4549c4b292d433fdf99930cd457c8a0420000000000160014fa755713f69d7e2718a6c0c02519cf1a7b985f2c02483045022100b388462528d4da701615c2f85cfaeb41ee7ed8c152f6edf94ff1871b62b2ba7f0220401690005eb3f5cb210efb61aa6a8010d26df6e858ede6a6ad7d7d89e83e8910012103e2496cd002fbab38df1c2b6bb077fb760c59bc68b86c2450354912452d4fd80800000000 for ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0): transaction rejected: output already spent
2020-08-23 16:47:00.223 [INF] NTFN: New confirmation subscription: conf_id=1, txid=bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076, num_confs=3 height_hint=645048
2020-08-23 16:47:00.224 [INF] FNDG: Waiting for funding tx (bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076) to reach 3 confirmations
2020-08-23 16:47:00.317 [WRN] CHBU: Replacing disk backup for ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0) w/ newer version
2020-08-23 16:47:00.565 [INF] PEER: NodeKey(02fffb0baa1f8a64d92c8b4222278c33a9c16d0f37bba24104c678fd9e4e7f57d6) loading ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0)
2020-08-23 16:47:00.565 [WRN] PEER: ChannelPoint(bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076:0) has status ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator, won't start.
```

### Your environment

* lnd: 0.11.0  (though it was 0.10.0 when this was first opened)
* bitcoind: 0.20.0
* Linux armv7 (raspberry pi)

### Steps to reproduce

No idea.

### Expected behaviour

These broken, unopened channels should disappear and the "limbo" balance be properly allocated.

### Actual behaviour

They just stay there.  It's been about 4 weeks so far.

**Comment by Roasbeef** [comment] 2020-08-25 02:04
> These broken, unopened channels should disappear and the "limbo" balance be properly allocated.


The `abandonchannel` RPC call (only available with the `dev` build tag atm) should allow you to remove these transactions.

**Comment by bcwhite0** [comment] 2020-08-25 02:49
Before I do that, is there anything else I can provide that would help lnd developers?

**Comment by guggero** [comment] 2020-08-25 07:52
A channel funding TX that never makes it to the chain _should_ be removed after a while. I think the current timeout is two weeks. Has it already been that long?

**Comment by bcwhite0** [comment] 2020-08-25 12:02
It was started on July 31st.  Is there something specific I can grep for in the logs?  Perhaps the timer is being reset?

**Comment by guggero** [comment] 2020-08-25 12:35
Ah, looking at the log again, I think what I wrote above doesn't apply because you tried force closing the channel. It is now in the wrong state for the timer to apply. I'm not sure what exactly we should do in such a case in the future. We'll discuss this internally.

In the meantime as @Roasbeef said, you can get rid of this channel with the `abaondonchannel` command.

**Comment by Roasbeef** [comment] 2020-08-25 18:07
One other question: did you enable zero conf funding for autopilot?

**Comment by bcwhite0** [comment] 2020-08-25 21:26
No, I didn't set that option.

There was a problem in the beginning with, if I recall correctly, the relay fee on the underlying bitcoin client that caused transactions to not get sent for some channels.  I fixed that but, I think, these were two of the victims.

It was on 0815 that I first tried to close these channels which were created on 0731.

```
  726  2020-08-15 22:29:47 : lncli closechannel bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076
  729  2020-08-15 22:30:19 : lncli closechannel --force bcd32fbe3f682219db3b7f9015966fa0832ddd3a5c9b1ef2c656278eb6838076
```

My RPi doesn't have golang 1.13 yet so I'll have to wait before creating a "dev" build.

**Comment by bcwhite0** [comment] 2021-02-09 20:58
Just following up on this.  I upgraded to 0.12.0 when it was released but these channels still aren't being cleaned up on their own.  Is that something a future release should address or is it in a state that will absolutely require me getting a "dev" build?

**Comment by wpaulino** [comment] 2021-02-09 21:06
A dev build is still required as of now. A future release will likely handle removing these automatically while in the pending open state, not in the force closed state.

**Comment by bcwhite0** [comment] 2021-04-18 22:12
Things are just getting worse.  I now have one "pending_force_closing_channels" and seven "waiting_close_channels", most (if not all) of which are due to a remote close.  It's been this way for months.

I If try something like:
`lncli closechannel --force 9d3a2...d9fa`

I get
`[lncli] rpc error: code = Unknown desc = channel is already in the process of being force closed`

**Comment by wpaulino** [comment] 2021-04-19 19:03
As previously mentioned, a dev build is still required to remove these channels. You've only commented about two channels, so we can't tell/know if the others are actually valid and it's just a matter of waiting for your CSV delays to expire to sweep the funds. I'd recommend looking up each channel funding transaction to see whether it's confirmed in the chain. If it's not, then it can be safely removed with the `lncli abandonchannel` command.

**Comment by Roasbeef** [comment] 2021-07-10 00:52
A dev build is no longer required as of 0.13.1

**Closed by Roasbeef** 2021-07-10 00:52 UTC

**Comment by bcwhite0** [comment] 2021-08-06 20:19
I installed 0.13.1.  After a couple hours, those two original connections are still there.  Do I have to wait two more weeks?

**Comment by guggero** [comment] 2021-08-08 09:36
If you installed 0.13.1 you can now use the abandonchannel command mentioned above. Make sure you use the "i know what I'm doing flag", see `lncli abandonchannel --help`

**Comment by bcwhite0** [comment] 2021-08-10 19:35
This bug is now titled "Remove unconfirmed but force-closed channels after two weeks as well" and was closed.  I assumed that these old transactions would be automatically removed.  Should the bug be closed?

It's not all good, though.  One of the two channels was successfully abandoned but the other remains ("unable to find closed channel summary").  It's been in this state since 2020-08-15.

```
{
    "total_limbo_balance": "706714",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "03fab7f8655169ea77d9691d4bd359e97782cb6177a6f76383994ed9c262af97a5",
                "channel_point": "6cd62956c52c68f86cbb2347bcfb0172316d6e546bde2b9bcf783e2ac3e20781:1",
                "capacity": "708524",
                "local_balance": "706714",
                "remote_balance": "0",
                "local_chan_reserve_sat": "7085",
                "remote_chan_reserve_sat": "7085",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "706714",
            "commitments": {
                "local_txid": "e6926f61079791f4bc5b5391c1b0d30c7f2e791f9f6291e55409ddfce362a05a",
                "remote_txid": "4eed4b9ca37124b320b9bb2ad6a667cd29b1c77adecb5932b9bd0a6f3823c045",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "1810",
                "remote_commit_fee_sat": "1810",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}

$ lncli abandonchannel --i_know_what_i_am_doing 6cd62956c52c68f86cbb2347bcfb0172316d6e546bde2b9bcf783e2ac3e20781
[lncli] rpc error: code = Unknown desc = unable to find closed channel summary

$ lncli closechannel --force 6cd62956c52c68f86cbb2347bcfb0172316d6e546bde2b9bcf783e2ac3e20781 1
[lncli] rpc error: code = Unknown desc = channel is already in the process of being force closed
```

**Comment by bcwhite0** [comment] 2022-03-15 21:08
Now trying 0.14.2.  Still can't close:

$  lncli abandonchannel --i_know_what_i_am_doing 6cd62956c52c68f86cbb2347bcfb0172316d6e546bde2b9bcf783e2ac3e20781
[lncli] rpc error: code = Unknown desc = unable to find closed channel summary

**Comment by guggero** [comment] 2022-03-16 08:48
You're still missing the ` 1` in the end. If you run the command correctly, do you still get the `channel is already in the process of being force closed` error?
