### ISSUE TITLE
Node Announcement not sent?

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#3428] opened 2019-08-23 18:01 UTC
I changed the external IP of my node, the alias, restarted several times and it seems it did not update those info in the network? 1ml.com did not refresh, and a lightning wallet on my android that has a channel to this node cannot reach it (aparently it's trying to conmect to the old ip).

**Comment by gustavonalle** [comment] 2019-08-26 21:22
Some more info:

Version: ```v0.7.1-beta-64-g6e43974d378ab70583cbae51a907d1d58d19258f```

Config file:

```
[Application Options]
debuglevel=debug
minchansize=1000000
maxpendingchannels=10
externalip=domain.dns.net
alias=myalias
restlisten=0.0.0.0:8081
listen=0.0.0.0:9735
maxlogfiles=0
maxlogfilesize=100
color=#111222

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
#bitcoin.basefee=3000

[Bitcoind]
bitcoind.rpchost=localhost
bitcoind.rpcuser=user
bitcoind.rpcpass=pass
bitcoind.zmqpubrawblock=tcp://127.0.0.1:29000
bitcoind.zmqpubrawtx=tcp://127.0.0.1:29001
```

**Comment by gustavonalle** [comment] 2019-08-27 06:10
More info: closing a channel does not update the node in the network. Still with old alias, color and IP. 
What is the best way to manually force this update?

**Comment by gustavonalle** [comment] 2019-08-28 13:59
@wpaulino Looking at the code, it seems the only way to get my node announced is to open a channel, correct?

**Comment by gustavonalle** [comment] 2019-09-01 18:40
Is ```v0.8.0``` the next version or there will be several 0.7.x. before?

**Comment by wpaulino** [comment] 2019-09-02 20:57
v0.8.0 will be the next one.

**Comment by wpaulino** [comment] 2019-09-03 20:42
Closing as duplicate of #2005.

**Closed by wpaulino** 2019-09-03 20:42 UTC
Labels: bug, gossip, v0.8.0

**Comment by gustavonalle** [comment] 2019-11-29 23:51
Still not working on 0.8.0-beta and 0.8.0-beta1. NodeAnnoucement is simply not sent. Tried opening and closing channels, changing alias, change IP, restarting and nothing...Is there a way to manually force it? C'mon guys, this has been going for a while, just send those darn NodeAnnouncement if ANY node property changes. :smile:

**Comment by The34Goon** [comment] 2020-02-02 12:20
still can't update the node alias to "zombie" to flag dead node from pre watchtower times...
halp

**Comment by cfromknecht** [comment] 2020-02-05 02:19
> still can't update the node alias to "zombie" to flag dead node from pre watchtower times...

if the node is dead, does it still have channels?

**Comment by The34Goon** [comment] 2020-02-05 15:21
neither of both parties can force-close them.
