### ISSUE TITLE
Channels stuck on concurrent mutual close

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lnd#5841] opened 2021-10-07 15:46 UTC
### Background

Tried to cooperatively close 4 channels ACINQ<>Bluewallet yesterday. eclair `close` command can take multiple channels at once, so those 4 close attempts happened simultaneously.

Two of them worked as expected, but for the other two, `eclair` didn't receive the `shutdown` messages from `lnd`. Tried reconnecting multiple times to no avail. The channels are stuck now.

I have the logs from `lnd`, provided by @Overtorment. Here is the grep for one of the stuck channels:

```
2021-10-06 02:30:44.087 [INF] PEER: NodeKey(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f) loading ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1)
2021-10-06 02:30:44.087 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1)
2021-10-06 09:40:13.376 [INF] CHCL: Ideal fee for closure of ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) is: 489 sat
2021-10-06 09:40:13.376 [INF] NANN: Announcing channel(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) disabled [requested]
2021-10-06 09:40:13.390 [INF] CHCL: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1): sending shutdown message
2021-10-06 09:40:13.390 [INF] CHCL: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1): responding to shutdown
2021-10-06 09:40:13.393 [INF] CHCL: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1): proposing fee of 489 sat to close chan
2021-10-06 09:40:15.251 [INF] PEER: NodeKey(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f) loading ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1)
2021-10-06 09:40:15.251 [WRN] PEER: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) has status ChanStatusCoopBroadcasted|ChanStatusRemoteCloseInitiator, won't start.
2021-10-06 09:41:46.351 [INF] PEER: NodeKey(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f) loading ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1)
2021-10-06 09:41:46.351 [WRN] PEER: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) has status ChanStatusCoopBroadcasted|ChanStatusRemoteCloseInitiator, won't start.
2021-10-06 09:48:10.193 [INF] PEER: NodeKey(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f) loading ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1)
2021-10-06 09:48:10.193 [WRN] PEER: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) has status ChanStatusCoopBroadcasted|ChanStatusRemoteCloseInitiator, won't start.
2021-10-06 09:50:17.123 [WRN] CHBU: Replacing disk backup for ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) w/ newer version
2021-10-06 09:50:17.427 [WRN] CHBU: Replacing disk backup for ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) w/ newer version
2021-10-06 13:23:51.845 [INF] PEER: NodeKey(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f) loading ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1)
2021-10-06 13:23:51.846 [WRN] PEER: ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) has status ChanStatusCoopBroadcasted|ChanStatusRemoteCloseInitiator, won't start.
2021-10-06 14:07:51.542 [WRN] CHBU: Replacing disk backup for ChannelPoint(d49253551fd2b8d544027af1a5f8e0112cf0780ac610d5f237c3eab37cc980dc:1) w/ newer version
```

I see the `responding to shutdown`, but I'm positive the `shutdown` didn't make it to `eclair`. In any case, that shutdown should be retransmitted on reconnection, but there seem to be an issue `has status ..., won't start`.

**Comment by Roasbeef** [comment] 2021-10-07 19:22
Will try to reproduce the concurrent close case on our end as well, should be a simple set up. Would be curious to see what happend in the logs in that 2 minute interval (after we send shutdown but before the reconnect).

**Comment by Bobz-zg** [comment] 2021-11-21 11:41
I have a channel that is closing since 5. Oct 2021.
https://amboss.space/node/0380003e5f9c71f14aed84bfbda9549ce04b57a813de9f9471c05b94d561c26539

Not sure how would I troubleshoot that, any info would help?

**Comment by guggero** [comment] 2021-11-22 08:18
> If a coop close is attempted but doesn't go through (because the peer fails to respond in time) then a channel must be force closed.

**Comment by guggero** [comment] 2022-03-28 11:43
I can see on chain that this channel was closed a while ago.
Closing as the underlying issue is tracked under https://github.com/lightningnetwork/lnd/issues/5690.

**Closed by guggero** 2022-03-28 11:43 UTC
Labels: p2p, channel closing, channel management, compatibility
