### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by HotCrypt** [lightningnetwork/lnd#7184] opened 2022-11-20 16:05 UTC
Hi, I am running a node LND 15.4 on a Raspberry 4b 8GB HDD 2TB. 
I believe everything works fine but while looking at the log file I noticed this error:

```
2022-11-19 19:47:09.501 [INF] CRTR: Processed channels=1 updates=115 nodes=4 in last 59.999796477s
2022-11-19 19:47:25.363 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
2022-11-19 19:47:25.438 [INF] WTCL: (anchor) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
2022-11-19 19:48:09.502 [INF] CRTR: Processed channels=0 updates=119 nodes=11 in last 1m0.000624001s
2022-11-19 19:48:25.363 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
2022-11-19 19:48:25.438 [INF] WTCL: (anchor) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
2022-11-19 19:48:25.678 [INF] DISC: Broadcasting 169 new announcements in 17 sub batches
2022-11-19 19:48:29.079 [ERR] DISC: unable to validate channel update announcement for short_chan_id=(lnwire.ShortChannelID) 759405:2134:1
: invalid max htlc for channel update (*lnwire.ChannelUpdate)(0x4006484a50)({
 Signature: (lnwire.Sig) (len=64 cap=64) {
  00000000  24 d6 96 f4 46 e7 02 03  b8 59 a2 f0 3f 9f 39 9f  |$...F....Y..?.9.|
  00000010  fa 57 e1 3f 14 9a ad 50  19 e6 bb 91 f8 1e 72 b3  |.W.?...P......r.|
  00000020  15 1b 60 59 6b 0a d5 36  66 03 f4 28 9b f0 61 f8  |..`Yk..6f..(..a.|
  00000030  b1 ad 93 29 61 bf df 8f  94 63 8b 47 ab 6b f4 c7  |...)a....c.G.k..|
 },
 ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
 ShortChannelID: (lnwire.ShortChannelID) 759405:2134:1,
 Timestamp: (uint32) 1668883355,
 MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001,
 ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000000,
 TimeLockDelta: (uint16) 34,
 HtlcMinimumMsat: (lnwire.MilliSatoshi) 1 mSAT,
 BaseFee: (uint32) 0,
 FeeRate: (uint32) 833,
 HtlcMaximumMsat: (lnwire.MilliSatoshi) 0 mSAT,
 ExtraOpaqueData: (lnwire.ExtraOpaqueData) {
 }
})

2022-11-19 19:49:09.502 [INF] CRTR: Processed channels=0 updates=117 nodes=9 in last 59.99954211s
2022-11-19 19:49:25.363 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
2022-11-19 19:49:25.437 [INF] WTCL: (anchor) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
2022-11-19 19:49:55.679 [INF] DISC: Broadcasting 233 new announcements in 18 sub batches
2022-11-19 19:50:09.506 [INF] CRTR: Processed channels=1 updates=148 nodes=6 in last 1m0.003594617s
```
Could someone please explain to me?
Thank you. 
Kind regards,

**Comment by sputn1ck** [comment] 2022-11-20 16:10
I don't think this is not a bug or unintended behaviour. Your processing a channel update announcement with an invalid configuration. This has no implications for your own node.

Moving this to a discussion.

**Comment by HotCrypt** [comment] 2022-11-20 17:51
Thank you my friend 👍

**Closed** 2022-11-21 01:47 UTC
Labels: bug, needs triage
