### ISSUE TITLE
synced_to_chain turns false and never recovers

### ISSUE THREAD

**Issue by TechMiX** [lightningnetwork/lnd#5563] opened 2021-07-23 20:32 UTC
### Background

I am trying to setup an `lnd` node. I already have a `bitcoind` fully synced and ready.

I run `lnd` and it successfully connects to `bitcoind` and both `synced_to_chain` and `synced_to_graph` turn to true after a while. The moment a new block is found `block_height` is updated (which indicates ZMQ connection is alive and working), but `synced_to_chain` turns to false and never becomes true again unless I restart `lnd`.

I thought this was because I didn't have any active channels, so I opened a channel but it didn't change the result and `synced_to_chain` still turns to false and never recovers, no matter there are active channels or not.

I also tried these things both behind Tor and with an external IP that didn't make any changes either.

### Environment

* `lnd v0.13.1-beta`, `lnd v0.13.1-beta.rc2`, `lnd v0.12.1-beta`, 49f1169d7cb7d2fb1fa1b9905dd4aaf3717b6d6c
* `Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux`
* `bitcoind-0.21.1`
* lnd.conf:
```
[Application Options]

rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:10010

[Bitcoin]

bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.dir=~/data/bitcoin
bitcoind.rpchost=localhost:8030
bitcoind.rpcuser=xxxxxxxx
bitcoind.rpcpass=xxxxxxxxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:38331
bitcoind.zmqpubrawtx=tcp://127.0.0.1:38330

[wtclient]
wtclient.active=true
```
* bitcoin.conf:
```
daemon=1
server=1
mainnet=1
txindex=1
disablewallet=1

zmqpubhashtx=tcp://127.0.0.1:38330
zmqpubhashblock=tcp://127.0.0.1:38331

[main]
rpcallowip=127.0.0.1
rpcauth=xxxxx
rpcport=8030
```

### Expected behaviour

After a block is found, `synced_to_chain` should eventually become true after a while.

### Actual behaviour

After a block is found, `synced_to_chain` turns false and never becomes true.

**Comment by Roasbeef** [comment] 2021-07-23 20:34
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/5132

**Closed by Roasbeef** 2021-07-23 20:34 UTC

**Comment by wpaulino** [comment] 2021-07-23 20:44
Your `bitcoin.conf` is not configured properly:

```
zmqpubhashtx=tcp://127.0.0.1:38330
zmqpubhashblock=tcp://127.0.0.1:38331
```

It should instead be:

```
zmqpubrawtx=tcp://127.0.0.1:38330
zmqpubrawblock=tcp://127.0.0.1:38331
```

**Comment by TechMiX** [comment] 2021-07-23 21:03
Bingo! That was exactly my problem. It's fixed now. Thank you very much @wpaulino ! but I hope I don't get into the duplicated problem mentioned by @Roasbeef
