### ISSUE TITLE
Errors with RTL and channel opening

### ISSUE THREAD

**Issue by HodlingOnward** [lightningnetwork/lnd#5599] opened 2021-08-02 21:37 UTC
### Background

I am attempting to open a channel with my entire on-chain balance. The on-chain balance is the result of a cooperative channel close a counter party initiated. The transaction confirmed a few hundred blocks ago. I am using Ride The Lightning (and was instructed by their team to log the issue here).

### Your environment

* Running MyNode v 0.2.38 with LND v 0.13.0 and Ride The Lightning v 0.11.0
* Bitcoin Core 0.21.1

### Steps to reproduce

Here's the log from trying to open the channel:
timestamp myNode lnd: 2021-08-02 [ERR] RPCS: [/lnrpc.Lightning/OpenChannelSync]: reserved wallet balance invalidated
timestamp myNode lnd: 2021-08-02 [ERR] RPCS: unable to open channel to NodeKey("redacted"): reserved wallet balance invalidated
timestamp myNode lnd: 2021-08-02 [WRN] CHFD: Unable to find funding output for shim intent: unable to create witness script, no funding keys

### Expected behaviour

Expect to open a channel to a peered node (a channel already exists that the peer opened to my node) via RTL on MyNode.

### Actual behaviour

Receive error "reserved wallet balance invalidated" - changing the amount for opening the channel does not produce different results.

**Comment by guggero** [comment] 2021-08-03 08:21
This is expected. With the new anchor output channel format you need to keep a reserve in your wallet for when a channel needs to be force closed. The error you get isn't very helpful but this has been fixed in a recently merged PR: https://github.com/lightningnetwork/lnd/pull/5577

So you need 10k sats per channel (or a maximum of 100k sats in total) as a reserve.

**Comment by HodlingOnward** [comment] 2021-08-03 09:46
> 
> 
> This is expected. With the new anchor output channel format you need to keep a reserve in your wallet for when a channel needs to be force closed. The error you get isn't very helpful but this has been fixed in a recently merged PR: #5577
> 
> So you need 10k sats per channel (or a maximum of 100k sats in total) as a reserve.

Interesting, how recent was this change? I'm not a huge fan of this, depending on what happens with the BTC price that could quickly become a very large amount of capital tied up with no utility for the average person. Mind pointing me to the relevant discussions on this? Would like to read what people thought about it and what the technical reasons are. Thanks!

**Comment by guggero** [comment] 2021-08-03 10:19
Anchor channels were turned on by default in `lnd v0.13.0` and can be disabled. See https://bitcoinops.org/en/topics/anchor-outputs/ for all relevant information.

Going to close this for now as this is "working as intended".

**Closed by guggero** 2021-08-03 10:19 UTC
