### ISSUE TITLE
Document complete Neutrino node instructions

### ISSUE THREAD

**Issue by sako0938** [lightningnetwork/lnd#3868] opened 2019-12-22 00:14 UTC
### Background

When starting up a Neutrino node, LND must be compiled with the experimental flag and run with assumevalid=true, or else the graph will not sync. This question has been asked in the slack many, many times, including myself, unless it is planning on changing in the future, why not document how to do it?

**Comment by molxyz** [comment] 2019-12-23 20:14
@sako0938  I think because Neutrino is still under testing and not ready for Mainnet.

**Comment by sako0938** [comment] 2019-12-24 15:17
@molxyz As of 0.8.0 Neutrino was "Supported" for mainnet
```Mainnet Neutrino

Neutrino has steadily been improved, and this release contains several fixes and optimizations that make it stable enough for mainnet support. Keep in mind that it is still early, and stay craeful.```

**Comment by sako0938** [comment] 2019-12-24 15:20
All Im saying is a release says Neutrino Mainnet is here, but there are incomplete docs about it, so it wastes LND devs time. I definitely feel "in the know" since I've been around to hear it explained like 10 times, but is that really a good use of time?

**Comment by molxyz** [comment] 2019-12-25 05:02
@sako0938 You can always submit a PR!  As for me, i have no problem keeping a note of my own document.

**Comment by sako0938** [comment] 2019-12-27 03:57
Sorry if it seems I am asking for work, and not putting work in. Its great you have your notes, but they should be fed back in to the process. I plan on using the issue to document what is needed to start a node with Neutrino backend. I will eventually make a PR if it seems stable and no one else gets there before me.

How to compile the node with the experimental flag.
Look here: #3598 

How to start the node:
nohup lnd --routing.assumechanvalid=1 > /dev/null 2> /dev/null &

**Comment by Roasbeef** [comment] 2019-12-27 16:34
Duplicate of #3630.

**Closed by Roasbeef** 2019-12-27 16:34 UTC
