### ISSUE TITLE
fwdhistory and feereport increases on restart of lnd

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1175] opened 2018-05-03 11:58 UTC
stop lnd
start lnd
check fwdinghistory

duplicate records are added again, but with a fresh timestamp
also feereport is increased

diff -y between two sections from one fwdinghistory output, extremely similar other than the timestamp:

```
        {                                                               {
            "timestamp": "1525243347",                        |             "timestamp": "1525264176",
            "chan_id_in": "568543169230667776",                             "chan_id_in": "568543169230667776",
            "chan_id_out": "571651488594722817",                            "chan_id_out": "571651488594722817",
            "amt_in": "152",                                                "amt_in": "152",
            "amt_out": "151",                                               "amt_out": "151",
            "fee": "1"                                                      "fee": "1"
        },                                                              },
        {                                                               {
            "timestamp": "1525243347",                        |             "timestamp": "1525264176",
            "chan_id_in": "570252909732560896",                             "chan_id_in": "570252909732560896",
            "chan_id_out": "568543169230667776",                            "chan_id_out": "568543169230667776",
            "amt_in": "1001",                                               "amt_in": "1001",
            "amt_out": "1000",                                              "amt_out": "1000",
            "fee": "1"                                                      "fee": "1"
        },                                                              },
        {                                                               {
            "timestamp": "1525243347",                        |             "timestamp": "1525264176",
            "chan_id_in": "571009373681418240",                             "chan_id_in": "571009373681418240",
            "chan_id_out": "570641037292929025",                            "chan_id_out": "570641037292929025",
            "amt_in": "151",                                                "amt_in": "151",
            "amt_out": "150",                                               "amt_out": "150",
            "fee": "1"                                                      "fee": "1"
        },                                                              },
        {                                                               {
            "timestamp": "1525243347",                        |             "timestamp": "1525264176",
            "chan_id_in": "571009373681418240",                             "chan_id_in": "571009373681418240",
            "chan_id_out": "570641037292929025",                            "chan_id_out": "570641037292929025",
            "amt_in": "151",                                                "amt_in": "151",
            "amt_out": "150",                                               "amt_out": "150",
            "fee": "1"                                                      "fee": "1"
        },                                                              },
        {                                                               {
            "timestamp": "1525243347",                        |             "timestamp": "1525264176",
            "chan_id_in": "571009373681418240",                             "chan_id_in": "571009373681418240",
            "chan_id_out": "570641037292929025",                            "chan_id_out": "570641037292929025",
            "amt_in": "22",                                                 "amt_in": "22",
            "amt_out": "21",                                                "amt_out": "21",
            "fee": "1"                                                      "fee": "1"
        },                                                              },
        {                                                               {
            "timestamp": "1525243347",                        |             "timestamp": "1525264176",
            "chan_id_in": "571009373681418240",                             "chan_id_in": "571009373681418240",
            "chan_id_out": "570641037292929025",                            "chan_id_out": "570641037292929025",
            "amt_in": "151",                                                "amt_in": "151",
            "amt_out": "150",                                               "amt_out": "150",
            "fee": "1"                                                      "fee": "1"
        },                                                    |         }
```

### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by robtex** [comment] 2018-05-05 13:56
good news, two days ago it came in batches of 62 duplicate records, then down to 27, and today they are only 14.

$ lncli fwdinghistory | grep 1525451699 -c
27
lncli fwdinghistory | grep 1525474095 -c
14

**Comment by robtex** [comment] 2018-06-02 10:02
still face this issue fyi. 26 equal timestamps on restart.
the 14 i saw a month ago was probably missing some because they differed by a second or so

**Comment by vegardengen** [comment] 2018-08-10 05:02
I now have an instance of this, pretty isolated. I have two forwardet transactions, or possibly the same twice, of 630 satoshi, that is added to the fwdinghistory on every restart.

The first one was at 2018-08-08 20:58:12. There were *no* 630 satoshi transactions being listed in fwdinghistory before then. This is during the first restart, durinc HSWC startup.

It may or may not be these):

2018-08-08 20:58:11.924 [INF] SRVR: Adding preimage=225ef3fdb36d2440fcf23c4363e29e0141cb3bc026ec2386047942eb5e72b9db to witness cache

2018-08-08 20:58:11.985 [INF] SRVR: Adding preimage=225ef3fdb36d2440fcf23c4363e29e0141cb3bc026ec2386047942eb5e72b9db to witness cache

It may or may not originate from these, earlier in the day. The amount is correct....

2018-08-08 12:43:08.166 [ERR] HSWC: ChannelLink(525794:1537:0) unhandled error w
hile forwarding htlc packet over htlcswitch: incoming HTLC(92a8080c401e8df359e33
ece2bbfd3da08b99076e9b8e79ed898bcbfa496bab8) violated target outgoing link (id=5
32170:576:1) policy: FeeInsufficient(htlc_amt==630001 mSAT, update=(lnwire.Chann

2018-08-08 12:43:10.358 [ERR] HSWC: incoming HTLC(92a8080c401e8df359e33ece2bbfd3
da08b99076e9b8e79ed898bcbfa496bab8) violated target outgoing link (id=532170:576
:1) policy: FeeInsufficient(htlc_amt==630001 mSAT, update=(lnwire.ChannelUpdate)

Adding the relevant logs, third restart is a full debug restart around 2018-08-09 18:20 

[lnd.log.1425.gz](https://github.com/lightningnetwork/lnd/files/2276631/lnd.log.1425.gz)
[lnd.log.1426.gz](https://github.com/lightningnetwork/lnd/files/2276632/lnd.log.1426.gz)

**Comment by carlaKC** [comment] 2020-08-14 09:14
I can't reproduce this error with the latest version of lnd. Since this is an old issue, there is a chance that this problem has been resolved in subsequent versions. 

@vegardengen @robtex what version of lnd were you running when you encountered this issue? I'd like to try reproduce on that version so that we can determine whether this problem still exists.

**Comment by vegardengen** [comment] 2020-08-20 17:47
I was running 0.4.2, it seems. I have not seen that issue since.

**Comment by carlaKC** [comment] 2020-08-20 19:30
Going to close this for now, because I cannot reproduce in more recent lnd versions. Feel free to reopen if you run into this again!

**Closed by carlaKC** 2020-08-20 19:30 UTC
Labels: P4, beginner, bug, fees, rpc, v0.12
