### ISSUE TITLE
chantools triggerforceclose fails to dial tor onion addresses

### ISSUE THREAD

**Issue by tmaiorca** [lightningnetwork/lnd#7595] opened 2023-04-11 23:17 UTC
I have a channel with a remote host via a Tor onion URI that is in a month-long `waiting_close` state. The [chantools](https://github.com/guggero/chantools/blob/master/doc/chantools_triggerforceclose.md) tool that was recently developed seems to work for other node operators, but not with the channel I have open when I issue the `triggerforceclose` command. 

Does chantools only work with clearnet IPv4 addresses? I tried to also throw quotes around  the host portion of the `--peer` flag, but that returns the same error. 

-lnd version 0.15.4-beta
-raspberry pi 4 (raspiblitz)
-chantools 10.7

![error](https://user-images.githubusercontent.com/46833258/231307538-b81d218b-4688-4f74-85e3-0cfc44e44f54.png)

Originally posted by @guggero in https://github.com/lightningnetwork/lnd/issues/7301#issuecomment-1445121739_

`chantools triggerforceclose --peer 039910a225afe022698e41afdc69ef7b23832cb03baf632476b42d1b7ccc596fcf@2zqc23kimjn63oec4j6dlmlii6ghiisk6cthshlbvcaiugbsnwwikzid.onion:9735 --channel_point c2c5e72c007f87325e633233d4c0d27a29dd90a9dac6755333f4d0504383b42a:0`

**Comment by guggero** [comment] 2023-04-12 07:20
Did you lose the channel state and needed to recover from SCB? Otherwise you can just run `lncli closechannel --force`.
And are you sure your peer is a CLN node? This will work with CLN only and only with the affected version.

Anyway, this is a duplicate of https://github.com/guggero/chantools/issues/60.

Also, there's also the alternative described here: https://github.com/lightningnetwork/lnd/issues/7301#issuecomment-1443517382.

**Closed by guggero** 2023-04-12 07:20 UTC

**Comment by scissorstail** [comment] 2023-10-23 12:48
Same here. My database was corrupted due to a power outage, and I attempted to recover channels using SCB, but there were 3 channels remaining. I was able to successfully recover one of them using the 'triggerforceclose' command. However, the remaining 2 channels both only have tor connections open, so it seems that this method is not working. Is there anything else I can do? thanks.

**Comment by guggero** [comment] 2023-10-23 12:55
Are the nodes still online? Can you connect to them on the node you used to restore the channels using the `channel.backup` file?

**Comment by scissorstail** [comment] 2023-10-23 13:07
**Yes**, and to provide more details, since the database was completely damaged, I backed up the data directory with a different name and completely restarted the node. After that, I attempted to restore using an SCB backup made up of hex strings.

Additionally, following the Channel recovery scenario, I copied the recreated channel.db and went through various processes, but only the message to execute 'rescanblockchain 48xxxx on Bitcoin Core' was displayed. Even after running that command, nothing changed.

**Comment by guggero** [comment] 2023-10-23 13:21
If you restored the SCB backup, and the peers are online, they should initiate the recovery. Can you run `lncli listpeers` to make sure the peers are connected? If yes, check the logs for those two channels.

**Comment by scissorstail** [comment] 2023-10-23 13:45
I think I have found something. I have erased some information because the information presented here is not about my node.

Node 1 is connected.
```
{
    "pub_key": "pub_key",
    "address": "ip4:port",
    "bytes_sent": "449875",
    "bytes_recv": "774697",
    "sat_sent": "0",
    "sat_recv": "0",
    "inbound": true,
    "ping_time": "758952",
    "sync_type": "ACTIVE_SYNC",
    "features": {
        "1": {
            "name": "data-loss-protect",
            "is_required": false,
            "is_known": true
        },
        "5": {
            "name": "upfront-shutdown-script",
            "is_required": false,
            "is_known": true
        },
        "7": {
            "name": "gossip-queries",
            "is_required": false,
            "is_known": true
        },
        "8": {
            "name": "tlv-onion",
            "is_required": true,
            "is_known": true
        },
        "11": {
            "name": "unknown",
            "is_required": false,
            "is_known": false
        },
        "13": {
            "name": "static-remote-key",
            "is_required": false,
            "is_known": true
        },
        "14": {
            "name": "payment-addr",
            "is_required": true,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        },
        "25": {
            "name": "unknown",
            "is_required": false,
            "is_known": false
        },
        "27": {
            "name": "shutdown-any-segwit",
            "is_required": false,
            "is_known": true
        },
        "39": {
            "name": "unknown",
            "is_required": false,
            "is_known": false
        },
        "45": {
            "name": "explicit-commitment-type",
            "is_required": false,
            "is_known": true
        },
        "47": {
            "name": "scid-alias",
            "is_required": false,
            "is_known": true
        },
        "51": {
            "name": "zero-conf",
            "is_required": false,
            "is_known": true
        }
    },
    "errors": [
    ],
    "flap_count": 28,
    "last_flap_ns": "1698065457939314245",
    "last_ping_payload": null
}
```

Node 2 is not connected. Moreover, as soon as I attempt to connect, it immediately disconnects.
I found some logs...
```
2023-10-23 13:35:05.228 [INF] PEER: Peer(pubkey): Negotiated chan series queries
2023-10-23 13:35:05.228 [INF] DISC: Creating new GossipSyncer for peer=pubkey
2023-10-23 13:35:05.228 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(txid:1)
2023-10-23 13:35:05.228 [INF] NTFN: New block epoch subscription
2023-10-23 13:35:05.228 [INF] HSWC: ChannelLink(txid:1): HTLC manager started, bandwidth=0 mSAT
2023-10-23 13:35:05.228 [INF] HSWC: ChannelLink(txid:1): attempting to re-synchronize
2023-10-23 13:35:06.248 [INF] PEER: Peer(pubkey): unable to read message from peer: EOF
2023-10-23 13:35:06.248 [INF] DISC: GossipSyncer(pubkey): applying new update horizon: start=2106-02-07 06:28:15 +0000 UTC, end=2242-03-16 12:56:30 +0000 UTC, backlog_size=0
2023-10-23 13:35:06.248 [INF] PEER: Peer(pubkey): disconnecting pubkey@ip4:port, reason: read handler closed
2023-10-23 13:35:06.248 [INF] HSWC: ChannelLink(txid:1): received re-establishment message from remote side
2023-10-23 13:35:06.248 [ERR] LNWL: ChannelPoint(txid:1): sync failed with local data loss: remote believes our tail height is 690224, while we have 0!
2023-10-23 13:35:06.248 [WRN] LNWL: ChannelPoint(txid:1): detected restored triggering DLP
2023-10-23 13:35:06.248 [INF] NTFN: Cancelling epoch notification, epoch_id=23
2023-10-23 13:35:06.248 [WRN] HSWC: ChannelLink(txid:1): error when syncing channel states: ChannelPoint(txid:1) with CommitPoint(hash) had possible local commitment state data loss
2023-10-23 13:35:06.259 [ERR] HSWC: ChannelLink(txid:1): failing link: unable to synchronize channel states: ChannelPoint(txid:1) with CommitPoint(hash) had possible local commitment state data loss with error: unable to resume channel, recovery required
2023-10-23 13:35:06.259 [INF] HSWC: ChannelLink(txid:1): exited
2023-10-23 13:35:06.448 [INF] DISC: Removing GossipSyncer for peer=pubkey
2023-10-23 13:35:06.448 [INF] HSWC: ChannelLink(txid:1): stopping

```

**Comment by guggero** [comment] 2023-10-23 13:48
That looks good for node 1, it means the force close should be happening. Maybe things just take a long time with the current mempool? What's the output of `lncli pendingchannels`?

If you can't connect to node 2 then you won't be able to recover the channel normally. If you find a way to contact them, I would ask them to force close manually from their end. If not, sounds to me like www.node-recovery.com is your only option.

**Comment by scissorstail** [comment] 2023-10-23 13:53
It is output of `lncli pendingchannels`

```
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "pubkey(Node 1)",
                "channel_point": "hash:0",
                "capacity": "5000000",
                "local_balance": "0",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "STATIC_REMOTE_KEY",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusLocalDataLoss|ChanStatusRestored",
                "private": true
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "",
                "remote_txid": "",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "0",
                "remote_commit_fee_sat": "0",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        },
        {
            "channel": {
                "remote_node_pub": "pubkey(Node 2)",
                "channel_point": "hash:1",
                "capacity": "996491",
                "local_balance": "0",
                "remote_balance": "0",
                "local_chan_reserve_sat": "0",
                "remote_chan_reserve_sat": "0",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "STATIC_REMOTE_KEY",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusLocalDataLoss|ChanStatusRestored",
                "private": true
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "",
                "remote_txid": "",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "0",
                "remote_commit_fee_sat": "0",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
}
```
The channel on Node 1 has not closed for over 4 weeks, so it probably isn't that.

**Comment by guggero** [comment] 2023-10-23 13:57
Can you check if there are any transactions in the mempool that spend the transaction shown in `channel_point` (just the part before the `:X`).

**Comment by scissorstail** [comment] 2023-10-23 14:10
![1](https://github.com/lightningnetwork/lnd/assets/93466598/dafa5fe5-eb6d-49c4-9fea-ba9bc95d7e73)

I checked the mempool.io, but it seems unlikely.

**Comment by guggero** [comment] 2023-10-23 14:15
Can you DM me the full output of `lncli pendingchannels` please? Debugging by obfuscated info or screenshots is really hard... Same username on Slack or Keybase, or you should also be able to find me on Telegram (if you search, the username there has some additional stuff).

**Comment by scissorstail** [comment] 2023-10-23 14:25
Thanks. Sent info to Keybase.

**Comment by tmaiorca** [comment] 2023-11-01 23:02
@scissorstail - if you review the [chantools page](https://github.com/lightninglabs/chantools) and find yourself needing to perform a zombie recovery, I wrote a [quick tutorial](https://tmaiorca.github.io/posts/Bitcoin-Zombie-Channels/) on how to do so (@guggero, thanks for the inspiration)
