### ISSUE TITLE
Accounting for onchain fees in listchaintxns for force-closed channels and sweeps

### ISSUE THREAD

**Issue by bitromortac** [lightningnetwork/lnd#3708] opened 2019-11-11 17:15 UTC
I'm trying to do some accounting for onchain fees for forced channel closures.

Looking for force closures:
`lncli closedchannels | grep -B9 FORCE_CLOSE`
The funding transaction is the first part of the `CHANNEL_POINT` and also the closing transaction id can be seen here (`CLOSING_TX_HASH`).

I pick up a channel_point for which a transaction entry exists in
`lncli listchaintxns | grep -A6 $CHANNEL_POINT`. This means that I opened up the channel and thus have to pay for onchain fees (which is correctly reflected).

However, by looking up
`lncli listchaintxns | grep -A6 $CLOSING_TX_HASH`,
fees are displayed to be zero, which shouldn't be the case if I'm not mistaken (in that case it was a local force closing). Also the following sweep transaction shows zero fees.

**Comment by wpaulino** [comment] 2019-11-11 18:54
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/2936.

**Closed by wpaulino** 2019-11-11 18:54 UTC
