### ISSUE TITLE
Unable to remove wathctower

### ISSUE THREAD

**Issue by flexo82** [lightningnetwork/lnd#6315] opened 2022-03-08 09:14 UTC
### Background

A watchtower was added at some point and now has connection issues. I am unable to remove the watchtower.

```
 "towers": [
        {
            "pubkey": "0301135932e89600b3582513c648d46213dc425c7666e3380faa7dbb51f7e6a3d6",
            "addresses": [
                "44.237.235.163:9911"
            ],
            "active_session_candidate": true,
            "num_sessions": 21,
            "sessions": [
            ]
        },
```

```
$ lncli wtclient remove 0301135932e89600b3582513c648d46213dc425c7666e3380faa7dbb51f7e6a3d6
[lncli] rpc error: code = Unknown desc = tower has unacked updates
```

### Your environment

* version of `lnd`
`"version": "0.14.2-beta commit=v0.14.2-beta"`
* which operating system (`uname -a` on *Nix)
`Linux lightning-pi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
`Bitcoin Core version v22.0.0`
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

I had hoped I could remove the broken tower so my logs would not get flooded with errors

### Actual behaviour

Watchtower is not removed

**Comment by lucasdcf** [comment] 2022-03-08 13:50
Closing as a duplicate of: https://github.com/lightningnetwork/lnd/issues/4420

**Closed by lucasdcf** 2022-03-08 13:50 UTC
