### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by chlarsen** [lightningnetwork/lnd#721] opened 2018-02-03 08:58 UTC
Dear All,
Thanks a lot for all your hard work! 
I followed the installation tutorial, running the entire show from inside a FreeBSD jail.
When it comes to the 
````
go install . ./cmd/...
````
step, I get:
````
unexpected directory layout:
	import path: github.com/boltdb/bolt
	root: /root/go/src
	dir: /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt
	expand root: /root/go/src
	expand dir: /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt
	separator: /
````
I am probably missing something silly. Any thoughts? All the steps prior to the one mentioned work nicely. Other GoLang apps work well.
Thank you so much for your help!
Chris

**Comment by MeshCollider** [comment] 2018-02-03 11:49
Duplicate of https://github.com/lightningnetwork/lnd/issues/717

**Closed by MeshCollider** 2018-02-03 11:49 UTC

**Comment by chlarsen** [comment] 2018-02-03 12:12
Incorrect, I am afraid. Here is my environment:
````
GOPATH=/usr/local/go_packages
GOROOT=/usr/local/go
````
The error presents with well-defined, distinct GOROOT and GOPATH environment variables.
Also, it seems to me that the stanza
````
go install . ./cmd/...
````
looks a bit weird. Should it not sport two, instead of three, "."'s?
Chris

**Comment by Roasbeef** [comment] 2018-02-03 20:09
From the error info listed, it's looking into `/usr/local/go` as if that were your `GOPATH`. If you modify your gopath to not have a shared prefix as your goroot, does the problem still persist? 

We don't do anything fancy as far as packaging or anything, `glide` is pretty standard these days amongst Go projects (tho `dep` may replace it soon).

**Comment by chlarsen** [comment] 2018-02-04 09:54
Good morning from Lilongwe,
I changed GOPATH to /root/go, and still get:
````
go install . ./cmd/...
unexpected directory layout:
	import path: github.com/boltdb/bolt
	root: /root/go/src
	dir: /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt
	expand root: /root/go/src
	expand dir: /root/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt
	separator: /
````
FreeBSD runs csh as default shell. Could this be an issue?
Thank you so much for your help!
Chris

**Comment by chlarsen** [comment] 2018-02-04 10:30
To answer my question: No, it is not a shell issue.

**Comment by halseth** [comment] 2018-02-05 23:04
Try wiping the go directories, might be stuff leftover from when the paths overlapped.

Similar issue: https://github.com/alecthomas/gometalinter/issues/242
