### ISSUE TITLE
Channel does not re-connect

### ISSUE THREAD

**Issue by rationalflaneur** [lightningnetwork/lnd#2919] opened 2019-04-09 15:13 UTC
### Background

I have a channel that never seems to become active. 

```
{
  "active": false,
  "remote_pubkey": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
  "channel_point": "8c00e0ae75695604213779a7ef3af4b618ad4f00e0516d840b4d0d04d4562644:1",
  "chan_id": "626181767819689985",
  "capacity": "100000",
  "local_balance": "96699",
  "remote_balance": "0",
  "commit_fee": "3301",
  "commit_weight": "600",
  "fee_per_kw": "4560",
  "unsettled_balance": "0",
  "total_satoshis_sent": "0",
  "total_satoshis_received": "0",
  "num_updates": "0",
  "pending_htlcs": [
  ],
  "csv_delay": 144,
  "private": false,
  "initiator": true,
  "chan_status_flags": "ChanStatusDefault"
}
```

I can `ping`, `telnet` and `traceroute` to the node IP, so network connectivity doesn't seem to be a problem. `lncli queryroute <pubkey> --amt 500` shows a route to the node with an additional hop before.

I see some suspicious events in the log:

```
Apr 08 19:17:04 asgardroid lnd[19279]: 2019-04-08 19:17:04.486 [INF] SRVR: Disconnecting from 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735
Apr 08 19:17:04 asgardroid lnd[19279]: 2019-04-08 19:17:04.486 [INF] PEER: Disconnecting 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735, reason: server: disconnecting peer 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735
Apr 08 19:17:04 asgardroid lnd[19279]: 2019-04-08 19:17:04.486 [INF] PEER: unable to read message from 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735: read tcp 192.168.0.20:51962->138.68.14.104:9735: use of closed network connection
Apr 08 19:17:04 asgardroid lnd[19279]: 2019-04-08 19:17:04.586 [INF] DISC: Removing gossipSyncer for peer=03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d
Apr 08 19:42:42 asgardroid lnd[14005]: 2019-04-08 19:42:42.326 [INF] SRVR: Established connection to: 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735
```

`lncli connect <pubkey@port>` gives me: `[lncli] rpc error: code = Unknown desc = already connected to peer: 03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d@138.68.14.104:9735`

### Your environment

* version of `lnd` `lnd version 0.6.0-beta commit=v0.6-beta-rc3-4-g78ffb5bb5f6a12a976405c2d0e23de608f471f8b`
* which operating system (`uname -a` on *Nix) `Linux asgardroid 4.14.55-133 #1 SMP PREEMPT Sat Jul 14 18:18:06 UTC 2018 armv7l armv7l armv7l GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend `Bitcoin Core Daemon version v0.17.1`

### Steps to reproduce

Run `lnd`. Check channel states with `lncli listchannels`

### Expected behaviour

The channel is shown as active in the channel list.

### Actual behaviour

The channel is shown as inactive in the channel list.

**Comment by wpaulino** [comment] 2019-04-09 19:08
Closing as duplicate of #2632. This will be addressed in the upcoming v0.6 release.

**Closed by wpaulino** 2019-04-09 19:08 UTC
