### ISSUE TITLE
temporary_channel_failure messages wrong

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1599] opened 2018-07-21 14:16 UTC
"unable to route payment" messages usually looks like this:
```
unable to route payment to destination: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc426c713b0)({
 Signature: (lnwire.Sig) (len=64 cap=64) {
  00000000  34 16 83 fb aa 67 a7 05  13 f1 85 a8 e5 8a 88 5c  |4....g.........\|
  00000010  38 f6 51 38 20 af 78 51  a3 c2 57 94 c7 56 20 46  |8.Q8 .xQ..W..V F|
  00000020  5b c0 07 2d a7 5c 3e b2  bc 7a ce d1 c7 06 0c c5  |[..-.\>..z......|
  00000030  6a 16 59 ff 59 2e 51 23  14 cd 12 c3 a6 3b ff cd  |j.Y.Y.Q#.....;..|
 },
 ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
 ShortChannelID: (lnwire.ShortChannelID) 524753:1823:0,
 Timestamp: (uint32) 1532149421,
 Flags: (lnwire.ChanUpdateFlag) 0,
 TimeLockDelta: (uint16) 144,
 HtlcMinimumMsat: (lnwire.MilliSatoshi) 0 mSAT,
 BaseFee: (uint32) 1000,
 FeeRate: (uint32) 1
})
)
```
with correct chainhash and otherwise sane data .

but sometimes they look like this. 
it seems the entire message is skewed by 2 bytes, and the first two bytes look like a length specification and are always 01 02
```
unable to route payment to destination: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc43701cab0)({
 Signature: (lnwire.Sig) (len=64 cap=64) {
  00000000  01 02 9f 8a 5b a1 4f 54  e8 3b 79 4e 18 12 03 a8  |....[.OT.;yN....|
  00000010  e5 ab fc 97 39 6f 8d bf  f5 b3 0f 99 2d b0 03 a6  |....9o......-...|
  00000020  34 f9 03 2f 7c 25 71 20  f6 12 cf 39 1f 4a 0c f3  |4../|%q ...9.J..|
  00000030  7a 28 e7 85 b2 b5 0c 19  24 5a 85 77 45 f3 3d 32  |z(......$Z.wE.=2|
 },
 ChainHash: (chainhash.Hash) (len=32 cap=32) 00000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26faadb,
 ShortChannelID: (lnwire.ShortChannelID) 8:1422336:1659,
 Timestamp: (uint32) 23379,
 Flags: (lnwire.ChanUpdateFlag) 6389,
 TimeLockDelta: (uint16) 0,
 HtlcMinimumMsat: (lnwire.MilliSatoshi) 3940649673949184 mSAT,
 BaseFee: (uint32) 0,
 FeeRate: (uint32) 65536000
})
)
```

it seems the messages that look like this are sent from c-lightning nodes.

according to the rfc it looks like there *should* be a length specification in those messages
```type: UPDATE|7 (temporary_channel_failure)
data:
[2:len]
[len:channel_update]
```

thus i suspect lnd is doing it wrong both when crafting these messages and when parsing them.
apart from cosmetic issues, this also affects channel pruning in both lnd other implementations.

**Comment by Roasbeef** [comment] 2018-07-22 00:13
Our parsing is deterministic. AFAICT, this doesn't appear for `lnd` to `lnd`, therefore, we it's safe to conclude that this might be an issue with `c-lightning`. They've had an issue in the past due to stray pointer arithmetic where channel updates in their in-memory store get partially garbled. AFAIK, they've fixed this issue since then, so either it's a regression on their side, or you're interacting with a very old `c-lightning` node.

**Comment by robtex** [comment] 2018-07-22 01:09
btw i think the 01 02 might not a length byte as my first guess was, but rather message type 258

**Comment by cdecker** [comment] 2018-07-22 10:56
Yep, that looks a lot like there are two different interpretations of what it means to send back a channel_update: do we include the type or not? c-lightning includes it lnd seems not to.

For reference the `0x0102` bytes are indeed the message type 258 which is [channel_update](https://github.com/lightningnetwork/lightning-rfc/blob/fd9da9b95eb5d585252d7e749212151502e0cc17/07-routing-gossip.md#the-channel_update-message)

**Comment by robtex** [comment] 2018-07-22 14:39
Thank you guys!

I guess you will also check other message types used in similar cases.
`amount_below_minimum`, `fee_insufficient` , `incorrect_cltv_expiry` , `expiry_too_soon`, `channel_disabled` all include a `channel_update`

 I haven't done much interoperability tests myself. I started investigating this particular problem while trying to make my rebalancer understand which channels are down, however the symptoms themselves have been known for half a year now, and probably affecting the efficiency of routing for all implementations.

I suggest the implementations will make a fix that will be able to handle both formats, until all nodes are upgraded according to the concensus.

since `channel_update` is fixed size it is very easy and fixable with a couple of lines of code. 

also don't forget to get ACINQ involved.

**Comment by Roasbeef** [comment] 2018-07-23 19:52
Here's how we encode the failure messages: https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go#L1080

The length of the message, then the internal message itself. This is encapsulated in the htlc fail message which has its own type. 

The first thing in the buffer is the type of the error code itself: https://github.com/lightningnetwork/lnd/blob/master/lnwire/onion_error.go#L1048

**Comment by Roasbeef** [comment] 2018-07-23 19:53
> do we include the type or not? c-lightning includes it lnd seems not to.

We _always_ include the type as we use the same routine for encoding a regular channel update not encapsulated within an error message.

**Comment by Roasbeef** [comment] 2018-07-23 20:12
OK, so turns out that there's an ambiguity in the spec atm. It just says the length and then the channel update, without specifying the type itself.

**Comment by robtex** [comment] 2018-07-23 20:24
i think we should always including the type. 
including message type makes it flexible and easy to add other types instead of `channel_update` in the future.

**Comment by Roasbeef** [comment] 2018-07-23 23:33
We can't add other messages in the future (for these messages) as that would break the behavior of existing peers. It will need to be done in a new set of failure messages which includes the type. I agree that the newer messages should include the type just to make things explicit all the way through. Closing this for now as eclair also doesn't expect or write out the type there as it's implicit. I think the clightning devs will push a patch soon-ish to make it remove the type. In the mean time, it's still a routing error and lets you know that you should likely avoid using the channel in the short term

**Closed by Roasbeef** 2018-07-23 23:33 UTC

**Comment by robtex** [comment] 2018-07-24 04:36
Definitely should avoid the channel, that is what i try to do.
But i find the output is unparseable until lnd makes a compatibility patch to parse the message if it does include the message type, and i don't think internal routing logic of lnd is able to avoid that channel either.
A patch to check length and skip the first two bytes should be quick and trivial to implement.

**Comment by Roasbeef** [comment] 2018-07-24 04:37
So clightning is gonna be modified to exclude the length. lnd and ACINQ will keep their current behavior. The spec more or less says "the length of a channel update", not the "the length of a type and the channel update".

**Comment by robtex** [comment] 2018-07-24 05:35
i assume you mean the opposite? they should exclude the type but keep the length?

since we seem to only have channel_update as message type in the errors now, it is trivial to support both versions in all implementation, and update the spec to say it *should* include the type.

after all that seems to be the consensus of what is really the best approach.

otherwise we would need to wait until the future and then duplicate all error messages to be future-proof just in order to keep the old error messages not future-proof. and then we would have new issues with old implementations not being able to parse the new errors.

avoiding a channel that has temporary errors is the ultimate goal, but as long as neither side can interpret the other sides messages, they probably do not figure out *which* channel to avoid.

that said i would strongly suggest that the dev teams start doing compatibility tests themselves so issues like this doesn't take half a year to be discovered.

**Comment by cdecker** [comment] 2018-07-24 10:50
I thought we decided to standardize on including the type everywhere we have nested messages to make the length computation consistent with how we handle wire messages. We just allow the nested messages in an error to either be prefixed with a type or not.

@robtex if you rely on being able to parse the messages you can just check in your external script whether they have a type prefix or not.

**Comment by cdecker** [comment] 2018-07-24 10:52
Like I said yesterday, I prefer adding some workaround that prefixes the type if it is not present in the short-term, if it allows us to achieve a better consistency in the long-term.

**Comment by robtex** [comment] 2018-07-24 15:09
@cdecker i would if i could. unfortunately i don't get the entire hexdump.
the workaround to use parsed channelid, shifting it left 16 bits and shifting in 16 bits from the parsed timestamp to fill it up seems a little bit too hackish in comparison to how easy it would be to make the decoder inside lnd skip two bytes when needed before decoding it, which would also benefit lnd:s own route prune logic.

**Comment by Roasbeef** [comment] 2018-07-24 19:02
> I thought we decided to standardize on including the type everywhere we have nested messages to make the length computation consistent with how we handle wire messages.

Going forward yes, but since 2/3 have a current behavior, we decided clightning to switch over itself. Either way the rollout would be instant as most are still running on the tagged releases.

**Comment by robtex** [comment] 2018-07-24 19:39
how about this
1) make a small patch for reading channel_update with or without type included in all implementations
2) clightning removes type temporarily so old lnd/acinq implementations can understand it
3) when we are confident most nodes run a version that can read the version with type included, we start adding it in all implementations

**Comment by cdecker** [comment] 2018-07-24 19:54
> Going forward yes, but since 2/3 have a current behavior, we decided clightning to switch over itself. Either way the rollout would be instant as most are still running on the tagged releases.

So that implies this inconsistency would be dragged along indefinitely, and if we decided to clean up at a later point in time, we'd still need to add exactly the same code to handle both options, with the added bonus of now having a much larger install base.

**Comment by Roasbeef** [comment] 2018-07-24 21:49
Sorry, that should read _wouldn't_ be instant. 

>  and if we decided to clean up at a later point in time, we'd still need to add exactly the same code to handle both options

There's no future clean up of the _prior_ messages due to the existing deployment of both lnd and acinq nodes. What I'm referring to is the _next_ version of the HTLC fail messages (for example dlog based htlcs, etc) that allows us to revise exactly what the payload is. 

I'm just repeating what was decided on in the call: c-lightning is the minority here. In the past when spec incompatibilities like this were discovered, we've gone with a majority rule. 

Again, the issue here is with the language of the specification which states "the length of a channel update", which is 128 bytes. We can't modify the error messages to switch over to a new format as that breaks all existing clients. The only thing we can do is append to it, but given that it has max 256 bytes, we're constrained w.r.t what we can add in. The move to dlog based HTLCs will give us a clean slate to introduce the type properly, as the error messages there again need to be parsed end to end. 

(also remember even if you get a garbled error, which can just happen at anytime, you can _always_ prune still)

(meta commentary: the type is there to signal what the message is so you can parse it, the spec states it's a channel update, so you don't need the type to signal that, it's a wasted byte)

**Comment by Roasbeef** [comment] 2018-07-24 23:11
In the mean time, we can just parse both based on the length to bridge the gap a bit.

**Comment by rustyrussell** [comment] 2018-07-25 00:17
OK, to be *absolutely* sure, I grabbed a decrypted `temporary_channel_failure` msg from c-lightning:

```
100700820102fc56e016a3bd520d362b34f3cdf59107dfef006ee528d572549034964bb520cb4bb600923087a284390d28d887bcf1dd98eddf51a79bfad8573c2858b0652ded06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f00006700000100015b56d06c000000060000000000000000000000010000000a
```

You can see here:
1. 1007: the type `temporary_channel_failure` (4103)
2. 0082: the length of the following field (130 characters)
3. 0102...: the channel_update message, starting with the type (258)

So, indeed, we include the type in the channel_update.  On our call @Roasbeef and Fabrice indicated they *don't* include the type in lnd/eclair, though the comment above seems to contradict that.

**Comment by robtex** [comment] 2018-07-25 07:42
the statement that lnd always includes the message type was a mistake and probably prior to your voice-communication.
according to my investigations neither eclair nor lnd includes the message, in reality only clighting currently does.
the consensus seem to be that it should be included in the future, and for now the implementations should support both versions, which i think is an excellent idea!

**Comment by Roasbeef** [comment] 2018-07-25 23:49
> On our call @Roasbeef and Fabrice indicated they don't include the type in lnd/eclair, though the comment above seems to contradict that.

That's correct, we don't include the type.

**Comment by rustyrussell** [comment] 2018-07-30 10:45
OK, @cdecker has submitted a patch to c-lightning which will accept both (https://github.com/ElementsProject/lightning/pull/1775/commits/e32802191e3b305ed49c60d5e502dc911f7f8ae2), then we'll patch to send out the un-prefixed one as a separate PR.

**Comment by cdecker** [comment] 2018-07-30 20:11
For reference PR ElementsProject/lightning#1775 addresses both receiving as well as sending non-prefixed `channel_update`s.
