### ISSUE TITLE
[bug]: routing hints not included for private channel in invoices

### ISSUE THREAD

**Issue by vindard** [lightningnetwork/lnd#7753] opened 2023-06-07 16:22 UTC
### Background

I have 2 channels:
- 1 public (disabled)
- 1 private (active)

If I execute `lncli addinvoice --private --amt 1` I get back the following:
```
{
    "r_hash": "cdacb2659bf051d4bc5e0051a0eab7b03baa319a4819fedfc327ef0578b27c23",
    "payment_request": "lnbc10n1pjgpt8rpp5ekktyevm7pgaf0z7qpg6p64hkqa65vv6fqvlah7rylhs279j0s3sdqqcqzzsxqyz5vqsp53pxyyya4kmwctmcq89m5ems5el03462fzumhmxlmjzqlqmhtv3ns9qyyssqf2ep4f82d5qv4ck83rjful2pwt8afhyvuycp5g43ht7km4yu62j3r3xjx0y5pxdpqasg3jff02qfzam5vlgdu3xnreqrhq453gm3d2cq2knwjs",
    "add_index": "278",
    "payment_addr": "884c4213b5b6dd85ef0039774cee14cfdf1ae94917377d9bfb9081f06eeb6467"
}
```

This is my channel list:
```
{
    "channels": [
        {
            "active": false,
            "remote_pubkey": "<redacted>",
            "channel_point": "<redacted>:0",
            "chan_id": "<redacted>",
            "capacity": "120000",
            "local_balance": "8279",
            "remote_balance": "108251",
            "commit_fee": "2810",
            "commit_weight": "1116",
            "fee_per_kw": "2500",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "8279",
            "num_updates": "2",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "1200",
            "remote_chan_reserve_sat": "1200",
            "static_remote_key": false,
            "commitment_type": "ANCHORS",
            "lifetime": "1747498",
            "uptime": "0",
            "close_address": "",
            "push_amount_sat": "0",
            "thaw_height": 0,
            "local_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "1200",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "118800000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "remote_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "1200",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "118800000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "alias_scids": [
            ],
            "zero_conf": false,
            "zero_conf_confirmed_scid": "0",
            "peer_alias": "dirtballs",
            "peer_scid_alias": "0"
        },
        {
            "active": true,
            "remote_pubkey": "<redacted>",
            "channel_point": "<redacted>:0",
            "chan_id": "<redacted>",
            "capacity": "100000",
            "local_balance": "2710",
            "remote_balance": "93544",
            "commit_fee": "3086",
            "commit_weight": "1116",
            "fee_per_kw": "2746",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "2710",
            "num_updates": "56",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": true,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "1000",
            "remote_chan_reserve_sat": "1000",
            "static_remote_key": false,
            "commitment_type": "ANCHORS",
            "lifetime": "1747498",
            "uptime": "1747426",
            "close_address": "",
            "push_amount_sat": "0",
            "thaw_height": 0,
            "local_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "1000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "99000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "remote_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "1000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "99000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "alias_scids": [
            ],
            "zero_conf": false,
            "zero_conf_confirmed_scid": "0",
            "peer_alias": "spires.shelved.classics",
            "peer_scid_alias": "0"
        }
    ]
}
```

### Your environment

* version of `lnd`: `btcpayserver/lnd:v0.16.2-beta`
* version of `btcd`, `bitcoind`, or other backend: `btcpayserver/bitcoin:24.0.1-1`

**Comment by positiveblue** [comment] 2023-06-07 18:17
I wasn't able to reproduce it locally. Can you search the logs around the timestamp that you execute the add req?

Anything matching `unable to populate hophints`?

Also, is the node with the private channel "public"? ex: has public channels announced?

**Comment by guggero** [comment] 2023-06-08 15:43
Looks like the node was maybe pruned from the graph as a zombie (because the one public channel it has isn't public). How long has the other channel been inactive for? What does `lncli getnodeinfo` show for that peer?

**Comment by guggero** [comment] 2023-06-09 08:32
Thanks for the info on Slack. So my suspicion seems to be confirmed: Because from the point of view of your node the other node does not have an **active** public channel, it is classified as an "unadvertised" node. And the routing hint is not included to not leak information about fully unadvertised nodes (that hint wouldn't help you anyway as there is no public channel _to_ that node that could be routed through).

So I would say this is working as designed even if perhaps a bit un-intuitive?

**Comment by saubyk** [comment] 2023-06-13 04:10
hi @vindard hope @guggero 's explanation is satisfactory. Closing this issue now, feel free to comment or reopen if you feel otherwise. Thanks

**Closed by saubyk** 2023-06-13 04:10 UTC
Labels: invoices
