### ISSUE TITLE
fwdinghistory lost

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#3410] opened 2019-08-16 13:39 UTC
Executing ```lncli fwdinghistory --start_time 0``` yielded results a few days ago, with 10 records, now it's empty.

**Comment by wpaulino** [comment] 2019-08-16 20:00
Duplicate of https://github.com/lightningnetwork/lnd/issues/3357.

**Closed by wpaulino** 2019-08-16 20:00 UTC
