### ISSUE TITLE
wallet: respect policy-level transaction size limits when crafting regular and funding transactions 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#4760] opened 2020-11-11 01:26 UTC
Tracking this here instead of the `btcwallet` issue for more visibility. As is, we don't always ensure that a transaction either we construct manually (for funding) or within `btcwallet` itself is below the current widely used policy that constraints transaction sizes. Thankfully, we can simply start using the existing policy level function within `btcd` itself to enforce these limits: https://github.com/btcsuite/btcd/blob/master/mempool/policy.go#L271 

When a user encounters this issue, they'll see this in the logs: 
```
: unmatched backend error: -26: 64: tx-size
```

And then end up with a dangling transaction that'll keep being rebroadcast, when instead we should remove it from the tx store.

**Comment by Roasbeef** [comment] 2020-11-17 02:04
Actually, reading the `btcwallet` code more closely here, I think we already properly handle this case. What we don't do however, is remove the "pending open" channel from the lnd's DB.

**Comment by yyforyongyu** [comment] 2022-03-24 05:17
> we have already sent our tx out into the wild and cant ever be 100% sure that it has not actually broadcast.

I don't think this is something we want to deal here. We use the interface `PublishTransaction` here, which is implemented in `btcwallet`. If the above statement is an issue then we should fix it in `btcwallet`.

Basically we rely on [this interface here](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/interface.go#L354), and it must do what it guarantees. Otherwise we'd have an issue not just in funding, but every call site of this interface in `lnd`.

As for the scope, I think this issue deals specifically with the error `: unmatched backend error: -26: 64: tx-size`. However, `PublishTransaction` doesn't explicitly return this error, as it maps the error codes [here](https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L3673). So to continue the work in #5158, I think if we could explicitly check this error we'd be safe. So either,
- we change `btcwallet` to catch and return this error explicitly, or,
- we can do an error match in `lnd` to be sure we are getting this exact error when `PublishTransaction` fails.

**Comment by Crypt-iQ** [comment] 2022-03-24 13:15
> > we have already sent our tx out into the wild and cant ever be 100% sure that it has not actually broadcast.
> 
> I don't think this is something we want to deal here. We use the interface `PublishTransaction` here, which is implemented in `btcwallet`. If the above statement is an issue then we should fix it in `btcwallet`.
> 

I believe elle is referring to the case where we send a transaction and we receive a malicious MsgReject in neutrino. Or another scenario like maybe we're eclipsed and have sent it out, but it hasn't propagated. This neutrino case should definitely be fixed in addition to the PR that fixes this issue.

> Basically we rely on [this interface here](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/interface.go#L354), and it must do what it guarantees. Otherwise we'd have an issue not just in funding, but every call site of this interface in `lnd`.
> 

I still think having some API that calls PublishTransaction and continues to do so until some block-timeout would be useful.

> As for the scope, I think this issue deals specifically with the error `: unmatched backend error: -26: 64: tx-size`. However, `PublishTransaction` doesn't explicitly return this error, as it maps the error codes [here](https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L3673). So to continue the work in #5158, I think if we could explicitly check this error we'd be safe. So either,
> 
>     * we change `btcwallet` to catch and return this error explicitly, or,
> 
>     * we can do an error match in `lnd` to be sure we are getting this exact error when `PublishTransaction` fails.

This is what a testmempoolaccept api could pre-emptively handle. This is already something that we need as having one would have caught the high-S signatures CVE. I do think though that a minimum fix would be something along the lines of your original PR, but we'd want to catch _more_ than just tx-size since there are other policy checks that can fail besides size. As an example, an error that is returned that is not policy and wouldn't be caught if we'd only catch tx-size is mempool min fee not met. If all non-double-spend errors are caught, however, I think it would be a good idea to wait until the input is double-spent or the channel is confirmed on chain (either we missed something or the user took their raw tx and broadcast it elsewhere) before cleaning up as a safety measure in case something was missed.

**Comment by yyforyongyu** [comment] 2022-03-25 05:27
@Crypt-iQ  If we want to handle more than tx-size error, it'd be nice but another story. This `testmempoolaccept` is dope and can be implemented in `btcwallet`. I think our abstractions are pretty clear here, `lnd` defines all types of transactions, `btcwallet` treats them as raw tx and handles the validation and broadcast. Behind the wallet there are three chain backends handling layer one stuff. If we want to fix the issues across the layers of abs, then a good first step IMO is to refactor `PublishTransaction` to return a list of explicitly defined errors, and we handle the errors one by one in `lnd`. I don't think there's one solution to fit in all the scenarios, eg if tx-size is not right we are sure we can abandon the funding flow.

> or the user took their raw tx and broadcast it elsewhere

If this happens it's nice to handle it but not necessary or urgent IMO. Meanwhile, curious why would a user do that?

**Comment by Crypt-iQ** [comment] 2022-03-25 12:56
`testmempoolaccept` would probably be written in btcd and called from btcwallet. My point is there are more policy errors besides tx-size that a user can hit and these would probably occur with the psbt api. This issue is concerned with tx-size, but it could easily include every policy violation and `PublishTransaction` would just return some `PolicyError`. Also the mempool-min-fee error should be caught and special-cased probably

> Meanwhile, curious why would a user do that?

Users pretty much do anything and everything given some large timeframe. I was thinking this would happen using the psbt api.

**Comment by Roasbeef** [comment] 2022-05-23 17:56
Seeing this in #6566 but odd in that if you go to my last linked comment there, in the code we should _always_ remove the transaction on startup when/if we go to rebroadcast it, but also the very first time we go to broadcast it (unless that fails for some reason).

**Comment by ellemouton** [comment] 2023-04-21 12:25
More details from users who have run into this for both `sendcoins` and during channel open can be found in these issues:

https://github.com/lightningnetwork/lnd/issues/6556
https://github.com/lightningnetwork/lnd/issues/7622

**Closed** 2024-01-27 02:54 UTC
Labels: bug, wallet, beginner, intermediate, P1, policy
