### ISSUE TITLE
Negative blocks till maturity on SCB + Seed Restore

### ISSUE THREAD

**Issue by thelightningist** [lightningnetwork/lnd#4004] opened 2020-02-14 22:05 UTC
EDIT: here are the CNCT logs

https://hastebin.com/vasagicuxa.cs

### Background

A while back, my storage device failed and I lost my LND wallet with channels. Fortunately, I had the latest copy of the scb file (channel.backup) and my seed.

When I restore with the seed and copy the scb over, I am able to see my old channels and balances. They were all in “waiting close” for about a week until I tried force closing them, but there was no change. 

When I run lncli pendingchannels I see the channels, almost all of which have negative blocks till maturity. Does this means the funds have settled but something isn’t updating to send it back to my lnd wallet?

### Your environment

* version of `lnd`
0.9.0 beta
* which operating system (`uname -a` on *Nix)

Linux raspberrypi 4.19.102-v7l+, “Raspiblitz” image 
* version of `btcd`, `bitcoind`, or other backend

Bitcoind 19.0.1

* any other relevant environment details
Routed behind the TOR network and successfully connected to 11 peers

### Steps to reproduce

Restore using seed + SCB file, use lncli pendingchannels after everything is set up and running 

### Expected behaviour
Force closed channels should finalize after the blocks till maturity unit is reached

### Actual behaviour

Force closed channels are still in a pending state and have a negative value in blocks until maturity 
Hastebin output of pending channels:

https://hastebin.com/atilayiwuf.bash

**Comment by wpaulino** [comment] 2020-02-14 22:14
Have you tried multiple restore attempts? If you look at these channels on-chain, all your outputs have already been swept, some of them have even been used for new channels. Could you paste `CNCT` for 2-3 channels in this state?

Looks similar to https://github.com/lightningnetwork/lnd/issues/3321.

**Comment by thelightningist** [comment] 2020-02-14 22:43
> Have you tried multiple restore attempts? If you look at these channels on-chain, all your outputs have already been swept, some of them have even been used for new channels. Could you paste `CNCT` for 2-3 channels in this state?
> 
> Looks similar to #3321.

I have tried multiple restore attempts. I just did one last night and it was probably the 5th or 6th one. The one last night was one week since the previous restore. Every previous restore I have gotten funds swept up but not so with this current attempt. 

What’s the best way for me to retrieve the CNCT state of a couple of channels?

**Comment by wpaulino** [comment] 2020-02-14 23:48
Forgot a word:

Could you paste `CNCT` logs for 2-3 channels in this state?

**Comment by thelightningist** [comment] 2020-02-15 00:02
Here’s 
"026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2"

https://hastebin.com/igatemuqeq.coffeescript

And now 

“026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2”

https://hastebin.com/ozacifoqic.coffeescript

**Comment by wpaulino** [comment] 2020-02-15 00:06
We'll need to grep for logs containing `[CNCT]` for the channel point, not the node public key.

**Comment by thelightningist** [comment] 2020-02-15 00:39
Duplicate of #

> We'll need to grep for logs containing `[CNCT]` for the channel point, not the node public key.

I’m trying when searching the same logs for the channel point instead but it returns nothing. For me the log path is /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log ,

Any suggestions on what command I should use to put the channel point hash into?

**Comment by thelightningist** [comment] 2020-02-17 03:44
> We'll need to grep for logs containing `[CNCT]` for the channel point, not the node public key.

Hi, when I try
`sudo cat /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | grep "channelpoint"`

I get

`2020-02-17 03:37:33.576 [DBG] UTXN: NurseryReport: building nursery report for channel "channel ID"`

Any idea where I can go to access the NurseyReports?

**Comment by thelightningist** [comment] 2020-02-17 04:21
After doing more research, it seems like I need to turn on CNCT trace. 

But when I do 
`lncli debuglevel CNCT=trace`

I get

`[lncli] rpc error: code = Unknown desc = the specified debug level [] is invalid`

Any ideas what is wrong with my syntax?

**Comment by guggero** [comment] 2020-02-17 08:43
> `sudo cat /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | grep "channelpoint"`

Try `grep -i` to do case insensitive search, most likely `ChannelPoint` is written camel case in most cases (but perhaps not always).

You can use the `--help` flag for all `lncli` commands. That will tell you that the command is `lncli debuglevel --level CNCT=trace`

**Comment by thelightningist** [comment] 2020-02-17 20:57
> > `sudo cat /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log | grep "channelpoint"`
> 
> Try `grep -i` to do case insensitive search, most likely `ChannelPoint` is written camel case in most cases (but perhaps not always).
> 
> You can use the `--help` flag for all `lncli` commands. That will tell you that the command is `lncli debuglevel --level CNCT=trace`

Thank you! I’ll try this. I was trying to use the help command but didn’t quite understand how the level syntax was supposed to work. Thank you though. 

I should also clarify, the channel point reference I had in my previous post is the placeholder for the value next to channel point when using the lncli pendingchannels command

**Comment by thelightningist** [comment] 2020-02-17 23:56
> We'll need to grep for logs containing `[CNCT]` for the channel point, not the node public key.

Here are the CNCT logs
https://hastebin.com/vasagicuxa.cs

**Comment by thelightningist** [comment] 2020-02-19 04:34
And here are some more 
https://hastebin.com/okibezuzoz.sql

**Comment by wpaulino** [comment] 2020-02-19 18:29
Thanks for the logs! I went through each channel and confirmed that all the funds been swept, so you should have the balance in your on-chain wallet. The fact that the channels remain in `pendingchannels` is a bug within `lnd` where it doesn't recognize previous channel restore attempts. Closing this as a duplicate of #3321.

**Closed by wpaulino** 2020-02-19 18:29 UTC

**Comment by thelightningist** [comment] 2020-02-19 20:19
> Thanks for the logs! I went through each channel and confirmed that all the funds been swept, so you should have the balance in your on-chain wallet. The fact that the channels remain in `pendingchannels` is a bug within `lnd` where it doesn't recognize previous channel restore attempts. Closing this as a duplicate of #3321.

If I don’t have the balance with my on chain wallet, is there something I can do to prompt the node to scan and pick it up?

**Comment by wpaulino** [comment] 2020-02-19 20:25
If you already recovered from your seed, the balance should be there unless you already spent those funds elsewhere. For example, if you look at the channel `19efead5d19f0a51bfe0763715bee528e36fd5f5cbf40723b34fd5977d4efa00`, the closing transaction is `cdae9571f97fb2c5758f6d2e2f59d1465a1fa6d2a2e4a73ff1964c67fcf13e62`, and the transaction that returned the funds back to your wallet is `5841b42f4280d7f83120a5e55890af6906537864423a7716751fecdb63562773`. From there, you can track where the funds may have gone.
