### ISSUE TITLE
gRPC "SubscribeForwardingEvent" method

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3333] opened 2019-07-22 15:33 UTC
Hello,

I have a suggestion to implement the subscribe gRPC method for forwardning payments (realtime). So that when it gets a new payment he can create an event about it. I think this API method would be useful.

I think about creating a visualization of the passage of payments for viewing by everyone. A lot of people are interested in the number of payments going through lightning network. Given the large capacity of the LNBIG network, it would be interesting to see in real time the progress of payments in order to get a feel for the lightning network load. If I make such a visualization I will anonymize the external nodes as much as possible which accept and send the payment (for example by creating fake node id through HMAC function with hidden key so thus the outside observer will see the outside anonymised nodes and will not know the real network node).

You already have `SubscribeTransactions`, `SubscribeChannelEvents`, `SubscribeChannelGraph` and `SubscribeInvoices` method. If there would be like `SubscribeForwardingEvent` it would be fine.

**Comment by wpaulino** [comment] 2019-07-22 19:17
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/2103.

**Closed by wpaulino** 2019-07-22 19:17 UTC

**Comment by Roasbeef** [comment] 2019-07-29 22:53
>  If I make such a visualization I will anonymize the external nodes as much as possible which accept and send the payment

Even just making the _access pattern_ public, can give away a lot of information.
