### ISSUE TITLE
Pending open channel with no longer valid channel_point

### ISSUE THREAD

**Issue by prusnak** [lightningnetwork/lnd#5380] opened 2021-06-12 14:39 UTC
### Background

I opened a channel via `lncli openchannel --conf_target 0`, but the funds never confirmed. The transactions has fallen out of mempool because the inputs were used for another transaction (RBF).

The channel is not stuck in `lncli pendingchannels`, but it will never open, because the channel_point is invalid (and it never will be).

### Your environment

* version: `0.12.1-beta commit=v0.12.1-beta`
* OS: `Debian x86_64 GNU/Linux`
* backend: `bitcoind 0.21.0`

---

I am aware about `lncli abandonchannel`, but for that I'd need a debug version of lnd, while the situation happened with production build of lnd, so I think it should be possible to recover from it also with non-debug version of lnd.

---

Suggested solution: Maybe lnd should keep a copy of channel_point transaction and check against the UTXO set whether the transaction is still valid and mineable.

**Comment by wpaulino** [comment] 2021-06-14 18:42
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/386.

**Closed by wpaulino** 2021-06-14 18:42 UTC
