### ISSUE TITLE
Payment stuck in IN_FLIGHT state

### ISSUE THREAD

**Issue by tdickman** [lightningnetwork/lnd#4788] opened 2020-11-20 19:01 UTC
### Background

Creating as a replacement for [this ticket](https://github.com/lightningnetwork/lnd/issues/4381).

We have a payment that is stuck in the `IN_FLIGHT` state. One of the htlcs is stuck in the `IN_FLIGHT` state despite having an expiry that is in the past. When listing channels we see no pending htlcs for the involved channel.

### Your environment

* version of `lnd`: `0.11.1-beta commit=v0.11.1-beta`
* which operating system (`uname -a` on *Nix): `Linux nodes-lnd-667ff844cc-2krmj 4.19.112+ #1 SMP Fri Sep 4 12:00:04 PDT 2020 x86_64 Linux`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind 0.17.1`
* any other relevant environment details

### Steps to reproduce

Initiate an outgoing payment (loop operation in our case). Get unlucky, and get one of the htlcs to get stuck in the `IN_FLIGHT` state beyond the expiry of the htlc.

### Expected behaviour

Payment should `FAIL` when expiry of htlcs is breached.

### Actual behaviour

Payment gets stuck in the `IN_FLIGHT` state after expiry of htlcs. In addition, channel shows no pending htlcs (in fact our node shows 0 pending htlcs).

[Example payment](https://paste.ubuntu.com/p/B5RPZDnrZ6/)

**Comment by Roasbeef** [comment] 2020-11-20 19:50
Do you see the payment retry on start up for the node?

**Comment by halseth** [comment] 2020-11-20 19:59
Related do https://github.com/lightningnetwork/lnd/issues/4501

**Comment by halseth** [comment] 2020-11-20 19:59
Do you have logs from when the payment was sent?

**Comment by tdickman** [comment] 2020-11-20 20:34
> Do you have logs from when the payment was sent?

Our node outputs a lot of logs unfortunately - I can try getting just the logs around when the payment was sent (let me know), but here are all log statements with the payment hash:

```
2020-11-11 07:34:27.599 EST
2020-11-11 12:34:27.599 [WRN] CRTR: Attempt 105183 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc001ca8b00)({
Info
2020-11-11 07:36:53.323 EST
2020-11-11 12:36:53.322 [WRN] CRTR: Attempt 105187 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc003193600)({
Info
2020-11-11 07:36:53.323 EST
2020-11-11 12:36:53.323 [WRN] CRTR: Attempt 105188 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc002bfc6e0)({
Info
2020-11-11 07:39:28.784 EST
2020-11-11 12:39:28.783 [WRN] CRTR: Attempt 105195 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc001e414a0)({
Info
2020-11-11 07:39:49.857 EST
2020-11-11 12:39:49.857 [WRN] CRTR: Attempt 105197 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc00d0e4160)({
Info
2020-11-11 07:42:05.053 EST
2020-11-11 12:42:05.053 [WRN] CRTR: Attempt 105193 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: MPPTimeout@5
Info
2020-11-11 07:42:45.648 EST
2020-11-11 12:42:45.645 [WRN] CRTR: Attempt 105203 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc002c829a0)({
Info
2020-11-11 07:43:39.295 EST
2020-11-11 12:43:39.295 [WRN] CRTR: Attempt 105206 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc00a2b2000)({
Info
2020-11-11 07:44:05.525 EST
2020-11-11 12:44:05.524 [WRN] CRTR: Attempt 105202 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: MPPTimeout@5
Info
2020-11-11 07:46:46.509 EST
2020-11-11 12:46:46.509 [WRN] CRTR: Attempt 105214 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc003192160)({
Info
2020-11-11 07:47:12.515 EST
2020-11-11 12:47:12.515 [WRN] CRTR: Failed to find route for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c: unable to find a path to destination
Info
2020-11-11 07:47:19.241 EST
2020-11-11 12:47:19.241 [WRN] CRTR: Attempt 105215 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc001d69e40)({
Info
2020-11-11 07:47:35.683 EST
2020-11-11 12:47:35.683 [WRN] CRTR: Attempt 105209 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: MPPTimeout@5
Info
2020-11-11 07:48:17.976 EST
2020-11-11 12:48:17.976 [WRN] CRTR: Attempt 105211 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: MPPTimeout@5
Info
2020-11-11 16:29:17.309 EST
2020-11-11 21:29:17.309 [WRN] CRTR: Attempt 105217 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: MPPTimeout@5
Info
2020-11-11 16:29:32.581 EST
2020-11-11 21:29:32.581 [WRN] CRTR: Attempt 105223 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: IncorrectOrUnknownPaymentDetails(amt=404280762 mSAT, height=656496)@5
Info
2020-11-13 16:02:34.023 EST
2020-11-13 21:02:34.014 [ERR] CRTR: Error collecting result for shard 105229 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c: shard handler exiting
Info
2020-11-13 16:02:34.023 EST
2020-11-13 21:02:34.014 [ERR] CRTR: Error collecting result for shard 105227 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c: shard handler exiting
Info
2020-11-13 16:02:34.023 EST
2020-11-13 21:02:34.014 [ERR] CRTR: Error collecting result for shard 105225 for payment ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c: shard handler exiting
Info
2020-11-13 16:02:34.023 EST
2020-11-13 21:02:34.014 [ERR] CRTR: Payment with hash ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: router shutting down
Info
2020-11-13 16:12:50.981 EST
2020-11-13 21:12:50.981 [INF] CRTR: Resuming payment with hash ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c
Info
2020-11-17 09:15:43.206 EST
2020-11-17 14:15:43.204 [ERR] CRTR: Resuming payment with hash ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c failed: router shutting down.
Info
2020-11-17 09:18:08.146 EST
2020-11-17 14:18:08.146 [INF] CRTR: Resuming payment with hash ae2379e4f27cb32d13772c32b95f6b8781cfc1304356be4b2e49839b4d50ac8c
```

**Comment by tdickman** [comment] 2020-11-20 20:49
> Do you see the payment retry on start up for the node?

Is searching by the payment hash the best way to find this? (Our node has lots of log output, especially at startup).

**Comment by halseth** [comment] 2020-11-24 11:58
> Our node outputs a lot of logs unfortunately 

This is a good thing 😁

**Comment by halseth** [comment] 2020-11-24 12:00
@tdickman Do you see this often? 

Unfortunately there is not much to go on in the `info` logs. If you could bump your `debuglevel` to `debug` and report back if this happens again that would be super helpful 🙏

**Comment by halseth** [comment] 2020-11-24 13:21
@tdickman Could you also try grepping for the three failed payment IDs (105225, 105227, 105229) in addition to the payment hash? See if there is anything useful there.

**Comment by halseth** [comment] 2021-02-25 11:49
@tdickman Have you seen this happening lately?

**Comment by tdickman** [comment] 2021-02-25 13:41
I have not seen it happen much recently, but I also haven't been swapping as much lately, which was the primary trigger for it.

**Comment by halseth** [comment] 2021-02-25 14:10
OK, no worries. Be sure to run with debug logs and let me know when/if this happens again. Sounds like an issue we should get to the bottom of :)

**Comment by villastrangiato** [comment] 2021-02-26 06:55
Hi, 

every time i reboot my node i get these lines in the logfile

```
[DBG] CRTR: Payment 2137ce8f1a45f65c6e6c26296217ddd6e6008bb1fbc2733053cbefad089d6773 in state terminate=false, active_shards=1, rem_value=0 mSAT, fee_limit=0 mSAT
[DBG] CRTR: Payment b976fd5aa52aadb8f41b10630bef560415fb96b585e7a29b20d0a6218ea2c4ac in state terminate=false, active_shards=1, rem_value=0 mSAT, fee_limit=0 mSAT
[DBG] CRTR: Payment fdd46834a9873b094ba7982096e96946f28f39e31d7a94a96d24b3df5200b4c7 in state terminate=false, active_shards=1, rem_value=0 mSAT, fee_limit=0 mSAT
[DBG] CRTR: Payment 5cc5f52bf01cd7c726ac4d418bc7c91b1a3f947c01d15dfc7e1214342f5d93d1 in state terminate=false, active_shards=1, rem_value=0 mSAT, fee_limit=0 mSAT
```

also, not sure if related, lately I'm not routing much HTLC as before and getting a lot of these messages:

```
[ERR] HSWC: Unhandled error while reforwarding htlc settle/fail over htlcswitch: insufficient bandwidth to route htlc
```

being all my channels well founded and balanced this looks suspicious.

**Comment by halseth** [comment] 2021-02-26 09:47
@villastrangiato Do you see the payment having `in_flight`  HTLCs in `listpayments`?



> also, not sure if related, lately I'm not routing much HTLC as before and getting a lot of these messages:
> 
> ```
> [ERR] HSWC: Unhandled error while reforwarding htlc settle/fail over htlcswitch: insufficient bandwidth to route htlc
> ```

No totally sure if related. @cfromknecht any idea?

**Comment by villastrangiato** [comment] 2021-02-26 09:57
> @villastrangiato Do you see the payment having `in_flight` HTLCs in `listpayments`?

yes!

**Comment by halseth** [comment] 2021-02-26 10:03
@villastrangiato Do you know when the payment was originally attempted? And do you have logs from that time?

**Comment by villastrangiato** [comment] 2021-02-26 16:28
> @villastrangiato Do you know when the payment was originally attempted? And do you have logs from that time?

apparently they are very old: if the creation date is in seconds, they originated in december 2019.
unfortunately my logs don't go that far back in time.

```
{
	    "payment_hash": "fdd46834a9873b094ba7982096e96946f28f39e31d7a94a96d24b3df5200b4c7",
            "value": "8936",
            "creation_date": "1575737043",
            "fee": "0",
            "payment_preimage": "0000000000000000000000000000000000000000000000000000000000000000",
            "value_sat": "8936",
            "value_msat": "8936000",
            "payment_request": "",
            "status": "IN_FLIGHT",
            "fee_sat": "0",
            "fee_msat": "0",
            "creation_time_ns": "1575737043000000000",
{
            "payment_hash": "5cc5f52bf01cd7c726ac4d418bc7c91b1a3f947c01d15dfc7e1214342f5d93d1",
            "value": "8936",
            "creation_date": "1575739613",
            "fee": "0",
            "payment_preimage": "0000000000000000000000000000000000000000000000000000000000000000",
            "value_sat": "8936",
            "value_msat": "8936000",
            "payment_request": "",
            "status": "IN_FLIGHT",
            "fee_sat": "0",
            "fee_msat": "0",
            "creation_time_ns": "1575739613000000000",
            "htlcs": [

 {
            "payment_hash": "2137ce8f1a45f65c6e6c26296217ddd6e6008bb1fbc2733053cbefad089d6773",
            "value": "55958",
            "creation_date": "1576209926",
            "fee": "0",
            "payment_preimage": "0000000000000000000000000000000000000000000000000000000000000000",
            "value_sat": "55958",
            "value_msat": "55958000",
            "payment_request": "",
            "status": "IN_FLIGHT",
            "fee_sat": "0",
            "fee_msat": "0",
            "creation_time_ns": "1576209926000000000",
            "htlcs": [

  {
            "payment_hash": "b976fd5aa52aadb8f41b10630bef560415fb96b585e7a29b20d0a6218ea2c4ac",
            "value": "55958",
            "creation_date": "1576210170",
            "fee": "0",
            "payment_preimage": "0000000000000000000000000000000000000000000000000000000000000000",
            "value_sat": "55958",
            "value_msat": "55958000",
            "payment_request": "",
            "status": "IN_FLIGHT",
            "fee_sat": "0",
            "fee_msat": "0",
            "creation_time_ns": "1576210170000000000",
```

**Comment by lukaszsamson** [comment] 2021-03-20 17:12
I'm also seeing this issue on v0.12.1. In my case I can see that the payment failed
```
2021-03-18 08:18:39.458 [WRN] CRTR: Failed to find route for payment 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb: unable to find a path to destination
2021-03-18 08:18:40.941 [WRN] CRTR: Attempt 5265 for payment b30f90271eb5803ae4f1684302ea3867a27881c169b4da23203852a7a090061b failed: IncorrectOrUnknownPaymentDetails(amt=30000000 mSAT, height=675131)@3
2021-03-18 08:18:41.121 [WRN] CRTR: Attempt 5693 for payment 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: IncorrectOrUnknownPaymentDetails(amt=393362133 mSAT, height=675131)@6
2021-03-18 08:18:41.847 [INF] CRTR: Payment b30f90271eb5803ae4f1684302ea3867a27881c169b4da23203852a7a090061b failed: final_outcome=incorrect_payment_details, raw_err=IncorrectOrUnknownPaymentDetails(amt=30000000 mSAT, height=675131)@3
2021-03-18 08:18:41.958 [INF] CRTR: Payment 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: final_outcome=incorrect_payment_details, raw_err=IncorrectOrUnknownPaymentDetails(amt=393362133 mSAT, height=675131)@6
2021-03-18 08:18:42.092 [ERR] CRTR: Payment with hash b30f90271eb5803ae4f1684302ea3867a27881c169b4da23203852a7a090061b failed: incorrect_payment_details
2021-03-18 08:18:42.946 [ERR] CRTR: Payment with hash 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: payment has reached terminal condition
```
or
```
2021-03-20 11:55:43.704 [WRN] CRTR: Attempt 6239 for payment 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: IncorrectOrUnknownPaymentDetails(amt=406819278 mSAT, height=675453)@7
2021-03-20 11:55:44.289 [INF] CRTR: Payment 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: final_outcome=incorrect_payment_details, raw_err=IncorrectOrUnknownPaymentDetails(amt=406819278 mSAT, height=675453)@7
2021-03-20 11:55:44.583 [ERR] CRTR: Payment with hash 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: payment has reached terminal condition
```
but the payment is still IN_FLIGHT (both in listpayments and trackpayment responses)

restarting lnd causes the payment to be retried
```
2021-03-20 16:44:56.570 [ERR] CRTR: Resuming payment with hash 76e0570ea031be6f584b69fa2f67f2c8ef320beee5295be24671db22ef0ee7fb failed: incorrect_payment_details.
```
but this time its cirrectly marked as FAILED
```
As in @tdickman case the payment was a loop out. I have info level the logs from when it was issued but there is nothing out of the ordinary.

**Comment by halseth** [comment] 2021-03-22 08:20
@lukaszsamson Do you still have the full logs around when this happened? Would be very helpful if I could take a look at them. Feel free to reach out to me on keybase (@halseth) or the LND slack (@johanth)

**Comment by halseth** [comment] 2021-03-22 14:11
Okay, I think I see the problem now, it is indeed a race condition with how the shards are updating the DB state.

1) We send out some shards.
2) We have more value to send, so we attempt to find a route for another shard.
3) While pathfinding is ongoing, the result for a previous shard comes back, and has a terminal condition. It will mark the payment failed with a terminal error in the DB.
4) Pathfinding finishes, and we attempt to send the next shard. However, this shard is not allowed to be sent since the payment has failed. Currently we treat this as an unexpected error and stop whatever we were doing at that point.
5) This means that if there was more outstanding shards at this point, we won't handle their results, and the payment will stay `IN_FLIGHT`.

I think the fix could be as simple as not treating that error as an unexpected one, but will have to see if there are more edge cases we should handle :)

**Comment by carlaKC** [comment] 2021-04-14 09:14
Going to pick this one up!

**Comment by calvinrzachman** [comment] 2021-04-18 23:15
Hey guys, forgive me if I state what's already known, but if you take a look at the [`channeldb.fetchPayment()`](https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta.rc6-branch/channeldb/payments.go#L358-L365) method, you will notice that we report (to the caller both internal and externally via RPC) that a payment is `IN-FLIGHT` if there are ANY in-flight HTLCs, regardless of what the top level [`paymentFailInfoKey`](https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta.rc6-branch/channeldb/payments.go#L94) says about the failure status of the payment. 

So in a way the `fetchPayment` method seems to be lying to the user of the RPC. The payment is indeed marked as failed in the database (that would be the whole reason our attempt to `launchShard()` fails with an error), but we decide to report that the payment is still in-flight? This seems like a piece of the trouble to me.

Is it proper for a payment to be considered `IN-FLIGHT` after it has been marked as having failed by `r.cfg.Control.Fail()`? Perhaps it was done this way for a good reason that I am not aware of.  Given [this comment](https://github.com/lightningnetwork/lnd/blob/v0.12.1-beta.rc6-branch/channeldb/payment_control_test.go#L681) it seems @halseth might have the insight for why a payment should not be considered “failed” if there are any outstanding HTLCs.

It makes sense that failing a payment need not update all HTLCs to be marked as having failed. The shards may already have been forwarded by the Switch and we need to spin up the result collecting go routines if we end up retrying a failed payment/restarting the Channel Router, but why require that a payment always be considered in-flight if it has any in-flight HTLCs?

**Comment by carlaKC** [comment] 2021-04-19 08:06
Thanks for the in-depth investigation @calvinrzachman, really fantastic work!

> Is it proper for a payment to be considered IN-FLIGHT after it has been marked as having failed by `r.cfg.Control.Fail()`? 

I believe it is correct for a payment to still be in-flight if it has pending htlcs after we call `r.cfg.Control.Fail()`, because we want to wait for those htlcs to report back before finalizing the payment. 

It seems like there are two possible errors we could run into that will cause a stuck state: 
1. `ErrPaymentAlreadyFailed`: when we launch one shard, get a permanent failure then try to launch another
2. `ErrPaymentTerminal`: when we launch > 1 shard, get a permanent failure then try to launch another (as you point out [here](https://github.com/lightningnetwork/lnd/pull/5214#discussion_r615492475), and reported [above](https://github.com/lightningnetwork/lnd/issues/4788#issuecomment-803428143))

In practice we could hit either, depending on how quickly the permanent failure comes back/how many shards we launch. The current solution addresses (1) but not (2), so I'm going to update to reproduce and address that as well. Going to try to bring the mock in-line with our actual impl, since that seems to be an issue in testing these conditions.

**Comment by halseth** [comment] 2021-04-19 10:18
@calvinrzachman Thanks, you bring up a good point. We should probably make the check when registering a new shard a bit "smarter".

However, the reason we must consider the payment stil `IN_FLIGHT` as long as there are shards left, is that technically it could still succeed even though we have reached a terminal error. For the reverse condition (we have learnt the preimage, but there are still shards int flight), it would be safe to consider it `SUCCEEDED`, but seems easier to just wait for all shards to have resolved for the symmetry.

As @carlaKC points out it looks like we missed the `ErrPaymentTerminal` case. To me it seems like the easiest solution would be to justmove the `TerinalInfo` check first?

**Comment by calvinrzachman** [comment] 2021-04-19 16:49
Hey, thanks for explaining here. IIUC, it seems like we have a `terminal error = no more shards sent`, but still wait on any existing `IN_FLIGHT` shards type approach? If a payment ends up with a stuck shard, as is the case here, we will just end up waiting till CLTV expiry notification (I assume from the Switch). At this point we will be able to fail the shard and report the payment as failed to the user so they can retry.

I fully agree with your summary, @carlaKC.

I have a local branch for user initiated payment ["cancellation" via RPC](https://github.com/lightningnetwork/lnd/issues/4562). I might have some questions soon for you on that @halseth, though it will surely be helped by understanding this better.

**Closed** 2021-04-23 16:50 UTC
Labels: P1, bug, missing reproduction, mpp, routing

**Comment by dolcalmi** [comment] 2021-12-27 17:31
we are having the same issue described here (track payment return in-flight, 1tx more than 10 days other more than 60 days) is it safe to return the funds if there are no pending transactions in the outgoing channel?

lnd version: v0.14.1-beta

**Comment by dskvr** [comment] 2023-06-08 12:35
Same issue as described here w/ `lnd version 0.15.4-beta commit=v0.15.4-beta`
