### ISSUE TITLE
count of routings decrease after some time and only and restart helps

### ISSUE THREAD

**Issue by kieselbert** [lightningnetwork/lnd#6937] opened 2022-09-21 16:11 UTC
### Background

Its hard to describe that issue. If my node runs a longer time without restarts, the amount of routings decreases slowly. After an restart of the node or lnd the routing events are much higher than normal. This effect does not happen by chance, but is reproducible.
I can manily increase my routings by periodically restarting my node. But that should not be the solution.

![ln_transaction_count](https://user-images.githubusercontent.com/4134726/191551665-d02773c8-15d9-49a0-ae0f-9c999bd8b4d7.JPG)
This chart should show that effect and I think there is no need to explain on which day I restarted my node.
I can provide many of similar charts that show the same behave.
What is the best attempt to find something in the lnd.log that is maybe related to this issue. I see nothing that looks like an error or somthing else.

### Your environment

LND v0.14.3-beta
Bitcoin v22.0.0
Ubuntu 22.04 LTS

### Steps to reproduce
Wait some days, routing events are becoming less and less. Restart LND and I have more routings in a few hours then in the last couple auf days.

### Expected behaviour

I'm not here to complain about lnd, I'm looking for clues what may be causing this behavior. But I have no idea where to start looking.

**Comment by saubyk** [comment] 2022-09-21 16:23
Hi @kieselbert when you see the routing volume go down, do you also see any uptick on the number of inactive channels on your node?
Also, it might be worthwhile to update to the latest version of LND (0.15.1) and see if you get similar behaviour.

**Comment by saubyk** [comment] 2022-09-21 18:00
>Hm i could update, but I would like to avoid the "restart to announce new channels"-bug.
It might be worthwhile to wait for 0.15.2 to come out, which will fix the issue. Shouldn't be too long.

**Comment by steff123** [comment] 2022-10-06 19:06
Hey, I am on 15.1 and had no forwards for 24h. The node was up for 6 days. I decided to restart the node and had 10 Forwards in the first 30 minutes after the restart.

**Comment by steff123** [comment] 2022-10-07 15:10
@saubyk I beleave it is hard to reproduce for you. Do you have any recommendations what we should log, respectively what we should search the logfile for?

**Comment by kieselbert** [comment] 2022-10-07 15:35
Issue is still present in 0.15.1
I want to add the detail that in the period when the routing decrease, the routing attempts are still there. I observe that with lntop and can see that the routing "requests" are still happen in the same frequent. But most of them failed (without a detail statement). I observed that lntop shows more rounting attempts with the amount of zero (0). This zero routing attempts does not happen after a restart.

**Comment by steff123** [comment] 2022-10-09 19:48
@saubyk 
After a long journey, we found that the circuitbreaker causes the problem and it seems that LinkFailEvents aren't considered in cb probably.

https://github.com/lightningequipment/circuitbreaker/issues/9

**Comment by guggero** [comment] 2022-10-10 07:13
@kieselbert are you running Circuit Breaker as well?

**Comment by kieselbert** [comment] 2022-10-10 12:09
yep, I think the CB caused that issue.

**Comment by guggero** [comment] 2022-10-10 12:16
> yep, I think the CB caused that issue.

Okay, good to know. Closing the issue then as confirmed to be caused by Circuit Breaker in two cases.

**Closed by guggero** 2022-10-10 12:16 UTC
Labels: routing, needs triage
