### ISSUE TITLE
[bug]: race with `funding_locked` and `update_fee`/`update_add_htlc`

### ISSUE THREAD

**Issue by SomberNight** [lightningnetwork/lnd#7401] opened 2023-02-12 23:29 UTC
We have an electrum user who opened [a channel](https://blockstream.info/tx/5312520f35070e7c353377ac84483ffac5fe9d08a006fb2d40d73e64e594f203?output:1) with [`bfx-lnd1`](https://1ml.com/node/03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6).
The channel is using static_remotekey, no anchors.
Immediately after the channel gets opened, the following message exchange happens (electrum logs - `feb12`):
```
20230212T211915.199453Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | >> Sending FUNDING_LOCKED
20230212T211915.200725Z |    DEBUG | lnchannel.Channel.[03f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f521252] | Setting channel state: FUNDED -> OPEN
20230212T211915.228150Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | CHANNEL OPENING COMPLETED (776238x1553x1)
20230212T211915.242947Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | updating fee to bump remote ctn
20230212T211915.243083Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | (chan: 776238x1553x1) current pending feerate 3755. new feerate 3756
20230212T211915.246767Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | >> Sending UPDATE_FEE
20230212T211915.247150Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | send_commitment. chan 776238x1553x1. ctn: 1.
20230212T211915.250417Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | >> Sending COMMITMENT_SIGNED
20230212T211915.907661Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | << Received ERROR
20230212T211915.907861Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | remote peer sent error [DO NOT TRUST THIS MESSAGE]: rejected commitment: commit_height=1, invalid_commit_sig=304402205ffed5b844d11c1b8f5e4be6dfb17287265eef80ffd975195c76ee6a9ff424250220173cd11940a49db06fe524d24fbf7eb9180f93b8117536c78eb7db8904823304, commit_tx=020000000103f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f52125301000000007268e7800161f5ff0000000000160014aec8d8fd4e9bcb41de8f241c4eef3d2a9811e5ece6fa9d20, sig_hash=ff310d4f9219d30ff57064b885d4792314d012fd2c8e6bc5f7d3873ae412b425. chan_id=03f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f521252
```
Based on the error message (and the node alias?), the remote (`bfx-lnd1`) [is likely running lnd](https://github.com/lightningnetwork/lnd/blob/48c8c1bf48ed9be7a014803ea4c3b4624407dcc3/lnwallet/channel.go#L4449), no idea what version though.

Note that electrum is the opener/funder of the channel, and it sends an `update_fee` msg (3755 sat/kw -> 3756 sat/kw) right after `funding_locked`:
```
20230212T211915.243083Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | (chan: 776238x1553x1) current pending feerate 3755. new feerate 3756
```
This is supposed to update the absolute fee for the commitment tx (msat), from `2718 sat` to `2719 sat`:
```py
>>> 3755 * 724 // 1000 * 1000
2718000
>>> 3756 * 724 // 1000 * 1000
2719000
```

The `commit_tx` lnd sends it is checking our sig against:
`commit_tx=020000000103f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f52125301000000007268e7800161f5ff0000000000160014aec8d8fd4e9bcb41de8f241c4eef3d2a9811e5ece6fa9d20`
From that, the fee lnd expects to be paid:
```py
>>> fee=16777215-16774497
>>> fee
2718
```
It looks like lnd is incorrectly still calculating with the old feerate.

The issue seems to be similar to https://github.com/ElementsProject/lightning/issues/3341,
which by the looks of it was worked around in c-lightning in https://github.com/ElementsProject/lightning/pull/3634 - not sure if there was any follow-up to fix the bug in lnd there...
Note that in either case, unlike in many seemingly related issues, there is no disconnection of bolt8 transport, no channel_reestablish is involved.

-----

ref: https://github.com/spesmilo/electrum/issues/8191#issuecomment-1427158299
@ondra-novak

**Comment by SomberNight** [comment] 2023-02-13 00:39
Note that this is not the first time this user had a signature verification failure with the `bfx-lnd1` node.
We have another log from a week ago, where I believe the same underlying issue manifested but later in the flow, due to how onchain fees are rounded.

`feb5` log:
```
20230205T111616.963603Z |    DEBUG | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | Setting channel state: OPENING -> FUNDED
20230205T111616.992508Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | > Sending FUNDING_LOCKED
20230205T111617.002068Z |    DEBUG | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | Setting channel state: FUNDED -> OPEN
20230205T111617.047194Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | CHANNEL OPENING COMPLETED (775134x2404x1)
20230205T111617.047451Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | updating fee to bump remote ctn
20230205T111617.047549Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | (chan: 775134x2404x1) current pending feerate 4144. new feerate 4145
20230205T111617.047688Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | > Sending UPDATE_FEE
20230205T111617.048025Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | send_commitment. chan 775134x2404x1. ctn: 1.
20230205T111617.048110Z |     INFO | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | sign_next_commitment 1
20230205T111617.051997Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | > Sending COMMITMENT_SIGNED
20230205T111617.158960Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | < Received REVOKE_AND_ACK
20230205T111617.159108Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | on_revoke_and_ack. chan 775134x2404x1. ctn: 0
20230205T111617.159178Z |     INFO | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | receive_revocation
20230205T111617.303175Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | saved remote channel_update gossip msg for chan 775134x2404x1

// was expecting "Received COMMITMENT_SIGNED" here...
// ~nothing interesting happens for ~16 mins

20230205T113209.075139Z |     INFO | lnworker.LNWallet.[<anonymized>] | pay_invoice starting session for RHASH=db97e532bed30abb35bb1efd7d5b37d1cc9ef16dc17ca24c3dd484f0ab54b8c5
20230205T113209.076770Z |     INFO | lnworker.LNWallet.[<anonymized>] | trying split configuration: dict_values([[16500000000]]) rating: 2.9416073491689008
20230205T113209.103007Z |     INFO | lnrouter.LNPathFinder | found a path
20230205T113209.107522Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | > Sending UPDATE_ADD_HTLC
20230205T113209.107890Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | send_commitment. chan 775134x2404x1. ctn: 2.
20230205T113209.107964Z |     INFO | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | sign_next_commitment 2
20230205T113209.112608Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | > Sending COMMITMENT_SIGNED
20230205T113209.200555Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | < Received REVOKE_AND_ACK
20230205T113209.200936Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | on_revoke_and_ack. chan 775134x2404x1. ctn: 1
20230205T113209.201172Z |     INFO | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | receive_revocation
20230205T113209.288728Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | < Received COMMITMENT_SIGNED
20230205T113209.289148Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | on_commitment_signed. chan 775134x2404x1. ctn: 1.
20230205T113209.289546Z |     INFO | lnchannel.Channel.[0958ee8fe66a0845149a40418bc707d9f5f87d2f49e2dfed2f42b9958d74ca60] | receive_new_commitment. ctn=1, len(htlc_sigs)=1
20230205T113209.309550Z |    ERROR | lnpeer.Peer.[LNWallet, 03cde60a63-4548f074] | Exception in main_loop: LNProtocolWarning('failed verifying HTLC signatures: UpdateAddHtlc(amount_msat=16500017500, payment_hash=db97e532bed30abb35bb1efd7d5b37d1cc9ef16dc17ca24c3dd484f0ab54b8c5, cltv_expiry=775320, timestamp=1675596729, htlc_id=0) -1, rawtx: cHNidP8BAF4CAAAAARkZDdblT4soHy0QVmhOYi/P6913NREGK2rBnBjiKNjRAQAAAAAAAAAAAXW6+wAAAAAAIgAgjwmmkTMFRdyDGW4EDLvazz452vZ+TnEdRnfoMVX2UkOY1AsAAAEFhXapFJzxs2DxG/L1mnv+CuHt7hEXA9fOh2OsZyECKeVFQY9xQuNI/L2aguwW2JIo7jsDrEq33UMRra/qgjZ8ggEgh2R1UnwhA/gHpxHcf7k8bbtXFaYA7zjZvYmG0L4SSGdMEf4DOJx4Uq5nqRTw+A84BdVQLUGsRsu8B0Tvw5p1s4isaGgBBwAAAA==')
```
As the sat/kw feerate was only increased by 1, the rounded onchain sat fees just happen to match for the first few checks, and the first time they differ is for the electrum-side htlc-timeout tx.
see https://github.com/spesmilo/electrum/issues/8191#issuecomment-1427179147

**Comment by Crypt-iQ** [comment] 2023-02-13 15:28
I know what's going on here. Unfortunately the only thing you can do with older LND nodes is to patch your node to delay sending `update_fee` so it's not immediately after `funding_locked`

**Comment by Crypt-iQ** [comment] 2023-02-13 16:12
The issue occurs when the peer sends `funding_locked` followed by either `update_add_htlc` or `update_fee`. This can happen between LND nodes, so isn't specific to electrum or CLN.

1. The peer sends `funding_locked`. This is handled in a goroutine `handleFundingLocked` here:
https://github.com/lightningnetwork/lnd/blob/8ade1acba31cf6bf803a260e901c1c0fb1520ca9/funding/manager.go#L3547-L3552
2. `AddNewChannel` eventually passes a signal to the `channelManager` goroutine in `peer/brontide.go` here:
https://github.com/lightningnetwork/lnd/blob/8ade1acba31cf6bf803a260e901c1c0fb1520ca9/peer/brontide.go#L2349
3. When the peer sends `update_fee` or `update_add_htlc`, it is handled by the `channelManager` goroutine. The `activeChannels` map is checked to see if the associated channel is known to the `*Brontide` object:
https://github.com/lightningnetwork/lnd/blob/8ade1acba31cf6bf803a260e901c1c0fb1520ca9/peer/brontide.go#L1592-L1594
4. If the `channelManager` hasn't populated the `activeChannels` map yet, the `update_fee` or `update_add_htlc` will be dropped since `isActiveChannel` will return false. This will lead to channel closure.

The fix here isn't so simple. If we were to move `funding_locked` handling so that some "dummy" `ChannelLink` existed, it might fix the issue as the `activeChannels` map would already be populated by the time we received the `update_*`.

**Comment by ondra-novak** [comment] 2023-02-13 18:34
My opinion is that it's a nasty race-condition bug. It should be handled consistently. If an update can appear for a channel not yet established. the request should not be discarded. There are possible solutions
- "try again later" message or error (I understand that there may not be such a thing)
- register the request in some temporary container and process all registered requests as soon as the channel is established.

**Comment by SomberNight** [comment] 2023-02-14 09:02
Thank you for the quick investigation @Crypt-iQ!

> Unfortunately the only thing you can do with older LND nodes is to patch your node to delay sending update_fee so it's not immediately after funding_locked

I had tried several times and could not reproduce the bug on regtest, before opening this report. (Though I guess I could retest now with your explanation, with modified code that sends a state update even faster after funding_locked.) One would think not having network latency would have made it more likely to trigger it.

However, my question is, how long do you think one should wait to comfortably avoid the race? Does the time heavily depend on the CPU/disk load of the machine, making it longer for extremely busy nodes? That could explain why it happens so frequently with the bfx node but we haven't seen it with other lnd nodes.

**Comment by Crypt-iQ** [comment] 2023-02-14 14:07
> However, my question is, how long do you think one should wait to comfortably avoid the race? Does the time heavily depend on the CPU/disk load of the machine, making it longer for extremely busy nodes? That could explain why it happens so frequently with the bfx node but we haven't seen it with other lnd nodes.

Depends on network latency and load on the LND machine. So I can't give you a good estimate here. If a machine is crawling, maybe a minute?

**Comment by tony-voltage** [comment] 2023-02-15 21:35
Since my other issue was closed instantly, I'll go ahead and provide another point on why this is a really nasty bug like others have mentioned.

For 0 conf channels, there shouldn't be a reason to "maybe wait 1 minute" like @Crypt-iQ is suggesting. LND should not be force closing channels like this and it really kills the whole reason 0 conf exists, which at this point seems like a rushed and untested feature after many months of working on this across multiple lightning implementations. This isn't a problem with other implementations and I would like to see a little more urgency than some release that's slated for maybe the end of the year.

**Comment by Roasbeef** [comment] 2023-02-15 22:01
> Since my other issue was closed instantly,

Your issue was closed as we're tracking this issue here to avoid duplicate issue in the tracker (this issue also has a more precise title as well). As mentioned above, we've traced the root cause down to a race condition (the channel isn't "up" by the time the `update_fee` message is sent). We did in fact test this feature with all the other major implementations, but didn't run into this during that phase. 

We're now working on identifying a solid fix, in addition to some of the fixes identified above.

**Comment by ondra-novak** [comment] 2023-02-17 22:02
Just update. According to bitfinex, the node in question is LND 0.15.4-beta commit=v0.15.4-beta

**Comment by Roasbeef** [comment] 2023-02-17 23:37
Suggested fix:
  * When we go check to see if a message [is for an active channel](https://github.com/lightningnetwork/lnd/blob/master/peer/brontide.go#L1592-L1594), we should ask the funding manager in a concurrent safe manner if this is a channel that is _soon_ to be active (today we only ask channels in the link). 
  * In the funding manger, [right before we send funding locked](https://github.com/lightningnetwork/lnd/blob/master/funding/manager.go#L2880-L2888), we should add the _channel ID_ to a map of soon to be active channels. 

The end result of the above is that because we'll mark as channel is "ready soon" _before_ we send a funding locked, if the remote party sends funding locked then a state update immediately, the message will be queued in the normal `chanMsgStream` to be consumed by the local channel link once it fully propagates. The issue today is that while a channel link is propagating (internal async interaction), we might get their funding locked and an update, with the updating being dropped if arrives soon afterwards.

**Closed** 2023-08-09 00:10 UTC
Labels: bug, p2p, interop, force closes
