### ISSUE TITLE
[bug]: watchtower server unable to handle state update

### ISSUE THREAD

**Issue by bitromortac** [lightningnetwork/lnd#7468] opened 2023-02-28 10:37 UTC
### Background
I'm using a watchtower server and client pair for development, which is why the client is often restarted. The server has been offline as well for some time, which is why I think they somehow become unsynced.

`lncli wtclient towers` was empty, so I added a new tower/session. The session seemed to be added correctly, I have `"num_sessions_acquired": 2`.

The server shows some logs:
```
[INF] WTWR: Accepted incoming peer SESSION@127.0.0.1:49498
[ERR] WTWR: Unable to handle CreateSession from SESSION: connection with SESSION failed with code=CreateSessionCodeAlreadyExists
[INF] WTWR: Releasing incoming peer SESSION@127.0.0.1:49498
```
I also see those lines:
```
[INF] WTWR: Accepted incoming peer SESSION@127.0.0.1:41614
[ERR] WTWR: Unable to handle StateUpdate from SESSION: connection with SESSION failed with code=StateUpdateCodeClientBehind
[INF] WTWR: Releasing incoming peer SESSION@127.0.0.1:41614
```

It would be great to know how to get out of this state, perhaps adding a command that lets one remove sessions from the client and/or the server would help.

### Your environment
* server: `lnd v0.15.5-beta`
* client: `lnd v0.16.0-rc`

**Comment by saubyk** [comment] 2023-03-02 16:16
cc: @ellemouton

**Comment by ellemouton** [comment] 2023-03-06 06:10
just making a note that another user from slack also ran into the `StateUpdateCodeClientBehind` error: 
```
2023-03-05 22:02:48.100 [WRN] WTCL: (anchor) SessionQueue(02e873cf0d9f3e93b1910fdc5344ae7b60e14f8d12c9560b38adefbfd17675bd51) unable to upload state update to tower=02b759a578157393d2a70444ff9204f2ca5c0c0dfac01d0873f1b0d57f090685c1@116.202.17.127:9911: received error code StateUpdateCodeClientBehind in StateUpdateReply for seqnum=1
2023-03-05 22:02:48.100 [ERR] WTCL: (anchor) SessionQueue(02e873cf0d9f3e93b1910fdc5344ae7b60e14f8d12c9560b38adefbfd17675bd51) unable to send state update: received error code StateUpdateCodeClientBehind in StateUpdateReply for seqnum=1
```

**Comment by ellemouton** [comment] 2023-03-06 06:12
I think currently these non-OK statuses are completely unhandled in the tower client. So need to:
1. Find out what could be the cause of these errors
2. Implement a recovery (either auto recovery or allow user to force recovery)

**Comment by ellemouton** [comment] 2023-03-31 15:27
fixed in https://github.com/lightningnetwork/lnd/pull/7541 :)

**Closed by ellemouton** 2023-03-31 15:27 UTC
Labels: bug, watchtower
