### ISSUE TITLE
Nice to have feature request - LND - Connecting to peer

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2036] opened 2018-10-11 18:05 UTC
### Background

Peer connection attempts don't succeed due to either peer not fully synced or for other reasons. If these reasons are errors they are provided as a json string as a response to a rest api query. Other times, when an attempt to connect to peer at the network level itself was successful, but the end result was that peer didn't respond within 5 seconds, such messages are reported as "info". Example of one such is 
2018-10-11 17:16:29.638 [INF] SRVR: Established connection to: [2601:648:8004:acf0:xxxx:xxxx:xxxx:xxxx]:9735
2018-10-11 17:16:29.639 [INF] SRVR: Finalizing connection to 0381c58b1cd7a10642c716a9a6b206fa82e6b25a3e2ceb0638edcaa0fabffe0324, inbound=false
no json[error] found  {
}  and value =  {
}
2018-10-11 17:16:44.644 [INF] PEER: Disconnecting [2601:648:8004:acf0:xxxx:xxxx:xxxx:xxxx]:9735, reason: unable to start peer: peer did not complete handshake within 5 seconds
2018-10-11 17:16:44.645 [INF] DISC: Removing gossipSyncer for peer=0381c58b1cd7a10642c716a9a6b206fa82e6b25a3e2ceb0638edcaa0fabffe0324
### Your environment

* version of `lnd` : 0.5 beta
* which operating system (`uname -a` on *Nix) --- ios
* version of `btcd`, `bitcoind`, or other backend --- btcd

### Steps to reproduce

Having started two LND instances, try peer connection and if one of the peer is not ready, you will see these informational logs

### Expected behaviour

It would be ideal if LND reported these in ListPeers for the peer in question. 

### Actual behaviour

These are informational messages at this time. Even when listing peers, if there are no peers , no information can be gleaned about the status of a connection.

**Comment by wpaulino** [comment] 2018-10-11 22:48
If I understand correctly, you'd like an RPC that displays all pending peer connection states? If so, this has already been requested in https://github.com/lightningnetwork/lnd/issues/555.

**Comment by weaklysubjective** [comment] 2018-10-12 04:11
Hi Wilmer, I think #555 accurately reflects my request. A rest endpoint to query peer connect status and if error then to return error. End user apps can execute handlers or timers accordingly.  Thank you for your response.

**Comment by wpaulino** [comment] 2018-10-12 19:51
Cool, closing as a duplicate of #555 then.

**Closed by wpaulino** 2018-10-12 19:51 UTC
