### ISSUE TITLE
[feature]: Read wallet-unlock-password-file before opening the main database

### ISSUE THREAD

**Issue by feikede** [lightningnetwork/lnd#8107] opened 2023-10-22 10:55 UTC
### Background

I create a password file tmp in shared mem. I want to remove the password file after LND starts. Bug: Time between startup and wallet unlock by file can not be estimated because of database compaction. Log:

2023-10-22 12:40:16.602 [INF] LTND: Version: 0.16.4-beta commit=v0.16.4-beta, build=production, logging=default, debuglevel=CNCT=warn,CRTR=warn,HSWC=warn,NTFN=warn,RPCS=warn
2023-10-22 12:40:16.602 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2023-10-22 12:40:16.635 [INF] LTND: Opening the main database, this might take a few minutes...
...
2023-10-22 12:40:45.193 [INF] LTND: Database(s) now open (time_to_open=28.557644775s)!
2023-10-22 12:40:45.193 [INF] LTND: Attempting automatic wallet unlock with password provided in file
2023-10-22 12:40:47.583 [INF] LNWL: Opened wallet
2023-10-22 12:40:48.097 [INF] CHRE: Primary chain is set to: bitcoin

It's 30 secs in this example, but that time is unreliable. In my start script I have:

  ExecStartPre=+/root/wallet-unlock.py
  ExecStart=/usr/local/bin/lnd --wallet-unlock-password-file=/dev/shm/lndpass
  ExecStartPost=/bin/sleep 30
  ExecStartPost=+rm -f /dev/shm/lndpass

Please read the provided password file into mem before opening the main database. Then a sleep 5 would always work.
Thanks.

### Your environment
0.16.4-beta 
Linux 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux
btc-core

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

That's simple.

### Expected behaviour

Please read the provided password file before opening the main database.

### Actual behaviour

Password file is read after an unreliable amount of secs.

**Comment by ViktorTigerstrom** [comment] 2023-10-23 09:37
Hi @feikede, thanks for the issue report! 
It's currently intended behaviour that the wallet is unlocked after the database has been opened. This is as the we need the `btcwallet.LoaderOption` + `MacaroonDB` while unlocking the wallet, and both are fetched when opening database.

I'm therefore editing this issue report to be a feature request rather then a bug report, as the current process is intended behaviour.

**Comment by guggero** [comment] 2023-10-23 09:43
As @ViktorTigerstrom has already pointed out, the startup sequence of subsystems within `lnd` cannot just be changed around without having an impact on other things.
To make your script more robust, one alternative would be to use a FIFO pipe instead of a file, then deleting that pipe is low priority as it wouldn't contain the password anymore. See an example here: https://github.com/lightninglabs/lndinit#5-store-the-wallet-password-in-a-file

**Comment by feikede** [comment] 2023-10-23 13:16
@guggero Thanks for the pipe - hint, works for me.

**Comment by ViktorTigerstrom** [comment] 2023-10-23 14:14
Great to hear that the solution provided by @guggero satisfies your needs @feikede! Closing the issue given that the requested feature isn't needed any longer.

**Closed by ViktorTigerstrom** 2023-10-23 14:14 UTC
Labels: enhancement, wallet, feature request, needs triage
