### ISSUE TITLE
LND channel is stuck in "Waiting Closed" with funds visible on chain still in opening txn

### ISSUE THREAD

**Issue by sfmcnally** [lightningnetwork/lnd#6370] opened 2022-03-25 17:56 UTC
### Background

I have a channel stuck in waiting closed 
{
    "total_limbo_balance": "***",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "****",
                "channel_point": "***:1",
                "capacity": "***",
                "local_balance": "***",
                "remote_balance": "1",
                "local_chan_reserve_sat": "***",
                "remote_chan_reserve_sat": "***",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator"
            },
            "limbo_balance": "***",
            "commitments": {
                "local_txid": "****",
                "remote_txid": "***",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "1426",
                "remote_commit_fee_sat": "1426",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
}

The other node appears to be online, and force closing does not work. The funds are sitting on chain, but are locked in the channel still. Is there a way I can manually broadcast a commit txn from the database or rebroadcast the closing transaction. The channel was closed several days ago along with several others that closed just fine. Perhaps the error was introduced by closing too many channels at once. 

### Your environment

* lnd v0.14.2-beta
* Umbrel
* bitcoind v22.0.0
* any other relevant environment details

### Steps to reproduce

Not sure, just closed the channel, along with several others, perhaps closing too many channels at once triggers this error?

### Expected behaviour

Channel Closes

### Actual behaviour

Channel is stuck in Waiting Closed

**Comment by alexbosworth** [comment] 2022-03-25 18:34
Any log activity associated with force closing attempt? If you force close is there a specific error returned?

**Comment by sfmcnally** [comment] 2022-03-25 19:16
> Any log activity associated with force closing attempt? If you force close is there a specific error returned?

There's nothing in the log about the force close attempt. Here's the last log entry that references that channel:

ChannelPoint(16cf151ff3a6d0e80c4c3e168a3f3b504355639012f292986da62df88ca94508:1)
2022-03-24 05:59:56.577 [WRN] PEER: ChannelPoint(16cf151ff3a6d0e80c4c3e168a3f3b504355639012f292986da62df88ca94508:1) has status ChanStatusCoopBroadcasted|ChanStatusLocalCloseInitiator, won't start.

**Comment by sfmcnally** [comment] 2022-03-25 19:20
> I think you attempted to co-op close, and then the peer cycled out. We're fixing an issue related to resuming that in 0.15, but for now you'll need to force close the channel.

Force closing the channel returns nothing. See below. Is this the normal behavior when you force close? I seem to remmber some output with a txid in the past. 

umbrel@umbrel:~/umbrel/bin $ ./lncli closechannel --force 16cf151ff3a6d0e80c4c3e168a3f3b504355639012f292986da62df88ca94508:0
umbrel@umbrel:~/umbrel/bin $ ./lncli closechannel --force 16cf151ff3a6d0e80c4c3e168a3f3b504355639012f292986da62df88ca94508
umbrel@umbrel:~/umbrel/bin $ ./lncli closechannel --force 16cf151ff3a6d0e80c4c3e168a3f3b504355639012f292986da62df88ca94508:1
umbrel@umbrel:~/umbrel/bin $

**Comment by sfmcnally** [comment] 2022-03-25 19:24
Nothing new in the log after the force close attempts either. I would let it go if it wasn't 3 million sats. Kind of need to figure out how to manually broadcast one of the presigned txns.

**Comment by alexbosworth** [comment] 2022-03-25 19:25
guggero chantools could potentially be used to get the raw commitment tx out of the database but it's not normal to not be able to force close so maybe that could be figured out

**Comment by sfmcnally** [comment] 2022-03-25 19:30
> guggero chantools could potentially be used to get the raw commitment tx out of the database but it's not normal to not be able to force close so maybe that could be figured out

This would close all my channels though, correct? Not just the faulty one?

**Comment by alexbosworth** [comment] 2022-03-25 19:31
> This would close all my channels though, correct? Not just the faulty one?

It can close just a single channel, but I'd only use this as a last resort. Another approach is have the other side force close?

**Comment by sfmcnally** [comment] 2022-03-25 19:35
I messaged the other node operator using Thunderhub. We will see if they respond.

**Comment by alexbosworth** [comment] 2022-03-25 19:37
If it's a node associated with https://www.getzion.com/ you could also contact them through other channels

**Comment by sfmcnally** [comment] 2022-03-25 21:18
Thanks, I reached out on twitter.

**Comment by sfmcnally** [comment] 2022-03-26 23:54
I didn't hear back but was able to get the raw force close transaction out of chantools and manually broadcast it. Should I leave this issue open or close it? It isn't fixed, but it is resolved for me.

**Comment by guggero** [comment] 2022-03-28 11:43
I think your `lncli closechannel` command was incorrect. It's `lncli closechannel --force <txid> <index>` (with a space) instead of `lncli closechannel --force <txid>:<index>` (with a colon).

But good you were able to resolve the issue manually.
The underlying cause of this is a duplicate of https://github.com/lightningnetwork/lnd/issues/5841 and https://github.com/lightningnetwork/lnd/issues/4819, so closing this one.

**Closed by guggero** 2022-03-28 11:43 UTC
