### ISSUE TITLE
abandonchannel zombie dev build

### ISSUE THREAD

**Issue by TheCHGoon** [lightningnetwork/lnd#3072] opened 2019-05-12 13:27 UTC
### Background

After restoring from seed i was trying to update the feepolicy for my channels.
seems this is impossible since some old zombie is guarding the gate.

### Your environment
* version of `lnd`
v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b
* which operating system 
Ubuntu 18.04.2 LTS
* version of `btcd`, `bitcoind`, or other backend
bitcoind 0.18.0
* any other relevant environment details
go version go1.12.3 linux/arm

last 2 lines in .bashrc
export GOPATH=~/gocode
export PATH=$PATH:$GOPATH/bin

### Steps taken

$ lncli updatechanpolicy --base_fee_msat 478 --fee_rate 1 --time_lock_delta 14
[lncli] rpc error: code = Unknown desc = Channel from self node has no policy

$ lncli feereport
[lncli] rpc error: code = Unknown desc = no policy for outgoing channel 598078250466476032

$ lncli abandonchannel 2a00c8d2e392cbf20f9175f2ebb72dd1f8d522547cf5b3d01725446a08776e59:0
[lncli] rpc error: code = Unknown desc = AbandonChannel RPC call only available in dev builds

$ cd $GOPATH/src/github.com/lightningnetwork/lnd
$ export PATH=$PATH:/usr/local/go/bin
$ git pull
Already up to date.
$ make clean && make && make build

Cleaning source.
rm -f ./lnd-debug ./lncli-debug
rm -f ./lnd-itest ./lncli-itest
rm -f -r ./vendor .vendor-new
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b" github.com/lightningnetwork/lnd/cmd/lnd
GO111MODULE=on go build -v -tags="dev" -o lncli-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b" github.com/lightningnetwork/lnd/cmd/lncli
 Building debug lnd and lncli.
GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b" github.com/lightningnetwork/lnd/cmd/lnd
GO111MODULE=on go build -v -tags="dev" -o lncli-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b" github.com/lightningnetwork/lnd/cmd/lncli

$ lnd
2019-05-12 13:23:18.359 [INF] LTND: Version: 0.6.1-beta commit=v0.6.1-beta-rc1, build=production, logging=default

in new terminal
$ lncli unlock
lnd successfully unlocked!

$  lncli abandonchannel 2a00c8d2e392cbf20f9175f2ebb72dd1f8d522547cf5b3d01725446a08776e59:0
[lncli] rpc error: code = Unknown desc = AbandonChannel RPC call only available in dev builds

### Expected behaviour

expected to remove the zombie and restore lncli functionality

### Actual behaviour
RPC call only available in dev builds

### what am i missing?

**Comment by vegardengen** [comment] 2019-05-12 14:21
You need to go into the source directory and start lnd with **./lnd-debug**

Then, abandonchannel will work.

Do a **which lnd** to show which version you are running typing only **lnd**

**Comment by TheCHGoon** [comment] 2019-05-12 16:05
thank you for the fast reply.

Ok that starts lnd in devbuild
$ ./lnd-debug
[INF] LTND: Version: 0.6.1-beta commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b, build=development, logging=default

however when i check:
$ lncli feereport i get the expected: 
rpc error: code = Unknown desc = no policy for outgoing channel 598078250466476032

so i run: 
$ lncli getchaninfo 598078250466476032
2a00c8d2e392cbf20f9175f2ebb72dd1f8d522547cf5b3d01725446a08776e59:0

expecting to solve this with:
$ lncli abandonchannel --funding_txid 2a00c8d2e392cbf20f9175f2ebb72dd1f8d522547cf5b3d01725446a08776e59
[lncli] rpc error: code = Unknown desc = channel not found

this zombie seems hard to kill -.-

**Comment by molxyz** [comment] 2019-05-12 16:47
@TheCHGoon  it seems you need the ` --output_index`?  Try it again: 
```
lncli abandonchannel --funding_txid 2a00c8d2e392cbf20f9175f2ebb72dd1f8d522547cf5b3d01725446a08776e59 --output_index 0
```

**Comment by TheCHGoon** [comment] 2019-05-12 16:59
unfortunately it returns the same result
$ lncli abandonchannel --funding_txid 2a00c8d2e392cbf20f9175f2ebb72dd1f8d522547cf5b3d01725446a08776e59 --output_index 0
[lncli] rpc error: code = Unknown desc = channel not found

**Comment by wpaulino** [comment] 2019-05-13 19:02
You're unable to use `abandonchannel` because the issue that you're running into is related to the channel graph, not your channel state. Closing this as a duplicate of https://github.com/lightningnetwork/lnd/issues/2911.

**Closed by wpaulino** 2019-05-13 19:02 UTC
