### ISSUE TITLE
LND cant start anymore 'runtime: out of memory' Raspberry Pi 3

### ISSUE THREAD

**Issue by UnholyLizard** [lightningnetwork/lnd#1036] opened 2018-04-06 06:47 UTC
### Background

By 'RaspiBollt' tutorial get worked 0.4.0 LND on testnet.

Possible after not correctly shutdown (weak/bad power supply on RaspPi or external HDD or both) LND can't start after wallet unlock.

Upgrade to 0.4.1 beta didn't help.

Bitcoind fully synced.

Memory usage:
```
              total        used        free      shared  buff/cache   available
Mem:           976M        101M        818M        1.0M         56M        826M
Swap:          2.0G        380M        1.6G

```

After LN unlock:
```
Apr 04 23:42:41 SkyCry lnd[6528]: 2018-04-04 23:42:41.766 [INF] LNWL: The wallet has been unlocked without a time limit
Apr 04 23:42:41 SkyCry lnd[6528]: 2018-04-04 23:42:41.766 [INF] LTND: LightningWallet opened
Apr 04 23:44:20 SkyCry lnd[6528]: runtime: out of memory: cannot allocate 374341632-byte block (1032159232 in use)
Apr 04 23:44:20 SkyCry lnd[6528]: fatal error: out of memory
Apr 04 23:44:20 SkyCry lnd[6528]: runtime stack:
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.throw(0x8c7f9c, 0xd)
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/panic.go:619 +0x60
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.largeAlloc(0x16500000, 0x60101, 0x76f39000)
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/malloc.go:828 +0xdc
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.mallocgc.func1()
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/malloc.go:721 +0x38
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.systemstack(0x0)
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/asm_arm.s:349 +0x80
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.mstart()
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/proc.go:1170
Apr 04 23:44:20 SkyCry lnd[6528]: goroutine 84 [running]:
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.systemstack_switch()
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/asm_arm.s:294 +0x4 fp=0x12f4ac54 sp=0x12f4ac50 pc=0x68c0c
Apr 04 23:44:20 SkyCry lnd[6528]: runtime.mallocgc(0x16500000, 0x81f080, 0x4282a601, 0x179f4)
Apr 04 23:44:20 SkyCry lnd[6528]:         /usr/local/go/src/runtime/malloc.go:720 +0x86c fp=0x12f4acb4 sp=0x12f4ac54 pc=0x21130
Apr 04 23:44:21 SkyCry systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 04 23:44:21 SkyCry systemd[1]: lnd.service: Unit entered failed state.
Apr 04 23:44:21 SkyCry systemd[1]: lnd.service: Failed with result 'exit-code'.
```
Memory usage at time around error:
```
              total        used        free      shared  buff/cache   available
Mem:           976M        916M         39M        672K         20M         25M
Swap:          2.0G        596M        1.4G
```

### Environment

* `lnd version 0.4.1-beta commit=`
* `Linux SkyCry 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux`
* `Bitcoin Core Daemon version v0.16.0`

bitcoin.conf:
```
# RaspiBolt LND Mainnet: bitcoind configuration
# /home/bitcoin/.bitcoin/bitcoin.conf

# remove the following line to enable Bitcoin mainnet
testnet=1

# Bitcoind options
server=1
daemon=1
txindex=1
disablewallet=1

# Connection settings
rpcuser=*
rpcpassword=*
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000

# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000
```

lnd.conf:
```
# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=trace
debughtlc=true
maxpendingchannels=5
alias=Lightning-Moon
color=#640d89

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
bitcoin.testnet=1
#bitcoin.mainnet=1

bitcoin.node=bitcoind

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6
```

If I need to provide you more information, please keep in mind I'm not very good with Linux.

**Comment by Roasbeef** [comment] 2018-04-06 06:52
> Apr 04 23:44:20 SkyCry lnd[6528]: runtime: out of memory: cannot allocate 374341632-byte block (1032159232 in use)

Looks like you might need to allocate some swap to the system. The initial `scrypt` on start up can be a bit memory intensive, but the memory will quickly be released once key derivation is finished.

**Comment by Roasbeef** [comment] 2018-04-06 06:53
Which version of Go are you running? 

Actually looking at the mem report, you shoud definitely have enough: 
```
              total        used        free      shared  buff/cache   available
Mem:           976M        916M         39M        672K         20M         25M
Swap:          2.0G        596M        1.4G
```

**Comment by UnholyLizard** [comment] 2018-04-06 09:52
At that time I did not have Go, but now I have `go version go1.10.1 linux/arm`

**Comment by Roasbeef** [comment] 2018-04-06 18:37
If you manually compile from master, and re-attempt are results different?

**Comment by UnholyLizard** [comment] 2018-04-06 20:53
`lnd version 0.4.1-beta commit=e30881a14cdd5d9f17132acc99dd46d331f6f61f`

The same sesults:

```
Apr 06 23:34:22 SkyCry lnd[21619]: 2018-04-06 23:34:22.484 [INF] LTND: Version 0.4.1-beta commit=e30881a14cdd5d9f17132acc99dd46d331f6f61f
Apr 06 23:34:22 SkyCry lnd[21619]: 2018-04-06 23:34:22.485 [INF] LTND: Active chain: Bitcoin (network=testnet)
Apr 06 23:34:22 SkyCry lnd[21619]: 2018-04-06 23:34:22.608 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
Apr 06 23:34:22 SkyCry lnd[21619]: 2018-04-06 23:34:22.661 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
Apr 06 23:34:22 SkyCry lnd[21619]: 2018-04-06 23:34:22.661 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
Apr 06 23:34:22 SkyCry lnd[21619]: 2018-04-06 23:34:22.662 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
Apr 06 23:42:40 SkyCry lnd[21619]: 2018-04-06 23:42:40.121 [INF] LNWL: Opened wallet
Apr 06 23:42:40 SkyCry lnd[21619]: 2018-04-06 23:42:40.550 [INF] LTND: Primary chain is set to: bitcoin
Apr 06 23:42:40 SkyCry lnd[21619]: 2018-04-06 23:42:40.550 [INF] LTND: Initializing bitcoind backed fee estimator
Apr 06 23:42:46 SkyCry lnd[21619]: 2018-04-06 23:42:46.807 [INF] LNWL: Opened wallet
Apr 06 23:42:47 SkyCry lnd[21619]: 2018-04-06 23:42:46.864 [INF] LNWL: Started listening for blocks via ZMQ on tcp://127.0.0.1:29000
Apr 06 23:42:53 SkyCry lnd[21619]: 2018-04-06 23:42:53.040 [INF] LNWL: The wallet has been unlocked without a time limit
Apr 06 23:42:53 SkyCry lnd[21619]: 2018-04-06 23:42:53.040 [INF] LTND: LightningWallet opened
Apr 06 23:43:52 SkyCry lnd[21619]: runtime: out of memory: cannot allocate 374341632-byte block (968163328 in use)
Apr 06 23:43:52 SkyCry lnd[21619]: fatal error: out of memory
Apr 06 23:43:52 SkyCry lnd[21619]: runtime stack:
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.throw(0x8c94f7, 0xd)
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/panic.go:616 +0x60
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.largeAlloc(0x16500000, 0x60101, 0x76dc06c8)
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/malloc.go:828 +0xdc
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.mallocgc.func1()
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/malloc.go:721 +0x38
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.systemstack(0x0)
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/asm_arm.s:349 +0x80
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.mstart()
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/proc.go:1175
Apr 06 23:43:52 SkyCry lnd[21619]: goroutine 33 [running]:
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.systemstack_switch()
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/asm_arm.s:294 +0x4 fp=0x12c5fc54 sp=0x12c5fc50 pc=0x6a1ac
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.mallocgc(0x16500000, 0x8200f0, 0x19101, 0x193c8)
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/malloc.go:720 +0x89c fp=0x12c5fcb4 sp=0x12c5fc54 pc=0x22b68
Apr 06 23:43:52 SkyCry lnd[21619]: runtime.newarray(0x8200f0, 0x440000, 0x2613dbc0)
Apr 06 23:43:52 SkyCry lnd[21619]:         /usr/local/go/src/runtime/malloc.go:855 +0x5c fp=0x12c5fcc8 sp=0x12c5fcb4 pc=0x22e64
Apr 06 23:43:55 SkyCry systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 06 23:43:55 SkyCry systemd[1]: lnd.service: Unit entered failed state.
Apr 06 23:43:55 SkyCry systemd[1]: lnd.service: Failed with result 'exit-code'.
```

Also `make check` returned some `FAIL`s 
[make_check.txt](https://github.com/lightningnetwork/lnd/files/1885538/make_check.txt)

**Comment by Roasbeef** [comment] 2018-04-06 21:09
If you increase your swap to say, 4G are the result any different? 

This is odd as I run an lnd node a btcd node, and several other services on a box with only 1GB of RAM, yet have no issues.

**Comment by UnholyLizard** [comment] 2018-04-07 15:34
4G swap do not help.

Looks like `wallet.db` is somehow broken. What is its normal size? My is 146MB..
Got `lnd` + `bitcoind` on windows desktop and fed it that `wallet.db`. Unlock wallet and `lnd` very fast get all memory it can (up to 30Gb including swap). `wallet.db` very fast grew to 256MB. System gets huge lags, `lnd` "worked" about 10 min and finally crashed.

```
2018-04-07 17:43:55.963 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
2018-04-07 17:44:12.330 [INF] LNWL: Opened wallet
2018-04-07 17:44:12.391 [INF] LTND: Primary chain is set to: bitcoin
2018-04-07 17:44:12.392 [INF] LTND: Initializing bitcoind backed fee estimator
2018-04-07 17:44:13.153 [INF] LNWL: Opened wallet
2018-04-07 17:44:14.157 [INF] LNWL: Started listening for blocks via ZMQ on tcp://127.0.0.1:18501
2018-04-07 17:44:14.897 [INF] LNWL: The wallet has been unlocked without a time limit
2018-04-07 17:44:14.897 [INF] LTND: LightningWallet opened
2018-04-07 17:55:00.582 [DBG] LNWL: Filtering block 1291878 (0000000000000490dd50c3bdce8746e00213d1cc5940a4d841060791ee3be549) with 47 transactions

```

**Comment by Roasbeef** [comment] 2018-04-07 22:40
> Unlock wallet and lnd very fast get all memory it can (up to 30GB including swap). wallet.db very fast grew to 256MB. System gets huge lags, lnd "worked" about 10 min and finally crashed:

There must be something peculiar with your set up, I run `lnd` on machines that have _much_ less RAM and don't run into any issues during start up or operation. Note that `wallet.db` isn't the only database that `lnd` uses, if you swap that one out, but don't also move the others, then you may run into issues during startup.

**Comment by UnholyLizard** [comment] 2018-04-08 07:05
> Note that wallet.db isn't the only database that lnd uses, if you swap that one out, but don't also move the others, then you may run into issues during startup.

Well actually before I copy `wallet.db` to my windows machine I created new wallet there, so I though all necessary files were there. Never mind, when copied all files from raspi `lnd` dir to the windows one nothing is changed: unlock wallet -> `lnd` eats all memory -> system lags -> `lnd` die.

**Comment by Roasbeef** [comment] 2018-04-09 20:04
Can you reproduce this with a _fresh_ installation?

**Comment by Roasbeef** [comment] 2018-04-09 20:04
If you activate profiling, then attempt with the original `wallet.db`, what shows up in the CPU trace?

**Comment by resdat** [comment] 2018-04-11 19:03
I ran out of memory on my Raspberry Pi a while back, and had this same issue, even after adding swap. The way I cleared it was to kill all lnd created files (in my case in the ~/.lnd directory), and then it runs fine with 2GB of swap. Here is my current memory with lnd and bitcoind running.

              total        used        free      shared  buff/cache   available
Mem:         949580      524596       26868       35492      398116      335764
Swap:       2047996       44604     2003392

**Comment by UnholyLizard** [comment] 2018-04-14 05:30
> Can you reproduce this with a fresh installation?

I made a new RasPi installation on a separate SD card. I created a **new** wallet, and everything still works. Tried to use an **old** wallet here and receive exectly the same error as in the opened message.

On Windows10 desktop I have the same thing, a **new** wallet from RaspPi works and the **old** one does not.

> If you activate profiling, then attempt with the original wallet.db, what shows up in the CPU trace?

Yes I know some words)) Actually I do not know what I do but here is screen.. 
![2018-04-13_200317](https://user-images.githubusercontent.com/37688772/38764719-d04a6abc-3fbc-11e8-89c5-db1bf5192551.png)

I think we're just wasting time here. I can provide this file if someone is interested (it's testnet with a random password).

**Comment by biscottigelato** [comment] 2018-05-05 18:55
I see a very similar signature running on iOS. Not sure if I should open a different issue over this. I also suspect this has something to do with improper shutdowns. I occasionally hit 'out of memory' upon unlocking the wallet after an improper LND shutdown. But if I restart LND then I might be able to recover again. The probability of hitting this is much higher on iPhone 5S (1GB memory) vs iPhone X (3GB memory). This is master commit 4ab2bba5c7bad9f1b1b7d7c9855e0e82194cab6a (dated April 27th)

`2018-05-05 09:10:33.649 [WRN] LTND: open /var/mobile/Containers/Data/Application/CDA6EA8C-F993-4A99-B82B-DD2B94636787/Library/Application Support/lnd/lnd.conf: no such file or directory
2018-05-05 09:10:33.650 [INF] LTND: Version 0.4.1-beta commit=
2018-05-05 09:10:33.651 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-05-05 09:10:33.972 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2018-05-05 09:10:34.843 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-05-05 09:10:34.846 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-05-05 09:10:34.846 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
2018-05-05 09:10:39.989 [INF] LNWL: Opened wallet
2018-05-05 09:10:40.354 [INF] LTND: Primary chain is set to: bitcoin
2018-05-05 09:10:40.547 [INF] BTCN: Loaded 1052 addresses from file '/var/mobile/Containers/Data/Application/CDA6EA8C-F993-4A99-B82B-DD2B94636787/Library/Application Support/lnd/data/chain/bitcoin/testnet/peers.json'
2018-05-05 09:10:40.551 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me
2018-05-05 09:10:40.551 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host
2018-05-05 09:10:40.552 [INF] CMGR: 50 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de
2018-05-05 09:10:40.769 [INF] BTCN: New valid peer 159.203.125.125:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
2018-05-05 09:10:40.779 [INF] BTCN: Syncing to block height 1296416 from peer 159.203.125.125:18333
2018-05-05 09:10:47.754 [INF] LNWL: Opened wallet
runtime: out of memory: cannot allocate 268435456-byte block (274825216 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x101447e42, 0xd)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x5c
runtime.largeAlloc(0x10000000, 0x100a50101, 0x105158000)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/malloc.go:828 +0xec
runtime.mallocgc.func1()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/malloc.go:721 +0x3c
runtime.systemstack(0x100000000)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_arm64.s:229 +0x8c
runtime.mstart()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:1170

goroutine 90 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_arm64.s:178 +0x8 fp=0x10e358f60 sp=0x10e358f50 pc=0x100a591c0
runtime.mallocgc(0x10000000, 0x1012d1400, 0x1, 0x10e82c000)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/malloc.go:720 +0x760 fp=0x10e359010 sp=0x10e358f60 pc=0x100a17098
runtime.makeslice(0x1012d1400, 0x4000000, 0x4000000, 0x10e82c000, 0x200, 0x200)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/slice.go:61 +0x74 fp=0x10e359040 sp=0x10e359010 pc=0x100a45f0c
github.com/biscottigelato/SwiftLightning/vendor/github.com/btcsuite/golangcrypto/scrypt.Key(0x10e45e078, 0x8, 0x8, 0x10e740fc8, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/btcsuite/golangcrypto/scrypt/scrypt.go:235 +0xd0 fp=0x10e359100 sp=0x10e359040 pc=0x100c2cde8
github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/snacl.(*SecretKey).deriveKey(0x10e740fc0, 0x10e359970, 0x10e48c2a0, 0x100c3fa70)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/snacl/snacl.go:114 +0x6c fp=0x10e3591a0 sp=0x10e359100 pc=0x100c2d504
github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/snacl.(*SecretKey).DeriveKey(0x10e740fc0, 0x10e359970, 0x10e506000, 0x10e359230)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/snacl/snacl.go:201 +0x28 fp=0x10e359200 sp=0x10e3591a0 pc=0x100c2db30
github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/waddrmgr.(*Manager).Unlock(0x10e506000, 0x1091dc6c8, 0x10e2bc200, 0x10e45e078, 0x8, 0x8, 0x0, 0x0)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/waddrmgr/manager.go:1040 +0x284 fp=0x10e359950 sp=0x10e359200 pc=0x100c3fc9c
github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/wallet.(*Wallet).walletLocker.func1(0x10168e8e0, 0x10e426010, 0x10e426010, 0x0)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/wallet/wallet.go:1141 +0x90 fp=0x10e3599b0 sp=0x10e359950 pc=0x100dd2168
github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/walletdb.View(0x101696160, 0x10e720780, 0x10e74ebc8, 0x0, 0x22706d617453656d)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/walletdb/interface.go:196 +0x58 fp=0x10e359a00 sp=0x10e3599b0 pc=0x100c286e0
github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/wallet.(*Wallet).walletLocker(0x10e45c000)
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/wallet/wallet.go:1139 +0x734 fp=0x10e359fd0 sp=0x10e359a00 pc=0x100dc9f1c
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_arm64.s:1037 +0x4 fp=0x10e359fd0 sp=0x10e359fd0 pc=0x100a5b87c
created by github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/wallet.(*Wallet).Start
	/Users/biscottigelato/gocode/src/github.com/biscottigelato/SwiftLightning/vendor/github.com/roasbeef/btcwallet/wallet/wallet.go:142 +0xc4

goroutine 39 [select]:`

**Comment by biscottigelato** [comment] 2018-05-06 22:12
> Before running on mobile phones, there're optimizations that need to be done. We don't recommend doing so until that point. If you wish to run on mobile phons, then the best way would be to help with the required optimizations.

Is there an issue that details what exactly is being talked about here?

**Comment by Roasbeef** [comment] 2018-07-07 02:28
Closing for now as there've been a few goroutine leaks recently that _should_ have addressed this. If this still arises (upon upgrading to the current master), then I'll re-open this issue.

**Closed by Roasbeef** 2018-07-07 02:28 UTC
Labels: raspi, resource usage

**Comment by lechatnieger** [comment] 2019-02-23 02:06
hi, i have the same issue of memory.

lnd version 0.5.2, running on a raspberry pi3, with 2 gb of swap , with a swap file on external hard drive

runtime: out of memory: cannot allocate 2097152-byte block (1311211520 in use)
fatal error: out of memory
runtime stack:
 runtime.throw(0x9dff80, 0xd)
  /usr/local/go/src/runtime/panic.go:608 +0x5c
 runtime.largeAlloc(0x1ffe00, 0x60101, 0x7e584000)
     /usr/local/go/src/runtime/malloc.go:1021 +0x120
runtime.mallocgc.func1()
       /usr/local/go/src/runtime/malloc.go:914 +0x38
runtime.systemstack(0x35f0000)
     /usr/local/go/src/runtime/asm_arm.s:354 +0x84
runtime.mstart()
         /usr/local/go/src/runtime/proc.go:1229
goroutine 14 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_arm.s:298 +0x4 fp=0x3647db4 sp=0x3647db0 pc=0x68530
 runtime.mallocgc(0x1ffe00, 0x8c0238, 0x80001, 0x3647e34)
    /usr/local/go/src/runtime/malloc.go:913 +0x86c fp=0x3647e18 sp=0x3647db4 pc=0x1af38
runtime.makeslice(0x8c0238, 0x1ffe00, 0x1ffe00, 0x7b38c, 0x7e2bccc0, 0x7e603e00)
    /usr/local/go/src/runtime/slice.go:70 +0x68 fp=0x3647e2c sp=0x3647e18 pc=0x53138
 bytes.makeSlice(0x1ffe00, 0x0, 0x0, 0x0)
       /usr/local/go/src/bytes/buffer.go:231 +0x58 fp=0x3647e48 sp=0x3647e2c pc=0x7b528
