### ISSUE TITLE
Pending public channel close pending for several days.  

### ISSUE THREAD

**Issue by cferr716** [lightningnetwork/lnd#5279] opened 2021-05-07 11:22 UTC
### Background

I closed a 50k sat public channel several days ago. (25001 sats still pending in the close).

### Your environment

lnd 0.12.1-beta
umbrella v3.10
Remote Pub key of the channel: 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266
Remote Peer Alias: 1ML.com node ALPHA

### Expected behaviour

Closed channel. UTXOs should have been returned to the primary BTC wallet. 

### Actual behaviour

UTXOs still pending in channel close.

**Comment by guggero** [comment] 2021-05-07 11:25
Can you post the channel point (=funding transaction) of the channel please?

**Comment by cferr716** [comment] 2021-05-07 11:32
This is the funding transaction for the initial channel funding (channel opening) a523d51ca85d743da7677b9c32e15eebddffc388dbea169437853967fcc5e5ee 
I believe this would be the channel point bc1qe0s237jf953vmhxnnzflyvgy2yf6m5hy7lheypgc43g336nm2kfsyzecm0

please bear with me on some of the terminology I'm still a little new around here.

**Comment by guggero** [comment] 2021-05-07 12:06
Thanks, that helped. On the chain I don't see a closing transaction. If your lnd is showing it in `lncli pendingchannels`, then that means something went wrong when communicating with the remote peer and a normal close was not possible. You might need to force-close the channel. The funds will be locked for 144 blocks (~1 day) and then return to your wallet.

Re terminology: A channel or funding outpoint is the combination of the transaction ID (e.g. a523d51ca85d743da7677b9c32e15eebddffc388dbea169437853967fcc5e5ee) and the index of the channel output (zero-based, in your case the index is 1) combined. Usually it's written as `a523d51ca85d743da7677b9c32e15eebddffc388dbea169437853967fcc5e5ee:1` (notice the colon in the end). The output address (`bc1qe0s237jf953vmhxnnzflyvgy2yf6m5hy7lheypgc43g336nm2kfsyzecm0`) can also be called the output script and is often less useful. Because on contrast to a channel point (which is unique), an output script can theoretically occur in the chain multiple times.

**Comment by guggero** [comment] 2021-05-07 15:01
Not sure what UI you're using. On the command line (Umbrel should have some docs on how to open the command line and run commands), it would be `lncli closechannel --force --funding_txid a523d51ca85d743da7677b9c32e15eebddffc388dbea169437853967fcc5e5ee --output_index 1`.

Closing this for now as this is expected behavior if a peer is unresponsive. Feel free to comment further if you have trouble force closing.

**Closed by guggero** 2021-05-07 15:01 UTC
