### ISSUE TITLE
LND dies with "out of memory" after trying to route

### ISSUE THREAD

**Issue by zavan** [lightningnetwork/lnd#940] opened 2018-03-25 15:10 UTC
Every time my LND node (0.4.0-beta) tries to route to the [Blockstream store](https://store.blockstream.com/),

([02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432@104.198.32.198:9735](https://1ml.com/node/02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432))

Be it by trying to pay an invoice or by `queryroutes`, I get a bunch of errors:
<img width="818" alt="screen shot 2018-03-25 at 11 45 39" src="https://user-images.githubusercontent.com/1722965/37876557-87c8252e-3024-11e8-8abc-ba48426756bd.png">
<img width="823" alt="screen shot 2018-03-25 at 11 48 18" src="https://user-images.githubusercontent.com/1722965/37876559-8b35ed0e-3024-11e8-806d-0da86f76cc06.png">

It gets stuck trying to route and after a while dies with "out of memory":
<img width="825" alt="screen shot 2018-03-25 at 11 48 37" src="https://user-images.githubusercontent.com/1722965/37876569-a7170b20-3024-11e8-8873-0ffb206dd53a.png">

[I have two channels open](https://1ml.com/node/0245d1fbaa954a79417cc45b12cc2f2ef84fbc84e8e03147109ef17b0f483de184), one of them to [Bitrefill](https://1ml.com/node/024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed), so I think routing this shouldn't be a problem.

I have made successful payments to other services (even multi-hop ones).

@cdecker says their node is updated and working well.

I started this discussion on my twitter, [see thread](https://twitter.com/opchecksig/status/977920489095131138), I'm not sure if this is a problem with blockstream's node or LDN, or both, so I created this issue.

**Comment by aakselrod** [comment] 2018-03-25 20:10
Can you do a `free -h` before trying to send a payment/use `queryroutes` to see how much RAM you have available? Also, can you see how much RAM `lnd` and your Bitcoin node are consuming on the device (again, before trying to calculate a payment route)?

**Comment by zavan** [comment] 2018-03-25 20:13
![167b863a-de6e-4f13-9cc8-97cb929a7568](https://user-images.githubusercontent.com/1722965/37879460-e5096ed4-304f-11e8-9402-47bb30ba9035.png)
![4754f56b-2b46-4c80-b6e6-b3568211f16e](https://user-images.githubusercontent.com/1722965/37879461-e5289174-304f-11e8-9168-446595fc4b02.png)

**Comment by Roasbeef** [comment] 2018-03-26 02:00
What seems to have happened here is a tight-ish reconnection loop caused by not liking the address type of a received `NodeAnnouncement`. The initial connection is a bit bursty atm due to all the information sent. Thankfully, that's being fixed with an upcoming addition to the protocol.

**Comment by zavan** [comment] 2018-03-26 22:29
One of my channels (to `0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a`) became inactive and this issue is not happening anymore, instead, I get:

```
Mar 26 17:51:01 raspberrypi lnd[6754]: 2018-03-26 17:51:01.654 [INF] SRVR: Attempting to send msgs 11350 to: 0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a
Mar 26 17:51:01 raspberrypi lnd[6754]: 2018-03-26 17:51:01.655 [ERR] SRVR: unable to send message to 0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a, peer not found
Mar 26 17:51:05 raspberrypi lnd[6754]: 2018-03-26 17:51:05.859 [INF] DISC: Broadcasting batch of 14 new announcements
Mar 26 17:51:24 raspberrypi lnd[6754]: 2018-03-26 17:51:24.926 [ERR] HSWC: unable to find links by destination unable to locate channel link bydestination hop id 024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed
Mar 26 17:51:24 raspberrypi lnd[6754]: 2018-03-26 17:51:24.926 [ERR] CRTR: Attempt to send payment 2b7f3f05eb40b55d2d301504b95e3ffd9f05331b4f8317e03891e11e4195494d failed: UnknownNextPeer
Mar 26 17:51:32 raspberrypi lnd[6754]: 2018-03-26 17:51:32.381 [ERR] CRTR: Attempt to send payment 2b7f3f05eb40b55d2d301504b95e3ffd9f05331b4f8317e03891e11e4195494d failed: FeeInsufficient(fee=164079231 mSAT, update=(lnwire.ChannelUpdate) {
Mar 26 17:51:32 raspberrypi lnd[6754]:  Signature: (lnwire.Sig) (len=64 cap=64) {
Mar 26 17:51:32 raspberrypi lnd[6754]:   00000000  17 c7 da 5d 85 3b be a4  33 10 86 b5 a6 35 27 40  |...].;..3....5'@|
Mar 26 17:51:32 raspberrypi lnd[6754]:   00000010  de 2e 20 09 68 2a 9f b8  0a b7 20 41 9f 99 05 1a  |.. .h*.... A....|
Mar 26 17:51:32 raspberrypi lnd[6754]:   00000020  2d 9a 3e b2 8d 4f 75 68  05 67 70 de c1 2a ac 0b  |-.>..Ouh.gp..*..|
Mar 26 17:51:32 raspberrypi lnd[6754]:   00000030  50 19 15 3a bb 58 4d 7a  0e a2 3f de a0 a5 fa 0d  |P..:.XMz..?.....|
Mar 26 17:51:32 raspberrypi lnd[6754]:  },
Mar 26 17:51:32 raspberrypi lnd[6754]:  ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
Mar 26 17:51:32 raspberrypi lnd[6754]:  ShortChannelID: (lnwire.ShortChannelID) 515072:335:0,
Mar 26 17:51:32 raspberrypi lnd[6754]:  Timestamp: (uint32) 1522054565,
Mar 26 17:51:32 raspberrypi lnd[6754]:  Flags: (lnwire.ChanUpdateFlag) 0,
Mar 26 17:51:32 raspberrypi lnd[6754]:  TimeLockDelta: (uint16) 144,
Mar 26 17:51:32 raspberrypi lnd[6754]:  HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,
Mar 26 17:51:32 raspberrypi lnd[6754]:  BaseFee: (uint32) 1000,
Mar 26 17:51:32 raspberrypi lnd[6754]:  FeeRate: (uint32) 1
Mar 26 17:51:32 raspberrypi lnd[6754]: }
Mar 26 17:51:35 raspberrypi lnd[6754]: 2018-03-26 17:51:35.214 [INF] HSWC: Sent 0 satoshis received 0 satoshis in the last 10 seconds (0.2 tx/sec)
```

Which may be related to #922 (the `FeeInsuficient` bit).
I am closing my channels and opening new ones now, once they're open I'll try again.

**Comment by Roasbeef** [comment] 2018-03-26 23:21
That's not related to this issue, just a channel peer going offline, meaning you aren't yet able to utilize that channel. Generally, many nodes on the network atm are unreliable as users are very new to the technology.

**Closed by Roasbeef** 2018-03-26 23:21 UTC
Labels: resource usage, routing
