### ISSUE TITLE
Automatic Invoice Cancellation

### ISSUE THREAD

**Issue by jackeveritt** [lightningnetwork/lnd#3445] opened 2019-08-31 07:58 UTC
### Background

BTCPayServer currently assumes that after an invoice expires, it won't be paid.  This causes issues if the invoice then is paid after expiry: 

https://github.com/btcpayserver/btcpayserver/issues/1002

One solution suggested is to use a hodl invoice.

Is there a planned feature for automatic cancellation of a regular invoice when it expires?

### Your environment
LND 0.7.1 (BTCPaySever fork)

**Comment by NicolasDorier** [comment] 2019-08-31 16:06
BTCPay don't have implementation specific code for lightning so we can support as much implementations we can. Hodl invoice would break our abstraction layer, so the best would be to simply implement the invoice expiry if possible.

**Comment by wpaulino** [comment] 2019-09-03 20:13
Closing as duplicate of https://github.com/lightningnetwork/lnd/issues/3448.

**Closed by wpaulino** 2019-09-03 20:13 UTC
