### ISSUE TITLE
Can't pay my own invoice

### ISSUE THREAD

**Issue by riperk** [lightningnetwork/lnd#3326] opened 2019-07-18 05:25 UTC
Let's say I create an invoice:

```
$lnd addinvoice
{
	"r_hash": "9bba1a48331815a5a97aee24b2365e99d8e4dbfd39460afe675e85a98b600085",
	"pay_req": "lntb1pwnqqg8pp5nwap5jpnrq26t2t6acjtydj7n8vwfkla89rq4ln8t6z6nzmqqzzsdqqcqzpgnytgevp9rnjq76huzzjvypg7vylve0rs0ae9flm9570nzxkmc6tnynxszvew6cg0sl204antlsp48l8ftkr8ufhvhsa7q5gw6p8jv8qpvp3z2h",
	"add_index": 58
}
```
And then try to pay it:
```
lnd sendpayment --force --amt 100 --pay_req lntb1pwnqqg8pp5nwap5jpnrq26t2t6acjtydj7n8vwfkla89rq4ln8t6z6nzmqqzzsdqqcqzpgnytgevp9rnjq76huzzjvypg7vylve0rs0ae9flm9570nzxkmc6tnynxszvew6cg0sl204antlsp48l8ftkr8ufhvhsa7q5gw6p8jv8qpvp3z2h
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
[lncli] unable to find a path to destination
```

I believe this is a huge usability problem, because in a multi-user situation (custodian wallets, services, businesses) one user might be trying to pay another and it will consistently fail. Now the service will need to implement a special case for "sending to an invoice created by the same lnd node" and a special case for when a payment was "received" by an lnd node.

And if that's not annoying enough, it makes it extremely hard (adds a lot of state) when trying to multiplex requests onto different lnd nodes. 

I think an possible solution would be for lnd to detect the payment was to itself, do a special sort of noop payment? Assuming it's a reasonable design, it would be nice to not even use any channels, making it guaranteed to immediately succeed. But either way, the ideal thing would be that as a caller of lnd, you don't need to care where the invoice was generated or paid from.

**Comment by halseth** [comment] 2019-07-18 12:55
Duplicate of https://github.com/lightningnetwork/lnd/issues/1645

**Closed by halseth** 2019-07-18 12:55 UTC

**Comment by riperk** [comment] 2019-07-18 14:05
I don't think this is exactly a duplicate of #1645, at least in intention. I don't want to send to myself to balance channels, I want to send to myself to have a consistent API.

**Comment by Roasbeef** [comment] 2019-07-19 03:33
> I believe this is a huge usability problem, because in a multi-user situation (custodian wallets, services, businesses) one user might be trying to pay another and it will consistently fail. 

They'll need to track account externally, where they can also track user balances.

**Comment by halseth** [comment] 2019-07-19 07:18
@riperk You could always decode the invoice and check the receiver pubkey. If it is your own pubkey then update your database.
