### ISSUE TITLE
lnd is heavy on disk I/O

### ISSUE THREAD

**Issue by Talkless** [lightningnetwork/lnd#3119] opened 2019-05-25 08:59 UTC
### Background
I've reported comment https://github.com/lightningnetwork/lnd/issues/3060#issuecomment-495886688 that my `lnd` got stuck after reboot, and at the same time I noticed how disk utilization got down while `lnd` was inactive(-ish):

![sda-day](https://user-images.githubusercontent.com/292191/58366993-38132c00-7ee2-11e9-9dad-c9c1bf3264a2.png)

This graph shows disk utilization when only `bitcoind` and `electrumx` is working. So bitcoind & electrumx does not reach 50% disk utilization. When `lnd` is working fine (see all these days before in graph) I ofter get 100% utilization...

This is year graph:
![sda-year](https://user-images.githubusercontent.com/292191/58367119-07cc8d00-7ee4-11e9-92c3-3a6bdff97d16.png)

Looks like after I starting using `lnd`, disk utilization kept growing slowly for months..? Does it correlate to the whole Lightning Network growth?

### Your environment

* version of `lnd` `0.6.1-beta commit=v0.6.1-beta`
* which operating system (`uname -a` on *Nix) `Linux odroid-hc1 4.9.0-9-armmp-lpae #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) armv7l GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend `/Satoshi:0.18.0/`
* OdrdoidHC1 SBC with HGST HTS721075A9E630 HDD (7200).
* Have 17 channels.

```
$ du -hs ~/.lnd/data/
175M    /home/lnd/.lnd/data/
```

### Steps to reproduce

Stop `lnd` and check how disk utilization goes down.

### Expected behaviour

`lnd` shoudn't be resource hog..?

### Actual behaviour

`lnd` has big impact on HDD load.

**Comment by Roasbeef** [comment] 2019-05-27 20:08
`lnd` will query `bitcoind` for information it needs. Relative to just running `bitcoind`, this will generate additional I/O utilization. Going through the normal dance: check your logs for anything that stands out, etc. On my nodes with hundreds of channels, I have what I consider to be "normal".

**Comment by wpaulino** [comment] 2019-06-05 18:31
Have there been any improvements since running with > v0.6?

**Comment by cfromknecht** [comment] 2019-06-06 06:38
@Talkless what rpcs are being used and how frequently are they being executed?

**Comment by Talkless** [comment] 2019-06-06 16:15
@wpaulino I don't believe I see any noticatble improvements in HDD I/O regards.

@cfromknecht There are not regular/automatic RPC's. I only rarely ssh into that machine and do `getinfo`,  `fwdinghistory` etc, for general manual statistics tracking :) .

**Comment by Roasbeef** [comment] 2019-06-07 11:03
Still unable to reproduce this. Does anything stand out in your logs?

**Comment by Roasbeef** [comment] 2019-06-18 01:36
Closing due to lack of updates or actionable information.

**Closed by Roasbeef** 2019-06-18 01:36 UTC

**Comment by Talkless** [comment] 2019-06-18 16:13
Oh sorry for stalling this thread. I don't have any interesting info to provide, maybe it's just too much for small OdroidHC1 machine with just 2GB of RAM. Only ~500MB is available for file system cache, so lot's of real seeking on HDD is expected, aspeccialy when HDD is "shared" between bitcoind/electrumx/lnd...
