### ISSUE TITLE
Cannot send payment ("Unable to apply channel update")

### ISSUE THREAD

**Issue by BitBargain** [lightningnetwork/lnd#865] opened 2018-03-17 13:13 UTC
Just installed a fresh lnd (LTND: Version 0.4.0-alpha). Completely removed everything except the config. Launched with:

`lnd --bitcoin.mainnet --bitcoin.node=bitcoind [...]`

I opened a few channels (which is by the way very hard, lots of timeouts and disconnects when I go to random peers) and tried sending a payment. I got:

`Unable to send coins: Unable to apply channel update: unable to fetch chan point for chan_id=8620838226088: tx_index=#14103040 is out of range (max_index=0), network_chan_id=(*lnwire.ShortChannelID)(0xc420016ab4)(7:14103040:2216)`

If I do 'listchannels' and grep for this chan_id, there are no results. There was one with chan_id=0 but it disappeared after restarting lnd.

Meanwhile, my lnd is flooded with logs such as:

> 2018-03-17 12:55:09.154 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=562786126215970816, chan_point=33fe5a06f6bc6b6c37b0a95c251bc789a6a943e34aa8f5b3dae8554b740b4648:0: target output has been spent
> 2018-03-17 12:55:09.154 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=562290246542753792, chan_point=ebad7ba6ed6b3177861d4dd71647295adf876f72679e2caa76bbf14b1c53cc56:0: target output has been spent
> 2018-03-17 12:55:09.155 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=562949953495040000, chan_point=82e6ec82863010133a4aca9a7175fb310eb1ecfaf3811e1e2fd9d0c01f810801:0: target output has been spent
> 2018-03-17 12:55:09.155 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=563826264248942592, chan_point=52117ac65589189e1492563616fdd98a90cc771f02f5a1b98668bd51421a2454:0: target output has been spent
> 2018-03-17 12:55:09.371 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=563833960915533824, chan_point=a1a919340366daf5b03be56659855a6f86508d1f6236abbd51ca4563bf314525:0: target output has been spent
> 2018-03-17 12:55:09.372 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=563466724027203584, chan_point=ea01e741175204eec0f3db412dcbe9fd434f14242b6af4e49c9e6507e1bb11da:0: target output has been spent

I'm using go-1.9, on a Debian, did nothing special except install lnd, send some money to it, open a few channels and try to send a payment.

Any advice would be appreciated. The one I got on IRC was to check if maybe I'm on testnet instead of mainnet. I did give it --bitcoin.mainnet so it shouldn't be testnet, but let's suppose this is the issue somehow, how do I make sure?

**Comment by BitBargain** [comment] 2018-03-17 16:08
Update: I am able to send payments if I have an open channel with the peer.

The invoice I was trying to pay before was for an article on mainnet.yalls.org. I opened a channel just now, I can pay it.

The original issue still stands, the error message is very cryptic and I'm not sure if I can send a payment unless I'm directly connected to the node with a channel.

**Comment by remyers** [comment] 2018-03-17 20:46
I also see a flood of these `DISC: Router rejected channel edge` and I'm using bitcoind on mainnet.  It sounds like almost all channels are rejected because their utxo can't be fetched.   Any tips on how to diagnose this?

**Comment by Roasbeef** [comment] 2018-03-17 21:34
@BitBargain 

> I opened a few channels (which is by the way very hard, lots of timeouts and disconnects when I go to random peers) and tried sending a payment. I got:

It seems there're some very old nodes on mainnet, as most of them were just due to people hacking in support for mainnet as it wasn't enabled at the time they launched their nodes. If they were very old nodes, then they're using a slightly incompatible version of the wire protocol: 
>  tx_index=#14103040 is out of range (max_index=0)

There's no way to even fit that many transactions in a Bitcoin block. 

> If I do 'listchannels' and grep for this chan_id, there are no results. There was one with chan_id=0 but it disappeared after restarting lnd.

That's not your channel ID. That's the chan ID of a channel them you attempted to route through, but the node was faulty due to the reasons I described above. 

> Meanwhile, my lnd is flooded with logs such as:

Again, there are old faulty nodes on mainnet that seem to accept invalid channels, and then attempt to propagate them. As we properly verify channels, we won't propagate them. 

> On #recksplorer (lnmainnet.gaben.win), I can't find anything with this pubkey. It seems to have connected to me

Explorers shouldn't be taken as a source of golden truth, they're not authoritative. 


> . This is an incoming channel and when I try to send a payment I'm supposed to be using channels I opened.

The channel is not active, meaning that the remote peer isn't online, so you can't utilize it.

@remyers 

> I also see a flood of these DISC: Router rejected channel edge and I'm using bitcoind on mainnet. It sounds like almost all channels are rejected because their utxo can't be fetched.

See the response above. 


> One other odd thing is that walletbalance gives me a much larger value then I would expect after tying up most my deposited bitcoin in channels. When I add it to what I get from channelbalance the value is almost double. Could that also indicate some mainnet/testnet mixup?

There's no mainnet/testnet mixup, all networks are properly partitioned within `lnd`. `walletbalance` will show both confirmed and unconfirmed balances, what makes you think it's larger than it should actually be?

**Comment by Roasbeef** [comment] 2018-03-17 21:35
>  And also, I have an open channel with chan_id=0 again. Is that normal?

Channels aren't "fully" open until 6+ confirmations, before then the channel ID isn't considered stable so it may not be set. What backend are you using?

**Comment by remyers** [comment] 2018-03-18 18:06
> There's no mainnet/testnet mixup, all networks are properly partitioned within lnd. walletbalance will show both confirmed and unconfirmed balances, what makes you think it's larger than it should actually be?

Sorry @Roasbeef , my mistake.  I just added it up and the sum of my `walletbalance` and `channelbalance` match my deposits afterall.

**Comment by halfik** [comment] 2018-03-21 14:56
Have same issue when trying to tip https://lnmainnet.gaben.win/#
So they are runing some outdated lightning node?

**Comment by Roasbeef** [comment] 2018-03-21 19:43
This issue will be resolved by #893. 

@halfik it's possible that they are, many that were on mainnet before the latest release were running older versions with a mainnet flag hacked in. It may be a few days until people uniformly update.

**Closed** 2018-03-21 22:24 UTC
Labels: channels, multi-hop, payments

**Comment by remyers** [comment] 2018-04-03 11:31
FYI - I updated to 0.4.1 and after my graph finished updating I tried again.  This time it worked.

Also, no more flood of `DISC: Router rejected channel edge` messages in my log.

**Comment by halfik** [comment] 2018-04-03 11:42
Yea i saw commit that fixed this. Today gona update my lnd and check if problem was solved.
