### ISSUE TITLE
Unable to start server: a height hint greater than 0 must be provided

### ISSUE THREAD

**Issue by cyclopes2011** [lightningnetwork/lnd#3539] opened 2019-09-24 14:29 UTC
### Background

Attempting to restore LND from wallet seed and channel.backup file.

### Your environment

* lnd version 0.7.1-beta commit=v0.7.1-beta-352-9b1ecbd3fa3fd93a6d95a5f71921c73777340760
* 16.04.1-Ubuntu
* Bitcoin Core Daemon version v0.16.3.0-g49e34e288 (installed on dedicated server)

### Steps to reproduce

Performed the steps to restore LND from wallet seed and channel.backup file via `lncli create` command.

### Expected behaviour

Existing wallet restored via `lncli create` and funds returned to wallet after channel restore and closeall per the SCB recovery process.

### Actual behaviour

LND fails to start due to the following error:

`2019-09-24 03:55:09.062 [ERR] LTND: Unable to start server: a height hint greater than 0 must be provided`

Complete startup log attached below:
[20190924 1026 steropes.log](https://github.com/lightningnetwork/lnd/files/3647692/20190924.1026.steropes.log)

**Comment by cyclopes2011** [comment] 2019-09-24 14:32
Similar to #3444

**Comment by wpaulino** [comment] 2019-09-24 21:53
The following patch should allow you to start your node again:

```diff --git a/chanrestore.go b/chanrestore.go
index f771f91b..34f74f69 100644
--- a/chanrestore.go
+++ b/chanrestore.go
@@ -138,7 +138,8 @@ func (c *chanDBRestorer) RestoreChansFromSingles(backups ...chanbackup.Single) e
 	for _, restoredChannel := range channelShells {
 		err := c.chainArb.WatchNewChannel(restoredChannel.Chan)
 		if err != nil {
-			return err
+			continue
+			//return err
 		}
 	}
 
```

Closing the issue as a duplicate of #3444.

**Closed by wpaulino** 2019-09-24 21:53 UTC

**Comment by cyclopes2011** [comment] 2019-09-24 22:33
Here is what I did but the error remains the same.

Sorry, I am not a developer so I assume the @@ is a location for the code function and not part of the edit. I have edited the "chanrestore.go" file per your instruction and have included the comments prior to the section to be edited for clarity:

        // Finally, we'll need to inform the chain arbitrator of these new
        // channels so we'll properly watch for their ultimate closure on chain
        // and sweep them via the DLP.
        for _, restoredChannel := range channelShells {
                err := c.chainArb.WatchNewChannel(restoredChannel.Chan)
                if err != nil {
                        continue
                        // return err
                }
        }

Thank you for your response and assistance. :)

**Comment by wpaulino** [comment] 2019-09-24 22:36
Did you reinstall lnd with the new changes?

**Comment by cyclopes2011** [comment] 2019-09-24 22:38
I simply edited the chanrestore.go file and restarted LND. Do I need to do a clean install of LND, the SCB restore, and then start LND?

**Comment by wpaulino** [comment] 2019-09-24 22:45
You'll need to run `make install` before restarting.

**Comment by cyclopes2011** [comment] 2019-09-24 22:54
Same error after the make install and restart.

**Comment by wpaulino** [comment] 2019-09-24 22:57
Are you using the lnd binary found in `$GOPATH/bin/`?

**Comment by cyclopes2011** [comment] 2019-09-24 23:02
I assume so since I have it in my path. I don't have any other LND installed.

**Comment by wpaulino** [comment] 2019-09-24 23:08
Could you try this as well?

```diff --git a/contractcourt/chain_arbitrator.go b/contractcourt/chain_arbitrator.go
index b3cd497d..b1e934b9 100644
--- a/contractcourt/chain_arbitrator.go
+++ b/contractcourt/chain_arbitrator.go
@@ -503,7 +503,7 @@ func (c *ChainArbitrator) Start() error {
 	for err := range watcherErrs {
 		if err != nil {
 			c.Stop()
-			return err
+			//return err
 		}
 	}
 
```

**Comment by cyclopes2011** [comment] 2019-09-24 23:41
(Sorry for the delay.)

Yes! LND is running after that last change. I am going to monitor and let it do its thing.

Thank you for the assistance! :)

**Comment by cyclopes2011** [comment] 2019-09-25 02:06
LND has been running for a while now. I have manually closed the channels with `lncli closeallchannels -force` but have five channels remaining. Those five produce an error and appear to be stuck and cannot be closed. Three of the five channels have a recurring error in the log:

`2019-09-24 21:58:52.799 [ERR] NANN: Unable to retrieve chan status for Channel(b0f7a019b4d0d4dd48e7071d10c9086a4ce675fa0970a43dc6263e1384202c7c:0): edge not found
2019-09-24 21:58:52.799 [ERR] NANN: Unable to retrieve chan status for Channel(3ebfb564ccd84c643f9b2cc6cf03837d6037f3d87314b623aafb962c5ff2d9a3:0): edge not found
2019-09-24 21:58:52.799 [ERR] NANN: Unable to retrieve chan status for Channel(bbc2e6bf0f1dfd166238df8050ba9cd1c3bf98e267de9db624b38ae2b08f11f4:0): edge not found`

Not sure about the other two channels. There is not an error being logged that I see for these two so I'm looking into more detail on the issue.

I searched the LND issues to find something similar and don't see anything directly applicable. Let me know if you have any advice on how to resolve these channels. Thank you!

I can open a new issue if needed and provide more details in the morning.

**Comment by wpaulino** [comment] 2019-09-25 02:20
Those errors can be ignored, they're only relevant for sending enabled/disabled updates for your channels. Your node doesn't have any graph information about them because they were restored and they have already been closed out on chain.
