### ISSUE TITLE
Add all possible build tags to docs

### ISSUE THREAD

**Issue by benthecarman** [lightningnetwork/lnd#5290] opened 2021-05-12 01:22 UTC
There is no way to see what are all the possible build tags in the docs. It would be nice so I can compile from source and know I have all the rpc servers available.

**Comment by Roasbeef** [comment] 2021-08-31 02:01
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/3598

**Closed by Roasbeef** 2021-08-31 02:01 UTC
Labels: golang/build system, P3, docs
