### ISSUE TITLE
Lots of pendingchannels with limbo balance

### ISSUE THREAD

**Issue by aantonop** [lightningnetwork/lnd#4401] opened 2020-06-21 23:57 UTC
### Background

Describe your issue here.

Closed channels are not getting swept and the balance remains in limbo. I disabled height_hint cache (problem last time), didn't manage to fix.

### Your environment

* version of `lnd` 10.1-beta
* which operating system (`uname -a` on *Nix)-  Ubuntu 18.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind 0.20
* any other relevant environment details

### Steps to reproduce

lncli pendingchannels

{
    "channel": {
      "remote_node_pub": "0274a984d028819cf0207965b4872aa4efa7fbd611d414d90f78c184154f099317",
      "channel_point": "a3c5ded9e26441e6d956925c38353f59686660aa8ff43d38446062b5bb0d90c4:0",
      "capacity": "5547214",
      "local_balance": "5546723",
      "remote_balance": "0",
      "local_chan_reserve_sat": "0",
      "remote_chan_reserve_sat": "0",
      "initiator": "INITIATOR_LOCAL",
      "commitment_type": "LEGACY"
    },
    "closing_txid": "c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc",
    "limbo_balance": "5546723",
    "maturity_height": 609267,
    "blocks_til_maturity": -26497,
    "recovered_balance": "0",
    "pending_htlcs": [],
    "anchor": "LIMBO"
  }

Closing TXID is not found on the blockchain. 

After restarting LND logs show:
May 19 21:29:34 ln lnd[882]: 2020-05-19 21:29:34.113 [ERR] CNCT: *contractcourt.commitSweepResolver(a3c5ded9e26441e6d956925c38353f59686660aa8ff43d38446062b5bb0d90c4:0): unable to sweep input: sweep failed after max attempts
May 19 21:29:34 ln lnd[882]: 2020-05-19 21:29:34.113 [ERR] CNCT: ChannelArbitrator(a3c5ded9e26441e6d956925c38353f59686660aa8ff43d38446062b5bb0d90c4:0): unable to progress *contractcourt.commitSweepResolver: sweep failed after max attempts

### Expected behaviour

Channel closes

### Actual behaviour

43 channels in "wait close"
7 channels in "pending force close"
30m sats! :eyes: in limbo

**Comment by aantonop** [comment] 2020-06-21 23:58
LND was down for about a week while I was travelling and not checking it regularly. When it restarted, a bunch of channels were inactive. They never closed properly.

**Comment by Roasbeef** [comment] 2020-06-22 00:02
If you do `lncli getinfo` does it show as being "synced to chain"? Also does the height reported there match the height of your backend? It might be the case that some re-scans are still on-going if it was down for a while.

**Comment by Roasbeef** [comment] 2020-06-22 00:02
> sweep failed after max attempts

Any logs related to this showing why the broadcasts are failing?

**Comment by Roasbeef** [comment] 2020-06-22 00:07
> version of btcd, bitcoind, or other backend - bitcoind 0.20


So 0.10.1 doesn't support `bitcoind`, but master, and the current `v0.10.2-beta.rc2` _do_.

**Comment by aantonop** [comment] 2020-06-22 00:23
Got it, let me change versions, see if that fixes it

Thanks

**Comment by aantonop** [comment] 2020-06-22 01:17
Still showing limbo balance, even for a channel that supposedly closed 6
months ago. This is just one of 7 pending in limbo:

{
    "channel": {
      "remote_node_pub":
"0274a984d028819cf0207965b4872aa4efa7fbd611d414d90f78c184154f099317",
      "channel_point":
"a3c5ded9e26441e6d956925c38353f59686660aa8ff43d38446062b5bb0d90c4:0",
      "capacity": "5547214",
      "local_balance": "5546723",
      "remote_balance": "0",
      "local_chan_reserve_sat": "0",
      "remote_chan_reserve_sat": "0",
      "initiator": "INITIATOR_LOCAL",
      "commitment_type": "LEGACY"
    },
    "closing_txid":
"c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc",
    "limbo_balance": "5546723",
    "maturity_height": 609267,
    "blocks_til_maturity": -26504,
    "recovered_balance": "0",
    "pending_htlcs": [],
    "anchor": "LIMBO"
  }


https://blockstream.info/tx/c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc

Status
26506 Confirmations
Included in Block
0000000000000000000c16bd299bd7eae7702b0ad1450306d780f01c2b6999a0
<https://blockstream.info/block/0000000000000000000c16bd299bd7eae7702b0ad1450306d780f01c2b6999a0>
Block height
609 267
Block timestamp
2019-12-22 03:58:21 GMT-5

I don't understand why that would be showing as in "limbo".

**Comment by aantonop** [comment] 2020-06-22 01:25
> If you do `lncli getinfo` does it show as being "synced to chain"? Also does the height reported there match the height of your backend? It might be the case that some re-scans are still on-going if it was down for a while.

It is synced to chain, height 635773, which is currently the same on bitcoind and blockstream.info, so it looks good.

**Comment by Roasbeef** [comment] 2020-06-22 01:26
So what happened is that in 0.20, bitcoind changed the error message returned when you try to broadcast a transaction that's already in the chain. 0.10.1 didn't account for this change, so it thinks it's just unable to broadcast, when in fact the transaction has already been confirmed on chain.

**Comment by Roasbeef** [comment] 2020-06-22 01:27
By _running 0.10.2, `lnd` _should_ now recognize that those transactions have actually confirmed (we register for confirmation _after)_ the broadcast), and mark those channels are being fully resolved on-chain (as they are, even the outputs created have been swept somewhere).

**Comment by aantonop** [comment] 2020-06-22 12:20
After 12 hours, still pending. However, I see that it is trying to sweep the channel closing TXs, such as ```c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc``` which was the example channel from December.

Jun 22 00:42:55 ln lnd[12151]: 2020-06-22 00:42:55.952 [INF] SWPR: Creating sweep transaction c500a9d583d8a1913cfdadd5609f3bbb3bf83905e4237b833c59afd7739d21b0 for 5 inputs (c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0 (CommitmentNoDelay), 809a5c03859570d576ae471e2eb0f353eddd1e0b862c14a7a226014bd1260552:1 (CommitmentNoDelay), 1d922ffea7ba6534fbb62c543ee5ec9a6d7d027ceb43790d66a2bc742108b422:0 (CommitmentNoDelay), 816cb9c49ff159bff9b0932da782d7b408698a1a82241834444bbbcf19f5af47:1 (CommitmentNoDelay), 8dbb43215961988064311246f34ce3a2d1c8e7acc3c0039e84dafebf46a6cc85:0 (CommitmentNoDelay)) using 5276 sat/kw, tx_fee=0.00008077 BTC
Jun 22 00:42:55 ln lnd[12151]:    PreviousOutPoint: (wire.OutPoint) c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0,
Jun 22 01:45:01 ln lnd[12151]: 2020-06-22 01:45:01.942 [INF] SWPR: Creating sweep transaction e13c89cd013643d2fbb80ab122c812db89c180c09ee7fc83cc7c1707eeb6145c for 2 inputs (c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0 (CommitmentNoDelay), 809a5c03859570d576ae471e2eb0f353eddd1e0b862c14a7a226014bd1260552:1 (CommitmentNoDelay)) using 5276 sat/kw, tx_fee=0.00003756 BTC
Jun 22 01:45:01 ln lnd[12151]:    PreviousOutPoint: (wire.OutPoint) c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0,
Jun 22 02:07:49 ln lnd[12151]: 2020-06-22 02:07:49.665 [INF] SWPR: Creating sweep transaction 914d944d1e276de320f5db41219693e2be2aa09aed7e752a6e64c7287c5f9ba4 for 1 inputs (c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0 (CommitmentNoDelay)) using 5276 sat/kw, tx_fee=0.00002316 BTC
Jun 22 02:07:49 ln lnd[12151]:    PreviousOutPoint: (wire.OutPoint) c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0,
Jun 22 02:24:14 ln lnd[12151]: 2020-06-22 02:24:14.853 [INF] SWPR: Creating sweep transaction e8b61bb00a321bd0d62dec24059be189c29e5d53f18daad8a892463618337528 for 2 inputs (c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0 (CommitmentNoDelay), 6f9b60342937a0eb93fd1e91be9d52e90fa69db097a3b75df0fdead7706f288c:0 (CommitmentNoDelayTweakless)) using 5276 sat/kw, tx_fee=0.00003756 BTC
Jun 22 02:24:14 ln lnd[12151]:    PreviousOutPoint: (wire.OutPoint) c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0,
Jun 22 07:35:35 ln lnd[12151]: 2020-06-22 07:35:35.192 [INF] SWPR: Creating sweep transaction 95768a0aabc77ac3e8201af5f4a930773c7c534d5e792f9afbfebf415f37894e for 1 inputs (c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0 (CommitmentNoDelay)) using 4552 sat/kw, tx_fee=0.00001998 BTC
Jun 22 07:35:35 ln lnd[12151]:    PreviousOutPoint: (wire.OutPoint) c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0,

Perhaps it is having difficulty in the high-fee environment. But at least something is happening with those channels. 

Should I close the issue or should I wait until it has swept it successfully?

**Comment by wpaulino** [comment] 2020-06-22 18:04
> Perhaps it is having difficulty in the high-fee environment. But at least something is happening with those channels.
> Should I close the issue or should I wait until it has swept it successfully?

The outputs being swept have already been spent, which is why broadcasts keep failing. The issue seems to be lnd not recognizing the spend of the outputs being swept. Disabling the height hint cache in this case wouldn't help, but if it was already enabled and the spend wasn't detected, then that would point to an issue there.

What do your `NTFN` and `CNCT` logs show for `c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0`?

**Comment by aantonop** [comment] 2020-06-22 18:18
I will restart with detailed logging on NTFN and CNCT and we'll see. Thanks

**Comment by wpaulino** [comment] 2020-06-22 18:20
If you restart, don't forget to set `--debuglevel=NTFN=debug,CNCT=debug` :)

**Comment by aantonop** [comment] 2020-06-22 18:28
Yes exactly, it's now restarting with those two set to debug and all the rest set to info.

**Comment by aantonop** [comment] 2020-06-23 12:29
Here's what I'm seeing in the logs (several of these): 

Jun 23 05:00:12 ln lnd[15395]: 2020-06-23 05:00:12.110 [INF] SWPR: Creating sweep transaction 8425d91689bbbc9cd0ade369f8aaef04dd20a0f6da899e7908c8d7a8fd68e076 for 1 inputs (c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0 (CommitmentNoDelay)) using 6433 sat/kw, tx_fee=0.00002824 BTC
Jun 23 05:00:12 ln lnd[15395]: 2020-06-23 05:00:12.111 [INF] LNWL: Inserting unconfirmed transaction 8425d91689bbbc9cd0ade369f8aaef04dd20a0f6da899e7908c8d7a8fd68e076
Jun 23 05:00:12 ln lnd[15395]: 2020-06-23 05:00:12.124 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0xc00af0ae00)({
Jun 23 05:00:12 ln lnd[15395]:  Version: (int32) 2,
Jun 23 05:00:12 ln lnd[15395]:  TxIn: ([]*wire.TxIn) (len=1 cap=15) {
Jun 23 05:00:12 ln lnd[15395]:   (*wire.TxIn)(0xc0062d62a0)({
Jun 23 05:00:12 ln lnd[15395]:    PreviousOutPoint: (wire.OutPoint) c037a0c2c641f5c124c2483b4f9fe8da276f0d296d497c2c94047b530fc1fcbc:0,
Jun 23 05:00:12 ln lnd[15395]:    SignatureScript: ([]uint8) <nil>,
Jun 23 05:00:12 ln lnd[15395]:    Witness: (wire.TxWitness) (len=2 cap=2) {
Jun 23 05:00:12 ln lnd[15395]:     ([]uint8) (len=72 cap=144) {
Jun 23 05:00:12 ln lnd[15395]:      00000000  30 45 02 21 00 a6 62 e0  25 45 b9 32 2b e5 4e 7b  |0E.!..b.%E.2+.N{|
Jun 23 05:00:12 ln lnd[15395]:      00000010  1a ad ba 8e 14 3b 18 b8  d3 96 4f da 80 f7 7c 88  |.....;....O...|.|
Jun 23 05:00:12 ln lnd[15395]:      00000020  40 68 42 68 e2 02 20 05  5d d8 ad b9 c6 7d 60 16  |@hBh.. .]....}`.|
Jun 23 05:00:12 ln lnd[15395]:      00000030  83 77 4a a5 1f 6e ac 8a  a6 0a df 2d d7 b3 b2 df  |.wJ..n.....-....|
Jun 23 05:00:12 ln lnd[15395]:      00000040  1d c2 41 f9 d0 ae 1f 01                           |..A.....|
Jun 23 05:00:12 ln lnd[15395]:     },
Jun 23 05:00:12 ln lnd[15395]:     ([]uint8) (len=33 cap=33) {
Jun 23 05:00:12 ln lnd[15395]:      00000000  03 fb 9d 8e 69 73 60 24  ba 83 02 53 a8 86 69 a3  |....is`$...S..i.|
Jun 23 05:00:12 ln lnd[15395]:      00000010  a9 10 23 e4 d1 ed 59 eb  bb c7 19 1e 31 9d b6 46  |..#...Y.....1..F|
Jun 23 05:00:12 ln lnd[15395]:      00000020  ea                                                |.|
Jun 23 05:00:12 ln lnd[15395]:     }
Jun 23 05:00:12 ln lnd[15395]:    },
Jun 23 05:00:12 ln lnd[15395]:    Sequence: (uint32) 0
Jun 23 05:00:12 ln lnd[15395]:   })
Jun 23 05:00:12 ln lnd[15395]:  },
Jun 23 05:00:12 ln lnd[15395]:  TxOut: ([]*wire.TxOut) (len=1 cap=15) {
Jun 23 05:00:12 ln lnd[15395]:   (*wire.TxOut)(0xc006fcef40)({

The complete log file since startup (about 18 hours) is 14MB and can be found here:

https://drive.google.com/file/d/18EG55jLmdw_3Syoy4r-RD4eZlmgyJNAm/view?usp=sharing

**Comment by wpaulino** [comment] 2020-06-23 21:35
Looks like systemd didn't include all logs:

`Jun 22 18:26:42 ln systemd-journald[468]: Suppressed 9737 messages from lnd.service`

**Comment by aantonop** [comment] 2020-06-23 22:07
New log file upload (28MB):
https://drive.google.com/file/d/15RY14QIsVLD0XjgYwKqdZsvmMiaWgbAG/view?usp=sharing

**Comment by wpaulino** [comment] 2020-06-23 23:09
Looks like you're running into the same height hint cache issue as last time. Do you have any debug `NTFN` logs prior to the ones included in your latest comment?

**Comment by aantonop** [comment] 2020-06-24 01:06
I think I removed the height hint cache when running 0.10.1 which was
incompatible with bitcoind 0.20. When I upgraded lnd, I reverted the height
hint cache issue.

I will add it back in, maybe with a config option patch...

I don't have older logs. I don't keep them long.

**Comment by aantonop** [comment] 2020-06-24 16:14
After about 15 hours, 40 out of the 50 pending channels have cleared. Only 10 now on "pending force close"

Again, it was the height hint cache, combined with a long downtime cause by lack of maintenance and attention on my end. 

I think there should be a config flag to disable height hint cache to help unstick stuck channels. 

Can I get some feedback (here) on whether that's desirable so I can work on a PR to that effect?

**Comment by wpaulino** [comment] 2020-06-24 18:01
Yeah, let's move forward with the flag.

Given that you've run into this issue twice already, would you mind keeping the `debuglevel=CNCT=debug,NTFN=debug` option on so that we have the logs required to debug this the next time around?

**Comment by Roasbeef** [comment] 2020-07-16 18:19
The PR adding the flag has been merged, and I think andreas reports no more pending channels running w/ the flag. Can we close this now?

**Comment by aantonop** [comment] 2020-07-16 18:25
Yes, this issue is resolved by the PR that disables the height hint cache
queries

**Closed** 2020-07-16 18:28 UTC
