### ISSUE TITLE
correct way to bump the fee of a mutual channel closing tx

### ISSUE THREAD

**Issue by philipp1992** [lightningnetwork/lnd#7997] opened 2023-09-17 16:03 UTC
Hi,
i have a channel closing tx (no force) that has only 11.8 sat / vbyte and i want to test bumping the fee with lncli.

This is the TX and i know which of these outputs belongs to my wallet.

https://blockstream.info/tx/1ded37ff718cac267491e55b16f025f9b5a8aa39f12bfddaa96d3d707ee8cbdd
What is the correct way to bump the fee with lncli?

**Comment by alexbosworth** [comment] 2023-09-17 16:07
did you try bumpfee https://docs.lightning.engineering/lightning-network-tools/lnd/unconfirmed-bitcoin-transactions

**Comment by philipp1992** [comment] 2023-09-17 16:09
yeah but what do i pass to bumpfee?

**Comment by alexbosworth** [comment] 2023-09-17 16:11
Bumpfee takes as arguments the outpoint that your wallet knows how to spend, the fee of the child, and a force flag for uneconomical spends

you can read about it via lncli wallet h bumpfee

**Comment by philipp1992** [comment] 2023-09-17 16:16
so for my specific case, the output of the channel closing tx that belongs to me has the index 1

lncli bumpfee 1ded37ff718cac267491e55b16f025f9b5a8aa39f12bfddaa96d3d707ee8cbdd:1 --sat_per_vbyte=20 should do the trick?

**Comment by philipp1992** [comment] 2023-09-17 16:19
{
    "total_limbo_balance": "15000",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "03c23b7f5b9fa984705678b96821f4d15133ced6ef58c0521e4dcca434e0d5a50a",
                "channel_point": "0ffacb7b3d32b3d4b0420f477e1e6c719a18bfad34bb3cb257c0bd8f08e0688c:0",
                "capacity": "30000",
                "local_balance": "15000",
                "remote_balance": "12136",
                "local_chan_reserve_sat": "354",
                "remote_chan_reserve_sat": "354",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "LEGACY",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "limbo_balance": "15000",
            "commitments": {
                "local_txid": "850b8e2298668e1b867a948bc60909c90964d2483fb91f4ca26264291727d412",
                "remote_txid": "bc21411b67fd917f932fe8dd39737ef25b24f2f2d50e339f3e8f4877ed382fb3",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2864",
                "remote_commit_fee_sat": "2864",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }
    ]
}

**Comment by alexbosworth** [comment] 2023-09-17 16:20
Yeah if the wallet can spend that outpoint and it's economical

**Comment by philipp1992** [comment] 2023-09-17 16:23
outpoint means the "channel_point": "0ffacb7b3d32b3d4b0420f477e1e6c719a18bfad34bb3cb257c0bd8f08e0688c:0", ? or the utxo of the closing tx that belongs to my wallet?

**Comment by alexbosworth** [comment] 2023-09-17 16:24
The unconfirmed utxo that belongs to your wallet that's right, the bumpfee will spend that utxo into a new tx that has the fee rate you specified

**Comment by philipp1992** [comment] 2023-09-17 16:26
thanks a lot. just to confirm.

do i pass the txid of the closing tx (first **?**) or do i pass the input (second **?**)
![image](https://github.com/lightningnetwork/lnd/assets/11994884/bb310f98-137b-4e56-af31-68f4861f9275)

**Comment by alexbosworth** [comment] 2023-09-17 16:29
I guess the left side is the channel outpoint, which means its' locked to a 2:2 with you and your peer

So this means its not your outpoint, it's a shared outpoint

Then it's spent into 2 outputs, which I assume is yours and your peers'

So you cannot spend the left side outpoint (the channel), but you can potentially spend the child of the spend of that outpoint

**Comment by philipp1992** [comment] 2023-09-17 16:31
so how would i spend this using bumpfee?

**Comment by alexbosworth** [comment] 2023-09-17 16:33
If you look at the example in the doc

```
lncli wallet bumpfee --conf_target 6 --force 38a64ad629960b0100e6954801a035c484df64f6efa783c33508054d8f2cfe95:0
```

replace conf target with the sat per vbyte if you want to use that

replace the outpoint with the outpoint that you can spend

if you can't spend the outpoint nothing bad will happen it will just tell you it can't bump it

**Comment by philipp1992** [comment] 2023-09-17 16:42
Take note that the transaction id and output specified in this command relate to an input used in the transaction that you want to be confirmed, not the transaction itself.

**Comment by philipp1992** [comment] 2023-09-17 17:31
https://blockstream.info/tx/f89bf3c0de9ec6cb7a32c43d3e97a9a83b8caa55e1b1af6b2663c21a40a01279 doesnt get confirmed though

**Comment by philipp1992** [comment] 2023-09-17 19:53
Can you check if I did everything as supposed to? @alexbosworth

**Comment by alexbosworth** [comment] 2023-09-17 19:55
It looks like you increased the effective fee rate from 11.8 sat/vbyte to 17.1 sat/vbyte

The current fee rate is a bit higher. If you want you can run the same command again but increase the fee a bit, or just wait for 17.1 to be a confirming fee rate level

**Comment by guggero** [comment] 2023-09-18 08:10
Looks like everything is working correctly. Please use discussions for troubleshooting in the future. Closing as no action required.

**Closed by guggero** 2023-09-18 08:10 UTC
Labels: bug, needs triage
