### ISSUE TITLE
rpc: abandonchannel silently "succeeds" for channels not in the pending open state

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#4483] opened 2020-07-23 20:14 UTC
I opened a channel from Electrum Mobile lightning wallet to my lnd node, but the funding transaction failed to be broadcast.

That left a pending channel in my lnd node that I can't get rid of. I tried force closing, then called 'abandonChannel', but it still is shown as:

```json
➜  lnd git:(master) ✗ ./lncli-debug pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "redacted",
                "channel_point": "redacted:0",
                "capacity": "1000000",
                "local_balance": "0",
                "remote_balance": "redacted",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "redacted",
                "remote_txid": "redacted",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "12116",
                "remote_commit_fee_sat": "12116",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}

``` 

Is there a way to get rid of it?

**Comment by Roasbeef** [comment] 2020-07-23 22:09
> I tried force closing, then called 'abandonChannel', but it still is shown as:

Hmm, yeah abandon channel atm only removes channels that were pending or considered open. It's now been moved to a different area of the database now that it's considered "waiting close". We need to update the `abandonchannel` call to clean up all the new state that was added since the call was originally introduced.

**Comment by cfromknecht** [comment] 2020-07-23 22:46
> Hmm, yeah abandon channel atm only removes channels that were pending or considered open.

A more immediate fix, abandonchannel should fail if the channel isn't in a pending-open state.

**Comment by wpaulino** [comment] 2020-08-13 20:19
@gustavonalle I'm not able to reproduce following your steps. Do you recall if you ran into any errors when closing or abandoning the channel?

**Comment by wpaulino** [comment] 2020-10-19 20:13
Closing due to lack of updates and inability to reproduce.

**Closed by wpaulino** 2020-10-19 20:13 UTC
Labels: bug, channel management, rpc
