### ISSUE TITLE
Please add a transactions lookup (by txid) endpoint

### ISSUE THREAD

**Issue by altaraven** [lightningnetwork/lnd#7617] opened 2023-04-19 19:11 UTC
v0.16.0
LND has a GetTransactions endpoint
GET /v1/transactions

But it has no pagination and its a pretty bad way to search a transaction by txid using it if there are thousands of them.

Please add a new lookup endpoint (or extend existing one) where it will be possible to find on-chain transaction by txid (tx_hash in terms of LND)
If it already exists, please add a page in docs.
Thank you.

**Comment by lujakob** [comment] 2023-04-19 22:18
I think there already is a similar issue #7323 Seems like it is on hold for a while. In case I would also be interested to give it a try.

**Comment by guggero** [comment] 2023-04-20 07:46
Duplicate of https://github.com/lightningnetwork/lnd/issues/7323.

**Closed by guggero** 2023-04-20 07:46 UTC
Labels: enhancement
