### ISSUE TITLE
[bug]: Removed invalid transaction didn't work, lnd retry to broadcast a double spend on every startup

### ISSUE THREAD

**Issue by bota87** [lightningnetwork/lnd#7732] opened 2023-05-26 21:58 UTC
On each startup lnd try to broadcast a sweep transaction that its already confirmed from more than 1k blocks
lnd version 0.16.2
```
[INF] WTCL: (anchor) Requesting new session.
[INF] SWPR: Sweeper starting
[ERR] BTCN: Broadcast attempt failed: -25: bad-txns-inputs-missingorspent
[INF] LNWL: 1317edb2d92cd88af6e4bdacf0a6d2306f14185992c519cfd937d153861fcdca: broadcast failed because of: double spend: -25: bad-txns-inputs-missingorspent
[INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0xXXXXXXXX) <transaction detail removed>
[INF] LNWL: Removed invalid transaction: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
[INF] UTXN: UTXO nursery starting
[INF] NTFN: New block epoch subscription
```

**Comment by Roasbeef** [comment] 2023-05-26 22:34
Duplicate of https://github.com/lightningnetwork/lnd/issues/7708

**Closed by Roasbeef** 2023-05-26 22:34 UTC
Labels: bug, needs triage
