### ISSUE TITLE
[Bug] The way LND handles bitcoind cookie authentication is dangerous

### ISSUE THREAD

**Issue by NicolasDorier** [lightningnetwork/lnd#2984] opened 2019-04-21 04:58 UTC
### Background

I have LND configured to use BitcoinD RPC via cookie file authentication.
If BitcoinD restart, LND does not crash but stop working, exposing the user to malicious behavior.

The reason is that when BitcoinD restart, a new cookiefile is generated but LND does not try to read it again.

### Steps to reproduce

1. Start Bitcoind  with cookieauth
2. Start LND with cookieauth to Bitcoind
3. Restart bitcoind

### Expected behaviour

By order or preference:
1. LND should see that bitcoind RPC is now returning 401 and should read fresh cookiefile value.
2. LND should crash, allowing the process manager to restart it.
3. LND should not support bitcoin cookiefile auth

### Actual behaviour

LND does not crash, while stop processing new blocks.

Error such as
```
Unable to process chain reorg: status code: 401, response: ""
unable to start peer: unable to load channels: status code: 401, response: ""
```

Are popping up.

LND then need to be manually restarted by the user.
Until the user manually restart it, a malicious peer can broadcast an outdated commitment.

**Comment by Roasbeef** [comment] 2019-04-22 19:02
Duplicate of #1557.

**Closed by Roasbeef** 2019-04-22 19:02 UTC

**Comment by NicolasDorier** [comment] 2019-04-23 03:32
thanks I did not even remembered I already reported it...
