### ISSUE TITLE
Feature request: Tor onion support à la `lncli --rpcserver=xxx.onion`

### ISSUE THREAD

**Issue by hieblmi** [lightningnetwork/lnd#5799] opened 2021-09-28 01:18 UTC
It would be great if nodes with TOR proxy support could submit lncli commands to an .onion address.

Example:
```
lncli --rpcserver=xxx.onion --macaroonpath=data/chain/bitcoin/simnet/admin.macaroon getinfo
```

**Comment by Roasbeef** [comment] 2021-09-28 01:52
Closing as a duplicate of https://github.com/lightningnetwork/lnd/issues/4939#issuecomment-905262693

**Closed by Roasbeef** 2021-09-28 01:52 UTC
