### ISSUE TITLE
Long standing pending channels with unfindable txid 

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#5569] opened 2021-07-25 19:00 UTC
### Background

There are channels that have been pending for days despite a fairly empty mempool.  I can see these when running `lncli pendingchannels` I'm unsure how Thunderhub is associating txid's with these pending channel opens.. However, these txid's don't show up in the mempool. I would like to understanding if I should try to close or abandon these pending channels. I'm Seeking advice.

### Your environment

* version of `lnd` 0.13.1
* which operating system (`uname -a` on *Nix) ubuntu 20.04
* version of `btcd`, `bitcoind`, or other backend bitcoind
* any other relevant environment details

### Steps to reproduce

open a channel

### Expected behaviour

open a channel, goes to active status.

### Actual behaviour

remains pending.

**Comment by subjectdelta86** [comment] 2021-07-25 19:52
hey mate,

did you try following command?
_lncli abandonchannel _[channelpoint]__

for example if the channelpoint is 123456789:1
_lncli abandonchannel 123456789 1_

hope this will fix this annoying bug...

**Comment by miketwenty1** [comment] 2021-07-25 20:00
@subjectdelta86 
> I would like to understanding if I should try to close or abandon these pending channels

I wanted to ask for help before abandoning. I've never abandoned a pending channel before and wasn't sure if it was safe to do so.

**Comment by guggero** [comment] 2021-07-26 10:18
Was lnd ever restarted since those channels were opened? Then the funding transactions would be re-broadcast.
Not sure why they wouldn't confirm in the first place, with the mempool this empty as you mentioned.

I wouldn't abandon the channel unless you know the UTXO that is being spent by the channel open TX has been spent in another confirmed TX. Otherwise you risk the original channel funding TX to confirm by accident.

**Comment by miketwenty1** [comment] 2021-07-27 01:03
@guggero Yes the node has been restarted, we even have a 1 pending transaction that is 70 days old. Would there be an opportunity to resolve this with lncli commands? Is this something where I don't have to broadcast this, but safely fail these channel opens?

**Comment by guggero** [comment] 2021-07-27 07:58
Since the channel wasn't opened in the default 2 week period the other node likely has already removed the channel from their state and you'll need to force close it right away if it confirms anyway.

The "safest" option is to create a double spend TX with a higher fee that spends the same input as the channel funding TX does. Once that is confirmed you can be certain the channel will never open and can use the `lncli abandonchannel` command on it.

**Comment by Roasbeef** [comment] 2021-07-28 02:18
Closing this as it doesn't appear to be tracking an active issue in the software itself. If the transaction has never been broadcast (as oliver mentions), then it's safe to abandon the channel. In this case, you'll either need to double spend manually, or get lnd to select that input during transaction selection. 

There's a PR which may land in 0.14 that'll automate this process (double spending the output, etc). One way to check if `lnd` is still trying to broaddcast these channels would be to look at the start up logs, to see if a broadcast is attempted (based on the outpoint) of the channels. We can [continue this in the discussions section if needed](https://github.com/lightningnetwork/lnd/discussions).

**Closed by Roasbeef** 2021-07-28 02:18 UTC

**Comment by rkbtc** [comment] 2021-07-28 14:13
I have a very simillar issue which I believe was related to some of the UTXOs which where somehow conflicted because I used the seed of my BTC wallet from the node on BlueWallet. Anyways, the problem has now been fixed and the UTXOs are now fine and the wallet works, but I have 3 channels that were initiated and just wont open because when I initiated them there was the issue with the BTC Wallet. I use umbrel, and unfortunately, they do not allow their users to use the abandonchannel command. Now, what I am trying to do instead is to have the channels rebroadcast the transaction to the mempool but I don't know how. Can someone help?
