### ISSUE TITLE
subscribetransactions fires duplicated event when a transaction is received

### ISSUE THREAD

**Issue by joaodealmeida** [lightningnetwork/lnd#2267] opened 2018-12-04 01:24 UTC
### Background

subscribetransactions is firing 2 events per tx received. Whenever I receive a transaction, lnd fires 2 events containing the same payload.

The transaction gets notified independent from the block notification once it’s confirmed and it’s also notified when processing the block notification containing the transaction.

### Your environment

* version of `lnd` - 0.5.1-beta commit=v0.5.1-beta-dirty
* which operating system (`uname -a` on *Nix)  - Linux ip-172-31-4-119 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend - bitcoind

### Steps to reproduce

- Listen suscribetransactions
- Generate an address
- Send btc to that address 

### Expected behaviour

An event should be fired only when the transaction gets notified independent from the block notification once it’s confirmed.

### Actual behaviour

An event is also fired when processing the block notification containing the transaction.

**Comment by Roasbeef** [comment] 2020-05-05 01:03
I think this is no longer the case for updates from the invoice RPC sub-server.

**Comment by wpaulino** [comment] 2020-05-05 01:23
This is regarding wallet transaction notifications.

**Comment by nicolasburtey** [comment] 2020-10-14 15:33
I can confirm the issue is still present

**Comment by Roasbeef** [comment] 2021-07-13 23:17
Re-opening this, as we fixed the issue in `btcwallet`, but need to update `lnd` accordingly

**Comment by Roasbeef** [comment] 2021-08-11 02:22
Fixed by https://github.com/btcsuite/btcwallet/pull/751

**Closed by Roasbeef** 2021-08-11 02:22 UTC
Labels: bug, wallet, notifications
