### ISSUE TITLE
lnd should detect and refuse double payment / invoice spending

### ISSUE THREAD

**Issue by baryluk** [lightningnetwork/lnd#1353] opened 2018-06-09 16:33 UTC
### Background

Describe your issue here.

### Your environment

* version of `lnd`, git, 5c42a88038ec2c273c27e2bf8cb7eeb50775c09a
* which operating system (`uname -a` on *Nix), Linux

### Steps to reproduce

Got a payment to https://hodlmonkey.com/, which uses a payment gateway, https://opennode.co/

I added merch to a cart, added my address info, accepted to pay via Lightning, and got a lightning invoice to pay.

```text
https://opennode.co/checkout/abcdabcd-abcd-abcd-abcd-xyzxyzxyzxyzxyz

1 × Bitcoin Lightning Network T-Shirt - Black, M 

0.00295188 BTC
($22.43 USD) 
```

I got a lightning invoice around 17:05 CEST.

I run `decodepayreq` to confirm it is correct (in terms of amount of satoshi to spend), and executed `payinvoice`:

```text
baryluk@vps2:~$ lncli decodepayreq 'lnbc2951880n1pd3hm22pp5854y2dznfh5elyxm05lhcz9sycytf3s3s5q3ey3yqfyav90un7rqdz0xysv89eqgf5hgcm0d9hzqnrfva58gmnfdenjqnn9w3mk7untyp2z65mgd9e8ggpdyppxcctrdvkzqngcqzysf5na2m7s5qv2jwlyf4xmdxyvmlcs9cvja75ea2k9kunsjdey5nupkygasxxu7584e5lud2kptzy3mzltp5rgmh3axkaph82c08agqygp520ygm' 
{
    "destination": "039376f846cb4e137f3474baa7fbe74ec627745c7d5c54935b99fbb1b60a62c9b3",
    "payment_hash": "3d2a4534534de99f90db7d3f7c08b02608b4c61185011c92240249d615fc9f86",
    "num_satoshis": "295188",
    "timestamp": "1528556874",
    "expiry": "3600",
    "description": "1 × Bitcoin Lightning Network T-Shirt - Black, M",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144",
    "route_hints": [
    ]
}
$
```

Decoded timestamp, `2018-06-09T15:07:54+00:00` , or 17:07 CEST.

Seems right.

First payment was done just few seconds after decoding and verifying:

```
baryluk@vps2:~$ lncli payinvoice 'lnbc2951880n1pd3hm22pp5854y2dznfh5elyxm05lhcz9sycytf3s3s5q3ey3yqfyav90un7rqdz0xysv89eqgf5hgcm0d9hzqnrfva58gmnfdenjqnn9w3mk7untyp2z65mgd9e8ggpdyppxcctrdvkzqngcqzysf5na2m7s5qv2jwlyf4xmdxyvmlcs9cvja75ea2k9kunsjdey5nupkygasxxu7584e5lud2kptzy3mzltp5rgmh3axkaph82c08agqygp520ygm'
{
	"payment_error": "",
	"payment_preimage": "9a4b16f8d52abd1e2517c74c4110e66aeaf802fb039ecad776b1b937aba02458",
	"payment_route": {
		"total_time_lock": 527025,
		"total_amt": 295188,
		"hops": [
			{
				"chan_id": 576412373860024320,
				"chan_capacity": 860991,
				"amt_to_forward": 295188,
				"expiry": 526881,
				"amt_to_forward_msat": 295188000,
				"fee_msat": 394
			},
			{
				"chan_id": 574487129024561153,
				"chan_capacity": 500000,
				"amt_to_forward": 295188,
				"expiry": 526881,
				"amt_to_forward_msat": 295188000
			}
		],
		"total_fees_msat": 394,
		"total_amt_msat": 295188394
	}
}
$
```

At this time I checked my webbrowser, and it was showing that the transaction is still pending. Also because of verbosity of returned message, I assumed that payment was unsuccessful (I did not check `payment_error` field, to see that it actually was successful). So I redone the payment:

Second payment few minutes later:

```
baryluk@vps2:~$ lncli payinvoice 'lnbc2951880n1pd3hm22pp5854y2dznfh5elyxm05lhcz9sycytf3s3s5q3ey3yqfyav90un7rqdz0xysv89eqgf5hgcm0d9hzqnrfva58gmnfdenjqnn9w3mk7untyp2z65mgd9e8ggpdyppxcctrdvkzqngcqzysf5na2m7s5qv2jwlyf4xmdxyvmlcs9cvja75ea2k9kunsjdey5nupkygasxxu7584e5lud2kptzy3mzltp5rgmh3axkaph82c08agqygp520ygm'
{
	"payment_error": "",
	"payment_preimage": "9a4b16f8d52abd1e2517c74c4110e66aeaf802fb039ecad776b1b937aba02458",
	"payment_route": {
		"total_time_lock": 527170,
		"total_amt": 295188,
		"hops": [
			{
				"chan_id": 576412373860024320,
				"chan_capacity": 565802,
				"amt_to_forward": 295188,
				"expiry": 527026,
				"amt_to_forward_msat": 295188295,
				"fee_msat": 394
			},
			{
				"chan_id": 566743268596121600,
				"chan_capacity": 625000,
				"amt_to_forward": 295188,
				"expiry": 526882,
				"amt_to_forward_msat": 295188000,
				"fee_msat": 295
			},
			{
				"chan_id": 568462904767610881,
				"chan_capacity": 2307692,
				"amt_to_forward": 295188,
				"expiry": 526882,
				"amt_to_forward_msat": 295188000
			}
		],
		"total_fees_msat": 689,
		"total_amt_msat": 295188689
	}
}
$
```

Only then I realized, that it was successful, as was the first one. Double payment.

Why it was not detected as duplicate, either by my `lnd` node, or end node?!

Notice that the pay request do have `payment_hash` and `description`, and `destination`, and should detect that it is duplicate pay.

```text
baryluk@vps2:~$ lncli listpayments
{
    "payments": [
...

        {
            "payment_hash": "3d2a4534534de99f90db7d3f7c08b02608b4c61185011c92240249d615fc9f86",
            "value": "295188",
            "creation_date": "1528556914",
            "path": [
                "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
                "039376f846cb4e137f3474baa7fbe74ec627745c7d5c54935b99fbb1b60a62c9b3"
            ],
            "fee": "0",
            "payment_preimage": "9a4b16f8d52abd1e2517c74c4110e66aeaf802fb039ecad776b1b937aba02458"
        },
        {
            "payment_hash": "3d2a4534534de99f90db7d3f7c08b02608b4c61185011c92240249d615fc9f86",
            "value": "295188",
            "creation_date": "1528557286",
            "path": [
                "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
                "03e0a26dca5f4d4dea43ba104d41e4f54b6b66c5b2559811f83b20efafbe307183",
                "039376f846cb4e137f3474baa7fbe74ec627745c7d5c54935b99fbb1b60a62c9b3"
            ],
            "fee": "0",
            "payment_preimage": "9a4b16f8d52abd1e2517c74c4110e66aeaf802fb039ecad776b1b937aba02458"
        }
    ]
}
$
```

First timestamp of creation_date: `2018-06-09T15:08:34+00:00` aka 17:08 CEST.
Second timestamp of creation_date: `2018-06-09T15:14:46+00:00` aka 17:14 CEST.

Logs (timestamps in CEST):

```text
2018-06-09 17:08:38.575 [INF] HSWC: Sent 295188 satoshis and received 0 satoshis in the last 10 seconds (0.200000 tx/sec)
2018-06-09 17:14:48.575 [INF] HSWC: Sent 295189 satoshis and received 0 satoshis in the last 10 seconds (0.400000 tx/sec)
```

I then stopped `lnd`, and restarted it. New entry showed up in the log:

```text
2018-06-09 18:01:20.182 [INF] HSWC: Sent 590731 satoshis and received 0 satoshis in the last 10 seconds (159.200000 tx/sec)
```

No idea why!

The status page at https://opennode.co/ was telling me that there was an error. Fine, that is the problem with them and not `lnd`. About an hour later (at 18:20 CEST), I received an automatic email from https://hodlmonkey.com/ that my order has been received and is now being processed. Presumably meaning that they received correctly my funds. Well they did, but the web page from opennode.co was broken, and did not tell me that immediately. Again, not a problem with `lnd`.

### Expected behaviour

I expect second payment to the same destination with the same payment_hash to be rejected by my own `lnd` node as duplicate, unless some additional flag is passed to allow that (i.e. `--allow_duplicate`, or `--allow_duplicate_after=6d`, which would ignore duplicate successful payments older than 6 days).

### Actual behaviour

Two identical payments were accepted by `lnd`, and forward to destination over lightning network.

**Comment by Cryptoknut** [comment] 2018-06-10 14:14
The issue I submitted was also while trying to use hodlmonkey

**Comment by baryluk** [comment] 2018-06-10 19:28
@Cryptoknut I have seen your issue. It is unrelated. The hodlmonkey is just an example. I had problem like yours 2 days ago (`lncli payinvoice` would hung for hours doing nothing), but this is different issue.

My bug is about just a detection of duplicate invoice payments, which is not necessarily a bug in `lnd`, just an enhancement to make life easier.

**Comment by Roasbeef** [comment] 2018-06-10 23:17
Duplicate of #973.

**Closed by Roasbeef** 2018-06-10 23:17 UTC

**Comment by cfromknecht** [comment] 2018-08-23 04:33
master now has checks to ensure it doesn't pay the same invoice twice #1719
