### ISSUE TITLE
Tor v3 neutrino backend support

### ISSUE THREAD

**Issue by openoms** [lightningnetwork/lnd#5788] opened 2021-09-24 15:44 UTC
### Background

Tor v3 Bitcoin Core address is not resolved when passed in `neutrino.connect=`

### Your environment

* lnd v0.13.1
* Linux raspberrypi 5.10.60-v8+ aarch64 GNU/Linux
* Bitcoin Core version v22.0.0
* RaspiBlitz v1.7.1rc2

### Steps to reproduce
add a Tor v3 address to lnd.conf with the options:
```
[Application Options]
feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json   

[Bitcoin]
bitcoin.active=1   
bitcoin.node=neutrino

[neutrino]
neutrino.connect=longaddressxxxxxxxxxxxxxxxxx.onion

[tor]
tor.active=true
tor.v3=true
tor.socks=9050
tor.control=9051
```

### Expected behaviour

Bitcoin Core has moved to Tor v3 addresses by default in v0.21.0 and the Tor network is deprecating the v2 services as well.
LND should be able to connect to a v3 neutrino enabled backend.

### Actual behaviour

Error in lnd.log:
```
[WRN] BTCN: unable to lookup IP for longaddressxxxxxxxxxxxxxxxxx.onion: invalid onion v2 host: longaddressxxxxxxxxxxxxxxxxx.onion   
```

**Comment by Roasbeef** [comment] 2021-09-24 18:29
Closing as a duplicate of: https://github.com/lightningnetwork/lnd/issues/4973

**Closed by Roasbeef** 2021-09-24 18:29 UTC
