### ISSUE TITLE
mass closure of channels after btcd restart

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1086] opened 2018-04-12 18:40 UTC
### Background

btcd got stuck for about 10 blocks or so. i decided to restart it, without stopping lnd.
btcd got up and spinning, lnd renegotiated fees resulting in 92 channels force_closing.
probably all those channels were with c-lightning nodes.
am i barking up the correct repository?

```
2018-04-12 15:18:54.556 [INF] CNCT: Unilateral close of ChannelPoint(e4f0be6d40b10f0425de1610327e5c6020516a014fff5df96910e66db8eeb983:1) detected
2018-04-12 15:18:54.577 [INF] CNCT: Unilateral close of ChannelPoint(9033374a89b3d52606dee743a3a4f07510be7ee30fceeef673f841c68e5d2494:0) detected
2018-04-12 15:18:54.578 [INF] CNCT: Unilateral close of ChannelPoint(6be3307736349bff5dd2719d2b61ea26b58e17bdd1afd908701813b7f6d34233:1) detected
...
```

and errors like

```
2018-04-12 15:15:51.128 [ERR] HSWC: ChannelPoint(fd1dec6b56adb338ad80a4f7f3e5dd14154d103cadeeb08ecf8cf1f40a46c1a4:0): recieved error from peer: update_fee 1500 outside range 15000-200000
2018-04-12 15:17:30.829 [ERR] HSWC: ChannelPoint(31cfd17293ecab6d896a773d4cb9f00c9156c8496fb0fb8d79a1a7a16ec6dabe:0): recieved error from peer: update_fee 1750 outside range 3499-60765
2018-04-12 15:17:30.829 [ERR] HSWC: ChannelPoint(ca4307d8dc3b9d74ce40127656261b10904789847026f60f499ab98d389169f0:0): recieved error from peer: update_fee 1750 outside range 3499-60765
2018-04-12 15:17:30.937 [ERR] HSWC: ChannelPoint(0860b7e72f239802ab39bb0f30aea3821bb447dff25e73a83d03ab7455b7c2fd:1): recieved error from peer: update_fee 1750 outside range 3499-60765
2018-04-12 15:17:31.007 [ERR] HSWC: ChannelPoint(b75c9165d83b230589c24019a9fd7b03d6b20a60d7b5350c388d1cf1f63711ce:0): recieved error from peer: update_fee 1750 outside range 3499-60765
...
```

a detailed log of one of those:

http://paste.ubuntu.com/p/zkyJ9hWwPB/
interesting things happen around 2018-04-12 15:17:31.400
search for "recieved error" (yes it seems to be a typo)

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment] 2018-04-12 19:04
> am i barking up the correct repository?
Perhaps...the driver here is `clightning` _always_ force closing if it doesn't like fees. Note that this is a bad decision, as it's the _broadcaster_ that must now incur the timelock penalty.

**Comment by halseth** [comment] 2018-04-13 09:19
Duplicate of #1058

**Closed by halseth** 2018-04-13 09:19 UTC
