### ISSUE TITLE
Can't sweep the remaining funds

### ISSUE THREAD

**Issue by georgeorwell23** [lightningnetwork/lnd#7400] opened 2023-02-12 22:24 UTC
Hello,

I closed down my node a few months ago. I still had 2 channels in pending open for already 6 months or so and 2 channels in ''waiting close'' 
I'm not able to withdraw the 40.000 sats that are still on this adres: https://mempool.space/address/bc1png8we7h8m2fy0vmvr07zk5hsc6f65czwe7k0z8vf4ly8y6e9p8hs645vqw

When i run lncli pendingchannels i see this: 

{
    "total_limbo_balance": "29993490",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "035352d5960c7f86263e079f29707144088709332e781246b306370ca7e0a64183",
                "channel_point": "db4ebb20ea335eb5bec1e616fd7ebb1875aa82373b9eff7b7ca1f2e2369d3a60:1",
                "capacity": "10000215",
                "local_balance": "9996745",
                "remote_balance": "0",
                "local_chan_reserve_sat": "100002",
                "remote_chan_reserve_sat": "100002",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "commit_fee": "2810",
            "commit_weight": "772",
            "fee_per_kw": "2500"
        },
        {
            "channel": {
                "remote_node_pub": "038f8f113c580048d847d6949371726653e02b928196bad310e3eda39ff61723f6",
                "channel_point": "ef9c02915b0167d4c17b44b780a4dda838293f11e2d9db3578ea2f9c8921de9e:1",
                "capacity": "18750000",
                "local_balance": "18746530",
                "remote_balance": "0",
                "local_chan_reserve_sat": "187500",
                "remote_chan_reserve_sat": "187500",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "",
                "private": false
            },
            "commit_fee": "2810",
            "commit_weight": "772",
            "fee_per_kw": "2500"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69",
                "channel_point": "df850beb10dda6e3ce64fe190293c58aa22fa645d916b477adf07b549e7e23bb:0",
                "capacity": "20000215",
                "local_balance": "19996745",
                "remote_balance": "0",
                "local_chan_reserve_sat": "200002",
                "remote_chan_reserve_sat": "200002",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
                "private": false
            },
            "limbo_balance": "19996745",
            "commitments": {
                "local_txid": "60b052b1dbb8f7ed60839f1f775334be66e4c62a8300591fd8937219049c3cd7",
                "remote_txid": "0de48e3f5502870df4120e3b8cca79117b14601b0a87ec7e4b6acc4fefda681c",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2810",
                "remote_commit_fee_sat": "2810",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": "60b052b1dbb8f7ed60839f1f775334be66e4c62a8300591fd8937219049c3cd7"
        },
        {
            "channel": {
                "remote_node_pub": "02f72978d40efeffca537139ad6ac9f09970c000a2dbc0d7aa55a71327c4577a80",
                "channel_point": "17961bfeaad968f0523ff56b59a7d47c423d87633355d6458c95df00d0044dd1:0",
                "capacity": "10000215",
                "local_balance": "9996745",
                "remote_balance": "0",
                "local_chan_reserve_sat": "100002",
                "remote_chan_reserve_sat": "100002",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
                "private": false
            },
            "limbo_balance": "9996745",
            "commitments": {
                "local_txid": "99d277fc1d25775b4fad381fbbd16ca53ac6c79d679a2fadb37084c1ec2c28cc",
                "remote_txid": "4c07a20b31270f82188c426809a27740dae8b34fca9ce303d896f7784ee51c6f",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "2810",
                "remote_commit_fee_sat": "2810",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": "99d277fc1d25775b4fad381fbbd16ca53ac6c79d679a2fadb37084c1ec2c28cc"
        }
    ]
}

When i'm trying to force close the channels i get this respons: ''channel is already in the process of being force closed''

Which sounds  odd to me, i already tried to force close them a few months ago.

I also tried to sweep all the funds, that also didn't work.

How can i get the funds out?

### Your environment

lnd version 0.15.4-beta
Linux pop-os 6.0.6-76060006-generic x86_84
Bitcoin Core RPC client version v23.0.0

**Comment by bitromortac** [comment] 2023-02-13 08:38
It looks like none of the channel points exist on chain. How are the 40.000 sats related?

**Comment by georgeorwell23** [comment] 2023-02-13 17:16
> It looks like none of the channel points exist on chain. How are the 40.000 sats related?

Not sure, but they are in some sort of way related to the 4 channels, otherwise i would be able to sweep the funds right?

**Comment by saubyk** [comment] 2023-02-13 21:53
Hi @georgeorwell23 none of the channel opening/closing transactions that you've posted in your issue can be traced onchain. You should have all your on-chain funds intact on your node, as none of the related inputs appear to have been spent. At best you can inspect your UTXOs and try to spend the inputs again to your wallet to ensure that you have control over your funds.

**Comment by saubyk** [comment] 2023-02-16 16:31
Closing this issue. Feel free to re-open if you need further inputs. Thanks

**Comment by georgeorwell23** [comment] 2023-02-20 23:25
> Hi @saubyk thanks for your reply. So i tried to sweep the funds, but i'm still unable to withdraw the sats. Do you know how i can fix this?
![signal-2023-02-12-215957_002](https://user-images.githubusercontent.com/108611713/220212336-539b180d-4976-4c77-8dc0-1354d9e97546.png)

**Comment by guggero** [comment] 2023-02-21 08:39
@georgeorwell23 can you contact me on our [Slack](https://lightning.engineering/slack.html) please? Same username as here. I'll help you debug this.

**Comment by georgeorwell23** [comment] 2023-02-21 17:21
> 

Can you send me a new link? 

I got the notification: ''this link is no longer active''

**Comment by guggero** [comment] 2023-02-21 19:36
All channels shown never made it to chain, so there were no funds to sweep from them.
Getting out the single remaining UTXO of 40k sats didn't work because of the P2TR fee estimation bug that is also described in https://github.com/lightningnetwork/lnd/issues/5739.
Worked with @georgeorwell23 offline and they were able to sweep the funds using the PSBT APIs.

So closing this, since it turned out to be a duplicate of https://github.com/lightningnetwork/lnd/issues/5739 or https://github.com/lightningnetwork/lnd/issues/7079.

**Closed by guggero** 2023-02-21 19:36 UTC
Labels: bug, needs triage
