### ISSUE TITLE
lnd <-> lnd peer cannot reconnect

### ISSUE THREAD

**Issue by Dikay900** [lightningnetwork/lnd#5632] opened 2021-08-15 17:35 UTC
### Background

I cannot reconnect to some peers with existing channels after a restart of lnd.

### Your environment

* version of `lnd` - 0.13.1
* which operating system (`uname -a` on *Nix) - Linux raspberrypi 5.10.52-v8+ aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend - bitcoind 21.1 full node
* any other relevant environment details - rpi4 8GB tor network only (i know tor is unreliable but i can persistenly reconnect to every other peer ~100 without a problem)

### Steps to reproduce

Probably but unknown:

1. open channel to one of the nodes
2. restart lnd
3. cannot reconnect to peer - channels stays inactive

### Expected behaviour

Reconnect of peers when channels between them exist successfull

### Actual behaviour

Every connect is aborted with the message: unable to start peer: unable to read init msg: EOF

I had the problem with different nodes:

- `0318ac9faa9629e7da08819bc8fe0dd2ae3044d69b1b2283a63479acffeb968483`
- `02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c`
- `0234227bdcd0361622f39447f961618480e7347ab1cfe6e74f561b976135343b31`

All having a public ip and a tor ip. Could this be the root cause for such an issue?
Unfortunately i do not know to which ip I was intially connected when i opened the channels but i am unable to reconnect now after a restart of lnd.
I cannot test both nodes since the other node already force closed the channel between us, but in the older logs i see the same error `unable to start peer: unable to read init msg: EOF`

I tried already clearing the tor cache/rebooting but every channel gets back up but the ones from mentioned nodes.

Debug Log grepped to `02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c`:
```
2021-08-15 19:24:49.495 [DBG] PRNF: PeerNotifier notifying peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c online
2021-08-15 19:24:49.497 [DBG] PEER: Sending Init to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:24:49.841 [INF] PEER: disconnecting 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, reason: unable to start peer: unable to read init msg: EOF
2021-08-15 19:24:49.841 [DBG] SRVR: Peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 has been disconnected
2021-08-15 19:24:49.841 [DBG] FNDG: Cancelling all reservations for peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
2021-08-15 19:24:49.841 [DBG] FNDG: No active reservations for node: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
2021-08-15 19:24:49.841 [DBG] SRVR: Notifying that peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 is offline
2021-08-15 19:24:49.841 [DBG] SRVR: removing peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:24:49.841 [DBG] PRNF: PeerNotifier notifying peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c offline
2021-08-15 19:24:49.841 [DBG] SRVR: Scheduling connection re-establishment to persistent peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 in 19.4481s
2021-08-15 19:24:49.842 [DBG] BTCN: Disconnected from 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 201)
2021-08-15 19:24:55.465 [DBG] BTCN: Ignoring connection for canceled conn req: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@yocrhxpg2hkof6xeaz4zsjtwmbbcu6xvwvb7dazf2lkbslwylkqzrwad.onion:9735 (reqid 81)
2021-08-15 19:25:09.290 [DBG] SRVR: Attempting to re-establish persistent connection to peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:09.290 [DBG] BTCN: Attempting to connect to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 202)
2021-08-15 19:25:09.893 [DBG] BTCN: Connected to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 202)
2021-08-15 19:25:09.893 [INF] SRVR: Established connection to: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:09.893 [INF] SRVR: Finalizing connection to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, inbound=false
2021-08-15 19:25:09.893 [DBG] PRNF: PeerNotifier notifying peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c online
2021-08-15 19:25:09.895 [DBG] PEER: Sending Init to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:10.235 [INF] PEER: disconnecting 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, reason: unable to start peer: unable to read init msg: EOF
2021-08-15 19:25:10.235 [DBG] SRVR: Peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 has been disconnected
2021-08-15 19:25:10.235 [DBG] FNDG: Cancelling all reservations for peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
2021-08-15 19:25:10.235 [DBG] FNDG: No active reservations for node: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
2021-08-15 19:25:10.235 [DBG] SRVR: Notifying that peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 is offline
2021-08-15 19:25:10.235 [DBG] SRVR: removing peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:10.235 [DBG] PRNF: PeerNotifier notifying peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c offline
2021-08-15 19:25:10.236 [DBG] SRVR: Scheduling connection re-establishment to persistent peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 in 40.84101s
2021-08-15 19:25:10.236 [DBG] BTCN: Disconnected from 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 202)
2021-08-15 19:25:51.077 [DBG] SRVR: Attempting to re-establish persistent connection to peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:51.077 [DBG] BTCN: Attempting to connect to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 205)
2021-08-15 19:25:51.621 [DBG] BTCN: Connected to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 205)
2021-08-15 19:25:51.621 [INF] SRVR: Established connection to: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:51.621 [INF] SRVR: Finalizing connection to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, inbound=false
2021-08-15 19:25:51.621 [DBG] PRNF: PeerNotifier notifying peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c online
2021-08-15 19:25:51.623 [DBG] PEER: Sending Init to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:51.883 [INF] PEER: disconnecting 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, reason: unable to start peer: unable to read init msg: EOF
2021-08-15 19:25:51.884 [DBG] SRVR: Peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 has been disconnected
2021-08-15 19:25:51.884 [DBG] FNDG: Cancelling all reservations for peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
2021-08-15 19:25:51.884 [DBG] FNDG: No active reservations for node: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
2021-08-15 19:25:51.884 [DBG] SRVR: Notifying that peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 is offline
2021-08-15 19:25:51.884 [DBG] SRVR: removing peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-15 19:25:51.884 [DBG] PRNF: PeerNotifier notifying peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c offline
2021-08-15 19:25:51.884 [DBG] SRVR: Scheduling connection re-establishment to persistent peer 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 in 1m25.766121s
2021-08-15 19:25:51.884 [DBG] BTCN: Disconnected from 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735 (reqid 205)

```

**Comment by Dikay900** [comment] 2021-08-15 20:54
geez, seems like the node i have now for reproducing this issue is offline for other people as well so closing this for now...

**Comment by Dikay900** [comment] 2021-08-19 12:42
reopening since i have new multiple channels / peers with such an behaviour.
I am able to connect to these peers, open a channel but after restarting LND i cannot get a connection until after the channel is closed again.

Nodes:
1. 0234227bdcd0361622f39447f961618480e7347ab1cfe6e74f561b976135343b31
2. 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c

I force closed the channel to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c. After that i could connect to the peer and create a new channel. Now after restarting LND i cannot connect again.
Same for 0318ac9faa9629e7da08819bc8fe0dd2ae3044d69b1b2283a63479acffeb968483 who remote force closed their channel last time. After the close i can now sucessfully connect again.
I do not think this is not a coincidence.

Can i somehow debug this?

**Comment by cryptosharks131** [comment] 2021-08-19 12:43
I am also seeing this issue with one of my peers.  No connections issues with other peers but this one in particular and specifically after they updated to v0.13.1. After this first occurred, closing the existing channel and recreating it seemed to solve the issue. However, now the issue seems to be occurring again after a few days of having the new channel open.

Trying to connect over clearnet yields:
```
2021-08-19 12:22:19.374 [INF] SRVR: Established connection to: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
2021-08-19 12:22:19.375 [INF] SRVR: Finalizing connection to 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, inbound=false
2021-08-19 12:22:19.772 [INF] PEER: disconnecting 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735, reason: unable to start peer: unable to read init msg: EOF
```

Connecting over tor seems to yield a different error:
```
unknown error TTL expired
```

**Comment by Dikay900** [comment] 2021-08-19 12:51
just checked for the same for 0234227bdcd0361622f39447f961618480e7347ab1cfe6e74f561b976135343b31 I am getting on both clearnet and onionnet the same error
`reason: unable to start peer: unable to read init msg: EOF`

@cryptosharks131 can you try to connect to this node as well? I would assume if you do not have an open channel to them you will be able to connect, else not.

**Comment by cryptosharks131** [comment] 2021-08-19 13:02
Strangely enough I did not see this issue for peer ``0234227bdcd0361622f39447f961618480e7347ab1cfe6e74f561b976135343b31`` previously but I currently have a channel pending force close with them.  What is really weird is that my node force closed the channel with them for no apparent reasons when checking the logs (no reason given).

```
2021-08-19 11:26:14.647 [ERR] LTND: Unable to lookup witness: no witnesses
2021-08-19 11:26:14.723 [INF] CNCT: ChannelArbitrator(xxxxxxxxxxxx): force closing chan
2021-08-19 11:26:14.735 [INF] HSWC: Removing channel link with ChannelID(xxxxxxxxxxxx)
2021-08-19 11:26:14.783 [INF] CNCT: Broadcasting force close transaction...........
```

But in short, I am connected to them still currently so the connection attempt was not necessary.  The only change I can tell is that I have recently started running v0.13.1 in the past week or so from a previous version v0.12.1.

**Comment by cryptosharks131** [comment] 2021-08-20 13:50
Looks like in the past few days these three peers you have listed all have had a lot of channel closing activity.  Some of them are even down almost 50% capacity from all the channel closes.  Nonetheless, the issue seems to be common between these peers though and not necessarily with our side of the channel.

**Comment by BhaagBoseDK** [comment] 2021-08-20 16:17
I have same issue too coming in my logs
`
25:41.538 [INF] PEER: unable to read message from 02e176cb42623b6949a2fa3adc0b329cd6445971f508f443caf91faf0594a08915@uawtmoup24amhb3rnodpbgepw3pq6e22v5z2c3jvapnipft2o44aspad.onion:9735: EOF
2021-08-20 14:25:41.537 [INF] PEER: unable to read message from 031e24b91156f948a47198d807ae24e98fd31e8f5edfe6a3d7cd37d4196b1a3752@10.21.21.11:55024: EOF
2021-08-20 14:25:41.537 [INF] PEER: unable to read message from 03f7261f79d54afd6737d7a0e27861a0fc3b0a882317c4d90aff7770859562f9af@10.21.21.11:55280: EOF
2021-08-20 14:25:41.543 [INF] PEER: unable to read message from 03b49dab6025517f2dc5bc81580ce125a15d072091e2c5e8965b9415cc65deba1c@10.21.21.11:35264: EOF
2021-08-20 14:25:41.543 [INF] PEER: unable to read message from 03b9bfbfee5464048eea9f01a0e41a0e029a019e7df6fb5ce41299e75a369e2f3f@10.21.21.11:54290: EOF
2021-08-20 14:25:41.544 [INF] PEER: unable to read message from 033878501f9a4ce97dba9a6bba4e540eca46cb129a322eb98ea1749ed18ab67735@92.245.194.234:9735: EOF
2021-08-20 14:25:41.549 [INF] PEER: unable to read message from 0297fc579bb3476cf486cc39de0bf8478e4c04f16a8954d57bcc442ac505e5c9ff@pkifn4jokx6fnjvwerljnenuwcg45nsqikiml6n3nwhx5n4chal7e6qd.onion:9735: EOF
2021-08-20 14:25:41.550 [INF] PEER: unable to read message from 0398866fca94f17d9054d586ac88a24faf1450296f80a382b08416337d8c6260fe@10.21.21.11:40098: EOF
2021-08-20 14:25:41.550 [INF] PEER: unable to read message from 03f10c03894188447dbf0a88691387972d93416cc6f2f6e0c0d3505b38f6db8eb5@sdk3hj73zwzwxalsvq2yp4r3ozdz33fagjfo2edux5d2vhlhd2phewad.onion:9735: EOF
2021-08-20 14:25:41.575 [INF] PEER: unable to read message from 034a29e256807da8cbe4fbbdba6f2c79ee02ba3d6536f71da610e5ec5999d6107e@h4cj52pdkobtfvqfz4ctl2mcqoqe2qncdjkwo5sqxqcjigblligmmnad.onion:9735: EOF
2021-08-20 14:25:41.577 [INF] PEER: unable to read message from 02ee625bb15e64a4b053c31d111ee608a4300f7661f55d0635a0dd08cab52e9025@wvkojgosumfd254bmrylcq5oundihujroenv4ow7gdeosuwwyehxbmqd.onion:9735: EOF
2021-08-20 14:25:41.577 [INF] PEER: unable to read message from 021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d@54.184.88.251:9735: EOF
2021-08-20 14:25:41.577 [INF] PEER: unable to read message from 03d67293bea1d531353a5026d752783628ef15f285fb00207b4eb72185674e9ec5@10.21.21.11:42838: EOF
2021-08-20 14:25:41.582 [INF] PEER: unable to read message from 0307eafebbf6583eaf3dce69181018185b193414901c029e98062455e328c76bf3@10.21.21.11:39720: EOF
2021-08-20 14:25:41.582 [INF] PEER: unable to read message from 03ce61cb90aa08f4b19b28d8393fa39d107fefa3ff8d303808449ed0853487d150@10.21.21.11:50290: EOF
2021-08-20 14:25:41.582 [INF] PEER: unable to read message from 0387d57be12709c8745bc35ac3dfc22611a944a12bcc1fe49a55d7c9bafea335f9@10.21.21.11:34706: EOF
2021-08-20 14:25:41.583 [INF] PEER: unable to read message from 03675abead8c476de5a28f635d4f1516500a0fbd79fe42c3f23e974754af5d48b7@2vyrqbaldjxdgyy7mo445kzkgpmkfgpctejekcmoibooecamkf3h2qyd.onion:9735: EOF
2021-08-20 14:25:41.587 [INF] PEER: unable to read message from 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@34.239.230.56:9735: EOF
2021-08-20 14:25:41.587 [INF] PEER: unable to read message from 030f43bc18cea01f020b60875b0f48574a8149d0ba6b8fc377b5c8d991695c827a@qw7ckl3nngdlztt4uqvy2ysiynunpztpulc4kin46mkk4dvrn2dbesid.onion:9735: EOF
2021-08-20 14:25:41.588 [INF] PEER: unable to read message from 02e98e5929c25f16f7c15b9026b9986e32dc36ba62c6497f436984b40fc3f0d7ac@uagt7hb6nw2dkv3gy2madsj4uu3xlpe47en7gtr7pilrvcse4j4pc4yd.onion:9735: EOF
2021-08-20 14:25:41.588 [INF] PEER: unable to read message from 037659a0ac8eb3b8d0a720114efc861d3a940382dcfa1403746b4f8f6b2e8810ba@172.65.217.219:9735: EOF
2021-08-20 14:25:41.592 [INF] PEER: unable to read message from 033e7e466c56c51f53723fb966674db881b5aae8907e22170d630fb1b149f55ee3@10.21.21.11:54008: EOF
2021-08-20 14:25:41.593 [INF] PEER: unable to read message from 035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226@170.75.163.209:9735: EOF
2021-08-20 14:25:41.593 [INF] PEER: unable to read message from 0368c14e0abf3e503a6d562fc2d4e8e3d5befbd9ec9cd231f0aa3e4e9ea7c3c00a@10.21.21.11:54184: EOF
2021-08-20 14:25:41.593 [INF] PEER: unable to read message from 03212562564b3be0b44cd1ac577007b20dcaeeb7d393845a7c75eed958c53b728a@ugs3rswnba3aweqtnyuhowqrqwp5as3hpspw4ngbj52vgiuh3v7kmnad.onion:9735: EOF
2021-08-20 14:26:50.578 [INF] PEER: unable to read message from 02e330447ed6e20f32028ba9717136679c0cc398b3b4858e0dcbdeef6931837b38@10.21.21.11:40816: EOF
2021-08-20 14:32:35.012 [INF] PEER: unable to read message from 030f43bc18cea01f020b60875b0f48574a8149d0ba6b8fc377b5c8d991695c827a@qw7ckl3nngdlztt4uqvy2ysiynunpztpulc4kin46mkk4dvrn2dbesid.onion:9735: EOF
2021-08-20 14:38:21.280 [INF] PEER: unable to read message from 03496bcfbd4a04c01ba6d29ef68aef32fd723b4de9225d2676beabcb25be4289ee@10.21.21.11:47734: EOF
2021-08-20 14:38:21.303 [INF] PEER: unable to read message from 0268b1105ed1509f93efe38fe42304c96f4c65697bd99880940e16559d694475e7@10.21.21.11:39846: EOF
2021-08-20 14:38:21.454 [INF] PEER: unable to read message from 03ee7d1e4598b09e63f83ae5a39d6dff23cdc8ba963b93aafa861c544de08fd82c@tw7c23pogoyie4fpxzkdtg5f3dltgboj4rofjr5itgykm62wwwb332yd.onion:9735: EOF
2021-08-20 14:38:21.573 [INF] PEER: unable to read message from 02d08d6f7389de7a92be30f17220d631c8533fc11f355bb18910f27158367e95ad@c4nzoqc2pz74kpbjykjg6sv5qiti54gihcqo7wpluox32u3b37nasyyd.onion:9735: EOF
2021-08-20 14:38:22.245 [INF] PEER: unable to read message from 03d4e028a0d4a90868ec202ab684fb0085779defea9ca7553e06146557631eec20@10.21.21.11:56444: EOF
2021-08-20 14:39:14.226 [INF] PEER: unable to read message from 03675abead8c476de5a28f635d4f1516500a0fbd79fe42c3f23e974754af5d48b7@10.21.21.11:51220: EOF
2021-08-20 14:39:30.765 [INF] PEER: unable to read message from 033878501f9a4ce97dba9a6bba4e540eca46cb129a322eb98ea1749ed18ab67735@92.245.194.234:9735: EOF
2021-08-20 15:02:53.151 [INF] PEER: unable to read message from 0379571978492c8de286d906d194966d94b5fbd7cb49d8751261cf9ab49c33543a@10.21.21.11:51222: EOF
2021-08-20 15:11:49.153 [INF] PEER: unable to read message from 0337694505123a12a8fadd95523dcc235898ad3b80a06e4a63ca26fed68dd0d17c@10.21.21.11:51038: EOF
2021-08-20 15:15:35.626 [INF] PEER: unable to read message from 03fc8aaec61b42da62e36f5473623ca9b91285d7af62c6189d14bcf84c549d473b@10.21.21.11:43656: EOF
2021-08-20 15:20:31.279 [INF] PEER: unable to read message from 03ce61cb90aa08f4b19b28d8393fa39d107fefa3ff8d303808449ed0853487d150@10.21.21.11:51270: EOF
2021-08-20 15:24:44.126 [INF] PEER: unable to read message from 03ce61cb90aa08f4b19b28d8393fa39d107fefa3ff8d303808449ed0853487d150@ldjvnzkxgex436qvsooasg7d2q2s3icaubaiev7slkruy72hvedvddad.onion:9735: EOF
2021-08-20 15:27:18.406 [INF] PEER: unable to read message from 0218c0c7455899d13627a4bc64b1681f33ee262e86282158b31eccdf8251596e87@10.21.21.11:51198: EOF
2021-08-20 15:27:23.596 [INF] PEER: disconnecting 0218c0c7455899d13627a4bc64b1681f33ee262e86282158b31eccdf8251596e87@n2jinjhosvowymkgqg34obkfljbnlhrj44yntopogslcfbgsv4i4vmad.onion:9735, reason: unable to start peer: unable to read init msg: EOF
2021-08-20 15:33:11.597 [INF] PEER: unable to read message from 035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226@170.75.163.209:9735: EOF
2021-08-20 15:54:43.616 [INF] PEER: unable to read message from 03ce61cb90aa08f4b19b28d8393fa39d107fefa3ff8d303808449ed0853487d150@10.21.21.11:35662: EOF
`

**Comment by BhaagBoseDK** [comment] 2021-08-20 16:22
same error when we try to connect to 03212562564b3be0b44cd1ac577007b20dcaeeb7d393845a7c75eed958c53b728a
My lnd
lncli version 0.12.1-beta commit=v0.12.1-beta

**Comment by cryptosharks131** [comment] 2021-08-20 16:36
Looking at your logs @BhaagBoseDK it seems you have the same error mentioned above but for this peer `0218c0c7455899d13627a4bc64b1681f33ee262e86282158b31eccdf8251596e87`. I tested a connection to the peer myself and had no issues connecting to them.  I am guessing that you have or recently had a channel open with this peer already?

Also a note, the peer's age is very low (5 days) so it could be more likely they are running `v0.13.1`.

**Comment by BhaagBoseDK** [comment] 2021-08-20 16:40
can you connect/open channel to 03212562564b3be0b44cd1ac577007b20dcaeeb7d393845a7c75eed958c53b728a?

0218c0c7455899d13627a4bc64b1681f33ee262e86282158b31eccdf8251596e87 -> I will try to reach out to peer to see what the issue is on their end if any.

**Comment by BhaagBoseDK** [comment] 2021-08-20 16:43
just got these 3 again (I do not have channel with them)
2021-08-20 16:29:14.138 [INF] PEER: unable to read message from 0307eafebbf6583eaf3dce69181018185b193414901c029e98062455e328c76bf3@10.21.21.11:52614: EOF
2021-08-20 16:32:35.914 [INF] PEER: unable to read message from 020df9bce498c3063f8046dcf036f075556628a2165958e7e5f35838e3534e6c41@10.21.21.11:43650: EOF
2021-08-20 16:35:36.770 [INF] PEER: unable to read message from 0297fc579bb3476cf486cc39de0bf8478e4c04f16a8954d57bcc442ac505e5c9ff@10.21.21.11:51266: EOF

**Comment by Roasbeef** [comment] 2021-08-22 18:46
If you're having an issue with _specific_ peers, then it likely isn't an `lnd` issue, and instead it may be the peer itself having networking issues. 

Also note that if you need to restart `lnd`, then you may also need to restart `tor` itself if you need to re-establish a brand new hidden service.

**Closed by Roasbeef** 2021-08-22 18:46 UTC
