### ISSUE TITLE
lnd segfaults when I run restorechanbackup

### ISSUE THREAD

**Issue by bob-333** [lightningnetwork/lnd#3180] opened 2019-06-09 23:40 UTC
### Background

I've been having an issue with a bad channel since February. See my comments in #2582. For a while I was unable to run lnd any more - it would crash every time I started it, but I worked around that by blocking the IP of the peer on the other end of the bad channel at the firewall level.

Then yesterday I noticed I was unable to make a particular payment using my node. I tried 10 different routes and they all failed. I hadn't updated lnd from git for a while, so tried that. After updating I was unable to run lnd. It was failing with the same error as in #2582, even though the IP address was still blocked on the firewall. Luckily I had kept a backup of the full .lnd folder from just before updating lnd, so was able to rebuild the old code (commit 3a19afe4) and get lnd running again.

I was advised on the slack that I should shut down all my existing channels and start fresh, to avoid anyone having to mess about with the db to fix this bug, so that's what I did. I've closed all the channels except the broken one.

I tried exporting backup data from the broken channel, making a new node with the same wallet seed phrase and importing it there, but that causes the new lnd node to crash. I tried again, this time waiting a few hours for the new node to scan the whole blockchain to get all the onchain transactions into its db, but it made no difference; the restorechanbackup still crashes lnd.

On the old node I ran:

```
$ lncli exportchanbackup --chan_point=067119f4d38dec2d15fb1e1fc88176fc0504801245f11d5bd74371e137c2502c:0
{
	"chan_point": "067119f4d38dec2d15fb1e1fc88176fc0504801245f11d5bd74371e137c2502c:0",
	"chan_backup": "b99b0726943f926a8a2aa431cf4b873005bd440f34d49a17bba4aae451aa1fe11ca7ca84c2a51cf440158dbfe16fcaa77cabbc4242afdfe14a4567819123bdb560055d5af97e879d1fccc4ffea2d953746475c88c004f8d759c24e61c7ae667b4619a7707c56cebf10ecdfa4d766a25cda73571c7c66da694fb114e0c1f77c48d9e92dd19b22eb9544d7e3e2bd2bb7afc8128dbd0ad135319a2448cd43345fc15b4b69fac430243f1616f3ba0a4a8911e9c51a603fbbd7405f3b01eb02e20d1b13dfbe8f99bab9604a0832bbc7c990905351267503518b6707f8c95e1e7655f4d5340530cdd6999c8ab21f33084afcb7fe9d7854783fb0a028146acfc2ec3658601daf802fb7fef2ae1a1aa0ef7041d547299e3e2c1655c9948dcecfb468cccbdfd05a11c9906b6542a6dfde9ac0613994513fedc4c67a71e7864659cc6148bbeb00f83552296706aa6d543c95c61a45912fe0ba787b59bdf19c4f8253ade11e58050ac5a7241a6d56982142658fad41992948e8619731b235fd206fa669938daeeda2c4ca5bdab6301170970714e80cc3b4aae85e96394830b57c2006b9eef078df2e676308a4923bb6a419341269abf93bac2c6a"
}
```

then on the new node:

```
$ lncli verifychanbackup --single_backup=b99b0726943f926a8a2aa431cf4b873005bd440f34d49a17bba4aae451aa1fe11ca7ca84c2a51cf440158dbfe16fcaa77cabbc4242afdfe14a4567819123bdb560055d5af97e879d1fccc4ffea2d953746475c88c004f8d759c24e61c7ae667b4619a7707c56cebf10ecdfa4d766a25cda73571c7c66da694fb114e0c1f77c48d9e92dd19b22eb9544d7e3e2bd2bb7afc8128dbd0ad135319a2448cd43345fc15b4b69fac430243f1616f3ba0a4a8911e9c51a603fbbd7405f3b01eb02e20d1b13dfbe8f99bab9604a0832bbc7c990905351267503518b6707f8c95e1e7655f4d5340530cdd6999c8ab21f33084afcb7fe9d7854783fb0a028146acfc2ec3658601daf802fb7fef2ae1a1aa0ef7041d547299e3e2c1655c9948dcecfb468cccbdfd05a11c9906b6542a6dfde9ac0613994513fedc4c67a71e7864659cc6148bbeb00f83552296706aa6d543c95c61a45912fe0ba787b59bdf19c4f8253ade11e58050ac5a7241a6d56982142658fad41992948e8619731b235fd206fa669938daeeda2c4ca5bdab6301170970714e80cc3b4aae85e96394830b57c2006b9eef078df2e676308a4923bb6a419341269abf93bac2c6a
{

}
$ lncli restorechanbackup --single_backup=b99b0726943f926a8a2aa431cf4b873005bd440f34d49a17bba4aae451aa1fe11ca7ca84c2a51cf440158dbfe16fcaa77cabbc4242afdfe14a4567819123bdb560055d5af97e879d1fccc4ffea2d953746475c88c004f8d759c24e61c7ae667b4619a7707c56cebf10ecdfa4d766a25cda73571c7c66da694fb114e0c1f77c48d9e92dd19b22eb9544d7e3e2bd2bb7afc8128dbd0ad135319a2448cd43345fc15b4b69fac430243f1616f3ba0a4a8911e9c51a603fbbd7405f3b01eb02e20d1b13dfbe8f99bab9604a0832bbc7c990905351267503518b6707f8c95e1e7655f4d5340530cdd6999c8ab21f33084afcb7fe9d7854783fb0a028146acfc2ec3658601daf802fb7fef2ae1a1aa0ef7041d547299e3e2c1655c9948dcecfb468cccbdfd05a11c9906b6542a6dfde9ac0613994513fedc4c67a71e7864659cc6148bbeb00f83552296706aa6d543c95c61a45912fe0ba787b59bdf19c4f8253ade11e58050ac5a7241a6d56982142658fad41992948e8619731b235fd206fa669938daeeda2c4ca5bdab6301170970714e80cc3b4aae85e96394830b57c2006b9eef078df2e676308a4923bb6a419341269abf93bac2c6a
[lncli] unable to restore chan backups: rpc error: code = Unavailable desc = transport is closing
$ 
```

and at that point lnd is dead:

```
2019-06-09 23:26:23.864 [INF] CRTR: New channel discovered! Link connects 0216006237022044d9bdb73ca51af267c5f67cf76095b4c6275f1162eb422fed68 and 039ceed5a1c064a36f71dcfc300fa622ef11a879a7a4e7c8b8fd328250b74c6855 with ChannelPoint(f1786980684b21374969a193d0b49412b8ff279127d88b6f5b136dd2af2bb8cc:1): chan_id=613948601342689281, capacity=0.0177402 BTC
2019-06-09 23:26:24.014 [INF] CRTR: Updated vertex data for node=039ceed5a1c064a36f71dcfc300fa622ef11a879a7a4e7c8b8fd328250b74c6855
2019-06-09 23:26:24.254 [INF] CRTR: New channel discovered! Link connects 027cf99e95e346897a6f88212d5240fa790e3b4c97581bcffa354de10128998ce7 and 02c287d1be9c9fa13d4ded0b0432b7e2367b1b20d822ab76546c4bb67cac1bc6e1 with ChannelPoint(940f1297a29c45f309d3a46e1d83b9eaf91b2324e47fa1d08fab434b58ab7e2d:1): chan_id=613948601396887553, capacity=0.00629808 BTC
2019-06-09 23:26:24.740 [INF] LTND: Inserting 1 SCB channel shells into DB
2019-06-09 23:26:24.894 [INF] CRTR: New channel discovered! Link connects 032679fec1213e5b0a23e066c019d7b991b95c6e4d28806b9ebd1362f9e32775cf and 03c44a3fef1637aae26c96bbe932baf5094b6f48a060d8944bd32d4f67032cc027 with ChannelPoint(e838784d32d818763a383ad8726788f969ad1169fbe0079e66de424afb788d45:1): chan_id=613949700886167553, capacity=0.005 BTC
2019-06-09 23:26:24.994 [INF] CRTR: New channel discovered! Link connects 0377c9f9105f3decdd06962f164001982de9f26a28b1f21a1a9ebcc160d13e6574 and 03b0318fecc7e8165c49053a944e5ceb9d4feb0d08a5db78794d9230c8c8193513 with ChannelPoint(ef24e5cee7a0711e05737d4d174b01619e8abf4cdbea67bef28837b8a190865b:0): chan_id=613950800305520640, capacity=0.005 BTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9c17bb]

goroutine 3342 [running]:
github.com/lightningnetwork/lnd/channeldb.(*DB).RestoreChannelShells.func1(0xc010b0e0e0, 0x127d4e0, 0xc010b0e0e0)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:923 +0xcb
github.com/coreos/bbolt.(*DB).Update(0xc00001a000, 0xc001f89040, 0x0, 0x0)
	/home/light/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/db.go:688 +0x90
github.com/lightningnetwork/lnd/channeldb.(*DB).RestoreChannelShells(0xc00000c260, 0xc0017c4110, 0x1, 0x1, 0x0, 0x0)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:921 +0x130
github.com/lightningnetwork/lnd.(*chanDBRestorer).RestoreChansFromSingles(0xc011030d60, 0xc000aca600, 0x1, 0x1, 0x1, 0x1)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/chanrestore.go:129 +0x2a4
github.com/lightningnetwork/lnd/chanbackup.Recover(0xc000aca180, 0x1, 0x1, 0x1388620, 0xc011030d60, 0x1388680, 0xc00001a600, 0x1, 0x0)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/chanbackup/recover.go:49 +0x1ff
github.com/lightningnetwork/lnd/chanbackup.UnpackAndRecoverSingles(0xc011030d80, 0x1, 0x1, 0x7fc1d1adcbc0, 0xc0004ac960, 0x1388620, 0xc011030d60, 0x1388680, 0xc00001a600, 0xc012546240, ...)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/chanbackup/recover.go:95 +0xd9
github.com/lightningnetwork/lnd.(*rpcServer).RestoreChannelBackups(0xc0002460a0, 0x1395300, 0xc012cdca80, 0xc012cdcab0, 0xc0002460a0, 0xc011030aa0, 0xc000276d20)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:4825 +0x2fd
github.com/lightningnetwork/lnd/lnrpc._Lightning_RestoreChannelBackups_Handler.func1(0x1395300, 0xc012cdca80, 0x1086720, 0xc012cdcab0, 0x1, 0x1, 0x0, 0x0)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:11385 +0x89
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0x1395300, 0xc012cdca80, 0x1086720, 0xc012cdcab0, 0xc011030a80, 0xc011030aa0, 0xf7e8c0, 0x1c67b28, 0x10d29c0, 0xc01296c100)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:125 +0x153
github.com/lightningnetwork/lnd/lnrpc._Lightning_RestoreChannelBackups_Handler(0x10f5860, 0xc0002460a0, 0x1395300, 0xc012cdca80, 0xc0002f7180, 0xc010a780e0, 0x0, 0x0, 0xc0126da1c0, 0x1be)
	/home/light/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:11387 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004bb080, 0x139cd00, 0xc000aca000, 0xc01296c100, 0xc010a7c210, 0x1c22520, 0x0, 0x0, 0x0)
	/home/light/gocode/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x4a2
google.golang.org/grpc.(*Server).handleStream(0xc0004bb080, 0x139cd00, 0xc000aca000, 0xc01296c100, 0x0)
	/home/light/gocode/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd58
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc012d6c450, 0xc0004bb080, 0x139cd00, 0xc000aca000, 0xc01296c100)
	/home/light/gocode/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/light/gocode/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
```

### Your environment

* version of `lnd`: old node: commit 3a19afe4, new node: commit e45d4d70
* which operating system: Linux 4.9.0-7-amd64
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core 0.17.0
* any other relevant environment details

**Comment by Roasbeef** [comment] 2019-06-12 03:40
Is this reproducible? If you make a new clean `lnd` version, and then input the seed, later on using the `restorechanbackup` command, do you get the same result?

**Comment by Crypt-iQ** [comment] 2019-06-30 13:08
It's because when deriving the private key for the shachain root, no error is returned 

https://github.com/lightningnetwork/lnd/blob/6a4179e2248236a8f2cb96c6a7fed095069915bb/chanrestore.go#L42-L45

**Comment by Roasbeef** [comment] 2019-07-01 22:40
Fixed by #3257

**Closed by Roasbeef** 2019-07-01 22:40 UTC

**Comment by dooglus** [comment] 2019-08-15 12:37
@Roasbeef > Is this reproducible? If you make a new clean lnd version, and then input the seed, later on using the restorechanbackup command, do you get the same result?

Yes. I just tried that with the `v0.7.1-beta` lnd and it no longer crashes.

Now it says this instead:

`[lncli] unable to restore chan backups: rpc error: code = Unknown desc = unable to unpack single backups: unable to derive shachain root key: unable to derive private key`

**Comment by Roasbeef** [comment] 2019-08-15 22:59
@dooglus in your case, how manny channels had been created for that node before it created a backup? More than 100k?

**Comment by dooglus** [comment] 2019-08-15 23:12
I really doubt it. I think I have only ever had 1 channel with that node.

**Comment by Roasbeef** [comment] 2019-08-15 23:26
When was this SCB created? Was it perhaps during one of the release candidates or from a node built on some intermediate master branch?
