### ISSUE TITLE
lnd crashing when calling lncli addinvoice

### ISSUE THREAD

**Issue by pldelattre** [lightningnetwork/lnd#1289] opened 2018-05-26 23:36 UTC
### Background

LND Crashing when calling lncli addinvoice

### Your environment

* lnd commit 6a2a049df13103918546a3fc83d65862b68d9708
* Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
* bitcoind 0.16 -testnet

lnd.conf 
```
[Application Options]
debuglevel=debug
debughtlc=true
maxpendingchannels=10
noencryptwallet=1
listen=0.0.0.0:9735

[Bitcoin]
bitcoin.active=1
;bitcoin.mainnet=1
bitcoin.testnet=1
bitcoin.node=bitcoind

[Autopilot]
autopilot.active=1
autopilot.maxchannels=10
autopilot.allocation=1.0
```

### Steps to reproduce

"Lncli addinvoice" crashes lnd but not always. It seems that it happens only after a certain amount of time (1 minute). 

This is new. I used to call this command many times in the past without any issue with the same version of lnd. Only change is that I switched from mainnet to testnet 

### Expected behaviour

Generate Invoice  instead of crashing lnd

### Actual behaviour

Crash LND 

```
2018-05-27 01:19:33.041 [DBG] CRTR: New channel update applied: (*channeldb.ChannelEdgePolicy)(0x124879a0)({
 SigBytes: ([]uint8) (len=71 cap=71) {
  00000000  30 45 02 21 00 81 dc 73  e6 55 8a c0 81 d1 2f 92  |0E.!...s.U..../.|
  00000010  9c 3b f3 eb 58 1b f1 5c  bf aa d3 e5 ab 6c f9 e8  |.;..X..\.....l..|
  00000020  eb e2 89 2e e1 02 20 15  d1 50 e8 72 5c 76 81 a3  |...... ..P.r\v..|
  00000030  1b 58 0a cc 38 3e d7 5a  64 da 3b b7 fe 83 f7 b5  |.X..8>.Zd.;.....|
  00000040  16 0a 2d 15 b9 be 62                              |..-...b|
 },
 sig: (*btcec.Signature)(<nil>),
 ChannelID: (uint64) 1427361805929545728,
 LastUpdate: (time.Time) 2018-05-27 01:19:21 +0200 CEST,
 Flags: (lnwire.ChanUpdateFlag) 1,
 TimeLockDelta: (uint16) 6,
 MinHTLC: (lnwire.MilliSatoshi) 1000 mSAT,
 FeeBaseMSat: (lnwire.MilliSatoshi) 1 mSAT,
 FeeProportionalMillionths: (lnwire.MilliSatoshi) 10 mSAT,
 Node: (*channeldb.LightningNode)(<nil>),
 db: (*channeldb.DB)(<nil>)
})

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x7015a8]

goroutine 50117 [running]:
main.(*rpcServer).AddInvoice(0x124d4140, 0xaea3b8, 0x13578860, 0x12452120, 0x124d4140, 0x13a05ee0, 0x1230c408)
        /home/pi/go/src/github.com/lightningnetwork/lnd/rpcserver.go:2323 +0xd14
github.com/lightningnetwork/lnd/lnrpc._Lightning_AddInvoice_Handler.func1(0xaea3b8, 0x13578860, 0x8baba0, 0x12452120, 0x1, 0x1, 0x0, 0x0)
        /home/pi/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:5889 +0x68
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0xaea3b8, 0x13578860, 0x8baba0, 0x12452120, 0x13a05ed0, 0x13a05ee0, 0x5288cc, 0x126d0d3c, 0x5279a0, 0x30)
        /home/pi/go/src/github.com/lightningnetwork/lnd/macaroons/service.go:117 +0x108
github.com/lightningnetwork/lnd/lnrpc._Lightning_AddInvoice_Handler(0x8cc9a0, 0x124d4140, 0xaea3b8, 0x13578860, 0x126c5e60, 0x1248c130, 0x0, 0x0, 0x127f8c05, 0x9)
        /home/pi/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:5891 +0x124
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x126c0180, 0xaece80, 0x124ca0f0, 0x1268a750, 0x124d4240, 0xefee6c, 0x1373caa0, 0x0, 0x0)
        /home/pi/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x7c0
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0x126c0180, 0xaece80, 0x124ca0f0, 0x1268a750, 0x1373caa0)
        /home/pi/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1054
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0x13f39c30, 0x126c0180, 0xaece80, 0x124ca0f0, 0x1268a750)
        /home/pi/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x7c
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/pi/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0x7c
```

**Comment by Roasbeef** [comment] 2018-05-26 23:42
Hmm, that line doesn't match up with the current master. If you update to the latest version of `lnd`, are you able to reproduce? 

> noencryptwallet=1
I'd recommend creating an entirely new instance. As you have wallet encryption de-activated, you didn't receive a seed. As a result, if anything happens, you'll have no way of recovering _any_ of your funds. Also `debughtlc` shouldn't be used on mainnet either, as it can allow you to create an outgoing HTLC which everyone by default knows the pre-image to, possibly leading to a loss of funds.

**Comment by pldelattre** [comment] 2018-05-26 23:58
Updated to latest lnd. I cannot reproduce the issue for the moment. I will keep you updated if it fails again. 

Regarding noencryptwallet and debughtlc, thanks for the explanations. I will disable them when switching back to mainnet.

**Comment by Roasbeef** [comment] 2018-05-27 00:01
> Regarding noencryptwallet and debughtlc, thanks for the explanations. I will disable them when switching back to mainnet.

They can't simply be disabled. You should instead close out all your old channels, create a new instance, then send over the coins from the old node to the new. The coins under control of the new node will then be protected under your seed.

**Comment by Roasbeef** [comment] 2018-05-28 03:36
Closing for now as unable to reproduce after upgrading to the latest version of master. If you can repro, just ping here, and we'll re-open and get to the bottom of it. Thanks!

**Closed by Roasbeef** 2018-05-28 03:36 UTC
