### ISSUE TITLE
High CPU load with no reason

### ISSUE THREAD

**Issue by babaiants** [lightningnetwork/lnd#3668] opened 2019-11-02 21:35 UTC
### Background
I am working on a project where I need to run lots of lnd processes on a single machine. So, I started 16 lnd services and they updated their graph DBs (channel.db). The CPU usage slowed down after that. Then a few hours later a few of the processes (could be any lnd processes, not specific ones) started heavely loading CPU with no reason.  I mean I did not send any transactions. They are all in idle mode.  The only way to stop the high CPU usage is to restart these services, but in a few hours another ones will do the same.

### Your environment

* version of `lnd` -  0.8.0-beta
* which operating system (`uname -a` on *Nix) CentOS 7 (with all updates)
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v0.18.1

### **I attached a couple of *.svg files,** which I hope to help understand what's going on.

[svg.zip](https://github.com/lightningnetwork/lnd/files/3800958/svg.zip)

**Comment by wpaulino** [comment] 2019-11-04 19:42
Looking at the profiles, this seems to be a duplicate of https://github.com/lightningnetwork/lnd/issues/3370. Closing this so we can track it there instead.

**Closed by wpaulino** 2019-11-04 19:42 UTC
