### ISSUE TITLE
Stuck pending channels

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#3626] opened 2019-10-23 10:00 UTC
### Background

Some pending channels are still in a state of pending, although their funding transactions have more than 100 confirmations

### Your environment

* version of `lnd` - 0.8.0-beta
* version of `btcd`, `bitcoind`, or other backend - bitcoind 0.18.0
* golang 1.13.3

### Steps to reproduce

I don't know.

### Expected behaviour

After some confirmations they should be opened

### Actual behaviour

Over the last day, my own autopilot opened 82 channels until the nodes worked. But it is important that of these 14 channels are still in a state of pending, although their funding transactions have more than 100 confirmations. Do I need to create a ticket for this? As explained to me @btcontract, this could be due to the fact that the remote nodes must exchange messages FundingLocked. But I have big doubts that this is because of this, because for several hours the list of such channels has not been reduced, although they are open with different nodes. It is hard to believe that all these nodes behave in the same way (with some there are even active channels on the same LNBIG nodes where pending channels are with them). If I restart the server’s server now, I’m afraid that these channels will go into opened status and they won’t be able to catch the bug.

Other strange things about pending channels that they are seen as `opened` through 1ml.com for example. Here is full list of channel points of their channels:

```
p_1, pending, keys: lnd-01, 77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0, 16776085
p_1, pending, keys: lnd-03, 23269e76af291d70a883bf2ad4cbb47f12394d6419b979ad3e0b3256e47f331e:1, 16776085
p_1, pending, keys: lnd-11, 0f34842013205509f3c00da1d29542f2912913d4ec124bbeca13132a87b90607:0, 2956141
p_1, pending, keys: lnd-12, fcf666865702e4da1e45207a1c1ea6764128caadae13c877d7c9336388711330:1, 7998870
p_1, pending, keys: lnd-12, d19a86b6f63a863ac0ce84f70e319079eab4f9188ea79393e59399d96225c9fe:1, 7998870
p_1, pending, keys: lnd-12, 177a81d2719cd63b7203dffae93d7f8d9fed19a14f6c3669b5bf150e980543d0:1, 7998870
p_1, pending, keys: lnd-13, 92dc896927df360280f65b50213a3c67778817acaa7badaa7b72f9d158b7c574:1, 7998867
p_1, pending, keys: lnd-13, 78417a41a0d734cead2b38560301634770e0ca432fd2df9ac31b97899292247c:1, 13974405
p_1, pending, keys: lnd-13, 22d94aadd0d599fb866eec4b123c370ee24e73869eaeef8faed28f9cb8f5af91:1, 7998979
p_1, pending, keys: lnd-13, acd8a99c25dc0486f36084acfabb6dafaf6cf131583a0f88372840d20e826d6c:1, 7998870
p_1, pending, keys: lnd-13, 68532a99f566f41d480785f1e4dc46a67f4222af882fa7240f154b3382e85491:1, 9737903
p_1, pending, keys: lnd-13, 754bce568b58ea24ad1df09e6bfa7682fbf41de7dd5d3ca01a5c435f518d0c85:1, 7998979
p_1, pending, keys: lnd-27, 93c1547a79b3b93fbec0d77430243d958691898b455e4af99e604ca7ca8cc6fb:1, 7998979
p_1, pending, keys: lnd-31, 94037ead101b0f23f32d0a3e09b302518804f09f0d6a2edda12038db1d477185:1, 7998870
```

For example lets see to this channel: `lnd-01, 77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0`

Right now the lnd-01 has in `pendingchannels`:

```
        {
            "channel": {
                "remote_node_pub": "02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695",
                "channel_point": "77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0",
                "capacity": "16777215",
                "local_balance": "16776085",
                "remote_balance": "0",
                "local_chan_reserve_sat": "167772",
                "remote_chan_reserve_sat": "167772"
            },
            "confirmation_height": 0,
            "commit_fee": "1130",
            "commit_weight": "600",
            "fee_per_kw": "1562"
        },
```

Here all related grep info from logs:

```
$ grep -E '77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9|02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695|600553:2370:0' ~/.lnd/mainnet-lnd-run.log

2019-10-22 17:30:15.604 [ERR] RPCS: [connectpeer]: error connecting to peer: already connected to peer: 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735
2019-10-22 17:30:15.604 [ERR] RPCS: [/lnrpc.Lightning/ConnectPeer]: already connected to peer: 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735
2019-10-22 17:30:15.846 [INF] FNDG: Initiating fundingRequest(local_amt=0.16777215 BTC (subtract_fees=false), push_amt=0 mSAT, chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, peer=02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695, dust_limit=0.00000573 BTC, min_confs=0)
2019-10-22 17:30:16.619 [INF] FNDG: Generated ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) for pendingID(a83e47e8c926d02446c7c60ad89247962545cda25256bba2d34ab4011bdf8b80)
2019-10-22 17:30:16.822 [INF] FNDG: Broadcasting funding tx for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): (*wire.MsgTx)(0xc0073221c0)({
2019-10-22 17:30:16.822 [INF] LNWL: Inserting unconfirmed transaction 77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9
2019-10-22 17:30:16.874 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 17:30:16.875 [INF] CNCT: ChannelArbitrator(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): starting state=StateDefault
2019-10-22 17:30:16.876 [INF] NTFN: New spend subscription: spend_id=699, outpoint=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0, height_hint=600546
2019-10-22 17:30:16.959 [INF] FNDG: Finalizing pendingID(a83e47e8c926d02446c7c60ad89247962545cda25256bba2d34ab4011bdf8b80) over ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0), waiting for channel open on-chain
2019-10-22 17:30:16.959 [INF] CNCT: Close observer for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) active
2019-10-22 17:30:16.959 [INF] NTFN: New confirmation subscription: conf_id=134, txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9, num_confs=6 height_hint=600546
2019-10-22 17:30:16.959 [INF] FNDG: Waiting for funding tx (77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9) to reach 6 confirmations
2019-10-22 17:39:33.317 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 17:39:33.318 [ERR] FNDG: Unable to advance pending state of ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): error waiting for funding confirmation for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): waiting for fundingconfirmation failed
2019-10-22 17:39:33.521 [INF] SRVR: Disconnecting from 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735
2019-10-22 17:39:33.521 [INF] PEER: Disconnecting 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735, reason: server: disconnecting peer 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735
2019-10-22 17:39:33.521 [INF] PEER: unable to read message from 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735: read tcp 46.229.165.136:37392->141.101.8.36:9735: use of closed network connection
2019-10-22 17:47:25.751 [INF] NTFN: New spend subscription: spend_id=537, outpoint=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0, height_hint=600546
2019-10-22 17:47:57.261 [INF] CNCT: Close observer for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) active
2019-10-22 17:48:15.546 [INF] CNCT: ChannelArbitrator(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): starting state=StateDefault
2019-10-22 17:48:20.096 [INF] NTFN: New confirmation subscription: conf_id=15, txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9, num_confs=6 height_hint=600546
2019-10-22 17:48:20.247 [INF] FNDG: Waiting for funding tx (77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9) to reach 6 confirmations
2019-10-22 17:48:22.707 [INF] SRVR: Established connection to: 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735
2019-10-22 17:48:22.707 [INF] SRVR: Finalizing connection to 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695@141.101.8.36:9735, inbound=false
2019-10-22 17:48:22.870 [INF] PEER: NodeKey(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695) loading ChannelPoint(82f5bb545b35e549303c0b533c07da71620814664d60273de929c661e79ee3cb:1)
2019-10-22 17:48:23.129 [INF] PEER: NodeKey(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695) loading ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 17:48:23.131 [WRN] PEER: Unable to find our forwarding policy for channel 77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0, using default values
2019-10-22 17:48:23.145 [INF] HSWC: ChannelLink(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) is starting
2019-10-22 17:48:23.145 [INF] HSWC: HTLC manager for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) started, bandwidth=16607992000 mSAT
2019-10-22 17:48:23.145 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 17:48:23.145 [INF] SRVR: Negotiated chan series queries with 02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695
2019-10-22 17:48:23.145 [INF] DISC: Creating new GossipSyncer for peer=02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695
2019-10-22 17:48:23.146 [INF] HSWC: Received re-establishment message from remote side for channel(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
   PreviousOutPoint: (wire.OutPoint) 77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:1,
2019-10-22 18:21:12.929 [INF] LNWL: Marking unconfirmed transaction 77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9 mined in block 600553
2019-10-22 18:45:45.500 [INF] DISC: Received new remote channel announcement for 600553:2370:0
2019-10-22 18:45:46.519 [INF] NTFN: Dispatching 6 confirmation notification for txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9
2019-10-22 18:45:46.519 [INF] FNDG: ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) is now active: ChannelID(64396461323030303439396539333665363836353261386365366530383264323731613863343036626166333336326366353562663734393630363963383737)
2019-10-22 18:45:47.063 [INF] HSWC: ChannelLink(0:0:0) Updating to short_chan_id=600553:2370:0 for chan_id=d9da2000499e936e68652a8ce6e082d271a8c406baf3362cf55bf7496069c877
2019-10-22 18:45:47.063 [INF] HSWC: Updated short_chan_id for ChannelLink(d9da2000499e936e68652a8ce6e082d271a8c406baf3362cf55bf7496069c877): old=0:0:0, new=600553:2370:0
2019-10-22 18:45:47.063 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 18:45:47.068 [INF] FNDG: Peer(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695) is online, sending FundingLocked for ChannelID(d9da2000499e936e68652a8ce6e082d271a8c406baf3362cf55bf7496069c877)
2019-10-22 18:45:49.367 [INF] PEER: Already have ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0), ignoring.
2019-10-22 18:45:49.367 [INF] PEER: Processing retransmitted FundingLocked for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 18:45:50.312 [INF] NTFN: New confirmation subscription: conf_id=29, txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9, num_confs=6 height_hint=600553
2019-10-22 18:45:50.312 [INF] NTFN: Dispatching 6 confirmation notification for txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9
2019-10-22 18:45:50.312 [INF] FNDG: Announcing ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0), short_chan_id=600553:2370:0
2019-10-22 18:45:50.313 [INF] DISC: Received new local channel announcement for 600553:2370:0
2019-10-23 00:22:23.410 [INF] HSWC: ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): updating commit fee to 1562 sat/kw sat/kw
2019-10-23 05:59:25.602 [INF] DISC: GossipSyncer(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695): applying new update horizon: start=2019-10-23 05:59:24 +0200 CEST, end=2155-11-29 11:27:39 +0100 CET, backlog_size=0
2019-10-23 06:19:25.628 [INF] DISC: GossipSyncer(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695): applying new update horizon: start=2042-07-14 02:04:00 +0100 CET, end=2042-07-14 02:04:00 +0100 CET, backlog_size=0

```

**Comment by LNBIG-COM** [comment] 2019-10-23 10:14
And **other related problem**: if some funding transaction was not confirmed and will not be - the lnd keeps same channel as `pending` forever. I see this problem from version to version. It could be when a lnd or remote node created transaction when meepool was under high load and transaction was wiped by fee. Because of this, I have to constantly check the channel point for presence in the blockchain in order to correctly calculate balances in pending channels. These pending channels as eternal garbage. **The LND could be check channel points for validity and to change status of same channels to other state (for example new status `non_existing_channels` for example).**

I suspect that some monitoring tools may erroneously consider the balance of such channels in favor of the node, although in fact these UTXOs were spent in other transactions of the node. What do you think about this @alexbosworth @Roasbeef @wpaulino ?

**Comment by alexbosworth** [comment] 2019-10-23 11:54
Stuck pending is a common issue, I have it on my own node and multiple people have told me about it. 

Most commonly there was a bug previously that caused the stuck pending and then the bug was fixed but the stuck pending was not cleaned up.

**Comment by wpaulino** [comment] 2019-10-23 15:04
> And other related problem: if some funding transaction was not confirmed and will not be - the lnd keeps same channel as pending forever. I see this problem from version to version. It could be when a lnd or remote node created transaction when meepool was under high load and transaction was wiped by fee. Because of this, I have to constantly check the channel point for presence in the blockchain in order to correctly calculate balances in pending channels. These pending channels as eternal garbage. The LND could be check channel points for validity and to change status of same channels to other state (for example new status non_existing_channels for example).

We are aware of this issue, it just hasn't been addressed yet. Note that you see this a lot more than other nodes due to spending unconfirmed funds for channels.

> As explained to me @btcontract, this could be due to the fact that the remote nodes must exchange messages FundingLocked.

From looking at your logs, this isn't the case, it seems more like a database issue where the channel isn't moved from it's persistent pending state to confirmed.

**Comment by LNBIG-COM** [comment] 2019-10-23 15:23
> From looking at your logs, this isn't the case, it seems more like a database issue where the channel isn't moved from it's persistent pending state to confirmed.

Should I wait for the patch or can I fix these problems myself?

**Comment by wpaulino** [comment] 2019-10-23 16:24
As you noted in your first comment, restarting should address the issue for now.

**Comment by halseth** [comment] 2019-10-24 11:35
There's a few interesting things to see in the logs:

A restart seems to have happened during the flow (which should be okay):
```
2019-10-22 17:39:33.317 [WRN] FNDG: ChainNotifier shutting down, cannot complete funding flow for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
```

After the restart, we re-sync the channel, and add it to the active channels know by the peer (maybe we shouldn't do this for pending channels?):
```
2019-10-22 17:48:23.145 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
```

When the funding tx confims, we mark the channel opened in the DB, and report the shortChanID to the switch:

```
2019-10-22 18:45:46.519 [INF] NTFN: Dispatching 6 confirmation notification for txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9
2019-10-22 18:45:46.519 [INF] FNDG: ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0) is now active: ChannelID(64396461323030303439396539333665363836353261386365366530383264323731613863343036626166333336326366353562663734393630363963383737)
2019-10-22 18:45:47.063 [INF] HSWC: ChannelLink(0:0:0) Updating to short_chan_id=600553:2370:0 for chan_id=d9da2000499e936e68652a8ce6e082d271a8c406baf3362cf55bf7496069c877
2019-10-22 18:45:47.063 [INF] HSWC: Updated short_chan_id for ChannelLink(d9da2000499e936e68652a8ce6e082d271a8c406baf3362cf55bf7496069c877): old=0:0:0, new=600553:2370:0
2019-10-22 18:45:47.063 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
```

We send the `FundingLocked` message, which means the channel has successfully been marked open in the DB:
```
2019-10-22 18:45:47.068 [INF] FNDG: Peer(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695) is online, sending FundingLocked for ChannelID(d9da2000499e936e68652a8ce6e082d271a8c406baf3362cf55bf7496069c877)
```

We also receive `FundingLocked` from the peer:
```
2019-10-22 18:45:49.367 [INF] PEER: Already have ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0), ignoring.
2019-10-22 18:45:49.367 [INF] PEER: Processing retransmitted FundingLocked for ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0)
2019-10-22 18:45:50.312 [INF] NTFN: New confirmation subscription: conf_id=29, txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9, num_confs=6 height_hint=600553
2019-10-22 18:45:50.312 [INF] NTFN: Dispatching 6 confirmation notification for txid=77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9
2019-10-22 18:45:50.312 [INF] FNDG: Announcing ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0), short_chan_id=600553:2370:0
2019-10-22 18:45:50.313 [INF] DISC: Received new local channel announcement for 600553:2370:0
2019-10-23 00:22:23.410 [INF] HSWC: ChannelPoint(77c8696049f75bf52c36f3ba06c4a871d282e0e68c2a65686e939e490020dad9:0): updating commit fee to 1562 sat/kw sat/kw
2019-10-23 05:59:25.602 [INF] DISC: GossipSyncer(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695): applying new update horizon: start=2019-10-23 05:59:24 +0200 CEST, end=2155-11-29 11:27:39 +0100 CET, backlog_size=0
2019-10-23 06:19:25.628 [INF] DISC: GossipSyncer(02c12b5459cf107ee0440cae41902f1189db50fa003a077f3a6fbe6b5760218695): applying new update horizon: start=2042-07-14 02:04:00 +0100 CET, end=2042-07-14 02:04:00 +0100 CET, backlog_size=0
```

Everything looks okay from the logs, question is why it appears in the `pendingchannels` list, since I cannot see how we could get to the `sendFundingLocked` state without marking it `IsPending = false` in the DB.

**Comment by halseth** [comment] 2019-10-24 11:36
@LNBIG-COM if you run with `debuglevel=debug` and see this problem again, those logs would be super useful!

**Comment by halseth** [comment] 2019-10-24 11:48
@LNBIG-COM Just to make sure, is the channel in question found under `pending_open_channels` when issuing the `pendingchannels` command?

**Comment by LNBIG-COM** [comment] 2019-10-24 14:46
> @LNBIG-COM if you run with `debuglevel=debug` and see this problem again, those logs would be super useful!

May be it's main reason of this bug? 

https://github.com/lightningnetwork/lnd/issues/3624#issuecomment-545938476

I used autopilot and it created channels from unconfirmed of unconfirmed transactions. As @wpaulino told there:

> I noticed that both transactions have an output that was spent in the same block, which makes me wonder if this is an edge case that's not covered in the wallet.

**Comment by LNBIG-COM** [comment] 2019-10-24 14:56
> There's a few interesting things to see in the logs:

Today i restarted the lnd-01 and this channel is active.
But the transaction `77c869604...` is child of https://www.smartbit.com.au/tx/0838c0113185a6a40bae9f5f44677b9a96e0810d25a0e035340868a3cf81832d & https://www.smartbit.com.au/tx/3143a58e8a4536520965071aba67d4e9c3984083c52ce378b5fe95d4a931d90c which were confirmed in same block. So i think this bug and bug https://github.com/lightningnetwork/lnd/issues/3624#issuecomment-545938476 are related together.

**Comment by halseth** [comment] 2019-10-24 19:33
> @LNBIG-COM Just to make sure, is the channel in question found under pending_open_channels when issuing the pendingchannels command?

@LNBIG-COM any answer to this?

**Comment by LNBIG-COM** [comment] 2019-10-25 16:49
> Just to make sure, is the channel in question found under `pending_open_channels` when issuing the `pendingchannels` command?

I did not quite understand what you meant by the word `pending_open_channels`, but now everything has returned to normal status. After restart pending channels are active ones now.

**Comment by wpaulino** [comment] 2019-11-06 19:47
Closing this in favor of https://github.com/lightningnetwork/lnd/issues/3675, which provides better details on how to reproduce the issue. Once that's closed, the issue should be resolved going forward. If you run into it before then, restarting should bring things back to normal.

**Closed by wpaulino** 2019-11-06 19:47 UTC
Labels: channels, database, funding
