### ISSUE TITLE
Stuck on "waiting_close_channels"

### ISSUE THREAD

**Issue by jaxkeiser** [lightningnetwork/lnd#6391] opened 2022-04-03 16:03 UTC
I force closed all the channels I had on 3/30 and they have been stuck on "waiting_close_channels" ever since. I need to know how to finalize these closes and withdraw all funds associated with my lnd wallet back to mainnet.

By "all funds" I mean anywhere I might have sats such as my "lncli walletbalance" as well as "lncli listunspent".

**Comment by alexbosworth** [comment] 2022-04-03 16:39
Did you try restarting? Does it say that it's broadcasting the transactions in the logs when starting the node?

**Comment by jaxkeiser** [comment] 2022-04-05 03:28
I tried restarting and it did not fix the problem. This is what lnd shows upon restart: 

https://i.ibb.co/f9gRSXy/Problem.png

**Comment by alexbosworth** [comment] 2022-04-05 03:29
Did you try force closing channels that are in waiting close?

**Comment by jaxkeiser** [comment] 2022-04-05 03:30
Maybe, whats the command for that?

**Comment by alexbosworth** [comment] 2022-04-05 03:31
`lncli closechannel txid vout --force`

**Comment by jaxkeiser** [comment] 2022-04-05 03:35
Is there an easy way to do it for all of them at once? If not, where do I find the value for "txid"? Is it the "local_txid"?

**Comment by alexbosworth** [comment] 2022-04-05 03:39
It will be the funding txid, like `id:number`, id is tx id and number is the vout

I don't think it can be done for all of them at once

**Comment by jaxkeiser** [comment] 2022-04-05 03:45
I'm not sure if this is correct but I used the "channel_point" to fill in the values for the command:

lncli closechannel 40f957cc2163513aca4353e759ac694d1a9a218afafa6289dedc9c8905cd8aa9 0 --force

That returned this: 

[lncli] rpc error: code = Unknown desc = server is still in the process of starting

If I'm not getting the values from the right place then I need help on where to find them because I'm a massive noob. Fortunately, once this is resolved I won't be on this repository with noob questions anymore because I'm running a myNode now.

**Comment by alexbosworth** [comment] 2022-04-05 03:47
Did you just start the lnd or it has been running a long time?

**Comment by jaxkeiser** [comment] 2022-04-05 03:49
I restarted it 20 minutes ago when I saw your initial response. Should I wait a while and try again? But again, prior to restart, this thing had been running for like 5 days and the channels have been stuck on waiting close.

**Comment by alexbosworth** [comment] 2022-04-05 03:51
Maybe try again in a bit

**Comment by jaxkeiser** [comment] 2022-04-05 03:57
Okay I'm going to try again tomorrow and then give you an update

**Comment by jaxkeiser** [comment] 2022-04-06 02:32
Just now tried. It throws the same error message unfortunately @alexbosworth

**Comment by alexbosworth** [comment] 2022-04-06 02:33
So the server is still in the process of starting for 24 hours? Anything happening in the log file?

**Comment by jaxkeiser** [comment] 2022-04-06 03:13
Do you want the feed of bitcoind or lnd? It appears that they are both up to date though.

**Comment by ziggie1984** [comment] 2022-04-11 18:40
In case you want to force close all at once manually I helped someone with an umbrel with the same problem (in case your lnd starts correctly):

`sudo docker exec lnd lncli pendingchannels | jq -r '.waiting_close_channels[].channel.channel_point' |awk -F: ' {print "sudo docker exec lnd lncli closechannel --force --funding_txid "$1" --output_index "$2}' | bash`

**Comment by ziggie1984** [comment] 2022-04-11 18:42
for other setups just omit `sudo docker exec` in front of the commands

**Comment by Roasbeef** [comment] 2022-04-12 22:28
Appears to be a duplicate of https://github.com/lightningnetwork/lnd/issues/4819: as is, if you try to do a cop-op close, then abort, the only option after that is to force close.

**Closed by Roasbeef** 2022-04-12 22:28 UTC
