### ISSUE TITLE
unable to read message from CLN peer, send "internal error", force close ensues

### ISSUE THREAD

**Issue by heyambob** [lightningnetwork/lnd#6564] opened 2022-05-23 05:13 UTC
### Background

```
lnd                  | 2022-05-20 14:35:28.133 [INF] PEER: unable to read message from 0xxx@xxx: EOF
lnd                  | 2022-05-20 14:35:28.134 [INF] PEER: disconnecting 0xxx@xxx, reason: read handler closed
lnd                  | 2022-05-20 14:35:28.135 [INF] NTFN: Cancelling epoch notification, epoch_id=799
lnd                  | 2022-05-20 14:35:28.235 [INF] DISC: Removing GossipSyncer for peer=0xxx
```

the unable to read message error happened over and over again for afew hours and then the channel was force closed.

From CLN side, the log received "internal error", and force closed was fired by protocol

The CLN peer also experienced a similar incidence of force close with another peer of his a while back

### Your environment

LND 0.14.2
CLN 0.11.1

### Expected behaviour

It would be helpful for to print what message it cannot read before sending "internal error".

Even better:

1. instead of sending internal error, print the message it cannot read, disconnect from peer for 1 day, on and on, until the operator notice and decide to mutual close it himself.

2. if the (1) is unacceptable, it would be nicer to fire the mutual close instead of sending the "internal error". It's not like both nodes cannot reach one another, and the fund is not at risk

**Comment by Roasbeef** [comment] 2022-05-23 17:55
As far as CL releases, I think you may want to be on this version: https://github.com/ElementsProject/lightning/releases/tag/v0.11.1

From my reading, it fixed an issue with inadvertent force closes. Do you have further logs _before_ we send over that error message? Thinking this might be a duplicate of: https://github.com/lightningnetwork/lnd/issues/6485

**Closed** 2022-05-23 23:51 UTC

**Comment by btweenthebars** [comment] 2022-05-24 04:35
> As far as CL releases, I think you may want to be on this version: https://github.com/ElementsProject/lightning/releases/tag/v0.11.1
> 
> From my reading, it fixed an issue with inadvertent force closes. Do you have further logs _before_ we send over that error message? Thinking this might be a duplicate of: #6485

I have a similar issue with another peer of mine, here's from his log, there's no keystone:

```
Not very good with combing through logs, but if it's any help to understand what may have happened, here's my log searching for short channel ID and your node pubkey ..


2022-05-22 14:58:03.778 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-22 14:58:03.865 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-22 16:30:25.418 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-22 16:30:25.419 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-22 21:54:49.981 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-22 21:54:50.019 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-22 22:23:45.064 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-22 22:23:45.064 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-22 22:23:58.464 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-22 22:23:58.464 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-23 09:26:41.728 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-23 09:26:41.746 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-23 09:35:15.237 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-23 09:35:15.237 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-23 11:28:12.066 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-23 11:28:12.067 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-23 12:53:49.669 [INF] HSWC: Trimming open circuits for chan_id=yyyy:981:0, start_htlc_id=2173
2022-05-23 12:53:49.669 [INF] HSWC: Adding live link chan_id=xxxxx, short_chan_id=yyyy:981:0

2022-05-23 12:53:50.483 [INF] DISC: Received new remote channel announcement for yyyy:981:0

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

2022-05-23 12:53:51.770 [INF] PEER: disconnecting kkkkkk@llll:9735, reason: server: disconnecting peer 
xxxxx@lllll:9735
2022-05-23 12:53:51.773 [INF] PEER: unable to read message from xxxxx@lllll:9735: read tcp 
127.0.0.1:57576->127.0.0.1:9050: use of closed network connection

...  Around about here I see lots of failed htlc _ delete payments, i.e too many to paste here, but you can see about 20 mins +

2022-05-23 12:58:41.371 [WRN] CRTR: Attempt 271624 for payment 33e66100682ff712708c6688d0eb8477dcded4190ce2be260286f2a87acd66cf failed: 
TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0x140043be210)({

2022-05-23 13:18:05.193 [INF] RPCS: [DeletePayment] payment_identifier=3c82c2f027740b0de004ee5c0a95505cf4ff0929427213880e8bbdf9afc01afc, failed_htlcs_only=false
)@5
2022-05-23 13:18:19.872 [INF] RPCS: [DeletePayment] payment_identifier=75671ce87eb772c60ab8517957c95aa59dc4244f46045b9e047c458b8569a9a3, failed_htlcs_only=false

2022-05-23 13:18:36.480 [INF] RPCS: [DeletePayment] payment_identifier=ad664ecbf50f02651609b186dc1aa00862235c1881fa1dbe0e0b79739d62e012, failed_htlcs_only=false

2022-05-23 13:19

:09.690 [INF] RPCS: [DeletePayment] payment_identifier=b9217a949002b7f21b34d27ff737aa325ae5200c9163603fa51f1d21d948a76e, failed_htlcs_only=false

2022-05-23 13:20:35.818 [INF] RPCS: [DeletePayment] payment_identifier=0c2395b26394779072642b4c9dee1d1af58b0c8c1d630caa256cf7e0bd4ff61e, failed_htlcs_only=false

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

2022-05-23 14:34:06.700 [INF] RPCS: [DeletePayment] payment_identifier=d7e28aee4588efe1031c7aab39a4066a8c6a6147da3a95e76f592fcd914b14e9, failed_htlcs_only=false

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

2022-05-23 15:26:34.105 [INF] SRVR: Established connection to: xxxxx@lllll:9735
2022-05-23 15:26:34.143 [INF] SRVR: Finalizing connection to xxxxx@lllll:9735

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

node connection dropped / offline briefly so shutdown

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

2022-05-23 15:26:57.426 [INF] LTND: Received shutdown request.
2022-05-23 15:26:57.426 [INF] LTND: Shutting down...
2022-05-23 15:26:57.426 [INF] LTND: Gracefully shutting down.
2022-05-23 15:26:57.610 [INF] NANN: Channel Status Manager shutting down
2022-05-23 15:26:57.610 [INF] HSWC: HTLC Switch shutting down
2022-05-23 15:26:57.610 [ERR] CRTR: Resuming payment 20867985f78ece6b0b95c6e9ad0e453e2f9f337ce0e5754a6e644f1cff497e1f failed: htlcswitch shutting down.

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

2022-05-23 15:26:59.417 [INF] PEER: unable to read message from xxxxx@lllll:9735: EOF
2022-05-23 15:26:59.417 [INF] PEER: disconnecting xxxxx@lllll:9735, reason: read handler closed

/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////
/////////////////////////////////

2022-05-23 15:27:04.687 [INF] SRVR: Disconnecting from xxxxx@lllll:9735


2022-05-23 16:37:26.190 [INF] CHDB: Pruning link node xxxxx with zero open channels from database
```
