### ISSUE TITLE
lnd say: no contract resolutions exist and exists

### ISSUE THREAD

**Issue by starinacool** [lightningnetwork/lnd#1068] opened 2018-04-10 07:43 UTC
### Background

lnd keep exiting after unlock command with message: "no contract resolutions exist"

### Your environment

0.4.1-beta commit=b7875fce4cb82db11c86cec41218f3e49e8c15b0
Linux Ubuntu-1604-xenial-64-minimal 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bitcoind  0.16

I have opened more then a hundred channels on main net and this started to happend

### Steps to reproduce

start server
lncli unlock

### Expected behaviour

Server starts

### Actual behaviour

Server exit with exit code 1

Log:

2018-04-10 09:40:57.785 [DBG] CNCT: ChannelArbitrator(826418a78265daf716b74188f2472db624e2cffe6e0cd417444ca8576d182ecd:0)
: checking chain actions at height=517180
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0)
: new block (height=517505, hash=00000000000000000044fd331cbd6c3dda7407defa868f160ffefab18ed9076f) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517505 
2018-04-10 09:40:57.786 [DBG] CNCT: Starting ChannelArbitrator(5df3f253752d3d53d9564695f2898e47fbd61f7119984ae3743892bb8e
abf12e:0), htlc_set=(contractcourt.htlcSet) { 
 incomingHTLCs: (map[uint64]channeldb.HTLC) {
 }, 
 outgoingHTLCs: (map[uint64]channeldb.HTLC) { 
 }
} 

2018-04-10 09:40:57.786 [INF] CNCT: ChannelArbitrator(5df3f253752d3d53d9564695f2898e47fbd61f7119984ae3743892bb8eabf12e:0): starting state=StateContractClosed 
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0)
: new block (height=517172, hash=00000000000000000020b4286112feaf1530b6af5dcf796c7f599d9751af9842) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517172 
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0)
: new block (height=517173, hash=00000000000000000044e42f881dda7bf6758c550314e987b653b67774a374ae) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517173 
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0)
: new block (height=517174, hash=0000000000000000000504ceac707361cb66a43285d29060e3a2e48c00dd4642) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0)
: checking chain actions at height=517174
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): new block (height=517175, hash=0000000000000000003892269b8fdeb65117456085f8e59a9278e3178d6f5a28) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517175
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): new block (height=517176, hash=000000000000000000344562444bdee0ae6016e2ec2a029ca3fdd0bcc0de766f) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517176
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): new block (height=517177, hash=00000000000000000014818fc834aefebc0b2f7def409361c285e3c809b771a6) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517177
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): new block (height=517178, hash=0000000000000000000a95932872a80eb76b990ffee7d834aa7d5165b52fe92b) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517178
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): new block (height=517179, hash=0000000000000000000a80b5ad75924462f9d9f15517d2b7f90a26eac0a74b4f) examining active HTLC's
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517179
2018-04-10 09:40:57.786 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): new block (height=517180, hash=00000000000000000025bbeb1d74f902fb76f485b9ada1e3dfa1d04903f3314c) examining active HTLC's
2018-04-10 09:40:57.787 [DBG] CNCT: ChannelArbitrator(f7d2f1f5ca7202dd1bcc647697dbbe64d2b3205413d19ba1837e178953a44403:0): checking chain actions at height=517180
2018-04-10 09:40:57.787 [ERR] CNCT: unable to fetch contract resolutions: no contract resolutions exist
2018-04-10 09:40:57.787 [ERR] CNCT: unable to advance state: no contract resolutions exist
2018-04-10 09:40:57.787 [ERR] SRVR: unable to start server: no contract resolutions exist

**Comment by Roasbeef** [comment] 2018-04-10 19:16
Do you have logs prior to this instance?

**Comment by Roasbeef** [comment] 2018-04-10 19:27
Alright, I think I know the culprit here: 
   * you were offline for some period of time, possibly causing one of the HTLCs to time out
   * upon restart, we'll then step through the blocks we missed in the chain in order to ensure we play all active contracts
   * seems that you were actually syncing up your node at the same time `lnd` we restarting
   * the channel was closed unilaterally by the remote party 
   * in order to properly handle uni-closes, we need to get a signal from the `chainWatcher` in order to ensure we log the set of contract resolutions 
    * the state `contractcourt.StateBroadcastCommit` was _skipped_ (as normal for  uni closes)
   * however we then entered the `contractcourt.StateContractClosed` state w/o writing the resolutions

**Comment by halseth** [comment] 2018-04-11 10:48
@Roasbeef How is it able to get into `StateContractClosed` without first writing the resolutions? From what I can see there are only two ways fo getting to this state
1) by the `remotePeerTrigger`, in which the state callback should write the resolutions.
2) by the `chainTrigger`, in which we should go to `StateBroadcastCommit` and the resolutions should be written before moving to `StateContractClosed.

**Comment by Roasbeef** [comment] 2018-04-11 20:47
Agreed that it appears those are the only two ways to shift into the `StateContractClosed` state without explicitly writing the resolutions. However, it seems that's the case as the logs in the OP show the no resolutions have been written. I think there's a lingering bug involving the trigger that initially begins a state transition, and the one that's used on subsequent restarts.

**Comment by starinacool** [comment] 2018-05-02 08:39
Are there any updates on this issue? @Roasbeef

**Comment by Roasbeef** [comment] 2018-05-03 22:07
Hey @starinacool #1017 landed recently which itself ensure that channels can no longer get into this state. If you apply this diff: 
```diff --git a/contractcourt/chain_arbitrator.go b/contractcourt/chain_arbitrator.go
index 95bc071c..f0633141 100644
--- a/contractcourt/chain_arbitrator.go
+++ b/contractcourt/chain_arbitrator.go
@@ -417,9 +417,11 @@ func (c *ChainArbitrator) Start() error {
 			return err
 		}
 	}
-	for _, arbitrator := range c.activeChannels {
+	for chanPoint, arbitrator := range c.activeChannels {
 		if err := arbitrator.Start(); err != nil {
-			return err
+			log.Errorf("unable to start arb for "+
+				"chan_point=%v: %v", chanPoint, err)
+			continue
 		}
 	}
 
```

Then you should be able to start up again. Once you do, can you report the status of that channel? In the future we'll be adding a set of dev tools to be able to extract/remove channels like this that were borked, but then later fixed.

**Comment by starinacool** [comment] 2018-05-17 16:28
Installed the latest version.

Same story:

2018-05-17 18:27:42.838 [INF] CNCT: ChannelArbitrator(6f62d5fd30acf186661537386a715cded1c4d4d2894e2503bf2c7b8a9be82f4f:0): starting state=StateDefault 
2018-05-17 18:27:42.840 [DBG] CNCT: ChannelArbitrator(6f62d5fd30acf186661537386a715cded1c4d4d2894e2503bf2c7b8a9be82f4f:0): new block (height=523136) examining active HTLC's 
2018-05-17 18:27:42.840 [DBG] CNCT: ChannelArbitrator(6f62d5fd30acf186661537386a715cded1c4d4d2894e2503bf2c7b8a9be82f4f:0): checking chain actions at height=523136 
2018-05-17 18:27:42.840 [DBG] CNCT: Starting ChannelArbitrator(48615e9bfd67f99c7a99b941920bf45244da8c052f722d2f0018fe170280dd5c:0), htlc_set=(contractcourt.htlcSet) { 
 incomingHTLCs: (map[uint64]channeldb.HTLC) {
 }, 
 outgoingHTLCs: (map[uint64]channeldb.HTLC) {
 } 
}
 
2018-05-17 18:27:42.840 [INF] CNCT: ChannelArbitrator(48615e9bfd67f99c7a99b941920bf45244da8c052f722d2f0018fe170280dd5c:0): starting state=StateContractClosed 
2018-05-17 18:27:42.841 [ERR] CNCT: unable to fetch contract resolutions: no contract resolutions exist
2018-05-17 18:27:42.841 [ERR] CNCT: unable to advance state: no contract resolutions exist 
2018-05-17 18:27:42.841 [ERR] SRVR: unable to start server: no contract resolutions exist

**Comment by starinacool** [comment] 2018-05-23 22:30
It did helped.
What information do you want me to provide? What command should I run?

**Comment by Roasbeef** [comment] 2018-05-23 22:31
> What information do you want me to provide? What command should I run?

No further information, as the root cause of the issue has been fixed in master, and we'll be releasing a new version of `lnd` soon which packages up that fix and many others.

**Closed** 2018-05-28 23:45 UTC

**Comment by starinacool** [comment] 2018-05-30 21:17
OK,

Server is running fine, but I have 82 channels in pending_force_closing_channels state now.

Example:

{
    "total_limbo_balance": "499095",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "02ce7adcbaf97f78592ffeabe71bf75e41a20fa15f255a4def2aeeb8297966f78c",
                "channel_point": "cf66d4cbe7970254cfe9b6a43f73dca9bcaa1ded34d47526ea04dc294aaa8001:0",
                "capacity": "500000",
                "local_balance": "499276",
                "remote_balance": "0"
            },
            "closing_txid": "c414790eca162367182edcdd435bd2b565e02e2608b670de18b9074f8b391aae",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        },
        {
            "channel": {
                "remote_node_pub": "020fccc5602053c438b13ebee7aa31a25e9c3803baace5afcecedff8db70543747",
                "channel_point": "7532fe908fd2d92ef2d451574d16b41a1bb2b00b84a212d340caff619a013a04:0",
                "capacity": "500000",
                "local_balance": "499276",
                "remote_balance": "0"
            },
            "closing_txid": "70343aab55bd2eeb03d20b58e0109e74249daee8ec483c1aa67bc22ee5068530",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        },
        {
            "channel": {
                "remote_node_pub": "039195c0969d69f9a25839cb44bd5e858bd9e3971638959f0e657bffa6692b43f1",
                "channel_point": "0ec3bf7104adee9fb7b9ffd1024326a7857cc4df09e6212ae194d580683c450a:0",
                "capacity": "500000",
                "local_balance": "499276",
                "remote_balance": "0"
            },
            "closing_txid": "ae1bcde87f9ba5549b0fdf25761f4382984579a67785251b9181b0847eba09ed",
            "limbo_balance": "0",
            "maturity_height": 0,
            "blocks_til_maturity": 0,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        },


What is that mean, and what should I do to recover funds?

Thanks for your help.

**Comment by Roasbeef** [comment] 2018-05-31 22:59
Once they confirm (the closing transactions), then we'll start the process of sweeping the funds after the relevant timelocks have expired.
