### ISSUE TITLE
[bug]: Go to chain for outgoing htlc even though the peer connection is active

### ISSUE THREAD

**Issue by Impa10r** [lightningnetwork/lnd#8257] opened 2023-12-06 20:21 UTC
### Background

LND force closing the channel and putting outgoing HTLC on chain upon expiry instead of trying to fail it and update the commitment state

### Your environment

* version of `lnd` 0.17.2
* which operating system (`uname -a` on *Nix) Umbrel
* version of `btcd`, `bitcoind`, or other backend 25.1
* any other relevant environment details

### Steps to reproduce

Had an old channel with peer running Core Lightning v23.08.1 with connection over Tor. The connection was not stable, last reconnect happened 5 minutes before HTLC expired. I don't know why the peer did not send update_fail_htlc earlier, or maybe it was lost in transit. Despite the peer connection was active, upon HTLC expiry my LND closed the channel and placed HTLC on chain.

### Expected behaviour

I would imagine it is possible not to close the channel in such a situation, but fail the expired HTLC and update the channel state mutually with the downstream peer. If the peer does not cooperate, then close the channel. I am not fluent in BOLTs to suggest it there.

### Actual behaviour

Non-receipt of update_fail_htlc leads to an expensive force close. 

I attached my log. My peer could only provide this listpeers output:

               "status": [
                  "CHANNELD_NORMAL:Reconnected, and reestablished.",
                  "ONCHAIN:Tracking their unilateral close",
                  "ONCHAIN:All outputs resolved: waiting 38 more blocks before forgetting channel"
               ],
               "htlcs": [
                  {
                     "direction": "in",
                     "id": 39634,
                     "amount_msat": 500417083,
                     "expiry": 819962,
                     "payment_hash": "95a4c32e97ef71bbb5cb1fa14206b78698e26889398e4c73752e074cfac5f20a",
                     "state": "RCVD_ADD_ACK_REVOCATION"
                  }

[WCC-BOUNCER FC.log](https://github.com/lightningnetwork/lnd/files/13591186/WCC-BOUNCER.FC.log)

**Comment by Roasbeef** [comment] 2023-12-06 20:26
> LND force closing the channel and putting outgoing HTLC on chain upon expiry instead of trying to fail it and update the commitment state

You can't cancel back an outgoing HTLC. Only the party that received the HTLC can cancel it back. So one question here is: why didn't the other node cancel it back? I wonder if the TCP connection was inactive/dead? We've seen that at times w/ Tor: the connection is dead, but it isn't detected, so the connection is idle. 

In lnd v0.18, we have a new way to try to ensure liveness of channels, by enforcing that a pong response is sent to a ping in time.

**Comment by Roasbeef** [comment] 2023-12-07 19:45
> . Ping-pong will identify a disconnected peer, but we need to keep re-sending update_htlc until the state advances. 

Indeed, this should improve in lnd v0.18. Closing for now as there doesn't seem to be anything actionable here, unless we dig into where caused the other node to hold onto the HTLC for longer. I'm guessing it was just high chain fees and not adjusting the fee quickly enough.

**Comment by Impa10r** [comment] 2023-12-07 21:36
> In my opinion it's more like #7683 , although I could be wrong.

Not quite the same situation. My peer did not force close another channel downstream. I have no idea why my node did not receive update_htlc message from him. Maybe it was lost by Tor. But you are right, several disconnects/reconnects in the previous hour did not trigger re-send of this update message. I am seeing this scenario over and over. It is complicated that the peer is running CLN and cannot find anything in his logs. But I hope it is possible to engineer a solution.

**Comment by SunnySarahNode** [comment] 2023-12-07 21:50
> several disconnects/reconnects in the previous hour did not trigger re-send of this update message. I am seeing this scenario over and over.

That's precisely what's happening. It seems like at some point LND (or CLN, I don't know) simply "forgets" about the existence of the HTLC for some reason. Maybe we can somehow additionally send an update message(s), for example, after a reconnection? Or something else...

**Comment by Impa10r** [comment] 2023-12-07 22:11
> That's precisely what's happening. It seems like at some point LND (or CLN, if the peer is CLN?) simply "forgets" about the existence of the HTLC for some reason. Maybe we can somehow additionally send an update message(s), for example, after a reconnection? Or something else...

I guess the downstream peer sends update_fail_htlc and assumes it was received. If the state does not advance after some time, he needs to re-send it.

**Comment by Roasbeef** [comment] 2023-12-07 23:21
> I had several very similar cases. It looks like reconnection (disconnect peer and connect it again) should help in this case, but it doesn't. The channel becomes active and enabled on both sides again, but the HTLC does not disappear.

As mentioned above, only the receiver of an HTLC can cancel it back. If we cycle the connection, but then the HTLC isn't gone, then that's because the receiver is the one holding onto the HTLC. The exact reason will vary. In the current fee env, it may be that they had to go on chain after forwarding that HTLC, and it's taking a long time to confirm, we'll only cancel back once it's confirmed, as otherwise it's possible to lose funds (we cancel back, but the the other party pulls with the preimage). 

Looking at the logs above, I see this: 
```
2023-12-06 04:24:11.862 [INF] CNCT: ChannelArbitrator(a7644e42c3b173178a533786b5e7ea0f13bd5a37a649ca4a7a2c0ac9b543f13f:1): go to chain for outgoing htlc 95a4c32e97ef71bbb5cb1fa14206b78698e26889398e4c73752e074cfac5f20a: timeout=819962, blocks_until_expiry=0, broadcast_delta=0
```

Before that it's able to reconnect to the peer, but the peer doesn't send anything related to changing HTLCs:
```
2023-12-06 04:19:16.163 [INF] DISC: Creating new GossipSyncer for peer=02f4c77dcf12255ccf705c18b8d6b95e4f884910bf61e8aa21242607193a79da1b
2023-12-06 04:19:16.335 [INF] DISC: GossipSyncer(02f4c77dcf12255ccf705c18b8d6b95e4f884910bf61e8aa21242607193a79da1b): applying new update horizon: start=2106-02-07 06:28:15 +0000 UTC, end=2242-03-16 12:56:30 +0000 UTC, backlog_size=0
2023-12-06 04:19:16.335 [INF] HSWC: ChannelLink(a7644e42c3b173178a533786b5e7ea0f13bd5a37a649ca4a7a2c0ac9b543f13f:1): received re-establishment message from remote side
2023-12-06 04:19:16.518 [INF] DISC: Received new remote announcement signature for 734461:1235:1
```

So it went to chain for that HTLC as the timeout had expired. 

> In my opinion it's more like https://github.com/lightningnetwork/lnd/issues/7683 , although I could be wrong.

I think you're right, so I'll close this so we can continue the discussion there. One other thing nodes can do in times like this is increase the `min_hltc` setting, which can be done via `updatechanpolicy`. 

Re reconnection: all nodes should retransmit anything that hasn't been ACK'd by the other side after the connection is established again. You can see if this is being done or not by doing `lncli debuglevel --level=PEER=debug`, then trying the reconnection. This'll show you exactly which messages are being sent back and forth between nodes.

**Closed by Roasbeef** 2023-12-07 23:21 UTC
Labels: bug, needs triage
