### ISSUE TITLE
lnd (or rather btcwallet) scanning blocks starting at genesis, blocking startup

### ISSUE THREAD

**Issue by wereHamster** [lightningnetwork/lnd#2803] opened 2019-03-19 18:50 UTC
### Background

A freshly set up lnd node (running against a fully synced btcd chain backend), is blocking startup at this message: `LTND: Waiting for chain backend to finish sync, start_height=1485269`. The culprit appears to be code inside btcwallet (https://github.com/btcsuite/btcwallet), which is scanning the chain starting at the genesis block. When I add debugging code to the `IsSynced()` function (in lnwallet/btcwallet/btcwallet.go), I can see that the `syncState.Height` starts at zero and increments slowly.

Furthermore, even after a clean shutdown (eg. with `lncli stop`), the wallet doesn't remember the previous height and starts at zero again.

### Your environment

* `lnd` and `btcd`: master (as of today)
* macOS High Sierra, 10.13.6

### Steps to reproduce

* Start with a clean slate (eg. `rm -rf $LNDDIR`)
* Start btcd, wait until it's fully synced
* Start lnd and create a new wallet (`lncli create`)

### Expected behaviour

After creating a new wallet lnd should be immediately useable, as there is no need for btcwallet to scan old blocks (from before the wallet birthday)

### Actual behaviour

It takes a looong time for lnd to start up and become useable.

**Comment by wpaulino** [comment] 2019-03-19 18:52
This is something that was done back then to alleviate huge reorg issues on testnet. https://github.com/btcsuite/btcwallet/pull/555 will fix this, but it is not a priority at the moment.

**Comment by wereHamster** [comment] 2019-03-19 19:19
When the btcd node is running on the same host, the rescanning is reasonably fast. But if it's a remote node then the rescan progresses at ~10 blocks/s, which makes it impractical.

**Comment by Roasbeef** [comment] 2019-03-19 20:24
Closing as it's a duplicate of other issues and fixed above.

**Closed by Roasbeef** 2019-03-19 20:24 UTC
