### ISSUE TITLE
[bug]: verifychanbackup indicates a good backup with empty json response

### ISSUE THREAD

**Issue by ardevd** [lightningnetwork/lnd#7440] opened 2023-02-22 13:49 UTC
Currently, `lncli verifychanbackup`  generally just returns an empty json response when the provided backup is good. Passing in an invalid backup however doesnt return any json output but usually some sort of rpc error.

Is this the intended behavior, and if so, does it make sense to return more sensible responses when verifying backups?

**Comment by ellemouton** [comment] 2023-02-22 13:57
I think this is intended behaviour. An empty json output is generally considered to mean "success".

but agree that perhaps a "success" message can be added in lncli to make things more clear. 

Going to remove the "bug" label and turn it into a feature request rather.

**Comment by raehat** [comment] 2024-04-17 16:09
Is this issue assigned to someone currently? If not, can I get assigned for this?

**Comment by raehat** [comment] 2024-04-17 16:11
Is anyone working on this issue? If not, can I take it?

**Comment by guggero** [comment] 2024-04-17 16:17
See https://github.com/lightningnetwork/lnd/pull/7762.

**Closed** 2024-11-07 18:14 UTC
Labels: beginner, feature request, good first issue, lncli
