### ISSUE TITLE
HTLCs stuck in limbo for months after force close

### ISSUE THREAD

**Issue by ppppso** [lightningnetwork/lnd#8629] opened 2024-04-07 21:28 UTC
### Background

About six months ago one of my channels with pending HTLCs was forced closed. The closing tx is confirmed, but the HTLCs are still unconfirmed due to low fees and their stage is still 1. The command `pendingchannels` reports `"blocks_til_maturity":  0` for the channel and thousands of negative blocks for `"blocks_til_maturity"` for each HTLC. I believe this issue is similar to https://github.com/lightningnetwork/lnd/issues/8328 with the difference that in my case the stage is 1.

I tried `bumpfee` with the HTLCs tx id but it says the tx doesn't belong to my wallet.

I looked at the code a little bit and it's quite complex but I found in `utxonursery.go` that the function `sweepCribOutput` says that there is nothing to be done to bump this transaction. Does this apply to my case? If not, how can I bump the fees? Or what can I do to recover those sats from limbo? Thank you.

### Your environment

* version of `lnd`: v0.17.4
* which operating system: Ubuntu 20.04.2 LTS
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core 26.1

**Comment by hieblmi** [comment] 2024-04-09 14:26
Hi @ppppso, thanks for the report.

It could be that the second stage htlc output values are too low to be swept, e.g. their value is less than what the sweep fee would be, so lnd isn't sweeping until the mempool fees decrease.

If it doesn't majorly impact your operations, could you restart your node and grep for the outpoint of the channel thats closing and see what lnd reports for it?

**Comment by ppppso** [comment] 2024-04-09 17:15
Thanks for your reply.

> It could be that the second stage htlc output values are too low to be swept, e.g. their value is less than what the sweep fee would be, so lnd isn't sweeping until the mempool fees decrease.

The unconfirmed tx is the one that spends directly from the force closing tx. My understanding is that this is the first stage and the sweeper can only sweep the second stage, correct?

> If it doesn't majorly impact your operations, could you restart your node and grep for the outpoint of the channel thats closing and see what lnd reports for it?

I'm unable to restart the node at the moment. It's a business critical node and due to its size it takes a long time to start. This is the only occurrence I see right now:

`[INF] NTFN: Found input xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:x, spent in yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy`

**Comment by ppppso** [comment] 2024-04-09 19:02
I'll see if I can do that.

In any case, can you confirm that a pending HTLC in stage one cannot be bumped? The commitment type is `STATIC_REMOTE_KEY`. I saw in `channel.go` a [comment](https://github.com/lightningnetwork/lnd/blob/6377f98536a6e5f22924ea498f8565b2dcbe4aee/lnwallet/channel.go#L6883) saying that if it's an anchor commitment then the tx can be resigned (and presumably bumped?), but it's not clear to me what happens if it's not.

Thank you.

**Comment by hieblmi** [comment] 2024-04-10 06:41
Yes I can confirm in that case. Since the second stage htlc tx is tied to spending only the commitment tx(no other inputs can be attached) and the channel doesn't have an anchor this closure can't be fee bumped and has to confirm once the mempool calms. Another way would be to use a fee accelerator to get it confirmed quicker.

**Comment by ziggie1984** [comment] 2024-04-12 00:35
1-Level-HTLCs resulting from STATIC_REMOTE_KEY channels cannot be bumped because their signature is static and negotiated during the building up of the htlc. For anchor channels thats not the case, HTLCs have actually zero-fees, and are only provided with sufficient feerate when they are swept.

**Comment by hieblmi** [comment] 2024-04-12 07:11
Is it correct that the fee could theoretically be updated if the htlc is re-signed?

**Comment by ziggie1984** [comment] 2024-04-12 09:11
Yes theoretically, but the peer has not incentives to do so if the channel is already closed. But yeah it's possible and that's why `anchors-zero-fee-htlc-tx` were introduced I think.

Closing this issue, because thats the general downside of STATIC_REMOTE_KEY channels. No way to bump the fee of the commitment transaction nor the htlc sweeps.

**Closed by ziggie1984** 2024-04-12 09:11 UTC
Labels: bug, needs triage

**Comment by ppppso** [comment] 2024-04-12 09:16
Thanks for the replies.

What about a CPFP tx? Could it be done?

**Comment by ziggie1984** [comment] 2024-04-12 09:19
no that's not possible because the First-Level HTLC sends to a P2WSH which is bound to a relative timelock.

See: https://github.com/lightning/bolts/blob/master/03-transactions.md#htlc-timeout-and-htlc-success-transactions
