### ISSUE TITLE
[bug]: LND shutdown when looses connection to bitcoind

### ISSUE THREAD

**Issue by zx9r** [lightningnetwork/lnd#7403] opened 2023-02-13 12:31 UTC
### Background

LND starts a shutdown when bitcoind is being stopped. 

In this case bitcoind is running in another machine. I reinitiated the machine running bitcoind and the LND running in another machine initiated a shutdown

### Your environment

* version of `lnd`: 0.15.5-beta commit=v0.15.5-beta
* which operating system (`uname -a` on *Nix): Linux ubuntu-pi-server 5.15.0-1021-raspi # 23-Ubuntu SMP PREEMPT Fri Nov 25 15:27:43 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v22.0.0
* any other relevant environment details

### Steps to reproduce

Stop bitcoind which is running in another machine

### Expected behaviour

LND should not initiate a shutdown

### Actual behaviour

> 2023-02-13 12:53:31.216 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: unable to get best block info: invalid http POST response (nil), method: getblockchaininfo, id: 105135, last error=Post "http://192.168.0.17:8332": dial tcp 192.168.0.17:8332: connect: connection refused
> 2023-02-13 12:54:09.667 [INF] CRTR: Processed channels=0 updates=114 nodes=1 in last 59.999301488s
> 2023-02-13 12:54:19.984 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
> 2023-02-13 12:54:19.985 [INF] WTCL: (anchor) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
> 2023-02-13 12:54:22.512 [INF] DISC: GossipSyncer(025f1456582e70c4c06b61d5c8ed3ce229e6d0db538be337a2dc6d163b0ebc05a5): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
> 2023-02-13 12:54:22.526 [INF] DISC: Broadcasting 179 new announcements in 18 sub batches
> 2023-02-13 12:54:22.524 [INF] DISC: GossipSyncer(021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d): applying gossipFilter(start=2023-02-13 12:54:22.524078373 +0100 CET m=+3171703.818122654, end=2159-03-22 19:22:37.524078373 +0100 CET)
> 2023-02-13 12:54:30.205 [INF] CRTR: Examining channel graph for zombie channels
> 2023-02-13 12:54:30.457 [INF] CRTR: Pruning 0 zombie channels
> 2023-02-13 12:54:37.203 [CRT] SRVR: Health check: chain backend failed after 3 calls
> 2023-02-13 12:54:37.203 [INF] SRVR: Sending request for shutdown
> 2023-02-13 12:54:37.250 [INF] LTND: Received shutdown request.
> 2023-02-13 12:54:37.251 [INF] LTND: Shutting down...
> 2023-02-13 12:54:37.251 [INF] LTND: Gracefully shutting down.
> 2023-02-13 12:54:37.271 [INF] WTWR: Stopping watchtower
> 2023-02-13 12:54:37.290 [INF] WTWR: Stopping watchtower server
> 2023-02-13 12:54:37.290 [INF] WTWR: Watchtower server stopped successfully
> 2023-02-13 12:54:37.290 [INF] WTWR: Stopping lookout
> 2023-02-13 12:54:37.291 [INF] NTFN: Cancelling epoch notification, epoch_id=8
> 2023-02-13 12:54:37.291 [INF] WTWR: Lookout stopped successfully
> 2023-02-13 12:54:37.291 [INF] WTWR: Watchtower stopped successfully
> 2023-02-13 12:54:37.298 [INF] NANN: Channel Status Manager shutting down
> 2023-02-13 12:54:37.311 [INF] HSWC: HTLC Switch shutting down
> 
> [...]
> 
> 2023-02-13 12:54:47.876 [INF] WTCL: (legacy) Force quitting watchtower client
> 2023-02-13 12:54:47.877 [INF] WTCL: (legacy) Force quitting task pipeline
> 2023-02-13 12:54:47.877 [INF] WTCL: (legacy) Task pipeline unclean shutdown complete
> 2023-02-13 12:54:47.878 [INF] WTCL: (legacy) Watchtower client unclean shutdown complete, stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
> 2023-02-13 12:54:57.878 [INF] WTCL: (anchor) Force quitting watchtower client
> 2023-02-13 12:54:57.878 [INF] WTCL: (anchor) Force quitting task pipeline
> 2023-02-13 12:54:57.879 [INF] WTCL: (anchor) Task pipeline unclean shutdown complete
> 2023-02-13 12:54:57.879 [INF] HLCK: Health monitor shutting down
> 2023-02-13 12:54:57.879 [INF] WTCL: (anchor) Watchtower client unclean shutdown complete, stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
> 2023-02-13 12:54:57.900 [INF] RPCS: Stopping RPC Server
> 2023-02-13 12:54:57.901 [INF] RPCS: Stopping AutopilotRPC Sub-RPC Server
> 2023-02-13 12:54:57.901 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
> 2023-02-13 12:54:57.905 [INF] RPCS: Stopping NeutrinoKitRPC Sub-RPC Server
> 2023-02-13 12:54:57.906 [INF] RPCS: Stopping VersionRPC Sub-RPC Server
> 2023-02-13 12:54:57.926 [INF] RPCS: Stopping WatchtowerRPC Sub-RPC Server
> 2023-02-13 12:54:57.937 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
> 2023-02-13 12:54:57.945 [INF] RPCS: Stopping PeersRPC Sub-RPC Server
> 2023-02-13 12:54:57.946 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
> 2023-02-13 12:54:57.946 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
> 2023-02-13 12:54:57.969 [INF] RPCS: Stopping SignRPC Sub-RPC Server
> 2023-02-13 12:54:57.970 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
> 2023-02-13 12:54:57.970 [INF] TORC: Stopping tor controller
> 2023-02-13 12:54:58.131 [INF] LTND: Shutdown complete
>

**Comment by GeorgeTsagk** [comment] 2023-02-13 21:47
Hey @zx9r,

Just curious about this, why would you want LND to stay alive when the chain backend sub-system is failing?

I would assume it's safer to not perform any actions over channels as long as you are disconnected from the chain, which is used as the source of truth. It seems to me like lnd **should** restart until the chain backend comes back up online.

> I reinitiated the machine running bitcoind and the LND running in another machine initiated a shutdown

Have you configured your environment so that LND repeatedly restarts upon failure? Did LND fail to start after that shut down?

**Comment by guggero** [comment] 2023-04-14 08:34
As mentioned by @GeorgeTsagk, `lnd` needs a connection to `bitcoind` to work, that's what the health check is there for, so it can restart `lnd` when `bitcoind` goes down (assuming you have a dockerized or systemd environment that restarts `lnd` automatically). You can disable the health check but that is not recommended.

Closing since this is expected behavior. Feel free to re-open if you disagree.

**Closed by guggero** 2023-04-14 08:34 UTC
Labels: bug, needs triage
