### ISSUE TITLE
Using a remote rpchost is causing some strange networking issues.

### ISSUE THREAD

**Issue by matthewlilley** [lightningnetwork/lnd#1528] opened 2018-07-10 01:59 UTC
### Background

I have a remote BTCD running on an AWS server. I'm connecting to it from an LND instance running on my local Windows machine, catching up block height is EXTREMELY slow. It takes roughly 2 days to catch up, and network speed seems to never goes much past 50kb/s down. It's almost as if that BTCD is stalling repeatedly, and there's no buffer on the LND side to work from, so it's continually waiting for more data. 

~~I'll try to rule out OS by testing it on a separate Linux machine.~~

UPDATE: I've eliminated all other possibilities. This's 100% an issue with LND running on a Windows OS. I did the same on my local Linux box and there was absolutely no issues, LND caught up with the remote BTCD in around 5 minutes.  I'll investigate further.

### Your environment

* version of `lnd` - v0.42-beta, or master.
* which operating system (`uname -a` on *Nix) - local LND running on Windows WSL - remote BTCD running on Ubuntu.
* version of `btcd`, `bitcoind`, or other backend - BTCD
* any other relevant environment details

### Steps to reproduce

Connect to a fully synced remote BTCD node, from a local LND node. 

### Expected behaviour

Catching up should take no longer than an hour for testnet, locally this happens in a matter of minutes.

### Actual behaviour

Catching up takes around 2 days to catch up for testnet.

**Comment by matthewlilley** [comment] 2018-07-10 02:06
This seems to be related to #1177, the symptoms seem very similar.

**Comment by matthewlilley** [comment] 2018-07-10 03:07
Pinging @Roasbeef - This's a major issue for Windows users. It effects consumers running wallets, to developers looking to work on LN. I'll see if I can locate the issue in the source.

**Comment by matthewlilley** [comment] 2018-07-10 09:50
For the sake of argument, I tried running this natively on Windows, to rule out the possibility of something fishy going on with WSL, but can confirm that the same issue is present.

**Comment by Roasbeef** [comment] 2018-08-25 00:12
The issue is simply the RTT to the remote node. On "initial catch up" we (atm) request all the block headers. There's over 1.4 miil on testnet right now, multiply that by the RTT latency, and it can take a while for a remote node. We know a few ways of fixing this issue.

**Comment by Roasbeef** [comment] 2018-08-25 00:14
Related to #1545.

**Comment by fusion44** [comment] 2019-02-18 18:56
Is there any ETA when this might get fixed? I'm running BTCD on a remote node, and with the current rate, it'll finish catching up with the chain in 3 weeks.

**Comment by Roasbeef** [comment] 2019-10-30 00:36
Fixed now in the latest version as we don't store _all_ block headers in the wallet.

**Closed by Roasbeef** 2019-10-30 00:36 UTC
Labels: P3
