### ISSUE TITLE
Channel Stuck in "Waiting Close" for 2 years

### ISSUE THREAD

**Issue by Silarous** [lightningnetwork/lnd#6291] opened 2022-02-23 04:56 UTC
### Background

Channel was closed two years ago but the channel remains in 'waiting_close_channels" state.  It does not appear any funds are lost looking at the close transaction [here](https://blockstream.info/tx/8c9dfd89965c43c1c2fc22c7c946927ce0ece00bf967665dfd24e7a36704f3d9).  Primarily just getting annoyed seeing it there and not going away.  

### Your environment

* LND 0.14.2-beta
* RaspiBlitz 1.7.2
* Bitcoin Core 22.0.0

### Steps to reproduce

lncli pendingchannels lists this output 
 "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f",
                "channel_point": "837311dcadba5cf3008c3a827c023c35bdc0d3a1769e9ae1241f18d8e2e85644:0",
                "capacity": "1000000",
                "local_balance": "4000",
                "remote_balance": "992352",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "LEGACY",
                "num_forwarding_packages": "0",
                "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted"
            },
            "limbo_balance": "4000",
            "commitments": {
                "local_txid": "074c06a553bde49d5c8386a9e825ee037ba2011c3544f00f315724230ad35de7",
                "remote_txid": "6500454e17210ec71eaa965c2726f4936a9001791a5422405819695ce9e5092d",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "3648",
                "remote_commit_fee_sat": "3648",
                "remote_pending_commit_fee_sat": "0"
            },
            "closing_txid": ""
        }

### Expected behaviour

Channel should have cleared when closing transaction confirmed.  I

### Actual behaviour

Channel remains stuck in "waiting_close_channels"

**Comment by alexbosworth** [comment] 2022-02-23 05:37
Try force closing it

**Comment by Silarous** [comment] 2022-02-23 20:17
Attempting to force close it returns "[lncli] rpc error: code = Unknown desc = channel is already in the process of being force closed"

The channel has already closed 2 years ago and was finalized on the blockchain.  For some reason it remains stuck under the "Waiting Close" section on my node.

**Comment by lucasdcf** [comment] 2022-02-23 21:58
So it's closed and you had your onchain funds back?

Try this: lncli abandonchannel [command options] funding_txid [output_index]

**Comment by Silarous** [comment] 2022-02-23 23:40
> So it's closed and you had your onchain funds back?

>Try this: lncli abandonchannel [command options] funding_txid [output_index]

That's correct.  The channel was closed and this is the link to the [transaction](https://blockstream.info/tx/8c9dfd89965c43c1c2fc22c7c946927ce0ece00bf967665dfd24e7a36704f3d9).  

I don't fully understand what you are asking me to try.  Would you mind elaborating?  If I enter "  lncli abandonchannel 837311dcadba5cf3008c3a827c023c35bdc0d3a1769e9ae1241f18d8e2e85644" it returns "[lncli] rpc error: code = Unknown desc = AbandonChannel RPC call only available in dev builds"

**Comment by alexbosworth** [comment] 2022-02-23 23:41
You have to put "i know what i am doing" as a flag if you want to delete the channel

If the funds are already fully moved, this may be an error in LND that it didn't pick up that the channel closed

**Comment by Silarous** [comment] 2022-02-23 23:46
> 

Could you tell me the full command I should enter?

**Comment by alexbosworth** [comment] 2022-02-23 23:48
`--i_know_what_i_am_doing` is the flag but I think it would be better if the underlying issue were addressed if there is one, you shouldn't have to delete channels if nothing unusual happened

**Comment by Silarous** [comment] 2022-02-23 23:53
> `--i_know_what_i_am_doing` is the flag but I think it would be better if the underlying issue were addressed if there is one, you shouldn't have to delete channels if nothing unusual happened

How should I go about addressing the underlying issue?  From what I can tell, the channel close was initiated by the remote node.  The channel successfully closed, funds were released to both parties and have since been spent in other transactions.  For some reason it stuck in waiting close on my end for the last two years.  I assumed eventually it would correct its status but that hasn't happened.

**Comment by alexbosworth** [comment] 2022-02-23 23:54
I'm not sure you can do anything but you shouldn't have to do anything, ideally channels exit waiting close when they are resolved and if they don't then that's an issue that should be corrected

**Comment by Silarous** [comment] 2022-02-23 23:57
> I'm not sure you can do anything but you shouldn't have to do anything, ideally channels exit waiting close when they are resolved and if they don't then that's an issue that should be corrected

Yeah, I have opened and closed many channels successfully.  Some of them were closed cooperatively, some of them were forced.  This was the only one that had this issue for some reason.

**Comment by alexbosworth** [comment] 2022-02-23 23:59
If you still had some logs relating to the close it might be helpful to figure out what happened, I haven't heard of this kind of thing happening, potentially it has even already been solved but not in a way that cleaned out older channels, in which case abandonchannel would be appropriate

**Comment by Silarous** [comment] 2022-02-24 00:15
> If you still had some logs relating to the close it might be helpful to figure out what happened, I haven't heard of this kind of thing happening, potentially it has even already been solved but not in a way that cleaned out older channels, in which case abandonchannel would be appropriate

Where would I find such logs?

**Comment by alexbosworth** [comment] 2022-02-24 00:16
lnd will keep logs in the ~/.lnd/logs dir by default but it will also rotate them out if you haven't specified keeping very old logs so the relevant info might be gone

**Comment by Silarous** [comment] 2022-02-24 00:31
> lnd will keep logs in the ~/.lnd/logs dir by default but it will also rotate them out if you haven't specified keeping very old logs so the relevant info might be gone

Yeah, it's most likely gone after two years then.  Either way, the abandonchannel with the i know what i am doing flag worked in getting it out of the waiting close status.  That much I am thankful for.  It was really bothering my OCD.  I appreciate the help.  Should it happen again I will try and capture a log.

**Comment by guggero** [comment] 2022-02-24 08:33
It's very possible this happened due to a bug that was fixed in the meantime and the borked state just was never cleaned up automatically.

I'm going to close the issue, feel free to comment or re-open should it happen again.

**Closed by guggero** 2022-02-24 08:33 UTC

**Comment by guggero** [comment] 2022-05-31 18:00
You are missing a command line argument. The command needs to say `lncli closechannel --force 9918d0d8614f494286a50a1aee220ef639a87d61bb65a4de1eddd3292fd55aa7 1` (notice the space and the `1` in the end, this comes from the `:1` in the channel point).

**Comment by Silarous** [comment] 2022-05-31 21:16
> You are missing a command line argument. The command needs to say `lncli closechannel --force 9918d0d8614f494286a50a1aee220ef639a87d61bb65a4de1eddd3292fd55aa7 1` (notice the space and the `1` in the end, this comes from the `:1` in the channel point).

Awesome that worked.  Thanks for pointing me in the right direction.

**Comment by gerrylove0820** [comment] 2024-03-07 22:49
Hey guys I have a couple channels one on pending to close and the other one in pending force to close for a couple months now both channels were closing by the others peers, I have trying with no luck any help will be appreciated I am using umbrel lighting node thanks 🙏

**Comment by gerrylove0820** [comment] 2024-03-07 22:52
Txid 84a6e6616db5d45432ad19e191befdd97300092bc37fe4586dbdfdf55d0900ae

txid ea96a553bee08e6ab69328eb9f68f58b27d0676bedbc62fcdaa694ec6a3de3eb

**Comment by Silarous** [comment] 2024-03-07 23:15
Transaction ending in 900ae looks like it is just pending in the mempool with a low fee at 5.78sats/vb.  Transaction fees haven't gotten that low in a while.

Transaction ending in e3eb successfully forced closed 4 weeks ago.

**Comment by gerrylove0820** [comment] 2024-03-07 23:29
So do you recommend to wait till confirmed on the menpool

**Comment by Silarous** [comment] 2024-03-08 01:21
I guess that depends on which output is yours and how urgent you are with it being confirmed.  If your output is the one for 11,823 sats, you may just wait and see if it confirms since the amount that is pending is so small.
