### ISSUE TITLE
Channel from listchannels has chan_id as "0"

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#2823] opened 2019-03-22 18:58 UTC
### Background

I found strange channels - they are not active but they are in listchannels and they are missing in closedchannels

### Your environment

* version of `lnd` 0.5.2-99-beta commit=queue/v1.0.1-106-g9143067014bcde14f1e8f7eb515bae1ccccb97c5
* which operating system (`uname -a` on *Nix) CentOS 6
* version of `btcd`, `bitcoind`, or other backend 0.17.1

### Actual behaviour

For example lnd-41

    {
        "active": false,
        "remote_pubkey": "028c2f98b483bccf9e2634d6d5dca5cc6606ed6afd17d209da1a95f4b138d11a87",
        "channel_point": "c47516fcca67ea4501ac05b2e3eeae3ad20ef1a7e178dcb3ee47b2bc1ffc1acb:0",
        "chan_id": "0",
        "capacity": "2000000",
        "local_balance": "1997276",
        "remote_balance": "0",
        "commit_fee": "2724",
        "commit_weight": "600",
        "fee_per_kw": "3763",
        "unsettled_balance": "0",
        "total_satoshis_sent": "0",
        "total_satoshis_received": "0",
        "num_updates": "0",
        "pending_htlcs": [
        ],
        "csv_delay": 240,
        "private": false,
        "initiator": true
    },

This channel is missing in feereport, closedchannels. What is this? And i have second there channel with chan_id as 0

    {
        "active": false,
        "remote_pubkey": "02005dcac896582db30f259c17bba1849a9e1127f60d120ec7db69c17ce64d749d",
        "channel_point": "0078eb89e787a676afa940e36c8871fa0f7bb5a21ad00a886e12c59b83c16fe1:0",
        "chan_id": "0",
        "capacity": "2000000",
        "local_balance": "1997276",
        "remote_balance": "0",
        "commit_fee": "2724",
        "commit_weight": "600",
        "fee_per_kw": "3763",
        "unsettled_balance": "0",
        "total_satoshis_sent": "0",
        "total_satoshis_received": "0",
        "num_updates": "0",
        "pending_htlcs": [
        ],
        "csv_delay": 240,
        "private": false,
        "initiator": true
    },

I will send now the full encrypted logs. Common feature of all these channels in logs look like `...too-long-mempool-chain, too many descendants...`

**Comment by wpaulino** [comment] 2019-03-22 19:02
Is the channel in your graph? A 0 chan_id would point to the graph not knowing of the channel.

**Comment by wpaulino** [comment] 2019-03-22 19:03
> Common feature of all these channels in logs look like ...too-long-mempool-chain, too many descendants...

This is because you keep opening channels with unconfirmed outputs. `bitcoind` has restrictions on how many of these you can broadcast to prevent spam attacks.

**Comment by LNBIG-COM** [comment] 2019-03-22 19:06
But why these channels are not into pendingchannels? I thought that listchannels shows only confirmed non-pending channels...

**Comment by LNBIG-COM** [comment] 2019-03-22 19:07
> Is the channel in your graph? A 0 chan_id would point to the graph not knowing of the channel.

No there. I checked right now.
Do you need the full logs and dumps of commands?

**Comment by LNBIG-COM** [comment] 2019-03-22 19:09
If you need logs & dumps you can get here:

https://drive.google.com/open?id=1kJbq08cRaTNudOAznBrmBOdbNAXO6LZj

**Comment by wpaulino** [comment] 2019-03-22 19:10
The channel is confirmed and was included in your graph at the time of creation. It's most likely not in your graph anymore due to it being a zombie channel. This means there haven't been any graph updates to either edge within the past 2 weeks. We do this to keep a lively routing table.

**Comment by LNBIG-COM** [comment] 2019-03-22 19:17
I checked all nodes. I have only there two same channels only

> The channel is confirmed and was included in your graph at the time of creation. It's most likely not in your graph anymore due to it being a zombie channel. This means there haven't been any graph updates to either edge within the past 2 weeks. We do this to keep a lively routing table.

So can i force-close this channel and will get funds back during 2016 blocks. Right?

**Comment by wpaulino** [comment] 2019-03-22 19:27
> So can i force-close this channel and will get funds back during 2016 blocks. Right?

Correct.

Will be fixed by https://github.com/lightningnetwork/lnd/pull/2824.

**Comment by LNBIG-COM** [comment] 2019-03-22 20:32
Thanks!
I did force closing and see both transactions!

P.S. In my first message i did mistake - the second channel dump was duplicated from first one
Now i corrected it

**Closed** 2019-03-27 14:29 UTC
