### ISSUE TITLE
Channel stuck in "opening" state with more than 1000 confirmations

### ISSUE THREAD

**Issue by danbadjar** [lightningnetwork/lnd#3423] opened 2019-08-21 12:34 UTC
### Background

Hello,
I'm running lnd-0.7.1 and I have a remote peer that has opened a channel with me but the channel is stuck in "opening" state. The funding tx has more than 1000 confirmations.
I've stopped and started lnd several times but this doesn't  solve the issue.

If you have some ideas about how to solve this problem I would be grateful. Thanks

The remote peer is: 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e

```
lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e",
                "channel_point": "1e643a835a9d1b0d2d0066bfaec516e2f8c282f8968dc74c12c2e430c8be9721:23",
                "capacity": "309735",
                "local_balance": "0",
                "remote_balance": "305304",
                "local_chan_reserve_sat": "3098",
                "remote_chan_reserve_sat": "3097"
            },
            "confirmation_height": 0,
            "commit_fee": "4431",
            "commit_weight": "552",
            "fee_per_kw": "6121"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}
```

And in my logs I find:
```
lnd.log.13.gz:2019-08-06 08:42:54.658 [INF] FNDG: Recv'd fundingRequest(amt=0.00309735 BTC, push=0 mSAT, delay=144, pendingId=b06f0142f557b6a0858645561cfc74912a4ff8b16843d19b6cc736d565d35c90) from peer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e)
lnd.log.13.gz:2019-08-06 08:42:57.888 [INF] FNDG: Cancelling funding reservation for node_key=032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e, chan_id=b06f0142f557b6a0858645561cfc74912a4ff8b16843d19b6cc736d565d35c90
lnd.log.13.gz:2019-08-06 08:42:57.927 [ERR] FNDG: Received funding error from 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e: Channel open canceled by us
lnd.log.13.gz:2019-08-06 08:57:17.077 [INF] FNDG: Recv'd fundingRequest(amt=0.00309735 BTC, push=0 mSAT, delay=144, pendingId=e53bdbee88c56a3904712c0832c9c48c3b05f81d200fac3626da741b0336183b) from peer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e)
lnd.log.13.gz:2019-08-06 08:57:17.997 [INF] FNDG: Cancelling funding reservation for node_key=032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e, chan_id=e53bdbee88c56a3904712c0832c9c48c3b05f81d200fac3626da741b0336183b
lnd.log.13.gz:2019-08-06 08:57:17.997 [ERR] FNDG: Received funding error from 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e: Channel open canceled by us
lnd.log.13.gz:2019-08-06 09:10:36.650 [INF] FNDG: Recv'd fundingRequest(amt=0.00309735 BTC, push=0 mSAT, delay=144, pendingId=a008e5877af3b3dddb860208574437eb8db6e158efa155de71115abdffca21bb) from peer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e)
lnd.log.13.gz:2019-08-06 09:10:37.761 [INF] FNDG: Cancelling funding reservation for node_key=032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e, chan_id=a008e5877af3b3dddb860208574437eb8db6e158efa155de71115abdffca21bb
lnd.log.13.gz:2019-08-06 09:10:37.762 [ERR] FNDG: Received funding error from 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e: Channel open canceled by us
lnd.log.13.gz:2019-08-06 09:19:38.039 [INF] FNDG: Recv'd fundingRequest(amt=0.00309735 BTC, push=0 mSAT, delay=144, pendingId=4d66c8793f81108006d468306e839a33f6ec508277404b04f2368988e660195a) from peer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e)
lnd.log.13.gz:2019-08-06 09:19:38.960 [INF] FNDG: Cancelling funding reservation for node_key=032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e, chan_id=4d66c8793f81108006d468306e839a33f6ec508277404b04f2368988e660195a
lnd.log.13.gz:2019-08-06 09:19:38.960 [ERR] FNDG: Received funding error from 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e: Channel open canceled by us
lnd.log.13.gz:2019-08-06 13:21:43.406 [INF] FNDG: Recv'd fundingRequest(amt=0.00309735 BTC, push=0 mSAT, delay=144, pendingId=2edd969de497c05236fe5d951b9c27372cd844f5f4b565f457b6185b90e63b8c) from peer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e)
lnd.log.13.gz:2019-08-06 13:21:44.542 [INF] FNDG: Cancelling funding reservation for node_key=032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e, chan_id=2edd969de497c05236fe5d951b9c27372cd844f5f4b565f457b6185b90e63b8c
lnd.log.13.gz:2019-08-06 13:21:44.542 [ERR] FNDG: Received funding error from 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e: Channel open canceled by us
```

Maybe other useful infos:
```
2019-08-20 11:28:05.760 [INF] SRVR: Established connection to: 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e@203.150.177.97:9735
2019-08-20 11:28:05.760 [INF] SRVR: Finalizing connection to 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e@203.150.177.97:9735, inbound=false
2019-08-20 11:28:05.977 [INF] PEER: NodeKey(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e) loading ChannelPoint(1e643a835a9d1b0d2d0066bfaec516e2f8c282f8968dc74c12c2e430c8be9721:23)
2019-08-20 11:28:05.980 [INF] SRVR: Negotiated chan series queries with 032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e
2019-08-20 11:28:05.980 [INF] DISC: Creating new GossipSyncer for peer=032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e
2019-08-20 11:28:06.695 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying new update horizon: start=2019-08-19 11:28:05 +0200 CEST, end=2155-09-25 16:56:20 +0100 CET, backlog_size=90646
2019-08-20 11:46:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=2019-08-20 11:46:07.611687747 +0200 CEST m=+132318.159411899, end=2155-09-26 17:14:22.611687747 +0100 CET m=+4295099613.159411899)
2019-08-20 12:06:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
2019-08-21 01:06:07.612 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): requesting new chans from height=0 and 4294967295 blocks after
2019-08-21 01:06:10.990 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): buffering chan range reply of size=0
2019-08-21 01:06:10.991 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): filtering through 0 chans
2019-08-21 01:06:10.991 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): remote peer has no new chans
2019-08-21 01:26:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=2019-08-21 01:26:07.611699422 +0200 CEST m=+181518.159423579, end=2155-09-27 06:54:22.611699422 +0100 CET m=+4295148813.159423579)
2019-08-21 01:46:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
2019-08-21 05:26:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=2019-08-21 05:26:07.611736757 +0200 CEST m=+195918.159460945, end=2155-09-27 10:54:22.611736757 +0100 CET m=+4295163213.159460945)
2019-08-21 05:46:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
2019-08-21 07:26:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=2019-08-21 07:26:07.611703157 +0200 CEST m=+203118.159427354, end=2155-09-27 12:54:22.611703157 +0100 CET m=+4295170413.159427354)
2019-08-21 08:06:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
2019-08-21 08:26:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=2019-08-21 08:26:07.61171721 +0200 CEST m=+206718.159441389, end=2155-09-27 13:54:22.61171721 +0100 CET m=+4295174013.159441389)
2019-08-21 10:26:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
2019-08-21 13:26:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=2019-08-21 13:26:07.611760061 +0200 CEST m=+224718.159484252, end=2155-09-27 18:54:22.611760061 +0100 CET m=+4295192013.159484252)
2019-08-21 13:46:07.611 [INF] DISC: GossipSyncer(032260c3b64b471b7eb0630b4af5d07ca94ff4e759573cbbe1bfb25845c375ed6e): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
```

### Your environment

lnd-0.7.1
linux
bitcoind-0.18.1

### Expected behaviour

The channel should go in "active" state after 3 confirmations

**Comment by cfromknecht** [comment] 2019-08-22 00:06
not much we can do here, the remote party messed up the funding transaction so many of the commitment transactions stemming from it are borked. your node will forget about it after a week tho since it never thinks the channel confirmed.

**Comment by Roasbeef** [comment] 2019-08-22 07:59
Closing as the initiator made an invalid funding transaction. At the responder you have no balance so the channel will be forgotten.

**Closed by Roasbeef** 2019-08-22 07:59 UTC
